import Link from 'next/link'
import BrandLogo from '../BrandLogo'
import styles from './funcionalidades.module.css'

export const metadata={title:'Funcionalidades | Comercio Lleno',description:'Conocé las funciones de Comercio Lleno: ventas, stock, ARCA, Mercado Pago, presupuestos, caja, reportes, IA y módulos por tipo de negocio.',alternates:{canonical:'https://comerciolleno.com/funcionalidades'}}

type Feature={title:string;body:string;tag?:string}
type Section={id:string;eyebrow:string;title:string;intro:string;features:Feature[]}
const sections:Section[]=[
  {id:'ventas',eyebrow:'OPERACIÓN DIARIA',title:'Ventas y punto de venta',intro:'Un flujo rápido para cobrar desde mostrador, celular o PC, con lo necesario a mano y sin convertir una venta simple en un trámite.',features:[
    {title:'Nueva venta rápida',body:'Buscá por nombre o código de barras, sumá productos y cobrá en pocos pasos.'},{title:'Múltiples medios de pago',body:'Efectivo, débito, crédito, transferencia, billeteras y Mercado Pago. También podés dividir un pago.'},{title:'Presupuestos',body:'Armá, guardá e imprimí presupuestos con total y detalle sin descontar stock, mover caja ni declarar nada en ARCA.',tag:'NUEVO'},{title:'Precio mayorista automático',body:'Definí desde cuántas unidades querés aplicar el precio mayorista de cada producto.'},{title:'Descuentos',body:'Aplicá descuentos por porcentaje o importe y configurá el límite permitido para el equipo.'},{title:'Cliente en la venta',body:'Asociá una persona o empresa a la operación para mantener trazabilidad y consultar su historial.'},{title:'Venta sin facturar en el momento',body:'Registrá una venta interna cuando corresponda y mantené separado el flujo fiscal.'},{title:'Uso desde celular',body:'La venta está pensada para funcionar también con una mano en pantallas chicas.'}]},
  {id:'productos',eyebrow:'CATÁLOGO E INVENTARIO',title:'Productos y stock',intro:'Cargá el catálogo una vez y mantené precio, costo, stock y movimientos ordenados.',features:[
    {title:'Categorías',body:'Creá categorías, filtrá el catálogo y encontrá más rápido lo que necesitás.',tag:'NUEVO'},{title:'Orden por fecha de carga',body:'Identificá los últimos productos incorporados o revisá los más antiguos.'},{title:'Importación masiva',body:'Importá productos por planilla y recibí una confirmación con la cantidad real procesada.'},{title:'Stock mínimo y objetivo',body:'Definí niveles de reposición y detectá faltantes antes de quedarte sin mercadería.'},{title:'Historial de stock',body:'Seguí ingresos, egresos, compras, ventas, devoluciones y ajustes.'},{title:'Código de barras',body:'Trabajá con lectores USB, scanner desde el celular o búsqueda manual.'},{title:'Precios minorista y mayorista',body:'Guardá ambos precios en el mismo producto y dejá que el POS elija según la cantidad configurada.'},{title:'Control de venta sin stock',body:'Elegí si el sistema debe bloquear cantidades que superan la disponibilidad.'}]},
  {id:'fiscal',eyebrow:'ARGENTINA',title:'Facturación electrónica ARCA',intro:'La facturación está integrada al flujo de venta para evitar cargar la misma operación dos veces.',features:[
    {title:'Emisión desde la venta',body:'Con el certificado y punto de venta configurados, emití comprobantes sin salir de Comercio Lleno.'},{title:'CAE y datos fiscales',body:'El resultado fiscal queda asociado a la venta y al ticket.'},{title:'Estado de conexión',body:'Visualizá si ARCA está disponible antes de cerrar una operación.'},{title:'Separación fiscal',body:'Presupuestos y operaciones no fiscales permanecen fuera del envío a ARCA.'},{title:'Configuración guiada',body:'Centralizá certificado, punto de venta y estado de la integración desde Configuración.'}]},
  {id:'mercadopago',eyebrow:'COBROS',title:'Mercado Pago',intro:'Conectá la cuenta del comercio y elegí la modalidad que mejor se adapta al mostrador.',features:[
    {title:'Point integrado',body:'Enviá el importe al dispositivo Point vinculado y esperá la confirmación antes de cerrar la venta.'},{title:'QR físico',body:'Vinculá el QR estático pegado en tu caja para que Comercio Lleno cargue el importe sobre ese mismo código.',tag:'NUEVO'},{title:'Caja QR de Mercado Pago',body:'Si todavía no tenés una caja QR integrada, el sistema queda preparado para crearla sobre una sucursal de Mercado Pago.'},{title:'Estado de cobro',body:'La venta no se finaliza hasta recibir un resultado confirmado del proveedor.'},{title:'Cancelación y seguimiento',body:'Controlá operaciones pendientes y evitá duplicar un cobro cuando el estado todavía no está claro.'}]},
  {id:'caja',eyebrow:'DINERO Y CONTROL',title:'Caja y movimientos',intro:'Sabé qué entró, qué salió y qué debería haber al cierre.',features:[
    {title:'Caja manual',body:'Abrí con un monto inicial y cerrá con recuento para comparar la diferencia.'},{title:'Caja automática',body:'Para negocios que prefieren vender sin realizar apertura y cierre todos los días.'},{title:'Ingresos y egresos',body:'Registrá movimientos que no provienen de una venta y mantenelos separados.'},{title:'Resumen por medio de pago',body:'Revisá cuánto ingresó por efectivo, tarjetas, transferencia y otros medios.'},{title:'Presupuestos fuera de caja',body:'Los presupuestos se muestran como documentos, nunca como dinero cobrado.'}]},
  {id:'gestion',eyebrow:'ADMINISTRACIÓN',title:'Clientes, proveedores y compras',intro:'Concentrá la información operativa que normalmente termina repartida entre cuadernos, chats y planillas.',features:[
    {title:'Clientes',body:'Nombre, teléfono, email, CUIT y relación con ventas.'},{title:'Cuentas corrientes',body:'Seguí saldos y movimientos cuando vendés con pago posterior.'},{title:'Proveedores',body:'Registrá proveedores y mantené referencias para compras y reposición.'},{title:'Compras',body:'Cargá mercadería adquirida y actualizá el stock de forma trazable.'},{title:'Devoluciones',body:'Registrá devoluciones conservando la relación con la operación original.'},{title:'Promociones',body:'Aplicá descuentos porcentuales a productos y mantené el precio original para restaurarlo.'}]},
  {id:'reportes',eyebrow:'DECISIONES',title:'Reportes y rentabilidad',intro:'Convertí los movimientos cotidianos en información entendible para decidir.',features:[
    {title:'Ventas por período',body:'Compará operaciones, importes y evolución entre distintos días.'},{title:'Medios de pago',body:'Entendé cómo te están pagando y cuánto representa cada medio.'},{title:'Productos vendidos',body:'Detectá productos con mayor salida y categorías que mueven más volumen.'},{title:'Rentabilidad',body:'Usá costo y precio para seguir márgenes y revisar qué conviene vender.'},{title:'Stock crítico',body:'Priorizá reposición según mínimos configurados.'},{title:'Exportación',body:'Llevá información a planillas cuando necesites analizarla o compartirla fuera del sistema.'}]},
  {id:'ia',eyebrow:'ASISTENTE',title:'Inteligencia artificial',intro:'Consultá el negocio con lenguaje natural sin tener que aprender a armar un reporte.',features:[
    {title:'Preguntas sobre ventas',body:'Pedí resúmenes y comparaciones usando los datos disponibles del comercio.'},{title:'Consultas de stock',body:'Encontrá faltantes, productos y tendencias sin recorrer listados largos.'},{title:'Contexto del comercio',body:'El asistente responde sobre la operación del tenant autenticado, no sobre datos de otros comercios.'},{title:'Ayuda humana',body:'Cuando necesitás soporte, el sistema contempla un canal separado para escalar la consulta.'}]},
  {id:'movil',eyebrow:'100% ONLINE',title:'Celular, PC y dispositivos',intro:'El mismo comercio, los mismos datos y una interfaz que se adapta a cómo trabajás.',features:[
    {title:'Responsive mobile-first',body:'Operá desde el teléfono sin depender de una PC en el mostrador.'},{title:'Versión de escritorio',body:'Usá más espacio cuando trabajás desde notebook o computadora.'},{title:'Impresoras 58 y 80 mm',body:'Configurá tamaño de ticket y flujo de impresión.'},{title:'Scanner USB',body:'Lectores de código funcionan como entrada rápida en la búsqueda de productos.'},{title:'Modo offline',body:'El sistema contempla continuidad operativa y sincronización para flujos compatibles cuando la conexión falla.'}]},
  {id:'modulos',eyebrow:'ACTIVÁ SOLO LO QUE USÁS',title:'Módulos por tipo de negocio',intro:'El sistema base se mantiene simple. Las funciones específicas aparecen únicamente cuando el titular decide activarlas.',features:[
    {title:'Venta fraccionada',body:'Habilitá productos por kilo, gramo, litro o mililitro y cantidades con decimales.',tag:'NUEVO'},{title:'Balanza',body:'Configurá lectura directa por USB/Serial en navegadores compatibles o trabajá con etiquetas/códigos generados por la balanza.',tag:'NUEVO'},{title:'Indumentaria',body:'Agregá variantes por talle y color, stock mínimo por variante, ubicación y estado del producto.',tag:'NUEVO'},{title:'Ticket de cambio',body:'Dentro del módulo de indumentaria, prepará un comprobante de cambio separado del comprobante fiscal.',tag:'NUEVO'},{title:'Configuraciones por comercio',body:'Cada tenant puede activar módulos y ajustar sus parámetros sin alterar la experiencia de los demás clientes.'}]},
  {id:'seguridad',eyebrow:'MULTI-TENANT',title:'Usuarios, sucursales y seguridad',intro:'Cada comercio trabaja dentro de su propio espacio, con permisos para reducir errores operativos.',features:[
    {title:'Usuarios y roles',body:'Separá permisos de venta, reportes, stock, caja, compras y administración.'},{title:'Sucursales',body:'Organizá la operación por sucursal y mantené el alcance de cada usuario.'},{title:'Sesiones autenticadas',body:'Las operaciones sensibles requieren una sesión válida y permisos del comercio.'},{title:'Historial y trazabilidad',body:'Las acciones operativas importantes conservan referencias para poder revisar qué pasó.'}]},
]

function Header(){return <header className={styles.header}><Link href="/" className={styles.brand}><BrandLogo size={38}/></Link><nav><Link href="/funcionalidades" className={styles.activeNav}>Funcionalidades</Link><Link href="/soluciones">Soluciones</Link><Link href="/#precio">Precio</Link><Link href="/terminos">Legales</Link></nav><div className={styles.actions}><Link href="/redesign/access" className={styles.login}>Ingresar</Link><Link href="/prueba-gratis" className={styles.trial}>30 DÍAS GRATIS</Link></div></header>}

export default function FuncionalidadesPage(){return <main className={styles.page}><Header/><section className={styles.hero}><div><span className={styles.eyebrow}>TODO LO QUE PODÉS HACER</span><h1>Un sistema simple por fuera.<br/><em>Completo por dentro.</em></h1><p>Comercio Lleno concentra ventas, caja, stock, facturación y gestión en una sola herramienta. Empezás con lo esencial y activás módulos cuando tu negocio los necesita.</p><div className={styles.heroCta}><Link href="/prueba-gratis">PROBAR 30 DÍAS GRATIS →</Link><span>Sin tarjeta · después $14.900/mes</span></div></div><aside><div><small>USALO EN</small><b>Celular + PC</b></div><div><small>FACTURACIÓN</small><b>ARCA</b></div><div><small>COBROS</small><b>Mercado Pago</b></div><div><small>EXTRAS</small><b>Módulos activables</b></div></aside></section><div className={styles.mobileIndex}>{sections.map(section=><a key={section.id} href={`#${section.id}`}>{section.title}</a>)}</div><div className={styles.content}><aside className={styles.side}><span>FUNCIONALIDADES</span>{sections.map(section=><a key={section.id} href={`#${section.id}`}>{section.title}</a>)}<Link href="/prueba-gratis">Empezar gratis →</Link></aside><div className={styles.sections}>{sections.map((section,index)=><section className={styles.section} id={section.id} key={section.id}><div className={styles.sectionTop}><div><span>{String(index+1).padStart(2,'0')} · {section.eyebrow}</span><h2>{section.title}</h2></div><p>{section.intro}</p></div><div className={styles.grid}>{section.features.map(feature=><article key={feature.title}><div>{feature.tag&&<span className={styles.tag}>{feature.tag}</span>}<h3>{feature.title}</h3><p>{feature.body}</p></div><i>↗</i></article>)}</div></section>)}</div></div><section className={styles.final}><span>30 DÍAS PARA USARLO DE VERDAD</span><h2>Probalo con tu comercio.<br/>Después decidís.</h2><p>No necesitás tarjeta para empezar. Durante 30 días podés recorrer el sistema y validar si encaja con tu forma de trabajar.</p><Link href="/prueba-gratis">CREAR MI CUENTA GRATIS →</Link><small>Después $14.900 por mes · cancelás cuando quieras.</small></section><footer className={styles.footer}><div><BrandLogo size={36}/><span>Comercio Lleno · Llena Group</span></div><nav><Link href="/terminos">Términos</Link><Link href="/politica-de-privacidad">Privacidad</Link><Link href="/politica-de-cookies">Cookies</Link><Link href="/eliminar-cuenta">Eliminar cuenta</Link></nav></footer></main>}
