export type Solution = {
  slug: string
  eyebrow: string
  title: string
  accent: string
  description: string
  intro: string
  painTitle: string
  pains: string[]
  uses: string[]
  searchTerms: string[]
  faq: { question: string; answer: string }[]
  heroImage: string
  heroAlt: string
  secondaryImage: string
  secondaryAlt: string
  photoCredit: string
  layout: 'photo-right' | 'photo-left' | 'editorial' | 'gallery' | 'system-first'
  theme: 'orange' | 'violet' | 'green' | 'pink' | 'blue'
  sceneTitle: string
  sceneText: string
  scenePoints: string[]
  systemTitle: string
  systemText: string
  productExamples: { name: string; detail: string; stock: string }[]
  stat: { value: string; label: string }
}

const pexels = (id: number, width = 1500) => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=${width}`

export const solutions: Solution[] = [
  {
    slug: 'sistema-para-kioscos',
    eyebrow: 'SISTEMA PARA KIOSCOS',
    title: 'Vendé rápido incluso cuando',
    accent: 'hay fila en el mostrador.',
    description: 'Sistema POS para kioscos con ventas, stock, caja, lector de códigos, impresora térmica y seguimiento desde el celular.',
    intro: 'En un kiosco cada segundo cuenta. Comercio Lleno concentra cobro, productos, stock y caja en una pantalla pensada para atender sin frenar la fila.',
    painTitle: 'Velocidad en el mostrador sin perder control.',
    pains: ['Muchos productos y precios que cambian seguido', 'Picos de venta donde no hay tiempo para buscar', 'Faltantes que aparecen justo cuando el cliente pide', 'Caja difícil de seguir cuando trabajan varias personas'],
    uses: ['Venta rápida desde mostrador', 'Scanner de códigos de barra', 'Control de stock y productos', 'Caja y cierres', 'Facturación electrónica ARCA', 'Consulta desde el celular'],
    searchTerms: ['sistema para kioscos', 'programa para kiosco', 'pos para kiosco', 'control de stock kiosco'],
    faq: [
      {question:'¿Sirve para un kiosco con muchos productos?',answer:'Sí. Podés buscar por nombre o código y trabajar con lector para acelerar la atención.'},
      {question:'¿Puedo controlar el kiosco desde el celular?',answer:'Sí. La experiencia móvil permite consultar y operar funciones clave del comercio.'},
      {question:'¿Incluye facturación electrónica?',answer:'Sí. La facturación ARCA se habilita después de completar la configuración fiscal correspondiente.'},
    ],
    heroImage: pexels(12935045),
    heroAlt: 'Cajera usando un punto de venta moderno en un comercio',
    secondaryImage: pexels(8410989),
    secondaryAlt: 'Interior de un kiosco con productos y clientes',
    photoCredit: 'Fotos de iMin Technology y Ahmet Hezretov · Pexels',
    layout: 'photo-right',
    theme: 'orange',
    sceneTitle: 'Pensado para el momento en que se llena el mostrador.',
    sceneText: 'La búsqueda, el código de barras y el cobro quedan en el mismo recorrido. El empleado atiende; el sistema registra el resto.',
    scenePoints: ['Escanear y sumar productos sin cambiar de pantalla', 'Cobrar en efectivo, tarjeta, transferencia o billetera', 'Descontar stock con cada venta', 'Consultar caja y ventas desde el teléfono'],
    systemTitle: 'Una venta de kiosco, vista desde Comercio Lleno.',
    systemText: 'Productos cotidianos, cantidades, stock y total en una interfaz que prioriza la operación.',
    productExamples: [
      {name:'Coca-Cola 500 ml',detail:'Bebidas',stock:'24 u.'},
      {name:'Alfajor triple',detail:'Golosinas',stock:'18 u.'},
      {name:'Papas clásicas 90 g',detail:'Snacks',stock:'9 u.'},
      {name:'Energizante 473 ml',detail:'Bebidas',stock:'12 u.'},
    ],
    stat:{value:'1 flujo',label:'producto → cobro → stock'},
  },
  {
    slug: 'sistema-para-almacenes',
    eyebrow: 'SISTEMA PARA ALMACENES',
    title: 'Ordená ventas, caja y stock',
    accent: 'sin complicar el mostrador.',
    description: 'Sistema para almacenes y autoservicios con punto de venta, control de stock, caja, facturación ARCA y gestión desde computadora o celular.',
    intro: 'Para pasar de la libreta o la planilla a un sistema sin volver más lenta la atención. El almacén sigue funcionando como siempre, pero con información ordenada.',
    painTitle: 'Que la información no quede repartida entre papeles.',
    pains: ['Precios y stock anotados en lugares distintos', 'Difícil saber cuánto se vendió durante el día', 'Productos que se terminan sin aviso', 'La información queda en el local cuando el dueño se va'],
    uses: ['Ventas y caja diaria', 'Productos y precios', 'Control de stock', 'Scanner de códigos', 'Facturación ARCA', 'Seguimiento desde celular'],
    searchTerms: ['sistema para almacenes', 'programa para almacén', 'sistema de ventas almacén', 'stock para almacén'],
    faq: [
      {question:'¿Tengo que cargar todo antes de empezar?',answer:'No. Podés crear el comercio y completar la configuración de forma progresiva.'},
      {question:'¿Funciona con lector de códigos?',answer:'Sí. Comercio Lleno contempla lectores USB y herramientas móviles de escaneo.'},
      {question:'¿Puedo ver las ventas desde afuera del local?',answer:'Sí. La versión móvil está pensada para consultar y gestionar el negocio a distancia.'},
    ],
    heroImage: pexels(12935050),
    heroAlt: 'Cajera pesando frutas junto a un sistema de punto de venta',
    secondaryImage: pexels(16211537),
    secondaryAlt: 'Góndolas de almacén con gran variedad de productos',
    photoCredit: 'Fotos de iMin Technology y ha ha · Pexels',
    layout: 'photo-left',
    theme: 'green',
    sceneTitle: 'Del mostrador a la reposición, sin planillas paralelas.',
    sceneText: 'Cada venta alimenta la información que después necesitás para mirar caja, revisar productos y preparar la próxima compra.',
    scenePoints: ['Buscar o escanear artículos', 'Registrar precios y cantidades', 'Ver existencias antes de reponer', 'Consultar el día desde computadora o celular'],
    systemTitle: 'El almacén en una pantalla que se entiende rápido.',
    systemText: 'Productos de alta rotación, stock visible y caja integrada para trabajar sin saltar entre sistemas.',
    productExamples: [
      {name:'Yerba mate 1 kg',detail:'Almacén',stock:'14 u.'},
      {name:'Leche entera 1 L',detail:'Lácteos',stock:'21 u.'},
      {name:'Fideos secos 500 g',detail:'Almacén',stock:'32 u.'},
      {name:'Aceite girasol 900 ml',detail:'Almacén',stock:'8 u.'},
    ],
    stat:{value:'Todo junto',label:'venta + caja + stock'},
  },
  {
    slug: 'sistema-para-ferreterias',
    eyebrow: 'SISTEMA PARA FERRETERÍAS',
    title: 'Encontrá cada producto y',
    accent: 'mantené el stock bajo control.',
    description: 'Software para ferreterías con ventas, productos, control de stock, caja, facturación electrónica y acceso desde celular.',
    intro: 'Cuando hay cientos o miles de referencias, vender bien también significa encontrar rápido una pieza y saber si realmente queda.',
    painTitle: 'Un catálogo grande no debería volver lenta la atención.',
    pains: ['Muchas referencias, medidas y variantes', 'Stock imposible de recordar de memoria', 'Búsquedas lentas cuando el cliente está esperando', 'Reposición y caja separadas de la venta'],
    uses: ['Buscador de productos', 'Stock por artículo', 'Venta desde POS', 'Lectores de códigos', 'Caja y reportes', 'Facturación ARCA'],
    searchTerms: ['sistema para ferreterías', 'software ferretería', 'programa de stock ferretería', 'pos ferretería'],
    faq: [
      {question:'¿Puedo manejar muchos productos?',answer:'Sí. El sistema permite buscar, vender y controlar stock en catálogos comerciales amplios.'},
      {question:'¿Sirve para controlar caja?',answer:'Sí. Ventas y caja forman parte del mismo flujo operativo.'},
      {question:'¿Tiene prueba gratis?',answer:'Sí. Podés probar Comercio Lleno durante 14 días sin tarjeta.'},
    ],
    heroImage: pexels(12340557),
    heroAlt: 'Exhibición de grifería y artículos de ferretería en estanterías',
    secondaryImage: pexels(14458537),
    secondaryAlt: 'Empleado de comercio organizando productos en estantes',
    photoCredit: 'Fotos de Mochammad Algi y Nina zeynep güler · Pexels',
    layout: 'editorial',
    theme: 'blue',
    sceneTitle: 'Encontrar una mecha o un tarugo no debería depender de la memoria.',
    sceneText: 'El buscador y el stock acompañan la conversación con el cliente. Menos ida y vuelta al depósito; más información delante del mostrador.',
    scenePoints: ['Buscar por nombre, código o descripción', 'Ver existencias mientras atendés', 'Registrar ventas y medios de pago', 'Detectar artículos que necesitan reposición'],
    systemTitle: 'Un catálogo ferretero dentro del mismo POS.',
    systemText: 'La captura de operación muestra referencias, familia y stock sin perder de vista la venta.',
    productExamples: [
      {name:'Mecha widia 8 mm',detail:'Perforación',stock:'17 u.'},
      {name:'Tarugo nylon N°8',detail:'Fijaciones',stock:'86 u.'},
      {name:'Cinta teflón 12 mm',detail:'Plomería',stock:'29 u.'},
      {name:'Pinza universal 8”',detail:'Herramientas',stock:'6 u.'},
    ],
    stat:{value:'Miles',label:'de referencias, un buscador'},
  },
  {
    slug: 'sistema-para-locales-de-ropa',
    eyebrow: 'SISTEMA PARA LOCALES DE ROPA',
    title: 'Vendé con una experiencia',
    accent: 'tan prolija como tu local.',
    description: 'Sistema de ventas para locales de ropa con stock, caja, productos, facturación electrónica ARCA y gestión móvil.',
    intro: 'La venta puede ser simple aunque el catálogo cambie todo el tiempo. Comercio Lleno reúne productos, stock, caja y seguimiento del negocio.',
    painTitle: 'Información clara para vender y reponer mejor.',
    pains: ['Stock que cambia durante todo el día', 'Productos y variantes difíciles de seguir', 'Caja y ventas que después hay que conciliar', 'Poca visibilidad cuando el dueño no está'],
    uses: ['Ventas desde mostrador', 'Productos y stock', 'Caja diaria', 'Reportes', 'Facturación ARCA', 'Panel desde celular'],
    searchTerms: ['sistema para local de ropa', 'software para indumentaria', 'pos local de ropa', 'control de stock ropa'],
    faq: [
      {question:'¿Puedo usarlo desde el celular?',answer:'Sí. Comercio Lleno tiene una experiencia móvil para operar y consultar el negocio.'},
      {question:'¿Puedo empezar sin configurar ARCA?',answer:'Sí. La configuración fiscal se puede completar después desde Configuración.'},
      {question:'¿Cuánto dura la prueba?',answer:'La prueba gratuita dura 14 días y no requiere tarjeta.'},
    ],
    heroImage: pexels(5864244),
    heroAlt: 'Clientas recorriendo un local de ropa moderno',
    secondaryImage: pexels(4855334),
    secondaryAlt: 'Atención humana en el mostrador de una tienda',
    photoCredit: 'Fotos de Rachel Claire y cottonbro studio · Pexels',
    layout: 'gallery',
    theme: 'pink',
    sceneTitle: 'El sistema acompaña al equipo, no compite con la atención.',
    sceneText: 'La experiencia está pensada para que el mostrador siga siendo humano mientras productos, ventas y caja quedan registrados.',
    scenePoints: ['Buscar prendas y productos rápido', 'Consultar disponibilidad', 'Cobrar y registrar la venta', 'Seguir el día desde el celular'],
    systemTitle: 'Productos, stock y venta en el mismo recorrido.',
    systemText: 'Una vista limpia para mantener el foco en la atención y dejar la información comercial ordenada.',
    productExamples: [
      {name:'Remera algodón',detail:'Indumentaria',stock:'12 u.'},
      {name:'Jean recto',detail:'Indumentaria',stock:'7 u.'},
      {name:'Buzo canguro',detail:'Indumentaria',stock:'9 u.'},
      {name:'Campera liviana',detail:'Temporada',stock:'5 u.'},
    ],
    stat:{value:'Desde el celu',label:'seguí ventas y operación'},
  },
  {
    slug: 'sistema-para-dieteticas',
    eyebrow: 'SISTEMA PARA DIETÉTICAS',
    title: 'Productos, stock y caja',
    accent: 'sin perder la esencia del local.',
    description: 'Sistema POS para dietéticas con control de productos, stock, ventas, caja, facturación ARCA y acceso desde celular.',
    intro: 'Una dietética combina muchas categorías, presentaciones y ritmos de rotación. Comercio Lleno ordena la operación sin convertirla en algo complejo.',
    painTitle: 'Que el stock deje de depender de la memoria.',
    pains: ['Gran variedad de productos y presentaciones', 'Reposición frecuente', 'Precios que necesitan actualización', 'Ventas y caja controladas por separado'],
    uses: ['Gestión de productos', 'Control de stock', 'POS de ventas', 'Caja y movimientos', 'Facturación electrónica', 'Seguimiento móvil'],
    searchTerms: ['sistema para dietética', 'programa para dietética', 'pos dietética', 'stock dietética'],
    faq: [
      {question:'¿Me ayuda a controlar faltantes?',answer:'Sí. El stock está integrado con productos y ventas para mantener una referencia actualizada.'},
      {question:'¿Puedo imprimir tickets?',answer:'Sí. Comercio Lleno contempla impresoras térmicas de 58 y 80 mm.'},
      {question:'¿Funciona online?',answer:'Sí. Es una plataforma web y cuenta con capacidades pensadas para continuidad operativa.'},
    ],
    heroImage: pexels(7262696),
    heroAlt: 'Interior de tienda de alimentos naturales con frascos y productos orgánicos',
    secondaryImage: pexels(7772129),
    secondaryAlt: 'Persona eligiendo productos naturales en una tienda',
    photoCredit: 'Fotos de Sarah Chai y Anna Tarazevich · Pexels',
    layout: 'photo-left',
    theme: 'green',
    sceneTitle: 'Una operación ordenada también puede sentirse cercana.',
    sceneText: 'Productos naturales, suplementos, snacks y otras categorías conviven en un catálogo que se puede buscar y controlar desde el mismo lugar.',
    scenePoints: ['Mantener productos y precios organizados', 'Ver stock disponible', 'Registrar ventas sin duplicar tareas', 'Controlar caja y movimientos'],
    systemTitle: 'El catálogo de la dietética, conectado a la venta.',
    systemText: 'Una vista operativa con categorías y existencias para decidir mejor qué reponer.',
    productExamples: [
      {name:'Granola artesanal 500 g',detail:'Cereales',stock:'10 u.'},
      {name:'Almendras 250 g',detail:'Frutos secos',stock:'16 u.'},
      {name:'Pasta de maní 400 g',detail:'Untables',stock:'8 u.'},
      {name:'Leche de almendras',detail:'Bebidas',stock:'13 u.'},
    ],
    stat:{value:'Stock visible',label:'para reponer a tiempo'},
  },
  {
    slug: 'sistema-para-pet-shops',
    eyebrow: 'SISTEMA PARA PET SHOPS',
    title: 'Muchas marcas y tamaños.',
    accent: 'Una sola operación.',
    description: 'Sistema de gestión para pet shops con punto de venta, stock, productos, caja, facturación ARCA y versión móvil.',
    intro: 'Alimentos, accesorios, higiene y presentaciones distintas pueden convivir sin que el control se vuelva manual. Comercio Lleno conecta venta, stock y caja.',
    painTitle: 'Más visibilidad del negocio, menos controles manuales.',
    pains: ['Muchas marcas y presentaciones', 'Reposición constante de alta rotación', 'Stock que se reparte entre góndola y depósito', 'Cierre de caja y ventas difíciles de revisar'],
    uses: ['Venta y caja', 'Catálogo de productos', 'Stock actualizado', 'Scanner de códigos', 'Facturación ARCA', 'Acceso desde celular'],
    searchTerms: ['sistema para pet shop', 'software pet shop', 'pos pet shop', 'control de stock pet shop'],
    faq: [
      {question:'¿Funciona con códigos de barra?',answer:'Sí. El sistema contempla lectores USB y herramientas de escaneo.'},
      {question:'¿Puedo usarlo en más de una sucursal?',answer:'El plan publicado actualmente incluye hasta 2 sucursales.'},
      {question:'¿Puedo probarlo antes de pagar?',answer:'Sí. La prueba es de 14 días sin tarjeta.'},
    ],
    heroImage: pexels(23692911),
    heroAlt: 'Clientes con un perro recorriendo una góndola de alimento en un pet shop',
    secondaryImage: pexels(796584),
    secondaryAlt: 'Pet shop con productos y accesorios para mascotas',
    photoCredit: 'Fotos de Ali Dashti y Maurício Mascaro · Pexels',
    layout: 'gallery',
    theme: 'violet',
    sceneTitle: 'Cuando una bolsa cambia de tamaño, el stock también tiene que entenderlo.',
    sceneText: 'Cada presentación puede vivir como un producto claro dentro del catálogo para que atender, cobrar y reponer sea más sencillo.',
    scenePoints: ['Encontrar alimento por marca o presentación', 'Ver stock de accesorios y consumibles', 'Escanear códigos en mostrador', 'Seguir ventas aunque no estés en el local'],
    systemTitle: 'El pet shop organizado por productos reales.',
    systemText: 'Presentaciones, categorías y stock visibles dentro de una interfaz pensada para vender.',
    productExamples: [
      {name:'Alimento adulto 15 kg',detail:'Perros',stock:'7 u.'},
      {name:'Piedras sanitarias 4 kg',detail:'Gatos',stock:'19 u.'},
      {name:'Correa reforzada M',detail:'Accesorios',stock:'11 u.'},
      {name:'Snack dental x7',detail:'Premios',stock:'15 u.'},
    ],
    stat:{value:'Más claro',label:'marca + presentación + stock'},
  },
  {
    slug: 'sistema-para-perfumerias',
    eyebrow: 'SISTEMA PARA PERFUMERÍAS',
    title: 'Un catálogo cuidado.',
    accent: 'Una gestión igual de prolija.',
    description: 'Sistema para perfumerías con ventas, stock, productos, caja, lector de códigos, facturación ARCA y gestión móvil.',
    intro: 'Cuidado personal, cosmética y perfumería suelen reunir productos muy parecidos entre sí. La búsqueda y el stock ayudan a que la atención siga siendo ágil.',
    painTitle: 'Un sistema a la altura de un catálogo amplio.',
    pains: ['Productos similares con muchas variantes', 'Precios que cambian con frecuencia', 'Stock difícil de controlar manualmente', 'Necesidad de revisar ventas sin estar en el local'],
    uses: ['Productos y precios', 'Venta rápida', 'Control de stock', 'Caja', 'Facturación electrónica', 'Consulta móvil'],
    searchTerms: ['sistema para perfumería', 'programa perfumería', 'pos perfumería', 'stock perfumería'],
    faq: [
      {question:'¿Tiene buscador de productos?',answer:'Sí. Podés buscar productos y trabajar con códigos de forma ágil.'},
      {question:'¿Puedo facturar con ARCA?',answer:'Sí. La facturación electrónica se integra después de completar la configuración fiscal.'},
      {question:'¿Necesito instalar un programa?',answer:'No para la operación principal: Comercio Lleno funciona desde el navegador.'},
    ],
    heroImage: pexels(7755536),
    heroAlt: 'Mujer en una tienda de belleza junto a productos cosméticos',
    secondaryImage: pexels(3735625),
    secondaryAlt: 'Productos de belleza y cuidado personal exhibidos en estantes',
    photoCredit: 'Fotos de RDNE Stock project y Polina Tankilevitch · Pexels',
    layout: 'editorial',
    theme: 'pink',
    sceneTitle: 'La experiencia del local puede seguir siendo visual y personal.',
    sceneText: 'El sistema queda detrás de la atención: organiza catálogo, existencias y caja sin transformar el mostrador en una oficina.',
    scenePoints: ['Buscar artículos parecidos sin confundirlos', 'Controlar existencias por producto', 'Registrar cobro y facturación', 'Seguir el negocio desde el celular'],
    systemTitle: 'Una vista limpia para un catálogo con muchas referencias.',
    systemText: 'Productos y stock visibles, con una interfaz que no compite con la atención al cliente.',
    productExamples: [
      {name:'Shampoo nutritivo 400 ml',detail:'Cabello',stock:'14 u.'},
      {name:'Crema facial hidratante',detail:'Skincare',stock:'8 u.'},
      {name:'Protector solar FPS 50',detail:'Cuidado',stock:'12 u.'},
      {name:'Perfume femenino 50 ml',detail:'Fragancias',stock:'5 u.'},
    ],
    stat:{value:'Catálogo claro',label:'menos confusiones al vender'},
  },
  {
    slug: 'control-de-stock-para-comercios',
    eyebrow: 'CONTROL DE STOCK PARA COMERCIOS',
    title: 'Sabé qué tenés antes de',
    accent: 'descubrirlo en el mostrador.',
    description: 'Control de stock online para comercios integrado con ventas, productos, caja, scanner y seguimiento desde celular.',
    intro: 'El stock sirve cuando está conectado con la operación. Comercio Lleno relaciona productos, existencias y ventas para reducir controles manuales.',
    painTitle: 'El stock deja de ser una planilla aparte.',
    pains: ['Faltantes detectados demasiado tarde', 'Stock anotado en distintos lugares', 'Diferencias entre lo vendido y lo disponible', 'Dificultad para consultar existencias fuera del local'],
    uses: ['Productos centralizados', 'Stock conectado con ventas', 'Búsqueda y códigos', 'Consulta móvil', 'Caja y ventas', 'Operación web'],
    searchTerms: ['control de stock para comercios', 'sistema de stock', 'programa de inventario comercio', 'stock online negocio'],
    faq: [
      {question:'¿El stock está separado de las ventas?',answer:'No. La propuesta es trabajar productos, ventas y existencias dentro del mismo sistema.'},
      {question:'¿Puedo consultar stock desde el celular?',answer:'Sí. La experiencia móvil permite consultar información comercial desde el teléfono.'},
      {question:'¿Sirve sólo para stock?',answer:'No. Comercio Lleno también incluye ventas, caja, facturación y otras herramientas.'},
    ],
    heroImage: pexels(31112244),
    heroAlt: 'Trabajadora organizando inventario en estanterías',
    secondaryImage: pexels(4481528),
    secondaryAlt: 'Equipo trabajando sobre inventario y productos en un depósito',
    photoCredit: 'Fotos de EqualStock IN y Tiger Lily · Pexels',
    layout: 'system-first',
    theme: 'blue',
    sceneTitle: 'El inventario tiene que responder una pregunta simple: ¿queda o no queda?',
    sceneText: 'La información de stock se vuelve útil cuando el equipo la puede consultar mientras vende y cuando el dueño la puede mirar desde afuera.',
    scenePoints: ['Existencias visibles por producto', 'Productos conectados con ventas', 'Búsqueda rápida de artículos', 'Consulta desde distintos dispositivos'],
    systemTitle: 'Una vista de stock para decidir sin adivinar.',
    systemText: 'Productos, categoría y existencia en una misma pantalla para detectar faltantes antes de que lleguen al mostrador.',
    productExamples: [
      {name:'Producto A',detail:'Alta rotación',stock:'4 u.'},
      {name:'Producto B',detail:'Reposición semanal',stock:'28 u.'},
      {name:'Producto C',detail:'Stock crítico',stock:'2 u.'},
      {name:'Producto D',detail:'Disponible',stock:'41 u.'},
    ],
    stat:{value:'Stock + venta',label:'una sola fuente de información'},
  },
  {
    slug: 'punto-de-venta-online',
    eyebrow: 'PUNTO DE VENTA ONLINE',
    title: 'Un POS para vender hoy y',
    accent: 'seguir el negocio después.',
    description: 'Punto de venta online para comercios en Argentina con ventas, stock, caja, ARCA, scanner, impresora térmica y acceso móvil.',
    intro: 'No es sólo una pantalla para cobrar. Comercio Lleno conecta el mostrador con stock, caja, facturación y seguimiento del negocio.',
    painTitle: 'El punto de venta como centro de la operación.',
    pains: ['Caja aislada del stock', 'Procesos duplicados para vender y facturar', 'Poca información cuando termina el turno', 'Dependencia de una única computadora'],
    uses: ['POS online', 'Caja y ventas', 'Productos y stock', 'Facturación ARCA', 'Impresora térmica y scanner', 'Acceso móvil'],
    searchTerms: ['punto de venta online', 'pos online argentina', 'sistema pos comercio', 'software punto de venta'],
    faq: [
      {question:'¿Qué necesito para usar el POS?',answer:'Podés comenzar desde un navegador y sumar lector, impresora y configuración fiscal cuando lo necesites.'},
      {question:'¿Tiene versión móvil?',answer:'Sí. Comercio Lleno incluye una experiencia móvil específica.'},
      {question:'¿Puedo probarlo gratis?',answer:'Sí. Tenés 14 días de prueba sin tarjeta.'},
    ],
    heroImage: pexels(34638901),
    heroAlt: 'Caja de comercio con pantalla táctil y lector en el mostrador',
    secondaryImage: pexels(12935074),
    secondaryAlt: 'Persona utilizando una pantalla táctil de punto de venta',
    photoCredit: 'Fotos de Jaykumar Bherwani e iMin Technology · Pexels',
    layout: 'system-first',
    theme: 'violet',
    sceneTitle: 'Cobrar es el principio, no el final del dato.',
    sceneText: 'Una venta puede actualizar stock, alimentar caja y quedar lista para facturación dentro del mismo recorrido.',
    scenePoints: ['Buscar o escanear productos', 'Elegir el medio de pago', 'Cobrar y facturar', 'Revisar el resultado del día'],
    systemTitle: 'El POS de Comercio Lleno, sin capas innecesarias.',
    systemText: 'Producto, cantidad, pago y total ocupan el centro de la experiencia.',
    productExamples: [
      {name:'Producto escaneado',detail:'Código 779…',stock:'18 u.'},
      {name:'Segundo producto',detail:'Venta actual',stock:'9 u.'},
      {name:'Producto agregado',detail:'Venta actual',stock:'22 u.'},
      {name:'Último artículo',detail:'Venta actual',stock:'6 u.'},
    ],
    stat:{value:'POS online',label:'desde navegador + celular'},
  },
  {
    slug: 'sistema-de-caja-para-comercios',
    eyebrow: 'SISTEMA DE CAJA PARA COMERCIOS',
    title: 'La caja conectada con',
    accent: 'lo que realmente vendés.',
    description: 'Sistema de caja para comercios con ventas, productos, stock, facturación electrónica y control desde computadora o celular.',
    intro: 'En lugar de cerrar el día comparando información de varios lados, Comercio Lleno reúne la venta y la caja dentro del mismo entorno.',
    painTitle: 'Menos conciliación manual al final del día.',
    pains: ['Ventas y caja registradas por separado', 'Dificultad para revisar movimientos', 'Poco control cuando trabajan empleados', 'Información que no está disponible fuera del local'],
    uses: ['Ventas conectadas con caja', 'Seguimiento de movimientos', 'Productos y stock', 'Facturación ARCA', 'Usuarios y operación', 'Acceso móvil'],
    searchTerms: ['sistema de caja para comercio', 'programa de caja', 'caja online comercio', 'sistema ventas y caja'],
    faq: [
      {question:'¿La caja se integra con las ventas?',answer:'Sí. Ventas y caja forman parte del mismo flujo operativo.'},
      {question:'¿Puedo usar empleados?',answer:'Comercio Lleno contempla usuarios y operación por empleados.'},
      {question:'¿Puedo entrar desde otro dispositivo?',answer:'Sí. La plataforma es web y también cuenta con experiencia móvil.'},
    ],
    heroImage: pexels(19224085),
    heroAlt: 'Caja registradora imprimiendo un comprobante en un comercio',
    secondaryImage: pexels(6390088),
    secondaryAlt: 'Mostrador de comercio con terminal de cobro',
    photoCredit: 'Fotos de GOWTHAM AGM y Julia Avamotive · Pexels',
    layout: 'editorial',
    theme: 'orange',
    sceneTitle: 'Que el cierre del día sea una revisión, no una investigación.',
    sceneText: 'La caja toma sentido cuando está conectada con las operaciones que la generaron.',
    scenePoints: ['Ventas registradas dentro del mismo sistema', 'Medios de pago visibles', 'Movimientos y cierres', 'Consulta de resultados desde el celular'],
    systemTitle: 'La operación de caja con contexto.',
    systemText: 'No sólo un número final: ventas, movimientos y productos quedan relacionados dentro del sistema.',
    productExamples: [
      {name:'Venta #1048',detail:'Efectivo',stock:'Cobrada'},
      {name:'Venta #1049',detail:'Débito',stock:'Cobrada'},
      {name:'Movimiento de caja',detail:'Ingreso',stock:'Registrado'},
      {name:'Venta #1050',detail:'Mercado Pago',stock:'Cobrada'},
    ],
    stat:{value:'Caja conectada',label:'con cada operación'},
  },
]

export const solutionsBySlug = Object.fromEntries(solutions.map((solution) => [solution.slug, solution])) as Record<string, Solution>
