import Link from 'next/link'
import BrandLogo from '../BrandLogo'
import styles from '../legal.module.css'

export const metadata={title:'Política de Privacidad | Comercio Lleno'}

export default function PrivacyPage(){return <main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link href="/" aria-label="Comercio Lleno"><BrandLogo size={46}/></Link><Link className={styles.back} href="/">← Volver a Comercio Lleno</Link></div><article className={styles.card}><span className={styles.eyebrow}>LLENA GROUP · COMERCIO LLENO</span><h1>Política de Privacidad</h1><div className={styles.updated}>Versión vigente desde el 15 de agosto de 2026.</div><p className={styles.notice}>Esta política explica cómo Comercio Lleno accede, utiliza, conserva y protege información cuando una persona usa la aplicación Android, la versión web o los servicios vinculados.</p>
<h2>1. Responsable y alcance</h2><p>Comercio Lleno es un sistema de gestión comercial publicado bajo el nombre de desarrollador <b>Llena Group</b>, nombre comercial utilizado por Gabriel Granvillano en Argentina. Esta política se aplica a la aplicación Comercio Lleno, su versión web y sus integraciones.</p><p>Para consultas de privacidad podés utilizar Ayuda humana dentro de Comercio Lleno o el canal público de contacto disponible en <Link href="/">comerciolleno.com</Link>.</p>
<h2>2. Datos que tratamos</h2><ul><li>Datos de cuenta y acceso: nombre, usuario o email, identificadores de autenticación, rol y permisos.</li><li>Datos del comercio: nombre, CUIT/CUIL cuando se informa, domicilio, teléfono o WhatsApp, sucursales y configuración.</li><li>Datos operativos: productos, códigos de barras, precios, costos, stock, ventas, medios de pago declarados, caja, compras, proveedores, promociones y reportes.</li><li>Datos de clientes cargados por el comercio: nombre, teléfono, email, identificación fiscal y otros datos necesarios para la gestión comercial.</li><li>Datos fiscales y de comprobantes: información necesaria para facturación electrónica y estado de comprobantes, incluyendo datos asociados a ARCA cuando la integración está habilitada.</li><li>Datos de soporte: mensajes enviados al asistente o a Ayuda humana y la información necesaria para resolver la consulta.</li><li>Datos técnicos: identificadores de sesión, registros de seguridad y datos básicos del dispositivo o navegador necesarios para operar, diagnosticar errores y proteger el servicio.</li></ul>
<h2>3. Cámara y escáner de productos</h2><p>La aplicación puede solicitar acceso a la cámara cuando el usuario decide utilizar el escáner de códigos de barras. La imagen de cámara se utiliza mientras el escáner está abierto para reconocer el código. Comercio Lleno no utiliza esta función para guardar fotografías o videos de la cámara.</p>
<h2>4. Inteligencia artificial</h2><p>Cuando el usuario utiliza el Asistente IA, la consulta y el contexto estrictamente necesario del comercio pueden procesarse para generar una respuesta. El servicio utiliza infraestructura de Vercel AI Gateway y puede recurrir a modelos de proveedores de inteligencia artificial habilitados. El asistente valida la sesión, el comercio y los permisos antes de consultar información.</p>
<h2>5. Para qué usamos la información</h2><p>Utilizamos la información para autenticar usuarios, prestar las funciones de ventas, stock, caja, productos, clientes, reportes y facturación, sincronizar datos entre dispositivos autorizados, brindar soporte, proteger cuentas, prevenir abuso, diagnosticar fallas, cumplir obligaciones aplicables y proporcionar funciones de IA cuando el usuario las utiliza.</p>
<h2>6. ARCA y credenciales fiscales</h2><p>Cuando el propietario conecta ARCA, Comercio Lleno puede generar y administrar material criptográfico y certificados necesarios para la integración. Las credenciales sensibles se protegen del lado del servidor y se utilizan únicamente para operaciones autorizadas del comercio correspondiente.</p>
<h2>7. WhatsApp y otras integraciones</h2><p>Si el comercio habilita una integración de mensajería, se procesan los identificadores, números y mensajes necesarios para las funciones configuradas. El uso de servicios externos también está sujeto a las políticas del proveedor correspondiente.</p>
<h2>8. Proveedores e infraestructura</h2><p>Para prestar el servicio podemos utilizar proveedores que procesan información por nuestra cuenta. Comercio Lleno utiliza actualmente infraestructura de <b>Supabase</b> para autenticación y datos y <b>Vercel</b> para alojamiento y servicios de aplicación. También pueden intervenir proveedores vinculados a facturación, mensajería, pagos o inteligencia artificial cuando el usuario utiliza esas funciones.</p>
<h2>9. Seguridad</h2><p>Aplicamos separación por comercio, controles de acceso, permisos por rol, conexiones cifradas mediante HTTPS y medidas específicas para credenciales sensibles. Ningún sistema puede garantizar riesgo cero, por lo que también es importante que cada usuario proteja sus credenciales.</p>
<h2>10. Almacenamiento local</h2><p>La aplicación puede utilizar almacenamiento local del navegador o WebView para mantener la sesión, recordar preferencias y permitir determinadas funciones de continuidad u operación móvil.</p>
<h2>11. Conservación</h2><p>La información se conserva mientras la cuenta esté activa y durante el tiempo razonablemente necesario para prestar el servicio, seguridad, respaldo, prevención de fraude, cumplimiento contractual o legal y resolución de incidentes. Determinados registros fiscales, contables o de seguridad pueden conservarse cuando una norma aplicable lo exija.</p>
<h2>12. Eliminación de cuenta y datos</h2><p>El titular puede solicitar la eliminación de su cuenta y de los datos asociados que no deban conservarse por obligación legal. La solicitud puede iniciarse desde Ayuda humana o desde nuestra página pública de eliminación de cuenta.</p><p><Link href="/eliminar-cuenta">Solicitar eliminación de cuenta y datos →</Link></p>
<h2>13. Datos de terceros cargados por un comercio</h2><p>Los comercios que utilizan Comercio Lleno son responsables de contar con una base legítima para cargar y utilizar datos de sus clientes, empleados, proveedores u otros terceros. Comercio Lleno procesa esos datos para brindar el servicio al comercio correspondiente y aplica aislamiento entre comercios.</p>
<h2>14. Comercialización de datos</h2><p>Comercio Lleno no vende la información personal u operativa de sus clientes como un producto independiente.</p>
<h2>15. Menores de edad</h2><p>Comercio Lleno es una herramienta de gestión para comercios y no está diseñada ni dirigida específicamente a niños.</p>
<h2>16. Cambios</h2><p>Esta política puede actualizarse para reflejar cambios en el producto, proveedores o requisitos aplicables. La fecha de la versión vigente se muestra al comienzo de esta página.</p><div className={styles.footer}>Esta política se complementa con los <Link href="/terminos">Términos y Condiciones</Link> y con la página de <Link href="/eliminar-cuenta">eliminación de cuenta</Link>.</div></article></div></main>}
