import type {Metadata} from 'next'
import Link from 'next/link'
import {headers} from 'next/headers'
import BrandLogo from '../BrandLogo'
import {PlatformFooter,PlatformHeader} from '../postula-preview/PlatformChrome'
import '../postula-preview/premium-v7.css'
import styles from '../legal.module.css'

function isPostulaHost(host:string){const clean=host.split(':')[0].toLowerCase();return clean==='postulamejor.com'||clean==='www.postulamejor.com'}
async function postulaRequest(){const h=await headers();return isPostulaHost(h.get('x-forwarded-host')||h.get('host')||'')}

export async function generateMetadata():Promise<Metadata>{
  if(await postulaRequest())return{
    title:{absolute:'Política de Privacidad | Postulá Mejor'},
    description:'Cómo Postulá Mejor trata datos de candidatos, empleadores, CV, postulaciones, mensajes, Trabajos Flex e inteligencia artificial.',
    robots:{index:true,follow:true},
    alternates:{canonical:'https://postulamejor.com/privacidad'},
    openGraph:{title:'Política de Privacidad | Postulá Mejor',description:'Privacidad, datos personales, IA y derechos de las personas en Postulá Mejor.',url:'https://postulamejor.com/privacidad'},
  }
  return{title:{absolute:'Política de Privacidad | Comercio Lleno'},alternates:{canonical:'https://comerciolleno.com/privacidad'}}
}

function PostulaPrivacy(){return <><PlatformHeader/><main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link className={styles.back} href="/legales">← Centro legal de Postulá Mejor</Link></div><article className={styles.card}><span className={styles.eyebrow}>POSTULÁ MEJOR · PRIVACIDAD</span><h1>Política de Privacidad</h1><div className={styles.updated}>Versión vigente desde el 20 de agosto de 2026.</div><p className={styles.notice}>Esta política explica qué información trata Postulá Mejor, para qué se utiliza, con quién puede procesarse y qué controles tiene la persona usuaria. Se aplica a candidatos, empleadores y personas que usan Trabajos Flex.</p>
<h2>1. Responsable y alcance</h2><p>Postulá Mejor es un servicio digital operado en Argentina por Gabriel Alejandro Granvillano, CUIT 20-38422407-6. Esta política alcanza el sitio postulamejor.com, las cuentas, herramientas de CV, búsquedas laborales, mensajería, funciones para empresas, Trabajos Flex y servicios vinculados.</p><p>Las solicitudes relacionadas con privacidad pueden iniciarse mediante los canales de soporte publicados dentro de la plataforma.</p>
<h2>2. Información que podemos tratar</h2><ul><li><b>Cuenta:</b> nombre, email, identificadores de autenticación, rol, preferencias y registros básicos de seguridad.</li><li><b>Perfil laboral:</b> ubicación, experiencia, estudios, habilidades, disponibilidad, áreas de interés, CV, foto cuando la persona decide cargarla y otros datos que incorpore voluntariamente.</li><li><b>Postulaciones:</b> puesto, empresa, CV elegido, presentación, respuestas, estado, notas operativas y evidencia relacionada con el proceso.</li><li><b>Empresas:</b> nombre comercial, actividad, ubicación, web, teléfono, identificación fiscal cuando se informa, integrantes, roles, búsquedas y señales de validación.</li><li><b>Mensajes y colaboración:</b> conversaciones entre partes, transcripciones de dictado cuando se utiliza esa función, notas internas y derivaciones dentro del equipo autorizado.</li><li><b>Trabajos Flex:</b> descripción de la tarea, zona, fecha, importe propuesto, respuestas y datos necesarios para conectar a las partes.</li><li><b>Datos técnicos:</b> sesión, navegador, registros de seguridad, errores y eventos necesarios para operar, proteger y mejorar el servicio.</li></ul>
<h2>3. Para qué usamos los datos</h2><p>Tratamos la información para crear y proteger cuentas, mostrar oportunidades, permitir postulaciones y conversaciones, operar herramientas de CV, administrar búsquedas de empresas, mantener trazabilidad, prevenir abuso, brindar soporte, mejorar la experiencia y cumplir obligaciones legales o contractuales aplicables.</p>
<h2>4. Inteligencia artificial y decisiones</h2><p>Algunas funciones utilizan inteligencia artificial para resumir, ordenar información, explicar coincidencias, sugerir mejoras de CV, preparar preguntas o asistir a candidatos y empleadores. La IA es una herramienta de apoyo: no debe tomar por sí sola la decisión final de contratar, rechazar o aceptar una tarea.</p><p>Los sistemas de match y ordenamiento están diseñados para trabajar con evidencia relacionada con la oportunidad. Características sensibles como género, religión, salud, orientación sexual o información equivalente no deben utilizarse como criterio de descarte. Cuando una foto existe en el perfil, no forma parte del cálculo de compatibilidad.</p>
<h2>5. Empleadores y acceso a datos de candidatos</h2><p>Una empresa accede a información de una persona cuando existe una relación legítima dentro de la plataforma, por ejemplo una postulación a una búsqueda de esa organización. Las cuentas empresariales se aíslan por organización y rol. Los integrantes del equipo deben utilizar la información exclusivamente para finalidades de selección informadas y relacionadas con su función.</p>
<h2>6. Fuentes externas de oportunidades</h2><p>Postulá Mejor puede mostrar oportunidades provenientes de páginas públicas oficiales de empresas o proveedores de recruiting. En esos casos se identifica la fuente y la publicación original mantiene prioridad sobre la copia informativa de la plataforma. Si una persona continúa hacia un sitio externo, también se aplican las políticas de ese tercero.</p>
<h2>7. Proveedores e infraestructura</h2><p>Para prestar el servicio pueden intervenir proveedores de alojamiento, base de datos, autenticación, almacenamiento, analítica, seguridad, pagos e inteligencia artificial. Actualmente la plataforma utiliza infraestructura de Vercel y Supabase, entre otros servicios que pueden incorporarse o reemplazarse. Sólo se comparte la información razonablemente necesaria para la función correspondiente y bajo las condiciones del proveedor aplicable.</p>
<h2>8. Pagos</h2><p>Cuando una persona contrata una función paga, el proveedor de pagos procesa la información necesaria para cobrar y acreditar la operación. Postulá Mejor conserva los identificadores y estados necesarios para habilitar el producto, conciliar la transacción y atender reclamos, pero no necesita almacenar los datos completos de una tarjeta cuando el cobro lo procesa un proveedor externo.</p>
<h2>9. Seguridad</h2><p>Aplicamos HTTPS, controles de sesión, permisos por rol, separación entre organizaciones y medidas de acceso para información privada. Ningún sistema conectado a Internet puede garantizar riesgo cero; por eso también recomendamos proteger credenciales y no compartir claves o documentación sensible fuera de los canales necesarios.</p>
<h2>10. Conservación</h2><p>La información se conserva mientras la cuenta o relación esté activa y por el período razonablemente necesario para operar el servicio, seguridad, prevención de fraude, respaldo, cumplimiento legal y resolución de disputas. Cuando un plan pago vence, eso no implica por sí solo borrar la cuenta ni el historial gratuito.</p>
<h2>11. Derechos sobre datos personales</h2><p>Las personas pueden solicitar acceso, actualización, rectificación o supresión de datos conforme a la normativa argentina aplicable, sujeto a la información que deba conservarse por razones legales, de seguridad o defensa de derechos. También pueden pedir revisión de una referencia o señal agregada cuando corresponda.</p><p>La Agencia de Acceso a la Información Pública es el órgano de control de la Ley 25.326 y recibe consultas y denuncias dentro de sus competencias.</p>
<h2>12. Menores de edad</h2><p>Postulá Mejor está orientado a personas con capacidad suficiente para buscar trabajo, contratar o publicar tareas conforme a la normativa aplicable. Las funciones no están diseñadas para recopilar deliberadamente información de niños.</p>
<h2>13. Cambios</h2><p>Podemos actualizar esta política cuando cambien funciones, proveedores o requisitos legales. La versión vigente y su fecha se publican en esta página. Si un cambio es relevante para el tratamiento de datos, podremos comunicarlo además dentro del servicio.</p><div className={styles.footer}>Esta política se complementa con los <Link href="/terminos">Términos y Condiciones</Link> y el <Link href="/legales">Centro legal y de seguridad</Link>.</div></article></div></main><PlatformFooter/></>}

function ComercioPrivacy(){return <main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link href="/" aria-label="Comercio Lleno"><BrandLogo size={46}/></Link><Link className={styles.back} href="/">← Volver a Comercio Lleno</Link></div><article className={styles.card}><span className={styles.eyebrow}>LLENA GROUP · COMERCIO LLENO</span><h1>Política de Privacidad</h1><div className={styles.updated}>Versión vigente desde el 15 de agosto de 2026.</div><p className={styles.notice}>Esta política explica cómo Comercio Lleno accede, utiliza, conserva y protege información cuando una persona usa la aplicación Android, la versión web o los servicios vinculados.</p>
<h2>1. Responsable y alcance</h2><p>Comercio Lleno es un sistema de gestión comercial publicado bajo el nombre de desarrollador <b>Llena Group</b>, nombre comercial utilizado por Gabriel Granvillano en Argentina. Esta política se aplica a la aplicación Comercio Lleno, su versión web y sus integraciones.</p><p>Para consultas de privacidad podés utilizar Ayuda humana dentro de Comercio Lleno o el canal público de contacto disponible en <Link href="/">comerciolleno.com</Link>.</p>
<h2>2. Datos que tratamos</h2><ul><li>Datos de cuenta y acceso: nombre, usuario o email, identificadores de autenticación, rol y permisos.</li><li>Datos del comercio: nombre, CUIT/CUIL cuando se informa, domicilio, teléfono o WhatsApp, sucursales y configuración.</li><li>Datos operativos: productos, códigos de barras, precios, costos, stock, ventas, medios de pago declarados, caja, compras, proveedores, promociones y reportes.</li><li>Datos de clientes cargados por el comercio: nombre, teléfono, email, identificación fiscal y otros datos necesarios para la gestión comercial.</li><li>Datos fiscales y de comprobantes: información necesaria para facturación electrónica y estado de comprobantes, incluyendo datos asociados a ARCA cuando la integración está habilitada.</li><li>Datos de soporte: mensajes enviados al asistente o a Ayuda humana y la información necesaria para resolver la consulta.</li><li>Datos técnicos: identificadores de sesión, registros de seguridad y datos básicos del dispositivo o navegador necesarios para operar, diagnosticar errores y proteger el servicio.</li></ul>
<h2>3. Cámara y escáner de productos</h2><p>La aplicación puede solicitar acceso a la cámara cuando el usuario decide utilizar el escáner de códigos de barras. La imagen de cámara se utiliza mientras el escáner está abierto para reconocer el código. Comercio Lleno no utiliza esta función para guardar fotografías o videos de la cámara.</p>
<h2>4. Inteligencia artificial</h2><p>Cuando el usuario utiliza el Asistente IA, la consulta y el contexto estrictamente necesario del comercio pueden procesarse para generar una respuesta. El servicio utiliza infraestructura de Vercel AI Gateway y puede recurrir a modelos de proveedores de inteligencia artificial habilitados. El asistente valida la sesión, el comercio y los permisos antes de consultar información.</p>
<h2>5. Para qué usamos la información</h2><p>Utilizamos la información para autenticar usuarios, prestar las funciones de ventas, stock, caja, productos, clientes, reportes y facturación, sincronizar datos entre dispositivos autorizados, brindar soporte, proteger cuentas, prevenir abuso, diagnosticar fallas, cumplir obligaciones aplicables y proporcionar funciones de IA cuando el usuario las utiliza.</p>
<h2>6. ARCA y credenciales fiscales</h2><p>Cuando el propietario conecta ARCA, Comercio Lleno puede generar y administrar material criptográfico y certificados necesarios para la integración. Las credenciales sensibles se protegen del lado del servidor y se utilizan únicamente para operaciones autorizadas del comercio correspondiente.</p>
<h2>7. WhatsApp y otras integraciones</h2><p>Si el comercio habilita una integración de mensajería, se procesan los identificadores, números y mensajes necesarios para las funciones configuradas. El uso de servicios externos también está sujeto a las políticas del proveedor correspondiente.</p>
<h2>8. Proveedores e infraestructura</h2><p>Para prestar el servicio podemos utilizar proveedores que procesan información por nuestra cuenta. Comercio Lleno utiliza actualmente infraestructura de <b>Supabase</b> para autenticación y datos y <b>Vercel</b> para alojamiento y servicios de aplicación. También pueden intervenir proveedores vinculados a facturación, mensajería, pagos o inteligencia artificial cuando el usuario utiliza esas funciones.</p>
<h2>9. Seguridad</h2><p>Aplicamos separación por comercio, controles de acceso, permisos por rol, conexiones cifradas mediante HTTPS y medidas específicas para credenciales sensibles. Ningún sistema puede garantizar riesgo cero, por lo que también es importante que cada usuario proteja sus credenciales.</p>
<h2>10. Almacenamiento local</h2><p>La aplicación puede utilizar almacenamiento local del navegador o WebView para mantener la sesión, recordar preferencias y permitir determinadas funciones de continuidad u operación móvil.</p>
<h2>11. Conservación</h2><p>La información se conserva mientras la cuenta esté activa y durante el tiempo razonablemente necesario para prestar el servicio, seguridad, respaldo, prevención de fraude, cumplimiento contractual o legal y resolución de incidentes. Determinados registros fiscales, contables o de seguridad pueden conservarse cuando una norma aplicable lo exija.</p>
<h2>12. Eliminación de cuenta y datos</h2><p>El titular puede solicitar la eliminación de su cuenta y de los datos asociados que no deban conservarse por obligación legal. La solicitud puede iniciarse desde Ayuda humana o desde nuestra página pública de eliminación de cuenta.</p><p><Link href="/eliminar-cuenta">Solicitar eliminación de cuenta y datos →</Link></p>
<h2>13. Datos de terceros cargados por un comercio</h2><p>Los comercios que utilizan Comercio Lleno son responsables de contar con una base legítima para cargar y utilizar datos de sus clientes, empleados, proveedores u otros terceros. Comercio Lleno procesa esos datos para brindar el servicio al comercio correspondiente y aplica aislamiento entre comercios.</p>
<h2>14. Comercialización de datos</h2><p>Comercio Lleno no vende la información personal u operativa de sus clientes como un producto independiente.</p>
<h2>15. Menores de edad</h2><p>Comercio Lleno es una herramienta de gestión para comercios y no está diseñada ni dirigida específicamente a niños.</p>
<h2>16. Cambios</h2><p>Esta política puede actualizarse para reflejar cambios en el producto, proveedores o requisitos aplicables. La fecha de la versión vigente se muestra al comienzo de esta página.</p><div className={styles.footer}>Esta política se complementa con los <Link href="/terminos">Términos y Condiciones</Link> y con la página de <Link href="/eliminar-cuenta">eliminación de cuenta</Link>.</div></article></div></main>}

export default async function PrivacyPage(){return await postulaRequest()?<PostulaPrivacy/>:<ComercioPrivacy/>}
