'use client'

import { FormEvent,useEffect,useRef,useState } from 'react'
import { authHeaders,trackCvEvent } from '../cv-ia/cvAuth'
import styles from './active.module.css'

const CHAT_API='https://pejkycdttogpmmdntzuq.supabase.co/functions/v1/postula-support-chat'
type Msg={id:string;sender_type:string;sender_name:string|null;body:string;created_at:string}

export default function HumanHelpChat({open,token,onClose,onNotice,onError}:{open:boolean;token:string;onClose:()=>void;onNotice:(v:string)=>void;onError:(v:string)=>void}){
 const[messages,setMessages]=useState<Msg[]>([]),[text,setText]=useState(''),[category,setCategory]=useState('Consulta sobre Búsqueda Activa'),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);const bottom=useRef<HTMLDivElement|null>(null)
 async function call(action:'thread'|'send',extra:Record<string,unknown>={}){const headers:Record<string,string>={'Content-Type':'application/json',...(await authHeaders())};const r=await fetch(CHAT_API,{method:'POST',headers,body:JSON.stringify({action,token,...extra}),cache:'no-store'});const d=await r.json().catch(()=>({ok:false,error:'Respuesta inválida'}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos abrir el chat.');return d}
 async function load(silent=false){if(!open)return;if(!silent)setLoading(true);try{const d=await call('thread');setMessages(d.messages||[]);if(!silent)void trackCvEvent('human_help_opened',{},'/busqueda-activa')}catch(e){if(!silent)onError(e instanceof Error?e.message:'No pudimos abrir el chat.')}finally{if(!silent)setLoading(false)}}
 useEffect(()=>{if(!open)return;void load();const id=window.setInterval(()=>void load(true),10000);return()=>window.clearInterval(id)},[open,token])
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:'smooth'})},[messages.length,open])
 async function send(e:FormEvent){e.preventDefault();if(busy||!text.trim())return;setBusy(true);onError('');try{const d=await call('send',{message:text.trim(),category});setMessages(d.messages||[]);setText('');onNotice('Mensaje enviado a ayuda humana.')}catch(e){onError(e instanceof Error?e.message:'No pudimos enviar el mensaje.')}finally{setBusy(false)}}
 if(!open)return null
 return <div className={styles.chatOverlay} onMouseDown={e=>{if(e.target===e.currentTarget)onClose()}}><section className={styles.chatCard}><header className={styles.chatHead}><div><span>AYUDA HUMANA · POSTULÁ MEJOR</span><h2>Chat de soporte</h2><p>Este hilo llega a Central Llena. No adjuntamos el contenido de tu CV.</p></div><button onClick={onClose}>×</button></header><label className={styles.chatCategory}>Tema<select value={category} onChange={e=>setCategory(e.target.value)}><option>Problema con mi cuenta</option><option>Problema con una candidatura</option><option>Consulta sobre Búsqueda Activa</option><option>Pago o plan</option><option>Otra consulta</option></select></label><div className={styles.chatMessages}>{loading?<div className={styles.chatEmpty}>Cargando conversación…</div>:messages.length?messages.map(m=><article key={m.id} data-mine={m.sender_type==='customer'}><b>{m.sender_type==='customer'?'Vos':'Ayuda humana'}</b><p>{m.body}</p><time>{new Date(m.created_at).toLocaleString('es-AR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}</time></article>):<div className={styles.chatEmpty}>Todavía no hay mensajes. Escribinos y la conversación va a quedar guardada en tu cuenta.</div>}<div ref={bottom}/></div><form className={styles.chatComposer} onSubmit={send}><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Escribí tu mensaje…" maxLength={2000} required/><button disabled={busy||!text.trim()}>{busy?'Enviando…':'Enviar'}</button></form><small className={styles.chatRefresh}>Mientras este chat está abierto, buscamos respuestas nuevas cada 10 segundos. Esto no usa tokens de IA.</small></section></div>
}
