'use client'

import {useLayoutEffect,useState} from 'react'
import {createPortal} from 'react-dom'

const styles=`
.pmcv-perspective-host>[class*="sectionIntro"],.pmcv-perspective-host>[class*="filterGrid"]{display:none!important}
.pmcv-perspective-host{padding:0!important;background:transparent!important;border:0!important;box-shadow:none!important;overflow:visible!important;width:min(1160px,100%)!important;max-width:1160px!important;margin:18px auto!important}
.pmcv-perspective-rebuild{position:relative;display:grid;grid-template-columns:minmax(280px,.78fr) minmax(0,1.42fr);gap:30px;align-items:center;padding:34px;border:1px solid rgba(105,87,255,.17);border-radius:32px;background:radial-gradient(circle at 8% 15%,rgba(105,87,255,.18),transparent 26%),radial-gradient(circle at 94% 88%,rgba(217,255,97,.08),transparent 28%),linear-gradient(135deg,#151621 0%,#1a1830 48%,#101218 100%);box-shadow:0 28px 70px rgba(31,26,70,.18);overflow:hidden;color:#fff}
.pmcv-perspective-rebuild::before{content:"";position:absolute;inset:0;pointer-events:none;opacity:.14;background-image:linear-gradient(rgba(255,255,255,.05) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.05) 1px,transparent 1px);background-size:28px 28px;mask-image:linear-gradient(90deg,#000,transparent 72%)}
.pmcv-perspective-copy{position:relative;z-index:1;padding:5px 0 5px 4px}.pmcv-perspective-kicker{display:inline-flex;align-items:center;gap:8px;margin-bottom:18px;padding:8px 11px;border:1px solid rgba(255,255,255,.12);border-radius:999px;background:rgba(255,255,255,.055);color:#d9d5ff;font-size:9px;font-weight:950;letter-spacing:.13em}.pmcv-perspective-kicker i{width:7px;height:7px;border-radius:50%;background:#d9ff61;box-shadow:0 0 0 5px rgba(217,255,97,.09)}
.pmcv-perspective-copy h2{margin:0!important;color:#fff!important;font-size:clamp(35px,4vw,54px)!important;line-height:.96!important;letter-spacing:-.055em!important;max-width:430px!important}.pmcv-perspective-copy h2 em{font-style:normal;color:#9b8cff}.pmcv-perspective-copy>p{max-width:390px;margin:16px 0 0!important;color:#b8bcc8!important;font-size:13px!important;line-height:1.6!important}
.pmcv-perspective-route{display:flex;align-items:center;flex-wrap:wrap;gap:7px;margin-top:24px}.pmcv-perspective-route span{display:inline-flex;align-items:center;justify-content:center;min-height:30px;padding:0 10px;border:1px solid rgba(255,255,255,.11);border-radius:10px;background:rgba(255,255,255,.055);color:#eeeefa;font-size:9px;font-weight:900}.pmcv-perspective-route span:first-child{background:#d9ff61;color:#171912;border-color:#d9ff61}.pmcv-perspective-route b{color:#706f7d;font-size:11px}
.pmcv-perspective-console{position:relative;z-index:1;border:1px solid rgba(255,255,255,.11);border-radius:24px;background:rgba(248,248,255,.97);box-shadow:0 22px 55px rgba(0,0,0,.23);overflow:hidden;color:#171923}.pmcv-perspective-console-top{height:42px;display:grid;grid-template-columns:auto 1fr auto;align-items:center;gap:12px;padding:0 14px;border-bottom:1px solid #e6e5ee;background:#f1f0f7}.pmcv-perspective-console-top>div{display:flex;gap:5px}.pmcv-perspective-console-top>div i{width:7px;height:7px;border-radius:50%;background:#d6d3df}.pmcv-perspective-console-top>div i:nth-child(1){background:#ff8d70}.pmcv-perspective-console-top>div i:nth-child(2){background:#ffd76a}.pmcv-perspective-console-top>div i:nth-child(3){background:#82d99d}.pmcv-perspective-console-top>span{font-size:8.5px;font-weight:950;letter-spacing:.12em;color:#7b7f8a}.pmcv-perspective-console-top>small{font-size:9px;font-weight:950;color:#5c4ae5;background:#e9e5ff;padding:5px 7px;border-radius:999px}
.pmcv-perspective-core{position:relative;padding:17px 17px 13px;background:linear-gradient(180deg,#fff,#faf9ff)}.pmcv-perspective-file{display:flex;align-items:center;gap:12px;padding:13px 14px;border:1px solid #e5e2f1;border-radius:16px;background:#fff;box-shadow:0 9px 22px rgba(47,42,74,.045)}.pmcv-perspective-file>span{width:42px;height:42px;border-radius:13px;display:grid;place-items:center;background:linear-gradient(135deg,#171923,#30295c);color:#d9ff61;font-size:12px;font-weight:950}.pmcv-perspective-file b{display:block;font-size:13px}.pmcv-perspective-file small{display:block;margin-top:3px;color:#8a8f99;font-size:9.5px}.pmcv-perspective-scanline{position:absolute;left:44px;right:44px;bottom:0;height:2px;background:linear-gradient(90deg,transparent,#6c58ff 20%,#d9ff61 50%,#6c58ff 80%,transparent);box-shadow:0 0 16px rgba(105,87,255,.55);animation:pmcvScan 3.6s ease-in-out infinite}@keyframes pmcvScan{0%,100%{transform:translateY(-8px);opacity:.28}50%{transform:translateY(2px);opacity:1}}
.pmcv-perspective-list{display:grid;gap:8px;padding:8px 12px 12px}.pmcv-perspective-list article{position:relative;display:grid;grid-template-columns:42px minmax(0,1fr) auto;gap:12px;align-items:center;min-height:76px;padding:10px 12px;border:1px solid #e8e6ef;border-radius:16px;background:#fff;transition:transform .18s ease,border-color .18s ease,box-shadow .18s ease}.pmcv-perspective-list article:hover{transform:translateX(4px);border-color:#d7d1f4;box-shadow:0 10px 24px rgba(50,44,91,.07)}.pmcv-perspective-index{width:36px;height:36px;border-radius:11px;display:grid;place-items:center;background:#f3f2f7;color:#767b87;font-size:10px;font-weight:950}.pmcv-perspective-list article>div b{display:block;margin:0;color:#1a1b22;font-size:15px;line-height:1.1}.pmcv-perspective-list article>div p{margin:4px 0 0;color:#6f7580;font-size:10.5px;line-height:1.45}.pmcv-perspective-list article>em{min-width:82px;padding:7px 8px;border-radius:999px;font-style:normal;text-align:center;font-size:8px;font-weight:950;letter-spacing:.08em}.pmcv-perspective-list article[data-tone="orange"] .pmcv-perspective-index,.pmcv-perspective-list article[data-tone="orange"]>em{background:#fff0e7;color:#d85b34}.pmcv-perspective-list article[data-tone="violet"] .pmcv-perspective-index,.pmcv-perspective-list article[data-tone="violet"]>em{background:#eeeaff;color:#5947e3}.pmcv-perspective-list article[data-tone="green"] .pmcv-perspective-index,.pmcv-perspective-list article[data-tone="green"]>em{background:#e6f8ee;color:#147d51}
.pmcv-perspective-foot{display:flex;justify-content:space-between;gap:10px;padding:11px 15px;border-top:1px solid #e7e5ee;background:#f7f6fa;color:#777c86;font-size:8.7px;font-weight:760}.pmcv-perspective-foot span:first-child{color:#343741}.pmcv-perspective-foot i{display:inline-block;width:6px;height:6px;margin-right:5px;border-radius:50%;background:#64c987}
@media(max-width:900px){.pmcv-perspective-rebuild{grid-template-columns:1fr;gap:22px;padding:28px}.pmcv-perspective-copy h2{max-width:680px!important}.pmcv-perspective-copy>p{max-width:620px}.pmcv-perspective-route{margin-top:18px}}
@media(max-width:620px){.pmcv-perspective-host{margin:12px auto!important}.pmcv-perspective-rebuild{padding:20px 14px;border-radius:24px}.pmcv-perspective-copy h2{font-size:34px!important}.pmcv-perspective-copy>p{font-size:11.5px!important}.pmcv-perspective-route{gap:5px}.pmcv-perspective-route span{min-height:27px;padding:0 8px;font-size:8px}.pmcv-perspective-console{border-radius:19px}.pmcv-perspective-list article{grid-template-columns:38px minmax(0,1fr);gap:9px;min-height:0;padding:11px}.pmcv-perspective-list article>em{grid-column:2;justify-self:start;min-width:0;margin-top:-3px;padding:5px 7px}.pmcv-perspective-list article>div b{font-size:13px}.pmcv-perspective-list article>div p{font-size:9.5px}.pmcv-perspective-foot{display:block;line-height:1.55}.pmcv-perspective-foot span{display:block}.pmcv-perspective-foot span+span{margin-top:3px}}
@media(prefers-reduced-motion:reduce){.pmcv-perspective-scanline{animation:none!important}}
`

export default function CvPerspectiveRebuild(){
 const [host,setHost]=useState<HTMLElement|null>(null)
 useLayoutEffect(()=>{
  const mount=()=>{
   const grid=document.querySelector('.pmcv-shell [class*="filterGrid"]') as HTMLElement|null
   const section=grid?.closest('section') as HTMLElement|null
   if(!section)return false
   section.classList.add('pmcv-perspective-host')
   setHost(section)
   return true
  }
  if(mount())return
  const observer=new MutationObserver(()=>{if(mount())observer.disconnect()})
  observer.observe(document.body,{childList:true,subtree:true})
  const timer=window.setTimeout(()=>observer.disconnect(),5000)
  return()=>{window.clearTimeout(timer);observer.disconnect()}
 },[])
 if(!host)return null
 return createPortal(<>
  <style>{styles}</style>
  <div className="pmcv-perspective-rebuild" aria-label="Cómo analizamos tu CV desde tres perspectivas">
   <div className="pmcv-perspective-copy"><span className="pmcv-perspective-kicker"><i/>TRIPLE REVISIÓN</span><h2>Un CV. <em>Tres filtros</em> antes de avanzar.</h2><p>La misma candidatura cambia según quién la mira. Por eso no usamos una sola opinión automática.</p><div className="pmcv-perspective-route" aria-hidden="true"><span>CV</span><b>→</b><span>ATS</span><b>→</b><span>Selección</span><b>→</b><span>Área</span></div></div>
   <div className="pmcv-perspective-console"><div className="pmcv-perspective-console-top"><div><i/><i/><i/></div><span>ANÁLISIS DE CANDIDATURA</span><small>3/3</small></div><div className="pmcv-perspective-core"><div className="pmcv-perspective-file"><span>CV</span><div><b>Tu candidatura</b><small>Una sola fuente. Tres lecturas.</small></div></div><div className="pmcv-perspective-scanline" aria-hidden="true"/></div><div className="pmcv-perspective-list"><article data-tone="orange"><span className="pmcv-perspective-index">01</span><div><b>Filtro ATS</b><p>Orden, lectura automática, palabras relevantes y compatibilidad con el aviso.</p></div><em>ESTRUCTURA</em></article><article data-tone="violet"><span className="pmcv-perspective-index">02</span><div><b>Selección</b><p>Si el perfil se entiende rápido y da motivos concretos para llamarte.</p></div><em>INTERÉS</em></article><article data-tone="green"><span className="pmcv-perspective-index">03</span><div><b>Responsable del área</b><p>Si tu experiencia realmente demuestra que podés resolver ese trabajo.</p></div><em>ENCAJE</em></article></div><div className="pmcv-perspective-foot"><span><i/> Sin inventar experiencia</span><span>Diagnóstico explicado, no una caja negra</span></div></div>
  </div>
 </>,host)
}
