'use client'
import {useEffect} from 'react'
function setNative(el:HTMLInputElement|HTMLTextAreaElement,value:string){const proto=el instanceof HTMLTextAreaElement?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const setter=Object.getOwnPropertyDescriptor(proto,'value')?.set;setter?.call(el,value);el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}))}
function findField(labelText:string){const labels=Array.from(document.querySelectorAll('label'));const label=labels.find(x=>(x.textContent||'').toLowerCase().includes(labelText.toLowerCase()));return label?.parentElement?.querySelector('input,textarea') as HTMLInputElement|HTMLTextAreaElement|null}
function replaceText(){const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n:Node|null;while((n=walker.nextNode())){const p=n.parentElement;if(!p||p.closest('script,style'))continue;const raw=n.nodeValue||'';let next=raw.replace(/CV Pro(?!\+)/g,'CV Pro+').replace(/Los planes pagos se habilitan mediante Mercado Pago\. CV Pro\+ y Búsqueda Activa duran 30 días\./g,'El diagnóstico es gratis. CV Pro+ se habilita mediante Mercado Pago y dura 30 días.').replace(/CV Pro\+ es un pago único; Búsqueda Activa dura 30 días\./g,'El diagnóstico es gratis. CV Pro+ se habilita mediante Mercado Pago y dura 30 días.').replace(/CV Pro\+ y Búsqueda Activa duran 30 días\./g,'El diagnóstico es gratis. CV Pro+ se habilita mediante Mercado Pago y dura 30 días.').replace(/pago único/g,'/ 30 días');if(next!==raw)n.nodeValue=next}}
const FILTER_POLISH=`
.pmcv-modern-filter-section [class*="filterGrid"]{gap:16px!important;perspective:1200px}
.pmcv-modern-filter-section .pmcv-modern-filter-card{position:relative!important;isolation:isolate!important;overflow:hidden!important;min-height:245px!important;padding:28px!important;border-radius:28px!important;border:1px solid rgba(255,255,255,.12)!important;color:#fff!important;box-shadow:0 22px 55px rgba(15,18,31,.18),inset 0 1px 0 rgba(255,255,255,.1)!important;transform:translateZ(0)!important;transition:transform .24s ease,box-shadow .24s ease,border-color .24s ease!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card::before{content:""!important;position:absolute!important;inset:0!important;height:auto!important;z-index:-2!important;background-image:linear-gradient(rgba(255,255,255,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.035) 1px,transparent 1px)!important;background-size:26px 26px!important;mask-image:linear-gradient(to bottom,rgba(0,0,0,.9),transparent 85%)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card::after{content:""!important;position:absolute!important;width:210px!important;height:210px!important;right:-75px!important;top:-82px!important;bottom:auto!important;border-radius:50%!important;filter:blur(4px)!important;opacity:.75!important;z-index:-1!important;pointer-events:none!important}
.pmcv-modern-filter-section .pmcv-modern-filter-1{background:radial-gradient(circle at 12% 0,rgba(255,126,77,.23),transparent 34%),linear-gradient(145deg,#17191f 0%,#242730 100%)!important}.pmcv-modern-filter-section .pmcv-modern-filter-1::after{background:radial-gradient(circle,#ff754f 0%,rgba(255,117,79,.1) 60%,transparent 72%)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-2{background:radial-gradient(circle at 12% 0,rgba(123,102,255,.28),transparent 35%),linear-gradient(145deg,#17162a 0%,#272340 100%)!important}.pmcv-modern-filter-section .pmcv-modern-filter-2::after{background:radial-gradient(circle,#7b66ff 0%,rgba(123,102,255,.12) 60%,transparent 72%)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-3{background:radial-gradient(circle at 12% 0,rgba(40,193,113,.24),transparent 35%),linear-gradient(145deg,#122019 0%,#1d3025 100%)!important}.pmcv-modern-filter-section .pmcv-modern-filter-3::after{background:radial-gradient(circle,#28c171 0%,rgba(40,193,113,.1) 60%,transparent 72%)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card:hover{transform:translateY(-7px) rotateX(1deg)!important;border-color:rgba(255,255,255,.24)!important;box-shadow:0 30px 72px rgba(15,18,31,.25),inset 0 1px 0 rgba(255,255,255,.16)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card>span{position:relative!important;z-index:2!important;display:inline-flex!important;align-items:center!important;width:auto!important;height:auto!important;margin:0 0 48px!important;padding:8px 11px!important;border:1px solid rgba(255,255,255,.14)!important;border-radius:999px!important;background:rgba(255,255,255,.08)!important;backdrop-filter:blur(10px)!important;color:#fff!important;font-size:9px!important;font-weight:950!important;letter-spacing:.14em!important;box-shadow:none!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card>b{position:relative!important;z-index:2!important;display:block!important;margin:0 0 12px!important;color:#fff!important;font-size:clamp(25px,2.2vw,32px)!important;line-height:1!important;letter-spacing:-.045em!important;text-shadow:0 2px 20px rgba(0,0,0,.18)!important}
.pmcv-modern-filter-section .pmcv-modern-filter-card>p{position:relative!important;z-index:2!important;margin:0!important;max-width:94%!important;color:rgba(244,247,251,.76)!important;font-size:13px!important;line-height:1.7!important}
.pmcv-modern-filter-section .pmcv-modern-filter-1>span{color:#ffd7ca!important;background:rgba(255,117,79,.13)!important}.pmcv-modern-filter-section .pmcv-modern-filter-2>span{color:#ddd7ff!important;background:rgba(123,102,255,.15)!important}.pmcv-modern-filter-section .pmcv-modern-filter-3>span{color:#c9f7dd!important;background:rgba(40,193,113,.13)!important}
@media(max-width:820px){.pmcv-modern-filter-section .pmcv-modern-filter-card{min-height:205px!important;padding:23px!important;border-radius:23px!important}.pmcv-modern-filter-section .pmcv-modern-filter-card>span{margin-bottom:34px!important}.pmcv-modern-filter-section .pmcv-modern-filter-card>b{font-size:25px!important}}
`
export default function CvUnifiedBridge(){useEffect(()=>{const style=document.createElement('style');style.id='pmcv-filter-premium-v13';style.textContent=FILTER_POLISH;document.head.appendChild(style);const apply=(detail:{title?:string;company?:string;text?:string})=>{const role=findField('Puesto al que querés postularte'),job=findField('Pegá la oferta');if(role&&detail.title)setNative(role,detail.title);if(job&&detail.text)setNative(job,detail.text)};const listener=(e:Event)=>apply((e as CustomEvent).detail||{});window.addEventListener('pm:cv-job',listener);const params=new URLSearchParams(location.search);const puesto=params.get('puesto'),empresa=params.get('empresa');if(puesto)window.setTimeout(()=>apply({title:puesto,text:empresa?`Oferta de ${empresa} para ${puesto}. Completá o pegá la descripción del puesto para un análisis más preciso.`:''}),250);replaceText();const timer=window.setTimeout(replaceText,0);return()=>{window.clearTimeout(timer);window.removeEventListener('pm:cv-job',listener);style.remove()}},[]);return null}
