'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import Link from 'next/link'
import {cvAuthClient} from '../../cv-ia/cvAuth'

type Job={id:string;title:string;area?:string;location_text?:string;public_location_text?:string;employer_visibility?:string;work_mode?:string;schedule?:string;compensation_text?:string;description?:string;requirements?:string[];status:string;published_at?:string;closes_at?:string;created_at?:string;updated_at?:string}
type Credits={plan:string;used:number;allowance:number|null;remaining:number|null}
type Edit={title:string;area:string;location:string;public_location:string;employer_visibility:string;mode:string;schedule:string;salary:string;description:string;requirements:string}
type Confirm={kind:'finish'|'remove';job:Job}|null

function statusLabel(v:string){if(v==='published')return'Activa';if(v==='closed')return'Finalizada';if(v==='draft')return'Borrador';if(v==='paused')return'Pausada';if(v==='review')return'En revisión';return v}
function dateLabel(v?:string){if(!v)return'';const d=new Date(v);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'})}
function editFrom(job:Job):Edit{return{title:job.title||'',area:job.area||'Otros rubros',location:job.location_text||'',public_location:job.public_location_text||'',employer_visibility:job.employer_visibility==='confidential'?'confidential':'public',mode:job.work_mode||'Presencial',schedule:job.schedule||'Full time',salary:job.compensation_text||'',description:job.description||'',requirements:(job.requirements||[]).join(' · ')}}
async function currentSession(){const {data}=await cvAuthClient().auth.getSession();return data.session}

export default function EmployerJobManager(){
 const [company,setCompany]=useState<{id:string;name:string}|null>(null),[jobs,setJobs]=useState<Job[]>([]),[credits,setCredits]=useState<Credits|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState(''),[editId,setEditId]=useState(''),[edit,setEdit]=useState<Edit|null>(null),[confirm,setConfirm]=useState<Confirm>(null),[filter,setFilter]=useState<'all'|'published'|'closed'>('all')
 const visible=useMemo(()=>jobs.filter(j=>filter==='all'||j.status===filter),[jobs,filter])
 const active=jobs.filter(j=>j.status==='published').length,closed=jobs.filter(j=>j.status==='closed').length,drafts=jobs.filter(j=>j.status==='draft').length
 async function load(){
  const s=await currentSession();if(!s){setLoading(false);return}
  setLoading(true);setError('')
  try{const headers={Authorization:`Bearer ${s.access_token}`};const cr=await fetch('/api/postula/company',{headers,cache:'no-store'});const cd=await cr.json().catch(()=>({}));const membership=cd?.memberships?.[0];if(!membership?.company_id){setLoading(false);return}setCompany({id:String(membership.company_id),name:String(membership.pm_companies?.name||'Mi empresa')});const r=await fetch(`/api/postula/company/jobs?company=${encodeURIComponent(membership.company_id)}`,{headers,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos cargar las publicaciones.');setJobs(d.jobs||[]);setCredits(d.credits||null)}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar las publicaciones.')}finally{setLoading(false)}
 }
 useEffect(()=>{void load()},[])
 async function patch(job:Job,action:string,payload:Record<string,unknown>={}){
  if(busy)return;const s=await currentSession();if(!s)return;setBusy(true);setError('');setNotice('')
  try{const r=await fetch('/api/postula/company/jobs',{method:'PATCH',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({id:job.id,action,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos actualizar la búsqueda.');setNotice(d.message||'Búsqueda actualizada.');setEditId('');setEdit(null);setConfirm(null);await load()}catch(e){setError(e instanceof Error?e.message:'No pudimos actualizar la búsqueda.');await load()}finally{setBusy(false)}
 }
 function startDescription(job:Job){setEditId(job.id);setEdit(editFrom(job));setError('');setNotice('')}
 function startReuse(job:Job){setEditId(job.id);setEdit(editFrom(job));setError('');setNotice('')}
 function saveDescription(e:FormEvent,job:Job){e.preventDefault();if(!edit)return;void patch(job,'edit_description',{description:edit.description})}
 function reactivate(e:FormEvent,job:Job){e.preventDefault();if(!edit)return;void patch(job,'reactivate',{title:edit.title,area:edit.area,location:edit.location,public_location:edit.public_location,employer_visibility:edit.employer_visibility,mode:edit.mode,schedule:edit.schedule,salary:edit.salary,description:edit.description,requirements:edit.requirements})}
 const publicProfile=company&&jobs.some(j=>j.status==='published'&&j.employer_visibility!=='confidential')?`/empresas/perfil/${company.id}`:''
 if(!company&&!loading)return null
 return <section className="pm43-job-manager" id="publicaciones-empleo">
  <header className="pm43-job-manager-head"><div><span>MIS PUBLICACIONES · EMPLEOS</span><h2>Administrá tus búsquedas sin empezar de cero.</h2><p>Una búsqueda activa mantiene bloqueados sus datos principales: sólo podés corregir la descripción. Si la finalizás, queda guardada para reutilizarla más adelante usando un nuevo crédito.</p></div><div className="pm43-job-manager-head-actions">{publicProfile&&<Link href={publicProfile}>Ver perfil público</Link>}<Link href="/empresas/publicar" className="primary">+ Nueva búsqueda</Link></div></header>
  <div className="pm43-job-creditbar"><div><small>CRÉDITOS DE PUBLICACIÓN</small><b>{credits?.allowance===null?'Plan con publicaciones incluidas':`${credits?.remaining??'—'} disponibles este mes`}</b><span>{credits?.allowance===null?`Plan ${credits?.plan||'activo'} · cada reactivación queda registrada como una nueva publicación`:`Usaste ${credits?.used||0} de ${credits?.allowance||2} · publicar o reactivar consume 1 crédito`}</span></div><div className="pm43-job-counts"><b>{active}<small>activas</small></b><b>{closed}<small>finalizadas</small></b><b>{drafts}<small>borradores</small></b></div></div>
  <div className="pm43-job-tabs"><button data-on={filter==='all'} onClick={()=>setFilter('all')}>Todas · {jobs.length}</button><button data-on={filter==='published'} onClick={()=>setFilter('published')}>Activas · {active}</button><button data-on={filter==='closed'} onClick={()=>setFilter('closed')}>Finalizadas · {closed}</button></div>
  {notice&&<div className="pm43-job-notice ok">{notice}</div>}{error&&<div className="pm43-job-notice error">{error}</div>}
  {loading?<div className="pm43-job-empty">Cargando tus búsquedas…</div>:visible.length===0?<div className="pm43-job-empty"><b>No hay búsquedas en esta vista.</b><span>Podés publicar una nueva o cambiar el filtro.</span></div>:<div className="pm43-job-list">{visible.map(job=><article key={job.id} data-status={job.status}>
   <div className="pm43-job-summary"><div className="pm43-job-summary-top"><div><span data-status={job.status}>{statusLabel(job.status)}</span><small>{dateLabel(job.published_at||job.created_at)}</small></div>{job.status==='published'&&job.closes_at&&<small>Hasta {dateLabel(job.closes_at)}</small>}</div><h3>{job.title}</h3><p>{job.description||'Sin descripción'}</p><div className="pm43-job-meta"><span>{job.area||'Sin área'}</span><span>{job.location_text||'Zona a confirmar'}</span><span>{job.work_mode||'Modalidad a confirmar'}</span>{job.compensation_text&&<span>{job.compensation_text}</span>}</div>
    {editId!==job.id&&<div className="pm43-job-actions">{job.status==='published'&&<><button className="secondary" onClick={()=>startDescription(job)}>Editar descripción</button><button className="finish" onClick={()=>setConfirm({kind:'finish',job})}>Finalizar</button><button className="danger" onClick={()=>setConfirm({kind:'remove',job})}>Eliminar</button></>}{job.status==='closed'&&<><button className="reactivate" onClick={()=>startReuse(job)}>Editar y reactivar</button><button className="danger ghost" onClick={()=>setConfirm({kind:'remove',job})}>Eliminar</button></>}{job.status==='draft'&&<><button className="reactivate" onClick={()=>void patch(job,'publish_draft')}>Publicar usando 1 crédito</button><button className="danger ghost" onClick={()=>setConfirm({kind:'remove',job})}>Eliminar</button></>}{job.status==='paused'&&<><button className="finish" onClick={()=>setConfirm({kind:'finish',job})}>Finalizar</button><button className="danger" onClick={()=>setConfirm({kind:'remove',job})}>Eliminar</button></>}</div>}
   </div>
   {editId===job.id&&edit&&job.status==='published'&&<form className="pm43-job-editor compact" onSubmit={e=>saveDescription(e,job)}><div><span>EDICIÓN SEGURA</span><h4>Sólo la descripción</h4><p>Mientras el aviso está activo, título, zona, modalidad, salario y requisitos quedan bloqueados.</p></div><label>Descripción<textarea value={edit.description} onChange={e=>setEdit(v=>v?{...v,description:e.target.value}:v)} minLength={30} maxLength={10000} required/></label><div className="pm43-editor-actions"><button type="button" className="secondary" onClick={()=>{setEditId('');setEdit(null)}}>Cancelar</button><button disabled={busy||edit.description.trim().length<30}>{busy?'Guardando…':'Guardar descripción'}</button></div></form>}
   {editId===job.id&&edit&&job.status==='closed'&&<form className="pm43-job-editor" onSubmit={e=>reactivate(e,job)}><div className="pm43-reuse-head"><div><span>REUTILIZAR BÚSQUEDA FINALIZADA</span><h4>Ahora sí podés editar todo el aviso.</h4><p>Los cambios quedan sobre esta misma publicación. Al reactivarla vuelve a estar visible 30 días y consume un nuevo crédito.</p></div><strong>1 crédito</strong></div><div className="pm43-editor-grid"><label>Título<input value={edit.title} onChange={e=>setEdit(v=>v?{...v,title:e.target.value}:v)} required/></label><label>Área<input value={edit.area} onChange={e=>setEdit(v=>v?{...v,area:e.target.value}:v)}/></label><label>Zona<input value={edit.location} onChange={e=>setEdit(v=>v?{...v,location:e.target.value}:v)} required/></label><label>Modalidad<select value={edit.mode} onChange={e=>setEdit(v=>v?{...v,mode:e.target.value}:v)}><option>Presencial</option><option>Híbrido</option><option>Remoto</option></select></label><label>Jornada<select value={edit.schedule} onChange={e=>setEdit(v=>v?{...v,schedule:e.target.value}:v)}><option>Full time</option><option>Part time</option><option>Por turnos</option><option>Contrato</option></select></label><label>Salario / rango<input value={edit.salary} onChange={e=>setEdit(v=>v?{...v,salary:e.target.value}:v)} placeholder="Ej. $900.000 a $1.100.000"/></label><label className="full">Descripción<textarea value={edit.description} onChange={e=>setEdit(v=>v?{...v,description:e.target.value}:v)} minLength={30} required/></label><label className="full">Requisitos<textarea value={edit.requirements} onChange={e=>setEdit(v=>v?{...v,requirements:e.target.value}:v)} placeholder="Separalos con · o por línea"/></label><label>Identidad<select value={edit.employer_visibility} onChange={e=>setEdit(v=>v?{...v,employer_visibility:e.target.value}:v)}><option value="public">Mostrar empresa</option><option value="confidential">Empresa confidencial</option></select></label>{edit.employer_visibility==='confidential'&&<label>Ubicación pública<input value={edit.public_location} onChange={e=>setEdit(v=>v?{...v,public_location:e.target.value}:v)} placeholder="Ej. Buenos Aires" required/></label>}</div><div className="pm43-reactivate-warning"><b>Reactivar consume un nuevo crédito.</b><span>El crédito original no vuelve al finalizar. Esta reactivación cuenta como una publicación nueva.</span></div><div className="pm43-editor-actions"><button type="button" className="secondary" onClick={()=>{setEditId('');setEdit(null)}}>Cancelar</button><button className="reactivate" disabled={busy||edit.title.trim().length<3||edit.description.trim().length<30}>{busy?'Reactivando…':'Guardar y reactivar · 1 crédito'}</button></div></form>}
  </article>)}</div>}
  {confirm&&<div className="pm43-job-confirm" role="dialog" aria-modal="true"><section><span>{confirm.kind==='finish'?'FINALIZAR BÚSQUEDA':'ELIMINAR BÚSQUEDA'}</span><h3>{confirm.job.title}</h3><p>{confirm.kind==='finish'?'El aviso deja de estar visible, pero queda guardado como finalizado. Más adelante lo vas a poder editar completo y reactivar usando un nuevo crédito.':'El aviso desaparece de Mis publicaciones. No recupera el crédito usado y conservamos únicamente el historial técnico necesario para no romper postulaciones o conversaciones existentes.'}</p><div className="pm43-reactivate-warning"><b>El crédito ya utilizado no se reintegra.</b><span>{confirm.kind==='finish'?'Finalizar es la opción indicada si querés reutilizar este aviso después.':'Eliminar es para cuando ya no querés verlo en tu listado.'}</span></div><div><button className="secondary" onClick={()=>setConfirm(null)}>Volver</button><button className={confirm.kind==='remove'?'danger':'finish'} disabled={busy} onClick={()=>void patch(confirm.job,confirm.kind)}>{busy?'Procesando…':confirm.kind==='finish'?'Sí, finalizar':'Sí, eliminar'}</button></div></section></div>}
 </section>
}
