'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'

type Member={user_id:string;email?:string|null;role:string;status:string;created_at:string}
type Invite={id:string;email:string;role:string;status:string;expires_at:string}
type Summary={company:{id:string;name:string};my_role:string;team:{members:Member[];invites:Invite[]}}
const roleLabel:Record<string,string>={owner:'Propietario',admin:'Administrador',recruiter:'Recursos Humanos',hiring_manager:'Responsable que entrevista',viewer:'Sólo lectura'}
async function currentSession(){const {data}=await cvAuthClient().auth.getSession();return data.session}

export default function EmployerTeamPermissions(){
 const [data,setData]=useState<Summary|null>(null),[email,setEmail]=useState(''),[role,setRole]=useState('recruiter'),[inviteUrl,setInviteUrl]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 async function load(){setLoading(true);try{const s=await currentSession();if(!s)throw new Error('Iniciá sesión.');const r=await fetch('/api/postula/company/account',{headers:{Authorization:`Bearer ${s.access_token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos cargar el equipo.');setData(d)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos cargar el equipo.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 const pending=useMemo(()=>data?.team.invites.filter(x=>x.status==='pending')||[],[data])
 const canManage=Boolean(data&&['owner','admin'].includes(data.my_role))
 async function invite(e:FormEvent){e.preventDefault();if(!data||!canManage||busy)return;setBusy(true);setNotice('');setInviteUrl('');try{const s=await currentSession();if(!s)throw new Error('Iniciá sesión.');const r=await fetch('/api/postula/company/team',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({company_id:data.company.id,email,role})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos crear la invitación.');setInviteUrl(`${location.origin}${d.invite_url}`);setEmail('');setNotice(d.email_sent?'Invitación enviada por email. También podés copiar el enlace.':'Invitación creada. Copiá el enlace para compartirlo.');await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos invitar.')}finally{setBusy(false)}}
 async function change(member:Member,nextRole:string,nextStatus=member.status){if(!data||!canManage||member.role==='owner'||busy)return;setBusy(true);setNotice('');try{const s=await currentSession();if(!s)throw new Error('Iniciá sesión.');const r=await fetch('/api/postula/company/team',{method:'PATCH',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({company_id:data.company.id,user_id:member.user_id,role:nextRole,status:nextStatus})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos cambiar el permiso.');setNotice('Permiso actualizado.');await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos actualizar el permiso.')}finally{setBusy(false)}}
 if(loading)return <div className="pm51-loading">Cargando equipo y permisos…</div>
 if(!data)return <div className="pm51-empty">{notice||'No pudimos cargar el equipo.'}</div>
 return <section className="pm51-panel pm51-team">
  <div className="pm51-panel-head"><div><span>EQUIPO Y PERMISOS</span><h2>Una cuenta por persona.</h2><p>Definí quién puede administrar, seleccionar, entrevistar o solamente consultar. No hace falta compartir contraseñas.</p></div><div className="pm51-count"><strong>{data.team.members.filter(x=>x.status==='active').length}</strong><small>integrantes activos</small></div></div>
  <div className="pm51-role-guide"><article><b>Administrador</b><span>Configura empresa y equipo.</span></article><article><b>Recursos Humanos</b><span>Gestiona candidatos y procesos.</span></article><article><b>Entrevistador</b><span>Revisa perfiles y entrevistas.</span></article><article><b>Sólo lectura</b><span>Consulta sin modificar.</span></article></div>
  <div className="pm51-member-list">{data.team.members.map((m,i)=><div key={m.user_id} data-disabled={m.status!=='active'}><span className="pm51-member-avatar">{(m.email||String(i+1)).slice(0,2).toUpperCase()}</span><div><b>{m.email||`Integrante ${i+1}`}</b><small>{roleLabel[m.role]||m.role} · {m.status==='active'?'Activo':'Pausado'}</small></div>{canManage&&m.role!=='owner'?<><select value={m.role} aria-label={`Rol de ${m.email||'integrante'}`} disabled={busy} onChange={e=>void change(m,e.target.value)}><option value="admin">Administrador</option><option value="recruiter">Recursos Humanos</option><option value="hiring_manager">Responsable que entrevista</option><option value="viewer">Sólo lectura</option></select><button type="button" disabled={busy} onClick={()=>void change(m,m.role,m.status==='active'?'disabled':'active')}>{m.status==='active'?'Pausar acceso':'Reactivar'}</button></>:<span className="pm51-owner">{m.role==='owner'?'Propietario':'Sin edición'}</span>}</div>)}</div>
  {canManage&&<form className="pm51-invite" onSubmit={invite}><div><span>INVITAR PERSONA</span><b>Sumá a alguien con el permiso correcto.</b></div><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="rrhh@empresa.com"/></label><label>Rol<select value={role} onChange={e=>setRole(e.target.value)}><option value="recruiter">Recursos Humanos</option><option value="hiring_manager">Responsable que entrevista</option><option value="admin">Administrador</option><option value="viewer">Sólo lectura</option></select></label><button disabled={busy}>{busy?'Procesando…':'Invitar'}</button></form>}
  {inviteUrl&&<div className="pm51-invite-link"><b>Enlace de invitación</b><input readOnly value={inviteUrl}/><button type="button" onClick={()=>navigator.clipboard?.writeText(inviteUrl)}>Copiar</button></div>}
  {pending.length>0&&<div className="pm51-pending"><b>{pending.length} invitación{pending.length===1?' pendiente':'es pendientes'}</b>{pending.slice(0,6).map(x=><span key={x.id}>{x.email} · {roleLabel[x.role]||x.role}</span>)}</div>}
  {notice&&<p className="pm51-notice">{notice}</p>}
 </section>
}
