'use client'
import Link from 'next/link'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'

type Company={id:string;name:string;verification_status:string;trust_score:number}
type Job={id:string;title:string;status:string;location_text?:string;created_at?:string}
type App={id:string;job_id:string;candidate_user_id:string;resume_path?:string|null;cover_letter?:string|null;status:string;candidate_snapshot?:{display_name?:string;availability?:string;experience?:string;city?:string;phone?:string};pm_jobs?:{id?:string;title?:string;company_id?:string};pm_candidate_matches?:{score?:number;reasons?:string[];missing_evidence?:string[]}[]}
type Note={id:string;application_id:string;body:string;created_at:string}
type Handoff={id:string;application_id:string;recipient_user_id?:string;recipient_role?:string;status:string;created_at:string}
async function session(){const {data}=await cvAuthClient().auth.getSession();return data.session}
export default function EmployerDashboardLive(){
 const [company,setCompany]=useState<Company|null>(null),[role,setRole]=useState(''),[jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<App[]>([]),[notes,setNotes]=useState<Note[]>([]),[handoffs,setHandoffs]=useState<Handoff[]>([]),[teamCount,setTeamCount]=useState(0),[selected,setSelected]=useState(''),[note,setNote]=useState(''),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[me,setMe]=useState('')
 async function load(){const s=await session();if(!s){setLoading(false);return}setMe(s.user.id);const headers={Authorization:`Bearer ${s.access_token}`};const cr=await fetch('/api/postula/company',{headers});const cd=await cr.json().catch(()=>({}));const m=cd?.memberships?.[0];if(!m?.pm_companies){setLoading(false);return}const co={...m.pm_companies,id:m.company_id};setCompany(co);setRole(m.role);const [jr,ar,nr,tr,hr]=await Promise.all([fetch(`/api/postula/company/jobs?company=${co.id}`,{headers}),fetch(`/api/postula/applications?company=${co.id}`,{headers}),fetch(`/api/postula/company/notes?company=${co.id}`,{headers}),fetch(`/api/postula/company/team?company=${co.id}`,{headers}),fetch(`/api/postula/company/handoffs?company=${co.id}`,{headers})]);const [jd,ad,nd,td,hd]=await Promise.all([jr.json().catch(()=>({})),ar.json().catch(()=>({})),nr.json().catch(()=>({})),tr.json().catch(()=>({})),hr.json().catch(()=>({}))]);setJobs(jd.jobs||[]);setApps(ad.applications||[]);setNotes(nd.notes||[]);setTeamCount((td.members||[]).length);setHandoffs(hd.handoffs||[]);if(!selected&&ad.applications?.[0])setSelected(ad.applications[0].id);setLoading(false)}
 useEffect(()=>{void load()},[])
 const stats=useMemo(()=>({received:apps.length,viewed:apps.filter(x=>x.status==='viewed').length,shortlist:apps.filter(x=>x.status==='shortlist').length,interview:apps.filter(x=>x.status==='interview').length,hired:apps.filter(x=>x.status==='hired').length}),[apps])
 const current=apps.find(x=>x.id===selected)||apps[0];const currentNotes=notes.filter(n=>n.application_id===current?.id);const assigned=handoffs.filter(h=>h.recipient_user_id===me&&['pending','seen'].includes(h.status))
 async function changeStatus(id:string,status:string){const s=await session();if(!s)return;const r=await fetch('/api/postula/applications',{method:'PATCH',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({id,status})});const d=await r.json().catch(()=>({}));if(r.ok&&d?.ok)setApps(v=>v.map(x=>x.id===id?{...x,status}:x));else setNotice(d?.error||'No pudimos cambiar la etapa.')}
 async function addNote(e:FormEvent){e.preventDefault();if(!company||!current||!note.trim())return;const s=await session();if(!s)return;const r=await fetch('/api/postula/company/notes',{method:'POST',headers:{Authorization:`Bearer ${s.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({company_id:company.id,application_id:current.id,body:note})});const d=await r.json().catch(()=>({}));if(r.ok&&d?.note){setNotes(v=>[d.note,...v]);setNote('')}else setNotice(d?.error||'No pudimos guardar la nota.')}
 async function openResume(path?:string|null){if(!path)return setNotice('Esta postulación no tiene CV adjunto.');const {data,error}=await cvAuthClient().storage.from('postula-private').createSignedUrl(path,300);if(error||!data?.signedUrl)return setNotice('No pudimos abrir el CV.');window.open(data.signedUrl,'_blank','noopener,noreferrer')}
 if(loading)return <div className="pmed-loading">Cargando el panel de tu empresa…</div>
 if(!company)return <section className="pmed-empty"><span>EMPRESAS</span><h1>Armemos primero tu espacio de contratación.</h1><p>Creá la empresa, validá los datos básicos y después vas a poder publicar, sumar a RRHH y recibir postulaciones.</p><Link href="/empresas/registro">Configurar empresa</Link></section>
 return <section className="pmed-page"><div className="pmed-head"><div><span>PANEL DE SELECCIÓN</span><h1>{company.name}</h1><p>{role==='owner'?'Vista propietario':role==='recruiter'?'Vista Recursos Humanos':`Rol ${role}`} · {company.verification_status==='verified'?'empresa verificada':'validación básica'}</p></div><div><Link href="/empresas/movil">Abrir versión móvil</Link><Link href="/empresas/configuracion">Cuenta empresa</Link><Link href="/empresas/publicar" className="primary">Nueva búsqueda</Link></div></div>
 {assigned.length>0&&<div className="pmed-assigned"><div><b>Tenés {assigned.length} derivación{assigned.length===1?'':'es'} de candidatos.</b><span>Nexo o un integrante del equipo te dejó perfiles para revisar.</span></div><button onClick={()=>setSelected(assigned[0].application_id)}>Abrir primero</button></div>}
 <div className="pmed-metrics"><article><small>Recibidos</small><b>{stats.received}</b><span>todas las búsquedas</span></article><article><small>Shortlist</small><b>{stats.shortlist}</b><span>para revisar de cerca</span></article><article><small>Entrevistas</small><b>{stats.interview}</b><span>en proceso</span></article><article><small>Contratados</small><b>{stats.hired}</b><span>cerrados con éxito</span></article><article><small>Equipo</small><b>{teamCount}</b><span>usuarios activos</span></article></div>
 <div className="pmed-flow"><div className="pmed-flow-head"><div><span>EMBUDO</span><h2>Qué está pasando con tus candidatos.</h2></div><small>Los porcentajes son descriptivos de tu propio proceso, no una comparación con otras empresas.</small></div><div className="pmed-bars">{[['Recibidos',stats.received],['Vistos',stats.viewed],['Shortlist',stats.shortlist],['Entrevista',stats.interview],['Contratados',stats.hired]].map(([label,val])=><div key={String(label)}><span>{label}</span><i><b style={{width:`${stats.received?Math.max(3,(Number(val)/stats.received)*100):0}%`}}/></i><strong>{val}</strong></div>)}</div></div>
 <div className="pmed-grid"><article className="pmed-card"><div className="pmed-card-head"><div><span>BÚSQUEDAS</span><h2>Vacantes</h2></div><Link href="/empresas/publicar">Publicar</Link></div>{jobs.length?jobs.slice(0,10).map(j=><div className="pmed-job" key={j.id}><div><b>{j.title}</b><small>{j.location_text||'Ubicación a confirmar'}</small></div><span>{j.status}</span></div>):<div className="pmed-zero"><b>Todavía no publicaste.</b><p>Creá una búsqueda y empezá a recibir postulaciones dentro de la plataforma.</p></div>}</article><article className="pmed-card"><div className="pmed-card-head"><div><span>ATENCIÓN</span><h2>Para Recursos Humanos</h2></div></div><div className="pmed-hr-insights"><article><b>{apps.filter(x=>x.status==='submitted').length}</b><span>nuevos para revisar</span></article><article><b>{apps.filter(x=>x.status==='shortlist').length}</b><span>en shortlist</span></article><article><b>{assigned.length}</b><span>derivados a vos</span></article><article><b>{notes.length}</b><span>notas internas</span></article></div><div className="pmed-tip"><b>Usá notas como memoria del equipo.</b><p>Guardá hechos de la entrevista, dudas por validar y próximos pasos. Evitá opiniones sobre características personales que no estén relacionadas con el puesto.</p></div></article></div>
 <div className="pmed-candidates"><div className="pmed-candidate-list"><div className="pmed-card-head"><div><span>CANDIDATOS</span><h2>{apps.length} postulaciones</h2></div><button onClick={()=>location.assign('/empresas/movil')}>Preguntar a Nexo</button></div>{apps.length?apps.map((a,i)=>{const s=a.candidate_snapshot||{};const match=Array.isArray(a.pm_candidate_matches)?a.pm_candidate_matches[0]:undefined;return <button key={a.id} data-on={a.id===current?.id} onClick={()=>setSelected(a.id)}><span className="pmed-avatar">{String(s.display_name||`C${i+1}`).slice(0,2).toUpperCase()}</span><span className="pmed-candidate-name"><b>{s.display_name||'Candidato/a'}</b><small>{a.pm_jobs?.title||'Postulación'} · {s.availability||'sin disponibilidad declarada'}</small></span><span className="pmed-candidate-stage">{match?.score!=null?`${match.score}%`:a.status}</span></button>}):<div className="pmed-zero"><p>Todavía no hay candidatos.</p></div>}</div><aside className="pmed-candidate-detail">{current?(()=>{const s=current.candidate_snapshot||{};const match=Array.isArray(current.pm_candidate_matches)?current.pm_candidate_matches[0]:undefined;return <><div className="pmed-detail-top"><div><span>PERFIL</span><h2>{s.display_name||'Candidato/a'}</h2><p>{current.pm_jobs?.title||'Postulación'} · {s.city||'zona no informada'}</p></div>{match?.score!=null&&<strong>{match.score}%</strong>}</div><div className="pmed-detail-facts"><div><small>Disponibilidad</small><b>{s.availability||'No informada'}</b></div><div><small>Experiencia declarada</small><b>{s.experience||'No informada'}</b></div><div><small>Etapa</small><b>{current.status}</b></div></div>{current.cover_letter&&<div className="pmed-letter"><small>PRESENTACIÓN</small><p>{current.cover_letter}</p></div>}{match&&<div className="pmed-match"><small>MATCH EXPLICABLE</small>{match.reasons?.slice(0,4).map(x=><p key={x}>+ {x}</p>)}{match.missing_evidence?.slice(0,3).map(x=><p className="missing" key={x}>? {x}</p>)}</div>}<div className="pmed-detail-actions"><button onClick={()=>openResume(current.resume_path)}>Ver CV</button><button onClick={()=>changeStatus(current.id,'shortlist')}>Shortlist</button><button onClick={()=>changeStatus(current.id,'interview')}>Entrevista</button><button onClick={()=>changeStatus(current.id,'rejected')} className="quiet">No avanzar</button></div><form className="pmed-notes" onSubmit={addNote}><label>Nota interna<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Ej. confirmar disponibilidad del sábado…"/></label><button>Guardar nota</button></form><div className="pmed-note-list">{currentNotes.map(n=><article key={n.id}><p>{n.body}</p><small>{new Date(n.created_at).toLocaleString('es-AR')}</small></article>)}</div></>} )():<div className="pmed-zero"><p>Elegí un candidato.</p></div>}</aside></div>
 {notice&&<div className="pmed-notice">{notice}<button onClick={()=>setNotice('')}>×</button></div>}
 </section>
}
