'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'
import EmploymentReviewPanel from '../../postula-preview/EmploymentReviewPanel'
import PublicReputationBadge from '../../postula-preview/PublicReputationBadge'
import type {PublicReputation,ReputationIndicator} from '../../postula-preview/publicReputation'
import css from './EmployerReviewsHub.module.css'

type RawRep={count?:number;average?:number|null;indicator?:string}|null
type App={id:string;candidate_user_id:string;status:string;hired_at?:string|null;candidate_snapshot?:{display_name?:string;city?:string};candidate_reputation?:RawRep;pm_jobs?:{title?:string}|{title?:string}[]}
function first<T>(v:T|T[]|null|undefined):T|null{return Array.isArray(v)?v[0]||null:v||null}
function rep(value:RawRep):PublicReputation{const indicator=(['favorable','mixed','unfavorable'].includes(String(value?.indicator))?value?.indicator:'forming') as ReputationIndicator;return{count:Number(value?.count||0),average:value?.average==null?null:Number(value.average),indicator,label:indicator==='favorable'?'Favorable':indicator==='mixed'?'Mixto':indicator==='unfavorable'?'Desfavorable':'Indicador en formación'}}
function stage(v:string){return v==='submitted'?'Nueva':v==='viewed'?'CV visto':v==='shortlist'?'Shortlist':v==='interview'?'Entrevista':v==='hired'?'Contratado/a':v==='rejected'?'No avanza':v==='withdrawn'?'Retirada':v}

export default function EmployerReviewsHub(){
 const [apps,setApps]=useState<App[]>([]),[selected,setSelected]=useState(''),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 async function load(){try{const {data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token){setLoaded(true);return}const cr=await fetch('/api/postula/company',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const cd=await cr.json().catch(()=>({}));const companyId=cd?.memberships?.[0]?.company_id;if(!companyId){setLoaded(true);return}const ar=await fetch(`/api/postula/applications?company=${encodeURIComponent(companyId)}`,{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const ad=await ar.json().catch(()=>({}));if(ar.ok&&ad?.ok){const rows=ad.applications||[];setApps(rows);setSelected((current:string)=>current||rows.find((x:App)=>x.status==='hired')?.id||rows[0]?.id||'')}else setError(ad?.error||'No pudimos cargar las contrataciones.')}catch{setError('No pudimos cargar las contrataciones.')}finally{setLoaded(true)}}
 useEffect(()=>{void load()},[])
 const current=useMemo(()=>apps.find(a=>a.id===selected)||apps[0],[apps,selected])
 async function confirmHire(){if(!current||busy)return;if(!window.confirm(`¿Confirmás que contrataste a ${current.candidate_snapshot?.display_name||'esta persona'}? Al hacerlo se habilitan 10 días para que ambas partes puedan calificarse.`))return;setBusy(true);setError('');setNotice('');try{const {data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Iniciá sesión nuevamente.');const r=await fetch('/api/postula/applications',{method:'PATCH',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({id:current.id,status:'hired'})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos confirmar la contratación.');setApps(rows=>rows.map(a=>a.id===current.id?{...a,status:'hired',hired_at:d?.application?.hired_at||new Date().toISOString()}:a));setNotice('Contratación confirmada. La persona fue notificada y se habilitó la evaluación bilateral por 10 días.')}catch(e){setError(e instanceof Error?e.message:'No pudimos confirmar la contratación.')}finally{setBusy(false)}}
 if(!loaded)return <section className={css.hub}><div className={css.loading}>Cargando contrataciones y calificaciones…</div></section>
 if(!apps.length)return <section className={css.hub}><div className={css.head}><div><span>REPUTACIÓN LABORAL</span><h2>Contrataciones y calificaciones.</h2><p>Cuando tengas postulantes, desde acá vas a poder confirmar una contratación. Recién entonces se habilita la evaluación bilateral.</p></div><Link href="/politica-evaluaciones">Cómo funciona</Link></div><div className={css.empty}>Todavía no hay postulaciones para gestionar.</div></section>
 return <section className={css.hub} id="calificaciones"><div className={css.head}><div><span>REPUTACIÓN LABORAL</span><h2>Contrataciones y calificaciones.</h2><p>La calificación se habilita únicamente al confirmar una contratación. Desde ese momento, empresa y postulante tienen 10 días para evaluar, modificar y responder.</p></div><Link href="/politica-evaluaciones">Cómo funciona la evaluación →</Link></div><div className={css.layout}><div className={css.list}>{apps.map(a=><button type="button" className={css.item} data-on={a.id===current?.id} key={a.id} onClick={()=>{setSelected(a.id);setNotice('');setError('')}}><b>{a.candidate_snapshot?.display_name||'Candidato/a'}</b><small>{first(a.pm_jobs)?.title||'Postulación'}{a.candidate_snapshot?.city?` · ${a.candidate_snapshot.city}`:''}</small><span className={css.stage} data-hired={a.status==='hired'}>{stage(a.status)}</span></button>)}</div><div className={css.detail}>{current&&<><div className={css.summary}><h3>{current.candidate_snapshot?.display_name||'Candidato/a'}</h3><p>{first(current.pm_jobs)?.title||'Postulación'} · {stage(current.status)}</p>{current.candidate_reputation&&<div className={css.rep}><PublicReputationBadge reputation={rep(current.candidate_reputation)}/></div>}</div>{current.status==='hired'?<EmploymentReviewPanel applicationId={current.id}/>:!['rejected','withdrawn'].includes(current.status)?<div className={css.hire}><b>¿La persona fue contratada?</b><p>Confirmalo únicamente cuando la incorporación sea real. Al hacerlo, la opción de calificar se activa para ambas partes durante 10 días y se envía una notificación al postulante.</p><button type="button" disabled={busy} onClick={()=>void confirmHire()}>{busy?'Confirmando…':'Marcar como contratado/a'}</button></div>:<div className={css.empty}>Esta postulación está cerrada y no habilita una evaluación laboral.</div>}{notice&&<div className={css.notice}>{notice}</div>}{error&&<div className={css.error}>{error}</div>}</>}</div></div></section>
}
