'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'

type EmployerJob={id:string;title:string;location:string;status:string;applications:number;created:string}
type Feedback='volveria'|'neutral'|'no'|null
const seed:EmployerJob[]=[{id:'demo-ventas',title:'Vendedor/a de salón',location:'Belgrano · CABA',status:'Activa',applications:186,created:'Hace 3 días'},{id:'demo-recepcion',title:'Recepcionista · Hotel',location:'CABA · Turnos',status:'Revisión',applications:74,created:'Ayer'}]
const candidates=[
 {name:'Martina R.',score:94,role:'Vendedora · caja y atención',reason:'Experiencia directa + horario compatible',stage:'Shortlist',reference:'92% · 3 verificadas',image:'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Nicolás G.',score:87,role:'Atención al cliente · POS',reason:'Buen ajuste operativo; falta validar sábados',stage:'Entrevista',reference:'Sin señal suficiente',image:'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Camila P.',score:82,role:'Ventas · retail',reason:'Experiencia relevante; traslado a confirmar',stage:'Revisión',reference:'96% · 2 verificadas',image:'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Lucas F.',score:78,role:'Comercial junior',reason:'Buena evidencia de objetivos; menor experiencia',stage:'Revisión',reference:'Sin señal suficiente',image:'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Agustina M.',score:74,role:'Atención general',reason:'Buena comunicación; poca evidencia comercial',stage:'Revisión',reference:'Sin señal suficiente',image:'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=500'},
]

export default function EmployerDashboard(){
 const [jobs,setJobs]=useState<EmployerJob[]>(seed)
 const [routed,setRouted]=useState(false)
 const [plan,setPlan]=useState<'Gratis'|'Selección IA'>('Selección IA')
 const [mode,setMode]=useState<'owner'|'hr'>('owner')
 const [threshold,setThreshold]=useState(84)
 const [feedback,setFeedback]=useState<Feedback>(null)
 useEffect(()=>{try{const raw=localStorage.getItem('pm_preview_employer_jobs');if(raw){const local=JSON.parse(raw) as EmployerJob[];setJobs([...local,...seed])};const saved=localStorage.getItem('pm_preview_reference_feedback') as Feedback;if(saved)setFeedback(saved)}catch{}},[])
 const total=useMemo(()=>jobs.reduce((n,j)=>n+j.applications,0),[jobs])
 const visibleCandidates=useMemo(()=>mode==='owner'?candidates.filter(c=>c.score>=threshold):candidates,[mode,threshold])
 function saveFeedback(value:Exclude<Feedback,null>){setFeedback(value);try{localStorage.setItem('pm_preview_reference_feedback',value)}catch{}}
 return <div className="pm7-biz-shell">
  <aside className="pm7-biz-left"><div className="pm7-biz-account"><span className="pm7-biz-logo">CO</span><div><small>EMPRESA DEMO</small><b>Comercio · Belgrano</b></div></div><nav><a href="#inicio" className="on">Inicio</a><a href="#busquedas">Búsquedas</a><a href="#candidatos">Candidatos</a><a href="#referencias">Referencias</a><a href="#equipo">Equipo</a><Link href="/empresas-preview/movil">Nexo móvil <small>NUEVO</small></Link></nav><div className="pm7-biz-plan"><span>{plan}</span><b>{plan==='Gratis'?'10 perfiles visibles':'2.000 postulaciones / mes'}</b><button onClick={()=>setPlan(plan==='Gratis'?'Selección IA':'Gratis')}>Cambiar vista de plan</button></div></aside>

  <main className="pm7-biz-main" id="inicio"><header className="pm7-biz-hello"><div><span className="pm7-eyebrow lime">PANEL DE SELECCIÓN</span><h1>Buen día.<br/><em>¿A quién buscamos?</em></h1><p>Todo lo importante de tus búsquedas, sin convertir el día en administración de CV.</p></div><div className="pm7-biz-actions"><Link href="/empresas-preview/publicar">＋ Nueva búsqueda</Link><button onClick={()=>setMode(mode==='owner'?'hr':'owner')}>{mode==='owner'?'Modo dueño':'Modo RRHH'}</button></div></header>

   <section className="pm7-biz-metrics"><article><span>BÚSQUEDAS</span><b>{jobs.length}</b><small>{jobs.filter(j=>j.status==='Activa').length} activas</small></article><article><span>POSTULACIONES</span><b>{total}</b><small>{plan==='Gratis'?'10 visibles en plan gratis':'incluidas este mes'}</small></article><article><span>{mode==='owner'?'PARA MIRAR':'SHORTLIST'}</span><b>{mode==='owner'?visibleCandidates.length:12}</b><small>{mode==='owner'?'con tu umbral actual':'siempre revisable'}</small></article><article><span>TIEMPO AHORRADO</span><b>7,4 h</b><small>estimación de preview</small></article></section>

   <section className="pm7-biz-section" id="busquedas"><div className="pm7-biz-section-head"><div><span>TUS BÚSQUEDAS</span><h2>Lo que está pasando ahora.</h2></div><Link href="/empresas-preview/publicar">Publicar otra →</Link></div><div className="pm7-biz-job-row">{jobs.slice(0,4).map((job,i)=><article key={job.id}><div className={`pm7-biz-job-art a${i}`}><span>{job.status}</span><b>{job.applications}</b><small>postulaciones</small></div><div><h3>{job.title}</h3><p>{job.location}</p><small>{job.created}</small><button>Ver candidatos →</button></div></article>)}</div></section>

   <section className="pm7-biz-section" id="candidatos"><div className="pm7-biz-section-head"><div><span>VENDEDOR/A DE SALÓN · BELGRANO</span><h2>Personas que vale la pena mirar.</h2><p>{mode==='owner'?'Modo dueño: Nexo reduce el ruido según el umbral que elegís.':'Modo RRHH: ves el embudo completo y los casos limítrofes.'}</p></div><div className="pm7-biz-threshold"><small>Mostrar desde</small><b>{threshold}%</b><input type="range" min="70" max="95" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/></div></div><div className="pm7-biz-candidate-grid">{visibleCandidates.map(c=><article key={c.name}><div className="pm7-biz-candidate-photo" style={{backgroundImage:`url(${c.image})`}}><span>{c.score}%</span><button>♡</button></div><div className="pm7-biz-candidate-copy"><div><h3>{c.name}</h3><em>{c.stage}</em></div><p>{c.role}</p><small>{c.reason}</small><div className="pm7-biz-ref"><span>Referencia general</span><b>{c.reference}</b></div><button>Ver perfil completo</button></div></article>)}</div><div className="pm7-biz-explain"><span>NX</span><p><b>Nexo explica el orden:</b> Martina aparece arriba por experiencia de caja, venta presencial y disponibilidad declarada. La foto y la referencia general no modifican el ranking.</p></div></section>

   <section className="pm7-biz-split"><article className="pm7-biz-reference" id="referencias"><span className="pm7-eyebrow blue">REFERENCIA LABORAL · DEMO</span><h2>Una señal simple, con límites.</h2><p>Después de una relación laboral verificada se puede dejar una señal general. No entra al match, la persona puede verla y pedir revisión.</p><div className="pm7-biz-feedback"><button data-on={feedback==='volveria'} onClick={()=>saveFeedback('volveria')}>Volvería a trabajar</button><button data-on={feedback==='neutral'} onClick={()=>saveFeedback('neutral')}>Sin opinión suficiente</button><button data-on={feedback==='no'} onClick={()=>saveFeedback('no')}>No volvería a trabajar</button></div><small>{feedback?'Guardado sólo en esta preview.':'Elegí una opción para probar la interacción.'}</small></article><article className="pm7-biz-routing" id="equipo"><span className="pm7-eyebrow lime">EQUIPO</span><h2>¿Quién sigue con la shortlist?</h2><p>Derivá dentro de la misma cuenta. Nexo mantiene el contexto de empresa y búsqueda.</p><label>Destino<select><option>María · Recursos Humanos</option><option>Gerente de sucursal</option><option>Administrador general</option><option>Entrevisto yo</option></select></label><button onClick={()=>setRouted(true)}>{routed?'Derivación preparada ✓':'Preparar derivación'}</button>{routed&&<small>Preview: no se envió ningún CV ni correo real.</small>}</article></section>

   <section className="pm7-biz-section"><div className="pm7-biz-section-head"><div><span>PIPELINE</span><h2>De 186 a una conversación.</h2></div></div><div className="pm7-biz-pipeline"><div><b>186</b><span>Recibidos</span></div><i>→</i><div><b>42</b><span>Revisión</span></div><i>→</i><div><b>12</b><span>Shortlist</span></div><i>→</i><div><b>4</b><span>Entrevista</span></div></div></section>
  </main>

  <aside className="pm7-biz-right"><article className="pm7-biz-nexo"><div className="pm7-biz-nexo-head"><span>NX</span><div><b>Nexo</b><small>tu búsqueda, resumida</small></div><i/></div><p>“Tengo 186 postulaciones. Hay 12 perfiles fuertes y 4 listos para entrevista.”</p><div className="pm7-biz-nexo-quick"><Link href="/empresas-preview/movil">Dame los 5 mejores</Link><Link href="/empresas-preview/movil">¿Quién puede sábados?</Link><Link href="/empresas-preview/movil">Preparar entrevista</Link></div><Link className="pm7-biz-open-nexo" href="/empresas-preview/movil">Abrir Nexo móvil →</Link></article><article className="pm7-biz-agent-status"><span>AGENTES</span>{[['Selector','activo'],['Coordinador','3 pendientes'],['Entrevista','4 listas'],['Auditor','sin alertas']].map(([a,s])=><div key={a}><i/><b>{a}</b><small>{s}</small></div>)}</article><article className="pm7-biz-tip"><span>HOY</span><p>El mayor ahorro no está en leer CV más rápido. Está en no leer los que no necesitabas abrir.</p></article></aside>
 </div>
}
