'use client'

import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import styles from '../../postula-preview/platform.module.css'

type EmployerJob={id:string;title:string;location:string;status:string;applications:number;created:string}
const seed:EmployerJob[]=[{id:'demo-ventas',title:'Vendedor/a de salón · Belgrano',location:'CABA · Presencial',status:'Activa',applications:186,created:'Hace 3 días'},{id:'demo-recepcion',title:'Recepcionista · Hotel',location:'CABA · Turnos',status:'Revisión',applications:74,created:'Ayer'}]
const candidates=[
 {name:'Martina R.',score:94,role:'Vendedora · caja y atención',reason:'Experiencia directa + horario compatible',stage:'Shortlist'},
 {name:'Nicolás G.',score:87,role:'Atención al cliente · POS',reason:'Buen ajuste operativo; falta validar sábados',stage:'Entrevista'},
 {name:'Camila P.',score:82,role:'Ventas · retail',reason:'Experiencia relevante; traslado a confirmar',stage:'Revisión'},
 {name:'Lucas F.',score:78,role:'Comercial junior',reason:'Buena evidencia de objetivos; menor experiencia',stage:'Revisión'},
 {name:'Agustina M.',score:74,role:'Atención general',reason:'Buena comunicación; poca evidencia comercial',stage:'Revisión'},
]

export default function EmployerDashboard(){
 const [jobs,setJobs]=useState<EmployerJob[]>(seed)
 const [routed,setRouted]=useState(false)
 const [plan,setPlan]=useState<'Gratis'|'Selección IA'>('Selección IA')
 const [mode,setMode]=useState<'owner'|'hr'>('owner')
 const [threshold,setThreshold]=useState(84)
 useEffect(()=>{try{const raw=localStorage.getItem('pm_preview_employer_jobs');if(raw){const local=JSON.parse(raw) as EmployerJob[];setJobs([...local,...seed])}}catch{}},[])
 const total=useMemo(()=>jobs.reduce((n,j)=>n+j.applications,0),[jobs])
 const visibleCandidates=useMemo(()=>mode==='owner'?candidates.filter(c=>c.score>=threshold):candidates,[mode,threshold])
 return <div className={styles.dashShell}>
  <aside className={styles.sidebar}><div className={styles.sideSection}><div className={styles.sideTitle}>Empresa</div><Link href="/empresas-preview/panel" className={`${styles.sideLink} ${styles.sideActive}`}>Resumen</Link><Link href="/empresas-preview/publicar" className={styles.sideLink}>Publicar búsqueda</Link><a href="#postulantes" className={styles.sideLink}>Postulantes</a><a href="#equipo" className={styles.sideLink}>Equipo y roles</a></div><div className={styles.sideSection}><div className={styles.sideTitle}>Control</div><a href="#agentes" className={styles.sideLink}>Agentes IA</a><a href="#consumo" className={styles.sideLink}>Plan y consumo</a><Link href="/empresas-preview/registro" className={styles.sideLink}>Verificación</Link></div></aside>
  <section className={styles.dashMain}>
   <div className={styles.dashTop}><div><h1>Panel de selección.</h1><p>Preview · empresa demo · datos sintéticos</p></div><div style={{display:'flex',gap:8,alignItems:'center',flexWrap:'wrap'}}><button onClick={()=>setMode(mode==='owner'?'hr':'owner')} className={styles.planPill} style={{border:0,cursor:'pointer'}}>{mode==='owner'?'MODO DUEÑO':'MODO RRHH'}</button><button onClick={()=>setPlan(plan==='Gratis'?'Selección IA':'Gratis')} className={styles.planPill} style={{border:0,cursor:'pointer'}}>{plan.toUpperCase()}</button><Link href="/empresas-preview/publicar" className={styles.buttonDark}>Nueva búsqueda</Link></div></div>
   <div className={styles.metricGrid}><div className={styles.metric}><small>Búsquedas</small><strong>{jobs.length}</strong><span>{jobs.filter(j=>j.status==='Activa').length} activas</span></div><div className={styles.metric}><small>Postulaciones</small><strong>{total}</strong><span>{plan==='Gratis'?'10 visibles en plan gratis':'2.000 incluidas / mes'}</span></div><div className={styles.metric}><small>{mode==='owner'?'Finalistas visibles':'Shortlist sugerida'}</small><strong>{mode==='owner'?visibleCandidates.length:12}</strong><span>{mode==='owner'?'filtrado fuerte para ahorrar tiempo':'siempre revisable'}</span></div><div className={styles.metric}><small>Tiempo estimado ahorrado</small><strong>7.4h</strong><span>estimación de preview</span></div></div>
   <div className={styles.dashGrid}><article className={styles.panel}><div className={styles.panelHead}><h2>Búsquedas recientes</h2><Link href="/empresas-preview/publicar">Crear aviso</Link></div>{jobs.slice(0,5).map(job=><div className={styles.applicationRow} key={job.id}><div><strong>{job.title}</strong><small>{job.location} · {job.applications} postulaciones · {job.created}</small></div><span className={styles.status}>{job.status}</span></div>)}</article><article className={`${styles.panel} ${styles.upgrade}`} id="consumo"><span className={styles.miniLabel}>{plan==='Gratis'?'Plan gratis':'Selección IA'}</span><h2 style={{fontSize:24,margin:'8px 0'}}>{plan==='Gratis'?'Probá el flujo completo antes de pagar.':'Automatización con límites claros.'}</h2><p>{plan==='Gratis'?'2 avisos por mes, 30 días y primeras 10 postulaciones completas.':'Hasta 2.000 postulaciones al mes, shortlist explicada, entrevistas y routing a RRHH.'}</p><div className={styles.featureList}><span>Mercado Pago como único cobro previsto</span><span>La cuenta permanece aunque venza el plan</span><span>Consumo visible antes de alcanzar el límite</span></div></article></div>
   <article className={styles.panel} id="postulantes" style={{marginTop:14}}><div className={styles.panelHead}><div><h2>Postulantes · Vendedor/a de salón</h2><p style={{margin:'4px 0 0',fontSize:12,color:'#748495'}}>{mode==='owner'?'Modo dueño: te mostramos sólo perfiles que superan el umbral elegido para que no hagas trabajo de RRHH.':'Modo RRHH: ves todo el embudo y podés revisar casos limítrofes.'}</p></div><span className={styles.status}>186 recibidos</span></div>{mode==='owner'&&<div className={styles.aiNote}><b>Filtro de tiempo:</b> Mostrar perfiles con match explicable desde <strong>{threshold}%</strong>. <input aria-label="Umbral de shortlist" type="range" min="70" max="95" value={threshold} onChange={e=>setThreshold(Number(e.target.value))} style={{width:'180px',verticalAlign:'middle',marginLeft:10}}/> <span style={{fontSize:11}}>Podés bajarlo si querés ampliar la mirada.</span></div>}<div className={styles.compareTable}><table><thead><tr><th>Candidato</th><th>Match</th><th>Por qué aparece</th><th>Etapa</th></tr></thead><tbody>{visibleCandidates.map(c=><tr key={c.name}><td>{c.name}<br/><span style={{fontWeight:400,color:'#7a8997'}}>{c.role}</span></td><td className={styles.good}>{c.score}%</td><td>{c.reason}</td><td><span className={styles.status}>{c.stage}</span></td></tr>)}</tbody></table></div><div className={styles.aiNote}><b>Selector:</b> “Martina aparece primero porque reúne experiencia de caja, venta presencial y disponibilidad declarada. No evalué foto, edad, género ni datos sensibles. Recomendación: validar objetivos comerciales y disponibilidad de fin de semana.”</div></article>
   <div className={styles.dashGrid}><article className={styles.panel} id="agentes"><div className={styles.panelHead}><h2>Agentes de esta búsqueda</h2><span className={styles.status}>5 activos</span></div>{[['Publicador','Aviso revisado','100%'],['Selector','186 perfiles ordenados','100%'],['Coordinador','3 seguimientos pendientes','72%'],['Entrevista','4 guías preparadas','84%'],['Auditor','Sin alertas críticas','100%']].map(([a,b,c])=><div className={styles.applicationRow} key={a}><div><strong>{a}</strong><small>{b}</small></div><span className={styles.status}>{c}</span></div>)}</article><article className={styles.panel} id="equipo"><div className={styles.panelHead}><h2>Derivación interna</h2><span className={styles.status}>RRHH / dueño</span></div><p style={{fontSize:13,lineHeight:1.6,color:'#657788'}}>Elegí quién continúa. Si sos dueño, podés quedarte con la shortlist. Si tenés RRHH, el Coordinador deriva sólo los perfiles que cumplen tus reglas, con trazabilidad.</p><div className={styles.field}><label>Destino de la shortlist</label><select><option>Recursos Humanos · Selección</option><option>Gerente de sucursal</option><option>Administrador general</option><option>Entrevisto yo</option></select></div><button className={styles.buttonDark} onClick={()=>setRouted(true)}>{routed?'Derivación preparada':'Preparar derivación'}</button>{routed&&<div className={styles.securityBadge}>Preview: se preparó la acción, pero no se envió ningún email ni CV real.</div>}</article></div>
   <article className={styles.panel} style={{marginTop:14}}><div className={styles.panelHead}><h2>Pipeline de contratación</h2></div><div className={styles.flow}><div className={styles.flowCard}><span className={styles.flowNo}>186</span><h3>Recibidos</h3><p>CV + respuestas normalizadas y deduplicadas.</p></div><div className={styles.flowCard}><span className={styles.flowNo}>42</span><h3>Revisión</h3><p>Cumplen señales suficientes para mirar con más detalle.</p></div><div className={styles.flowCard}><span className={styles.flowNo}>12</span><h3>Shortlist</h3><p>Razones visibles y dudas que todavía hay que confirmar.</p></div><div className={styles.flowCard}><span className={styles.flowNo}>4</span><h3>Entrevista</h3><p>Guía específica y scorecard para comparar evidencia.</p></div></div></article>
  </section>
 </div>
}
