import styles from '../../postula-preview/platform.module.css'
import {PlatformHeader} from '../../postula-preview/PlatformChrome'
import SupportHelp from '../../postula-preview/SupportHelp'
import EmployerWorkspace from './EmployerWorkspace'
import '../../postula-preview/premium-v5.css'
import '../../postula-preview/premium-v6.css'
import '../../postula-preview/premium-v7.css'
import '../../postula-preview/premium-v7-employer-dashboard.css'
import '../../postula-preview/inner-v5.css'
import '../../postula-preview/support-help-v21.css'
import '../../postula-preview/notifications-v16.css'
import '../../changas-preview/flex-manage-v37.css'
import '../../changas-preview/flex-market-v39.css'
import '../../mi-postula-preview/account-flex-v38.css'
import '../configuracion/settings.css'
import '../configuracion/branding-v31.css'
import '../configuracion/notifications-accordion.css'
import './dashboard-live.css'
import './dashboard-onboarding-v18.css'
import './panel-organization.css'
import './messaging-v25.css'
import './panel-readability-v26.css'
import './panel-loading-v42.css'
import './job-manager-v43.css'
import './dashboard-v48.css'
import './dashboard-v49.css'
import './dashboard-v50.css'
export const metadata={title:{absolute:'Dashboard empresa | Postulá Mejor'},robots:{index:false,follow:false},alternates:{canonical:'https://postulamejor.com/empresas/panel'}}
export default function EmployerPanel(){return <main className={`${styles.page} pm7-page pm7-employer`}><PlatformHeader audience="employer"/><EmployerWorkspace/><SupportHelp audience="employer"/></main>}
