'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type Ticket={id:string;audience:string;category:string;priority:number;subject:string;status:string;page_path?:string|null;created_at:string;last_message_at:string;pm_companies?:{name?:string}|null}
type Message={id:string;sender_kind:'user'|'support'|'system';body:string;created_at:string}
const categoryLabel:Record<string,string>={security_fraud:'Seguridad / posible estafa',user_problem:'Problema con usuario',payment:'Pago / plan / créditos',publishing:'Postulación / publicación',technical:'Problema técnico',how_to:'Cómo usar la plataforma',other:'Otra consulta'}
const statusLabel:Record<string,string>={open:'Nuevo',waiting_support:'Esperando soporte',waiting_user:'Esperando usuario',resolved:'Resuelto',closed:'Cerrado'}

export default function SupportAdminClient(){
 const [tickets,setTickets]=useState<Ticket[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<any>(null),[reply,setReply]=useState(''),[filter,setFilter]=useState('active'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authorized,setAuthorized]=useState<boolean|null>(null),[unseen,setUnseen]=useState(0)
 async function token(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token||''}
 async function request(url:string,init:RequestInit={}){const access=await token();if(!access)throw new Error('Iniciá sesión con la cuenta administradora.');const r=await fetch(url,{...init,headers:{...(init.headers||{}),Authorization:`Bearer ${access}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos completar la operación.');return d}
 async function load(){setError('');try{const d=await request('/api/postula/support/admin');setTickets(d.tickets||[]);setUnseen(d.unseen_alerts||0);setAuthorized(true);const wanted=new URLSearchParams(location.search).get('ticket');const first=wanted||(d.tickets||[])[0]?.id;if(first){setSelected(first);await loadDetail(first)}}catch(e){setAuthorized(false);setError(e instanceof Error?e.message:'No pudimos abrir soporte.')}}
 async function loadDetail(id:string){try{const d=await request(`/api/postula/support/admin?ticket=${encodeURIComponent(id)}`);setDetail(d);setSelected(id);history.replaceState(null,'',`/soporte-admin?ticket=${encodeURIComponent(id)}`)}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir el caso.')}}
 useEffect(()=>{void load()},[])
 const visible=useMemo(()=>tickets.filter(t=>filter==='all'?true:filter==='urgent'?t.priority===1&&!['resolved','closed'].includes(t.status):filter==='active'?!['resolved','closed'].includes(t.status):t.status===filter),[tickets,filter])
 async function action(payload:any){setBusy(true);setError('');try{const d=await request('/api/postula/support/admin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({ticket_id:selected,...payload})});await Promise.all([load(),loadDetail(selected)]);return d}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar el cambio.')}finally{setBusy(false)}}
 async function send(e:FormEvent){e.preventDefault();if(!reply.trim())return;const text=reply;const d=await action({action:'reply',message:text});if(d)setReply('')}
 if(authorized===null)return <main className="pmsa-shell"><div className="pmsa-loading">Cargando bandeja de soporte…</div></main>
 if(authorized===false)return <main className="pmsa-shell"><section className="pmsa-access"><span>POSTULÁ MEJOR · SOPORTE</span><h1>Bandeja privada.</h1><p>{error||'Esta sección está reservada para administración.'}</p><a href="/cuenta">Iniciar sesión</a></section></main>
 const ticket=detail?.ticket as Ticket|undefined;const messages=(detail?.messages||[]) as Message[]
 return <main className="pmsa-shell">
  <header className="pmsa-top"><div><span>POSTULÁ MEJOR · OPERACIONES</span><h1>Soporte</h1><p>Casos ordenados por urgencia y último movimiento.</p></div><div className="pmsa-top-actions"><b>{unseen} alerta{unseen===1?'':'s'} nueva{unseen===1?'':'s'}</b><a href="/empresas/panel">Panel empresa</a><a href="/">Ver sitio</a></div></header>
  <section className="pmsa-stats"><article><small>Activos</small><b>{tickets.filter(t=>!['resolved','closed'].includes(t.status)).length}</b></article><article className="urgent"><small>Prioridad alta</small><b>{tickets.filter(t=>t.priority===1&&!['resolved','closed'].includes(t.status)).length}</b></article><article><small>Esperando soporte</small><b>{tickets.filter(t=>t.status==='waiting_support'||t.status==='open').length}</b></article><article><small>Resueltos</small><b>{tickets.filter(t=>t.status==='resolved').length}</b></article></section>
  <div className="pmsa-layout">
   <aside className="pmsa-list"><div className="pmsa-filters">{[['active','Activos'],['urgent','Urgentes'],['waiting_support','Responder'],['waiting_user','Usuario'],['resolved','Resueltos'],['all','Todos']].map(([id,label])=><button key={id} data-on={filter===id} onClick={()=>setFilter(id)}>{label}</button>)}</div><div className="pmsa-list-scroll">{visible.length?visible.map(t=><button key={t.id} className="pmsa-ticket" data-on={selected===t.id} onClick={()=>void loadDetail(t.id)}><span className={`pmsa-priority p${t.priority}`}>P{t.priority}</span><span className="pmsa-ticket-copy"><b>{t.subject}</b><small>{categoryLabel[t.category]||t.category} · {t.audience==='employer'?'Empleador':'Postulante'}</small><em>{t.pm_companies?.name||statusLabel[t.status]||t.status}</em></span><time>{new Date(t.last_message_at||t.created_at).toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit'})}</time></button>):<div className="pmsa-empty">No hay casos en este filtro.</div>}</div></aside>
   <section className="pmsa-detail">{ticket?<><div className="pmsa-detail-head"><div><div className="pmsa-kicker"><span className={`pmsa-priority p${ticket.priority}`}>PRIORIDAD {ticket.priority}</span><span>{statusLabel[ticket.status]||ticket.status}</span></div><h2>{ticket.subject}</h2><p>{categoryLabel[ticket.category]||ticket.category} · {ticket.audience==='employer'?'Empleador':'Postulante'} · {detail?.requester?.email||'email no disponible'}</p>{ticket.page_path&&<small>Origen: {ticket.page_path}</small>}</div><div className="pmsa-controls"><select value={ticket.priority} onChange={e=>void action({action:'priority',priority:Number(e.target.value)})} disabled={busy}><option value={1}>P1 · Urgente</option><option value={2}>P2 · Alta</option><option value={3}>P3 · Media</option><option value={4}>P4 · Normal</option></select><select value={ticket.status} onChange={e=>void action({action:'status',status:e.target.value})} disabled={busy}><option value="open">Nuevo</option><option value="waiting_support">Esperando soporte</option><option value="waiting_user">Esperando usuario</option><option value="resolved">Resuelto</option><option value="closed">Cerrado</option></select></div></div>
    <div className="pmsa-thread">{messages.map(m=><article key={m.id} className={`pmsa-msg ${m.sender_kind}`}><div><b>{m.sender_kind==='support'?'Soporte':m.sender_kind==='system'?'Sistema':'Usuario'}</b><time>{new Date(m.created_at).toLocaleString('es-AR')}</time></div><p>{m.body}</p></article>)}</div>
    <form className="pmsa-reply" onSubmit={send}><label>Responder al usuario<textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Escribí una respuesta clara. Al enviarla también se avisa por email…"/></label><div><small>El caso pasa automáticamente a “Esperando usuario”.</small><button disabled={busy||reply.trim().length<2}>{busy?'Enviando…':'Enviar respuesta'}</button></div></form>
   </>:<div className="pmsa-empty big">Elegí un caso para ver la conversación.</div>}</section>
  </div>{error&&<div className="pmsa-error">{error}<button onClick={()=>setError('')}>×</button></div>}
 </main>
}
