import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import forge from "npm:node-forge@1.3.1";

type Profile={company_id:string;role:string;active:boolean};
type CredRow={company_id:string;private_key_secret_id:string|null;certificate_secret_id:string|null;csr_pem:string|null;certificate_subject:string|null;certificate_expires_at:string|null};
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
function cors(req:Request){const o=req.headers.get('origin')||'';const ok=o==='https://comerciolleno.com'||o==='https://www.comerciolleno.com'||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(o);return{'Access-Control-Allow-Origin':ok?o:'https://www.comerciolleno.com','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:cors(req)})}
function jwtPayload(req:Request){try{const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');const p=t.split('.')[1];if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(p.length/4)*4,'=')))}catch{return null}}
function headers(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,'Content-Type':'application/json',...extra}}
async function admin(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:headers(init.headers as Record<string,string>||{})})}
async function profile(uid:string):Promise<Profile|null>{const r=await admin(`profiles?id=eq.${encodeURIComponent(uid)}&select=company_id,role,active&limit=1`);const a=await r.json();return a?.[0]||null}
async function creds(cid:string):Promise<CredRow|null>{const r=await admin(`arca_tenant_credentials?company_id=eq.${encodeURIComponent(cid)}&select=*&limit=1`);const a=await r.json();return a?.[0]||null}
async function setting(cid:string){const r=await admin(`arca_tenant_settings?company_id=eq.${encodeURIComponent(cid)}&select=enabled,environment,tax_id,point_of_sale,receipt_type,credential_slot&limit=1`);const a=await r.json();return a?.[0]||null}
async function rpc(name:string,body:any){const r=await admin(`rpc/${name}`,{method:'POST',body:JSON.stringify(body)});const x=await r.json().catch(()=>null);if(!r.ok)throw new Error(x?.message||`No se pudo ejecutar ${name}`);return x}
async function storeSecret(existing:string|null,name:string,value:string,description:string){return String(await rpc('arca_vault_upsert_secret',{p_secret_id:existing,p_name:name,p_secret:value,p_description:description}))}
async function readSecret(id:string|null){if(!id)return null;return await rpc('arca_vault_read_secret',{p_secret_id:id}) as string|null}
function digits(v:unknown){return String(v||'').replace(/\D/g,'')}
function validTaxId(v:string){return /^\d{11}$/.test(v)}
function certInfo(pem:string){const cert=forge.pki.certificateFromPem(pem);const attrs=cert.subject.attributes.map(a=>`${a.shortName||a.name}=${a.value}`).join(', ');const serial=cert.subject.getField('serialNumber')?.value||'';return{cert,subject:attrs,serial:String(serial),expires:cert.validity.notAfter.toISOString()}}
function keysMatch(cert:forge.pki.Certificate,key:forge.pki.rsa.PrivateKey){const pub=cert.publicKey as forge.pki.rsa.PublicKey;return pub.n.compareTo(key.n)===0&&pub.e.compareTo(key.e)===0}
async function upsertCred(cid:string,patch:Record<string,unknown>){const r=await admin('arca_tenant_credentials?on_conflict=company_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({company_id:cid,...patch,updated_at:new Date().toISOString()})});const a=await r.json().catch(()=>[]);if(!r.ok)throw new Error(a?.message||'No se pudieron guardar las credenciales de ARCA.');return a?.[0]}
async function clearTicket(cid:string){await admin(`arca_wsaa_cache?company_id=eq.${encodeURIComponent(cid)}`,{method:'DELETE'}).catch(()=>{})}
function statusPayload(c:CredRow|null,s:any){return{ok:true,configured:Boolean(s?.enabled&&c?.certificate_secret_id&&c?.private_key_secret_id),tax_id:s?.tax_id||null,environment:s?.environment||'produccion',point_of_sale:s?.point_of_sale||null,receipt_type:s?.receipt_type||11,credential_slot:s?.credential_slot||null,csr_pem:c?.csr_pem||null,private_key_ready:Boolean(c?.private_key_secret_id),certificate_ready:Boolean(c?.certificate_secret_id),certificate_subject:c?.certificate_subject||null,certificate_expires_at:c?.certificate_expires_at||null}}

Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{ok:false,error:'Método no permitido'},405);const p=jwtPayload(req);if(!p?.sub||p.role!=='authenticated')return json(req,{ok:false,error:'Sesión requerida'},401);const pr=await profile(p.sub);if(!pr?.active||!pr.company_id)return json(req,{ok:false,error:'Usuario sin comercio activo'},403);if(pr.role!=='owner')return json(req,{ok:false,error:'Sólo el propietario puede configurar ARCA'},403);let body:any={};try{body=await req.json()}catch{};const action=String(body.action||'status');const cid=pr.company_id;
 try{
  if(action==='status')return json(req,statusPayload(await creds(cid),await setting(cid)));
  if(action==='generate_csr'){
    const tax=digits(body.tax_id),organization=String(body.organization||'Comercio Lleno').trim().slice(0,80)||'Comercio Lleno';if(!validTaxId(tax))return json(req,{ok:false,error:'El CUIT/CUIL debe tener exactamente 11 dígitos.'},400);
    const previous=await creds(cid);const pair=forge.pki.rsa.generateKeyPair({bits:2048,e:0x10001});const csr=forge.pki.createCertificationRequest();csr.publicKey=pair.publicKey;const alias=`ComercioLleno_${cid.replace(/-/g,'').slice(0,10)}`;csr.setSubject([{name:'countryName',value:'AR'},{name:'organizationName',value:organization},{name:'commonName',value:alias},{name:'serialNumber',value:`CUIT ${tax}`}]);csr.sign(pair.privateKey,forge.md.sha256.create());if(!csr.verify())throw new Error('No se pudo verificar el CSR generado.');const keyPem=forge.pki.privateKeyToPem(pair.privateKey),csrPem=forge.pki.certificationRequestToPem(csr);const keyId=await storeSecret(previous?.private_key_secret_id||null,`arca:${cid}:private-key`,keyPem,`Clave privada ARCA de ${cid}`);await upsertCred(cid,{private_key_secret_id:keyId,certificate_secret_id:null,csr_pem:csrPem,certificate_subject:null,certificate_expires_at:null});await clearTicket(cid);return json(req,{ok:true,csr_pem:csrPem,alias,tax_id:tax});
  }
  if(action==='upload_certificate'){
    const tax=digits(body.tax_id),pem=String(body.certificate_pem||'').trim();if(!validTaxId(tax))return json(req,{ok:false,error:'El CUIT/CUIL debe tener 11 dígitos.'},400);if(!pem.includes('BEGIN CERTIFICATE')||pem.includes('CERTIFICATE REQUEST'))return json(req,{ok:false,error:'Ese archivo no es el certificado .crt que devuelve ARCA.'},400);const row=await creds(cid);if(!row?.private_key_secret_id)return json(req,{ok:false,error:'Primero generá el CSR desde Comercio Lleno.'},409);const keyPem=await readSecret(row.private_key_secret_id);if(!keyPem)throw new Error('No se encontró la clave privada cifrada.');const key=forge.pki.privateKeyFromPem(keyPem) as forge.pki.rsa.PrivateKey;const info=certInfo(pem);if(!keysMatch(info.cert,key))return json(req,{ok:false,error:'El certificado no corresponde a la clave privada del CSR generado.'},400);if(digits(info.serial)&&digits(info.serial)!==tax)return json(req,{ok:false,error:'El CUIT del certificado no coincide con el CUIT configurado.'},400);const certId=await storeSecret(row.certificate_secret_id||null,`arca:${cid}:certificate`,pem,`Certificado ARCA de ${cid}`);await upsertCred(cid,{certificate_secret_id:certId,certificate_subject:info.subject,certificate_expires_at:info.expires});await clearTicket(cid);return json(req,{ok:true,certificate_subject:info.subject,certificate_expires_at:info.expires});
  }
  if(action==='upload_pair'){
    const tax=digits(body.tax_id),certPem=String(body.certificate_pem||'').trim(),keyPem=String(body.private_key_pem||'').trim();if(!validTaxId(tax))return json(req,{ok:false,error:'El CUIT/CUIL debe tener 11 dígitos.'},400);if(!certPem.includes('BEGIN CERTIFICATE')||certPem.includes('CERTIFICATE REQUEST'))return json(req,{ok:false,error:'Certificado inválido.'},400);if(!keyPem.includes('PRIVATE KEY'))return json(req,{ok:false,error:'Clave privada inválida.'},400);const info=certInfo(certPem);const key=forge.pki.privateKeyFromPem(keyPem) as forge.pki.rsa.PrivateKey;if(!keysMatch(info.cert,key))return json(req,{ok:false,error:'El certificado y la clave privada no forman el mismo par.'},400);if(digits(info.serial)&&digits(info.serial)!==tax)return json(req,{ok:false,error:'El CUIT del certificado no coincide.'},400);const previous=await creds(cid);const keyId=await storeSecret(previous?.private_key_secret_id||null,`arca:${cid}:private-key`,keyPem,`Clave privada ARCA de ${cid}`);const certId=await storeSecret(previous?.certificate_secret_id||null,`arca:${cid}:certificate`,certPem,`Certificado ARCA de ${cid}`);await upsertCred(cid,{private_key_secret_id:keyId,certificate_secret_id:certId,csr_pem:null,certificate_subject:info.subject,certificate_expires_at:info.expires});await clearTicket(cid);return json(req,{ok:true,certificate_subject:info.subject,certificate_expires_at:info.expires});
  }
  if(action==='configure'){
    const tax=digits(body.tax_id),point=Number(body.point_of_sale),environment=body.environment==='homologacion'?'homologacion':'produccion',receipt=11;if(!validTaxId(tax))return json(req,{ok:false,error:'El CUIT/CUIL debe tener exactamente 11 dígitos.'},400);if(!Number.isInteger(point)||point<=0||point>99999)return json(req,{ok:false,error:'Ingresá un punto de venta válido.'},400);const row=await creds(cid);if(!row?.private_key_secret_id||!row?.certificate_secret_id)return json(req,{ok:false,error:'Falta cargar el certificado de ARCA.'},409);const r=await admin('arca_tenant_settings?on_conflict=company_id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=representation'},body:JSON.stringify({company_id:cid,enabled:true,environment,tax_id:tax,point_of_sale:point,receipt_type:receipt,credential_slot:'tenant_vault',updated_at:new Date().toISOString()})});const a=await r.json().catch(()=>[]);if(!r.ok)throw new Error(a?.message||'No se pudo guardar la configuración fiscal.');await clearTicket(cid);return json(req,{ok:true,configured:true,environment,tax_id:tax,point_of_sale:point,receipt_type:receipt});
  }
  return json(req,{ok:false,error:'Acción inválida'},400);
 }catch(e){return json(req,{ok:false,error:e instanceof Error?e.message:String(e)},500)}
});
