'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import styles from '../postula-preview/platform.module.css'

type SavedApplication={title:string;company:string;status:string;date:string}
type CandidateProfile={country?:string;province?:string;city?:string;neighborhood?:string;headline?:string;skills?:string[];preferred_areas?:string[];availability?:string;work_modes?:string[];resume_name?:string;resume_path?:string;profile_completion?:number}
type Profile={display_name?:string;avatar_url?:string;onboarding_completed?:boolean}
const demoApps:SavedApplication[]=[{title:'Customer Support Representative',company:'Emi Labs',status:'Preparada',date:'Hoy'},{title:'Junior para Auditoría Externa',company:'EY',status:'Guardada',date:'Ayer'}]

async function authHeaders(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}

export default function CandidateDashboard({jobCount=0}:{jobCount?:number}){
 const avatarRef=useRef<HTMLInputElement>(null),resumeRef=useRef<HTMLInputElement>(null)
 const [email,setEmail]=useState(''),[apps,setApps]=useState<SavedApplication[]>([]),[profile,setProfile]=useState<Profile>({}),[candidate,setCandidate]=useState<CandidateProfile>({country:'Argentina'}),[signedAvatar,setSignedAvatar]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[authed,setAuthed]=useState(false)
 const [skillsText,setSkillsText]=useState(''),[areasText,setAreasText]=useState('')
 useEffect(()=>{(async()=>{const {data}=await cvAuthClient().auth.getSession();const session=data.session;setAuthed(Boolean(session));setEmail(session?.user.email||'');try{const raw=localStorage.getItem('pm_preview_applications');setApps(raw?JSON.parse(raw):demoApps)}catch{setApps(demoApps)}if(!session)return;const r=await fetch('/api/postula/profile',{headers:{Authorization:`Bearer ${session.access_token}`}});const d=await r.json().catch(()=>({}));if(d?.ok){const p=d.profile||{},c=d.candidate||{country:'Argentina'};setProfile(p);setCandidate(c);setSkillsText((c.skills||[]).join(', '));setAreasText((c.preferred_areas||[]).join(', '));if(p.avatar_url){const {data:s}=await cvAuthClient().storage.from('postula-private').createSignedUrl(p.avatar_url,3600);if(s?.signedUrl)setSignedAvatar(s.signedUrl)}}})()},[])
 const completion=Number(candidate.profile_completion||10)
 const missing=useMemo(()=>[!profile.display_name&&'tu nombre',!candidate.city&&'tu ciudad',!(candidate.skills||[]).length&&'habilidades',!candidate.availability&&'disponibilidad',!candidate.resume_name&&'tu CV'].filter(Boolean) as string[],[profile,candidate])
 async function save(e?:FormEvent){e?.preventDefault();if(!authed)return;setBusy(true);setNotice('');try{const headers={'Content-Type':'application/json',...(await authHeaders())};const body={role:'candidate',display_name:profile.display_name||'',avatar_url:profile.avatar_url||'',country:candidate.country||'Argentina',province:candidate.province||'',city:candidate.city||'',neighborhood:candidate.neighborhood||'',headline:candidate.headline||'',availability:candidate.availability||'',skills:skillsText.split(',').map(x=>x.trim()).filter(Boolean),preferred_areas:areasText.split(',').map(x=>x.trim()).filter(Boolean),work_modes:candidate.work_modes||[],resume_name:candidate.resume_name||'',resume_path:candidate.resume_path||'',searchable:true,onboarding_completed:true,accept_legal:true,source:'candidate_profile'};const r=await fetch('/api/postula/profile',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos guardar el perfil.');setProfile(v=>({...v,onboarding_completed:true}));setCandidate(v=>({...v,skills:body.skills,preferred_areas:body.preferred_areas,profile_completion:Math.min(100,10+[body.display_name,body.province,body.city,body.headline,body.skills.length,body.availability,body.resume_name].filter(Boolean).length*12)}));setEditing(false);setNotice('Perfil actualizado.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos guardar.')}finally{setBusy(false)}}
 async function upload(kind:'avatar'|'resume',file:File){const {data}=await cvAuthClient().auth.getSession();if(!data.session)return;setBusy(true);try{const user=data.session.user;const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${user.id}/${kind}-${Date.now()}.${ext}`;const {error}=await cvAuthClient().storage.from('postula-private').upload(path,file,{upsert:false});if(error)throw error;if(kind==='avatar'){setProfile(v=>({...v,avatar_url:path}));const {data:s}=await cvAuthClient().storage.from('postula-private').createSignedUrl(path,3600);if(s?.signedUrl)setSignedAvatar(s.signedUrl)}else setCandidate(v=>({...v,resume_path:path,resume_name:file.name}));setNotice(kind==='avatar'?'Foto lista. Guardá el perfil para conservar el cambio.':'CV adjuntado. Guardá el perfil para conservarlo.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos subir el archivo.')}finally{setBusy(false)}}
 if(!authed)return <section className="pm8-account-guest"><div><span className="pm7-eyebrow coral">TU CUENTA</span><h1>Guardá tu búsqueda y hacela más tuya.</h1><p>La cuenta es gratis. Podés crearla con email y contraseña; Google se conecta en la próxima etapa.</p><Link href="/postula-acceso-preview?modo=crear&next=/mi-postula-preview" className="pm7-btn-black">Crear cuenta gratis</Link></div></section>
 return <div className={styles.dashShell}><aside className={styles.sidebar}><div className={styles.sideSection}><div className={styles.sideTitle}>Mi búsqueda</div><Link className={`${styles.sideLink} ${styles.sideActive}`} href="/mi-postula-preview">Resumen</Link><Link className={styles.sideLink} href="/empleos-preview">Buscar empleos</Link><Link className={styles.sideLink} href="/mi-postula-preview/chat">Mensajes</Link><Link className={styles.sideLink} href="/changas-preview">Trabajos Flex</Link></div><div className={styles.sideSection}><div className={styles.sideTitle}>Herramientas</div><Link className={styles.sideLink} href="/cv-ia">Mejorar mi CV</Link><Link className={styles.sideLink} href="/primer-cv">Crear CV gratis</Link><Link className={styles.sideLink} href="/test-vocacional">Test vocacional</Link><Link className={styles.sideLink} href="/plantillas-preview">Plantillas</Link><Link className={styles.sideLink} href="/busqueda-activa">Búsqueda Activa</Link></div></aside><section className={styles.dashMain}>
  <div className="pm8-profile-hero"><div className="pm8-profile-person"><button className="pm8-avatar" onClick={()=>avatarRef.current?.click()} style={signedAvatar?{backgroundImage:`url(${signedAvatar})`}:{}}>{signedAvatar?'':(profile.display_name||email||'PM').slice(0,2).toUpperCase()}</button><input ref={avatarRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload('avatar',e.target.files[0])}/><div><span className="pm7-eyebrow blue">MI PERFIL</span><h1>{profile.display_name||'Completá tu nombre'}</h1><p>{candidate.headline||email}</p></div></div><div className="pm8-profile-score"><b>{completion}%</b><span>perfil completo</span><div className="pm8-profile-completion"><i style={{width:`${completion}%`}}/></div><button onClick={()=>setEditing(v=>!v)}>{editing?'Cerrar edición':'Completar perfil'}</button></div></div>
  {!profile.onboarding_completed&&<div className="pm8-onboarding"><h3>Tu primer recorrido, sin vueltas.</h3><p>Podés hacerlo en cualquier orden. Estos cuatro pasos hacen que la plataforma pueda ayudarte mejor.</p><div className="pm8-onboarding-steps"><a href="#perfil"><b>1 · Perfil</b><small>Zona, habilidades y disponibilidad</small></a><Link href="/cv-ia"><b>2 · CV</b><small>Subí uno o crealo gratis</small></Link><Link href="/empleos-preview"><b>3 · Buscar</b><small>Guardá oportunidades reales</small></Link><Link href="/mi-postula-preview/chat"><b>4 · Mensajes</b><small>Respondé a empresas desde el celular</small></Link></div></div>}
  {editing&&<form className="pm8-profile-form" id="perfil" onSubmit={save}><div className="pm8-form-head"><div><span>DATOS PARA TU BÚSQUEDA</span><h2>Contanos lo justo para encontrar algo mejor.</h2></div><small>No hace falta repetir todo tu CV. Acá sumamos zona, preferencias y disponibilidad.</small></div><div className="pm8-form-grid"><label>Nombre y apellido<input value={profile.display_name||''} onChange={e=>setProfile(v=>({...v,display_name:e.target.value}))}/></label><label>Titular breve<input value={candidate.headline||''} onChange={e=>setCandidate(v=>({...v,headline:e.target.value}))} placeholder="Ej. Atención al cliente · ventas"/></label><label>País<input value={candidate.country||'Argentina'} onChange={e=>setCandidate(v=>({...v,country:e.target.value}))}/></label><label>Provincia<input value={candidate.province||''} onChange={e=>setCandidate(v=>({...v,province:e.target.value}))}/></label><label>Ciudad<input value={candidate.city||''} onChange={e=>setCandidate(v=>({...v,city:e.target.value}))}/></label><label>Barrio / zona<input value={candidate.neighborhood||''} onChange={e=>setCandidate(v=>({...v,neighborhood:e.target.value}))}/></label><label className="wide">Habilidades separadas por coma<input value={skillsText} onChange={e=>setSkillsText(e.target.value)} placeholder="ventas, Excel, caja, atención al cliente"/></label><label className="wide">Áreas que te interesan<input value={areasText} onChange={e=>setAreasText(e.target.value)} placeholder="ventas, administración, gastronomía"/></label><label className="wide">Disponibilidad<input value={candidate.availability||''} onChange={e=>setCandidate(v=>({...v,availability:e.target.value}))} placeholder="Ej. full time · sábados sí · turno mañana"/></label><fieldset className="wide"><legend>Modalidad</legend>{['Presencial','Híbrido','Remoto'].map(m=><label key={m}><input type="checkbox" checked={(candidate.work_modes||[]).includes(m)} onChange={e=>setCandidate(v=>({...v,work_modes:e.target.checked?[...(v.work_modes||[]),m]:(v.work_modes||[]).filter(x=>x!==m)}))}/>{m}</label>)}</fieldset></div><div className="pm8-resume-upload"><div><b>{candidate.resume_name||'Todavía no adjuntaste un CV a tu perfil.'}</b><span>PDF, DOC o DOCX · privado · podés reemplazarlo cuando quieras.</span></div><button type="button" onClick={()=>resumeRef.current?.click()}>Adjuntar CV</button><input ref={resumeRef} hidden type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>e.target.files?.[0]&&upload('resume',e.target.files[0])}/></div><div className="pm8-form-actions"><button disabled={busy}>{busy?'Guardando…':'Guardar perfil'}</button><span>Al guardar confirmás los Términos, la Política de Privacidad y el tratamiento de estos datos para gestionar tu cuenta y postulaciones.</span></div></form>}
  {notice&&<div className="pm8-notice">{notice}</div>}
  <div className={styles.metricGrid}><div className={styles.metric}><small>Perfil</small><strong>{completion}%</strong><span>{missing.length?`Falta: ${missing.slice(0,2).join(' y ')}`:'Listo para postularte'}</span></div><div className={styles.metric}><small>Oportunidades</small><strong>{jobCount||'60+'}</strong><span>catálogo actualizado</span></div><div className={styles.metric}><small>Postulaciones</small><strong>{apps.length}</strong><span>preparadas o guardadas</span></div><div className={styles.metric}><small>Mensajes</small><strong>1</strong><span><Link href="/mi-postula-preview/chat">Abrir chat móvil</Link></span></div></div>
  <div className="pm8-account-tools"><Link href="/cv-ia"><span>ATS GRATIS</span><h3>Mejorá el CV que ya tenés</h3><p>Diagnóstico gratuito y recomendaciones concretas.</p><b>Abrir →</b></Link><Link href="/primer-cv"><span>DESDE CERO</span><h3>Creá tu primer CV</h3><p>Guiado y sin inventar experiencia.</p><b>Empezar →</b></Link><Link href="/test-vocacional"><span>ORIENTACIÓN</span><h3>Test vocacional</h3><p>Conectá intereses con áreas y búsquedas reales.</p><b>Hacer test →</b></Link><Link href="/plantillas-preview"><span>DISEÑO</span><h3>Plantillas</h3><p>Tres gratis + biblioteca Pro visible.</p><b>Elegir →</b></Link></div>
  <div className={styles.dashGrid}><article className={styles.panel} id="postulaciones"><div className={styles.panelHead}><h2>Actividad reciente</h2><Link href="/empleos-preview">Encontrar otra</Link></div>{apps.map((a,i)=><div className={styles.applicationRow} key={`${a.title}-${i}`}><div><strong>{a.title}</strong><small>{a.company} · {a.date}</small></div><span className={styles.status}>{a.status}</span></div>)}</article><article className={`${styles.panel} ${styles.upgrade}`}><span className={styles.miniLabel}>PLANES DE 30 DÍAS</span><h2 style={{fontSize:24,margin:'8px 0'}}>Gratis no desaparece cuando vence un plan.</h2><p>Tu cuenta, CV e historial siguen existiendo. Pro+ suma versiones adaptadas; Búsqueda Activa agrega radar y seguimiento durante 30 días.</p><div className={styles.featureList}><span>Gratis: búsqueda, perfil, test y diagnóstico</span><span>Pro+: más preparaciones y CV adaptado por puesto</span><span>Búsqueda Activa: seguimiento y radar por 30 días</span></div><Link href="/cv-ia" className={styles.button}>Comparar planes</Link></article></div>
 </section></div>
}
