'use client'

import Link from 'next/link'
import {useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

export default function CandidateAccountControls(){
 const [busy,setBusy]=useState(''),[notice,setNotice]=useState('')
 async function action(name:string,body:Record<string,unknown>){
  setBusy(name);setNotice('')
  try{const {data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Iniciá sesión nuevamente.');const r=await fetch('/api/postula/account',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos procesar la solicitud.');return d}catch(e){setNotice(e instanceof Error?e.message:'No pudimos procesar la solicitud.');return null}finally{setBusy('')}}
 async function clearData(){if(!window.confirm('¿Querés borrar los datos editables de tu perfil de postulante, la foto y el CV? Tus postulaciones, mensajes y evaluaciones vinculadas a procesos laborales no se eliminan con esta acción.'))return;const d=await action('clear',{action:'clear_candidate_profile'});if(d){setNotice('Tus datos editables, la foto y el CV fueron eliminados.');window.setTimeout(()=>window.location.reload(),900)}}
 async function deleteAccount(){if(!window.confirm('¿Querés solicitar la eliminación de tu cuenta? Registraremos la solicitud para verificar y completar la supresión que corresponda.'))return;const d=await action('account',{action:'request_account_deletion',scope:'account'});if(d)setNotice(d.existing?'Ya existe una solicitud de eliminación en curso.':'Solicitud de eliminación registrada.')}
 return <section className="pm42-panel pm42-data-controls"><div className="pm42-section-head"><div><span>DATOS Y CUENTA</span><h2>Controlá tus datos desde acá.</h2><p>Podés quitar tus archivos y datos editables del perfil o solicitar la eliminación de la cuenta. Algunos registros vinculados a procesos, seguridad o evaluaciones pueden requerir un tratamiento separado según la normativa y nuestras políticas.</p></div></div><div className="pm42-danger-grid"><article><b>Borrar datos del perfil</b><p>Elimina foto, CV, ubicación, habilidades, disponibilidad, LinkedIn y demás datos editables del perfil de postulante. No borra postulaciones ni mensajes ya vinculados a procesos.</p><button type="button" disabled={Boolean(busy)} onClick={()=>void clearData()}>{busy==='clear'?'Eliminando…':'Borrar datos del perfil'}</button></article><article className="danger"><b>Eliminar cuenta</b><p>Inicia una solicitud de supresión de la cuenta y sus datos personales. La procesamos con verificación de identidad y las excepciones legales que correspondan.</p><button type="button" disabled={Boolean(busy)} onClick={()=>void deleteAccount()}>{busy==='account'?'Solicitando…':'Solicitar eliminación de cuenta'}</button></article></div>{notice&&<div className="pm42-data-notice">{notice}</div>}<p className="pm42-data-foot">También podés consultar la <Link href="/privacidad">Política de Privacidad</Link> y el <Link href="/legales">Centro legal y de seguridad</Link>.</p></section>
}
