'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import NativeApplications from './NativeApplications'
import FlexFavorites from './FlexFavorites'

type CandidateProfile={country?:string;province?:string;city?:string;neighborhood?:string;headline?:string;skills?:string[];preferred_areas?:string[];availability?:string;work_modes?:string[];resume_name?:string;resume_path?:string;profile_completion?:number;linkedin_url?:string;profile_visibility?:string}
type Profile={display_name?:string;avatar_url?:string;onboarding_completed?:boolean;primary_role?:string}
type Membership={company_id?:string;pm_companies?:{name?:string}|null}

async function authHeaders(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
function initials(value:string){return value.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'PM'}

export default function CandidateDashboard({jobCount=0}:{jobCount?:number}){
 const avatarRef=useRef<HTMLInputElement>(null),resumeRef=useRef<HTMLInputElement>(null)
 const [email,setEmail]=useState(''),[profile,setProfile]=useState<Profile>({}),[candidate,setCandidate]=useState<CandidateProfile>({country:'Argentina'}),[memberships,setMemberships]=useState<Membership[]>([]),[signedAvatar,setSignedAvatar]=useState(''),[editing,setEditing]=useState(false),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[authed,setAuthed]=useState<boolean|null>(null),[preview,setPreview]=useState(false)
 const [skillsText,setSkillsText]=useState(''),[areasText,setAreasText]=useState('')
 useEffect(()=>{(async()=>{const {data}=await cvAuthClient().auth.getSession();const session=data.session;setAuthed(Boolean(session));setEmail(session?.user.email||'');if(!session)return;const r=await fetch('/api/postula/profile',{headers:{Authorization:`Bearer ${session.access_token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(d?.ok){const p=d.profile||{},c=d.candidate||{country:'Argentina'};setProfile(p);setCandidate(c);setMemberships(d.memberships||[]);setSkillsText((c.skills||[]).join(', '));setAreasText((c.preferred_areas||[]).join(', '));if(!d.candidate)setEditing(true);if(p.avatar_url){const {data:s}=await cvAuthClient().storage.from('postula-private').createSignedUrl(p.avatar_url,3600);if(s?.signedUrl)setSignedAvatar(s.signedUrl)}}})().catch(()=>setAuthed(false))},[])
 const completion=Number(candidate.profile_completion||10)
 const missing=useMemo(()=>[!profile.display_name&&'nombre',!candidate.city&&'ciudad',!(candidate.skills||[]).length&&'habilidades',!candidate.availability&&'disponibilidad',!candidate.resume_name&&'CV'].filter(Boolean) as string[],[profile,candidate])
 const hasEmployer=memberships.length>0
 const location=[candidate.neighborhood,candidate.city,candidate.province].filter(Boolean).join(' · ')
 const visibility=candidate.profile_visibility==='discoverable'?'Visible para oportunidades':candidate.profile_visibility==='private'?'Privado':'Sólo al postularte'
 async function save(e?:FormEvent){e?.preventDefault();if(!authed)return;setBusy(true);setNotice('');try{const headers={'Content-Type':'application/json',...(await authHeaders())};const body={role:'candidate',activate_candidate:true,display_name:profile.display_name||'',avatar_url:profile.avatar_url||'',country:candidate.country||'Argentina',province:candidate.province||'',city:candidate.city||'',neighborhood:candidate.neighborhood||'',headline:candidate.headline||'',availability:candidate.availability||'',linkedin_url:candidate.linkedin_url||'',skills:skillsText.split(',').map(x=>x.trim()).filter(Boolean),preferred_areas:areasText.split(',').map(x=>x.trim()).filter(Boolean),work_modes:candidate.work_modes||[],resume_name:candidate.resume_name||'',resume_path:candidate.resume_path||'',onboarding_completed:true,accept_legal:true,source:'candidate_profile',terms_version:'2026-08-21'};const r=await fetch('/api/postula/profile',{method:'POST',headers,body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos guardar el perfil.');setProfile(v=>({...v,onboarding_completed:true}));setCandidate(v=>({...v,skills:body.skills,preferred_areas:body.preferred_areas,profile_completion:Math.min(100,10+[body.display_name,body.province,body.city,body.headline,body.skills.length,body.availability,body.resume_name,body.linkedin_url].filter(Boolean).length*11)}));setEditing(false);setNotice('Perfil actualizado. Ya usamos estos datos para ordenar mejor tus oportunidades.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos guardar.')}finally{setBusy(false)}}
 async function upload(kind:'avatar'|'resume',file:File){const {data}=await cvAuthClient().auth.getSession();if(!data.session)return;setBusy(true);try{const user=data.session.user;const ext=(file.name.split('.').pop()||'bin').toLowerCase();const path=`${user.id}/${kind}-${Date.now()}.${ext}`;const {error}=await cvAuthClient().storage.from('postula-private').upload(path,file,{upsert:false});if(error)throw error;if(kind==='avatar'){setProfile(v=>({...v,avatar_url:path}));const {data:s}=await cvAuthClient().storage.from('postula-private').createSignedUrl(path,3600);if(s?.signedUrl)setSignedAvatar(s.signedUrl)}else setCandidate(v=>({...v,resume_path:path,resume_name:file.name}));setNotice(kind==='avatar'?'Foto lista. Guardá los cambios para conservarla.':'CV adjuntado. Guardá los cambios para conservarlo.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos subir el archivo.')}finally{setBusy(false)}}
 if(authed===null)return <section className="pm34-loading"><b>Preparando tu perfil…</b></section>
 if(!authed)return <section className="pm34-guest"><span>MI CUENTA</span><h1>Tu búsqueda, en un solo lugar.</h1><p>Entrá para ver tu perfil, CV, postulaciones, mensajes, favoritos y recomendaciones según lo que estás buscando.</p><div><Link href="/login">Ingresar</Link><Link href="/registro">Crear cuenta gratis</Link></div></section>
 return <div className="pm34-shell">
  <aside className="pm34-sidebar">
   <div className="pm34-side-person"><button type="button" onClick={()=>avatarRef.current?.click()} className="pm34-mini-avatar" style={signedAvatar?{backgroundImage:`url(${signedAvatar})`}:{}}>{signedAvatar?'':initials(profile.display_name||email)}</button><div><b>{profile.display_name||'Tu perfil'}</b><small>{candidate.headline||email}</small></div></div>
   <nav><a href="#perfil" className="active">Perfil</a><a href="#cv">Mi CV</a><a href="#postulaciones">Postulaciones</a><Link href="/mensajes">Mensajes</Link><a href="#flex">Trabajo Flex</a><Link href="/mi-cuenta/preferencias">Preferencias</Link></nav>
   <div className="pm34-side-role"><small>{hasEmployer?'TENÉS PERFIL DE EMPRESA':'¿TAMBIÉN CONTRATÁS?'}</small><p>{hasEmployer?'Podés cambiar al panel de tu empresa sin mezclar los datos personales.':'Creá el perfil de tu empresa con sus propios datos y mantenelo separado de tu búsqueda laboral.'}</p><Link href={hasEmployer?'/empresas/panel':'/empresas/registro'}>{hasEmployer?'Ir a mi empresa':'Crear perfil de empresa'}</Link></div>
  </aside>
  <main className="pm34-main">
   <section className="pm34-profile-card" id="perfil">
    <div className="pm34-profile-cover"/>
    <div className="pm34-profile-body"><button type="button" className="pm34-avatar" onClick={()=>avatarRef.current?.click()} style={signedAvatar?{backgroundImage:`url(${signedAvatar})`}:{}}>{signedAvatar?'':initials(profile.display_name||email)}</button><input ref={avatarRef} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&upload('avatar',e.target.files[0])}/><div className="pm34-identity"><span>PERFIL DE POSTULANTE</span><h1>{profile.display_name||'Completá tu nombre'}</h1><p>{candidate.headline||'Agregá un titular profesional para contar qué buscás.'}</p><div>{location&&<span>⌖ {location}</span>}{candidate.availability&&<span>◷ {candidate.availability}</span>}<span>◉ {visibility}</span></div></div><div className="pm34-profile-actions"><button type="button" onClick={()=>setPreview(true)}>Ver como empresa</button><button type="button" className="primary" onClick={()=>setEditing(v=>!v)}>{editing?'Cerrar edición':'Editar perfil'}</button></div></div>
    <div className="pm34-profile-progress"><div><b>{completion}%</b><span>Perfil completo</span></div><i><span style={{width:`${completion}%`}}/></i><p>{missing.length?`Para mejorar las recomendaciones todavía podés sumar: ${missing.slice(0,3).join(', ')}.`:'Tu perfil ya tiene lo principal para personalizar la búsqueda.'}</p></div>
   </section>

   {editing&&<form className="pm34-edit" onSubmit={save}><div className="pm34-edit-head"><div><span>EDITAR PERFIL</span><h2>Lo que contás acá alimenta tus recomendaciones.</h2></div><p>No hace falta repetir todo el CV. Usamos estos datos para ordenar oportunidades y mostrarle a las empresas sólo lo que autorices.</p></div><div className="pm34-form-grid"><label>Nombre y apellido<input value={profile.display_name||''} onChange={e=>setProfile(v=>({...v,display_name:e.target.value}))}/></label><label>Titular profesional<input value={candidate.headline||''} onChange={e=>setCandidate(v=>({...v,headline:e.target.value}))} placeholder="Ej. Atención al cliente · ventas"/></label><label>Provincia<input value={candidate.province||''} onChange={e=>setCandidate(v=>({...v,province:e.target.value}))}/></label><label>Ciudad<input value={candidate.city||''} onChange={e=>setCandidate(v=>({...v,city:e.target.value}))}/></label><label>Barrio / zona<input value={candidate.neighborhood||''} onChange={e=>setCandidate(v=>({...v,neighborhood:e.target.value}))}/></label><label>Disponibilidad<input value={candidate.availability||''} onChange={e=>setCandidate(v=>({...v,availability:e.target.value}))} placeholder="Full time · turno mañana"/></label><label className="wide">Habilidades<input value={skillsText} onChange={e=>setSkillsText(e.target.value)} placeholder="ventas, Excel, caja, cocina, atención al cliente"/></label><label className="wide">Áreas que te interesan<input value={areasText} onChange={e=>setAreasText(e.target.value)} placeholder="ventas, administración, gastronomía"/></label><label className="wide">LinkedIn<input value={candidate.linkedin_url||''} onChange={e=>setCandidate(v=>({...v,linkedin_url:e.target.value}))} placeholder="https://www.linkedin.com/in/tu-perfil"/></label><fieldset className="wide"><legend>Modalidad</legend>{['Presencial','Híbrido','Remoto'].map(m=><label key={m}><input type="checkbox" checked={(candidate.work_modes||[]).includes(m)} onChange={e=>setCandidate(v=>({...v,work_modes:e.target.checked?[...(v.work_modes||[]),m]:(v.work_modes||[]).filter(x=>x!==m)}))}/>{m}</label>)}</fieldset></div><div className="pm34-edit-actions"><button disabled={busy}>{busy?'Guardando…':'Guardar cambios'}</button><span>Los datos del perfil de postulante se administran separados de cualquier perfil de empresa que tengas.</span></div></form>}
   {notice&&<div className="pm34-notice">{notice}</div>}

   <section className="pm34-grid">
    <article className="pm34-card pm34-about"><div className="pm34-card-head"><div><span>PERFIL PROFESIONAL</span><h2>Lo que una empresa entiende de vos.</h2></div><button onClick={()=>setEditing(true)}>Editar</button></div><p className="pm34-about-copy">{candidate.headline?`Tu perfil está orientado a ${candidate.headline}.`: 'Sumá un titular profesional, habilidades y áreas de interés para que el perfil cuente mejor qué podés aportar.'}</p><div className="pm34-chipset">{(candidate.skills||[]).length?(candidate.skills||[]).slice(0,10).map(s=><span key={s}>{s}</span>):<em>Sin habilidades cargadas todavía</em>}</div>{(candidate.preferred_areas||[]).length>0&&<div className="pm34-interest"><small>ÁREAS DE INTERÉS</small><p>{(candidate.preferred_areas||[]).join(' · ')}</p></div>}</article>
    <article className="pm34-card pm34-cv" id="cv"><div className="pm34-card-head"><div><span>MI CV</span><h2>{candidate.resume_name?'Tu currículum está cargado.':'Todavía no cargaste un CV.'}</h2></div></div><div className="pm34-cv-file"><i>CV</i><div><b>{candidate.resume_name||'Sin archivo'}</b><small>{candidate.resume_name?'Privado · sólo se comparte en los flujos autorizados':'PDF, DOC o DOCX'}</small></div></div><div className="pm34-card-actions"><button type="button" onClick={()=>resumeRef.current?.click()}>{candidate.resume_name?'Reemplazar CV':'Subir CV'}</button><Link href="/mejorar-cv">Mejorar con IA</Link><input ref={resumeRef} hidden type="file" accept=".pdf,.doc,.docx,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document" onChange={e=>e.target.files?.[0]&&upload('resume',e.target.files[0])}/></div></article>
    <article className="pm34-card pm34-search"><div className="pm34-card-head"><div><span>BÚSQUEDA INTELIGENTE</span><h2>Empleos ordenados según tu perfil.</h2></div></div><p>Comparamos área, habilidades, zona, modalidad y disponibilidad. No descartamos personas: solamente priorizamos qué oportunidades mostrarte primero.</p><Link href="/empleos?orden=perfil">Ver recomendaciones →</Link></article>
    <article className="pm34-card pm34-linkedin"><div className="pm34-card-head"><div><span>LINKEDIN</span><h2>{candidate.linkedin_url?'Perfil vinculado por URL.':'Sumá tu perfil profesional externo.'}</h2></div></div><p>{candidate.linkedin_url?'Podés abrirlo o cambiar el enlace cuando quieras.':'Agregar LinkedIn es opcional. Sirve para completar contexto profesional sin mezclarlo con tu CV.'}</p>{candidate.linkedin_url?<a href={candidate.linkedin_url} target="_blank" rel="noopener noreferrer">Abrir LinkedIn ↗</a>:<button type="button" onClick={()=>setEditing(true)}>Agregar LinkedIn</button>}</article>
   </section>

   <section className="pm34-quick"><Link href="/mensajes"><span>MENSAJES</span><b>Conversaciones</b><small>Empresas y Trabajo Flex</small></Link><Link href="/trabajos-flex"><span>TRABAJO FLEX</span><b>Oportunidades puntuales</b><small>Explorá y guardá tareas</small></Link><Link href="/mi-cuenta/preferencias"><span>PREFERENCIAS</span><b>Privacidad y notificaciones</b><small>Todo lo de configuración, separado</small></Link><Link href="/empleos"><span>EMPLEOS</span><b>{jobCount} oportunidades</b><small>Filtrá por área y zona</small></Link></section>

   <section id="postulaciones"><NativeApplications/></section>
   <section id="flex"><FlexFavorites/></section>
  </main>
  {preview&&<div className="pm34-preview-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setPreview(false)}}><section className="pm34-preview" role="dialog" aria-modal="true" aria-label="Vista del perfil para empresas"><header><div><span>VISTA DE EMPRESA</span><b>Así se presenta tu perfil</b></div><button onClick={()=>setPreview(false)}>×</button></header><div className="pm34-preview-person"><div className="pm34-preview-avatar" style={signedAvatar?{backgroundImage:`url(${signedAvatar})`}:{}}>{signedAvatar?'':initials(profile.display_name||email)}</div><div><h2>{profile.display_name||'Nombre del postulante'}</h2><p>{candidate.headline||'Titular profesional'}</p><span>{candidate.city||candidate.province||'Ubicación no publicada'}</span></div></div><div className="pm34-preview-section"><small>HABILIDADES</small><div>{(candidate.skills||[]).length?(candidate.skills||[]).map(s=><span key={s}>{s}</span>):<em>Sin habilidades públicas todavía.</em>}</div></div><div className="pm34-preview-section"><small>DISPONIBILIDAD</small><p>{candidate.availability||'A completar'}</p></div><footer>La empresa sólo ve los datos permitidos por tu configuración de privacidad y por una postulación concreta.</footer></section></div>}
 </div>
}
