'use client'
import {useEffect,useRef,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

function extFor(file:File){if(file.type==='image/png')return'png';if(file.type==='image/webp')return'webp';return'jpg'}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'PM'}
async function functionError(error:any){try{const response=error?.context;if(response&&typeof response.json==='function'){const body=await response.json();return String(body?.error||'')}}catch{}return String(error?.message||'')}

export default function CandidatePhoto(){
 const input=useRef<HTMLInputElement>(null);const[visible,setVisible]=useState(false),[path,setPath]=useState(''),[url,setUrl]=useState(''),[name,setName]=useState('Tu perfil'),[busy,setBusy]=useState(false),[notice,setNotice]=useState('')
 async function displayUrl(value:string){if(!value)return'';if(/^https?:\/\//i.test(value))return value;const{data}=await cvAuthClient().storage.from('postula-private').createSignedUrl(value,60*60);return data?.signedUrl||''}
 useEffect(()=>{void(async()=>{const client=cvAuthClient();const{data}=await client.auth.getSession();if(!data.session)return;const r=await fetch('/api/postula/profile',{headers:{Authorization:`Bearer ${data.session.access_token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));const c=d?.candidate||{};const activated=Boolean(c&&(c.city||c.headline||c.resume_name||(c.skills||[]).length))||d?.profile?.primary_role==='candidate'||Boolean((d?.consents||[]).some((x:any)=>x.consent_type==='candidate_profile_activation'&&x.accepted));if(!activated)return;setVisible(true);setName(String(d?.profile?.display_name||data.session.user.user_metadata?.full_name||data.session.user.user_metadata?.name||'Tu perfil'));const current=String(d?.profile?.avatar_url||'');setPath(current);setUrl(await displayUrl(current))})()},[])
 async function saveAvatar(next:string){const{data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token)throw new Error('Tu sesión venció.');const r=await fetch('/api/postula/profile',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({candidate_settings:true,avatar_url:next})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos guardar la foto.')}
 async function upload(file:File){if(busy)return;setNotice('');if(file.size>2*1024*1024){setNotice('La foto puede pesar hasta 2 MB.');return}if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setNotice('Usá JPG, PNG o WEBP.');return}setBusy(true);const client=cvAuthClient();let temp='';try{const{data}=await client.auth.getSession();const user=data.session?.user;if(!user)throw new Error('Tu sesión venció.');temp=`${user.id}/profile-review/${crypto.randomUUID()}.${extFor(file)}`;const{error:uploadError}=await client.storage.from('postula-private').upload(temp,file,{upsert:false,contentType:file.type});if(uploadError)throw uploadError;setNotice('Revisando la foto…');const{data:review,error}=await client.functions.invoke('postula-flex-image-review',{body:{path:temp,mode:'avatar'}});if(error)throw new Error((await functionError(error))||'No pudimos revisar la foto.');if(!review?.ok||!review?.path)throw new Error(String(review?.error||'No pudimos revisar la foto.'));const next=String(review.path);await saveAvatar(next);if(path&&!/^https?:\/\//i.test(path)&&path!==next)await client.storage.from('postula-private').remove([path]).catch(()=>{});setPath(next);setUrl(await displayUrl(next));setNotice('Foto actualizada. La privacidad de tu cuenta define dónde puede mostrarse.')}catch(e){if(temp)await client.storage.from('postula-private').remove([temp]).catch(()=>{});setNotice(e instanceof Error?e.message:'No pudimos subir la foto.')}finally{setBusy(false);if(input.current)input.current.value=''}}
 async function remove(){if(!path||busy)return;setBusy(true);setNotice('');try{await saveAvatar('');if(!/^https?:\/\//i.test(path))await cvAuthClient().storage.from('postula-private').remove([path]).catch(()=>{});setPath('');setUrl('');setNotice('Foto eliminada. Tu cuenta sigue funcionando normalmente.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos eliminar la foto.')}finally{setBusy(false)}}
 if(!visible)return null
 return <section className="pm33-photo-wrap"><article className="pm33-photo-card"><div className="pm33-photo-preview">{url?<img src={url} alt="Foto de perfil"/>:<span>{initials(name)}</span>}</div><div className="pm33-photo-copy"><span>FOTO DE PERFIL · OPCIONAL</span><h2>Una cara cuando vos quieras.</h2><p>Podés usar una foto para humanizar tu perfil. Antes de guardarse pasa por una revisión automática. Si no querés mostrarla públicamente, desactivá “Foto de perfil” en Privacidad.</p>{notice&&<small>{notice}</small>}</div><div className="pm33-photo-actions"><button type="button" onClick={()=>input.current?.click()} disabled={busy}>{busy?'Procesando…':path?'Cambiar foto':'Subir foto'}</button>{path&&<button type="button" className="quiet" onClick={()=>void remove()} disabled={busy}>Quitar</button>}<input ref={input} hidden type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>e.target.files?.[0]&&void upload(e.target.files[0])}/></div></article></section>
}
