'use client'
import {useEffect,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import {flexCategoryImage} from '../changas-preview/flexVisuals'

type Item={id:string;title:string;category:string;location_text:string;compensation_text:string;duration_text?:string|null;availability_text?:string|null;listing_type?:'request'|'offer';image_url?:string;publisher_display_name?:string|null;publisher_kind?:string|null}
function jobLabel(slug:string){try{return decodeURIComponent(slug).replace(/[-_]+/g,' ').replace(/\s+/g,' ').trim().replace(/^./,x=>x.toUpperCase())}catch{return slug}}
function flexType(item:Item){return item.listing_type==='offer'?'OFRECE SERVICIO':'BUSCA PROFESIONAL'}
export default function FlexFavorites(){
 const[ready,setReady]=useState(false),[authenticated,setAuthenticated]=useState(false),[items,setItems]=useState<Item[]>([]),[jobs,setJobs]=useState<string[]>([]),[notice,setNotice]=useState('')
 function loadJobs(){try{const parsed=JSON.parse(localStorage.getItem('pm_saved_jobs')||'[]');setJobs(Array.isArray(parsed)?parsed.filter(x=>typeof x==='string'):[])}catch{setJobs([])}}
 async function load(){loadJobs();const{data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token){setReady(true);return}setAuthenticated(true);const r=await fetch('/api/postula/flex?favorites=1',{headers:{Authorization:`Bearer ${token}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok&&d?.ok)setItems(d.posts||[]);setReady(true)}
 useEffect(()=>{void load();const sync=()=>loadJobs();window.addEventListener('storage',sync);return()=>window.removeEventListener('storage',sync)},[])
 async function remove(id:string){const{data}=await cvAuthClient().auth.getSession();const token=data.session?.access_token;if(!token)return;setItems(v=>v.filter(x=>x.id!==id));const r=await fetch('/api/postula/flex',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'favorite',post_id:id,saved:false})});if(!r.ok){setNotice('No pudimos quitarlo. Recargá la página para volver a intentarlo.');void load()}else setNotice('Servicio Flex quitado de favoritos.')}
 function removeJob(slug:string){const next=jobs.filter(x=>x!==slug);setJobs(next);try{localStorage.setItem('pm_saved_jobs',JSON.stringify(next));window.dispatchEvent(new Event('storage'))}catch{}setNotice('Empleo quitado de favoritos.')}
 if(!ready||!authenticated)return null
 const empty=!items.length&&!jobs.length
 return <section className="pm33-favorites-wrap"><article className="pm33-favorites-card"><div className="pm33-favorites-head"><div><span>FAVORITOS</span><h2>Lo que guardaste para mirar después.</h2><p>Empleos y Servicios Flex viven acá como una lista aparte de tus propias publicaciones.</p></div><div className="pm38-favorite-links"><a href="/empleos">Explorar empleos</a><a href="/servicios-flex#explorar">Explorar Servicios Flex</a></div></div>{empty?<div className="pm33-favorites-empty"><b>Todavía no guardaste favoritos.</b><p>Podés guardar tanto un empleo como un Servicio Flex. Después los vas a encontrar juntos en esta sección.</p></div>:<>{jobs.length>0&&<section className="pm38-favorite-section"><div className="pm38-favorite-section-head"><span>EMPLEOS</span><b>{jobs.length} {jobs.length===1?'guardado':'guardados'}</b></div><div className="pm38-job-favorites">{jobs.map(slug=><article key={slug}><div><span>EMPLEO</span><h3>{jobLabel(slug)}</h3><p>Guardado desde el buscador de empleos.</p></div><div><a href={`/empleos/${encodeURIComponent(slug)}`}>Ver empleo</a><button type="button" onClick={()=>removeJob(slug)}>Quitar</button></div></article>)}</div></section>}{items.length>0&&<section className="pm38-favorite-section"><div className="pm38-favorite-section-head"><span>SERVICIOS FLEX</span><b>{items.length} {items.length===1?'guardado':'guardados'}</b></div><div className="pm33-favorites-grid">{items.map(item=><article key={item.id}><div className="pm33-favorite-photo" style={{backgroundImage:`url(${item.image_url||flexCategoryImage(item.category)})`}}><span>{item.category}</span></div><div><span className="pm39-manager-type" data-type={item.listing_type==='offer'?'offer':'request'}>{flexType(item)}</span><small>{item.publisher_display_name||(item.publisher_kind==='company'?'Empresa':'Persona')}</small><h3>{item.title}</h3><p>{item.location_text} · {item.listing_type==='offer'?(item.availability_text||item.duration_text||'A coordinar'):(item.duration_text||'A coordinar')}</p><b>{item.compensation_text||'A acordar'}</b><div className="pm33-favorite-actions"><a href={`/servicios-flex?tarea=${encodeURIComponent(item.id)}#explorar`}>{item.listing_type==='offer'?'Ver servicio':'Ver solicitud'}</a><button type="button" onClick={()=>void remove(item.id)}>Quitar</button></div></div></article>)}</div></section>}</>}{notice&&<small className="pm33-favorites-notice">{notice}</small>}</article></section>
}