'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type Company={name?:string}|null
type Job={title?:string;area?:string;location_text?:string;work_mode?:string;schedule?:string;compensation_text?:string;description?:string;requirements?:string[];company_id?:string;employer_visibility?:string;identity_revealed?:boolean;pm_companies?:Company|Company[]}
type App={id:string;job_id:string;status:string;submitted_at?:string;created_at:string;updated_at?:string;cover_letter?:string|null;pm_jobs?:Job|Job[]}
const labels:Record<string,string>={submitted:'Postulación enviada',viewed:'CV visto',shortlist:'Preselección',interview:'Entrevista',rejected:'Proceso cerrado',hired:'Selección final',withdrawn:'Postulación retirada'}
const stage:Record<string,number>={submitted:0,viewed:25,shortlist:50,interview:75,hired:100}
const stages=[['Enviada',0],['CV visto',25],['Preselección',50],['Entrevista',75],['Final',100]] as const
function first<T>(v:T|T[]|null|undefined):T|null{return Array.isArray(v)?v[0]||null:v||null}
function fmt(v?:string){return v?new Date(v).toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit',year:'2-digit',timeZone:'America/Argentina/Buenos_Aires'}):''}
async function authHeader(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}

export default function NativeApplications(){
 const [apps,setApps]=useState<App[]>([]),[loaded,setLoaded]=useState(false),[selected,setSelected]=useState<App|null>(null),[unread,setUnread]=useState(0)
 async function markRead(applicationId?:string){const h=await authHeader();if(!('Authorization' in h))return;await fetch('/api/postula/notifications',{method:'PATCH',headers:{'Content-Type':'application/json',...h},body:JSON.stringify(applicationId?{application_id:applicationId}:{scope:'applications'})}).catch(()=>{});if(applicationId)setUnread(v=>Math.max(0,v-1));else setUnread(0)}
 useEffect(()=>{let cancelled=false;(async()=>{const h=await authHeader();if(!('Authorization' in h)){setLoaded(true);return}const [ar,nr]=await Promise.all([fetch('/api/postula/applications?mine=1',{headers:h,cache:'no-store'}),fetch('/api/postula/notifications',{headers:h,cache:'no-store'})]);const [ad,nd]=await Promise.all([ar.json().catch(()=>({})),nr.json().catch(()=>({}))]);if(cancelled)return;if(ad?.ok)setApps(ad.applications||[]);if(nd?.ok)setUnread(Number(nd.counts?.applications||0));setLoaded(true)})().catch(()=>setLoaded(true));return()=>{cancelled=true}},[])
 useEffect(()=>{const link=document.querySelector<HTMLAnchorElement>('.pm34-sidebar nav a[href="#postulaciones"]');if(!link)return;link.dataset.pmBadge=String(unread);const handler=()=>void markRead();link.addEventListener('click',handler);return()=>link.removeEventListener('click',handler)},[unread])
 const job=useMemo(()=>first(selected?.pm_jobs),[selected]),company=useMemo(()=>first(job?.pm_companies),[job])
 if(!loaded||!apps.length)return null
 return <>
  <section className="pm8-native-apps" aria-label="Seguimiento de postulaciones">
   <div className="pm8-native-head"><div><span>SEGUIMIENTO DE POSTULACIONES</span><h2>Sabé rápido en qué etapa estás.</h2><p>Cada avance se actualiza acá y genera una notificación en tu cuenta.</p></div><Link href="/mensajes">Mensajes</Link></div>
   <div className="pm8-native-grid">{apps.map(a=>{const j=first(a.pm_jobs),progress=stage[a.status]??0,closed=['rejected','withdrawn'].includes(a.status);return <button type="button" className="pm8-app-card" key={a.id} data-closed={closed} onClick={()=>{setSelected(a);void markRead(a.id)}}><div className="pm8-app-top"><div><small>{first(j?.pm_companies)?.name||'Empresa'}</small><b>{j?.title||'Búsqueda laboral'}</b><em>Postulación del {fmt(a.submitted_at||a.created_at)}</em></div><span data-status={a.status}>{labels[a.status]||a.status}</span></div>{closed?<div className="pm8-closed"><strong>{a.status==='withdrawn'?'Retirada':'Proceso cerrado'}</strong><span>{a.status==='withdrawn'?'Decidiste retirar esta postulación.':'La empresa indicó que esta búsqueda no continúa con tu postulación.'}</span></div>:<><div className="pm8-progress-row"><b>{progress}%</b><span>{progress===0?'Recibida por la empresa':progress===25?'Ya revisaron tu CV':progress===50?'Estás entre los perfiles que siguen':progress===75?'El proceso llegó a entrevista':'Proceso marcado como finalizado'}</span></div><div className="pm8-stage-line">{stages.map(([name,p])=><div key={name} data-on={progress>=p}><i/><small>{name}</small></div>)}</div></>}<div className="pm8-open-hint">Ver detalle de la postulación →</div></button>})}</div>
  </section>
  {selected&&job&&<div className="pm8-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.currentTarget===e.target)setSelected(null)}}><section className="pm8-modal" role="dialog" aria-modal="true" aria-label="Detalle de la postulación"><header><div><span>POSTULACIÓN</span><h2>{job.title||'Búsqueda laboral'}</h2><p>{company?.name||'Empresa'}{job.location_text?` · ${job.location_text}`:''}</p></div><button type="button" onClick={()=>setSelected(null)} aria-label="Cerrar">×</button></header><div className="pm8-modal-stage"><div><small>ETAPA ACTUAL</small><b>{labels[selected.status]||selected.status}</b></div>{!['rejected','withdrawn'].includes(selected.status)&&<strong>{stage[selected.status]??0}%</strong>}</div><div className="pm8-modal-facts">{job.work_mode&&<span><small>Modalidad</small><b>{job.work_mode}</b></span>}{job.schedule&&<span><small>Horario</small><b>{job.schedule}</b></span>}{job.compensation_text&&<span><small>Compensación</small><b>{job.compensation_text}</b></span>}<span><small>Postulación</small><b>{fmt(selected.submitted_at||selected.created_at)}</b></span></div>{job.description&&<div className="pm8-modal-copy"><small>LA OPORTUNIDAD</small><p>{job.description}</p></div>}{job.requirements?.length?<div className="pm8-modal-copy"><small>REQUISITOS</small><ul>{job.requirements.slice(0,8).map(x=><li key={x}>{x}</li>)}</ul></div>:null}{selected.cover_letter&&<div className="pm8-modal-copy"><small>TU PRESENTACIÓN</small><p>{selected.cover_letter}</p></div>}<footer><Link href={`/empleos/${selected.job_id}`}>Ver oferta completa</Link><Link href="/mensajes" className="primary">Ir a mensajes</Link></footer></section></div>}
 </>
}
