import styles from '../postula-preview/platform.module.css'
import {PlatformHeader,PlatformFooter,MobileNav} from '../postula-preview/PlatformChrome'
import CandidateDashboard from './CandidateDashboard'
import CandidateAvatarPersistence from './CandidateAvatarPersistence'
import CandidateAvatarConsistency from './CandidateAvatarConsistency'
import CandidateMobileTabBridge from './CandidateMobileTabBridge'
import CandidateChatMobileBehavior from './CandidateChatMobileBehavior'
import '../postula-preview/premium-v5.css'
import '../postula-preview/premium-v6.css'
import '../postula-preview/premium-v7.css'
import '../postula-preview/premium-v7-account.css'
import '../postula-preview/inner-v5.css'
import '../postula-preview/notifications-v16.css'
import '../changas-preview/flex-credits-v21.css'
import '../changas-preview/flex-manage-v37.css'
import '../changas-preview/flex-market-v39.css'
import './account-v8.css'
import './native-apps.css'
import './account-media-v33.css'
import './account-social-v34.css'
import './account-flex-v38.css'
import './privacy-v31.css'
import './chat/chat.css'
import './candidate-workspace-v42.css'
import './candidate-chat-embed-v42.css'
import './candidate-mobile-nav-v47.css'
import './candidate-chat-mobile-v48.css'
export const metadata={title:{absolute:'Mi cuenta | Postulá Mejor'},robots:{index:false,follow:false},alternates:{canonical:'https://postulamejor.com/mi-cuenta'}}
export default function CandidatePage(){return <main className={`${styles.page} pm7-page`}><PlatformHeader/><CandidateDashboard/><CandidateMobileTabBridge/><CandidateChatMobileBehavior/><CandidateAvatarPersistence/><CandidateAvatarConsistency/><PlatformFooter/><MobileNav active="cuenta"/></main>}
