'use client'

import { useEffect, useMemo, useState } from 'react'
import styles from './first-cv.module.css'
import { trackCvEvent } from '../cv-ia/cvAuth'

type Exp={title:string;place:string;period:string;tasks:string}
type Edu={study:string;institution:string;status:string}
type Data={name:string;email:string;phone:string;city:string;linkedin:string;target:string;summary:string;noFormal:boolean;experience:Exp[];education:Edu[];skills:string;tools:string;languages:string;projects:string;availability:string;license:string}
const emptyExp=():Exp=>({title:'',place:'',period:'',tasks:''})
const emptyEdu=():Edu=>({study:'',institution:'',status:''})
const initial:Data={name:'',email:'',phone:'',city:'',linkedin:'',target:'',summary:'',noFormal:false,experience:[emptyExp()],education:[emptyEdu()],skills:'',tools:'',languages:'',projects:'',availability:'',license:''}
const steps=[['Datos básicos','Lo necesario para que puedan contactarte.'],['Objetivo','Qué te interesa y cómo querés presentarte.'],['Experiencia real','Formal, informal, proyectos o responsabilidades.'],['Formación','Estudios, cursos y aprendizaje.'],['Habilidades','Lo que sabés hacer y herramientas.'],['Revisión','Tu primer CV listo para usar.']]

function lines(v:string){return v.split(/\n|,|·/).map(x=>x.trim()).filter(Boolean)}
function cvText(d:Data){
 const exp=d.experience.filter(x=>x.title||x.place||x.tasks).map(x=>`${x.title||'Experiencia / actividad'}${x.place?` — ${x.place}`:''}${x.period?` | ${x.period}`:''}\n${lines(x.tasks).map(t=>`- ${t}`).join('\n')}`).join('\n\n')
 const edu=d.education.filter(x=>x.study||x.institution).map(x=>`${x.study}${x.institution?` — ${x.institution}`:''}${x.status?` | ${x.status}`:''}`).join('\n')
 return `${d.name}\n${d.target||'Perfil inicial'}\n${[d.email,d.phone,d.city,d.linkedin].filter(Boolean).join(' · ')}\n\nPERFIL\n${d.summary||`Busco una primera oportunidad para desarrollarme en ${d.target||'un área donde pueda aprender y aportar'}.`}${d.noFormal?' Todavía no cuento con experiencia laboral formal; el CV incluye actividades, proyectos y habilidades reales que pueden demostrar mi forma de trabajar.':''}\n\nEXPERIENCIA, PROYECTOS Y ACTIVIDADES\n${exp||d.projects||'Sin experiencia formal declarada.'}${d.projects?`\n\nProyectos / actividades relevantes\n${d.projects}`:''}\n\nFORMACIÓN\n${edu||'No especificada'}\n\nHABILIDADES\n${lines(d.skills).join(' · ')}\n\nHERRAMIENTAS\n${lines(d.tools).join(' · ')}\n\nIDIOMAS\n${lines(d.languages).join(' · ')}${d.availability?`\n\nDISPONIBILIDAD\n${d.availability}`:''}${d.license?`\n\nOTROS DATOS\n${d.license}`:''}`
}

export default function FirstCvClient(){
 const [step,setStep]=useState(0),[data,setData]=useState<Data>(initial),[saved,setSaved]=useState(false)
 useEffect(()=>{
  void trackCvEvent('first_cv_started',{source:'direct'},'/primer-cv')
  try{
    const raw=localStorage.getItem('postula_first_cv_draft_v1');if(raw)setData({...initial,...JSON.parse(raw)})
    const target=localStorage.getItem('postula_first_cv_target_v1')||'';if(target)setData(d=>({...d,target:d.target||target}))
  }catch{}
 },[])
 useEffect(()=>{try{localStorage.setItem('postula_first_cv_draft_v1',JSON.stringify(data));setSaved(true);const t=window.setTimeout(()=>setSaved(false),500);return()=>window.clearTimeout(t)}catch{}},[data])
 const vocational=useMemo(()=>{try{return JSON.parse(localStorage.getItem('postula_vocational_result_v1')||'null')}catch{return null}},[])
 const progress=Math.round(((step+1)/steps.length)*100)
 function patch<K extends keyof Data>(key:K,value:Data[K]){setData(d=>({...d,[key]:value}))}
 function expPatch(i:number,key:keyof Exp,value:string){setData(d=>({...d,experience:d.experience.map((x,n)=>n===i?{...x,[key]:value}:x)}))}
 function eduPatch(i:number,key:keyof Edu,value:string){setData(d=>({...d,education:d.education.map((x,n)=>n===i?{...x,[key]:value}:x)}))}
 const canNext=step===0?data.name.trim().length>2&&/\S+@\S+\.\S+/.test(data.email):step===1?data.target.trim().length>2:true
 function next(){if(step<steps.length-1&&canNext){setStep(step+1);window.scrollTo({top:0,behavior:'smooth'})}}
 function analyze(){const text=cvText(data);localStorage.setItem('postula_first_cv_text_v1',text);localStorage.setItem('postula_first_cv_target_v1',data.target);void trackCvEvent('first_cv_completed',{source:'builder'},'/primer-cv');void trackCvEvent('first_cv_sent_to_analysis',{source:'builder'},'/primer-cv');location.href='/?primer_cv=1#analisis'}
 function download(){const blob=new Blob([cvText(data)],{type:'text/plain;charset=utf-8'});const u=URL.createObjectURL(blob);const a=document.createElement('a');a.href=u;a.download=`CV-${(data.name||'mi-primer-cv').replace(/[^a-z0-9]+/gi,'-')}.txt`;a.click();URL.revokeObjectURL(u)}
 return <main className={styles.page}>
  <header className={styles.top}><a href="/" className={styles.brand}><span>postula</span><strong>mejor</strong><span>.com</span></a><div className={styles.save}>{saved?'Guardado ✓':'Borrador local'}</div></header>
  <div className={styles.shell}>
   <aside className={styles.sidebar}><span>PRIMER CV · GRATIS</span><h1>Vamos paso a paso.</h1><p>No necesitás “rellenar” experiencia que no tenés. La idea es encontrar lo verdadero y relevante de tu historia.</p><div className={styles.stepList}>{steps.map((x,i)=><button key={x[0]} data-on={i===step} data-done={i<step} onClick={()=>{if(i<=step)setStep(i)}}><b>{i<step?'✓':i+1}</b><span><strong>{x[0]}</strong><small>{x[1]}</small></span></button>)}</div></aside>
   <section className={styles.main}>
    <div className={styles.progress}><div style={{width:`${progress}%`}}/><span>{progress}%</span></div>
    {step===0&&<div className={styles.card}><span className={styles.kicker}>PASO 1</span><h2>Primero, lo básico.</h2><p>Usá datos que realmente quieras mostrar en un CV. No hace falta poner DNI, dirección exacta, estado civil ni información sensible.</p><div className={styles.grid2}><label>Nombre y apellido<input value={data.name} onChange={e=>patch('name',e.target.value)} placeholder="Ej: Martina López"/></label><label>Email<input type="email" value={data.email} onChange={e=>patch('email',e.target.value)} placeholder="martina@email.com"/></label><label>Teléfono<input value={data.phone} onChange={e=>patch('phone',e.target.value)} placeholder="11 5555 5555"/></label><label>Ciudad / provincia<input value={data.city} onChange={e=>patch('city',e.target.value)} placeholder="Córdoba Capital"/></label></div><label>LinkedIn <small>(opcional)</small><input value={data.linkedin} onChange={e=>patch('linkedin',e.target.value)} placeholder="linkedin.com/in/..."/></label></div>}
    {step===1&&<div className={styles.card}><span className={styles.kicker}>PASO 2</span><h2>¿Hacia dónde querés empezar?</h2><p>No tiene que ser “la profesión de tu vida”. Sólo necesitamos una dirección para que el CV tenga sentido.</p>{vocational?.length>0&&<div className={styles.vocational}><b>Tu test dejó algunas pistas</b><div>{vocational.slice(0,3).flatMap((x:any)=>x.roles||[]).slice(0,6).map((r:string)=><button key={r} onClick={()=>patch('target',r)}>{r}</button>)}</div></div>}<label>Puesto o área que querés explorar<input value={data.target} onChange={e=>patch('target',e.target.value)} placeholder="Ej: Atención al cliente, Administración, Ventas..."/></label><label>Contanos en pocas palabras qué buscás <small>(opcional)</small><textarea value={data.summary} onChange={e=>patch('summary',e.target.value)} placeholder="Ej: Busco mi primera oportunidad en atención al cliente. Me gusta trabajar con personas, aprendo rápido y tengo disponibilidad por la tarde."/></label><div className={styles.tip}><b>No escribas “soy responsable y proactivo” porque sí.</b><span>Más adelante nuestro analizador puede mejorar el texto, pero siempre respetando lo que realmente nos cuentes.</span></div></div>}
    {step===2&&<div className={styles.card}><span className={styles.kicker}>PASO 3</span><h2>Experiencia no significa solamente “empleo en blanco”.</h2><p>También sirven trabajos informales, ayudar en un negocio familiar, cuidar personas, vender por tu cuenta, voluntariado, proyectos escolares, organizar actividades o trabajos independientes.</p><label className={styles.check}><input type="checkbox" checked={data.noFormal} onChange={e=>patch('noFormal',e.target.checked)}/><span><b>Todavía no tuve un trabajo formal</b><small>No pasa nada. Igual podemos construir un CV honesto.</small></span></label>{data.experience.map((x,i)=><div className={styles.repeat} key={i}><div className={styles.repeatHead}><b>Experiencia / actividad {i+1}</b>{data.experience.length>1&&<button onClick={()=>patch('experience',data.experience.filter((_,n)=>n!==i))}>Quitar</button>}</div><div className={styles.grid2}><label>Rol o actividad<input value={x.title} onChange={e=>expPatch(i,'title',e.target.value)} placeholder="Ej: Ayuda en comercio familiar"/></label><label>Lugar / proyecto<input value={x.place} onChange={e=>expPatch(i,'place',e.target.value)} placeholder="Ej: Kiosco familiar"/></label></div><label>Período <small>(opcional)</small><input value={x.period} onChange={e=>expPatch(i,'period',e.target.value)} placeholder="Ej: 2025 – actualidad"/></label><label>¿Qué hacías realmente?<textarea value={x.tasks} onChange={e=>expPatch(i,'tasks',e.target.value)} placeholder={'Una tarea por línea.\nEj: Atención a clientes\nCobro y manejo de caja\nReposición de mercadería'}/></label></div>)}<button className={styles.add} onClick={()=>patch('experience',[...data.experience,emptyExp()])}>+ Agregar otra experiencia o actividad</button><label>Proyectos, actividades o responsabilidades que también quieras destacar <small>(opcional)</small><textarea value={data.projects} onChange={e=>patch('projects',e.target.value)} placeholder="Ej: Organicé la feria del colegio, vendo productos por Instagram, administro el equipo de fútbol del barrio..."/></label></div>}
    {step===3&&<div className={styles.card}><span className={styles.kicker}>PASO 4</span><h2>Formación y aprendizaje.</h2><p>Podés poner secundario, terciario, universidad, cursos o capacitaciones. Si algo está en curso, decilo tal cual.</p>{data.education.map((x,i)=><div className={styles.repeat} key={i}><div className={styles.repeatHead}><b>Formación {i+1}</b>{data.education.length>1&&<button onClick={()=>patch('education',data.education.filter((_,n)=>n!==i))}>Quitar</button>}</div><label>Estudio / curso<input value={x.study} onChange={e=>eduPatch(i,'study',e.target.value)} placeholder="Ej: Secundario con orientación en Economía"/></label><div className={styles.grid2}><label>Institución<input value={x.institution} onChange={e=>eduPatch(i,'institution',e.target.value)} placeholder="Nombre de la institución"/></label><label>Estado / fecha<input value={x.status} onChange={e=>eduPatch(i,'status',e.target.value)} placeholder="Ej: Completo 2025 / En curso"/></label></div></div>)}<button className={styles.add} onClick={()=>patch('education',[...data.education,emptyEdu()])}>+ Agregar estudio o curso</button></div>}
    {step===4&&<div className={styles.card}><span className={styles.kicker}>PASO 5</span><h2>Qué sabés hacer.</h2><p>Elegí habilidades reales. Es mejor tener seis creíbles que veinte genéricas.</p><label>Habilidades<textarea value={data.skills} onChange={e=>patch('skills',e.target.value)} placeholder="Ej: Atención al público, organización, ventas, redacción, fotografía..."/></label><label>Herramientas y programas<textarea value={data.tools} onChange={e=>patch('tools',e.target.value)} placeholder="Ej: Excel básico, Canva, Google Drive, sistema de caja..."/></label><label>Idiomas<textarea value={data.languages} onChange={e=>patch('languages',e.target.value)} placeholder="Ej: Inglés intermedio"/></label><div className={styles.grid2}><label>Disponibilidad <small>(opcional)</small><input value={data.availability} onChange={e=>patch('availability',e.target.value)} placeholder="Ej: Full time"/></label><label>Licencia / movilidad / otro dato útil <small>(opcional)</small><input value={data.license} onChange={e=>patch('license',e.target.value)} placeholder="Ej: Licencia B1"/></label></div></div>}
    {step===5&&<div className={styles.review}><div className={styles.reviewHead}><span>PRIMER CV COMPLETO</span><h2>Ya tenés una base real para trabajar.</h2><p>No intentamos “inflarlo”. El siguiente paso es pasarlo por el analizador de Postulá Mejor para detectar qué mejorar según el puesto que elegiste.</p></div><article className={styles.cv}><header><h1>{data.name||'Tu nombre'}</h1><b>{data.target||'Puesto objetivo'}</b><p>{[data.email,data.phone,data.city,data.linkedin].filter(Boolean).join(' · ')}</p></header><h3>Perfil</h3><p>{data.summary||`Busco una primera oportunidad para desarrollarme en ${data.target||'un área donde pueda aprender y aportar'}.`}</p><h3>Experiencia, proyectos y actividades</h3>{data.experience.filter(x=>x.title||x.place||x.tasks).map((x,i)=><section key={i}><b>{x.title||'Actividad'} {x.place&&`· ${x.place}`}</b><small>{x.period}</small><ul>{lines(x.tasks).map(t=><li key={t}>{t}</li>)}</ul></section>)}{data.projects&&<p>{data.projects}</p>}<h3>Formación</h3>{data.education.filter(x=>x.study||x.institution).map((x,i)=><p key={i}><b>{x.study}</b> {x.institution&&`· ${x.institution}`} {x.status&&`· ${x.status}`}</p>)}<h3>Habilidades</h3><p>{lines(data.skills).join(' · ')||'Completá tus habilidades en el paso anterior.'}</p>{data.tools&&<><h3>Herramientas</h3><p>{lines(data.tools).join(' · ')}</p></>}{data.languages&&<><h3>Idiomas</h3><p>{lines(data.languages).join(' · ')}</p></>}</article><div className={styles.finish}><button onClick={analyze}>Analizar y mejorar este CV gratis →</button><button className={styles.secondary} onClick={download}>Guardar borrador</button></div><p className={styles.finishNote}>Al continuar, cargamos este CV generado por vos en el analizador principal. No inventamos datos nuevos; después podés usar Orientación Laboral o compararlo con una búsqueda concreta.</p></div>}
    <div className={styles.nav}>{step>0&&step<5?<button onClick={()=>setStep(step-1)}>← Anterior</button>:<span/>}{step<5&&<button className={styles.next} disabled={!canNext} onClick={next}>Continuar →</button>}</div>
   </section>
  </div>
 </main>
}
