'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import type {PreviewGig} from '../postula-preview/gigs'

type FlexCard=PreviewGig&{real?:boolean;postId?:string}
type Draft={title:string;category:string;description:string;location_text:string;compensation_text:string;duration_text:string;scheduled_for:string}
const images=['https://images.pexels.com/photos/5691622/pexels-photo-5691622.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/3379943/pexels-photo-3379943.jpeg?auto=compress&cs=tinysrgb&w=900','https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=900']
const emptyDraft:Draft={title:'',category:'',description:'',location_text:'',compensation_text:'',duration_text:'',scheduled_for:''}
async function authHeaders(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
function whenLabel(value:string|null|undefined){if(!value)return'A coordinar';const d=new Date(value);return Number.isNaN(d.getTime())?'A coordinar':d.toLocaleString('es-AR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'})}

export default function ChangasExplorer({gigs,categories}:{gigs:PreviewGig[];categories:string[]}){
 const [category,setCategory]=useState('Para hoy'),[saved,setSaved]=useState<string[]>([]),[open,setOpen]=useState<FlexCard|null>(null),[chat,setChat]=useState(false),[real,setReal]=useState<FlexCard[]>([]),[publish,setPublish]=useState(false),[draft,setDraft]=useState<Draft>(emptyDraft),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[message,setMessage]=useState('')
 useEffect(()=>{fetch('/api/postula/flex').then(r=>r.json()).then(d=>{if(!d?.ok||!Array.isArray(d.posts))return;setReal(d.posts.map((p:any,i:number)=>({id:`real-${p.id}`,postId:String(p.id),real:true,title:String(p.title),category:String(p.category||'Otros'),location:String(p.location_text||'A coordinar'),when:whenLabel(p.scheduled_for),pay:String(p.compensation_text||'A acordar'),duration:String(p.duration_text||'A coordinar'),poster:'Comunidad PM',posterRole:p.company_id?'Empresa':'Usuario',rating:'nuevo',verified:p.verification_level==='verified',image:images[i%images.length],summary:String(p.description||''),requirements:['Confirmar alcance, horario y forma de pago por chat','No compartir claves ni documentación sensible','Reportar cualquier conducta sospechosa'],tags:[String(p.category||'Flex'),p.verification_level==='verified'?'Verificado':'Validación básica'].filter(Boolean)}))) }).catch(()=>{})},[])
 const all=useMemo(()=>[...real,...gigs],[real,gigs])
 const allCategories=useMemo(()=>Array.from(new Set([...categories,...real.map(x=>x.category)])),[categories,real])
 const filtered=useMemo(()=>category==='Para hoy'?all.filter(g=>/hoy|mañana/i.test(g.when)).concat(all.filter(g=>!/hoy|mañana/i.test(g.when)).slice(0,4)):all.filter(g=>g.category===category),[category,all])
 function toggle(id:string){setSaved(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id])}
 async function openPublish(){const {data}=await cvAuthClient().auth.getSession();if(!data.session){location.href='/cuenta?modo=crear&next=/trabajos-flex';return}setNotice('');setPublish(true)}
 async function create(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{const headers={'Content-Type':'application/json',...(await authHeaders())};const r=await fetch('/api/postula/flex',{method:'POST',headers,body:JSON.stringify({action:'create',...draft})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos publicar.');const p=d.post;const card:FlexCard={id:`real-${p.id}`,postId:String(p.id),real:true,title:p.title,category:p.category,location:p.location_text,when:whenLabel(p.scheduled_for),pay:p.compensation_text,duration:p.duration_text||'A coordinar',poster:'Tu publicación',posterRole:'Validación básica',rating:'nuevo',verified:false,image:images[real.length%images.length],summary:p.description,requirements:['Confirmar alcance, horario y forma de pago por chat','No compartir claves ni documentación sensible'],tags:[p.category,'Nueva']};setReal(v=>[card,...v]);setDraft(emptyDraft);setPublish(false);setNotice('Trabajo Flex publicado. Ya puede recibir respuestas.');setCategory(p.category)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos publicar.')}finally{setBusy(false)}}
 async function respond(e:FormEvent){e.preventDefault();if(!open?.real||!open.postId||busy)return;const clean=message.trim();if(clean.length<3)return;setBusy(true);setNotice('');try{const headers={'Content-Type':'application/json',...(await authHeaders())};if(!('Authorization' in headers)){location.href='/cuenta?modo=crear&next=/trabajos-flex';return}const r=await fetch('/api/postula/flex',{method:'POST',headers,body:JSON.stringify({action:'respond',post_id:open.postId,message:clean})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos enviar el mensaje.');setMessage('');setNotice('Mensaje enviado. La respuesta quedó asociada a este Trabajo Flex.');setChat(false)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos enviar el mensaje.')}finally{setBusy(false)}}
 return <>
  <div className="pm7-gig-cats">{allCategories.map(c=><button key={c} data-on={c===category} onClick={()=>setCategory(c)}>{c}</button>)}<button onClick={openPublish} style={{background:'#d9ff59',color:'#071827',fontWeight:950}}>+ Publicar Trabajo Flex</button></div>
  {notice&&<div className="pm8-notice" style={{margin:'12px 0'}}>{notice}</div>}
  <div className="pm7-gig-grid">{filtered.map(g=><article className="pm7-gig-card" key={g.id}>
    <div className="pm7-gig-photo" style={{backgroundImage:`url(${g.image})`}}><span>{g.when}</span><button onClick={()=>toggle(g.id)} data-saved={saved.includes(g.id)} aria-label="Guardar Trabajo Flex">{saved.includes(g.id)?'♥':'♡'}</button><div className="pm7-gig-price"><b>{g.pay}</b><small>{g.duration}</small></div></div>
    <div className="pm7-gig-body"><div className="pm7-gig-person"><span>{g.poster.split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</span><div><b>{g.poster}</b><small>{g.posterRole}{g.rating!=='nuevo'?` · ★ ${g.rating}`:' · publicación nueva'}{g.verified?' · verificado':''}</small></div></div><h3>{g.title}</h3><p>{g.summary}</p><div className="pm7-gig-tags">{g.tags.map(t=><span key={t}>{t}</span>)}</div><div className="pm7-gig-foot"><span>{g.location}</span><button onClick={()=>{setOpen(g);setChat(false);setNotice('')}}>Ver tarea</button></div></div>
   </article>)}</div>
  {open&&<div className="pm7-gig-modal" role="dialog" aria-modal="true"><div className="pm7-gig-modal-card"><button className="pm7-modal-close" onClick={()=>{setOpen(null);setChat(false);setNotice('')}}>×</button><div className="pm7-modal-image" style={{backgroundImage:`url(${open.image})`}}/><div className="pm7-modal-content"><span className="pm7-mini-label">{open.category} · {open.when}</span><h2>{open.title}</h2><div className="pm7-modal-pay"><b>{open.pay}</b><span>{open.duration}</span></div><p>{open.summary}</p><h4>Antes de aceptar</h4><ul>{open.requirements.map(x=><li key={x}>{x}</li>)}</ul><div className="pm7-gig-person big"><span>{open.poster.split(/\s+/).map(x=>x[0]).join('').slice(0,2)}</span><div><b>{open.poster}</b><small>{open.posterRole}{open.verified?' · identidad verificada':' · validación básica'}</small></div></div>{chat?<form className="pm7-mini-chat" onSubmit={open.real?respond:e=>e.preventDefault()}><div>Consultá todo lo necesario antes de acordar la tarea.</div><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Escribí un mensaje…"/><button disabled={busy||!message.trim()}>{busy?'Enviando…':'Enviar'}</button></form>:<button className="pm7-primary-wide" onClick={()=>setChat(true)}>Chatear antes de aceptar</button>}<div className="pm7-safety-line">La tarea no se confirma sin acuerdo de ambas partes. No compartas datos bancarios, claves ni documentos sensibles por chat.</div></div></div></div>}
  {publish&&<div className="pm7-gig-modal" role="dialog" aria-modal="true"><form className="pm7-gig-modal-card" onSubmit={create}><button type="button" className="pm7-modal-close" onClick={()=>setPublish(false)}>×</button><div className="pm7-modal-content" style={{maxWidth:720,margin:'0 auto'}}><span className="pm7-mini-label">PUBLICAR TRABAJO FLEX</span><h2>Contá qué necesitás, cuánto pagás y dónde.</h2><p>Está pensado para tareas puntuales. Si por su realidad corresponde una relación laboral, publicalo como empleo.</p><div className="pm8-form-grid"><label>Título<input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))} required placeholder="Ej. Ayuda para ordenar depósito"/></label><label>Categoría<input value={draft.category} onChange={e=>setDraft(v=>({...v,category:e.target.value}))} required placeholder="Ej. Logística"/></label><label className="wide">Descripción<textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))} required rows={4} placeholder="Qué hay que hacer, qué herramientas hay y cualquier detalle importante."/></label><label>Zona<input value={draft.location_text} onChange={e=>setDraft(v=>({...v,location_text:e.target.value}))} required placeholder="Palermo, CABA"/></label><label>Pago / importe<input value={draft.compensation_text} onChange={e=>setDraft(v=>({...v,compensation_text:e.target.value}))} required placeholder="$40.000 por tarea"/></label><label>Duración<input value={draft.duration_text} onChange={e=>setDraft(v=>({...v,duration_text:e.target.value}))} placeholder="3 horas"/></label><label>Fecha y hora<input type="datetime-local" value={draft.scheduled_for} onChange={e=>setDraft(v=>({...v,scheduled_for:e.target.value}))}/></label></div><div className="pm7-safety-line">Al publicar aceptás los Términos y la Política de Privacidad. Postulá Mejor puede pausar publicaciones engañosas, riesgosas o que intenten encubrir una relación laboral.</div><button className="pm7-primary-wide" disabled={busy}>{busy?'Publicando…':'Publicar Trabajo Flex'}</button></div></form></div>}
 </>
}
