'use client'

import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import type {PreviewGig} from '../postula-preview/gigs'
import FlexCredits from './FlexCredits'
import FlexImagePicker from './FlexImagePicker'
import {flexCategoryImage} from './flexVisuals'

type ListingType='request'|'offer'
type DirectionFilter='all'|ListingType
type FlexCard=PreviewGig&{
 real?:boolean;postId?:string;publisherAvatar?:string;publisherKind?:'person'|'company';privateIdentity?:boolean;imageSource?:string;contactPhone?:string;listingType:ListingType;availability?:string
}
type Draft={listing_type:ListingType;title:string;category:string;description:string;location_text:string;compensation_text:string;duration_text:string;availability_text:string;scheduled_for:string;image_path:string;image_url:string;allow_phone_contact:boolean;contact_phone:string}
const blankDraft=(listingType:ListingType='request'):Draft=>({listing_type:listingType,title:'',category:'',description:'',location_text:'',compensation_text:'',duration_text:'',availability_text:'',scheduled_for:'',image_path:'',image_url:'',allow_phone_contact:false,contact_phone:''})
const PAGE_SIZE=18

async function authHeaders(){const{data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
function cleanType(v:unknown):ListingType{return String(v||'request')==='offer'?'offer':'request'}
function whenLabel(value:string|null|undefined){if(!value)return'A coordinar';const d=new Date(value);return Number.isNaN(d.getTime())?'A coordinar':d.toLocaleDateString('es-AR',{day:'2-digit',month:'short'})}
function isExample(g:PreviewGig){return g.posterRole.includes('Vista ilustrativa')||g.tags.includes('Ejemplo')}
function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()||'PM'}
function phoneHref(value:string){return `tel:${value.replace(/[^\d+]/g,'')}`}
function norm(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9$+\s-]/g,' ').replace(/\s+/g,' ').trim()}
function typeLabel(type:ListingType){return type==='offer'?'OFRECE SERVICIO':'BUSCA PROFESIONAL'}
function typeTitle(type:ListingType){return type==='offer'?'Ofrezco un servicio':'Necesito un servicio'}
function employmentWarningFor(draft:Draft){
 const hay=norm(`${draft.title} ${draft.category} ${draft.description} ${draft.duration_text} ${draft.compensation_text} ${draft.availability_text}`)
 if(!hay)return''
 const hard=/\b(ninera|ninero|babysitter|empleada domestica|empleado domestico|personal domestico|personal de casas particulares|ama de llaves)\b/
 const strong=/\b(relacion de dependencia|relacion laboral|puesto de trabajo|puesto laboral|vacante|sueldo|salario|jornada laboral|full time|part time|media jornada|empleado|empleada|incorporacion inmediata|obra social|aguinaldo|presentismo|franco semanal|contrato laboral)\b/
 const role=/\b(cajero|cajera|vendedor|vendedora|repositor|repositora|recepcionista|administrativo|administrativa|secretario|secretaria|operario|operaria|mozo|moza|camarero|camarera|cocinero|cocinera|bachero|bachera|chofer|conductor|conductora|sereno|vigilador|vigiladora|encargado|encargada|supervisor|supervisora|gerente|telemarketer|promotor|promotora|playero|playera|cuidador|cuidadora)\b/
 const hiring=/\b(se busca|buscamos|busco|se necesita|necesitamos|contratamos|para cubrir|cubrir puesto|reemplazo de personal|turno fijo|horario fijo|lunes a viernes|lunes a sabado|todos los dias|cada semana|semanal|mensual|permanente|estable)\b/
 if(hard.test(hay)||strong.test(hay)||(role.test(hay)&&hiring.test(hay)))return'Esto parece una búsqueda laboral. Publicalo desde una cuenta de Empresa en Empleos. Servicio Flex sirve para prestaciones independientes y no para cubrir puestos ni relaciones laborales.'
 return''
}
function cardFromPost(p:any):FlexCard{
 const category=String(p.category||'Otros'),kind=p.publisher_kind==='company'?'company':'person',listingType=cleanType(p.listing_type)
 const requirements=listingType==='offer'?['Consultá disponibilidad, alcance y precio antes de coordinar','El pago se acuerda directamente entre las partes','No compartas claves ni documentación sensible','Reportá cualquier conducta sospechosa']:['Confirmá alcance, fecha e importe antes de acordar','El pago se acuerda directamente entre las partes','No compartas claves ni documentación sensible','Reportá cualquier conducta sospechosa']
 return {id:`real-${p.id}`,postId:String(p.id),real:true,title:String(p.title),category,location:String(p.location_text||'A coordinar'),when:listingType==='offer'?String(p.availability_text||'Disponibilidad a coordinar'):whenLabel(p.scheduled_for),pay:String(p.compensation_text||'A acordar'),duration:String(p.duration_text||'A coordinar'),poster:String(p.publisher_display_name||(kind==='company'?'Empresa':'Persona')),posterRole:p.public_identity===false?(kind==='company'?'Empresa · identidad reservada':'Perfil privado'):kind==='company'?'Empresa':'Persona',rating:'nuevo',verified:p.verification_level==='verified',image:String(p.image_url||flexCategoryImage(category)),summary:String(p.description||''),requirements,tags:[category,listingType==='offer'?'Servicio ofrecido':'Solicitud',p.verification_level==='verified'?'Verificado':'Validación básica'].filter(Boolean),publisherAvatar:String(p.publisher_avatar_public||''),publisherKind:kind,privateIdentity:p.public_identity===false,imageSource:String(p.image_source||'category'),contactPhone:String(p.contact_phone_public||''),listingType,availability:String(p.availability_text||'')}
}
function cardFromExample(g:PreviewGig):FlexCard{return {...g,publisherKind:'person',listingType:cleanType(g.listingType)} as FlexCard}
function PublisherAvatar({gig}:{gig:FlexCard}){
 if(gig.publisherAvatar)return <span className="pm33-publisher-avatar has-photo" style={{backgroundImage:`url(${gig.publisherAvatar})`}} aria-hidden="true"/>
 return <span className="pm33-publisher-avatar" data-kind={gig.publisherKind||'person'} aria-hidden="true">{gig.publisherKind==='company'?<svg viewBox="0 0 24 24"><path d="M4 21V6.5L12 3v18M4 21h16M15 9h5v12M7 9h2m-2 4h2m-2 4h2"/></svg>:gig.privateIdentity?<svg viewBox="0 0 24 24"><circle cx="12" cy="8" r="4"/><path d="M4.8 21c.7-4.4 3-6.5 7.2-6.5s6.5 2.1 7.2 6.5"/></svg>:initials(gig.poster)}</span>
}

export default function FlexMarketplaceExplorer({gigs,categories}:{gigs:PreviewGig[];categories:string[]}){
 const catsRef=useRef<HTMLDivElement|null>(null)
 const[category,setCategory]=useState('Todos'),[query,setQuery]=useState(''),[zone,setZone]=useState(''),[publisherFilter,setPublisherFilter]=useState('Todos'),[timingFilter,setTimingFilter]=useState('Todos'),[directionFilter,setDirectionFilter]=useState<DirectionFilter>('all'),[visibleCount,setVisibleCount]=useState(PAGE_SIZE)
 const[saved,setSaved]=useState<string[]>([]),[open,setOpen]=useState<FlexCard|null>(null),[chat,setChat]=useState(false),[real,setReal]=useState<FlexCard[]>([]),[publish,setPublish]=useState(false),[authChoice,setAuthChoice]=useState(false),[draft,setDraft]=useState<Draft>(blankDraft()),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[message,setMessage]=useState(''),[acceptRules,setAcceptRules]=useState(false),[selectedCompanyId,setSelectedCompanyId]=useState<string|null>(null),[creditRefresh,setCreditRefresh]=useState(0),[publicIdentity,setPublicIdentity]=useState(true)

 async function loadPosts(){
  const headers=await authHeaders();const r=await fetch('/api/postula/flex',{headers,cache:'no-store'});const d=await r.json().catch(()=>({}));if(!d?.ok||!Array.isArray(d.posts))return
  const cards=d.posts.map((p:any)=>cardFromPost(p));setReal(cards);if(Array.isArray(d.favorites))setSaved(d.favorites.map((id:any)=>`real-${id}`));const deep=new URLSearchParams(location.search).get('tarea');if(deep){const found=cards.find((x:FlexCard)=>x.postId===deep);if(found){setOpen(found);setChat(false)}}
 }
 async function openPublish(initialType?:ListingType){
  const type=cleanType(initialType||sessionStorage.getItem('pm_flex_publish_type'))
  const{data}=await cvAuthClient().auth.getSession()
  if(!data.session){setDraft(blankDraft(type));setPublish(false);setAuthChoice(true);return}
  setAuthChoice(false);setNotice('');setAcceptRules(false);setSelectedCompanyId(null);setCreditRefresh(v=>v+1);setDraft(blankDraft(type));setPublicIdentity(true);setPublish(true)
 }
 function askToPublish(type:ListingType){window.dispatchEvent(new CustomEvent('pm:flex-legal-open',{detail:{listingType:type}}))}

 useEffect(()=>{void loadPosts()},[])
 useEffect(()=>{
  const launch=(event:Event)=>{const detail=(event as CustomEvent<{listingType?:ListingType}>).detail;void openPublish(cleanType(detail?.listingType))}
  window.addEventListener('pm:flex-publish',launch as EventListener)
  const params=new URLSearchParams(location.search)
  if(params.get('publicar')==='1'){
   const type=cleanType(params.get('tipo'));params.delete('publicar');params.delete('tipo');history.replaceState({},'',`${location.pathname}${params.toString()?`?${params}`:''}`);window.setTimeout(()=>askToPublish(type),0)
  }
  return()=>window.removeEventListener('pm:flex-publish',launch as EventListener)
 },[])
 useEffect(()=>{if(!publish&&!authChoice&&!open)return;const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[publish,authChoice,open])

 const all=useMemo<FlexCard[]>(()=>[...real,...gigs.map(cardFromExample)],[real,gigs])
 const allCategories=useMemo(()=>['Todos',...Array.from(new Set([...categories,...real.map(x=>x.category)]))],[categories,real])
 const publishCategories=useMemo(()=>Array.from(new Set(allCategories.filter(x=>x!=='Todos'&&x!=='Para hoy').concat('Otros'))),[allCategories])
 const filtered=useMemo(()=>{
  const q=norm(query),z=norm(zone)
  return all.filter(g=>{
   const hay=norm(`${g.title} ${g.summary} ${g.poster} ${g.category} ${g.tags.join(' ')} ${g.location} ${typeLabel(g.listingType)}`)
   const catOk=category==='Todos'||(category==='Para hoy'?/hoy/i.test(g.when):g.category===category)
   const zoneOk=!z||norm(g.location).includes(z)||(z==='remoto'&&norm(g.location).includes('remoto'))
   const publisherOk=publisherFilter==='Todos'||(publisherFilter==='Empresas'?g.publisherKind==='company':publisherFilter==='Personas'?g.publisherKind!=='company':true)
   const timingOk=timingFilter==='Todos'||g.listingType==='offer'||(timingFilter==='Hoy'?/hoy/i.test(g.when):timingFilter==='A coordinar'?/coordinar/i.test(g.when):timingFilter==='Con fecha'?!/coordinar/i.test(g.when):true)
   const directionOk=directionFilter==='all'||g.listingType===directionFilter
   return(!q||hay.includes(q))&&catOk&&zoneOk&&publisherOk&&timingOk&&directionOk
  })
 },[all,query,zone,category,publisherFilter,timingFilter,directionFilter])
 const visible=useMemo(()=>filtered.slice(0,visibleCount),[filtered,visibleCount])
 useEffect(()=>{setVisibleCount(PAGE_SIZE)},[query,zone,category,publisherFilter,timingFilter,directionFilter])
 const previewImage=draft.image_url||flexCategoryImage(draft.category||'Otros')
 const previewWhen=draft.listing_type==='offer'?(draft.availability_text||'Disponibilidad a coordinar'):(draft.scheduled_for?whenLabel(draft.scheduled_for):'Fecha a coordinar')
 const authNext=encodeURIComponent(`/servicios-flex?clasificar=1&tipo=${draft.listing_type}`)
 const employmentWarning=useMemo(()=>employmentWarningFor(draft),[draft])
 const offering=draft.listing_type==='offer'

 async function toggle(g:FlexCard){
  const next=!saved.includes(g.id);setSaved(v=>next?[...v,g.id]:v.filter(x=>x!==g.id));if(!g.real||!g.postId)return
  const{data}=await cvAuthClient().auth.getSession();if(!data.session){setSaved(v=>v.filter(x=>x!==g.id));location.assign('/login?next=/servicios-flex');return}
  try{const r=await fetch('/api/postula/flex',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({action:'favorite',post_id:g.postId,saved:next})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos actualizar favoritos.');setNotice(next?'Guardado en Mi cuenta.':'Quitado de favoritos.')}catch(e){setSaved(v=>next?v.filter(x=>x!==g.id):[...v,g.id]);setNotice(e instanceof Error?e.message:'No pudimos actualizar favoritos.')}
 }
 function scrollCats(direction:-1|1){catsRef.current?.scrollBy({left:direction*Math.min(520,Math.max(280,catsRef.current.clientWidth*.72)),behavior:'smooth'})}
 function clearFilters(){setQuery('');setZone('');setCategory('Todos');setPublisherFilter('Todos');setTimingFilter('Todos');setDirectionFilter('all')}
 async function create(e:FormEvent){
  e.preventDefault();if(busy)return;if(employmentWarning){setNotice(employmentWarning);return}if(!acceptRules){setNotice('Para publicar necesitás aceptar las reglas de publicación, los Términos específicos de Servicios Flex y la Política de Privacidad.');return}setBusy(true);setNotice('')
  try{const headers={'Content-Type':'application/json',...(await authHeaders())};const r=await fetch('/api/postula/flex',{method:'POST',headers,body:JSON.stringify({action:'create',...draft,company_id:selectedCompanyId,public_identity:publicIdentity,policy_version:'services-flex-2026-08-26',responsibility_ack:true})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok){if(d?.code==='no_credits')setCreditRefresh(v=>v+1);throw new Error(d?.error||'No pudimos publicar.')}const type=cleanType(d?.post?.listing_type||draft.listing_type);setDraft(blankDraft(type));setAcceptRules(false);setCreditRefresh(v=>v+1);setPublish(false);await loadPosts();setDirectionFilter(type);setCategory(String(d?.post?.category||'Todos'));setNotice(type==='offer'?'Tu servicio quedó publicado y ya puede recibir consultas.':'Tu solicitud quedó publicada y ya puede recibir propuestas.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos publicar.')}finally{setBusy(false)}
 }
 async function respond(e:FormEvent){e.preventDefault();if(!open?.real||!open.postId||busy)return;const clean=message.trim();if(clean.length<3)return;setBusy(true);setNotice('');try{const{data}=await cvAuthClient().auth.getSession();if(!data.session){location.assign('/login?next=/servicios-flex');return}const r=await fetch('/api/postula/flex',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${data.session.access_token}`},body:JSON.stringify({action:'respond',post_id:open.postId,message:clean})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos enviar el mensaje.');setMessage('');setNotice('Mensaje enviado. La conversación quedó asociada a este Servicio Flex.');setChat(false)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos enviar el mensaje.')}finally{setBusy(false)}}

 return <>
  <div className="pm39-direction-cards" aria-label="Elegí cómo usar Servicios Flex">
   <article data-type="request"><span>NECESITO UN SERVICIO</span><h3>Publicá lo que necesitás resolver.</h3><p>Ej. reparar un aire, armar un mueble, sacar fotos o resolver una tarea puntual.</p><button type="button" onClick={()=>askToPublish('request')}>+ Buscar a alguien</button></article>
   <article data-type="offer"><span>OFREZCO UN SERVICIO</span><h3>Mostrá lo que sabés hacer.</h3><p>Publicá tu servicio, zona, precio orientativo y disponibilidad para que te encuentren.</p><button type="button" onClick={()=>askToPublish('offer')}>+ Ofrecer mi servicio</button></article>
  </div>
  <div className="pm39-market-note"><b>Funciona en las dos direcciones.</b><span>Podés encontrar a alguien que ya ofrece lo que necesitás o publicar una solicitud y recibir consultas.</span></div>
  <div className="pm38-flex-search"><label><span>Servicio o palabra clave</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Ej. aire acondicionado, muebles, fotografía"/></label><label><span>Zona o modalidad</span><input value={zone} onChange={e=>setZone(e.target.value)} placeholder="Ej. Palermo, Córdoba, remoto"/></label><div><span>RESULTADOS</span><b>{filtered.length}</b><small>publicaciones encontradas</small></div></div>
  <div className="pm39-listing-filter" role="group" aria-label="Tipo de publicación"><button data-on={directionFilter==='all'} onClick={()=>setDirectionFilter('all')}>Todos</button><button data-on={directionFilter==='request'} onClick={()=>setDirectionFilter('request')}>Buscan un servicio</button><button data-on={directionFilter==='offer'} onClick={()=>setDirectionFilter('offer')}>Ofrecen un servicio</button></div>
  <div className="pm15-category-shell" aria-label="Categorías de Servicios Flex"><button type="button" className="pm15-cat-arrow left" onClick={()=>scrollCats(-1)} aria-label="Ver categorías anteriores">←</button><div className="pm7-gig-cats" ref={catsRef}>{allCategories.map(c=><button key={c} data-on={c===category} onClick={()=>setCategory(c)}>{c==='Todos'?'Todos los servicios':c}</button>)}</div><button type="button" className="pm15-cat-arrow right" onClick={()=>scrollCats(1)} aria-label="Ver más categorías">→</button></div>
  <div className="pm38-flex-filters"><label><span>Quién publica</span><select value={publisherFilter} onChange={e=>setPublisherFilter(e.target.value)}><option>Todos</option><option>Personas</option><option>Empresas</option></select></label><label><span>Cuándo</span><select value={timingFilter} onChange={e=>setTimingFilter(e.target.value)}><option>Todos</option><option>Hoy</option><option>Con fecha</option><option>A coordinar</option></select></label><label><span>Categoría</span><select value={category} onChange={e=>setCategory(e.target.value)}>{allCategories.map(c=><option key={c} value={c}>{c==='Todos'?'Todas':c}</option>)}</select></label><button type="button" onClick={clearFilters}>Limpiar filtros</button></div>
  {notice&&<div className="pm8-notice" style={{margin:'12px 0'}}>{notice}</div>}
  {filtered.length?<><div className="pm7-gig-grid">{visible.map(g=><article className="pm7-gig-card pm39-market-card" data-listing-type={g.listingType} key={g.id}>
    <div className="pm7-gig-photo" style={{backgroundImage:`url(${g.image})`}}><div className="pm39-type-badge" data-type={g.listingType}>{typeLabel(g.listingType)}</div><span>{g.when}</span><button onClick={()=>void toggle(g)} data-saved={saved.includes(g.id)} aria-label="Guardar Servicio Flex">{saved.includes(g.id)?'♥':'♡'}</button><div className="pm7-gig-price"><b>{g.pay}</b><small>{g.duration}</small></div></div>
    <div className="pm7-gig-body"><div className="pm7-gig-person"><PublisherAvatar gig={g}/><div><b>{g.poster}</b><small>{isExample(g)?g.posterRole:<>{g.posterRole}{g.rating!=='nuevo'?` · ★ ${g.rating}`:' · publicación nueva'}{g.verified?' · verificado':''}</>}</small></div></div><h3>{g.title}</h3><p>{g.summary}</p><div className="pm7-gig-tags">{g.tags.map(t=><span key={t}>{t}</span>)}</div><div className="pm7-gig-foot"><span>{g.location}</span><button onClick={()=>{setOpen(g);setChat(false);setNotice('')}}>{g.listingType==='offer'?'Ver servicio':'Ver solicitud'}</button></div></div>
   </article>)}</div>{visible.length<filtered.length&&<div className="pm38-flex-more"><button type="button" onClick={()=>setVisibleCount(v=>Math.min(v+PAGE_SIZE,filtered.length))}>Ver más Servicios Flex · {filtered.length-visible.length} restantes</button></div>}</>:<div className="pm38-flex-empty"><b>No encontramos Servicios Flex con esos filtros.</b><p>Probá otra categoría, zona o tipo de publicación.</p><button type="button" onClick={clearFilters}>Ver todas las publicaciones</button></div>}

  {open&&<div className="pm7-gig-modal" role="dialog" aria-modal="true"><div className="pm7-gig-modal-card"><button className="pm7-modal-close" onClick={()=>{setOpen(null);setChat(false);setNotice('')}} aria-label="Cerrar servicio">×</button><div className="pm7-modal-image" style={{backgroundImage:`url(${open.image})`}}/><div className="pm7-modal-content"><div className="pm39-modal-type" data-type={open.listingType}>{typeLabel(open.listingType)}</div><span className="pm7-mini-label">{open.category} · {open.when}</span><h2>{open.title}</h2><div className="pm7-modal-pay"><b>{open.pay}</b><span>{open.duration}</span></div><p>{open.summary}</p><h4>Antes de acordar</h4><ul>{open.requirements.map(x=><li key={x}>{x}</li>)}</ul><div className="pm7-gig-person big"><PublisherAvatar gig={open}/><div><b>{open.poster}</b><small>{isExample(open)?open.posterRole:<>{open.posterRole}{open.verified?' · identidad verificada':' · validación básica'}</>}</small></div></div>{isExample(open)?<><div className="pm7-safety-line">Este contenido es ilustrativo. Muestra cómo se ve una publicación de Servicios Flex y no tiene una persona real detrás.</div><button className="pm7-primary-wide" onClick={()=>{const type=open.listingType;setOpen(null);askToPublish(type)}}>Publicar algo similar</button></>:<>{chat?<form className="pm7-mini-chat" onSubmit={respond}><div>{open.listingType==='offer'?'Consultá disponibilidad, alcance y precio antes de coordinar.':'Contale por qué te interesa y acordá todos los detalles antes de empezar.'}</div><input value={message} onChange={e=>setMessage(e.target.value)} placeholder={open.listingType==='offer'?'Hola, quería consultar por este servicio…':'Hola, me interesa esta solicitud…'}/><button disabled={busy||!message.trim()}>{busy?'Enviando…':'Enviar'}</button></form>:<button className="pm7-primary-wide" onClick={()=>setChat(true)}>{open.listingType==='offer'?'Consultar por este servicio':'Me interesa · enviar mensaje'}</button>}{open.contactPhone&&<a href={phoneHref(open.contactPhone)} className="pm39-phone-link">Llamar · {open.contactPhone}</a>}</>}<div className="pm7-safety-line">El servicio no se confirma sin acuerdo de ambas partes. El pago se acuerda directamente entre ustedes. Postulá Mejor no recibe ni custodia ese dinero.</div></div></div></div>}

  {authChoice&&<div className="pm34-auth-overlay" role="dialog" aria-modal="true" aria-labelledby="pm34-auth-title"><div className="pm34-auth-card"><button type="button" className="pm34-close" onClick={()=>setAuthChoice(false)} aria-label="Cerrar">×</button><span className="pm34-kicker">{typeLabel(draft.listing_type)}</span><h2 id="pm34-auth-title">¿Ya tenés una cuenta?</h2><p>Para publicar necesitamos asociar esta publicación a una cuenta. Elegí cómo querés continuar.</p><div className="pm34-auth-actions"><a className="pm34-auth-login" href={`/login?next=${authNext}`}><span>Ya tengo cuenta</span><b>Iniciar sesión</b><small>Entrás y volvés directo a Servicios Flex.</small></a><a className="pm34-auth-signup" href={`/registro?next=${authNext}`}><span>Soy nuevo/a</span><b>Crear cuenta gratis</b><small>Una cuenta sirve para Empleos y Servicios Flex.</small></a></div><button type="button" className="pm34-auth-cancel" onClick={()=>setAuthChoice(false)}>Seguir viendo servicios</button></div></div>}

  {publish&&<div className="pm34-publish-overlay" role="dialog" aria-modal="true" aria-labelledby="pm34-publish-title"><form className="pm34-publish-card" onSubmit={create}>
   <button type="button" className="pm34-close pm34-publish-close" onClick={()=>{setPublish(false);setAcceptRules(false)}} aria-label="Cerrar">×</button>
   <header className="pm34-publish-head"><div><span className="pm34-kicker">PUBLICAR SERVICIO FLEX</span><h2 id="pm34-publish-title">{offering?'Mostrá el servicio que ofrecés.':'Contá qué necesitás resolver.'}</h2><p>{offering?'Tu publicación puede seguir activa para que nuevas personas te encuentren. Cada trabajo se acuerda de forma independiente.':'Publicá una necesidad puntual y recibí consultas de personas que puedan resolverla.'}</p></div><div className="pm34-publish-steps" aria-hidden="true"><span><i>1</i> Tipo</span><span><i>2</i> Datos</span><span><i>3</i> Publicación</span></div></header>

   <div className="pm34-publish-layout"><div className="pm34-publish-main">
    <section className="pm34-section pm39-type-picker"><div className="pm34-section-title"><span>00 · TIPO DE PUBLICACIÓN</span><h3>¿Qué querés hacer?</h3><p>Podés buscar a alguien o publicar tu propio servicio.</p></div><div><button type="button" data-on={!offering} onClick={()=>setDraft(v=>({...blankDraft('request'),category:v.category,image_path:v.image_path,image_url:v.image_url}))}><b>Necesito un servicio</b><span>Busco a alguien para resolver algo.</span></button><button type="button" data-on={offering} onClick={()=>setDraft(v=>({...blankDraft('offer'),category:v.category,image_path:v.image_path,image_url:v.image_url}))}><b>Ofrezco un servicio</b><span>Quiero que me encuentren por lo que hago.</span></button></div></section>
    <section className="pm34-section pm34-credit-section"><div className="pm34-section-title"><span>CUENTA Y CRÉDITOS</span><h3>¿Desde qué cuenta publicás?</h3></div><FlexCredits companyId={selectedCompanyId} onCompanyChange={setSelectedCompanyId} refreshKey={creditRefresh}/></section>

    <section className="pm34-section"><div className="pm34-section-title"><span>01 · EL SERVICIO</span><h3>{offering?'Presentá lo que hacés.':'Contá qué necesitás.'}</h3><p>{offering?'Un nombre claro, tu experiencia y el alcance del servicio ayudan a que te contacten.':'Un título concreto y una descripción simple reciben mejores respuestas.'}</p></div><div className="pm34-fields"><label className="pm34-field"><span>{offering?'Nombre del servicio':'Título de la tarea'} <b>*</b></span><input value={draft.title} onChange={e=>setDraft(v=>({...v,title:e.target.value}))} required minLength={5} placeholder={offering?'Ej. Instalación y reparación de aire acondicionado':'Ej. Necesito reparar un aire que no enfría'}/><small>{offering?'Describí un servicio independiente, no una búsqueda de empleo.':'Describí una necesidad concreta, no un puesto permanente.'}</small></label><label className="pm34-field"><span>Categoría <b>*</b></span><select value={draft.category} onChange={e=>setDraft(v=>({...v,category:e.target.value,image_path:'',image_url:''}))} required><option value="">Elegí una categoría</option>{publishCategories.map(c=><option key={c} value={c}>{c}</option>)}</select><small>La imagen predeterminada se adapta a esta categoría.</small></label><label className="pm34-field full"><span>Descripción <b>*</b></span><textarea value={draft.description} onChange={e=>setDraft(v=>({...v,description:e.target.value}))} required minLength={15} rows={5} placeholder={offering?'Contá qué hacés, qué incluye el servicio, tu experiencia y qué debería saber alguien antes de consultarte.':'Explicá qué necesitás, el resultado esperado, materiales disponibles y cualquier detalle importante.'}/><small>{draft.description.length}/1800 · No publiques claves ni documentación sensible.</small></label></div>{employmentWarning&&<div className="pm38-employment-warning"><b>Esto corresponde a Empleos, no a Servicio Flex.</b><p>{employmentWarning}</p><a href="/empresas/registro">Ir a publicar como Empresa</a></div>}</section>

    <section className="pm34-section"><div className="pm34-section-title"><span>02 · ZONA, PRECIO Y DISPONIBILIDAD</span><h3>{offering?'Definí cómo pueden encontrarte.':'Dejá lo importante y acordá el resto después.'}</h3><p>{offering?'Zona, precio orientativo y disponibilidad hacen tu publicación mucho más útil.':'Sólo la zona o modalidad es obligatoria. Fecha, importe y duración pueden quedar a coordinar.'}</p></div><div className="pm34-fields"><label className="pm34-field"><span>Zona o modalidad <b>*</b></span><input value={draft.location_text} onChange={e=>setDraft(v=>({...v,location_text:e.target.value}))} required placeholder="Ej. Palermo, CABA · o Remoto"/></label>{offering?<label className="pm34-field"><span>Disponibilidad</span><input value={draft.availability_text} onChange={e=>setDraft(v=>({...v,availability_text:e.target.value}))} placeholder="Ej. Lun a sáb · turnos a coordinar"/><small>Podés actualizarla después desde Mis publicaciones.</small></label>:<label className="pm34-field"><span>Fecha estimada</span><input type="date" value={draft.scheduled_for} onChange={e=>setDraft(v=>({...v,scheduled_for:e.target.value}))}/><small>Opcional. Si no la sabés todavía, queda “A coordinar”.</small></label>}<label className="pm34-field"><span>{offering?'Precio orientativo':'Importe / presupuesto'}</span><input value={draft.compensation_text} onChange={e=>setDraft(v=>({...v,compensation_text:e.target.value}))} placeholder={offering?'Ej. Desde $35.000':'Ej. Hasta $60.000 o $40.000 por tarea'}/><small>{offering?'Podés usar “Desde”, por hora o por servicio.':'Opcional. Si lo dejás vacío, se mostrará “A acordar”.'}</small></label><label className="pm34-field"><span>{offering?'Duración típica':'Duración estimada'}</span><input value={draft.duration_text} onChange={e=>setDraft(v=>({...v,duration_text:e.target.value}))} placeholder={offering?'Ej. 1 a 3 horas según trabajo':'Ej. 3 horas'}/><small>Opcional. También pueden definirla por mensajes.</small></label></div></section>

    <section className="pm34-section"><div className="pm34-section-title"><span>03 · IMAGEN, CONTACTO E IDENTIDAD</span><h3>Elegí cómo se va a mostrar y cómo te contactan.</h3><p>Mensajes de Postulá Mejor queda siempre activo. El teléfono es opcional.</p></div><FlexImagePicker category={draft.category} imagePath={draft.image_path} imageUrl={draft.image_url} onChange={({path,url})=>setDraft(v=>({...v,image_path:path,image_url:url}))} onReset={()=>setDraft(v=>({...v,image_path:'',image_url:''}))}/>
     <div className="pm39-contact-box"><div><span>MEDIO DE CONTACTO</span><b>Mensajes primero, teléfono si querés.</b></div><div className="pm39-contact-active"><div><b>Mensajería interna</b><small>Predeterminada y siempre disponible.</small></div><span>ACTIVA</span></div><label className="pm39-phone-check"><input type="checkbox" checked={draft.allow_phone_contact} onChange={e=>setDraft(v=>({...v,allow_phone_contact:e.target.checked,contact_phone:e.target.checked?v.contact_phone:''}))}/><span><b>También pueden contactarme por teléfono</b><small>Tu número sólo será visible para usuarios que hayan iniciado sesión.</small></span></label>{draft.allow_phone_contact&&<label className="pm34-field"><span>Teléfono <b>*</b></span><input type="tel" value={draft.contact_phone} onChange={e=>setDraft(v=>({...v,contact_phone:e.target.value}))} required inputMode="tel" autoComplete="tel" placeholder="Ej. +54 9 11 4054 0970"/></label>}</div>
     <div className="pm33-identity-choice pm34-identity"><div><span>IDENTIDAD EN LA PUBLICACIÓN</span><b>{selectedCompanyId?'¿Mostrar la identidad de la empresa?':'¿Mostrar tu identidad?'}</b><p>{publicIdentity?selectedCompanyId?'Se mostrará el nombre y el logo de la empresa si tiene uno cargado.':'Se mostrará tu nombre y tu foto si la tenés cargada.':'La publicación mantendrá la identidad reservada.'}</p></div><button type="button" data-on={publicIdentity} onClick={()=>setPublicIdentity(v=>!v)}><i/><span>{publicIdentity?'Visible':'Reservada'}</span></button></div></section>

    <section className="pm34-section pm34-rules"><div className="pm34-section-title"><span>04 · REGLAS DE PUBLICACIÓN</span><h3>Publicá un servicio real, legal y seguro.</h3></div><div className="pm34-rule-grid"><p><b>Información verdadera.</b> La cuenta que publica es responsable por lo que ofrece o solicita.</p><p><b>Sin datos sensibles.</b> No se permiten contraseñas, credenciales bancarias ni pagos previos injustificados.</p><p><b>Sin abuso ni fraude.</b> No se admiten tareas ilegales, engañosas, inseguras, esquemas piramidales, acoso o explotación.</p><p><b>No reemplaza un empleo.</b> Una relación con dependencia, continuidad, supervisión o cobertura de un puesto habitual debe ir por Empleos.</p></div><div data-services-flex-payment="1" className="pm39-payment-note"><b>Pago directo entre las partes</b>Postulá Mejor no recibe, retiene, custodia ni libera el dinero del servicio.</div><label className="pm34-policy-check"><input type="checkbox" required checked={acceptRules} onChange={e=>setAcceptRules(e.target.checked)}/><span>Leí y acepto estas reglas, los <a href="/terminos" target="_blank" rel="noopener noreferrer">Términos y Condiciones</a>, los <a href="/terminos/servicios-flex" target="_blank" rel="noopener noreferrer">Términos específicos de Servicios Flex</a> y la <a href="/privacidad" target="_blank" rel="noopener noreferrer">Política de Privacidad</a>.</span></label></section>
   </div>

   <aside className="pm34-publish-preview"><div className="pm34-preview-sticky"><span className="pm34-preview-label">VISTA PREVIA</span><div className="pm34-preview-photo" style={{backgroundImage:`url(${previewImage})`}}><div className="pm39-preview-type" data-type={draft.listing_type}>{typeLabel(draft.listing_type)}</div><span>{previewWhen}</span></div><div className="pm34-preview-body"><div className="pm34-preview-top"><span>{draft.category||'Categoría'}</span><b>{draft.compensation_text||'A acordar'}</b></div><h3>{draft.title||(offering?'Tu servicio va a verse así':'Tu solicitud va a verse así')}</h3><p>{draft.description||(offering?'Contá qué hacés para que puedan encontrarte y consultarte.':'Contá qué necesitás para que puedan ofrecerte una solución.')}</p><div className="pm34-preview-meta"><span>⌖ {draft.location_text||'Zona a definir'}</span><span>◷ {offering?(draft.availability_text||'Disponibilidad a coordinar'):(draft.duration_text||'Duración a coordinar')}</span><span>✉ Mensajes de Postulá Mejor</span>{draft.allow_phone_contact&&<span>☎ Teléfono habilitado</span>}</div></div></div><div className="pm34-preview-help"><b>Antes de publicar</b><span>✓ Tipo de publicación claro</span><span>✓ Servicio concreto</span><span>✓ Zona o modalidad</span><span>✓ Precio opcional</span><span>✓ Sin datos sensibles</span></div></aside></div>

   {notice&&<div className="pm34-form-notice">{notice}</div>}
   <footer className="pm34-publish-footer"><button type="button" className="pm34-secondary" onClick={()=>{setPublish(false);setAcceptRules(false)}}>Cancelar</button><div><small>{employmentWarning?'Esta publicación debe ir en Empleos.':acceptRules?'Todo listo para publicar.':'Aceptá las reglas para habilitar la publicación.'}</small><button className="pm34-primary" disabled={busy||!acceptRules||Boolean(employmentWarning)}>{busy?'Publicando…':offering?'Publicar mi servicio':'Publicar solicitud'}</button></div></footer>
  </form></div>}
 </>
}