'use client'

import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type ListingType='request'|'offer'
type MinePost={id:string;title:string;category?:string;description?:string;location_text?:string;compensation_text?:string;duration_text?:string;availability_text?:string;listing_type?:ListingType;scheduled_for?:string|null;status:string;created_at?:string}
type ConfirmAction={kind:'finish'|'remove';post:MinePost}|null
type EditFields={description:string;location_text:string;compensation_text:string;availability_text:string;duration_text:string}

function typeOf(post:MinePost):ListingType{return post.listing_type==='offer'?'offer':'request'}
function typeLabel(post:MinePost){return typeOf(post)==='offer'?'OFRECE SERVICIO':'NECESITA SERVICIO'}
function statusLabel(status:string){if(status==='published')return'Activa';if(status==='closed')return'Finalizada';if(status==='removed')return'Eliminada';if(status==='paused')return'Pausada';if(status==='review')return'En revisión';return'Borrador'}
function statusHelp(status:string){if(status==='published')return'Visible en Servicios Flex';if(status==='paused')return'Está guardada pero no se muestra públicamente';if(status==='closed')return'Ya no se muestra públicamente';if(status==='removed')return'Eliminada de la vista pública';return'No está visible públicamente'}
function dateLabel(value?:string){if(!value)return'';const d=new Date(value);return Number.isNaN(d.getTime())?'':d.toLocaleDateString('es-AR',{day:'2-digit',month:'short',year:'numeric'})}

export default function FlexManager({accountMode=false}:{accountMode?:boolean}){
 const[authReady,setAuthReady]=useState(false),[authenticated,setAuthenticated]=useState(false),[open,setOpen]=useState(false),[loading,setLoading]=useState(false),[busy,setBusy]=useState(false),[posts,setPosts]=useState<MinePost[]>([]),[notice,setNotice]=useState(''),[editId,setEditId]=useState(''),[editFields,setEditFields]=useState<EditFields>({description:'',location_text:'',compensation_text:'',availability_text:'',duration_text:''}),[confirm,setConfirm]=useState<ConfirmAction>(null),[filter,setFilter]=useState<'all'|ListingType>('all')

 const visible=useMemo(()=>posts.filter(p=>p.status!=='removed'),[posts])
 const filteredVisible=useMemo(()=>visible.filter(p=>filter==='all'||typeOf(p)===filter),[visible,filter])
 const activeCount=useMemo(()=>posts.filter(p=>p.status==='published').length,[posts])
 const requestCount=useMemo(()=>visible.filter(p=>typeOf(p)==='request').length,[visible])
 const offerCount=useMemo(()=>visible.filter(p=>typeOf(p)==='offer').length,[visible])

 async function token(){const{data}=await cvAuthClient().auth.getSession();return data.session?.access_token||''}
 async function load(){
  const t=await token();if(!t){setAuthenticated(false);return}
  setLoading(true);setNotice('')
  try{const r=await fetch('/api/postula/flex?mine=1',{headers:{Authorization:`Bearer ${t}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos cargar tus publicaciones.');setPosts(Array.isArray(d.posts)?d.posts:[])}catch(e){setNotice(e instanceof Error?e.message:'No pudimos cargar tus publicaciones.')}finally{setLoading(false)}
 }
 useEffect(()=>{let alive=true;(async()=>{const{data}=await cvAuthClient().auth.getSession();if(!alive)return;const ok=Boolean(data.session);setAuthenticated(ok);setAuthReady(true)})().catch(()=>{if(alive){setAuthenticated(false);setAuthReady(true)}});return()=>{alive=false}},[])
 useEffect(()=>{if(accountMode&&authenticated)void load()},[accountMode,authenticated])
 async function openManager(){setOpen(true);setEditId('');setConfirm(null);setFilter('all');await load()}
 async function action(kind:'edit_description'|'edit_offer'|'pause'|'reactivate'|'finish'|'remove',post:MinePost,payload:Record<string,unknown>={}){
  if(busy)return;const t=await token();if(!t){location.assign('/login?next=/mi-cuenta#publicaciones');return}
  setBusy(true);setNotice('')
  try{const r=await fetch('/api/postula/flex/manage',{method:'POST',headers:{Authorization:`Bearer ${t}`,'Content-Type':'application/json'},body:JSON.stringify({action:kind,post_id:post.id,...payload})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos actualizar la publicación.');setNotice(String(d.message||'Publicación actualizada.'));setEditId('');setConfirm(null);await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos actualizar la publicación.')}finally{setBusy(false)}
 }
 function startEdit(post:MinePost){setConfirm(null);setEditId(post.id);setEditFields({description:String(post.description||''),location_text:String(post.location_text||''),compensation_text:String(post.compensation_text||''),availability_text:String(post.availability_text||''),duration_text:String(post.duration_text||'')});setNotice('')}
 function saveEdit(e:FormEvent,post:MinePost){e.preventDefault();if(typeOf(post)==='offer')void action('edit_offer',post,editFields);else void action('edit_description',post,{description:editFields.description})}

 if(!authReady||!authenticated)return null
 return <>
  {accountMode?<div className="pm38-account-pubs"><div className="pm38-account-pubs-head"><div><span>MIS PUBLICACIONES</span><h2>Lo que necesitás y los servicios que ofrecés.</h2><p>Acá están tus publicaciones propias, separadas de Favoritos. Podés administrar solicitudes y también mantener activos tus servicios.</p></div><a href="/servicios-flex?clasificar=1">+ Publicar servicio</a></div>{loading?<div className="pm38-account-pubs-empty">Cargando publicaciones…</div>:visible.length?<div className="pm38-account-pubs-list">{visible.slice(0,4).map(post=><article key={post.id}><div><span data-status={post.status}>{statusLabel(post.status)}</span><small>{dateLabel(post.created_at)}</small></div><span className="pm39-manager-type" data-type={typeOf(post)}>{typeLabel(post)}</span><h3>{post.title}</h3><p>{post.category||'Servicio Flex'} · {post.location_text||'Zona a coordinar'}</p></article>)}</div>:<div className="pm38-account-pubs-empty"><b>Todavía no publicaste ningún Servicio Flex.</b><span>Podés publicar que necesitás algo o mostrar un servicio que ofrecés.</span></div>}<div className="pm38-account-pubs-actions"><button type="button" onClick={()=>void openManager()}>Administrar mis publicaciones</button><a href="/servicios-flex#explorar">Ver Servicios Flex</a></div></div>:<div className="pm37-launch"><div><span>TUS SERVICIOS FLEX</span><b>Administrá solicitudes y servicios</b><small>{requestCount||offerCount?`${requestCount} buscando servicio · ${offerCount} ofreciendo servicio`:'Esta opción aparece únicamente cuando iniciás sesión.'}</small></div><button type="button" onClick={()=>void openManager()}>Mis publicaciones</button></div>}

  {open&&<div className="pm37-overlay" role="dialog" aria-modal="true" aria-labelledby="pm37-title"><section className="pm37-card">
   <header><div><span>GESTIÓN DE SERVICIOS FLEX</span><h2 id="pm37-title">Mis publicaciones</h2><p>{activeCount?`${activeCount} ${activeCount===1?'publicación activa':'publicaciones activas'}`:'No tenés publicaciones activas'} · los créditos consumidos no vuelven al finalizar o eliminar.</p></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar">×</button></header>
   <div className="pm39-manager-tabs"><button type="button" data-on={filter==='all'} onClick={()=>setFilter('all')}>Todas · {visible.length}</button><button type="button" data-on={filter==='request'} onClick={()=>setFilter('request')}>Necesito un servicio · {requestCount}</button><button type="button" data-on={filter==='offer'} onClick={()=>setFilter('offer')}>Servicios que ofrezco · {offerCount}</button></div>
   {notice&&<div className="pm37-notice">{notice}</div>}
   {loading?<div className="pm37-empty"><b>Cargando publicaciones…</b></div>:filteredVisible.length===0?<div className="pm37-empty"><b>No hay publicaciones en esta categoría.</b><p>Podés crear una nueva desde Servicios Flex.</p></div>:<div className="pm37-list">{filteredVisible.map(post=><article key={post.id} data-status={post.status}>
    <div className="pm37-post-main"><div className="pm37-post-top"><div><span className="pm39-manager-type" data-type={typeOf(post)}>{typeLabel(post)}</span><span className="pm37-status">{statusLabel(post.status)}</span></div><small>{dateLabel(post.created_at)}</small></div><h3>{post.title}</h3><p>{post.description||'Sin descripción'}</p><div className="pm37-meta"><span>{post.category||'Sin categoría'}</span><span>{post.location_text||'Zona a coordinar'}</span>{post.compensation_text&&<span>{post.compensation_text}</span>}{typeOf(post)==='offer'&&post.availability_text&&<span>{post.availability_text}</span>}</div><small className="pm37-status-help">{statusHelp(post.status)}</small></div>
    {editId===post.id?<form className={typeOf(post)==='offer'?'pm37-edit pm39-offer-edit':'pm37-edit'} onSubmit={e=>saveEdit(e,post)}>{typeOf(post)==='offer'?<><div className="pm39-edit-grid"><label className="full"><b>Descripción</b><textarea value={editFields.description} onChange={e=>setEditFields(v=>({...v,description:e.target.value}))} minLength={15} maxLength={1800} required/></label><label><b>Zona o modalidad</b><input value={editFields.location_text} onChange={e=>setEditFields(v=>({...v,location_text:e.target.value}))} required/></label><label><b>Precio orientativo</b><input value={editFields.compensation_text} onChange={e=>setEditFields(v=>({...v,compensation_text:e.target.value}))} placeholder="Ej. Desde $35.000"/></label><label><b>Disponibilidad</b><input value={editFields.availability_text} onChange={e=>setEditFields(v=>({...v,availability_text:e.target.value}))} placeholder="Ej. Lun a sáb"/></label><label><b>Duración típica</b><input value={editFields.duration_text} onChange={e=>setEditFields(v=>({...v,duration_text:e.target.value}))} placeholder="Ej. 1 a 3 horas"/></label></div><span>El título, la categoría y el tipo de publicación quedan bloqueados para que una publicación no se reutilice para otro servicio.</span></>:<label><b>Editar descripción</b><span>Por seguridad, título, categoría, zona, fecha e importe quedan bloqueados.</span><textarea value={editFields.description} onChange={e=>setEditFields(v=>({...v,description:e.target.value}))} minLength={15} maxLength={1800} required/></label>}<div><button type="button" className="secondary" onClick={()=>setEditId('')}>Cancelar</button><button disabled={busy||editFields.description.trim().length<15}>{busy?'Guardando…':'Guardar cambios'}</button></div></form>:<div className="pm37-actions pm39-status-actions">{post.status==='published'&&<><button type="button" className="secondary" onClick={()=>startEdit(post)}>{typeOf(post)==='offer'?'Editar servicio':'Editar descripción'}</button>{typeOf(post)==='offer'&&<button type="button" className="pause" onClick={()=>void action('pause',post)}>Pausar</button>}<button type="button" className="finish" onClick={()=>setConfirm({kind:'finish',post})}>Finalizar</button><button type="button" className="danger" onClick={()=>setConfirm({kind:'remove',post})}>Eliminar</button></>}{post.status==='paused'&&typeOf(post)==='offer'&&<><button type="button" className="secondary" onClick={()=>startEdit(post)}>Editar servicio</button><button type="button" className="reactivate" onClick={()=>void action('reactivate',post)}>Reactivar</button><button type="button" className="finish" onClick={()=>setConfirm({kind:'finish',post})}>Finalizar</button><button type="button" className="danger" onClick={()=>setConfirm({kind:'remove',post})}>Eliminar</button></>}{post.status==='closed'&&<button type="button" className="danger ghost" onClick={()=>setConfirm({kind:'remove',post})}>Eliminar del listado</button>}</div>}
   </article>)}</div>}
   <footer><span>Las ofertas pueden pausarse y reactivarse sin consumir otro crédito. Finalizar o eliminar no devuelve el crédito original.</span><button type="button" onClick={()=>setOpen(false)}>Cerrar</button></footer>
  </section></div>}

  {confirm&&<div className="pm37-confirm-overlay" role="dialog" aria-modal="true"><section className="pm37-confirm"><span>{confirm.kind==='finish'?'FINALIZAR PUBLICACIÓN':'ELIMINAR PUBLICACIÓN'}</span><h3>{confirm.post.title}</h3><p>{confirm.kind==='finish'?'La publicación dejará de mostrarse en Servicios Flex y quedará marcada como finalizada.':'La publicación se ocultará de Servicios Flex y también de tu listado de gestión.'}</p><div className="pm37-credit-warning"><b>El crédito Flex no se reintegra.</b><small>El crédito ya fue consumido al publicar y no vuelve aunque finalices o elimines. Si sólo querés ocultar un servicio que ofrecés, usá Pausar.</small></div><div><button type="button" className="secondary" onClick={()=>setConfirm(null)}>Volver</button><button type="button" className={confirm.kind==='remove'?'danger':'finish'} disabled={busy} onClick={()=>void action(confirm.kind,confirm.post)}>{busy?'Procesando…':confirm.kind==='finish'?'Sí, finalizar':'Sí, eliminar'}</button></div></section></div>}
 </>
}