'use client'
import {useEffect,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type Wallet={scope_key:string;company_id?:string|null;label:string;total:number;free_remaining:number;bonus_remaining:number;period_allowance:number;period_used:number;purchased_remaining:number;plan?:string}
type Pack={code:string;credits:number;amount:number;label:string}
async function authHeader(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
export default function FlexCredits({companyId,onCompanyChange,refreshKey=0}:{companyId:string|null;onCompanyChange:(id:string|null)=>void;refreshKey?:number}){
 const [personal,setPersonal]=useState<Wallet|null>(null),[companies,setCompanies]=useState<Wallet[]>([]),[packs,setPacks]=useState<Pack[]>([]),[busy,setBusy]=useState(''),[notice,setNotice]=useState('')
 async function load(){const h=await authHeader();if(!('Authorization' in h))return;const r=await fetch('/api/postula/flex/credits',{headers:h,cache:'no-store'});const d=await r.json().catch(()=>({}));if(r.ok&&d?.ok){setPersonal(d.personal);setCompanies(d.companies||[]);setPacks(d.packs||[]);if(companyId&&!d.companies?.some((x:Wallet)=>x.company_id===companyId))onCompanyChange(null)}}
 useEffect(()=>{void load()},[refreshKey])
 const selected=companyId?companies.find(x=>x.company_id===companyId)||personal:personal
 async function buy(pack:Pack){setBusy(pack.code);setNotice('');try{const h=await authHeader();const r=await fetch('/api/postula/flex/credits/checkout',{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify({pack:pack.code,company_id:companyId})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos abrir Mercado Pago.');location.assign(d.init_point)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos abrir Mercado Pago.');setBusy('')}}
 return <div className="pm21-flex-credits"><div className="pm21-flex-credit-head"><div><span>CRÉDITOS DE PUBLICACIÓN</span><b>{selected?`${selected.total} ${selected.total===1?'crédito disponible':'créditos disponibles'}`:'Consultando saldo…'}</b><small>Tu primera publicación personal es gratis. Los planes y packs pueden sumar más créditos.</small></div>{companies.length>0&&<label>Publicar como<select value={companyId||''} onChange={e=>onCompanyChange(e.target.value||null)}><option value="">Mi cuenta personal</option>{companies.map(c=><option key={c.scope_key} value={c.company_id||''}>{c.label} · {c.total} créditos</option>)}</select></label>}</div>{selected&&<div className="pm21-flex-credit-breakdown"><span>Gratis <b>{selected.free_remaining||0}</b></span><span>Beneficios <b>{selected.bonus_remaining||0}</b></span><span>Plan <b>{Math.max(0,(selected.period_allowance||0)-(selected.period_used||0))}</b></span><span>Comprados <b>{selected.purchased_remaining||0}</b></span></div>}{selected&&selected.total<=0&&<div className="pm21-flex-packs"><div><b>Necesitás otro crédito</b><span>Comprá publicaciones sueltas. No necesitás contratar un plan mensual.</span></div><div>{packs.map(p=><button type="button" key={p.code} disabled={Boolean(busy)} onClick={()=>void buy(p)}><b>{p.label}</b><span>${p.amount.toLocaleString('es-AR')}</span><small>{p.credits>1?`$${Math.round(p.amount/p.credits).toLocaleString('es-AR')} c/u`:'pago único'}</small></button>)}</div></div>}{notice&&<p className="pm21-flex-credit-notice">{notice}</p>}</div>
}
