import styles from '../postula-preview/platform.module.css'
import {PlatformFooter,PlatformHeader,MobileNav} from '../postula-preview/PlatformChrome'
import {gigCategories,previewGigs} from '../postula-preview/gigs'
import ChangasExplorer from './ChangasExplorer'
import '../postula-preview/premium-v6.css'
import '../postula-preview/premium-v7.css'
import './flex-credits-v21.css'
import './flex-polish-v27.css'
import './flex-media-v33.css'
import './flex-publish-v34.css'

export const metadata={title:{absolute:'Trabajos Flex | Postulá Mejor'},description:'Tareas puntuales, trabajos por hora y servicios concretos cerca tuyo, con contexto y chat desde PC o móvil antes de acordar.',robots:{index:true,follow:true},alternates:{canonical:'https://postulamejor.com/trabajos-flex'}}

const workerProfiles=[
 {name:'Perfil creativo',role:'Foto · redes · eventos',signal:'Señales de confianza visibles',jobs:'Vista ilustrativa',image:'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Perfil operativo',role:'Mudanzas · armado · logística',signal:'Historial cuando exista',jobs:'Vista ilustrativa',image:'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Perfil de cuidado',role:'Mascotas · paseos · cuidado',signal:'Identidad y contexto',jobs:'Vista ilustrativa',image:'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Perfil digital',role:'Excel · soporte · tecnología',signal:'Experiencia explicable',jobs:'Vista ilustrativa',image:'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=500'},
]

export default function TrabajosFlexPage(){return <main className={`${styles.page} pm7-page pm7-candidate`}>
 <PlatformHeader/>
 <section className="pm7-gigs-hero"><div className="pm7-gigs-hero-inner"><div><span className="pm7-eyebrow lime">NUEVO · TRABAJOS FLEX</span><h1>¿Tenés unas horas?<br/><em>Hacé algo. Ganá algo.</em></h1><p>Una sección para tareas puntuales, trabajos por hora y necesidades concretas cerca tuyo. Más simple que una búsqueda formal, pero con contexto, identidad y reglas claras.</p><div className="pm7-hero-actions"><a href="#explorar" className="pm7-btn-black">Ver Trabajos Flex</a><a href="/trabajos-flex?publicar=1" className="pm7-btn-white">Publicar una tarea</a></div><span className="pm-flex-device-note">Mensajes disponibles en PC y móvil</span></div><div className="pm7-gigs-stack"><article className="one"><span>HOY · PALERMO</span><h3>Armar dos muebles</h3><b>$38.000</b><small>3–4 horas</small></article><article className="two"><span>SÁBADO · CABALLITO</span><h3>Fotos + 4 reels</h3><b>$52.000</b><small>2 horas</small></article><article className="three"><span>FLEXIBLE · REMOTO</span><h3>Ordenar un Excel</h3><b>$44.000</b><small>2–3 horas</small></article><div className="pm7-gig-orbit"><i/><i/><i/></div></div></div></section>
 <section className="pm7-trust-strip"><div><b>Identidades verificables</b><span>sabés con quién hablás</span></div><div><b>Chat en PC y móvil</b><span>acordá tarea, horario y pago desde donde estés</span></div><div><b>Señales generales</b><span>sin listas negras ni puntajes secretos</span></div><div><b>Vos decidís</b><span>la plataforma no fuerza acuerdos</span></div></section>
 <section className="pm7-gig-explorer" id="explorar"><div className="pm7-section-head"><div><span className="pm7-eyebrow coral">CERCA TUYO</span><h2>Trabajos Flex con contexto, no avisos crípticos.</h2></div><p>Las publicaciones reales aparecen primero. Si todavía no hay tareas activas, te mostramos ejemplos claramente identificados para que veas cómo funciona la experiencia.</p></div><ChangasExplorer gigs={previewGigs} categories={gigCategories}/></section>
 <section className="pm7-people"><div className="pm7-section-head"><div><h2>Qué señales vas a poder mirar antes de acordar.</h2></div><p>Estos perfiles son ejemplos de interfaz, no personas ni reputaciones reales. Cuando exista historial verificable, se mostrará con su contexto y sin puntajes secretos.</p></div><div className="pm7-worker-row">{workerProfiles.map(p=><article key={p.name}><div className="pm7-worker-photo" style={{backgroundImage:`url(${p.image})`}}/><h3>{p.name}</h3><p>{p.role}</p><b>{p.signal}</b><small>{p.jobs}</small></article>)}</div></section>
 <section className="pm7-gig-safety pm15-safety"><div className="pm7-gig-safety-inner"><div className="pm15-safety-head"><span>CONFIANZA ANTES DE ACORDAR</span><h2>Rápido, claro y con reglas visibles.</h2><p>Antes de contactar, cada persona tiene que poder entender qué se ofrece, con quién habla y qué puede preguntar o reportar. El chat funciona desde la computadora y desde el celular con la interfaz adaptada a cada dispositivo.</p></div><div className="pm7-safety-grid"><article className="pay"><b>Pago claro</b><p>El importe y la unidad —por hora, tarea o jornada— quedan visibles antes de contactar.</p></article><article className="identity"><b>Identidad y contexto</b><p>Mostramos señales verificables e historial cuando exista, siempre con contexto y posibilidad de reportar abuso.</p></article><article className="fair"><b>Sin reputación oscura</b><p>Una recomendación general no puede convertirse en descarte automático, lista negra ni puntaje secreto.</p></article><article className="chat"><b>Chat primero</b><p>Podés preguntar, confirmar tarea, horario y pago, o retirarte antes de aceptar cualquier acuerdo.</p></article></div><p className="pm15-safety-note"><b>Flex describe la experiencia, no define la relación jurídica.</b> Está pensado para tareas puntuales o servicios independientes. Si por la forma real de trabajo existe dependencia, continuidad o un régimen especial —por ejemplo determinadas tareas de cuidado o trabajo en casas particulares— corresponde cumplir la registración y las obligaciones que resulten aplicables.</p></div></section>
 <PlatformFooter/><MobileNav active="changas"/>
 </main>}
