import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'

const URL='https://pejkycdttogpmmdntzuq.supabase.co'
const KEY='sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I'
const clean=(v:unknown,n=4000)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n)
function userDb(req:NextRequest){const auth=req.headers.get('authorization')||'';return createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
function adminDb(){const key=process.env.SUPABASE_SERVICE_ROLE_KEY;return key?createClient(URL,key,{auth:{persistSession:false,autoRefreshToken:false}}):null}
async function context(req:NextRequest){const udb=userDb(req),{data:{user}}=await udb.auth.getUser();if(!user)return null;const db=adminDb();if(!db)return null;const {data:adm}=await db.from('pm_support_admins').select('role,active').eq('user_id',user.id).maybeSingle();if(!adm?.active)return null;return {db,user,role:adm.role as string}}
async function recipient(db:any,userId:string){const r=await db.auth.admin.getUserById(userId);return r?.data?.user?.email||null}
async function sendMail(to:string,subject:string,text:string){const key=process.env.RESEND_API_KEY;if(!key||!to)return;await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({from:'Postulá Mejor <hola@postulamejor.com>',to:[to],subject,text,reply_to:'hola@postulamejor.com'})}).catch(()=>{})}

export async function GET(req:NextRequest){const ctx=await context(req);if(!ctx)return NextResponse.json({ok:false,error:'Acceso reservado a soporte.'},{status:403});const {db}=ctx;const ticketId=req.nextUrl.searchParams.get('ticket')||'';if(ticketId){const {data:ticket,error}=await db.from('pm_support_tickets').select('*').eq('id',ticketId).maybeSingle();if(error||!ticket)return NextResponse.json({ok:false,error:'Caso no disponible.'},{status:404});const [{data:messages},{data:company}]=await Promise.all([db.from('pm_support_messages').select('id,sender_kind,body,created_at').eq('ticket_id',ticketId).order('created_at',{ascending:true}).limit(300),ticket.company_id?db.from('pm_companies').select('id,name').eq('id',ticket.company_id).maybeSingle():Promise.resolve({data:null})]);const email=await recipient(db,ticket.user_id);await db.from('pm_support_alerts').update({seen_at:new Date().toISOString()}).eq('ticket_id',ticketId).is('seen_at',null);return NextResponse.json({ok:true,ticket:{...ticket,pm_companies:company},messages:messages||[],requester:{email}})}
 const {data:tickets,error}=await db.from('pm_support_tickets').select('id,user_id,company_id,audience,category,priority,subject,status,page_path,created_at,last_message_at').order('priority',{ascending:true}).order('last_message_at',{ascending:false}).limit(250);if(error)return NextResponse.json({ok:false,error:error.message},{status:400});const companyIds=[...new Set((tickets||[]).map((t:any)=>t.company_id).filter(Boolean))];const {data:companies}=companyIds.length?await db.from('pm_companies').select('id,name').in('id',companyIds):{data:[]};const map=new Map((companies||[]).map((x:any)=>[x.id,x]));const {count}=await db.from('pm_support_alerts').select('id',{count:'exact',head:true}).is('seen_at',null);return NextResponse.json({ok:true,tickets:(tickets||[]).map((t:any)=>({...t,pm_companies:t.company_id?map.get(t.company_id)||null:null})),unseen_alerts:count||0})}

export async function POST(req:NextRequest){const ctx=await context(req);if(!ctx)return NextResponse.json({ok:false,error:'Acceso reservado a soporte.'},{status:403});const {db,user}=ctx;const body=await req.json().catch(()=>({})),ticketId=clean(body?.ticket_id,80),action=clean(body?.action,30);if(!ticketId)return NextResponse.json({ok:false,error:'Falta el caso.'},{status:400});const {data:ticket}=await db.from('pm_support_tickets').select('*').eq('id',ticketId).maybeSingle();if(!ticket)return NextResponse.json({ok:false,error:'Caso no disponible.'},{status:404});if(action==='reply'){const message=clean(body?.message,5000);if(message.length<2)return NextResponse.json({ok:false,error:'Escribí una respuesta.'},{status:400});const {data:msg,error}=await db.from('pm_support_messages').insert({ticket_id:ticketId,sender_user_id:user.id,sender_kind:'support',body:message}).select('id,sender_kind,body,created_at').single();if(error)return NextResponse.json({ok:false,error:error.message},{status:400});await db.from('pm_support_tickets').update({status:'waiting_user',last_message_at:new Date().toISOString()}).eq('id',ticketId);const email=await recipient(db,ticket.user_id);if(email)await sendMail(email,`Respuesta de soporte | Postulá Mejor`, `Respondimos tu consulta: ${ticket.subject}\n\n${message}\n\nPodés continuar la conversación desde tu cuenta de Postulá Mejor.`);return NextResponse.json({ok:true,message:msg})}
 if(action==='status'){const status=clean(body?.status,30);if(!['open','waiting_user','waiting_support','resolved','closed'].includes(status))return NextResponse.json({ok:false,error:'Estado inválido.'},{status:400});await db.from('pm_support_tickets').update({status}).eq('id',ticketId);return NextResponse.json({ok:true})}
 if(action==='priority'){const priority=Number(body?.priority);if(![1,2,3,4].includes(priority))return NextResponse.json({ok:false,error:'Prioridad inválida.'},{status:400});await db.from('pm_support_tickets').update({priority}).eq('id',ticketId);return NextResponse.json({ok:true})}
 return NextResponse.json({ok:false,error:'Acción inválida.'},{status:400})}
