'use client'

import { useEffect,useState } from 'react'
import type { TenantSession } from '@/lib/comercio/types'
import styles from './arca-setup.module.css'

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
type SetupStatus={configured:boolean;tax_id?:string|null;environment?:'homologacion'|'produccion';point_of_sale?:number|null;receipt_type?:number;credential_slot?:string|null;csr_pem?:string|null;private_key_ready?:boolean;certificate_ready?:boolean;certificate_subject?:string|null;certificate_expires_at?:string|null}
function onlyDigits(v:string){return v.replace(/\D/g,'').slice(0,11)}
async function readText(file:File){return await file.text()}

export default function ArcaSetupPanel({session,companyName,companyTaxId,message}:{session:TenantSession;companyName:string;companyTaxId?:string|null;message:(m:string)=>void}){
  const[status,setStatus]=useState<SetupStatus|null>(null),[taxId,setTaxId]=useState(onlyDigits(companyTaxId||'')),[point,setPoint]=useState(''),[environment,setEnvironment]=useState<'produccion'|'homologacion'>('produccion'),[csr,setCsr]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[connectionOk,setConnectionOk]=useState(false),[advanced,setAdvanced]=useState(false),[guideOpen,setGuideOpen]=useState(false)
  async function setup(body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-setup`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.error||'No se pudo configurar ARCA.');return d}
  async function load(){setError('');try{const s=await setup({action:'status'}) as SetupStatus&{ok:boolean};setStatus(s);if(s.tax_id)setTaxId(onlyDigits(s.tax_id));if(s.point_of_sale)setPoint(String(s.point_of_sale));if(s.environment)setEnvironment(s.environment);if(s.csr_pem)setCsr(s.csr_pem)}catch(e){setError(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{void load()},[session.companyId,session.token])
  useEffect(()=>{if(!guideOpen)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setGuideOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[guideOpen])
  async function generate(){if(taxId.length!==11){setError('El CUIT/CUIL debe tener exactamente 11 dígitos.');return}setBusy('csr');setError('');setConnectionOk(false);try{const d=await setup({action:'generate_csr',tax_id:taxId,organization:companyName});setCsr(String(d.csr_pem||''));message('CSR generado. La clave privada quedó guardada cifrada; no se descarga ni se muestra.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  function downloadCsr(){if(!csr)return;const blob=new Blob([csr],{type:'application/pkcs10'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`comercio-lleno-${taxId||'arca'}.csr`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function uploadCertificate(file:File|null){if(!file)return;setBusy('cert');setError('');setConnectionOk(false);try{const pem=await readText(file);await setup({action:'upload_certificate',tax_id:taxId,certificate_pem:pem});message('Certificado ARCA validado y guardado cifrado.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function uploadPair(cert:File|null,key:File|null){if(!cert||!key){setError('Seleccioná el certificado .crt/.pem y la clave privada .key/.pem.');return}setBusy('pair');setError('');setConnectionOk(false);try{await setup({action:'upload_pair',tax_id:taxId,certificate_pem:await readText(cert),private_key_pem:await readText(key)});message('Par de certificado y clave validado y guardado cifrado.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function verifyConnection(){const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-test`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'status'}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'La configuración se guardó, pero ARCA todavía no respondió correctamente. Revisá el certificado, el punto de venta y la autorización del Web Service.');return d}
  function completeOnboardingIfNeeded(){if(typeof window==='undefined')return false;const activeKey=`cl_onboarding_active_step_${session.companyId}`;const cameFromOnboarding=sessionStorage.getItem(activeKey)==='arca';if(!cameFromOnboarding)return false;let progress:Record<string,boolean>={};try{progress=JSON.parse(localStorage.getItem(`cl_setup_steps_${session.companyId}`)||'{}')}catch{}progress.arca=true;localStorage.setItem(`cl_setup_steps_${session.companyId}`,JSON.stringify(progress));localStorage.removeItem(`cl_setup_minimized_${session.companyId}`);sessionStorage.setItem(`cl_resume_onboarding_${session.companyId}`,'1');sessionStorage.removeItem(activeKey);return true}
  async function configure(){if(taxId.length!==11){setError('El CUIT/CUIL debe tener 11 dígitos.');return}if(!/^\d+$/.test(point)||Number(point)<=0){setError('Ingresá el punto de venta para Web Services.');return}setBusy('configure');setError('');setConnectionOk(false);try{await setup({action:'configure',tax_id:taxId,point_of_sale:Number(point),environment});await verifyConnection();setConnectionOk(true);message('ARCA conectado correctamente.');completeOnboardingIfNeeded();window.setTimeout(()=>window.location.reload(),1100)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  function openHumanSupport(){window.dispatchEvent(new CustomEvent('comercio:open-human-support',{detail:{topic:'arca'}}));message('Abrimos la ayuda humana para configurar ARCA.')}
  const pilot=status?.credential_slot==='pilot_default'
  return <section className={styles.panel}>
    <div className={styles.head}><div><span>FACTURACIÓN ELECTRÓNICA</span><h3>Conectar ARCA</h3><p>Asistente guiado. Comercio Lleno genera el CSR y guarda la clave privada cifrada. Vos hacés la autorización en ARCA y subís el certificado que devuelve.</p></div><div className={`${styles.state} ${status?.configured||pilot?styles.ready:''}`}>{status?.configured||pilot?'✓ Configurado':'Configuración pendiente'}</div></div>
    {pilot&&<div className={styles.pilot}>La Económica conserva su configuración piloto actual. No necesitás migrarla para seguir facturando. El nuevo asistente se usa para conectar otros comercios con credenciales propias.</div>}
    <div className={styles.helpBanner}><div><b>¿Preferís que te ayudemos con ARCA?</b><span>La configuración de certificados puede ser un poco técnica. Si no querés hacerla solo, pedí asistencia y te ayudamos desde Central Llena.</span></div><button type="button" onClick={openHumanSupport}>Solicitar asistencia técnica</button></div>
    {error&&<div className={styles.error}>{error}</div>}
    <div className={styles.steps}>
      <article className={styles.step}><i>1</i><div><h4>CUIT y CSR</h4><p>Ingresá el CUIT/CUIL de 11 dígitos y tocá <b>Generar CSR</b>. Cuando aparezca el código largo, descargá el archivo <b>.csr</b>.</p><label>CUIT / CUIL<input inputMode="numeric" value={taxId} onChange={e=>setTaxId(onlyDigits(e.target.value))} placeholder="20123456789"/><small>{taxId.length}/11 dígitos</small></label><button type="button" disabled={busy!==''} onClick={()=>void generate()}>{busy==='csr'?'Generando…':csr?'Regenerar CSR':'Generar CSR'}</button>{csr&&<div className={styles.csr}><textarea readOnly value={csr}/><div><button type="button" onClick={downloadCsr}>↓ Descargar .csr</button></div></div>}<div className={styles.security}>🔒 La clave privada no se entrega al navegador: queda cifrada en Supabase Vault.</div></div></article>
      <article className={`${styles.step} ${styles.procedure}`}><i>2</i><div><h4>Hacer el trámite en ARCA</h4><p>Entrá al portal de ARCA con CUIT y Clave Fiscal. Este paso crea el certificado, autoriza Facturación Electrónica y prepara el punto de venta Web Services.</p><div className={styles.guideActions}><button type="button" className={styles.guideButton} onClick={()=>setGuideOpen(true)}>▣ Instructivo para habilitar facturación</button><a href="https://www.arca.gob.ar/" target="_blank" rel="noreferrer">Abrir ARCA ↗</a></div><small className={styles.officialNote}>El instructivo usa los nombres actuales del portal. Los datos fiscales del ejemplo se muestran ocultos por seguridad.</small></div></article>
      <article className={styles.step}><i>3</i><div><h4>Subir el certificado</h4><p>Volvé a Comercio Lleno y adjuntá el certificado que descargaste desde ARCA. Verificamos que corresponda a la clave privada del CSR antes de guardarlo.</p><label className={styles.file}>{status?.certificate_ready?'✓ Certificado cargado':'Seleccionar .crt / .cer / .pem'}<input type="file" accept=".crt,.cer,.pem,application/x-x509-ca-cert" disabled={busy!==''} onChange={e=>void uploadCertificate(e.target.files?.[0]||null)}/></label>{status?.certificate_subject&&<small className={styles.certInfo}>{status.certificate_subject}<br/>Vence: {status.certificate_expires_at?new Date(status.certificate_expires_at).toLocaleDateString('es-AR'):'—'}</small>}<button type="button" className={styles.advancedLink} onClick={()=>setAdvanced(v=>!v)}>{advanced?'Ocultar carga avanzada':'Ya tengo certificado + clave privada'}</button>{advanced&&<PairUpload busy={busy!==''} send={uploadPair}/>}</div></article>
      <article className={styles.step}><i>4</i><div><h4>Conectar y finalizar</h4><p>En <b>Entorno</b> elegí Producción. En <b>Punto de venta</b> escribí el número que creaste en ARCA, pero sin ceros adelante: por ejemplo, si ARCA muestra 0003, acá poné 3.</p><div className={styles.two}><label>Entorno<select value={environment} onChange={e=>setEnvironment(e.target.value as 'produccion'|'homologacion')}><option value="produccion">Producción</option><option value="homologacion">Homologación / pruebas</option></select></label><label>Punto de venta<input inputMode="numeric" value={point} onChange={e=>setPoint(e.target.value.replace(/\D/g,''))} placeholder="Ej: 3"/></label></div><div className={styles.note}>Por ahora este asistente habilita la emisión actual de Comercio Lleno como <b>Factura C</b>. No habilitamos A/B hasta incorporar el tratamiento fiscal e IVA correspondiente.</div><div className={styles.finish}><button type="button" className={styles.primary} disabled={busy!==''||(!status?.certificate_ready&&!pilot)} onClick={()=>void configure()}>{busy==='configure'?'Conectando…':'Guardar y conectar ARCA'}</button>{connectionOk&&<span className={styles.connectSuccess}>✓ Conexión exitosa</span>}</div><small className={styles.reloadNote}>Cuando la conexión sea correcta, Comercio Lleno recarga la página automáticamente para actualizar el estado de ARCA.</small></div></article>
    </div>
    {guideOpen&&<VisualArcaGuide hasCsr={Boolean(csr)} close={()=>setGuideOpen(false)} support={openHumanSupport}/>} 
  </section>
}

function VisualArcaGuide({hasCsr,close,support}:{hasCsr:boolean;close:()=>void;support:()=>void}){return <div className={styles.guideOverlay} role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className={styles.guideModal} role="dialog" aria-modal="true" aria-labelledby="arca-guide-title"><header><div><span>INSTRUCTIVO · ARCA</span><h3 id="arca-guide-title">Cómo habilitar la facturación electrónica</h3><p>Seguí el orden de abajo. Los datos del contribuyente del ejemplo están ocultos; usá siempre los datos reales de tu comercio.</p></div><button type="button" onClick={close} aria-label="Cerrar instructivo">×</button></header>{!hasCsr&&<div className={styles.guideWarning}>Antes de empezar, cerrá este instructivo, completá el paso 1 y tocá <b>Generar CSR</b> → <b>Descargar .csr</b>.</div>}<div className={styles.guideList}>
      <GuideCard n="1" title="Descargá el CSR desde Comercio Lleno" caption="En Configuración → ARCA, completá el CUIT, tocá Generar CSR y después Descargar .csr. El archivo queda en la carpeta Descargas de tu computadora." screen={<><div className={styles.mockTop}>Comercio Lleno · Configuración · ARCA</div><div className={styles.mockField}>CUIT / CUIL: •••••••••••</div><div className={styles.mockArea}>-----BEGIN CERTIFICATE REQUEST-----<br/>… CSR generado automáticamente …</div><div className={styles.mockHit}>↓ Descargar .csr</div></>}/>
      <GuideCard n="2" title="Creá el certificado digital" caption="Abrí ARCA e iniciá sesión. En “Buscá trámites y servicios” escribí Administración de Certificados Digitales. Entrá, tocá Agregar Alias, inventá un alias para tu negocio y en Seleccionar archivo elegí el .csr descargado. Guardá el trámite." screen={<><div className={styles.mockTop}>ARCA · Administración de Certificados Digitales</div><div className={styles.mockSearch}>Alias: NOMBRE-DE-TU-NEGOCIO</div><div className={styles.mockField}>Archivo: comercio-lleno-•••••••••••.csr</div><div className={styles.mockHit}>Agregar alias</div></>}/>
      <GuideCard n="3" title="Descargá el certificado que devuelve ARCA" caption="Cuando finalice el trámite, salí al portal de Clave Fiscal y volvé a entrar a Certificados Digitales. En el listado, tocá Ver sobre el alias creado y después el ícono/botón de Descargar. Guardá ese certificado: lo vas a subir luego en Comercio Lleno." screen={<><div className={styles.mockTop}>Certificados</div><div className={styles.mockField}>Alias: datos ocultos · Ver</div><div className={styles.mockField}>Estado: VÁLIDO</div><div className={styles.mockHit}>Descargar certificado ↓</div></>}/>
      <GuideCard n="4" title="Autorizá Facturación Electrónica" caption="Volvé al portal principal y abrí Administrador de Relaciones de Clave Fiscal → Nueva Relación → Buscar. Elegí ARCA → WebServices → Facturación Electrónica. En Representante tocá Buscar, elegí como Computador Fiscal el alias que creaste y tocá Confirmar. Luego confirmá nuevamente la relación." screen={<><div className={styles.mockTop}>Administrador de Relaciones</div><div className={styles.mockField}>Servicio: Facturación Electrónica</div><div className={styles.mockField}>Computador Fiscal: TU ALIAS</div><div className={styles.mockHit}>Confirmar ✓</div></>}/>
      <GuideCard n="5" title="Creá un punto de venta Web Services" caption="En el portal buscá Administración de puntos de venta y domicilios. Seleccioná tu nombre o empresa → Puntos de venta / Emisión → Agregar. Usá el número siguiente al último registrado: si tenés 1 y 2, creá 0003. Nombre de fantasía: tu local. Dominio asociado: dejalo en blanco." screen={<><div className={styles.mockTop}>A/B/M de Puntos de venta / emisión</div><div className={styles.mockField}>Número: 0003</div><div className={styles.mockField}>Nombre de fantasía: TU LOCAL</div><div className={styles.mockHit}>Agregar</div></>}/>
      <GuideCard n="6" title="Elegí el sistema correcto y terminá" caption="En Sistema seleccioná “Factura Electrónica - Monotributo - Web Services”. Elegí el domicilio fiscal y una actividad que represente al comercio. Aceptá y confirmá. Después volvé a Comercio Lleno: paso 3, subí el certificado; paso 4, Producción y el punto de venta sin ceros (0003 → 3). Tocá Guardar y conectar ARCA." screen={<><div className={styles.mockTop}>Nuevo punto de venta</div><div className={styles.mockField}>Sistema: Factura Electrónica · Monotributo · Web Services</div><div className={styles.mockField}>Domicilio: domicilio fiscal</div><div className={styles.mockHit}>Aceptar y confirmar ✓</div></>}/>
    </div><div className={styles.guidePrivacy}>🔒 En el instructivo nunca mostramos CUIT, razón social, alias reales ni otros datos fiscales de clientes.</div><footer><div><b>¿Se te complica en algún paso?</b><span>Podés pedir asistencia técnica y te ayudamos con la carga de certificados.</span></div><div className={styles.guideLinks}><a href="https://www.arca.gob.ar/" target="_blank" rel="noreferrer">Abrir ARCA ↗</a></div><div className={styles.footerButtons}><button type="button" className={styles.supportDanger} onClick={()=>{close();support()}}>Solicitar ayuda humana</button><button type="button" onClick={close}>Volver a la configuración</button></div></footer></section></div>}
function GuideCard({n,title,caption,screen}:{n:string;title:string;caption:string;screen:React.ReactNode}){return <article className={styles.guideCard}><div className={styles.guideNumber}>{n}</div><div className={styles.guideCopy}><h4>{title}</h4><p>{caption}</p><div className={styles.mockScreen}>{screen}</div></div></article>}
function PairUpload({busy,send}:{busy:boolean;send:(cert:File|null,key:File|null)=>Promise<void>}){const[cert,setCert]=useState<File|null>(null),[key,setKey]=useState<File|null>(null);return <div className={styles.pair}><label>Certificado<input type="file" accept=".crt,.cer,.pem" onChange={e=>setCert(e.target.files?.[0]||null)}/></label><label>Clave privada<input type="file" accept=".key,.pem" onChange={e=>setKey(e.target.files?.[0]||null)}/></label><button type="button" disabled={busy||!cert||!key} onClick={()=>void send(cert,key)}>Validar y guardar el par</button></div>}
