'use client'

import { useEffect,useState } from 'react'
import type { TenantSession } from '@/lib/comercio/types'
import styles from './arca-setup.module.css'

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
type SetupStatus={configured:boolean;tax_id?:string|null;environment?:'homologacion'|'produccion';point_of_sale?:number|null;receipt_type?:number;credential_slot?:string|null;csr_pem?:string|null;private_key_ready?:boolean;certificate_ready?:boolean;certificate_subject?:string|null;certificate_expires_at?:string|null}
function onlyDigits(v:string){return v.replace(/\D/g,'').slice(0,11)}
async function readText(file:File){return await file.text()}

export default function ArcaSetupPanel({session,companyName,companyTaxId,message}:{session:TenantSession;companyName:string;companyTaxId?:string|null;message:(m:string)=>void}){
  const[status,setStatus]=useState<SetupStatus|null>(null),[taxId,setTaxId]=useState(onlyDigits(companyTaxId||'')),[point,setPoint]=useState(''),[environment,setEnvironment]=useState<'produccion'|'homologacion'>('produccion'),[csr,setCsr]=useState(''),[busy,setBusy]=useState(''),[error,setError]=useState(''),[test,setTest]=useState(''),[advanced,setAdvanced]=useState(false)
  async function setup(body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-setup`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.error||'No se pudo configurar ARCA.');return d}
  async function load(){setError('');try{const s=await setup({action:'status'}) as SetupStatus&{ok:boolean};setStatus(s);if(s.tax_id)setTaxId(onlyDigits(s.tax_id));if(s.point_of_sale)setPoint(String(s.point_of_sale));if(s.environment)setEnvironment(s.environment);if(s.csr_pem)setCsr(s.csr_pem)}catch(e){setError(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{void load()},[session.companyId,session.token])
  async function generate(){if(taxId.length!==11){setError('El CUIT/CUIL debe tener exactamente 11 dígitos.');return}setBusy('csr');setError('');try{const d=await setup({action:'generate_csr',tax_id:taxId,organization:companyName});setCsr(String(d.csr_pem||''));message('CSR generado. La clave privada quedó guardada cifrada; no se descarga ni se muestra.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  function copyCsr(){if(!csr)return;void navigator.clipboard.writeText(csr).then(()=>message('CSR copiado. Pegalo en ARCA.'))}
  function downloadCsr(){if(!csr)return;const blob=new Blob([csr],{type:'application/pkcs10'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`comercio-lleno-${taxId||'arca'}.csr`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function uploadCertificate(file:File|null){if(!file)return;setBusy('cert');setError('');try{const pem=await readText(file);await setup({action:'upload_certificate',tax_id:taxId,certificate_pem:pem});message('Certificado ARCA validado y guardado cifrado.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function uploadPair(cert:File|null,key:File|null){if(!cert||!key){setError('Seleccioná el certificado .crt/.pem y la clave privada .key/.pem.');return}setBusy('pair');setError('');try{await setup({action:'upload_pair',tax_id:taxId,certificate_pem:await readText(cert),private_key_pem:await readText(key)});message('Par de certificado y clave validado y guardado cifrado.');await load()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function configure(){if(taxId.length!==11){setError('El CUIT/CUIL debe tener 11 dígitos.');return}if(!/^\d+$/.test(point)||Number(point)<=0){setError('Ingresá el punto de venta para Web Services.');return}setBusy('configure');setError('');setTest('');try{await setup({action:'configure',tax_id:taxId,point_of_sale:Number(point),environment});message('Configuración ARCA guardada. Probando conexión…');await load();await testConnection()}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setBusy('')}}
  async function testConnection(){setBusy('test');setTest('');try{const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-test`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify({action:'status'}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'ARCA no respondió correctamente.');setTest(`✓ ARCA conectado. Punto de venta ${d.test_point_of_sale}. Último comprobante autorizado: ${d.last_authorized??0}.`);message('ARCA quedó conectado y listo para facturar.')}catch(e){setTest(`⚠ ${e instanceof Error?e.message:String(e)}`)}finally{setBusy('')}}
  const pilot=status?.credential_slot==='pilot_default'
  return <section className={styles.panel}>
    <div className={styles.head}><div><span>FACTURACIÓN ELECTRÓNICA</span><h3>Conectar ARCA</h3><p>Asistente guiado. Comercio Lleno genera el CSR y guarda la clave privada cifrada. Vos sólo hacés la autorización en ARCA y subís el certificado que devuelve.</p></div><div className={`${styles.state} ${status?.configured||pilot?styles.ready:''}`}>{status?.configured||pilot?'✓ Configurado':'Configuración pendiente'}</div></div>
    {pilot&&<div className={styles.pilot}>La Económica conserva su configuración piloto actual. No necesitás migrarla para seguir facturando. El nuevo asistente se usa para conectar otros comercios con credenciales propias.</div>}
    {error&&<div className={styles.error}>{error}</div>}
    <div className={styles.steps}>
      <article className={styles.step}><i>1</i><div><h4>CUIT y CSR</h4><p>Ingresá el CUIT/CUIL de 11 dígitos. Generamos una clave RSA de 2048 bits y un CSR compatible con ARCA.</p><label>CUIT / CUIL<input inputMode="numeric" value={taxId} onChange={e=>setTaxId(onlyDigits(e.target.value))} placeholder="20123456789"/><small>{taxId.length}/11 dígitos</small></label><button disabled={busy!==''} onClick={()=>void generate()}>{busy==='csr'?'Generando…':csr?'Regenerar CSR':'Generar CSR'}</button>{csr&&<div className={styles.csr}><textarea readOnly value={csr}/><div><button onClick={copyCsr}>Copiar CSR</button><button onClick={downloadCsr}>↓ Descargar .csr</button></div></div>}<div className={styles.security}>🔒 La clave privada no se entrega al navegador: queda cifrada en Supabase Vault.</div></div></article>
      <article className={styles.step}><i>2</i><div><h4>Hacer el trámite en ARCA</h4><p>Con Clave Fiscal, creá el certificado usando el CSR. En producción se gestiona desde Administración de Certificados Digitales; en homologación, desde WSASS.</p><ol><li>Creá el certificado pegando el CSR de arriba.</li><li>Descargá el archivo <b>.crt</b> que devuelve ARCA.</li><li>En Administrador de Relaciones, autorizá el servicio <b>wsfe</b> para ese certificado.</li><li>Creá o verificá un punto de venta con modalidad <b>Web Services</b>.</li></ol><a href="https://www.arca.gob.ar/" target="_blank" rel="noreferrer">Abrir ARCA ↗</a></div></article>
      <article className={styles.step}><i>3</i><div><h4>Subir el certificado</h4><p>Subí únicamente el certificado que ARCA devuelve. Verificamos que corresponda a la clave privada del CSR antes de guardarlo.</p><label className={styles.file}>{status?.certificate_ready?'✓ Certificado cargado':'Seleccionar .crt / .pem'}<input type="file" accept=".crt,.cer,.pem,application/x-x509-ca-cert" disabled={busy!==''} onChange={e=>void uploadCertificate(e.target.files?.[0]||null)}/></label>{status?.certificate_subject&&<small className={styles.certInfo}>{status.certificate_subject}<br/>Vence: {status.certificate_expires_at?new Date(status.certificate_expires_at).toLocaleDateString('es-AR'):'—'}</small>}<button className={styles.advancedLink} onClick={()=>setAdvanced(v=>!v)}>{advanced?'Ocultar carga avanzada':'Ya tengo certificado + clave privada'}</button>{advanced&&<PairUpload busy={busy!==''} send={uploadPair}/>}</div></article>
      <article className={styles.step}><i>4</i><div><h4>Punto de venta y prueba</h4><p>Elegí el entorno e ingresá el número de punto de venta habilitado para Web Services.</p><div className={styles.two}><label>Entorno<select value={environment} onChange={e=>setEnvironment(e.target.value as 'produccion'|'homologacion')}><option value="produccion">Producción</option><option value="homologacion">Homologación / pruebas</option></select></label><label>Punto de venta<input inputMode="numeric" value={point} onChange={e=>setPoint(e.target.value.replace(/\D/g,''))} placeholder="Ej: 3"/></label></div><div className={styles.note}>Por ahora este asistente habilita la emisión actual de Comercio Lleno como <b>Factura C</b>. No habilitamos A/B hasta incorporar el tratamiento fiscal e IVA correspondiente.</div><div className={styles.finish}><button className={styles.primary} disabled={busy!==''||(!status?.certificate_ready&&!pilot)} onClick={()=>void configure()}>{busy==='configure'?'Guardando…':'Guardar y conectar ARCA'}</button><button disabled={busy!==''} onClick={()=>void testConnection()}>{busy==='test'?'Probando…':'Probar conexión'}</button></div>{test&&<div className={test.startsWith('✓')?styles.testOk:styles.testBad}>{test}</div>}</div></article>
    </div>
  </section>
}

function PairUpload({busy,send}:{busy:boolean;send:(cert:File|null,key:File|null)=>Promise<void>}){const[cert,setCert]=useState<File|null>(null),[key,setKey]=useState<File|null>(null);return <div className={styles.pair}><label>Certificado<input type="file" accept=".crt,.cer,.pem" onChange={e=>setCert(e.target.files?.[0]||null)}/></label><label>Clave privada<input type="file" accept=".key,.pem" onChange={e=>setKey(e.target.files?.[0]||null)}/></label><button disabled={busy||!cert||!key} onClick={()=>void send(cert,key)}>Validar y guardar el par</button></div>}
