'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import core from './page.module.css'
import styles from './management.module.css'
import {
  addAccountMovement,
  createProduct,
  createStaff,
  createTwoForOnePromotion,
  loadCustomerAccounts,
  loadPromotions,
  loadPurchases,
  loadStaff,
  loadSuppliers,
  registerPurchase,
  registerReturn,
  resetSalesData,
  saveSupplier,
  updateCompanyIdentity,
  updateProduct,
  updateStaff,
  type ArcaHealth,
  type CustomerAccount,
  type Promotion,
  type Purchase,
  type StaffProfile,
  type Supplier,
} from '@/lib/comercio/api'
import { writeDeviceSettings } from '@/lib/comercio/session'
import type { CommerceSnapshot, DeviceSettings, Product, Sale, TenantSession, UserPermissions } from '@/lib/comercio/types'

const money = new Intl.NumberFormat('es-AR', { style: 'currency', currency: 'ARS', maximumFractionDigits: 0 })

function Head({ eyebrow, title, subtitle, children }: { eyebrow: string; title: string; subtitle: string; children?: React.ReactNode }) {
  return <div className={core.pageHead}><div><div className={core.eyebrow}>{eyebrow}</div><h1>{title}</h1><p>{subtitle}</p></div>{children}</div>
}

function n(v: unknown) { return Number(v || 0) }

export function ProductsV2({ data, session, refresh, message }: { data: CommerceSnapshot; session: TenantSession; refresh: () => Promise<void>; message: (m: string) => void }) {
  const [q, setQ] = useState('')
  const [edit, setEdit] = useState<Product | null>(null)
  const [creating, setCreating] = useState(false)
  const [selected, setSelected] = useState<Record<string, number>>({})
  const rows = useMemo(() => data.products.filter(p => `${p.name} ${p.barcode || ''} ${p.category || ''}`.toLowerCase().includes(q.toLowerCase())).slice(0, 500), [data.products, q])
  const selectedRows = data.products.filter(p => (selected[p.id] || 0) > 0).map(p => ({ product: p, qty: selected[p.id] }))
  function toggle(id: string, checked: boolean) { setSelected(s => ({ ...s, [id]: checked ? (s[id] || 1) : 0 })) }
  return <>
    <Head eyebrow="CATÁLOGO" title="Productos" subtitle="Alta, edición, costos, precios, stock, proveedor y etiquetas.">
      <div className={styles.actions}><button className={core.secondary} disabled={!selectedRows.length} onClick={() => printLabels(selectedRows)}>▦ Imprimir etiquetas</button><button className={core.primary} onClick={() => setCreating(true)}>+ Agregar producto</button></div>
    </Head>
    <div className={core.tableTools}><div className={core.searchSlim}><span>⌕</span><input value={q} onChange={e => setQ(e.target.value)} placeholder="Buscar producto, código o categoría…"/></div></div>
    <div className={`${core.table} ${styles.productTable}`}>
      <div className={`${core.tableRow} ${core.tableHead} ${styles.productRow}`}><span></span><span>Producto</span><span>Código</span><span>Categoría</span><span>Costo</span><span>Minorista</span><span>Mayorista</span><span>Margen</span><span>Stock</span><span>Mín.</span><span>Objetivo</span><span></span></div>
      {rows.map(p => { const margin = p.price ? ((p.price - n(p.cost)) / p.price) * 100 : 0; return <div className={`${core.tableRow} ${styles.productRow}`} key={p.id}>
        <span><input type="checkbox" checked={(selected[p.id] || 0) > 0} onChange={e => toggle(p.id, e.target.checked)}/></span>
        <span><b>{p.name}</b><small>{p.unit || 'unidad'}</small></span><span>{p.barcode || '—'}</span><span>{p.category || 'General'}</span><span>{money.format(n(p.cost))}</span><span><b>{money.format(p.price)}</b></span><span>{money.format(n(p.wholesale_price))}</span><span className={margin >= 25 ? styles.good : styles.warn}>{margin.toFixed(1)}%</span><span>{p.stock}</span><span>{n(p.min_stock)}</span><span>{n(p.target_stock)}</span><span><button className={styles.miniButton} onClick={() => setEdit(p)}>Editar</button></span>
      </div> })}
    </div>
    {selectedRows.length > 0 && <div className={styles.labelBar}><b>Etiquetas</b><span>{selectedRows.length} productos seleccionados</span><div className={styles.labelQtys}>{selectedRows.map(x => <label key={x.product.id}>{x.product.name}<input type="number" min="1" max="99" value={x.qty} onChange={e => setSelected(s => ({ ...s, [x.product.id]: Math.max(1, Math.min(99, Number(e.target.value) || 1)) }))}/></label>)}</div><button onClick={() => printLabels(selectedRows)}>Imprimir seleccionadas</button></div>}
    {(edit || creating) && <ProductModal product={edit} session={session} close={() => { setEdit(null); setCreating(false) }} saved={async () => { setEdit(null); setCreating(false); await refresh(); message('Producto guardado.') }}/>} 
  </>
}

function ProductModal({ product, session, close, saved }: { product: Product | null; session: TenantSession; close: () => void; saved: () => Promise<void> }) {
  const [suppliers, setSuppliers] = useState<Supplier[]>([])
  const [draft, setDraft] = useState<Product>(product ? { ...product } : { id: '', name: '', barcode: '', category: 'General', price: 0, cost: 0, wholesale_price: 0, stock: 0, min_stock: 0, target_stock: 0, unit: 'unidad', supplier_id: null })
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState('')
  useEffect(() => { loadSuppliers(session).then(setSuppliers).catch(() => {}) }, [session])
  async function submit(e: FormEvent) { e.preventDefault(); if (!draft.name.trim()) return; setBusy(true); setError(''); try { if (product) await updateProduct(session, draft); else await createProduct(session, draft); await saved() } catch (e) { setError(e instanceof Error ? e.message : String(e)); setBusy(false) } }
  function numberField(key: keyof Product, value: string) { setDraft(d => ({ ...d, [key]: Math.max(0, Number(value) || 0) })) }
  return <div className={styles.modal} onMouseDown={e => e.currentTarget === e.target && close()}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>PRODUCTO</span><h2>{product ? 'Editar producto' : 'Agregar producto'}</h2></div><button type="button" onClick={close}>×</button></div><div className={styles.formGrid}>
    <label>Producto<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>Código de barras<input value={draft.barcode || ''} onChange={e => setDraft({ ...draft, barcode: e.target.value })}/></label>
    <label>Categoría<input value={draft.category || ''} onChange={e => setDraft({ ...draft, category: e.target.value })}/></label><label>Unidad<select value={draft.unit || 'unidad'} onChange={e => setDraft({ ...draft, unit: e.target.value })}><option>unidad</option><option>kg</option><option>litro</option><option>pack</option><option>caja</option></select></label>
    <label>Costo<input type="number" min="0" value={n(draft.cost)} onChange={e => numberField('cost', e.target.value)}/></label><label>Precio minorista<input type="number" min="0" value={n(draft.price)} onChange={e => numberField('price', e.target.value)}/></label>
    <label>Precio mayorista<input type="number" min="0" value={n(draft.wholesale_price)} onChange={e => numberField('wholesale_price', e.target.value)}/></label><label>Stock<input type="number" min="0" value={n(draft.stock)} onChange={e => numberField('stock', e.target.value)}/></label>
    <label>Stock mínimo<input type="number" min="0" value={n(draft.min_stock)} onChange={e => numberField('min_stock', e.target.value)}/></label><label>Stock objetivo<input type="number" min="0" value={n(draft.target_stock)} onChange={e => numberField('target_stock', e.target.value)}/></label>
    <label className={styles.wide}>Proveedor<select value={draft.supplier_id || ''} onChange={e => setDraft({ ...draft, supplier_id: e.target.value || null })}><option value="">Sin proveedor</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
  </div>{error && <div className={styles.formError}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={close}>Cancelar</button><button className={styles.save} disabled={busy}>{busy ? 'Guardando…' : 'Guardar cambios'}</button></div></form></div>
}

export function SuppliersV2({ session }: { session: TenantSession }) {
  const [rows, setRows] = useState<Supplier[]>([]), [edit, setEdit] = useState<Supplier | null>(null), [creating, setCreating] = useState(false), [error, setError] = useState('')
  async function load() { try { setRows(await loadSuppliers(session)); setError('') } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  useEffect(() => { load() }, [])
  return <><Head eyebrow="ABASTECIMIENTO" title="Proveedores" subtitle="Contactos y proveedores asociados al comercio."><button className={core.primary} onClick={() => setCreating(true)}>+ Nuevo proveedor</button></Head>{error && <div className={core.error}>{error}</div>}<div className={core.table}><div className={`${core.tableRow} ${core.tableHead} ${styles.supplierRow}`}><span>Proveedor</span><span>CUIT</span><span>Teléfono</span><span>Email</span><span></span></div>{rows.map(x => <div className={`${core.tableRow} ${styles.supplierRow}`} key={x.id}><span><b>{x.name}</b></span><span>{x.tax_id || '—'}</span><span>{x.phone || '—'}</span><span>{x.email || '—'}</span><span><button className={styles.miniButton} onClick={() => setEdit(x)}>Editar</button></span></div>)}</div>{(edit || creating) && <SupplierModal value={edit} session={session} close={() => { setEdit(null); setCreating(false) }} saved={async () => { setEdit(null); setCreating(false); await load() }}/>}</>
}

function SupplierModal({ value, session, close, saved }: { value: Supplier | null; session: TenantSession; close: () => void; saved: () => Promise<void> }) {
  const [draft, setDraft] = useState<Supplier>(value ? { ...value } : { id: '', name: '', tax_id: '', phone: '', email: '', notes: '' }), [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); if (!draft.name.trim()) return; setBusy(true); try { await saveSupplier(session, draft); await saved() } catch (e) { setError(e instanceof Error ? e.message : String(e)); setBusy(false) } }
  return <div className={styles.modal}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>PROVEEDOR</span><h2>{value ? 'Editar proveedor' : 'Nuevo proveedor'}</h2></div><button type="button" onClick={close}>×</button></div><div className={styles.formGrid}><label>Nombre<input value={draft.name} onChange={e => setDraft({ ...draft, name: e.target.value })}/></label><label>CUIT<input value={draft.tax_id || ''} onChange={e => setDraft({ ...draft, tax_id: e.target.value })}/></label><label>Teléfono<input value={draft.phone || ''} onChange={e => setDraft({ ...draft, phone: e.target.value })}/></label><label>Email<input value={draft.email || ''} onChange={e => setDraft({ ...draft, email: e.target.value })}/></label><label className={styles.wide}>Notas<input value={draft.notes || ''} onChange={e => setDraft({ ...draft, notes: e.target.value })}/></label></div>{error && <div className={styles.formError}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={close}>Cancelar</button><button className={styles.save} disabled={busy}>Guardar</button></div></form></div>
}

export function PurchasesV2({ data, session, refresh }: { data: CommerceSnapshot; session: TenantSession; refresh: () => Promise<void> }) {
  const [rows, setRows] = useState<Purchase[]>([]), [suppliers, setSuppliers] = useState<Supplier[]>([]), [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [error, setError] = useState('')
  const [supplier, setSupplier] = useState(''), [productId, setProductId] = useState(''), [invoice, setInvoice] = useState(''), [qty, setQty] = useState(1), [cost, setCost] = useState(0)
  async function load() { try { const [p, s] = await Promise.all([loadPurchases(session), loadSuppliers(session)]); setRows(p); setSuppliers(s); setError('') } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  useEffect(() => { load() }, [])
  async function submit(e: FormEvent) { e.preventDefault(); const product = data.products.find(x => x.id === productId); if (!product || !supplier || qty <= 0 || cost < 0) return; setBusy(true); try { await registerPurchase(session, { supplier_id: supplier, invoice_number: invoice, product, quantity: qty, unit_cost: cost }); setOpen(false); await Promise.all([load(), refresh()]) } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  return <><Head eyebrow="ABASTECIMIENTO" title="Compras" subtitle="Ingresá mercadería, costo y stock en un solo paso."><button className={core.primary} onClick={() => setOpen(true)}>+ Registrar compra</button></Head>{error && <div className={core.error}>{error}</div>}<div className={core.table}><div className={`${core.tableRow} ${core.tableHead} ${styles.purchaseRow}`}><span>Fecha</span><span>Proveedor</span><span>Comprobante</span><span>Total</span></div>{rows.map(x => <div className={`${core.tableRow} ${styles.purchaseRow}`} key={x.id}><span>{new Date(x.purchased_at).toLocaleString('es-AR')}</span><span>{x.suppliers?.name || '—'}</span><span>{x.invoice_number || '—'}</span><span><b>{money.format(x.total)}</b></span></div>)}</div>{open && <div className={styles.modal}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>COMPRA</span><h2>Registrar compra</h2></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className={styles.formGrid}><label>Proveedor<select value={supplier} onChange={e => setSupplier(e.target.value)}><option value="">Seleccionar…</option>{suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Comprobante<input value={invoice} onChange={e => setInvoice(e.target.value)}/></label><label className={styles.wide}>Producto<select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Seleccionar…</option>{data.products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Cantidad<input type="number" min="0.01" step="0.01" value={qty} onChange={e => setQty(Number(e.target.value) || 0)}/></label><label>Costo unitario<input type="number" min="0" value={cost} onChange={e => setCost(Number(e.target.value) || 0)}/></label></div><div className={styles.modalActions}><button type="button" onClick={() => setOpen(false)}>Cancelar</button><button className={styles.save} disabled={busy}>Confirmar ingreso</button></div></form></div>}</>
}

export function ProfitabilityV2({ data }: { data: CommerceSnapshot }) {
  const productMap = new Map(data.products.map(p => [p.id, p]))
  let revenue = 0, cost = 0, units = 0
  data.sales.forEach(s => { revenue += s.total; (s.details?.items || []).forEach(i => { cost += n(productMap.get(i.product_id)?.cost) * n(i.qty); units += n(i.qty) }) })
  const gross = revenue - cost, margin = revenue ? gross / revenue * 100 : 0
  return <><Head eyebrow="GESTIÓN" title="Rentabilidad" subtitle="Ganancia bruta estimada según costos cargados."/><div className={core.kpis}><div className={core.kpi}><span>Ventas</span><strong>{money.format(revenue)}</strong><small>{data.sales.length} operaciones</small></div><div className={core.kpi}><span>Costo vendido</span><strong>{money.format(cost)}</strong><small>{units} unidades</small></div><div className={`${core.kpi} ${core.kpiAccent}`}><span>Ganancia bruta</span><strong>{money.format(gross)}</strong><small>Estimación por costo</small></div><div className={core.kpi}><span>Margen bruto</span><strong>{margin.toFixed(1)}%</strong><small>Sobre ventas</small></div></div><div className={core.panel}><b>Cómo mejorar este dato</b><p className={styles.note}>La rentabilidad se vuelve más precisa cuando todos los productos tienen su costo actualizado. Las compras registradas actualizan ese costo automáticamente.</p></div></>
}

export function AccountsV2({ data, session }: { data: CommerceSnapshot; session: TenantSession }) {
  const [accounts, setAccounts] = useState<CustomerAccount[]>([]), [open, setOpen] = useState(false), [customer, setCustomer] = useState(''), [kind, setKind] = useState<'charge' | 'payment'>('charge'), [amount, setAmount] = useState(0), [note, setNote] = useState(''), [error, setError] = useState('')
  async function load() { try { setAccounts(await loadCustomerAccounts(session)); setError('') } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  useEffect(() => { load() }, [])
  const balances = new Map(accounts.map(x => [x.customer_id, x.balance]))
  async function submit(e: FormEvent) { e.preventDefault(); if (!customer || amount <= 0) return; try { await addAccountMovement(session, customer, kind, amount, note, balances.get(customer) || 0); setOpen(false); setAmount(0); setNote(''); await load() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  return <><Head eyebrow="GESTIÓN" title="Cuentas corrientes" subtitle="Fiado, cargos, pagos y saldo por cliente."><button className={core.primary} onClick={() => setOpen(true)}>+ Movimiento</button></Head>{error && <div className={core.error}>{error}</div>}<div className={core.table}><div className={`${core.tableRow} ${core.tableHead} ${styles.accountRow}`}><span>Cliente</span><span>Saldo</span><span>Estado</span></div>{data.customers.map(c => { const balance = balances.get(c.id) || 0; return <div className={`${core.tableRow} ${styles.accountRow}`} key={c.id}><span><b>{c.name}</b></span><span>{money.format(balance)}</span><span><span className={`${core.badge} ${balance > 0 ? core.badgeAmber : core.badgeGreen}`}>{balance > 0 ? 'Debe' : 'Al día'}</span></span></div> })}</div>{open && <div className={styles.modal}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>CUENTA</span><h2>Nuevo movimiento</h2></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className={styles.formGrid}><label>Cliente<select value={customer} onChange={e => setCustomer(e.target.value)}><option value="">Seleccionar…</option>{data.customers.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tipo<select value={kind} onChange={e => setKind(e.target.value as 'charge' | 'payment')}><option value="charge">Compra fiada / cargo</option><option value="payment">Pago</option></select></label><label>Monto<input type="number" min="0" value={amount} onChange={e => setAmount(Number(e.target.value) || 0)}/></label><label>Nota<input value={note} onChange={e => setNote(e.target.value)}/></label></div><div className={styles.modalActions}><button type="button" onClick={() => setOpen(false)}>Cancelar</button><button className={styles.save}>Guardar movimiento</button></div></form></div>}</>
}

export function ReturnsV2({ data, session, refresh, message }: { data: CommerceSnapshot; session: TenantSession; refresh: () => Promise<void>; message: (m: string) => void }) {
  const [sale, setSale] = useState<Sale | null>(null), [selected, setSelected] = useState<Record<number, boolean>>({}), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('')
  function openSale(s: Sale) { setSale(s); const x: Record<number, boolean> = {}; (s.details?.items || []).forEach((_, i) => x[i] = true); setSelected(x); setReason('') }
  async function submit() { if (!sale) return; const items = (sale.details?.items || []).filter((_, i) => selected[i]).map(i => ({ product_id: i.product_id, name: i.name, qty: i.qty, unit_price: i.unit_price })); setBusy(true); try { await registerReturn(session, sale, items, data.products, reason); setSale(null); await refresh(); message('Devolución registrada. La nota de crédito quedó pendiente.') } catch (e) { setError(e instanceof Error ? e.message : String(e)) } finally { setBusy(false) } }
  return <><Head eyebrow="GESTIÓN" title="Devoluciones" subtitle="Reintegro de mercadería al stock y seguimiento de nota de crédito."/>{error && <div className={core.error}>{error}</div>}<div className={core.table}><div className={`${core.tableRow} ${core.tableHead} ${styles.returnRow}`}><span>Venta</span><span>Fecha</span><span>Total</span><span></span></div>{data.sales.slice(0, 150).map(s => <div className={`${core.tableRow} ${styles.returnRow}`} key={s.id}><span><b>#{s.id.slice(0, 8)}</b></span><span>{new Date(s.date).toLocaleString('es-AR')}</span><span>{money.format(s.total)}</span><span><button className={styles.miniButton} disabled={!s.details?.items?.length} onClick={() => openSale(s)}>Devolver</button></span></div>)}</div>{sale && <div className={styles.modal}><div className={styles.modalCard}><div className={styles.modalHead}><div><span>DEVOLUCIÓN</span><h2>Venta #{sale.id.slice(0, 8)}</h2></div><button onClick={() => setSale(null)}>×</button></div><div className={styles.returnItems}>{(sale.details?.items || []).map((i, idx) => <label key={idx}><input type="checkbox" checked={selected[idx] !== false} onChange={e => setSelected({ ...selected, [idx]: e.target.checked })}/><span><b>{i.name}</b><small>{i.qty} × {money.format(i.unit_price)}</small></span></label>)}</div><label className={styles.blockLabel}>Motivo<input value={reason} onChange={e => setReason(e.target.value)} placeholder="Motivo de la devolución"/></label><div className={styles.modalActions}><button onClick={() => setSale(null)}>Cancelar</button><button className={styles.save} disabled={busy} onClick={submit}>Confirmar devolución</button></div></div></div>}</>
}

export function PromotionsV2({ data, session }: { data: CommerceSnapshot; session: TenantSession }) {
  const [rows, setRows] = useState<Promotion[]>([]), [open, setOpen] = useState(false), [name, setName] = useState('2x1'), [product, setProduct] = useState(''), [error, setError] = useState('')
  async function load() { try { setRows(await loadPromotions(session)); setError('') } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  useEffect(() => { load() }, [])
  async function submit(e: FormEvent) { e.preventDefault(); if (!product) return; try { await createTwoForOnePromotion(session, name, product); setOpen(false); await load() } catch (e) { setError(e instanceof Error ? e.message : String(e)) } }
  return <><Head eyebrow="GESTIÓN" title="Promociones" subtitle="Promociones comerciales aplicables a productos."><button className={core.primary} onClick={() => setOpen(true)}>+ Crear 2x1</button></Head>{error && <div className={core.error}>{error}</div>}<div className={core.table}><div className={`${core.tableRow} ${core.tableHead} ${styles.promoRow}`}><span>Promoción</span><span>Producto</span><span>Tipo</span><span>Estado</span></div>{rows.map(x => <div className={`${core.tableRow} ${styles.promoRow}`} key={x.id}><span><b>{x.name}</b></span><span>{data.products.find(p => p.id === x.product_id)?.name || '—'}</span><span>{x.type}</span><span><span className={`${core.badge} ${x.active ? core.badgeGreen : core.badgeRed}`}>{x.active ? 'Activa' : 'Inactiva'}</span></span></div>)}</div>{open && <div className={styles.modal}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>PROMOCIÓN</span><h2>Nueva promoción 2x1</h2></div><button type="button" onClick={() => setOpen(false)}>×</button></div><div className={styles.formGrid}><label>Nombre<input value={name} onChange={e => setName(e.target.value)}/></label><label>Producto<select value={product} onChange={e => setProduct(e.target.value)}><option value="">Seleccionar…</option>{data.products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select></label></div><div className={styles.modalActions}><button type="button" onClick={() => setOpen(false)}>Cancelar</button><button className={styles.save}>Crear promoción</button></div></form></div>}</>
}

export function SettingsV2({ data, session, device, setDevice, arca, buildVersion, refresh, message }: { data: CommerceSnapshot; session: TenantSession; device: DeviceSettings; setDevice: (d: DeviceSettings) => void; arca: ArcaHealth | null; buildVersion: string; refresh: () => Promise<void>; message: (m: string) => void }) {
  const [tab, setTab] = useState<'commerce' | 'sales' | 'arca' | 'printer' | 'stock' | 'users' | 'maintenance'>('commerce')
  const [name, setName] = useState(data.company.name), [tax, setTax] = useState(data.company.tax_id || '')
  const [staff, setStaff] = useState<StaffProfile[]>([]), [staffError, setStaffError] = useState(''), [newStaff, setNewStaff] = useState(false)
  const [resetOpen, setResetOpen] = useState(false), [resetPass, setResetPass] = useState(''), [resetBusy, setResetBusy] = useState(false), [resetError, setResetError] = useState('')
  const owner = session.role === 'owner'
  async function loadUsers() { if (!owner) return; try { setStaff(await loadStaff(session)); setStaffError('') } catch (e) { setStaffError(e instanceof Error ? e.message : String(e)) } }
  useEffect(() => { if (tab === 'users') loadUsers() }, [tab])
  async function saveCommerce() { try { await updateCompanyIdentity(session, name, tax); await refresh(); message('Datos del comercio guardados.') } catch (e) { message(e instanceof Error ? e.message : String(e)) } }
  function savePrinter(next: DeviceSettings) { setDevice(next); writeDeviceSettings(session.companyId, next); message('Configuración de impresora guardada en esta PC.') }
  async function resetSales() { if (!resetPass) return; setResetBusy(true); setResetError(''); try { await resetSalesData(session, resetPass); setResetOpen(false); setResetPass(''); await refresh(); message('Las ventas quedaron restablecidas a cero.') } catch (e) { setResetError(e instanceof Error ? e.message : String(e)) } finally { setResetBusy(false) } }
  const tabs = [
    ['commerce','Comercio'],['sales','Ventas y caja'],['arca','ARCA'],['printer','Impresora y tickets'],['stock','Stock'],...(owner ? [['users','Usuarios y roles'],['maintenance','Mantenimiento']] : []),
  ] as Array<[typeof tab,string]>
  return <><Head eyebrow="ADMINISTRACIÓN" title="Configuración" subtitle="Configuración completa del comercio, dispositivo y permisos."/><div className={styles.settingsLayout}><aside className={styles.settingsNav}>{tabs.map(([id,label]) => <button key={id} className={tab === id ? styles.settingsActive : ''} onClick={() => setTab(id)}>{label}</button>)}</aside><section className={styles.settingsBody}>
    {tab === 'commerce' && <div className={styles.settingPanel}><h3>Datos del comercio</h3><p>Información principal asociada a este tenant.</p><div className={styles.formGrid}><label>Nombre<input value={name} onChange={e => setName(e.target.value)}/></label><label>CUIT<input value={tax} onChange={e => setTax(e.target.value)}/></label></div><button className={core.primary} onClick={saveCommerce}>Guardar cambios</button></div>}
    {tab === 'sales' && <LocalSettingsPanel storageKey="cl_settings" section="sales" title="Ventas y caja" fields={[['allowNegative','Permitir vender sin stock','check'],['maxDiscount','Descuento máximo (%)','number'],['timeFormat','Formato horario 24 h','check']]}/>} 
    {tab === 'arca' && <div className={styles.settingPanel}><h3>ARCA / Facturación electrónica</h3><p>Estado fiscal actual del comercio.</p><div className={styles.settingLines}><div><span>Conexión</span><b className={arca?.connected ? styles.good : styles.bad}>{arca?.connected ? 'Conectado' : 'Desconectado'}</b></div><div><span>Servicio</span><b>{arca?.service || 'wsfev1'}</b></div><div><span>Punto de venta</span><b>{arca?.pointOfSale ?? '—'}</b></div><div><span>Entorno</span><b>{arca?.environment || 'homologación'}</b></div></div><div className={styles.note}>La configuración fiscal por comercio se va a mantener separada por tenant. El piloto actual de La Económica sigue usando la integración fiscal existente.</div></div>}
    {tab === 'printer' && <div className={styles.settingPanel}><h3>Impresora y tickets</h3><p>Esta configuración pertenece a esta PC.</p><div className={styles.formGrid}><label>Papel<select value={device.paper} onChange={e => savePrinter({ ...device, paper: e.target.value as '80' | '58' })}><option value="80">80 mm</option><option value="58">58 mm</option></select></label><label>Modo<select value={device.printerMode} onChange={e => savePrinter({ ...device, printerMode: e.target.value as 'browser' | 'bridge' })}><option value="browser">Navegador</option><option value="bridge">Bridge local / automático</option></select></label><label>Nombre de impresora<input value={device.printerName} onChange={e => savePrinter({ ...device, printerName: e.target.value })}/></label><label>Copias<input type="number" min="1" max="3" value={device.receiptCopies} onChange={e => savePrinter({ ...device, receiptCopies: Math.max(1, Math.min(3, Number(e.target.value) || 1)) })}/></label></div><label className={styles.switch}><span>Imprimir automáticamente después de ARCA</span><input type="checkbox" checked={device.autoPrint} onChange={e => savePrinter({ ...device, autoPrint: e.target.checked })}/></label></div>}
    {tab === 'stock' && <LocalSettingsPanel storageKey="cl_settings" section="stock" title="Stock e inventario" fields={[['low','Avisar stock bajo desde','number'],['allowNegative','Permitir stock negativo','check']]}/>} 
    {tab === 'users' && owner && <div className={styles.settingPanel}><div className={styles.settingHead}><div><h3>Usuarios, roles y permisos</h3><p>Solo visible y administrable por el Propietario.</p></div><button className={core.primary} onClick={() => setNewStaff(true)}>+ Crear usuario</button></div>{staffError && <div className={styles.formError}>{staffError}</div>}<div className={styles.staffList}>{staff.filter(x => x.role !== 'owner').map(x => <StaffRow key={x.id} staff={x} session={session} saved={loadUsers}/>)}</div>{newStaff && <NewStaffModal session={session} close={() => setNewStaff(false)} saved={async () => { setNewStaff(false); await loadUsers() }}/>}</div>}
    {tab === 'maintenance' && owner && <div className={`${styles.settingPanel} ${styles.dangerPanel}`}><h3>Restablecer valores de ventas</h3><p>Pone en cero ventas, reportes e historial. No modifica productos, stock, clientes ni configuración.</p><button className={styles.dangerButton} onClick={() => setResetOpen(true)}>Restablecer ventas a cero</button><div className={styles.note}>Requiere la contraseña del propietario y no se puede deshacer.</div></div>}
    <div className={styles.versionBox}>Comercio Lleno · Rediseño V2 · build {buildVersion} · tenant {session.companyId.slice(0,8)}</div>
  </section></div>{resetOpen && <div className={styles.modal}><div className={`${styles.modalCard} ${styles.dangerModal}`}><div className={styles.modalHead}><div><span>ZONA SENSIBLE</span><h2>Restablecer ventas</h2></div><button onClick={() => setResetOpen(false)}>×</button></div><p>Se eliminará el historial de ventas de este comercio y los indicadores quedarán en cero. Productos, stock y clientes no se modifican.</p><label className={styles.blockLabel}>Contraseña del propietario<input type="password" value={resetPass} onChange={e => setResetPass(e.target.value)} autoComplete="current-password"/></label>{resetError && <div className={styles.formError}>{resetError}</div>}<div className={styles.modalActions}><button onClick={() => setResetOpen(false)}>Cancelar</button><button className={styles.dangerButton} disabled={resetBusy} onClick={resetSales}>{resetBusy ? 'Restableciendo…' : 'Confirmar y poner en cero'}</button></div></div></div>}</>
}

function LocalSettingsPanel({ storageKey, section, title, fields }: { storageKey: string; section: string; title: string; fields: Array<[string,string,'number'|'check']> }) {
  const [state, setState] = useState<Record<string, any>>({})
  useEffect(() => { try { const all = JSON.parse(localStorage.getItem(storageKey) || '{}'); setState(all[section] || {}) } catch {} }, [storageKey, section])
  function save() { let all: any = {}; try { all = JSON.parse(localStorage.getItem(storageKey) || '{}') } catch {}; all[section] = state; localStorage.setItem(storageKey, JSON.stringify(all)) }
  return <div className={styles.settingPanel}><h3>{title}</h3><p>Ajustes propios de operación de este comercio.</p><div className={styles.localFields}>{fields.map(([key,label,type]) => type === 'check' ? <label className={styles.switch} key={key}><span>{label}</span><input type="checkbox" checked={Boolean(state[key])} onChange={e => setState({ ...state, [key]: e.target.checked })}/></label> : <label className={styles.blockLabel} key={key}>{label}<input type="number" min="0" value={state[key] ?? ''} onChange={e => setState({ ...state, [key]: Number(e.target.value) || 0 })}/></label>)}</div><button className={core.primary} onClick={save}>Guardar ajustes</button></div>
}

function StaffRow({ staff, session, saved }: { staff: StaffProfile; session: TenantSession; saved: () => Promise<void> }) {
  const [role, setRole] = useState(staff.role), [permissions, setPermissions] = useState<UserPermissions>(staff.permissions || {}), [busy, setBusy] = useState(false)
  async function save() { setBusy(true); await updateStaff(session, staff.id, role, permissions); await saved(); setBusy(false) }
  function setP(k: string, v: boolean) { setPermissions({ ...permissions, [k]: v }) }
  return <div className={styles.staffRow}><div><b>{staff.full_name || staff.username || 'Usuario'}</b><small>{staff.username || ''}</small></div><select value={role} onChange={e => { const r = e.target.value; setRole(r); if (r === 'supervisor') setP('can_sell', false) }}><option value="cashier">Encargado / Cajero</option><option value="supervisor">Supervisor</option></select><div className={styles.permissionSet}><label><input type="checkbox" checked={permissions.can_sell !== false} onChange={e => setP('can_sell', e.target.checked)}/> Vender</label><label><input type="checkbox" checked={permissions.can_view_reports !== false} onChange={e => setP('can_view_reports', e.target.checked)}/> Reportes</label><label><input type="checkbox" checked={permissions.can_manage_stock !== false} onChange={e => setP('can_manage_stock', e.target.checked)}/> Stock</label><label><input type="checkbox" checked={permissions.can_manage_customers !== false} onChange={e => setP('can_manage_customers', e.target.checked)}/> Clientes</label></div><button className={styles.miniButton} disabled={busy} onClick={save}>{busy ? 'Guardando…' : 'Guardar'}</button></div>
}

function NewStaffModal({ session, close, saved }: { session: TenantSession; close: () => void; saved: () => Promise<void> }) {
  const [name, setName] = useState(''), [username, setUsername] = useState(''), [password, setPassword] = useState(''), [role, setRole] = useState<'cashier'|'supervisor'>('cashier'), [busy, setBusy] = useState(false), [error, setError] = useState('')
  async function submit(e: FormEvent) { e.preventDefault(); if (!username.trim() || password.length < 6) { setError('Completá usuario y una contraseña de al menos 6 caracteres.'); return } const permissions: UserPermissions = role === 'supervisor' ? { can_sell: false, can_view_reports: true, can_manage_stock: true, can_manage_customers: true } : { can_sell: true, can_view_reports: true, can_manage_stock: true, can_manage_customers: true }; setBusy(true); try { await createStaff(session, { username, password, full_name: name, role, permissions }); await saved() } catch (e) { setError(e instanceof Error ? e.message : String(e)); setBusy(false) } }
  return <div className={styles.modal}><form className={styles.modalCard} onSubmit={submit}><div className={styles.modalHead}><div><span>USUARIO</span><h2>Crear usuario del comercio</h2></div><button type="button" onClick={close}>×</button></div><div className={styles.formGrid}><label>Nombre<input value={name} onChange={e => setName(e.target.value)}/></label><label>Usuario<input value={username} onChange={e => setUsername(e.target.value)} placeholder="ej: caja1"/></label><label>Contraseña<input type="password" value={password} onChange={e => setPassword(e.target.value)} minLength={6}/></label><label>Rol<select value={role} onChange={e => setRole(e.target.value as 'cashier'|'supervisor')}><option value="cashier">Encargado / Cajero</option><option value="supervisor">Supervisor</option></select></label></div>{error && <div className={styles.formError}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={close}>Cancelar</button><button className={styles.save} disabled={busy}>{busy ? 'Creando…' : 'Crear usuario'}</button></div></form></div>
}

function checksumEAN13(value: string) { const d = value.slice(0,12).split('').map(Number); let sum=0; for(let i=0;i<12;i++) sum += d[i]*(i%2?3:1); return String((10-sum%10)%10) }
function eanBits(value: string) { let s=value.replace(/\D/g,''); if(s.length===12)s+=checksumEAN13(s); if(s.length!==13)return null; const L=['0001101','0011001','0010011','0111101','0100011','0110001','0101111','0111011','0110111','0001011'],G=['0100111','0110011','0011011','0100001','0011101','0111001','0000101','0010001','0001001','0010111'],R=['1110010','1100110','1101100','1000010','1011100','1001110','1010000','1000100','1001000','1110100'],P=['LLLLLL','LLGLGG','LLGGLG','LLGGGL','LGLLGG','LGGLLG','LGGGLL','LGLGLG','LGLGGL','LGGLGL']; let bits='101',parity=P[Number(s[0])]; for(let i=1;i<=6;i++)bits+=parity[i-1]==='L'?L[Number(s[i])]:G[Number(s[i])]; bits+='01010'; for(let i=7;i<=12;i++)bits+=R[Number(s[i])]; bits+='101'; return { s,bits } }
function esc(s: string) { return s.replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c] || c)) }
function printLabels(items: Array<{ product: Product; qty: number }>) { const labels:string[]=[]; const date=new Date().toLocaleDateString('es-AR'); items.forEach(({product:p,qty})=>{ for(let q=0;q<Math.max(1,Math.min(99,qty));q++){ const code=eanBits(String(p.barcode||'')); const svg=code?`<svg viewBox="0 0 ${code.bits.length} 52" preserveAspectRatio="none"><g>${code.bits.split('').map((b,i)=>b==='1'?`<rect x="${i}" y="0" width="1" height="42"/>`:'').join('')}</g><text x="0" y="51" font-size="7">${code.s}</text></svg>`:''; labels.push(`<article class="label"><div class="name">${esc(p.name)}</div><div class="price">${money.format(p.price)}</div>${svg?`<div class="barcode">${svg}</div>`:'<div class="nocode">SIN CÓDIGO</div>'}<div class="date">${date}</div></article>`) } }); const sheets:string[]=[]; for(let i=0;i<labels.length;i+=21)sheets.push(`<main class="sheet">${labels.slice(i,i+21).join('')}</main>`); const w=window.open('','_blank','width=1000,height=800'); if(!w){alert('Permití ventanas emergentes para imprimir etiquetas.');return} w.document.write(`<!doctype html><html><head><title>Etiquetas</title><style>@page{size:A4 portrait;margin:0}*{box-sizing:border-box}body{margin:0;font-family:Arial}.sheet{width:210mm;height:297mm;display:grid;grid-template-columns:repeat(3,70mm);grid-template-rows:repeat(7,42.42mm);break-after:page}.label{width:70mm;height:42.42mm;border:1px dashed #aaa;padding:3mm 4mm;display:flex;flex-direction:column;align-items:center;overflow:hidden}.name{font-size:10px;font-weight:700;text-transform:uppercase;text-align:center;height:9mm}.price{font-size:22px;font-weight:800}.barcode{width:50mm;height:14mm}.barcode svg{width:50mm;height:14mm}.nocode{height:14mm;display:grid;place-items:center;font-size:10px}.date{font-size:7px;align-self:flex-start}</style></head><body>${sheets.join('')}<script>onload=()=>setTimeout(()=>print(),250)<\/script></body></html>`); w.document.close() }
