'use client'

import { useEffect,useState } from 'react'
import { createStaticQrPos,getStaticQrStatus,listStaticQrPos,listStaticQrStores,selectStaticQrPos,unlinkStaticQr,type StaticQrLink,type StaticQrPos,type StaticQrStore } from '@/lib/comercio/mercadopago-static-qr'
import type { TenantSession } from '@/lib/comercio/types'

const panel:React.CSSProperties={marginTop:16,border:'1px solid #d9e6e0',borderRadius:20,background:'#fff',overflow:'hidden',boxShadow:'0 8px 28px rgba(20,45,34,.05)'}
const button:React.CSSProperties={height:42,borderRadius:11,border:'1px solid #b8d3c5',background:'#f2faf6',color:'#155d3e',fontWeight:900,padding:'0 15px',cursor:'pointer'}
const input:React.CSSProperties={height:42,border:'1px solid #cbd8d1',borderRadius:11,padding:'0 12px',fontWeight:750,width:'100%',background:'#fff'}

export default function MercadoPagoPhysicalQrPanel({session,message}:{session:TenantSession;message:(text:string)=>void}){
  const[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[accountConnected,setAccountConnected]=useState(false),[link,setLink]=useState<StaticQrLink|null>(null),[positions,setPositions]=useState<StaticQrPos[]>([]),[stores,setStores]=useState<StaticQrStore[]>([]),[showPicker,setShowPicker]=useState(false),[showCreate,setShowCreate]=useState(false),[error,setError]=useState('')
  const[storeId,setStoreId]=useState(''),[externalStoreId,setExternalStoreId]=useState(''),[name,setName]=useState('Caja Comercio Lleno'),[externalId,setExternalId]=useState(`CLQR${Date.now().toString().slice(-8)}`)

  async function refresh(){setLoading(true);setError('');try{const status=await getStaticQrStatus(session);setAccountConnected(status.account_connected);setLink(status.linked?status.qr||null:null)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setLoading(false)}}
  useEffect(()=>{void refresh()},[session.companyId,session.token])

  async function openPicker(){setBusy(true);setError('');try{const result=await listStaticQrPos(session);setPositions(result.positions||[]);setShowPicker(true)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
  async function choose(pos:StaticQrPos){setBusy(true);setError('');try{await selectStaticQrPos(session,pos.id);setShowPicker(false);await refresh();message(`QR físico “${pos.name}” vinculado. Mañana podemos probar un cobro estático desde Nueva venta.`)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
  async function openCreate(){setBusy(true);setError('');try{const result=await listStaticQrStores(session);setStores(result.stores||[]);if(result.stores?.[0]){setStoreId(result.stores[0].id);setExternalStoreId(result.stores[0].external_id)}setShowCreate(true)}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
  async function create(){if(!storeId||!externalStoreId||!name.trim()||!externalId.trim())return;setBusy(true);setError('');try{await createStaticQrPos(session,{name:name.trim(),store_id:storeId,external_store_id:externalStoreId,external_id:externalId.trim(),category:5499});setShowCreate(false);await refresh();message('Caja QR creada y vinculada. Mercado Pago genera un QR estático exclusivo para imprimir o pegar en la caja.') }catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}
  async function unlink(){if(!window.confirm('¿Desvincular el QR físico de Comercio Lleno? El QR seguirá existiendo en Mercado Pago.'))return;setBusy(true);try{await unlinkStaticQr(session);setLink(null);message('QR físico desvinculado de Comercio Lleno.')}catch(err){setError(err instanceof Error?err.message:String(err))}finally{setBusy(false)}}

  return <section style={panel}>
    <div style={{padding:20,display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:18,flexWrap:'wrap',borderBottom:'1px solid #edf2ef'}}><div><div style={{fontSize:10,fontWeight:950,letterSpacing:1.4,color:'#188253'}}>QR FÍSICO · MERCADO PAGO</div><h3 style={{fontSize:20,margin:'5px 0 6px'}}>Vincular el QR pegado en tu caja</h3><p style={{margin:0,maxWidth:680,fontSize:12,lineHeight:1.55,color:'#607068'}}>Usa el modelo QR estático de Mercado Pago: Comercio Lleno envía el importe a la caja vinculada y el cliente escanea siempre el mismo QR físico. Es independiente del Point.</p></div>{link?<span style={{padding:'8px 11px',borderRadius:999,background:'#e6f7ee',color:'#126d43',fontSize:11,fontWeight:950}}>● Vinculado</span>:<span style={{padding:'8px 11px',borderRadius:999,background:'#f2f4f3',color:'#68756e',fontSize:11,fontWeight:900}}>{loading?'Consultando…':'Sin vincular'}</span>}</div>
    <div style={{padding:20,display:'grid',gap:14}}>
      {!accountConnected&&!loading&&<div style={{padding:13,borderRadius:12,background:'#fff7e8',border:'1px solid #efdbad',fontSize:12,lineHeight:1.5,color:'#76571e'}}>Primero conectá tu cuenta de Mercado Pago en el bloque de arriba. El QR físico reutiliza esa autorización segura.</div>}
      {link?<div style={{display:'grid',gridTemplateColumns:'minmax(0,1fr) auto',gap:15,alignItems:'center',padding:15,border:'1px solid #dbe9e2',borderRadius:15,background:'#f8fcfa'}}><div><b style={{fontSize:16}}>{link.name||'Caja QR'}</b><div style={{fontSize:11,color:'#617068',marginTop:4}}>ID externo: <b>{link.external_pos_id}</b>{link.external_store_id?` · Sucursal ${link.external_store_id}`:''}</div><div style={{fontSize:11,color:'#617068',marginTop:3}}>El importe se carga automáticamente sobre este QR; el cliente no lo escribe.</div></div>{link.image?<img src={link.image} alt="QR físico vinculado" width={88} height={88} style={{borderRadius:10,border:'1px solid #d8e2dd',background:'#fff',padding:4}}/>:null}<div style={{gridColumn:'1 / -1',display:'flex',gap:9,flexWrap:'wrap'}}><button type="button" style={button} disabled={busy} onClick={()=>void openPicker()}>Cambiar QR físico</button>{link.template?<a href={link.template} target="_blank" rel="noreferrer" style={{...button,display:'inline-flex',alignItems:'center',textDecoration:'none'}}>Abrir plantilla para imprimir</a>:null}<button type="button" disabled={busy} onClick={()=>void unlink()} style={{...button,borderColor:'#e4c2bf',background:'#fff7f6',color:'#9b4039'}}>Desvincular</button></div></div>:<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><button type="button" style={{...button,background:'#168755',borderColor:'#168755',color:'#fff'}} disabled={busy||!accountConnected} onClick={()=>void openPicker()}>{busy?'Consultando…':'Vincular QR físico'}</button><button type="button" style={button} disabled={busy||!accountConnected} onClick={()=>void openCreate()}>Crear una caja QR nueva</button></div>}
      <div style={{fontSize:11,lineHeight:1.5,color:'#68756e'}}>Para un QR ya impreso, elegí la caja de Mercado Pago que corresponde a ese código. Si no existe, Comercio Lleno puede crear una caja integrada y Mercado Pago devuelve su QR para imprimir.</div>
      {error&&<div style={{padding:11,borderRadius:11,background:'#fff0ef',border:'1px solid #efc5c0',fontSize:11,fontWeight:750,color:'#9b3e37'}}>{error}</div>}
    </div>

    {showPicker&&<div style={{position:'fixed',inset:0,zIndex:10300,background:'rgba(18,32,25,.58)',display:'grid',placeItems:'center',padding:18}} onMouseDown={e=>e.target===e.currentTarget&&setShowPicker(false)}><section style={{width:'min(650px,96vw)',maxHeight:'86vh',overflow:'auto',background:'#fff',borderRadius:22,padding:20}}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><div style={{fontSize:10,fontWeight:950,color:'#168755',letterSpacing:1.2}}>CAJAS DE TU CUENTA</div><h3 style={{margin:'5px 0 4px',fontSize:21}}>¿Qué QR físico querés usar?</h3><p style={{margin:0,fontSize:12,color:'#65736c'}}>Buscamos los puntos de venta creados en Mercado Pago. Elegí el que corresponda al QR que tenés pegado.</p></div><button type="button" onClick={()=>setShowPicker(false)} style={{width:38,height:38,border:'1px solid #dce5e0',borderRadius:11,background:'#fff',fontSize:20}}>×</button></div><div style={{display:'grid',gap:9,marginTop:16}}>{positions.map(pos=><button type="button" key={pos.id} disabled={busy} onClick={()=>void choose(pos)} style={{border:'1px solid #dce7e1',borderRadius:14,background:'#fff',padding:13,textAlign:'left',display:'grid',gridTemplateColumns:'1fr auto',gap:12,cursor:'pointer'}}><span><b>{pos.name}</b><small style={{display:'block',marginTop:4,color:'#6a7770'}}>ID externo {pos.external_id||'sin ID'} · Sucursal {pos.external_store_id||pos.store_id||'—'}</small><small style={{display:'block',marginTop:3,color:'#6a7770'}}>Estado {pos.status||'—'} · {pos.fixed_amount?'Importe fijo/integrado':'Importe abierto'}</small></span>{pos.qr_image?<img src={pos.qr_image} alt="" width={64} height={64}/>:<span style={{fontSize:11,fontWeight:850}}>Seleccionar →</span>}</button>)}{!positions.length&&<div style={{padding:16,borderRadius:12,background:'#f7f9f8',fontSize:12}}>No encontramos cajas QR en esta cuenta. Podés crear una nueva.</div>}</div></section></div>}

    {showCreate&&<div style={{position:'fixed',inset:0,zIndex:10300,background:'rgba(18,32,25,.58)',display:'grid',placeItems:'center',padding:18}} onMouseDown={e=>e.target===e.currentTarget&&setShowCreate(false)}><section style={{width:'min(600px,96vw)',background:'#fff',borderRadius:22,padding:21,display:'grid',gap:13}}><div><div style={{fontSize:10,fontWeight:950,color:'#168755',letterSpacing:1.2}}>NUEVA CAJA QR</div><h3 style={{margin:'5px 0 4px',fontSize:21}}>Crear QR estático integrado</h3><p style={{margin:0,fontSize:12,color:'#65736c'}}>Se crea dentro de una sucursal real de Mercado Pago. Después podés imprimir el código que devuelve Mercado Pago y dejarlo fijo en el mostrador.</p></div><label style={{fontSize:11,fontWeight:850,display:'grid',gap:6}}>Sucursal<select style={input} value={storeId} onChange={e=>{const id=e.target.value;setStoreId(id);setExternalStoreId(stores.find(s=>s.id===id)?.external_id||'')}}>{stores.map(store=><option key={store.id} value={store.id}>{store.name} · {store.external_id}</option>)}</select></label><label style={{fontSize:11,fontWeight:850,display:'grid',gap:6}}>Nombre de caja<input style={input} value={name} onChange={e=>setName(e.target.value)} /></label><label style={{fontSize:11,fontWeight:850,display:'grid',gap:6}}>Identificador interno<input style={input} value={externalId} onChange={e=>setExternalId(e.target.value.replace(/[^A-Za-z0-9]/g,'').slice(0,40))}/><small style={{fontWeight:500,color:'#65736c'}}>Solo letras y números. Mercado Pago exige que sea único.</small></label><div style={{display:'flex',gap:9,justifyContent:'flex-end'}}><button type="button" style={{...button,background:'#fff'}} onClick={()=>setShowCreate(false)}>Cancelar</button><button type="button" style={{...button,background:'#168755',borderColor:'#168755',color:'#fff'}} disabled={busy||!storeId||!externalId||!name.trim()} onClick={()=>void create()}>{busy?'Creando…':'Crear y vincular QR'}</button></div></section></div>}
  </section>
}
