import CommerceApp from './CommerceApp'
import TrialStatus from './TrialStatus'
import SubscriptionGate from './SubscriptionGate'
import AdminPauseGate from './AdminPauseGate'
import FirstStepsExperience from './FirstStepsExperience'
import RedesignBrandOverlay from './RedesignBrandOverlay'
import HeaderRefreshBehavior from './HeaderRefreshBehavior'
import MobileResponsiveFix from './MobileResponsiveFix'
import AdaptiveViewportFix from './AdaptiveViewportFix'
import ViewScrollReset from './ViewScrollReset'
import DesignRuntime from './DesignRuntime'
import DesignLivePreview from './DesignLivePreview'
import ProductPermissionGuard from './ProductPermissionGuard'
import MobileVersionPrompt from './MobileVersionPrompt'
import SessionFetchGuard from './SessionFetchGuard'
import SimpleModeRuntime from './SimpleModeRuntime'
import SimpleModeDarkStyles from './SimpleModeDarkStyles'
import FinanceRuntime from './FinanceRuntime'
import BranchDataScopeRuntime from './BranchDataScopeRuntime'
import BranchTopbarRuntime from './BranchTopbarRuntime'
import BranchSettingsRuntime from './BranchSettingsRuntime'

export const metadata={title:'Comercio Lleno · Rediseño POS',robots:{index:false,follow:false}}
export const dynamic='force-dynamic'
export default function RedesignPage(){const sha=process.env.VERCEL_GIT_COMMIT_SHA||process.env.GIT_COMMIT_SHA||'local',buildVersion=sha==='local'?'local':sha.slice(0,8);return <><BranchDataScopeRuntime/><SessionFetchGuard/><HeaderRefreshBehavior/><MobileResponsiveFix/><AdaptiveViewportFix/><ViewScrollReset/><DesignRuntime/><DesignLivePreview/><ProductPermissionGuard/><MobileVersionPrompt/><RedesignBrandOverlay/><AdminPauseGate/><SubscriptionGate/><TrialStatus/><FirstStepsExperience/><SimpleModeDarkStyles/><SimpleModeRuntime/><FinanceRuntime/><BranchTopbarRuntime/><BranchSettingsRuntime/><CommerceApp buildVersion={buildVersion}/></>}
