'use client'

import { FormEvent,useEffect,useMemo,useState } from 'react'
import PrinterSettingsPanel from './PrinterSettingsPanel'
import UpdatesCenter from './UpdatesCenter'
import core from './page.module.css'
import styles from './settings-next.module.css'
import { resetSalesData,type ArcaHealth,type StaffProfile } from '@/lib/comercio/api'
import { loadDesignSettings,readCachedDesignSettings,saveDesignSettings,type DesignSettings } from '@/lib/comercio/design-settings'
import { loadSalesSettings,readCachedSalesSettings,saveSalesSettings,type SalesSettings } from '@/lib/comercio/sales-settings'
import { createStaffAdmin,deactivateBranch,loadTenantAdmin,saveBranch,saveCompanyAdmin,updateStaffAdmin,type BranchAdmin,type CompanyAdmin,type StaffRole } from '@/lib/comercio/tenant-admin-api'
import { writeDeviceSettings } from '@/lib/comercio/session'
import type { CommerceSnapshot,DeviceSettings,TenantSession,UserPermissions } from '@/lib/comercio/types'

type Props={data:CommerceSnapshot;session:TenantSession;device:DeviceSettings;setDevice:(d:DeviceSettings)=>void;arca:ArcaHealth|null;buildVersion:string;refresh:()=>Promise<void>;message:(m:string)=>void}
type Tab='commerce'|'sales'|'design'|'arca'|'printer'|'stock'|'users'|'updates'|'maintenance'
type PermissionKey=keyof UserPermissions
const countries=['Argentina','Bolivia','Brasil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Guatemala','Honduras','México','Nicaragua','Panamá','Paraguay','Perú','República Dominicana','Uruguay','Venezuela','España']
const provinces=['Ciudad Autónoma de Buenos Aires (CABA)','Buenos Aires','Catamarca','Chaco','Chubut','Córdoba','Corrientes','Entre Ríos','Formosa','Jujuy','La Pampa','La Rioja','Mendoza','Misiones','Neuquén','Río Negro','Salta','San Juan','San Luis','Santa Cruz','Santa Fe','Santiago del Estero','Tierra del Fuego','Tucumán']
const roleLabels:Record<StaffRole,string>={seller:'Vendedor',manager:'Encargado',cashier:'Cajero',supervisor:'Supervisor'}
const permissions:Array<[PermissionKey,string,string]>=[['can_sell','Vender y cobrar','Nueva venta y cobros'],['can_open_close_cash','Abrir y cerrar caja','Apertura, arqueo y cierre'],['can_view_reports','Ver reportes y rentabilidad','Indicadores y reportes'],['can_manage_stock','Administrar stock','Inventario y movimientos'],['can_edit_products','Crear y editar productos','Precios, costos y existencias'],['can_import_export_products','Importar / exportar productos','Archivos Excel'],['can_manage_suppliers','Administrar proveedores','Altas y cambios'],['can_manage_purchases','Registrar compras','Compras y comprobantes'],['can_manage_customers','Administrar clientes','Clientes y cuentas'],['can_edit_customers','Editar clientes','Modificar datos'],['can_delete_customers','Eliminar clientes','Acción sensible'],['can_manage_promotions','Gestionar promociones','Descuentos y 2x1'],['can_manage_finances','Ver y gestionar Finanzas','Gastos internos y resultados'],['can_delete_sales','Eliminar ventas','Acción sensible; no borra ARCA']]
const roleDefaults:Record<StaffRole,UserPermissions>={seller:{can_sell:true,can_manage_customers:true,can_edit_customers:false,can_view_reports:false,can_open_close_cash:false,can_manage_stock:false,can_manage_finances:false},cashier:{can_sell:true,can_open_close_cash:true,can_manage_customers:true,can_view_reports:false,can_manage_stock:false,can_manage_finances:false},manager:{can_sell:true,can_open_close_cash:true,can_view_reports:true,can_manage_stock:true,can_edit_products:true,can_import_export_products:true,can_manage_suppliers:true,can_manage_purchases:true,can_manage_customers:true,can_edit_customers:true,can_manage_promotions:true,can_manage_finances:true},supervisor:{can_sell:true,can_open_close_cash:true,can_view_reports:true,can_manage_stock:true,can_edit_products:true,can_import_export_products:true,can_manage_suppliers:true,can_manage_purchases:true,can_manage_customers:true,can_edit_customers:true,can_manage_promotions:true,can_manage_finances:true,can_delete_sales:false,can_delete_customers:false}}
const strongPassword=(v:string)=>v.length>=8&&/[A-Z]/.test(v)&&/\d/.test(v)&&/[^A-Za-z0-9]/.test(v)

export default function SettingsTenantNext(props:Props){
  const{data,session,device,setDevice,arca,buildVersion,refresh,message}=props,owner=session.role==='owner'
  const[tab,setTab]=useState<Tab>('commerce'),[company,setCompany]=useState<CompanyAdmin>({id:session.companyId,name:data.company.name,tax_id:data.company.tax_id||'',country:'Argentina',province:'',owner_phone:''}),[branches,setBranches]=useState<BranchAdmin[]>([]),[staff,setStaff]=useState<StaffProfile[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[branchModal,setBranchModal]=useState(false),[staffModal,setStaffModal]=useState(false)
  async function reload(){setLoading(true);try{const x=await loadTenantAdmin(session);if(x.company)setCompany(x.company);setBranches(x.branches);setStaff(x.staff)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setLoading(false)}}
  useEffect(()=>{void reload()},[session.companyId])
  async function saveCommerce(){setError('');const complete=Boolean(company.name.trim()&&String(company.tax_id||'').trim()&&String(company.country||'').trim()&&(company.country!=='Argentina'||String(company.province||'').trim()));try{await saveCompanyAdmin(session,{name:company.name.trim(),legal_name:company.legal_name||company.name.trim(),tax_id:company.tax_id||null,owner_phone:company.owner_phone||null,country:company.country||null,province:company.country==='Argentina'?company.province||null:null,address:company.address||null,onboarding_complete:complete});await refresh();message(complete?'Datos del comercio guardados. Configuración inicial completa.':'Datos guardados. Todavía faltan datos obligatorios para completar la configuración.');await reload()}catch(e){setError(e instanceof Error?e.message:String(e))}}
  const tabs:Array<[Tab,string]>=owner?[['commerce','Comercio'],['sales','Ventas y caja'],['design','Diseño'],['arca','ARCA'],['printer','Impresora y tickets'],['stock','Stock'],['users','Usuarios'],['updates','Actualizaciones'],['maintenance','Mantenimiento']]:[['commerce','Comercio'],['sales','Ventas y caja'],['printer','Impresora y tickets'],['stock','Stock']]
  return <><div className={core.pageHead}><div><div className={core.eyebrow}>ADMINISTRACIÓN</div><h1>Configuración</h1><p>Comercio, sucursales, caja, facturación, hardware, usuarios y funciones.</p></div></div><div className={styles.tabs}>{tabs.map(([k,l])=><button key={k} className={tab===k?styles.active:''} onClick={()=>setTab(k)}>{l}</button>)}</div>{error&&<div className={styles.error}>{error}</div>}
    {tab==='commerce'&&<section className={styles.panel}><div className={styles.title}><div><h3>Datos del comercio</h3><p>Estos datos identifican al local y se usan también en tickets y funciones de WhatsApp.</p></div>{company.onboarding_complete===false&&<span className={styles.pending}>Configuración pendiente</span>}</div><div className={styles.grid}><label>Nombre del local *<input value={company.name||''} onChange={e=>setCompany({...company,name:e.target.value})}/></label><label>CUIT / CUIL *<input value={company.tax_id||''} onChange={e=>setCompany({...company,tax_id:e.target.value})} placeholder="Sólo números o formato habitual"/></label><label>País *<select value={company.country||''} onChange={e=>setCompany({...company,country:e.target.value,province:e.target.value==='Argentina'?company.province:''})}><option value="">Seleccionar…</option>{countries.map(x=><option key={x}>{x}</option>)}</select></label>{company.country==='Argentina'?<label>Provincia *<select value={company.province||''} onChange={e=>setCompany({...company,province:e.target.value})}><option value="">Seleccionar…</option>{provinces.map(x=><option key={x}>{x}</option>)}</select></label>:<label>Provincia / región<input value={company.province||''} onChange={e=>setCompany({...company,province:e.target.value})}/></label>}<label>WhatsApp del propietario<input value={company.owner_phone||''} onChange={e=>setCompany({...company,owner_phone:e.target.value})} placeholder="Ej: +54 9 11…"/><small>Se usa para Pedido IA+ y cierres de caja; no es el número de Ayuda humana.</small></label><label>Dirección<input value={company.address||''} onChange={e=>setCompany({...company,address:e.target.value})} placeholder="Opcional · para tickets"/></label></div><div className={styles.saveRow}><small>* Obligatorio para completar la configuración inicial.</small><button className={styles.primary} onClick={()=>void saveCommerce()}>Guardar comercio</button></div><div className={styles.subhead}><div><h3>Sucursales</h3><p>Si tenés un solo local, el local principal ya funciona como única sucursal.</p></div>{owner&&<button onClick={()=>setBranchModal(true)}>+ Agregar sucursal</button>}</div><div className={styles.branchList}>{branches.map(b=><div className={styles.branch} key={b.id}><div><b>{b.name}</b><small>{b.is_primary?'Local principal':b.address||'Sin dirección cargada'}</small></div>{!b.is_primary&&owner&&<button onClick={async()=>{if(confirm('¿Desactivar esta sucursal?')){await deactivateBranch(session,b.id);await reload()}}}>Desactivar</button>}</div>)}</div></section>}
    {tab==='sales'&&<SalesPanel session={session} message={message}/>} {tab==='design'&&owner&&<DesignPanel session={session} message={message}/>} {tab==='arca'&&<section className={styles.panel}><h3>ARCA / Facturación electrónica</h3><p>Estado fiscal actual del comercio.</p><div className={styles.lines}><div><span>Conexión</span><b>{arca?.connected?'Conectado':'Desconectado'}</b></div><div><span>Servicio</span><b>{arca?.service||'wsfev1'}</b></div><div><span>Punto de venta</span><b>{arca?.pointOfSale??'—'}</b></div><div><span>Entorno</span><b>{arca?.environment||'homologación'}</b></div></div></section>}
    {tab==='printer'&&<PrinterSettingsPanel company={data.company} device={device} onSave={next=>{writeDeviceSettings(session.companyId,next);setDevice(next)}} message={message}/>} {tab==='stock'&&<StockPanel/>}
    {tab==='users'&&owner&&<section className={styles.panel}><div className={styles.title}><div><h3>Usuarios, roles y funciones</h3><p>El Propietario crea los accesos y decide exactamente qué puede hacer cada persona.</p></div><button className={styles.primary} onClick={()=>setStaffModal(true)}>+ Crear usuario</button></div><div className={styles.staffList}>{staff.filter(x=>x.role!=='owner').map(x=><StaffEditor key={x.id} staff={x} session={session} saved={reload} message={message}/>)}</div></section>}
    {tab==='updates'&&owner&&<UpdatesCenter session={session} buildVersion={buildVersion} message={message}/>} {tab==='maintenance'&&owner&&<Maintenance session={session} message={message}/>}<div className={styles.version}>Comercio Lleno · build {buildVersion} · tenant {session.companyId.slice(0,8)}</div>
    {branchModal&&<BranchModal session={session} company={company} close={()=>setBranchModal(false)} saved={async()=>{setBranchModal(false);await reload()}}/>}{staffModal&&<NewStaff session={session} close={()=>setStaffModal(false)} saved={async()=>{setStaffModal(false);await reload()}}/>}
  </>
}

function SalesPanel({session,message}:{session:TenantSession;message:(m:string)=>void}){const[value,setValue]=useState<SalesSettings>(()=>readCachedSalesSettings(session.companyId)),[busy,setBusy]=useState(false);useEffect(()=>{loadSalesSettings(session).then(setValue).catch(()=>{})},[session.companyId]);async function save(){setBusy(true);try{setValue(await saveSalesSettings(session,value));message('Ajustes de ventas y caja guardados.')}catch(e){message(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}return <section className={styles.panel}><h3>Ventas y caja</h3><label className={styles.switch}><span><b>Permitir vender sin stock</b><small>El stock no baja de 0.</small></span><input type="checkbox" checked={value.allowNegativeStock} onChange={e=>setValue({...value,allowNegativeStock:e.target.checked})}/></label><label>Descuento máximo (%)<input type="number" min="0" max="100" value={value.maxDiscount} onChange={e=>setValue({...value,maxDiscount:Math.max(0,Math.min(100,Number(e.target.value)||0))})}/></label><div className={styles.choice}><button className={value.timeFormat==='24'?styles.selected:''} onClick={()=>setValue({...value,timeFormat:'24'})}>24 horas</button><button className={value.timeFormat==='12'?styles.selected:''} onClick={()=>setValue({...value,timeFormat:'12'})}>12 horas</button></div><div className={styles.saveRow}><span/><button className={styles.primary} disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Guardar ajustes'}</button></div></section>}
function DesignPanel({session,message}:{session:TenantSession;message:(m:string)=>void}){const[value,setValue]=useState<DesignSettings>(()=>readCachedDesignSettings(session.companyId));useEffect(()=>{loadDesignSettings(session).then(setValue).catch(()=>{})},[session.companyId]);async function save(){try{setValue(await saveDesignSettings(session,value));message('Diseño guardado.')}catch(e){message(e instanceof Error?e.message:String(e))}}return <section className={styles.panel}><h3>Diseño</h3><p>Tamaño, grosor y tipografía se guardan por comercio.</p><div className={styles.choice}><button className={value.fontSize==='compact'?styles.selected:''} onClick={()=>setValue({...value,fontSize:'compact'})}>Compacto</button><button className={value.fontSize==='standard'?styles.selected:''} onClick={()=>setValue({...value,fontSize:'standard'})}>Equilibrado</button><button className={value.fontSize==='large'?styles.selected:''} onClick={()=>setValue({...value,fontSize:'large'})}>Grande</button></div><div className={styles.choice}><button className={value.fontWeight==='soft'?styles.selected:''} onClick={()=>setValue({...value,fontWeight:'soft'})}>Suave</button><button className={value.fontWeight==='balanced'?styles.selected:''} onClick={()=>setValue({...value,fontWeight:'balanced'})}>Equilibrado</button><button className={value.fontWeight==='strong'?styles.selected:''} onClick={()=>setValue({...value,fontWeight:'strong'})}>Fuerte</button></div><div className={styles.choice}><button className={value.fontFamily==='modern'?styles.selected:''} onClick={()=>setValue({...value,fontFamily:'modern'})}>Moderna</button><button className={value.fontFamily==='classic'?styles.selected:''} onClick={()=>setValue({...value,fontFamily:'classic'})}>Clásica</button></div><div className={styles.saveRow}><span/><button className={styles.primary} onClick={()=>void save()}>Guardar diseño</button></div></section>}
function StockPanel(){const[low,setLow]=useState(5);useEffect(()=>{try{setLow(Number(JSON.parse(localStorage.getItem('cl_settings')||'{}')?.stock?.low??5))}catch{}},[]);function save(){let all:any={};try{all=JSON.parse(localStorage.getItem('cl_settings')||'{}')}catch{};all.stock={...(all.stock||{}),low};localStorage.setItem('cl_settings',JSON.stringify(all))}return <section className={styles.panel}><h3>Stock e inventario</h3><label>Avisar stock bajo desde<input type="number" min="0" value={low} onChange={e=>setLow(Math.max(0,Number(e.target.value)||0))}/></label><div className={styles.saveRow}><span/><button className={styles.primary} onClick={save}>Guardar</button></div></section>}

function StaffEditor({staff,session,saved,message}:{staff:StaffProfile;session:TenantSession;saved:()=>Promise<void>;message:(m:string)=>void}){const[open,setOpen]=useState(false),[role,setRole]=useState<StaffRole>((['seller','manager','cashier','supervisor'].includes(staff.role)?staff.role:'cashier') as StaffRole),[p,setP]=useState<UserPermissions>(staff.permissions||{}),[busy,setBusy]=useState(false);const enabled=Object.values(p).filter(Boolean).length;async function save(){setBusy(true);try{await updateStaffAdmin(session,staff.id,role,p,staff.active!==false);await saved();setOpen(false);message('Rol y funciones guardados.')}catch(e){message(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}return <><div className={styles.staff}><div><b>{staff.full_name||staff.username}</b><small>{staff.username}</small></div><div><b>{roleLabels[role]}</b><small>{enabled} funciones activas</small></div><button onClick={()=>setOpen(true)}>Editar</button></div>{open&&<div className={styles.modal}><div className={styles.card}><div className={styles.modalHead}><div><span>ROL Y FUNCIONES</span><h3>{staff.full_name||staff.username}</h3></div><button onClick={()=>setOpen(false)}>×</button></div><label>Rol<select value={role} onChange={e=>{const r=e.target.value as StaffRole;setRole(r);setP({...roleDefaults[r]})}}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><PermissionList value={p} onChange={setP}/><div className={styles.modalActions}><button onClick={()=>setOpen(false)}>Cancelar</button><button className={styles.primary} disabled={busy} onClick={()=>void save()}>{busy?'Guardando…':'Guardar rol y funciones'}</button></div></div></div>}</>}
function PermissionList({value,onChange}:{value:UserPermissions;onChange:(v:UserPermissions)=>void}){return <div className={styles.permissions}>{permissions.map(([k,l,h])=><label key={String(k)}><input type="checkbox" checked={value[k]===true} onChange={e=>onChange({...value,[k]:e.target.checked})}/><span><b>{l}</b><small>{h}</small></span></label>)}</div>}
function NewStaff({session,close,saved}:{session:TenantSession;close:()=>void;saved:()=>Promise<void>}){const[name,setName]=useState(''),[username,setUsername]=useState(''),[password,setPassword]=useState(''),[role,setRole]=useState<StaffRole>('seller'),[p,setP]=useState<UserPermissions>({...roleDefaults.seller}),[busy,setBusy]=useState(false),[error,setError]=useState('');const secure=strongPassword(password);async function submit(e:FormEvent){e.preventDefault();if(!username.trim()||!secure){setError('La contraseña debe tener mínimo 8 caracteres, una mayúscula, un número y un signo especial.');return}setBusy(true);setError('');try{await createStaffAdmin(session,{username,password,full_name:name,role,permissions:p});await saved()}catch(e){setError(e instanceof Error?e.message:String(e));setBusy(false)}}return <div className={styles.modal}><form className={styles.card} onSubmit={submit}><div className={styles.modalHead}><div><span>NUEVO USUARIO</span><h3>Crear acceso del comercio</h3></div><button type="button" onClick={close}>×</button></div><div className={styles.grid}><label>Nombre<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Usuario<input required value={username} onChange={e=>setUsername(e.target.value)} placeholder="ej: caja1"/></label><label>Contraseña<input required type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="8+ · Mayúscula · número · signo"/><small className={secure?styles.ok:styles.help}>Ejemplo válido: Comercio#2026</small></label><label>Rol<select value={role} onChange={e=>{const r=e.target.value as StaffRole;setRole(r);setP({...roleDefaults[r]})}}>{Object.entries(roleLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div><h4>Funciones</h4><PermissionList value={p} onChange={setP}/>{error&&<div className={styles.error}>{error}</div>}<div className={styles.modalActions}><button type="button" onClick={close}>Cancelar</button><button className={styles.primary} disabled={busy||!secure}>{busy?'Creando…':'Crear usuario'}</button></div></form></div>}
function BranchModal({session,company,close,saved}:{session:TenantSession;company:CompanyAdmin;close:()=>void;saved:()=>Promise<void>}){const[name,setName]=useState(''),[address,setAddress]=useState('');async function submit(e:FormEvent){e.preventDefault();await saveBranch(session,{name,address,country:company.country,province:company.province,is_primary:false});await saved()}return <div className={styles.modal}><form className={styles.card} onSubmit={submit}><div className={styles.modalHead}><div><span>SUCURSAL</span><h3>Nueva sucursal</h3></div><button type="button" onClick={close}>×</button></div><label>Nombre<input required value={name} onChange={e=>setName(e.target.value)} placeholder="Ej: Sucursal Centro"/></label><label>Dirección<input value={address} onChange={e=>setAddress(e.target.value)}/></label><div className={styles.modalActions}><button type="button" onClick={close}>Cancelar</button><button className={styles.primary}>Crear sucursal</button></div></form></div>}
function Maintenance({session,message}:{session:TenantSession;message:(m:string)=>void}){const[password,setPassword]=useState(''),[busy,setBusy]=useState(false);return <section className={`${styles.panel} ${styles.danger}`}><h3>Restablecer ventas</h3><p>Pone en cero ventas, reportes e historial de ventas. No modifica productos ni clientes.</p><label>Contraseña del propietario<input type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy||!password} onClick={async()=>{if(!confirm('Esta acción no se puede deshacer. ¿Continuar?'))return;setBusy(true);try{await resetSalesData(session,password);message('Ventas restablecidas.')}catch(e){message(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}}>Restablecer ventas a cero</button></section>}
