'use client'
import {FormEvent,useEffect,useState} from 'react'
import type {TenantSession} from '@/lib/comercio/types'

type Props={session:TenantSession;message:(m:string)=>void}
type Msg={id:string;direction:'inbound'|'outbound'|'system';body:string;created_at:string}
type State={feature?:{aiSellerEntitled?:boolean;aiSellerEnabled?:boolean;company?:{name?:string}};conversation?:{status?:string;cart?:{items?:any[]}}|null;messages?:Msg[];orders?:Array<{id:string;status:string;total:number;sale_id?:string|null;created_at:string}>}
async function api(session:TenantSession,payload:Record<string,unknown>){const r=await fetch('/api/redesign/whatsapp/seller',{method:'POST',headers:{Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Error ${r.status}`);return d}
export default function WhatsAppAiSellerPanel({session,message}:Props){
  const[phone,setPhone]=useState(''),[text,setText]=useState(''),[state,setState]=useState<State>({}),[busy,setBusy]=useState(false),[commitSale,setCommitSale]=useState(false)
  async function load(value=phone){try{const d=await api(session,{action:'state',phone:value});setState(d)}catch(e){message(e instanceof Error?e.message:String(e))}}
  useEffect(()=>{void load('')},[session.companyId])
  async function submit(e?:FormEvent){e?.preventDefault();if(!phone.trim()||!text.trim()||busy)return;setBusy(true);try{const d=await api(session,{action:'message',phone,text,commitSale});setText('');message(d?.committed?'Venta de prueba creada desde Vendedor IA.':'Vendedor IA respondió correctamente.');await load(phone)}catch(e){message(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  async function reset(){if(!phone.trim()||busy)return;setBusy(true);try{await api(session,{action:'reset',phone});await load(phone);message('Conversación de prueba reiniciada.')}catch(e){message(e instanceof Error?e.message:String(e))}finally{setBusy(false)}}
  const entitled=state.feature?.aiSellerEntitled===true,enabled=state.feature?.aiSellerEnabled===true,messages=state.messages||[],items=state.conversation?.cart?.items||[]
  return <section style={{border:'1px solid #dfe7e3',borderRadius:14,padding:16,display:'grid',gap:14}}>
    <div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',gap:12,flexWrap:'wrap'}}><div><div style={{fontSize:11,fontWeight:950,letterSpacing:'.09em',color:'#168a55'}}>S PLUS · NUEVA FUNCIÓN</div><h3 style={{margin:'5px 0 6px'}}>🤖 Vendedor IA WhatsApp</h3><p style={{margin:0,opacity:.72,lineHeight:1.5,maxWidth:760}}>Laboratorio Preview con catálogo real. Interpreta el pedido, consulta stock/precio, arma carrito y exige confirmación explícita.</p></div><span style={{padding:'7px 10px',borderRadius:999,fontSize:10,fontWeight:950,background:entitled&&enabled?'#e8f8ee':'#fff4df',color:entitled&&enabled?'#147244':'#926000'}}>{!entitled?'BLOQUEADO POR PLAN':enabled?'ACTIVO':'CONTRATADO · APAGADO'}</span></div>
    {!entitled?<div style={{padding:13,borderRadius:11,background:'#fff8e8'}}>🔒 Este comercio no tiene habilitado <b>Vendedor IA WhatsApp · S Plus</b>. Activá el módulo desde Central Llena.</div>:!enabled?<div style={{padding:13,borderRadius:11,background:'#fff8e8'}}>El módulo está contratado pero apagado. Activá “Vendedor IA WhatsApp” en las automatizaciones de arriba.</div>:<>
      <div style={{display:'grid',gridTemplateColumns:'minmax(180px,.7fr) 1.3fr',gap:10}}><label style={{fontSize:11,fontWeight:800}}>Cliente de prueba<input value={phone} onChange={e=>setPhone(e.target.value)} onBlur={()=>void load(phone)} placeholder="54911..." style={{display:'block',width:'100%',marginTop:5,padding:'10px 11px',border:'1px solid #ccd8d2',borderRadius:9,background:'transparent',color:'inherit'}}/></label><div style={{fontSize:11,opacity:.68,alignSelf:'end',paddingBottom:10}}>Usá tu número o uno de prueba. La conversación queda aislada por comercio + teléfono.</div></div>
      <div style={{minHeight:180,maxHeight:360,overflow:'auto',border:'1px solid #e1e8e4',borderRadius:12,padding:12,background:'rgba(247,250,248,.55)',display:'grid',gap:8}}>{messages.length?messages.map(m=><div key={m.id} style={{justifySelf:m.direction==='inbound'?'start':'end',maxWidth:'86%',padding:'9px 11px',borderRadius:12,background:m.direction==='inbound'?'#fff':'#e7f7ee',border:'1px solid #dbe6e0',whiteSpace:'pre-wrap',fontSize:12,lineHeight:1.45}}><b style={{display:'block',fontSize:9,opacity:.55,marginBottom:3}}>{m.direction==='inbound'?'CLIENTE':'VENDEDOR IA'}</b>{m.body}</div>):<div style={{placeSelf:'center',opacity:.55,textAlign:'center'}}>Escribí abajo como si fueras un cliente de WhatsApp.<br/>Ejemplo: “Hola, necesito desodorante de piso y acondicionador de pelo”.</div>}</div>
      {items.length>0&&<div style={{padding:11,borderRadius:10,border:'1px solid #cfe5d8',background:'#f0faf4'}}><b>Carrito actual</b><div style={{fontSize:11,marginTop:5,opacity:.75}}>{items.map((i:any)=>`${i.qty} × ${i.name}`).join(' · ')}</div></div>}
      <form onSubmit={submit} style={{display:'grid',gridTemplateColumns:'1fr auto',gap:8}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="Escribí como cliente…" disabled={busy} style={{padding:'11px 12px',border:'1px solid #ccd8d2',borderRadius:10,background:'transparent',color:'inherit'}}/><button disabled={busy||!phone.trim()||!text.trim()} style={{border:0,borderRadius:10,padding:'11px 16px',background:'#168a55',color:'#fff',fontWeight:900}}>{busy?'Pensando…':'Enviar'}</button></form>
      <div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{['Hola, necesito desodorante de piso y acondicionador de pelo','agregame dos lavandinas','¿qué llevo?','CONFIRMAR'].map(example=><button type="button" key={example} onClick={()=>setText(example)} style={{border:'1px solid #d9e4de',borderRadius:999,padding:'6px 9px',background:'transparent',color:'inherit',fontSize:10}}>{example}</button>)}</div>
      <label style={{display:'flex',alignItems:'flex-start',gap:9,padding:10,borderRadius:10,background:commitSale?'#fff0e8':'#f6f8f7',fontSize:11,lineHeight:1.45}}><input type="checkbox" checked={commitSale} onChange={e=>setCommitSale(e.target.checked)} style={{marginTop:2}}/><span><b>Permitir venta real al escribir CONFIRMAR</b><br/><span style={{opacity:.68}}>Apagado = modo seguro: confirma el pedido pero no descuenta stock. Encendido = crea “Pedido WhatsApp” y descuenta stock de verdad.</span></span></label>
      <div style={{display:'flex',justifyContent:'space-between',gap:8,alignItems:'center',flexWrap:'wrap'}}><small style={{opacity:.62}}>Webhook real preparado aparte. En Preview usamos este laboratorio porque el deployment está protegido.</small><button type="button" disabled={busy||!phone.trim()} onClick={()=>void reset()} style={{border:'1px solid #ccd8d2',borderRadius:9,padding:'8px 10px',background:'transparent',color:'inherit',fontWeight:800}}>Reiniciar prueba</button></div>
      {(state.orders||[]).length>0&&<div style={{borderTop:'1px solid #e1e8e4',paddingTop:10}}><b style={{fontSize:11}}>Pedidos de esta conversación</b>{(state.orders||[]).slice(0,4).map(o=><div key={o.id} style={{display:'flex',justifyContent:'space-between',gap:10,padding:'7px 0',fontSize:10}}><span>#{o.id.slice(0,8).toUpperCase()} · {o.status}</span><strong>${Number(o.total||0).toLocaleString('es-AR')}</strong></div>)}</div>}
    </>}
  </section>
}
