'use client'

import { FormEvent,useEffect,useState } from 'react'
import { signInTenant } from '@/lib/comercio/session'
import styles from './FacturaLlenaLanding.module.css'

type DeferredPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>}

export default function FacturaLlenaLanding(){
 const[loginOpen,setLoginOpen]=useState(false),[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
 const[installPrompt,setInstallPrompt]=useState<DeferredPrompt|null>(null),[device,setDevice]=useState<'android'|'ios'>('android')
 useEffect(()=>{const h=(e:Event)=>{e.preventDefault();setInstallPrompt(e as DeferredPrompt)};window.addEventListener('beforeinstallprompt',h);if(/iPhone|iPad|iPod/i.test(navigator.userAgent))setDevice('ios');return()=>window.removeEventListener('beforeinstallprompt',h)},[])
 async function login(e:FormEvent){e.preventDefault();if(!identifier.trim()||!password)return;setBusy(true);setError('');try{await signInTenant(identifier,password);window.location.reload()}catch(e){setError(e instanceof Error?e.message:'No se pudo ingresar.')}finally{setBusy(false)}}
 async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);return}document.getElementById('instalar')?.scrollIntoView({behavior:'smooth'})}
 return <main className={styles.page}>
  <nav className={styles.nav}><div className={styles.brand}>FacturaLlena</div><div className={styles.navCenter}><a href="#como-funciona">Cómo funciona</a><a href="#planes">Planes</a><a href="#instalar">Instalar</a></div><div className={styles.navAction}><button className={styles.ghost} onClick={()=>setLoginOpen(true)}>Ingresar</button><button className={styles.solid} onClick={()=>void install()}>Instalar app</button></div></nav>

  <section className={styles.hero}>
   <div className={styles.copy}><div className={styles.eyebrow}><i/> FACTURACIÓN ELECTRÓNICA · ARCA</div><h1>Facturá.<span>Mandala. Listo.</span></h1><p>Emití Facturas C desde el celular, obtené el CAE y compartí el comprobante por WhatsApp o mail en segundos.</p><div className={styles.heroButtons}><button className={styles.heroPrimary} onClick={()=>void install()}>Instalar FacturaLlena</button><button className={styles.heroSecondary} onClick={()=>setLoginOpen(true)}>Ya tengo cuenta</button></div><div className={styles.micro}><span><b>ARCA</b> conectado</span><span><b>PDF + QR</b> fiscal</span><span><b>WhatsApp</b> desde tu teléfono</span></div></div>
   <div className={styles.visual}><div className={styles.photo}><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1400&q=86" alt="Persona cobrando desde un celular"/><div className={styles.photoCopy}><small>TODO DESDE EL CELULAR</small><b>Facturá donde estés.</b></div></div><div className={styles.phone}><div className={styles.phoneTop}><span>12:37</span><b>FacturaLlena</b><span>61%</span></div><div className={styles.phoneBody}><small>NUEVA FACTURA C</small><h3>¿Qué facturamos?</h3><div className={styles.field}>Consumidor final</div><div className={styles.field}>Productos varios</div><div className={styles.amount}>$ 4.500</div><div className={styles.phoneCta}>Emitir factura</div></div></div></div>
  </section>

  <section className={styles.steps} id="como-funciona"><div className={styles.sectionHead}><span>3 PASOS</span><h2>Menos sistema.<br/>Más simple.</h2><p>No necesitás aprender un software enorme para hacer una factura.</p></div><div className={styles.stepGrid}><article className={styles.step}><em>01</em><h3>Cargá</h3><p>Cliente, concepto e importe. Nada más para empezar.</p></article><article className={styles.step}><em>02</em><h3>Emití</h3><p>FacturaLlena consulta ARCA y obtiene el CAE real.</p></article><article className={styles.step}><em>03</em><h3>Compartí</h3><p>Mandá el PDF fiscal por WhatsApp, mail o cualquier app del teléfono.</p></article></div></section>

  <section className={styles.proof}><div className={styles.proofPhoto}><img src="https://images.unsplash.com/photo-1556740758-90de374c12ad?auto=format&fit=crop&w=1400&q=86" alt="Persona usando un celular para cobrar"/></div><div className={styles.proofCopy}><span>PENSADA PARA UNA MANO</span><h2>Una app que no molesta.</h2><p>La acción principal queda cerca del pulgar. Sin menús eternos ni pantallas llenas de opciones que no usás.</p><div className={styles.features}><div className={styles.feature}><b>Factura C + CAE</b><small>Autorización real de ARCA</small></div><div className={styles.feature}><b>PDF fiscal + QR</b><small>Listo para enviar</small></div><div className={styles.feature}><b>Historial</b><small>Volvé a compartir cuando quieras</small></div><div className={styles.feature}><b>WhatsApp y mail</b><small>Usa las apps de tu teléfono</small></div></div></div></section>

  <section className={styles.pricing} id="planes"><span>PLANES EN PESOS ARGENTINOS</span><h2>Pagá sólo lo que necesitás.</h2><p>Podés empezar gratis y subir de plan cuando tu facturación crece.</p><div className={styles.plans}><article className={styles.plan}><small>INICIO</small><strong>$0</strong><em>por mes</em><p>Hasta 20 comprobantes mensuales para probar FacturaLlena.</p><button onClick={()=>void install()}>Empezar gratis</button></article><article className={`${styles.plan} ${styles.featured}`}><div className={styles.tag}>MÁS ELEGIDO</div><small>EMPRENDEDOR</small><strong>$8.900</strong><em>por mes</em><p>Hasta 200 comprobantes por mes. Ideal para profesionales y pequeños negocios.</p><button onClick={()=>void install()}>Elegir Emprendedor</button></article><article className={styles.plan}><small>NEGOCIO</small><strong>$14.900</strong><em>por mes</em><p>Hasta 1.000 comprobantes por mes para operaciones con más movimiento.</p><button onClick={()=>void install()}>Elegir Negocio</button></article></div></section>

  <section className={styles.install} id="instalar"><div><span>INSTALALA COMO APP</span><h2>Está a un toque.</h2><p>No hace falta esperar a Play Store o App Store. FacturaLlena ya se puede instalar en la pantalla de inicio y abrir como una app.</p><p className={styles.iosNote}>En Android funciona como PWA instalable. En iPhone se agrega desde Safari a la pantalla de inicio.</p></div><div className={styles.installCard}><div className={styles.deviceTabs}><button className={device==='android'?styles.active:''} onClick={()=>setDevice('android')}>Android</button><button className={device==='ios'?styles.active:''} onClick={()=>setDevice('ios')}>iPhone</button></div>{device==='android'?<div className={styles.installSteps}><div className={styles.installRow}><b>1</b><div><strong>Abrí FacturaLlena en Chrome</strong><small>Entrá desde tu celular Android.</small></div></div><div className={styles.installRow}><b>2</b><div><strong>Tocá “Instalar app”</strong><small>Si Chrome no muestra el aviso, usá el menú ⋮.</small></div></div><div className={styles.installRow}><b>3</b><div><strong>Queda en tu pantalla principal</strong><small>La próxima vez abre como una app.</small></div></div></div>:<div className={styles.installSteps}><div className={styles.installRow}><b>1</b><div><strong>Abrí FacturaLlena en Safari</strong><small>En iPhone usá Safari para instalarla.</small></div></div><div className={styles.installRow}><b>2</b><div><strong>Tocá Compartir</strong><small>Buscá “Agregar a pantalla de inicio”.</small></div></div><div className={styles.installRow}><b>3</b><div><strong>Confirmá “Agregar”</strong><small>FacturaLlena queda como acceso directo tipo app.</small></div></div></div>}<button className={styles.installAction} onClick={()=>void install()}>Instalar FacturaLlena</button></div></section>

  <section className={styles.final}><h2>Facturar debería sentirse así de fácil.</h2><p>ARCA por detrás. Simplicidad adelante.</p><button onClick={()=>void install()}>Instalar gratis</button></section>
  <footer className={styles.footer}><b>FacturaLlena</b><small>Un producto de Llena Group</small><span>Facturación electrónica simple para Argentina.</span></footer>

  {loginOpen&&<div className={styles.loginOverlay} onClick={e=>{if(e.currentTarget===e.target)setLoginOpen(false)}}><form className={styles.loginCard} onSubmit={login}><div className={styles.loginTop}><b>FacturaLlena</b><button type="button" onClick={()=>setLoginOpen(false)}>×</button></div><h3>Entrá a tu cuenta.</h3><label>Email o usuario<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoComplete="username"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className={styles.loginError}>{error}</div>}<button className={styles.loginButton} disabled={busy}>{busy?'Ingresando…':'Ingresar'}</button></form></div>}
 </main>
}
