'use client'

import { FormEvent, useEffect, useMemo, useState } from 'react'
import Link from 'next/link'
import { readTenantSession, signInTenant } from '@/lib/comercio/session'
import type { TenantSession } from '@/lib/comercio/types'
import { buildFacturaCPdf, type FiscalPdfIssuer } from '@/lib/factura-llena/pdf'
import styles from './factura-llena.module.css'

type DeferredPrompt=Event&{prompt:()=>Promise<void>;userChoice:Promise<{outcome:'accepted'|'dismissed'}>}
type FiscalStatus={configured:boolean;environment?:'homologacion'|'produccion';tax_id?:string|null;point_of_sale?:number|null}
type Invoice={receipt_number:number;cae:string;cae_expiration:string;date:string;amount:number}
type ReceiptSettings=Record<string,unknown>&{receiptAddress?:string;fiscalVatCondition?:string;grossIncome?:string;activityStartDate?:string}
type Issuer=FiscalPdfIssuer&{receiptSettings:ReceiptSettings}

const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
const money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0})
function requestId(){return globalThis.crypto?.randomUUID?.()??`${Date.now()}-${Math.random()}`}
function digits(v:string){return v.replace(/\D/g,'')}

export default function FacturaLlenaPreview(){
  const[session,setSession]=useState<TenantSession|null>(null),[ready,setReady]=useState(false)
  const[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[loginBusy,setLoginBusy]=useState(false)
  const[amount,setAmount]=useState(''),[client,setClient]=useState('Consumidor final'),[concept,setConcept]=useState('')
  const[fiscal,setFiscal]=useState<FiscalStatus|null>(null),[issuer,setIssuer]=useState<Issuer|null>(null)
  const[statusBusy,setStatusBusy]=useState(false),[emitBusy,setEmitBusy]=useState(false),[profileBusy,setProfileBusy]=useState(false),[shareBusy,setShareBusy]=useState(false)
  const[error,setError]=useState(''),[invoice,setInvoice]=useState<Invoice|null>(null),[installPrompt,setInstallPrompt]=useState<DeferredPrompt|null>(null)
  const[grossIncome,setGrossIncome]=useState(''),[activityStart,setActivityStart]=useState('')

  useEffect(()=>{setSession(readTenantSession());setReady(true);const h=(e:Event)=>{e.preventDefault();setInstallPrompt(e as DeferredPrompt)};window.addEventListener('beforeinstallprompt',h);return()=>window.removeEventListener('beforeinstallprompt',h)},[])
  useEffect(()=>{if(session)void loadAccount(session)},[session?.companyId,session?.token])
  const total=useMemo(()=>Number(digits(amount))||0,[amount])
  const profileComplete=Boolean(issuer?.legalName&&issuer?.taxId&&issuer?.address&&issuer?.grossIncome&&issuer?.activityStart)

  async function install(){if(installPrompt){await installPrompt.prompt();await installPrompt.userChoice;setInstallPrompt(null);return}alert('En Android: abrí el menú del navegador y elegí “Agregar a pantalla de inicio” o “Instalar app”.')}
  async function login(e:FormEvent){e.preventDefault();if(!identifier.trim()||!password)return;setLoginBusy(true);setError('');try{setSession(await signInTenant(identifier,password))}catch(e){setError(e instanceof Error?e.message:'No se pudo ingresar.')}finally{setLoginBusy(false)}}

  async function setupRequest(s:TenantSession,body:Record<string,unknown>){const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-setup`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${s.token}`,'Content-Type':'application/json'},body:JSON.stringify(body),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d?.ok===false)throw new Error(d?.error||'No se pudo consultar ARCA.');return d}
  async function loadAccount(s=session){if(!s)return;setStatusBusy(true);setError('');try{const[d,cr]=await Promise.all([setupRequest(s,{action:'status'}),fetch(`${SUPABASE_URL}/rest/v1/companies?id=eq.${encodeURIComponent(s.companyId)}&select=name,legal_name,tax_id,address,receipt_settings&limit=1`,{headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${s.token}`},cache:'no-store'})]);const ca=await cr.json().catch(()=>[]);if(!cr.ok||!ca?.[0])throw new Error('No se pudieron cargar los datos fiscales del comercio.');const c=ca[0],rs=(c.receipt_settings||{}) as ReceiptSettings;const next:Issuer={name:String(c.name||s.companyName),legalName:String(c.legal_name||c.name||s.companyName),taxId:String(c.tax_id||d.tax_id||''),address:String(rs.receiptAddress||c.address||''),vatCondition:String(rs.fiscalVatCondition||'Responsable Monotributo'),grossIncome:String(rs.grossIncome||''),activityStart:String(rs.activityStartDate||''),receiptSettings:rs};setFiscal(d);setIssuer(next);setGrossIncome(next.grossIncome);setActivityStart(next.activityStart)}catch(e){setFiscal(null);setError(e instanceof Error?e.message:String(e))}finally{setStatusBusy(false)}}

  async function saveFiscalProfile(){if(!session||!issuer)return;if(!grossIncome.trim()||!activityStart){setError('Completá Ingresos Brutos y fecha de inicio de actividades.');return}setProfileBusy(true);setError('');try{const rs={...issuer.receiptSettings,fiscalVatCondition:issuer.vatCondition||'Responsable Monotributo',grossIncome:grossIncome.trim(),activityStartDate:activityStart};const r=await fetch(`${SUPABASE_URL}/rest/v1/companies?id=eq.${encodeURIComponent(session.companyId)}`,{method:'PATCH',headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({receipt_settings:rs})});const d=await r.json().catch(()=>[]);if(!r.ok)throw new Error(d?.message||'No se pudieron guardar los datos del comprobante.');setIssuer({...issuer,grossIncome:grossIncome.trim(),activityStart,receiptSettings:rs})}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setProfileBusy(false)}}

  async function emit(){if(!session)return;if(!(total>0)){setError('Ingresá un importe mayor a cero.');return}if(!fiscal?.configured){setError('Primero hay que conectar ARCA para esta cuenta.');return}setEmitBusy(true);setError('');setInvoice(null);try{const r=await fetch(`${SUPABASE_URL}/functions/v1/arca-invoice`,{method:'POST',headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify({request_id:requestId(),amount:total}),cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok||!d?.invoice?.cae)throw new Error(d?.error||d?.invoice?.errors?.map((x:{code:string;msg:string})=>`${x.code}: ${x.msg}`).join(' · ')||'ARCA no autorizó el comprobante.');setInvoice(d.invoice as Invoice)}catch(e){setError(e instanceof Error?e.message:String(e))}finally{setEmitBusy(false)}}

  function shareText(){if(!invoice)return'';const n=String(invoice.receipt_number).padStart(8,'0');return `Factura C ${String(fiscal?.point_of_sale||0).padStart(5,'0')}-${n}\n${client||'Consumidor final'}\n${concept||'Comprobante electrónico'}\nTotal: ${money.format(invoice.amount)}\nCAE: ${invoice.cae}\nEmitida con FacturaLlena.`}
  async function pdfFile(){if(!invoice||!issuer||!fiscal?.point_of_sale)throw new Error('Faltan datos para generar el comprobante.');if(!profileComplete)throw new Error('Completá los datos fiscales del PDF antes de compartirlo.');const blob=await buildFacturaCPdf(issuer,{pointOfSale:fiscal.point_of_sale,receiptNumber:invoice.receipt_number,cae:invoice.cae,caeExpiration:invoice.cae_expiration,date:invoice.date,amount:invoice.amount,client:client||'Consumidor Final',concept:concept||'Productos / servicios'});return new File([blob],`Factura-C-${String(fiscal.point_of_sale).padStart(5,'0')}-${String(invoice.receipt_number).padStart(8,'0')}.pdf`,{type:'application/pdf'})}
  async function sharePdf(){setShareBusy(true);setError('');try{const file=await pdfFile();if(navigator.share&&(!navigator.canShare||navigator.canShare({files:[file]}))){await navigator.share({title:'Factura C',text:shareText(),files:[file]});return}const url=URL.createObjectURL(file);const a=document.createElement('a');a.href=url;a.download=file.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1500);alert('Descargamos el PDF. En este navegador podés adjuntarlo desde WhatsApp o mail.')}catch(e){if(e instanceof DOMException&&e.name==='AbortError')return;setError(e instanceof Error?e.message:String(e))}finally{setShareBusy(false)}}
  function whatsappText(){if(!invoice)return;window.open(`https://wa.me/?text=${encodeURIComponent(shareText())}`,'_blank','noopener,noreferrer')}
  function emailText(){if(!invoice)return;window.location.href=`mailto:?subject=${encodeURIComponent(`Factura C - ${money.format(invoice.amount)}`)}&body=${encodeURIComponent(shareText())}`}

  if(!ready)return <main className={styles.appPage}/>
  if(!session)return <main className={styles.publicPage}><header className={styles.publicHeader}><div className={styles.wordmark}>FacturaLlena</div><button onClick={install}>Instalar</button></header><section className={styles.publicHero}><div><span>FACTURACIÓN ELECTRÓNICA · ARCA</span><h1>Facturá desde el celular.<br/><em>Sin vueltas.</em></h1><p>Emití una Factura C, obtené el CAE y compartí el comprobante fiscal desde el mismo teléfono.</p></div><form className={styles.loginCard} onSubmit={login}><small>INGRESAR</small><h2>Abrí FacturaLlena</h2><label>Email o usuario<input value={identifier} onChange={e=>setIdentifier(e.target.value)} autoCapitalize="none" autoComplete="username"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="current-password"/></label>{error&&<div className={styles.error}>{error}</div>}<button type="submit" disabled={loginBusy}>{loginBusy?'Ingresando…':'Ingresar'}</button><p>Usá la misma cuenta de Comercio Llena.</p></form></section><section className={styles.human}><img src="https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=1200&q=85" alt="Persona usando su celular para trabajar"/><div><span>HECHA PARA UNA MANO</span><h2>Cliente. Concepto. Importe. Facturar.</h2><p>La acción principal siempre queda abajo, cerca del pulgar.</p></div></section><section className={styles.plans}><span>PLANES EN PESOS ARGENTINOS</span><h2>Simple también para pagar.</h2><div><article><small>INICIO</small><strong>$0</strong><p>20 comprobantes por mes.</p></article><article><small>EMPRENDEDOR</small><strong>$8.900</strong><p>200 comprobantes por mes.</p></article><article><small>NEGOCIO</small><strong>$14.900</strong><p>1.000 comprobantes por mes.</p></article></div></section><footer className={styles.publicFooter}><b>FacturaLlena</b><span>Un producto de Llena Group</span><Link href="/">Comercio Llena</Link></footer></main>

  return <main className={styles.appPage}>
    <header className={styles.appHeader}><button className={styles.iconButton} onClick={()=>void loadAccount()} aria-label="Actualizar">↻</button><div className={styles.appWordmark}>FacturaLlena</div><button className={styles.iconButton} onClick={install} aria-label="Instalar">↓</button></header>
    <section className={styles.statusBar}><span className={fiscal?.configured?styles.okDot:styles.warnDot}/><b>{statusBusy?'Consultando ARCA…':fiscal?.configured?`ARCA ${fiscal.environment==='produccion'?'Producción':'Homologación'}`:'ARCA pendiente'}</b><small>{session.companyName}</small></section>
    {!invoice?<section className={styles.invoiceForm}><div className={styles.formIntro}><span>NUEVA FACTURA C</span><h1>¿Qué facturamos?</h1></div><label>Cliente<input value={client} onChange={e=>setClient(e.target.value)} placeholder="Consumidor final"/></label><label>Concepto<input value={concept} onChange={e=>setConcept(e.target.value)} placeholder="Ej: Productos varios"/></label><div className={styles.chips}><button type="button" className={styles.activeChip}>Factura C</button><button type="button">Consumidor final</button></div><label className={styles.amount}>Importe<div><span>$</span><input inputMode="numeric" value={amount} onChange={e=>setAmount(digits(e.target.value))} placeholder="0"/></div></label>{error&&<div className={styles.error}>{error}</div>}{!fiscal?.configured&&<div className={styles.setupNote}><b>Esta cuenta todavía no figura conectada.</b><span>La configuración fiscal se hace una sola vez desde la versión web.</span><Link href="/redesign">Abrir configuración web</Link></div>}{issuer&&!profileComplete&&<div className={styles.setupNote}><b>Completá 2 datos para el PDF fiscal.</b><span>ARCA ya está conectado; esto completa los datos impresos del comprobante.</span><label>Ingresos Brutos<input value={grossIncome} onChange={e=>setGrossIncome(e.target.value)} placeholder="Número de inscripción"/></label><label>Inicio de actividades<input type="date" value={activityStart} onChange={e=>setActivityStart(e.target.value)}/></label><button type="button" disabled={profileBusy} onClick={()=>void saveFiscalProfile()}>{profileBusy?'Guardando…':'Guardar datos fiscales'}</button></div>}<div className={styles.thumbAction}><div><small>TOTAL</small><strong>{money.format(total)}</strong></div><button disabled={emitBusy||!fiscal?.configured||total<=0} onClick={()=>void emit()}>{emitBusy?'Consultando ARCA…':'Emitir factura'}</button></div></section>:<section className={styles.success}><div className={styles.check}>✓</div><span>FACTURA AUTORIZADA</span><h1>{money.format(invoice.amount)}</h1><p>{client}<br/>{concept||'Comprobante electrónico'}</p><div className={styles.fiscalCard}><div><small>COMPROBANTE</small><b>{String(fiscal?.point_of_sale||0).padStart(5,'0')}-{String(invoice.receipt_number).padStart(8,'0')}</b></div><div><small>CAE</small><b>{invoice.cae}</b></div><div><small>VENCIMIENTO</small><b>{invoice.cae_expiration}</b></div></div>{error&&<div className={styles.error}>{error}</div>}<button className={styles.whatsapp} disabled={shareBusy} onClick={()=>void sharePdf()}>{shareBusy?'Preparando PDF…':'Compartir PDF · WhatsApp / Mail'}</button><button className={styles.mail} onClick={whatsappText}>Abrir WhatsApp con datos</button><button className={styles.share} onClick={emailText}>Abrir app de mail</button><button className={styles.again} onClick={()=>{setInvoice(null);setAmount('');setConcept('');setError('')}}>Hacer otra factura</button></section>}
    <nav className={styles.bottomNav}><button className={styles.navActive}>Inicio</button><button className={styles.plus} onClick={()=>{setInvoice(null);setAmount('');setConcept('');setError('')}}>+</button><button onClick={()=>alert('Historial: siguiente módulo.')}>Facturas</button></nav>
  </main>
}
