'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'
import styles from '../../postula-preview/platform.module.css'

async function headers(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
export default function EmployerRegistration(){
 const [done,setDone]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[authed,setAuthed]=useState<boolean|null>(null)
 const [name,setName]=useState(''),[tax,setTax]=useState(''),[website,setWebsite]=useState(''),[phone,setPhone]=useState(''),[city,setCity]=useState(''),[province,setProvince]=useState('Buenos Aires'),[industry,setIndustry]=useState(''),[contact,setContact]=useState('')
 useEffect(()=>{cvAuthClient().auth.getSession().then(({data})=>setAuthed(Boolean(data.session)))},[])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{const h={'Content-Type':'application/json',...(await headers())};const r=await fetch('/api/postula/company',{method:'POST',headers:h,body:JSON.stringify({name,tax_id:tax,website,phone,city,province,industry,responsible_role:contact})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos crear la empresa.');setDone(true)}catch(e){setError(e instanceof Error?e.message:'No pudimos crear la empresa.')}finally{setBusy(false)}}
 if(authed===false)return <div className={styles.authGrid}><section className={styles.authVisual}><span className={styles.eyebrow}>Cuenta de empresa</span><h1>Primero identifiquemos a la persona que publica.</h1><p>La empresa queda asociada a una cuenta individual y después podés sumar a Recursos Humanos o gerentes con permisos separados.</p></section><section className={styles.authCardWrap}><div className={styles.authCard}><h2>Creá tu acceso en segundos</h2><p>Email + contraseña. Después volvés acá para completar la empresa.</p><Link className={styles.buttonDark} href="/acceso?rol=empresa&next=/empresas/registro">Crear cuenta de empleador</Link></div></section></div>
 if(done)return <div className={styles.authGrid}><section className={styles.authVisual}><span className={styles.eyebrow}>Empresa creada</span><h1>Ya tenés una identidad comercial separada y protegida.</h1><p>La cuenta quedó con validación básica. Desde el panel podés completar datos, invitar a RRHH y publicar búsquedas.</p></section><section className={styles.authCardWrap}><div className={styles.authCard}><span className={styles.planPill}>VALIDACIÓN BÁSICA ACTIVA</span><h2 style={{marginTop:16}}>{name}</h2><p>Tu cuenta personal es la propietaria inicial. Cada integrante adicional tendrá su propio usuario y rol.</p><div className={styles.securityBadge}><b>Seguridad multitenant:</b> los accesos de empresa se validan por membresía y rol. Los datos de candidatos sólo se exponen cuando existe una postulación vinculada a una búsqueda de esta empresa.</div><Link className={styles.button} style={{width:'100%',marginTop:14}} href="/empresas/panel">Entrar al panel</Link></div></section></div>
 return <div className={styles.authGrid}><section className={styles.authVisual}><span className={styles.eyebrow}>Alta de empresa</span><h1>Publicar es fácil. Hacerse pasar por otra empresa, no.</h1><p>Pedimos pocas señales pero útiles: contacto, actividad, ubicación y quién representa a la organización. El CUIT queda opcional para empezar.</p><div className={styles.heroMicro}><span><i/>Usuario individual</span><span><i/>Empresa aislada</span><span><i/>Roles y auditoría</span></div></section><section className={styles.authCardWrap}><form className={styles.authCard} onSubmit={submit}><span className={styles.miniLabel}>Validación básica</span><h2>Datos de la organización</h2><p>No necesitás subir constancia fiscal para crear la cuenta.</p><div className={styles.field}><label>Nombre comercial</label><input value={name} onChange={e=>setName(e.target.value)} required placeholder="Ej. Hotel Centro"/></div><div className={styles.fieldRow}><div className={styles.field}><label>Actividad / rubro</label><input value={industry} onChange={e=>setIndustry(e.target.value)} required placeholder="Hotelería, comercio, gastronomía…"/></div><div className={styles.field}><label>Tu rol</label><select value={contact} onChange={e=>setContact(e.target.value)} required><option value="">Elegir</option><option>Dueño / socio</option><option>Recursos Humanos</option><option>Gerencia</option><option>Recruiter autorizado</option></select></div></div><div className={styles.fieldRow}><div className={styles.field}><label>Ciudad</label><input value={city} onChange={e=>setCity(e.target.value)} required placeholder="CABA"/></div><div className={styles.field}><label>Provincia</label><input value={province} onChange={e=>setProvince(e.target.value)} required/></div></div><div className={styles.field}><label>Teléfono de contacto</label><input value={phone} onChange={e=>setPhone(e.target.value)} required placeholder="11 1234 5678"/></div><div className={styles.field}><label>Sitio web o dominio (opcional)</label><input value={website} onChange={e=>setWebsite(e.target.value)} placeholder="empresa.com.ar"/></div><div className={styles.field}><label>CUIT / identificación fiscal (opcional al inicio)</label><input value={tax} onChange={e=>setTax(e.target.value)} placeholder="XX-XXXXXXXX-X"/></div><button className={styles.buttonDark} style={{width:'100%',marginTop:18}} disabled={busy}>{busy?'Creando empresa…':'Crear empresa'}</button>{error&&<div className={styles.securityBadge} style={{color:'#a12d35'}}>{error}</div>}<div className={styles.securityBadge}>La validación básica no es una garantía absoluta sobre una empresa. Postulá Mejor puede pedir comprobaciones adicionales o pausar una publicación ante señales de riesgo.</div></form></section></div>
}
