import {PDFDocument,StandardFonts,rgb} from 'pdf-lib'
import type {CvTemplate} from './templates'

export const PM_TEMPLATE_MARKER='PM_TEMPLATE:'

const sample={
 name:'Valentina Pérez',role:'Analista Comercial',location:'Buenos Aires · Argentina',email:'valentina@email.com',phone:'+54 11 5555 0101',summary:'Perfil orientado a resultados, atención al cliente y mejora de procesos. Experiencia trabajando con equipos, seguimiento de objetivos y resolución de necesidades comerciales.',experience:[['Analista Comercial','Empresa Actual','2023 — Actualidad','Seguimiento de cartera, coordinación con equipos internos y mejora de procesos de atención.'],['Asistente de Ventas','Compañía Anterior','2021 — 2023','Atención de clientes, carga de información y soporte al equipo comercial.']],education:['Tecnicatura / Carrera relacionada · Institución','Curso de herramientas digitales · 2025'],skills:['Atención al cliente','Ventas','Excel','Organización','Comunicación'],languages:['Español nativo','Inglés intermedio']
}

function esc(v:string){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]||m))}
function blobDownload(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),500)}

function wordCss(t:CvTemplate){
 const common=`@page{size:A4;margin:0}body{margin:0;font-family:${t.font};color:${t.ink};background:#fff}.page{width:19cm;min-height:27.7cm;margin:0 auto;box-sizing:border-box;background:#fff}.marker{display:none;mso-hide:all}.name{font-size:30pt;font-weight:800;line-height:1;margin:0}.role{font-size:13pt;color:${t.accent};font-weight:700;margin:7pt 0 12pt}.contact{font-size:8.7pt;line-height:1.55;color:#59606b}.section{margin-top:16pt}.section h2{font-size:9.5pt;letter-spacing:1.2pt;text-transform:uppercase;color:${t.accent};border-bottom:1pt solid ${t.soft};padding-bottom:5pt;margin:0 0 7pt}.section p,.section li{font-size:9.2pt;line-height:1.45}.job{margin:0 0 11pt}.job b{font-size:9.8pt}.job small{display:block;color:#68707c;font-size:8pt;margin:2pt 0 4pt}.skill{display:inline-block;background:${t.soft};color:${t.ink};padding:4pt 7pt;margin:0 4pt 4pt 0;font-size:8.3pt;border-radius:10pt}.photo{width:66pt;height:66pt;border-radius:50%;background:${t.soft};border:5pt solid #fff;box-shadow:0 0 0 1pt ${t.accent};display:flex;align-items:center;justify-content:center;color:${t.accent};font-size:20pt;font-weight:800}`
 if(t.layout==='sidebar')return common+`.page{display:table}.side,.main{display:table-cell;vertical-align:top}.side{width:30%;background:${t.accent};color:white;padding:28pt 18pt}.side .contact,.side h2,.side p{color:white}.side .section h2{border-color:rgba(255,255,255,.35)}.main{width:70%;padding:34pt 30pt}.main .name{font-size:27pt}.photo{background:white;color:${t.accent};margin-bottom:20pt}`
 if(t.layout==='split')return common+`.page{padding:32pt}.top{background:${t.soft};padding:24pt;border-left:8pt solid ${t.accent};display:table;width:100%;box-sizing:border-box}.topcopy,.topphoto{display:table-cell;vertical-align:middle}.topphoto{width:78pt}.body{display:table;width:100%;margin-top:18pt}.left,.right{display:table-cell;vertical-align:top}.left{width:34%;padding-right:18pt}.right{width:66%;border-left:1pt solid #e5e7eb;padding-left:20pt}`
 if(t.layout==='timeline')return common+`.page{padding:36pt}.head{border-bottom:5pt solid ${t.accent};padding-bottom:16pt}.job{border-left:2pt solid ${t.accent};padding-left:14pt;position:relative}.job b{color:${t.accent}}.body{display:table;width:100%}.left,.right{display:table-cell;vertical-align:top}.left{width:68%;padding-right:22pt}.right{width:32%;background:${t.soft};padding:16pt}`
 if(t.layout==='compact')return common+`.page{padding:30pt}.head{display:table;width:100%;border-bottom:1pt solid #d8dde5;padding-bottom:15pt}.topcopy,.topphoto{display:table-cell;vertical-align:middle}.topphoto{width:76pt}.columns{column-count:2;column-gap:25pt}.section{break-inside:avoid}.section h2{background:${t.soft};padding:6pt 8pt;border:0}`
 if(t.layout==='editorial')return common+`.page{padding:44pt 38pt}.head{padding-bottom:20pt;border-bottom:1pt solid ${t.ink}}.name{font-family:Georgia,serif;font-size:34pt}.role{letter-spacing:1pt}.section h2{font-family:Arial,sans-serif;font-size:8.5pt;color:${t.ink};border-left:4pt solid ${t.accent};border-bottom:0;padding:2pt 0 2pt 8pt}.body{max-width:520pt}`
 return common+`.page{padding:38pt}.head{border-top:10pt solid ${t.accent};padding-top:23pt}.body{margin-top:18pt}`
}

function sections(t:CvTemplate){return `<div class="section"><h2>Perfil profesional</h2><p>${esc(sample.summary)}</p></div><div class="section"><h2>Experiencia</h2>${sample.experience.map(x=>`<div class="job"><b>${esc(x[0])} · ${esc(x[1])}</b><small>${esc(x[2])}</small><p>${esc(x[3])}</p></div>`).join('')}</div><div class="section"><h2>Formación</h2><ul>${sample.education.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="section"><h2>Habilidades</h2><p>${sample.skills.map(x=>`<span class="skill">${esc(x)}</span>`).join('')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join(' · ')}</p></div>`}
function contact(){return `<div class="contact">${esc(sample.location)}<br>${esc(sample.phone)}<br>${esc(sample.email)}<br>linkedin.com/in/tu-perfil</div>`}
function photo(t:CvTemplate){return t.photo?`<div class="photo">VP</div>`:''}

export function buildWordHtml(t:CvTemplate){
 const head=`<h1 class="name">${esc(sample.name)}</h1><div class="role">${esc(sample.role)}</div>`
 let body=''
 if(t.layout==='sidebar')body=`<div class="page"><aside class="side">${photo(t)}${contact()}<div class="section"><h2>Habilidades</h2><p>${sample.skills.join('<br>')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join('<br>')}</p></div></aside><main class="main">${head}${sections(t)}</main></div>`
 else if(t.layout==='split')body=`<div class="page"><div class="top"><div class="topcopy">${head}${contact()}</div><div class="topphoto">${photo(t)}</div></div><div class="body"><div class="left"><div class="section"><h2>Habilidades</h2><p>${sample.skills.map(x=>`<span class="skill">${x}</span>`).join('')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join('<br>')}</p></div></div><div class="right">${sections(t)}</div></div></div>`
 else if(t.layout==='timeline')body=`<div class="page"><div class="head">${head}${contact()}</div><div class="body"><div class="left">${sections(t)}</div><aside class="right">${photo(t)}<div class="section"><h2>Fortalezas</h2><p>${sample.skills.join('<br>')}</p></div></aside></div></div>`
 else if(t.layout==='compact')body=`<div class="page"><div class="head"><div class="topcopy">${head}${contact()}</div><div class="topphoto">${photo(t)}</div></div><div class="columns">${sections(t)}</div></div>`
 else if(t.layout==='editorial')body=`<div class="page"><div class="head">${photo(t)}${head}${contact()}</div><div class="body">${sections(t)}</div></div>`
 else body=`<div class="page"><div class="head">${photo(t)}${head}${contact()}</div><div class="body">${sections(t)}</div></div>`
 return `<!doctype html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><meta name="postula-template" content="${t.id}"><title>${esc(t.name)} · Postulá Mejor</title><style>${wordCss(t)}</style></head><body><!-- ${PM_TEMPLATE_MARKER}${t.id}:v1 --><span class="marker">${PM_TEMPLATE_MARKER}${t.id}:v1</span>${body}</body></html>`
}

export function downloadWordTemplate(t:CvTemplate){const html=buildWordHtml(t);blobDownload(new Blob(['\ufeff',html],{type:'application/msword;charset=utf-8'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}.doc`)}

function hex(v:string){const h=v.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255] as const}
function wrap(text:string,max=74){const words=text.split(/\s+/);const rows:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){rows.push(line);line=w}else line=(line+' '+w).trim()}if(line)rows.push(line);return rows}
export async function downloadPdfTemplate(t:CvTemplate){
 const doc=await PDFDocument.create();doc.setTitle(`${t.name} · Postulá Mejor`);doc.setSubject(`${PM_TEMPLATE_MARKER}${t.id}:v1`);doc.setKeywords(['Postula Mejor','CV template',`${PM_TEMPLATE_MARKER}${t.id}`]);const p=doc.addPage([595.28,841.89]);const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const [r,g,b]=hex(t.accent),accent=rgb(r,g,b),ink=rgb(.09,.1,.13),muted=rgb(.38,.41,.46);p.drawRectangle({x:0,y:800,width:595.28,height:42,color:accent});if(t.layout==='sidebar')p.drawRectangle({x:0,y:0,width:170,height:800,color:accent,opacity:.94});if(t.layout==='split')p.drawRectangle({x:34,y:665,width:527,height:110,color:rgb(.96,.97,.99)});let x=t.layout==='sidebar'?195:48,y=760;p.drawText(sample.name,{x,y,size:25,font:bold,color:t.layout==='sidebar'?ink:ink});y-=30;p.drawText(sample.role,{x,y,size:12,font:bold,color:accent});y-=22;p.drawText(`${sample.location} · ${sample.email}`,{x,y,size:8.5,font:regular,color:muted});y-=35;const section=(title:string,lines:string[])=>{p.drawText(title.toUpperCase(),{x,y,size:9,font:bold,color:accent});y-=16;for(const line of lines){for(const row of wrap(line,t.layout==='sidebar'?55:78)){p.drawText(row,{x,y,size:8.7,font:regular,color:ink});y-=12}y-=4}y-=8};section('Perfil profesional',[sample.summary]);section('Experiencia',sample.experience.map(e=>`${e[0]} · ${e[1]} · ${e[2]} — ${e[3]}`));section('Formación',sample.education);section('Habilidades',[sample.skills.join(' · ')]);p.drawText(`${PM_TEMPLATE_MARKER}${t.id}:v1`,{x:20,y:15,size:2,font:regular,color:rgb(1,1,1)});const bytes=await doc.save();blobDownload(new Blob([bytes as BlobPart],{type:'application/pdf'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}.pdf`)
}
