import {PDFDocument,StandardFonts,rgb} from 'pdf-lib'
import type {CvTemplate} from './templates'

export const PM_TEMPLATE_MARKER='PM_TEMPLATE:'
const sample={name:'Valentina Pérez',role:'Analista Comercial',location:'Buenos Aires · Argentina',email:'valentina@email.com',phone:'+54 11 5555 0101',summary:'Perfil orientado a resultados, atención al cliente y mejora de procesos. Experiencia trabajando con equipos, seguimiento de objetivos y resolución de necesidades comerciales.',experience:[['Analista Comercial','Empresa Actual','2023 — Actualidad','Seguimiento de cartera, coordinación con equipos internos y mejora de procesos de atención.'],['Asistente de Ventas','Compañía Anterior','2021 — 2023','Atención de clientes, carga de información y soporte al equipo comercial.']],education:['Tecnicatura / Carrera relacionada · Institución','Curso de herramientas digitales · 2025'],skills:['Atención al cliente','Ventas','Excel','Organización','Comunicación'],languages:['Español nativo','Inglés intermedio']}
function esc(v:string){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]||m))}
function blobDownload(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),500)}
const sideDesigns=new Set(['student-side','sales-strip','kpi-sidebar','hospitality-luxe','creative-shapes','customer-score','black-luxury','editorial-orange','gastro-menu'])
const metricDesigns=new Set(['sales-strip','kpi-sidebar','retail-blocks','finance-ledger','marketing-stats','data-dashboard','leadership-dark'])
const darkDesigns=new Set(['tech-console','leadership-dark','black-luxury'])
const cardDesigns=new Set(['office-grid','retail-blocks','health-soft','product-cards','data-dashboard','startup-bold','pastel-cards'])
const timelineDesigns=new Set(['trade-timeline','ops-route','blueprint','project-milestones'])
function designCss(t:CvTemplate){const d=t.design;let x='';if(sideDesigns.has(d))x+=`.content{display:table;width:100%}.side,.main{display:table-cell;vertical-align:top}.side{display:table-cell;width:31%;background:${t.accent};color:#fff;padding:20pt 14pt}.main{width:69%;padding:22pt 22pt}.side .contact,.side h2,.side p{color:#fff}.side .section h2{border-color:rgba(255,255,255,.35)}.head{padding:22pt 24pt}`;else x+=`.side{display:none}.main{padding:24pt 32pt}.head{padding:28pt 32pt}`;if(metricDesigns.has(d))x+=`.kpis{display:table;width:100%;padding:8pt 24pt;background:${t.soft}.kpis span{display:table-cell;width:33%;font-size:8pt}.kpis b{display:block;font-size:14pt;color:${t.accent}}`;else x+=`.kpis{display:none}`;if(cardDesigns.has(d))x+=`.section{border:1pt solid ${t.soft};padding:9pt;border-radius:6pt;background:#fff}.main{column-count:2;column-gap:12pt}.section{break-inside:avoid}`;if(timelineDesigns.has(d))x+=`.job{border-left:3pt solid ${t.accent};padding-left:10pt;margin-left:4pt}.job:before{content:'•';color:${t.accent};font-size:16pt;margin-left:-15pt;margin-right:6pt}`;if(darkDesigns.has(d))x+=`.head{background:#111827;color:#fff}.head .role,.head .contact{color:#d8dee8}`;
 const unique:Record<string,string>={
 'ats-line':`.head{border-bottom:2pt solid #111;padding-top:18pt}.name{font-size:27pt}.section h2{color:#111;border-bottom:1pt solid #aaa}`,
 'clean-banner':`.head{background:${t.soft};border-bottom:6pt solid ${t.accent}}.main{padding-top:18pt}.section h2{border-left:4pt solid ${t.accent};border-bottom:0;padding-left:6pt}`,
 'student-side':`.side{background:${t.soft};color:${t.ink}}.side .contact,.side h2,.side p{color:${t.ink}}.side .section h2{color:${t.accent}}`,
 'office-grid':`.head{border-top:7pt solid ${t.accent};padding-bottom:12pt}.main{background:#fafafe}`,
 'service-card':`.head{text-align:center;background:${t.soft};margin:22pt;border-radius:10pt}.name{font-size:25pt}.main{padding-top:6pt}`,
 'minimal-rule':`.head{border-bottom:1pt solid #222}.name{font-family:Georgia,serif;font-weight:400;font-size:32pt}.section h2{color:#222;border-left:3pt solid ${t.accent};border-bottom:0;padding-left:7pt}`,
 'profile-top':`.head{border-top:8pt solid ${t.accent}}.main{padding-right:18pt}.section h2{background:${t.soft};padding:4pt 6pt;border:0}`,
 'fresh-cap':`.head{background:${t.soft};border-left:26pt solid ${t.accent}}.skill{border-radius:12pt}`,
 'trade-timeline':`.head{border-bottom:5pt solid ${t.accent}}`,
 'sales-strip':`.page{border-left:12pt solid ${t.accent}}.side{background:${t.soft};color:${t.ink}}.side .contact,.side h2,.side p{color:${t.ink}}`,
 'classic-serif':`.head{text-align:center}.name{font-family:Georgia,serif;font-weight:600}.section h2{font-family:Georgia,serif;color:#333;border-bottom:1pt solid #888}`,
 'color-corner':`.head{border-right:42pt solid ${t.accent};padding-top:32pt}.name{font-size:31pt}.section h2{border-left:4pt solid ${t.accent};border-bottom:0;padding-left:7pt}`,
 'executive-panel':`.head{background:#253142;color:#fff}.head .role,.head .contact{color:#e3e7ec}.side{background:#ece8df;color:#253142}.side .contact,.side h2,.side p{color:#253142}.name{font-family:Georgia,serif}`,
 'kpi-sidebar':`.side{background:${t.accent}}.name{font-size:31pt}.section h2{letter-spacing:1.6pt}`,
 'tech-console':`.page{background:#0f172a;color:#dbeafe}.main{background:#0f172a}.section{background:#111c33;border-color:#22304a}.section p,.section li,.job small{color:#aab9cc}.section h2{font-family:Courier New,monospace;color:#60a5fa;border-color:#334155}`,
 'hospitality-luxe':`.head{text-align:center;background:#faf7f0}.name{font-family:Georgia,serif}.side{background:#7d5a31}.section h2{font-family:Georgia,serif}`,
 'retail-blocks':`.head{margin:18pt;background:${t.soft};border-radius:8pt}.main{column-count:2}`,
 'ops-route':`.head{background:#f2fbf9;border-bottom:5pt solid ${t.accent}}`,
 'health-soft':`.head{margin:18pt;background:${t.soft};border-radius:14pt}.section{border-radius:10pt;background:#f8fcfc}`,
 'finance-ledger':`.page{border-top:8pt solid ${t.accent}}.section h2{background:${t.soft};padding:5pt;border:0}`,
 'legal-column':`.page{border-left:1pt solid ${t.accent}}.name,.section h2{font-family:Georgia,serif}.name{font-weight:400}.section h2{color:${t.ink}}`,
 'creative-shapes':`.head{background:${t.soft};border-bottom:10pt solid ${t.accent}}.side{background:${t.soft};color:${t.ink}}.side .contact,.side h2,.side p{color:${t.ink}}.section h2{background:${t.accent};color:#fff;padding:4pt 6pt;border:0}`,
 'product-cards':`.head{background:${t.accent};color:#fff}.head .role,.head .contact{color:#e7e5ff}.section h2{letter-spacing:1.5pt}`,
 'marketing-stats':`.head{border-bottom:6pt solid ${t.accent}}.name{font-size:32pt}.section h2{background:${t.soft};padding:5pt;border:0}`,
 'data-dashboard':`.page{background:#f8fbff}.section h2{font-family:Courier New,monospace}.section{border-color:#dbe8f8}`,
 'blueprint':`.page{background:#fbfcfe}.head{background:${t.soft};border-bottom:5pt solid ${t.accent}}.section h2{letter-spacing:1.7pt}`,
 'academic-paper':`.head{text-align:center}.name,.section h2{font-family:Georgia,serif}.section h2{border-bottom:3pt double #9bbbad}`,
 'gastro-menu':`.head{background:#2b1c0d;color:#fff}.head .role,.head .contact{color:#f4d7b2}.side{background:#fff3e4;color:${t.ink}}.side .contact,.side h2,.side p{color:${t.ink}}.section h2{font-family:Georgia,serif}`,
 'remote-chips':`.head{background:${t.soft};margin:16pt;border-radius:9pt}.skill{background:${t.soft};border-radius:14pt}`,
 'leadership-dark':`.name{font-family:Georgia,serif;font-weight:400;font-size:34pt}.main{padding-top:26pt}`,
 'startup-bold':`.page{border-top:10pt solid ${t.accent}}.name{font-size:34pt;letter-spacing:-1pt}.section h2{background:${t.soft};padding:5pt;border:0}`,
 'customer-score':`.side{background:#075e87}.section h2{color:#0284c7}`,
 'project-milestones':`.head{border-bottom:5pt solid ${t.accent}}.job{padding-bottom:8pt}`,
 'black-luxury':`.head{background:#0b0b0b;color:#fff}.head .role,.head .contact{color:#ddd}.side{background:#f1f1f1;color:#111}.side .contact,.side h2,.side p{color:#111}.name{font-family:Georgia,serif;font-weight:400}.section h2{color:#111;border-color:#111}`,
 'pastel-cards':`.page{background:#faf8ff}.head{margin:16pt;background:${t.soft};border-radius:12pt}.section{border-radius:10pt;box-shadow:0 2pt 7pt #eee9fa}`,
 'editorial-orange':`.side{background:${t.accent}}.name{font-size:33pt}.section h2{color:${t.accent};border-bottom:2pt solid ${t.accent}}`
 };return x+(unique[d]||'')}
function wordCss(t:CvTemplate){return `@page{size:A4;margin:0}body{margin:0;font-family:${t.font};color:${t.ink};background:#fff}*{box-sizing:border-box}.page{width:19cm;min-height:27.7cm;margin:0 auto;background:#fff}.marker{display:none;mso-hide:all}.head{position:relative}.name{font-size:29pt;font-weight:800;line-height:1;margin:0}.role{font-size:11pt;color:${t.accent};font-weight:700;margin:7pt 0 9pt}.contact{font-size:8pt;line-height:1.5;color:#626c78}.photo{float:right;width:62pt;height:62pt;border-radius:50%;background:${t.soft};border:4pt solid #fff;text-align:center;line-height:62pt;color:${t.accent};font-weight:800}.section{margin:0 0 11pt}.section h2{font-size:8.5pt;letter-spacing:1.05pt;text-transform:uppercase;color:${t.accent};border-bottom:1pt solid ${t.soft};padding-bottom:4pt;margin:0 0 6pt}.section p,.section li{font-size:8.7pt;line-height:1.42}.job{margin:0 0 10pt}.job b{font-size:9.5pt}.job small{display:block;color:#69737e;font-size:7.8pt;margin:2pt 0 3pt}.skill{display:inline-block;background:${t.soft};padding:4pt 7pt;margin:0 4pt 4pt 0;font-size:7.8pt}.content{width:100%}.side{display:none}.kpis{display:none}${designCss(t)}`}
function sectionHtml(){return `<div class="section"><h2>Perfil profesional</h2><p>${esc(sample.summary)}</p></div><div class="section"><h2>Experiencia</h2>${sample.experience.map(x=>`<div class="job"><b>${esc(x[0])} · ${esc(x[1])}</b><small>${esc(x[2])}</small><p>${esc(x[3])}</p></div>`).join('')}</div><div class="section"><h2>Formación</h2><ul>${sample.education.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="section"><h2>Habilidades</h2><p>${sample.skills.map(x=>`<span class="skill">${esc(x)}</span>`).join('')}</p></div>`}
function contact(){return `<div class="contact">${esc(sample.location)} · ${esc(sample.phone)} · ${esc(sample.email)}</div>`}
export function buildWordHtml(t:CvTemplate){const head=`<div class="head">${t.photo?'<div class="photo">VP</div>':''}<h1 class="name">${esc(sample.name)}</h1><div class="role">${esc(sample.role)}</div>${contact()}</div>`;const kpis=`<div class="kpis"><span><b>18%</b> crecimiento</span><span><b>42</b> clientes</span><span><b>4.8</b> score</span></div>`;const side=`<aside class="side">${t.photo?'<div class="photo">VP</div>':''}${contact()}<div class="section"><h2>Habilidades</h2><p>${sample.skills.join('<br>')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join('<br>')}</p></div></aside>`;return `<!doctype html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><meta name="postula-template" content="${t.id}"><title>${esc(t.name)} · Postulá Mejor</title><style>${wordCss(t)}</style></head><body><!-- ${PM_TEMPLATE_MARKER}${t.id}:v4 --><span class="marker">${PM_TEMPLATE_MARKER}${t.id}:v4</span><div class="page">${head}${kpis}<div class="content">${side}<main class="main">${sectionHtml()}</main></div></div></body></html>`}
export function downloadWordTemplate(t:CvTemplate){blobDownload(new Blob(['\ufeff',buildWordHtml(t)],{type:'application/msword;charset=utf-8'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}.doc`)}
function hex(v:string){const h=v.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255] as const}
function wrap(text:string,max=70){const words=text.split(/\s+/),rows:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){if(line)rows.push(line);line=w}else line=(line+' '+w).trim()}if(line)rows.push(line);return rows}
export async function downloadPdfTemplate(t:CvTemplate){const doc=await PDFDocument.create();doc.setTitle(`${t.name} · Postulá Mejor`);doc.setSubject(`${PM_TEMPLATE_MARKER}${t.id}:v4`);const p=doc.addPage([595.28,841.89]);const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const [r,g,b]=hex(t.accent),accent=rgb(r,g,b),ink=rgb(.08,.09,.12),muted=rgb(.38,.41,.46);const side=sideDesigns.has(t.design),dark=darkDesigns.has(t.design),metrics=metricDesigns.has(t.design);if(side)p.drawRectangle({x:0,y:0,width:175,height:842,color:accent});if(dark)p.drawRectangle({x:side?175:0,y:690,width:side?420:595,height:152,color:rgb(.06,.08,.12)});else if(!side)p.drawRectangle({x:0,y:806,width:595,height:36,color:accent});if(cardDesigns.has(t.design))p.drawRectangle({x:side?195:35,y:75,width:side?365:525,height:610,color:rgb(.985,.985,1)});let x=side?198:48,y=dark?760:758;p.drawText(sample.name,{x,y,size:25,font:bold,color:dark?rgb(1,1,1):ink});y-=29;p.drawText(sample.role,{x,y,size:11,font:bold,color:dark?rgb(.75,.82,1):accent});y-=18;p.drawText(`${sample.location} · ${sample.email}`,{x,y,size:8,font:regular,color:dark?rgb(.75,.78,.84):muted});y-=metrics?62:32;if(metrics){for(let i=0;i<3;i++){p.drawRectangle({x:x+i*105,y:y+17,width:88,height:34,color:rgb(.95,.96,.98)});p.drawText(['18%','42','4.8'][i],{x:x+8+i*105,y:y+34,size:11,font:bold,color:accent});p.drawText(['crecimiento','clientes','score'][i],{x:x+8+i*105,y:y+23,size:5.8,font:regular,color:muted})}y-=8}const section=(title:string,lines:string[])=>{p.drawText(title.toUpperCase(),{x,y,size:8.5,font:bold,color:accent});y-=15;for(const line of lines){for(const row of wrap(line,side?50:76)){p.drawText(row,{x,y,size:8.1,font:regular,color:ink});y-=11}y-=3}y-=8};section('Perfil profesional',[sample.summary]);section('Experiencia',sample.experience.map(e=>`${e[0]} · ${e[1]} · ${e[2]}. ${e[3]}`));section('Formación',sample.education);section('Habilidades',[sample.skills.join(' · ')]);const bytes=await doc.save();blobDownload(new Blob([bytes],{type:'application/pdf'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}-muestra.pdf`)}
