import {PDFDocument,StandardFonts,rgb} from 'pdf-lib'
import type {CvTemplate} from './templates'

export const PM_TEMPLATE_MARKER='PM_TEMPLATE:'
const sample={name:'Valentina Pérez',role:'Analista Comercial',location:'Buenos Aires · Argentina',email:'valentina@email.com',phone:'+54 11 5555 0101',summary:'Perfil orientado a resultados, atención al cliente y mejora de procesos. Experiencia trabajando con equipos, seguimiento de objetivos y resolución de necesidades comerciales.',experience:[['Analista Comercial','Empresa Actual','2023 — Actualidad','Seguimiento de cartera, coordinación con equipos internos y mejora de procesos de atención.'],['Asistente de Ventas','Compañía Anterior','2021 — 2023','Atención de clientes, carga de información y soporte al equipo comercial.']],education:['Tecnicatura / Carrera relacionada · Institución','Curso de herramientas digitales · 2025'],skills:['Atención al cliente','Ventas','Excel','Organización','Comunicación'],languages:['Español nativo','Inglés intermedio']}
function esc(v:string){return v.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]||m))}
function blobDownload(blob:Blob,name:string){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.appendChild(a);a.click();a.remove();window.setTimeout(()=>URL.revokeObjectURL(url),500)}

function variantCss(t:CvTemplate){
 if(t.id==='pm-ejecutivo')return `.top{background:#ece8df!important}.name{font-family:Georgia,serif}.section h2{color:#253142!important}`
 if(t.id==='pm-comercial')return `.side{background:linear-gradient(#ec6244,#bd3d2b)!important}.name{letter-spacing:-1pt}.skill{background:#fff0eb}`
 if(t.id==='pm-tech')return `.page{background-image:linear-gradient(rgba(53,103,232,.035) 1px,transparent 1px),linear-gradient(90deg,rgba(53,103,232,.035) 1px,transparent 1px);background-size:16pt 16pt}.section h2{font-family:Courier New,monospace}`
 if(t.id==='pm-hotel')return `.side{background:linear-gradient(#7d5a31,#a7773e)!important}.name{font-family:Georgia,serif}.role{color:#9a6a2f}`
 if(t.id==='pm-retail')return `.top{background:linear-gradient(135deg,#f4edff,#fff)!important}.section h2{border-bottom-color:#d9c9fa}`
 if(t.id==='pm-salud')return `.head{background:#f7fcfc;padding:18pt;border-top:8pt solid #277f8a}.name{font-family:Georgia,serif}`
 if(t.id==='pm-finanzas')return `.page{border-top:8pt solid #163a6b}.section h2{background:#edf3fa;padding:5pt 7pt;border:0}`
 if(t.id==='pm-legal')return `.name{font-family:Georgia,serif;font-weight:500}.section h2{font-family:Georgia,serif;color:#241d18!important}`
 if(t.id==='pm-creative')return `.page{background:linear-gradient(135deg,#fff 0 72%,#fbf0fd 72%)}.top{background:#fff!important;border-left:9pt solid #c843d7}.section h2{background:#c843d7;color:#fff!important;padding:5pt 7pt;border:0}`
 if(t.id==='pm-producto')return `.side{background:linear-gradient(#4338ca,#625bdc)!important}.section h2{letter-spacing:1.5pt}`
 if(t.id==='pm-marketing')return `.head{border-bottom:5pt solid #df4f55;padding-bottom:18pt}.name{font-family:Trebuchet MS,sans-serif}`
 if(t.id==='pm-datos')return `.section h2{font-family:Courier New,monospace}.page{border-top:7pt solid #2563eb}`
 if(t.id==='pm-ingenieria')return `.head{background:#f5f7f9;padding:18pt}.job{border-left-width:3pt}`
 if(t.id==='pm-docencia')return `.name{font-family:Georgia,serif}.head{border-top-color:#0f8a5f}`
 if(t.id==='pm-gastronomia')return `.side{background:linear-gradient(#b45309,#7c3505)!important}.name{font-family:Trebuchet MS,sans-serif}`
 if(t.id==='pm-remoto')return `.top{background:linear-gradient(135deg,#f5f3ff,#fff)!important}.skill{background:#ede9fe}`
 if(t.id==='pm-liderazgo')return `.head{background:#111827;color:#fff;padding:24pt}.head .contact{color:#d6d9e0}.name{font-family:Georgia,serif;font-weight:500}.section h2{color:#111827!important}`
 if(t.id==='pm-startup')return `.page{border-top:8pt solid #16a34a}.section h2{background:#f0fdf4;padding:5pt 7pt;border:0}`
 if(t.id==='pm-customer')return `.side{background:linear-gradient(#0284c7,#045f8c)!important}`
 if(t.id==='pm-proyectos')return `.job{border-left-width:4pt;padding-left:16pt}.job b{font-family:Georgia,serif}`
 if(t.id==='pm-premium-black')return `.top{background:#111!important;color:#fff;border-left-color:#111}.top .contact,.top .role{color:#ddd}.name{font-family:Georgia,serif;font-weight:500}`
 if(t.id==='pm-pastel')return `.head{background:#f4f0ff;padding:22pt}.section h2{border-left-color:#6d5bd0}`
 if(t.id==='pm-naranja')return `.side{background:linear-gradient(#f97316,#c2410c)!important}.section h2{color:#ea580c!important}`
 return ''
}
function wordCss(t:CvTemplate){
 const common=`@page{size:A4;margin:0}body{margin:0;font-family:${t.font};color:${t.ink};background:#fff}*{box-sizing:border-box}.page{width:19cm;min-height:27.7cm;margin:0 auto;background:#fff}.marker{display:none;mso-hide:all}.name{font-size:30pt;font-weight:800;line-height:1;margin:0}.role{font-size:12pt;color:${t.accent};font-weight:700;margin:7pt 0 11pt}.contact{font-size:8.5pt;line-height:1.55;color:#626c78}.section{margin-top:15pt}.section h2{font-size:9pt;letter-spacing:1.15pt;text-transform:uppercase;color:${t.accent};border-bottom:1pt solid ${t.soft};padding-bottom:5pt;margin:0 0 7pt}.section p,.section li{font-size:9.1pt;line-height:1.46}.job{margin:0 0 11pt}.job b{font-size:9.8pt}.job small{display:block;color:#69737e;font-size:8pt;margin:2pt 0 4pt}.skill{display:inline-block;background:${t.soft};padding:4pt 7pt;margin:0 4pt 4pt 0;font-size:8pt;border-radius:10pt}.photo{width:68pt;height:68pt;border-radius:50%;background:${t.soft};border:5pt solid #fff;display:flex;align-items:center;justify-content:center;color:${t.accent};font-size:18pt;font-weight:800}`
 let layout=''
 if(t.layout==='sidebar')layout=`.page{display:table}.side,.main{display:table-cell;vertical-align:top}.side{width:31%;background:${t.accent};color:#fff;padding:28pt 18pt}.side .contact,.side h2,.side p{color:#fff}.side .section h2{border-color:rgba(255,255,255,.3)}.main{width:69%;padding:34pt 30pt}.photo{background:#fff;color:${t.accent};margin-bottom:20pt}`
 else if(t.layout==='split')layout=`.page{padding:30pt}.top{background:${t.soft};padding:22pt;border-left:8pt solid ${t.accent};display:table;width:100%}.topcopy,.topphoto{display:table-cell;vertical-align:middle}.topphoto{width:78pt}.body{display:table;width:100%;margin-top:17pt}.left,.right{display:table-cell;vertical-align:top}.left{width:32%;padding-right:16pt}.right{width:68%;border-left:1pt solid #e5e7eb;padding-left:19pt}`
 else if(t.layout==='timeline')layout=`.page{padding:34pt}.head{border-bottom:5pt solid ${t.accent};padding-bottom:16pt}.body{display:table;width:100%}.left,.right{display:table-cell;vertical-align:top}.left{width:68%;padding-right:22pt}.right{width:32%;background:${t.soft};padding:16pt}.job{border-left:2pt solid ${t.accent};padding-left:13pt}`
 else if(t.layout==='compact')layout=`.page{padding:30pt}.head{display:table;width:100%;border-bottom:1pt solid #d8dde5;padding-bottom:14pt}.topcopy,.topphoto{display:table-cell;vertical-align:middle}.topphoto{width:76pt}.columns{column-count:2;column-gap:24pt}.section{break-inside:avoid}.section h2{background:${t.soft};padding:5pt 7pt;border:0}`
 else if(t.layout==='editorial')layout=`.page{padding:42pt 38pt}.head{padding-bottom:19pt;border-bottom:1pt solid ${t.ink}}.name{font-family:Georgia,serif;font-size:34pt;font-weight:500}.role{letter-spacing:.8pt}.section h2{font-family:Arial,sans-serif;color:${t.ink};border-left:4pt solid ${t.accent};border-bottom:0;padding:2pt 0 2pt 8pt}.body{max-width:520pt}`
 else layout=`.page{padding:38pt}.head{border-top:9pt solid ${t.accent};padding-top:22pt}.body{margin-top:18pt}`
 return common+layout+variantCss(t)
}
function sections(t:CvTemplate){return `<div class="section"><h2>Perfil profesional</h2><p>${esc(sample.summary)}</p></div><div class="section"><h2>Experiencia</h2>${sample.experience.map(x=>`<div class="job"><b>${esc(x[0])} · ${esc(x[1])}</b><small>${esc(x[2])}</small><p>${esc(x[3])}</p></div>`).join('')}</div><div class="section"><h2>Formación</h2><ul>${sample.education.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></div><div class="section"><h2>Habilidades</h2><p>${sample.skills.map(x=>`<span class="skill">${esc(x)}</span>`).join('')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join(' · ')}</p></div>`}
function contact(){return `<div class="contact">${esc(sample.location)}<br>${esc(sample.phone)}<br>${esc(sample.email)}<br>linkedin.com/in/tu-perfil</div>`}
function photo(t:CvTemplate){return t.photo?`<div class="photo">VP</div>`:''}
export function buildWordHtml(t:CvTemplate){const head=`<h1 class="name">${esc(sample.name)}</h1><div class="role">${esc(sample.role)}</div>`;let body='';if(t.layout==='sidebar')body=`<div class="page"><aside class="side">${photo(t)}${contact()}<div class="section"><h2>Habilidades</h2><p>${sample.skills.join('<br>')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join('<br>')}</p></div></aside><main class="main">${head}${sections(t)}</main></div>`;else if(t.layout==='split')body=`<div class="page"><div class="top"><div class="topcopy">${head}${contact()}</div><div class="topphoto">${photo(t)}</div></div><div class="body"><div class="left"><div class="section"><h2>Habilidades</h2><p>${sample.skills.map(x=>`<span class="skill">${x}</span>`).join('')}</p></div><div class="section"><h2>Idiomas</h2><p>${sample.languages.join('<br>')}</p></div></div><div class="right">${sections(t)}</div></div></div>`;else if(t.layout==='timeline')body=`<div class="page"><div class="head">${head}${contact()}</div><div class="body"><div class="left">${sections(t)}</div><aside class="right">${photo(t)}<div class="section"><h2>Fortalezas</h2><p>${sample.skills.join('<br>')}</p></div></aside></div></div>`;else if(t.layout==='compact')body=`<div class="page"><div class="head"><div class="topcopy">${head}${contact()}</div><div class="topphoto">${photo(t)}</div></div><div class="columns">${sections(t)}</div></div>`;else body=`<div class="page"><div class="head">${photo(t)}${head}${contact()}</div><div class="body">${sections(t)}</div></div>`;return `<!doctype html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:w="urn:schemas-microsoft-com:office:word"><head><meta charset="utf-8"><meta name="postula-template" content="${t.id}"><title>${esc(t.name)} · Postulá Mejor</title><style>${wordCss(t)}</style></head><body><!-- ${PM_TEMPLATE_MARKER}${t.id}:v2 --><span class="marker">${PM_TEMPLATE_MARKER}${t.id}:v2</span>${body}</body></html>`}
export function downloadWordTemplate(t:CvTemplate){blobDownload(new Blob(['\ufeff',buildWordHtml(t)],{type:'application/msword;charset=utf-8'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}.doc`)}
function hex(v:string){const h=v.replace('#','');return [parseInt(h.slice(0,2),16)/255,parseInt(h.slice(2,4),16)/255,parseInt(h.slice(4,6),16)/255] as const}
function wrap(text:string,max=72){const words=text.split(/\s+/),rows:string[]=[];let line='';for(const w of words){if((line+' '+w).trim().length>max){rows.push(line);line=w}else line=(line+' '+w).trim()}if(line)rows.push(line);return rows}
export async function downloadPdfTemplate(t:CvTemplate){const doc=await PDFDocument.create();doc.setTitle(`${t.name} · Postulá Mejor`);doc.setSubject(`${PM_TEMPLATE_MARKER}${t.id}:v2`);const p=doc.addPage([595.28,841.89]);const regular=await doc.embedFont(StandardFonts.Helvetica),bold=await doc.embedFont(StandardFonts.HelveticaBold);const [r,g,b]=hex(t.accent),accent=rgb(r,g,b),ink=rgb(.09,.1,.13),muted=rgb(.38,.41,.46);if(t.layout==='sidebar')p.drawRectangle({x:0,y:0,width:174,height:842,color:accent});else if(t.layout==='split')p.drawRectangle({x:38,y:676,width:519,height:105,color:rgb(.96,.97,.99)});else p.drawRectangle({x:0,y:806,width:595,height:36,color:accent});let x=t.layout==='sidebar'?198:48,y=758;p.drawText(sample.name,{x,y,size:25,font:bold,color:ink});y-=29;p.drawText(sample.role,{x,y,size:11.5,font:bold,color:accent});y-=20;p.drawText(`${sample.location} · ${sample.email}`,{x,y,size:8.2,font:regular,color:muted});y-=34;const section=(title:string,lines:string[])=>{p.drawText(title.toUpperCase(),{x,y,size:8.8,font:bold,color:accent});y-=15;for(const line of lines){for(const row of wrap(line,t.layout==='sidebar'?54:76)){p.drawText(row,{x,y,size:8.4,font:regular,color:ink});y-=11.5}y-=3}y-=8};section('Perfil profesional',[sample.summary]);section('Experiencia',sample.experience.map(e=>`${e[0]} · ${e[1]} · ${e[2]} — ${e[3]}`));section('Formación',sample.education);section('Habilidades',[sample.skills.join(' · ')]);p.drawText(`${PM_TEMPLATE_MARKER}${t.id}:v2`,{x:20,y:15,size:2,font:regular,color:rgb(1,1,1)});const bytes=await doc.save();blobDownload(new Blob([bytes as BlobPart],{type:'application/pdf'}),`PostulaMejor-${t.name.replace(/[^a-z0-9]+/gi,'-')}.pdf`)}
