import "jsr:@supabase/functions-js/edge-runtime.d.ts";
const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!,SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!,TRIAL_DAYS=14,MONTHLY_PRICE=14900;
const countries=['Argentina','Bolivia','Brasil','Chile','Colombia','Costa Rica','Cuba','Ecuador','El Salvador','Guatemala','Honduras','México','Nicaragua','Panamá','Paraguay','Perú','República Dominicana','Uruguay','Venezuela','España'];
function allowedOrigin(req:Request){const o=req.headers.get('origin')||'';return o==='https://comerciolleno.com'||o==='https://www.comerciolleno.com'||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(o)?o:'https://www.comerciolleno.com'}
function cors(req:Request){return{'Access-Control-Allow-Origin':allowedOrigin(req),'Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(req:Request,b:unknown,s=200){return Response.json(b,{status:s,headers:cors(req)})}function headers(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,'Content-Type':'application/json',...extra}}
async function rest(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:headers(init.headers as Record<string,string>||{})})}
function strong(v:string){return v.length>=8&&/[A-Z]/.test(v)&&/\d/.test(v)&&/[^A-Za-z0-9]/.test(v)}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{ok:false,error:'Método no permitido'},405);let body:any={};try{body=await req.json()}catch{return json(req,{ok:false,error:'Solicitud inválida'},400)}if(String(body.website||'').trim())return json(req,{ok:true},200);
 const email=String(body.email||'').trim().toLowerCase(),password=String(body.password||''),companyName=String(body.company_name||'').trim(),fullName=String(body.full_name||'').trim(),phone=String(body.phone||'').trim(),taxId=String(body.tax_id||'').trim(),country=String(body.country||'').trim(),province=String(body.province||'').trim(),address=String(body.address||'').trim(),requestedComplete=body.onboarding_complete===true;
 if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email))return json(req,{ok:false,error:'Ingresá un email válido.'},400);if(!strong(password))return json(req,{ok:false,error:'La contraseña debe tener mínimo 8 caracteres, una mayúscula, un número y un signo especial.'},400);if(companyName.length<2||companyName.length>120)return json(req,{ok:false,error:'Ingresá el nombre de tu comercio.'},400);if(fullName.length<2||fullName.length>120)return json(req,{ok:false,error:'Ingresá tu nombre.'},400);if(phone.length<6)return json(req,{ok:false,error:'Ingresá el WhatsApp del propietario.'},400);
 const complete=requestedComplete&&taxId.length>=7&&countries.includes(country)&&(country!=='Argentina'||province.length>1);if(requestedComplete&&!complete)return json(req,{ok:false,error:'Faltan CUIT/CUIL, país o provincia para completar la configuración.'},400);
 let userId='',companyId='';try{const ur=await fetch(`${SUPABASE_URL}/auth/v1/admin/users`,{method:'POST',headers:headers(),body:JSON.stringify({email,password,email_confirm:true,user_metadata:{full_name:fullName,company_name:companyName,signup_source:'14_day_trial',phone}})});const user=await ur.json().catch(()=>({}));if(!ur.ok||!user?.id){const msg=String(user?.msg||user?.message||user?.error||'No se pudo crear la cuenta.');if(/already|registered|exists/i.test(msg))return json(req,{ok:false,error:'Ya existe una cuenta con ese email.'},409);throw new Error(msg)}userId=String(user.id);
 const cr=await rest('companies',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({name:companyName,legal_name:companyName,tax_id:complete?taxId:null,owner_phone:phone,country:complete?country:null,province:complete&&country==='Argentina'?province:null,address:complete&&address?address:null,onboarding_complete:complete})});const companies=await cr.json().catch(()=>[]);if(!cr.ok||!companies?.[0]?.id)throw new Error('No se pudo crear el comercio.');companyId=String(companies[0].id);
 const pr=await rest('profiles?on_conflict=id',{method:'POST',headers:{Prefer:'resolution=merge-duplicates,return=minimal'},body:JSON.stringify({id:userId,company_id:companyId,role:'owner',full_name:fullName,username:email,permissions:{can_sell:true,can_open_close_cash:true,can_view_reports:true,can_manage_stock:true,can_edit_products:true,can_import_export_products:true,can_manage_suppliers:true,can_manage_purchases:true,can_manage_customers:true,can_edit_customers:true,can_manage_promotions:true,can_manage_finances:true},active:true})});if(!pr.ok)throw new Error('No se pudo asociar el propietario al comercio.');
 const br=await rest('branches',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({company_id:companyId,name:companyName,address:complete&&address?address:null,country:complete?country:null,province:complete&&country==='Argentina'?province:null,is_primary:true,active:true})});if(!br.ok)throw new Error('No se pudo crear el local principal.');
 const start=new Date(),end=new Date(start.getTime()+TRIAL_DAYS*86400000);const sr=await rest('company_subscriptions',{method:'POST',headers:{Prefer:'return=representation'},body:JSON.stringify({company_id:companyId,plan:'comercio_lleno',status:'trialing',trial_started_at:start.toISOString(),trial_ends_at:end.toISOString(),price_amount:MONTHLY_PRICE,currency:'ARS'})});const subscriptions=await sr.json().catch(()=>[]);if(!sr.ok||!subscriptions?.[0])throw new Error('No se pudo activar la prueba gratuita.');return json(req,{ok:true,company_id:companyId,onboarding_complete:complete,trial_started_at:subscriptions[0].trial_started_at,trial_ends_at:subscriptions[0].trial_ends_at,price_amount:Number(subscriptions[0].price_amount||MONTHLY_PRICE),currency:subscriptions[0].currency||'ARS'});
 }catch(e){if(userId)await rest(`profiles?id=eq.${userId}`,{method:'DELETE'}).catch(()=>{});if(companyId)await rest(`companies?id=eq.${companyId}`,{method:'DELETE'}).catch(()=>{});if(userId)await fetch(`${SUPABASE_URL}/auth/v1/admin/users/${userId}`,{method:'DELETE',headers:headers()}).catch(()=>{});return json(req,{ok:false,error:e instanceof Error?e.message:String(e)},500)}})
