'use client'
import Link from 'next/link'
import {useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'
import EmployerPocket from './EmployerPocket'
type Tab='resumen'|'candidatos'|'nexo'|'equipo'
type Company={id:string;name:string;verification_status:string}
type Job={id:string;title:string;status:string;location_text?:string}
type App={id:string;status:string;candidate_snapshot?:{display_name?:string;availability?:string;experience?:string};pm_jobs?:{title?:string};pm_candidate_matches?:{score?:number}[]}
async function auth(){const {data}=await cvAuthClient().auth.getSession();return data.session}
export default function EmployerMobileHub(){const [tab,setTab]=useState<Tab>('resumen'),[company,setCompany]=useState<Company|null>(null),[jobs,setJobs]=useState<Job[]>([]),[apps,setApps]=useState<App[]>([]),[team,setTeam]=useState<any[]>([]),[loading,setLoading]=useState(true)
 useEffect(()=>{(async()=>{const session=await auth();if(!session){setLoading(false);return}const headers={Authorization:`Bearer ${session.access_token}`};const cr=await fetch('/api/postula/company',{headers});const cd=await cr.json().catch(()=>({}));const m=cd?.memberships?.[0];if(!m?.pm_companies){setLoading(false);return}const co={id:String(m.company_id),name:String(m.pm_companies.name),verification_status:String(m.pm_companies.verification_status)};setCompany(co);const [jr,ar,tr]=await Promise.all([fetch(`/api/postula/company/jobs?company=${co.id}`,{headers}),fetch(`/api/postula/applications?company=${co.id}`,{headers}),fetch(`/api/postula/company/team?company=${co.id}`,{headers})]);const [jd,ad,td]=await Promise.all([jr.json().catch(()=>({})),ar.json().catch(()=>({})),tr.json().catch(()=>({}))]);setJobs(jd.jobs||[]);setApps(ad.applications||[]);setTeam(td.members||[]);setLoading(false)})()},[])
 const stats=useMemo(()=>({received:apps.length,shortlist:apps.filter(x=>x.status==='shortlist').length,interview:apps.filter(x=>x.status==='interview').length,hired:apps.filter(x=>x.status==='hired').length}),[apps])
 if(loading)return <div className="pmm-loading">Preparando tu panel móvil…</div>
 if(!company)return <main className="pmm-empty"><h1>Panel móvil de empresa</h1><p>Ingresá y configurá tu empresa para usar el panel y Nexo.</p><Link href="/postula-acceso-preview?rol=empresa&next=/empresas-preview/movil">Ingresar</Link></main>
 return <main className="pmm-page"><header className="pmm-head"><div><span>POSTULÁ MEJOR · EMPRESA</span><b>{company.name}</b><small>{company.verification_status==='verified'?'Empresa verificada':'Validación básica'}</small></div><Link href="/empresas-preview/panel">Panel web</Link></header><nav className="pmm-tabs"><button data-on={tab==='resumen'} onClick={()=>setTab('resumen')}>Inicio</button><button data-on={tab==='candidatos'} onClick={()=>setTab('candidatos')}>Candidatos</button><button data-on={tab==='nexo'} onClick={()=>setTab('nexo')}>Nexo</button><button data-on={tab==='equipo'} onClick={()=>setTab('equipo')}>Equipo</button></nav>
 {tab==='resumen'&&<section className="pmm-content"><div className="pmm-welcome"><span>HOY</span><h1>Tu selección, en el bolsillo.</h1><p>Revisá lo importante, respondé rápido y entrá a Nexo cuando quieras pedir un resumen o una acción.</p></div><div className="pmm-stats"><article><small>Postulaciones</small><b>{stats.received}</b></article><article><small>Shortlist</small><b>{stats.shortlist}</b></article><article><small>Entrevistas</small><b>{stats.interview}</b></article><article><small>Contratados</small><b>{stats.hired}</b></article></div><div className="pmm-actions"><Link href="/empresas-preview/publicar"><span>NUEVA BÚSQUEDA</span><b>Publicar una oferta</b><small>Creá o retomá un borrador</small></Link><button onClick={()=>setTab('nexo')}><span>ASISTENTE</span><b>Preguntarle a Nexo</b><small>Texto o dictado corto</small></button><Link href="/empresas-preview/configuracion"><span>CONFIGURACIÓN</span><b>Equipo y permisos</b><small>RRHH, gerentes y roles</small></Link></div><div className="pmm-list"><div className="pmm-list-head"><h2>Búsquedas</h2><Link href="/empresas-preview/publicar">Nueva</Link></div>{jobs.slice(0,5).map(j=><article key={j.id}><div><b>{j.title}</b><small>{j.location_text||'Ubicación a confirmar'}</small></div><span>{j.status}</span></article>)}{!jobs.length&&<p className="pmm-muted">Todavía no publicaste búsquedas.</p>}</div></section>}
 {tab==='candidatos'&&<section className="pmm-content"><div className="pmm-section-title"><span>POSTULACIONES</span><h1>Personas, no planillas.</h1><p>Ordená por etapa y abrí Nexo si necesitás comparar evidencia.</p></div><div className="pmm-candidates">{apps.slice(0,40).map((a,i)=>{const snap=a.candidate_snapshot||{};const match=Array.isArray(a.pm_candidate_matches)?a.pm_candidate_matches[0]:undefined;return <article key={a.id}><span className="pmm-cavatar">{String(snap.display_name||`C${i+1}`).slice(0,2).toUpperCase()}</span><div><b>{snap.display_name||'Candidato/a'}</b><small>{a.pm_jobs?.title||'Postulación'} · {snap.availability||'disponibilidad no informada'}</small></div>{match?.score!=null?<strong>{match.score}%</strong>:<span>{a.status}</span>}</article>})}{!apps.length&&<p className="pmm-muted">Todavía no entraron postulaciones.</p>}</div><button className="pmm-nexo-cta" onClick={()=>setTab('nexo')}>Preguntarle a Nexo sobre estos candidatos</button></section>}
 {tab==='nexo'&&<section className="pmm-nexo"><div className="pmm-nexo-back"><button onClick={()=>setTab('resumen')}>← Volver al panel</button></div><EmployerPocket embedded/></section>}
 {tab==='equipo'&&<section className="pmm-content"><div className="pmm-section-title"><span>EQUIPO</span><h1>Un acceso por persona.</h1><p>No compartan claves. Cada integrante tiene un rol y permisos dentro de esta empresa.</p></div><div className="pmm-team">{team.map((m,i)=><article key={m.user_id}><span>{i+1}</span><div><b>{m.role==='owner'?'Propietario':'Miembro del equipo'}</b><small>{m.role} · {m.status}</small></div></article>)}</div><Link className="pmm-settings" href="/empresas-preview/configuracion">Administrar usuarios y roles</Link></section>}
 <footer className="pmm-foot">© 2026 Postulá Mejor · Seguridad y privacidad</footer></main>}
