import type {Metadata} from 'next'
const icon='/postula-mejor-favicon.svg'
export const metadata:Metadata={metadataBase:new URL('https://postulamejor.com'),title:{absolute:'Privacidad | Postulá Mejor'},description:'Cómo Postulá Mejor trata información de cuentas, CV, postulaciones, empresas, mensajes y soporte.',applicationName:'Postulá Mejor',robots:{index:false,follow:true},icons:{icon:[{url:icon,type:'image/svg+xml',sizes:'any'}],shortcut:icon,apple:icon}}
const box:React.CSSProperties={maxWidth:860,margin:'0 auto',padding:'40px 18px 80px',fontFamily:'Inter,system-ui,sans-serif',color:'#15171a',lineHeight:1.62};const h2:React.CSSProperties={fontSize:22,letterSpacing:'-.03em',marginTop:34};const p:React.CSSProperties={fontSize:14,color:'#555c66'};const note:React.CSSProperties={...p,background:'#f5f4ff',border:'1px solid #e6e2ff',borderRadius:14,padding:'13px 15px'}
export default function PrivacyPage(){return <main style={{background:'#fff',minHeight:'100vh'}}><article style={box}><a href="/" style={{color:'#5b49df',fontWeight:800,textDecoration:'none'}}>← Postulá Mejor</a><h1 style={{fontSize:42,lineHeight:1,letterSpacing:'-.055em',margin:'26px 0 12px'}}>Privacidad y tratamiento de la información</h1><p style={p}>Versión vigente: 21 de agosto de 2026.</p><p style={p}>Postulá Mejor es un producto digital de Llena Group, operado por Gabriel Alejandro Granvillano, CUIT 20-38422407-6. Esta política explica qué información usamos, para qué y con quién puede compartirse para operar la plataforma.</p><p style={note}><b>Registramos consentimientos relevantes.</b> Guardamos la versión aceptada, fecha y hora, usuario y referencias técnicas necesarias para acreditar la aceptación de Términos y Privacidad cuando el flujo lo requiere.</p>
<h2 style={h2}>Qué información procesamos</h2><p style={p}>Según las funciones que uses podemos tratar datos de cuenta, email, perfil laboral, CV, experiencia, formación, habilidades, disponibilidad, preferencias, postulaciones, mensajes, entrevistas, publicaciones, Trabajo Flex, datos de empresa, miembros del equipo, planes, pagos, créditos, tickets de soporte y reportes de seguridad.</p>
<h2 style={h2}>CV y materiales laborales</h2><p style={p}>Los archivos de CV se utilizan para extraer la información necesaria para prestar el servicio. Podemos conservar hechos profesionales estructurados, diagnósticos y materiales generados para mantener continuidad. La foto del CV, si se usa, se carga de forma voluntaria y se almacena en espacio privado.</p>
<h2 style={h2}>Cuentas y confirmación de correo</h2><p style={p}>La autenticación se gestiona mediante Supabase Auth y las contraseñas no se almacenan en texto legible por Postulá Mejor. Las cuentas nuevas requieren confirmar el correo electrónico. Podemos enviar mensajes operativos para confirmar el email, recuperar acceso, avisar cambios de seguridad, responder soporte y comunicar hechos necesarios para operar la cuenta.</p>
<h2 style={h2}>Postulaciones y datos visibles para empresas</h2><p style={p}>Cuando te postulás, la empresa correspondiente puede acceder a la información necesaria para evaluar esa candidatura según la configuración de privacidad aplicable. Los empleadores deben utilizar esos datos únicamente para selección y mantenerlos confidenciales. Postulá Mejor puede limitar o retirar el acceso si detecta usos incompatibles con esa finalidad.</p>
<h2 style={h2}>Empleos confidenciales</h2><p style={p}>Si una empresa elige publicar con identidad reducida, Postulá Mejor conserva internamente la empresa real y su validación, mientras el candidato ve sólo la información general prevista. La identidad puede revelarse cuando la empresa decide avanzar de etapa con el candidato.</p>
<h2 style={h2}>Mensajes, reportes y soporte</h2><p style={p}>Conservamos mensajes y metadatos necesarios para habilitar las conversaciones entre usuarios. Si se reporta una posible estafa, abuso o conducta inapropiada, podemos revisar la conversación relacionada, la publicación, la cuenta y datos técnicos necesarios para investigar. Los tickets de Ayuda guardan categoría, prioridad, estado, página de origen y conversación con soporte.</p>
<h2 style={h2}>Empresas y equipos</h2><p style={p}>Podemos tratar nombre comercial, razón social cuando corresponda, rubro, ciudad, dirección cuando se aporte, datos de contacto, validaciones, miembros de equipo, roles y permisos. Esta información se usa para administrar la cuenta, prevenir suplantaciones, publicar búsquedas, controlar acceso a candidatos y facturar servicios cuando corresponda.</p>
<h2 style={h2}>Pagos y créditos</h2><p style={p}>Mercado Pago procesa el checkout y no almacenamos los datos completos de la tarjeta. Conservamos referencias de la orden, plan o pack, importe, estado, moneda, créditos y datos mínimos necesarios para habilitación, conciliación y soporte.</p>
<h2 style={h2}>Inteligencia artificial y proveedores</h2><p style={p}>Usamos infraestructura de Vercel y Supabase, modelos de OpenAI para determinadas funciones de análisis y generación, Resend para correos y Mercado Pago para pagos. Se comparte con cada proveedor únicamente la información necesaria para ejecutar la función correspondiente, conforme a sus condiciones aplicables.</p>
<h2 style={h2}>Notificaciones</h2><p style={p}>Las alertas dentro de la plataforma pueden informar mensajes, cambios de postulación, entrevistas, soporte o seguridad. Las notificaciones del navegador o dispositivo requieren autorización expresa y pueden desactivarse desde la cuenta o el navegador. Las comunicaciones estrictamente necesarias para seguridad, acceso o funcionamiento pueden no ser optativas.</p>
<h2 style={h2}>Seguridad y minimización</h2><p style={p}>Las operaciones sensibles pasan por funciones de servidor, los permisos se validan en backend y el almacenamiento privado utiliza accesos temporales cuando corresponde. Aplicamos límites, controles y registros para reducir abuso. Ningún sistema conectado a Internet puede prometer riesgo cero.</p>
<h2 style={h2}>Conservación y derechos</h2><p style={p}>Conservamos información mientras sea necesaria para prestar servicios, mantener la cuenta, resolver compras, soporte, seguridad y obligaciones operativas. Podés pedir acceso, corrección o eliminación cuando corresponda. Algunas referencias transaccionales o de seguridad pueden conservarse durante el tiempo necesario para obligaciones legales o resolución de controversias.</p>
<h2 style={h2}>Contacto</h2><p style={p}>Para privacidad, acceso o eliminación usá Ayuda dentro de tu cuenta o escribí a hola@postulamejor.com.</p></article></main>}
