import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import forge from "npm:node-forge@1.3.1";

type FiscalConfig={company_id:string;enabled:boolean;environment:'homologacion'|'produccion';tax_id:string;point_of_sale:number;receipt_type:number;credential_slot:string};
const SERVICE='wsfe';
function cors(req:Request){const o=req.headers.get('origin')||'';const allowed=new Set(['https://comerciolleno.com','https://www.comerciolleno.com']);return{'Access-Control-Allow-Origin':allowed.has(o)?o:'https://www.comerciolleno.com','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(req:Request,data:unknown,status=200){return Response.json(data,{status,headers:cors(req)})}
function esc(s:string){return s.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function dec(s:string){return s.replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/&amp;/g,'&')}
function jwtPayload(req:Request){try{const t=(req.headers.get('authorization')||'').replace(/^Bearer\s+/i,'');const p=t.split('.')[1];if(!p)return null;return JSON.parse(atob(p.replace(/-/g,'+').replace(/_/g,'/').padEnd(Math.ceil(p.length/4)*4,'=')))}catch{return null}}
function endpoints(env:string){return env==='produccion'?{wsaa:'https://wsaa.afip.gov.ar/ws/services/LoginCms',wsfe:'https://servicios1.afip.gov.ar/wsfev1/service.asmx'}:{wsaa:'https://wsaahomo.afip.gov.ar/ws/services/LoginCms',wsfe:'https://wswhomo.afip.gov.ar/wsfev1/service.asmx'}}
function pemToCmsBase64(certPem:string,keyPem:string,tra:string){const cert=forge.pki.certificateFromPem(certPem);const key=forge.pki.privateKeyFromPem(keyPem);const p7=forge.pkcs7.createSignedData();p7.content=forge.util.createBuffer(tra,'utf8');p7.addCertificate(cert);p7.addSigner({key,certificate:cert,digestAlgorithm:forge.pki.oids.sha256});p7.sign();return forge.util.encode64(forge.asn1.toDer(p7.toAsn1()).getBytes())}
function parseErrors(t:string){return [...t.matchAll(/<Err>[\s\S]*?<Code>(.*?)<\/Code>[\s\S]*?<Msg>(.*?)<\/Msg>[\s\S]*?<\/Err>/g)].map(m=>({code:m[1],msg:dec(m[2])}))}
async function adminFetch(path:string,init:RequestInit={}){const url=Deno.env.get('SUPABASE_URL')!;const key=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;return fetch(url+path,{...init,headers:{apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',...(init.headers||{})}})}
async function companyId(userId:string){const r=await adminFetch(`/rest/v1/profiles?id=eq.${encodeURIComponent(userId)}&select=company_id&limit=1`);const a=await r.json();return a?.[0]?.company_id||null}
async function config(companyId:string):Promise<FiscalConfig|null>{const r=await adminFetch(`/rest/v1/arca_tenant_settings?company_id=eq.${encodeURIComponent(companyId)}&select=company_id,enabled,environment,tax_id,point_of_sale,receipt_type,credential_slot&limit=1`);const a=await r.json();return a?.[0]||null}
async function getCachedTicket(companyId:string){const r=await adminFetch(`/rest/v1/arca_wsaa_cache?company_id=eq.${encodeURIComponent(companyId)}&service=eq.${SERVICE}&select=token,sign,expires_at&limit=1`);const a=await r.json();const row=a?.[0];if(!row)return null;if(new Date(row.expires_at).getTime()-Date.now()<120000)return null;return row}
async function saveTicket(companyId:string,t:{token:string;sign:string;expiration:string}){await adminFetch('/rest/v1/arca_wsaa_cache?on_conflict=company_id,service',{method:'POST',headers:{Prefer:'resolution=merge-duplicates'},body:JSON.stringify({company_id:companyId,service:SERVICE,token:t.token,sign:t.sign,expires_at:t.expiration,updated_at:new Date().toISOString()})})}
async function readVault(secretId:string){const r=await adminFetch('/rest/v1/rpc/arca_vault_read_secret',{method:'POST',body:JSON.stringify({p_secret_id:secretId})});const v=await r.json().catch(()=>null);if(!r.ok||typeof v!=='string')throw new Error('No se pudo leer la credencial cifrada de ARCA.');return v.trim()}
async function credentials(cfg:FiscalConfig){if(cfg.credential_slot==='pilot_default'){const cert=Deno.env.get('ARCA_CERT_PEM')?.trim(),key=Deno.env.get('ARCA_PRIVATE_KEY')?.trim();if(!cert||!key)throw new Error('La configuración piloto de ARCA está incompleta.');return{cert,key}}if(cfg.credential_slot!=='tenant_vault')throw new Error('La configuración de ARCA de este comercio está incompleta.');const r=await adminFetch(`/rest/v1/arca_tenant_credentials?company_id=eq.${encodeURIComponent(cfg.company_id)}&select=private_key_secret_id,certificate_secret_id&limit=1`);const a=await r.json();const row=a?.[0];if(!row?.private_key_secret_id||!row?.certificate_secret_id)throw new Error('Falta el certificado ARCA de este comercio.');return{cert:await readVault(row.certificate_secret_id),key:await readVault(row.private_key_secret_id)}}
async function wsaa(cfg:FiscalConfig,cert:string,key:string){const now=new Date();const tra=`<?xml version="1.0" encoding="UTF-8"?><loginTicketRequest version="1.0"><header><uniqueId>${Math.floor(now.getTime()/1000)}</uniqueId><generationTime>${new Date(now.getTime()-600000).toISOString().replace(/\.\d{3}Z$/,'-00:00')}</generationTime><expirationTime>${new Date(now.getTime()+600000).toISOString().replace(/\.\d{3}Z$/,'-00:00')}</expirationTime></header><service>${SERVICE}</service></loginTicketRequest>`;const cms=pemToCmsBase64(cert,key,tra);const soap=`<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/" xmlns:log="http://wsaa.view.sua.dvadac.desein.afip.gov"><soapenv:Header/><soapenv:Body><log:loginCms><log:in0>${esc(cms)}</log:in0></log:loginCms></soapenv:Body></soapenv:Envelope>`;const r=await fetch(endpoints(cfg.environment).wsaa,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':''},body:soap});const text=await r.text();if(!r.ok||/faultcode|faultstring/i.test(text))throw new Error(`WSAA: ${dec(text.match(/<faultstring>([\s\S]*?)<\/faultstring>/i)?.[1]||text.slice(0,800))}`);const d=dec(text.match(/<loginCmsReturn>([\s\S]*?)<\/loginCmsReturn>/)?.[1]||'');const token=d.match(/<token>([\s\S]*?)<\/token>/)?.[1],sign=d.match(/<sign>([\s\S]*?)<\/sign>/)?.[1],expiration=d.match(/<expirationTime>([\s\S]*?)<\/expirationTime>/)?.[1];if(!token||!sign||!expiration)throw new Error('WSAA no devolvió Token/Sign');return{token,sign,expiration}}
async function wsfe(cfg:FiscalConfig,action:string,inner:string){const soap=`<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body>${inner}</soap:Body></soap:Envelope>`;const r=await fetch(endpoints(cfg.environment).wsfe,{method:'POST',headers:{'Content-Type':'text/xml; charset=utf-8','SOAPAction':`http://ar.gov.afip.dif.FEV1/${action}`},body:soap});const text=await r.text();if(!r.ok||/faultcode|faultstring/i.test(text))throw new Error(`WSFE ${action}: ${dec(text.match(/<faultstring>([\s\S]*?)<\/faultstring>/i)?.[1]||text.slice(0,1000))}`);return text}
function auth(cfg:FiscalConfig,token:string,sign:string){return `<Auth><Token>${esc(token)}</Token><Sign>${esc(sign)}</Sign><Cuit>${esc(cfg.tax_id)}</Cuit></Auth>`}
async function points(cfg:FiscalConfig,token:string,sign:string){const t=await wsfe(cfg,'FEParamGetPtosVenta',`<FEParamGetPtosVenta xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}</FEParamGetPtosVenta>`);return{values:[...t.matchAll(/<PtoVenta>[\s\S]*?<Nro>(.*?)<\/Nro>[\s\S]*?<EmisionTipo>(.*?)<\/EmisionTipo>[\s\S]*?<Bloqueado>(.*?)<\/Bloqueado>[\s\S]*?<FchBaja>(.*?)<\/FchBaja>[\s\S]*?<\/PtoVenta>/g)].map(m=>({nro:Number(m[1]),emision_tipo:m[2],bloqueado:m[3],fecha_baja:m[4]})),errors:parseErrors(t)}}
async function last(cfg:FiscalConfig,token:string,sign:string){const t=await wsfe(cfg,'FECompUltimoAutorizado',`<FECompUltimoAutorizado xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}<PtoVta>${cfg.point_of_sale}</PtoVta><CbteTipo>${cfg.receipt_type}</CbteTipo></FECompUltimoAutorizado>`);const n=t.match(/<CbteNro>(.*?)<\/CbteNro>/)?.[1];return{value:n===undefined?null:Number(n),errors:parseErrors(t)}}
async function vat(cfg:FiscalConfig,token:string,sign:string){const t=await wsfe(cfg,'FEParamGetCondicionIvaReceptor',`<FEParamGetCondicionIvaReceptor xmlns="http://ar.gov.afip.dif.FEV1/">${auth(cfg,token,sign)}<ClaseCmp>C</ClaseCmp></FEParamGetCondicionIvaReceptor>`);return{values:[...t.matchAll(/<CondicionIvaReceptor>[\s\S]*?<Id>(.*?)<\/Id>[\s\S]*?<Desc>(.*?)<\/Desc>[\s\S]*?<Cmp_Clase>(.*?)<\/Cmp_Clase>[\s\S]*?<\/CondicionIvaReceptor>/g)].map(m=>({id:Number(m[1]),desc:dec(m[2]),clase:m[3]})),errors:parseErrors(t)}}
Deno.serve(async(req:Request)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return new Response('Method not allowed',{status:405,headers:cors(req)});const p=jwtPayload(req);if(!p||p.role!=='authenticated'||!p.sub)return json(req,{ok:false,configured:false,error:'Se requiere una sesión autenticada'},401);try{const cid=await companyId(p.sub);if(!cid)return json(req,{ok:false,configured:false,error:'El usuario no tiene comercio asociado'},403);const cfg=await config(cid);if(!cfg?.enabled)return json(req,{ok:false,configured:false,error:'ARCA no está configurado para este comercio.'},412);let ticket=await getCachedTicket(cid);let source='cache';if(!ticket){const c=await credentials(cfg);ticket=await wsaa(cfg,c.cert,c.key);source='wsaa';await saveTicket(cid,ticket)}const ps=await points(cfg,ticket.token,ticket.sign);const la=await last(cfg,ticket.token,ticket.sign);const v=await vat(cfg,ticket.token,ticket.sign);const consumer=v.values.find(x=>/consumidor\s+final/i.test(x.desc));return json(req,{ok:true,configured:true,environment:cfg.environment,service:'wsfev1',ticket_source:source,points_of_sale:ps.values,points_of_sale_errors:ps.errors,test_point_of_sale:cfg.point_of_sale,test_receipt_type:cfg.receipt_type,last_authorized:la.value,last_authorized_errors:la.errors,receiver_vat_conditions:v.values,receiver_vat_condition_errors:v.errors,consumer_final_condition:consumer||null,ready_to_issue:!!consumer})}catch(e){return json(req,{ok:false,configured:true,error:e instanceof Error?e.message:String(e)},500)}});
