import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const SUPABASE_URL=Deno.env.get('SUPABASE_URL')!;
const SERVICE_ROLE=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!;
const PUBLISHABLE_KEY=Deno.env.get('SUPABASE_ANON_KEY')||Deno.env.get('SUPABASE_PUBLISHABLE_KEY')||SERVICE_ROLE;
const CLIENT_ID=Deno.env.get('MERCADOPAGO_POINT_CLIENT_ID')||'';
const CLIENT_SECRET=Deno.env.get('MERCADOPAGO_POINT_CLIENT_SECRET')||'';
const OWN_ACCESS_TOKEN=Deno.env.get('MERCADOPAGO_POINT_ACCESS_TOKEN')||Deno.env.get('MERCADOPAGO_ACCESS_TOKEN')||'';
const MP_API='https://api.mercadopago.com';

function originAllowed(origin:string){return origin==='https://comerciolleno.com'||origin==='https://www.comerciolleno.com'||/^https:\/\/[-a-z0-9]+\.vercel\.app$/i.test(origin)}
function cors(req:Request){const origin=req.headers.get('origin')||'';return{'Access-Control-Allow-Origin':originAllowed(origin)?origin:'https://comerciolleno.com','Vary':'Origin','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS'}}
function json(req:Request,body:unknown,status=200){return Response.json(body,{status,headers:cors(req)})}
function adminHeaders(extra:Record<string,string>={}){return{apikey:SERVICE_ROLE,Authorization:`Bearer ${SERVICE_ROLE}`,'Content-Type':'application/json',...extra}}
async function adminRest(path:string,init:RequestInit={}){return fetch(`${SUPABASE_URL}/rest/v1/${path}`,{...init,headers:adminHeaders(init.headers as Record<string,string>||{}),cache:'no-store'})}
function b64url(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}
async function sha256(value:string){return new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(value)))}
async function aesKey(){const seed=Deno.env.get('MERCADOPAGO_POINT_ENCRYPTION_KEY')||SERVICE_ROLE;return crypto.subtle.importKey('raw',await sha256(seed),{name:'AES-GCM'},false,['decrypt','encrypt'])}
function decodeB64url(value:string){const normalized=value.replace(/-/g,'+').replace(/_/g,'/'),padded=normalized+'='.repeat((4-normalized.length%4)%4),raw=atob(padded);return Uint8Array.from(raw,c=>c.charCodeAt(0))}
async function decryptText(value:string){if(!value)return'';const[version,ivRaw,dataRaw]=value.split('.');if(version!=='v1'||!ivRaw||!dataRaw)throw new Error('TOKEN_CIPHER_INVALID');const plain=await crypto.subtle.decrypt({name:'AES-GCM',iv:decodeB64url(ivRaw)},await aesKey(),decodeB64url(dataRaw));return new TextDecoder().decode(plain)}
async function encryptText(value:string){if(!value)return'';const iv=new Uint8Array(12);crypto.getRandomValues(iv);const encrypted=new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},await aesKey(),new TextEncoder().encode(value)));return`v1.${b64url(iv)}.${b64url(encrypted)}`}

async function authContext(req:Request){const auth=req.headers.get('authorization')||'',token=auth.replace(/^Bearer\s+/i,'');if(!token)throw new Error('UNAUTHORIZED');const userResponse=await fetch(`${SUPABASE_URL}/auth/v1/user`,{headers:{Authorization:`Bearer ${token}`,apikey:PUBLISHABLE_KEY},cache:'no-store'}),user=await userResponse.json().catch(()=>({}));if(!userResponse.ok||!user?.id)throw new Error('UNAUTHORIZED');const profileResponse=await adminRest(`profiles?id=eq.${encodeURIComponent(String(user.id))}&select=company_id,role,active,permissions&limit=1`),profiles=await profileResponse.json().catch(()=>[]),profile=Array.isArray(profiles)?profiles[0]:null;if(!profile?.company_id||profile.active===false)throw new Error('UNAUTHORIZED');return{userId:String(user.id),companyId:String(profile.company_id),role:String(profile.role||''),permissions:profile.permissions||{}}}
function ownerOnly(auth:any){if(auth.role!=='owner')throw new Error('OWNER_ONLY')}
function canSell(auth:any){return auth.role==='owner'||['cashier','seller','manager','supervisor'].includes(auth.role)||auth.permissions?.can_sell===true}
async function readConnection(companyId:string){const response=await adminRest(`mercadopago_point_connections?company_id=eq.${encodeURIComponent(companyId)}&select=*&limit=1`),rows=await response.json().catch(()=>[]);if(!response.ok)throw new Error('No se pudo leer la conexión de Mercado Pago.');return Array.isArray(rows)?rows[0]||null:null}
async function patchConnection(companyId:string,patch:Record<string,unknown>){const response=await adminRest(`mercadopago_point_connections?company_id=eq.${encodeURIComponent(companyId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({...patch,updated_at:new Date().toISOString()})});if(!response.ok){const text=await response.text();throw new Error(text||'No se pudo guardar el QR físico.')}}
async function mp(path:string,token:string,init:RequestInit={}){const response=await fetch(`${MP_API}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'});const text=await response.text();let data:any={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!response.ok){const error=new Error(String(data?.message||data?.error||data?.cause?.[0]?.description||`Mercado Pago respondió ${response.status}`));(error as any).status=response.status;throw error}return data}
async function refreshOauth(connection:any){if(!connection?.refresh_token_cipher||!CLIENT_ID||!CLIENT_SECRET)throw new Error('La autorización de Mercado Pago venció. Volvé a conectar la cuenta.');const refreshToken=await decryptText(String(connection.refresh_token_cipher));const response=await fetch(`${MP_API}/oauth/token`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({client_id:CLIENT_ID,client_secret:CLIENT_SECRET,grant_type:'refresh_token',refresh_token:refreshToken}),cache:'no-store'}),data=await response.json().catch(()=>({}));if(!response.ok||!data?.access_token)throw new Error(data?.message||'No se pudo renovar Mercado Pago.');await patchConnection(String(connection.company_id),{access_token_cipher:await encryptText(String(data.access_token)),refresh_token_cipher:await encryptText(String(data.refresh_token||refreshToken)),token_expires_at:new Date(Date.now()+Number(data.expires_in||15552000)*1000).toISOString(),mp_user_id:String(data.user_id||connection.mp_user_id||'')});return String(data.access_token)}
async function tokenFor(connection:any){if(!connection)throw new Error('Conectá Mercado Pago antes de vincular el QR físico.');const expires=connection.token_expires_at?new Date(connection.token_expires_at).getTime():0;if(connection.access_token_cipher&&(!expires||expires>Date.now()+300000))return decryptText(String(connection.access_token_cipher));if(String(connection.connection_mode||'oauth')==='own'&&OWN_ACCESS_TOKEN)return OWN_ACCESS_TOKEN;return refreshOauth(connection)}
async function resolveMpUser(connection:any,token:string){if(connection?.mp_user_id)return String(connection.mp_user_id);const me=await mp('/users/me',token);const id=String(me?.id||'');if(!id)throw new Error('Mercado Pago no devolvió el usuario de la cuenta.');await patchConnection(String(connection.company_id),{mp_user_id:id});return id}
function posView(pos:any){return{id:String(pos?.id||''),name:String(pos?.name||'Caja Mercado Pago'),external_id:String(pos?.external_id||''),store_id:String(pos?.store_id||''),external_store_id:String(pos?.external_store_id||''),status:String(pos?.status||''),fixed_amount:pos?.fixed_amount===true,qr_image:String(pos?.qr?.image||''),qr_template_document:String(pos?.qr?.template_document||''),qr_template_image:String(pos?.qr?.template_image||'')}}
function orderView(order:any){const payment=Array.isArray(order?.transactions?.payments)?order.transactions.payments[0]||{}:{};const status=String(order?.status||'');return{id:String(order?.id||''),status,status_detail:String(order?.status_detail||payment?.status_detail||''),external_reference:String(order?.external_reference||''),payment_id:String(payment?.id||''),payment_status:String(payment?.status||''),approved:status==='processed',final:['processed','failed','canceled','expired','refunded','action_required'].includes(status)}}

Deno.serve(async(req:Request)=>{
  if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors(req)});if(req.method!=='POST')return json(req,{ok:false,error:'Método no permitido.'},405)
  let auth:any;try{auth=await authContext(req)}catch{return json(req,{ok:false,error:'Sesión no disponible.'},401)}
  let body:any={};try{body=await req.json()}catch{}
  const action=String(body?.action||'status')
  try{
    const connection=await readConnection(auth.companyId)
    if(action==='status'){return json(req,{ok:true,account_connected:Boolean(connection&&(connection.access_token_cipher||OWN_ACCESS_TOKEN)),linked:Boolean(connection?.qr_external_pos_id),qr:connection?.qr_external_pos_id?{pos_id:connection.qr_pos_id,external_pos_id:connection.qr_external_pos_id,store_id:connection.qr_store_id,external_store_id:connection.qr_external_store_id,name:connection.qr_name,image:connection.qr_image_url,template:connection.qr_template_url,linked_at:connection.qr_linked_at}:null})}
    const token=await tokenFor(connection)
    if(action==='list_pos'){ownerOnly(auth);const data=await mp('/pos?limit=100&offset=0',token);return json(req,{ok:true,positions:(Array.isArray(data?.results)?data.results:[]).map(posView)})}
    if(action==='list_stores'){ownerOnly(auth);const userId=await resolveMpUser(connection,token),data=await mp(`/users/${encodeURIComponent(userId)}/stores/search?limit=100&offset=0`,token);const raw=Array.isArray(data?.results)?data.results:Array.isArray(data?.[0]?.results)?data[0].results:[];return json(req,{ok:true,stores:raw.map((store:any)=>({id:String(store?.id||''),name:String(store?.name||'Sucursal'),external_id:String(store?.external_id||''),location:store?.location||null}))})}
    if(action==='select_pos'){ownerOnly(auth);const id=String(body?.pos_id||'');if(!/^\d+$/.test(id))throw new Error('Elegí una caja válida.');const pos=await mp(`/pos/${encodeURIComponent(id)}`,token),view=posView(pos);if(!view.external_id)throw new Error('La caja elegida no tiene external_id y no sirve para QR integrado.');await patchConnection(auth.companyId,{qr_pos_id:view.id,qr_external_pos_id:view.external_id,qr_store_id:view.store_id||null,qr_external_store_id:view.external_store_id||null,qr_name:view.name,qr_image_url:view.qr_image||null,qr_template_url:view.qr_template_document||view.qr_template_image||null,qr_linked_at:new Date().toISOString()});return json(req,{ok:true,linked:true,qr:view})}
    if(action==='unlink'){ownerOnly(auth);await patchConnection(auth.companyId,{qr_pos_id:null,qr_external_pos_id:null,qr_store_id:null,qr_external_store_id:null,qr_name:null,qr_image_url:null,qr_template_url:null,qr_linked_at:null});return json(req,{ok:true,linked:false})}
    if(action==='create_pos'){ownerOnly(auth);const name=String(body?.name||'Caja Comercio Lleno').trim().slice(0,80),storeId=String(body?.store_id||''),externalStoreId=String(body?.external_store_id||'').trim(),externalId=String(body?.external_id||'').replace(/[^A-Za-z0-9]/g,'').slice(0,40);if(!/^\d+$/.test(storeId)||!externalStoreId||!externalId)throw new Error('Elegí una sucursal y definí un identificador de caja válido.');const pos=await mp('/pos',token,{method:'POST',body:JSON.stringify({name,fixed_amount:true,store_id:Number(storeId),external_store_id:externalStoreId,external_id:externalId,category:Number(body?.category||5499)})}),view=posView(pos);await patchConnection(auth.companyId,{qr_pos_id:view.id,qr_external_pos_id:view.external_id,qr_store_id:view.store_id||storeId,qr_external_store_id:view.external_store_id||externalStoreId,qr_name:view.name,qr_image_url:view.qr_image||null,qr_template_url:view.qr_template_document||view.qr_template_image||null,qr_linked_at:new Date().toISOString()});return json(req,{ok:true,linked:true,qr:view})}
    if(action==='create_order'){if(!canSell(auth))throw new Error('No tenés permiso para cobrar.');if(!connection?.qr_external_pos_id)throw new Error('Vinculá un QR físico en Configuración > Mercado Pago.');const amount=Number(body?.amount||0);if(!(amount>0))throw new Error('El importe debe ser mayor a cero.');const externalReference=String(body?.external_reference||`cl-${Date.now()}`).replace(/[^A-Za-z0-9_-]/g,'').slice(0,64),amountText=amount.toFixed(2),idempotency=String(body?.idempotency_key||crypto.randomUUID());const payload={type:'qr',processing_mode:'automatic',external_reference:externalReference,description:'Venta Comercio Lleno',total_amount:amountText,config:{qr:{external_pos_id:String(connection.qr_external_pos_id),mode:'static'}},transactions:{payments:[{amount:amountText}]},items:[{title:'Venta Comercio Lleno',unit_price:amountText,quantity:1,unit_measure:'unit'}],expiration_time:'PT15M'};const order=await mp('/v1/orders',token,{method:'POST',headers:{'X-Idempotency-Key':idempotency},body:JSON.stringify(payload)});return json(req,{ok:true,order:orderView(order)})}
    if(action==='order_status'){if(!canSell(auth))throw new Error('No tenés permiso para consultar cobros.');const id=String(body?.order_id||'');if(!/^ORD[A-Za-z0-9]+$/.test(id))throw new Error('Orden inválida.');return json(req,{ok:true,order:orderView(await mp(`/v1/orders/${encodeURIComponent(id)}`,token))})}
    if(action==='cancel_order'){if(!canSell(auth))throw new Error('No tenés permiso para cancelar cobros.');const id=String(body?.order_id||'');if(!/^ORD[A-Za-z0-9]+$/.test(id))throw new Error('Orden inválida.');return json(req,{ok:true,order:orderView(await mp(`/v1/orders/${encodeURIComponent(id)}/cancel`,token,{method:'POST'}))})}
    return json(req,{ok:false,error:'Acción no reconocida.'},400)
  }catch(error:any){const code=error?.message==='OWNER_ONLY'?403:Number(error?.status)||400;const message=error?.message==='OWNER_ONLY'?'Solo el titular puede configurar el QR físico.':String(error?.message||error);return json(req,{ok:false,error:message},code)}
})
