import Link from 'next/link'
import styles from '../postula-preview/platform.module.css'
import {PlatformFooter,PlatformHeader} from '../postula-preview/PlatformChrome'
import '../postula-preview/premium-v4.css'
import '../postula-preview/premium-v5.css'
import '../postula-preview/premium-v6.css'
import '../postula-preview/premium-v7.css'
import '../postula-preview/premium-v7-extra.css'
import './employer-v17.css'

export const metadata={
 title:{absolute:'Postulá Mejor Empresas | Contratá mejor'},
 description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde una experiencia simple, en PC y móvil, asistida por Nexo.',
 robots:{index:true,follow:true},
 alternates:{canonical:'https://postulamejor.com/empresas'},
 openGraph:{title:'Postulá Mejor Empresas | Contratá mejor',description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde PC o móvil con una experiencia simple y asistida.',url:'https://postulamejor.com/empresas'},
 twitter:{card:'summary',title:'Postulá Mejor Empresas | Contratá mejor',description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde PC o móvil.'},
}

const plans=[
 {id:'gratis',name:'Gratis',price:'$0',copy:'Para probar con una búsqueda real.',items:['2 avisos por mes · 30 días','Primeros 10 postulantes completos','Pipeline básico','Cuenta empresa sin tarjeta','✓ 1 crédito de Servicios Flex']},
 {id:'impulso',name:'Impulso',price:'$0',oldPrice:'$18.900',after:'Después $18.900 / mes',copy:'Para comercios y equipos chicos.',items:['30 días gratis al registrarte hoy','5 búsquedas activas','Hasta 250 postulaciones/mes','Aviso asistido + filtros','Exportación de CV','✓ 3 créditos de Servicios Flex por mes']},
 {id:'seleccion',name:'Selección IA',price:'$0',oldPrice:'$34.900',after:'Después $34.900 / mes',copy:'Cuando leer CV ya se volvió trabajo.',items:['30 días gratis al registrarte hoy','Hasta 2.000 postulaciones/mes','Shortlist explicada','Nexo en PC + móvil + entrevistas','Routing a RRHH','✓ 5 créditos de Servicios Flex por mes'],featured:true},
]

const compactCss=`
.pm45-compact{padding:52px 22px;background:#fff;color:#111821}.pm45-inner{width:min(1180px,100%);margin:0 auto}.pm45-kicker{display:block;margin-bottom:9px;font-size:10px;line-height:1;font-weight:950;letter-spacing:.14em;text-transform:uppercase;color:#5e62ff}.pm45-title{margin:0;font-size:clamp(30px,3.2vw,48px);line-height:.98;letter-spacing:-.045em}.pm45-sub{max-width:680px;margin:12px 0 0;color:#66737e;font-size:15px;line-height:1.55}
.pm45-steps{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px;margin-top:24px}.pm45-step{min-height:118px;padding:20px;border:1px solid #e4e8eb;border-radius:22px;background:linear-gradient(180deg,#fff,#f8faf9);box-shadow:0 14px 34px rgba(21,37,49,.06)}.pm45-step span{font-size:10px;font-weight:950;letter-spacing:.12em;color:#6e72ff}.pm45-step b{display:block;margin-top:8px;font-size:19px;line-height:1.05}.pm45-step p{margin:7px 0 0;color:#6a7680;font-size:13px;line-height:1.45}.pm45-more{display:inline-flex;align-items:center;gap:7px;margin-top:17px;color:#121922;font-size:13px;font-weight:900;text-decoration:none}.pm45-more:hover{text-decoration:underline}
.pm45-nexo{padding:24px 22px;background:#071827;color:#fff}.pm45-nexo-card{width:min(1180px,100%);margin:0 auto;min-height:132px;padding:24px 28px;border:1px solid rgba(255,255,255,.11);border-radius:25px;background:radial-gradient(circle at 85% 10%,rgba(217,255,89,.15),transparent 31%),linear-gradient(135deg,#0a2032,#071827);display:grid;grid-template-columns:1fr auto;gap:22px;align-items:center}.pm45-nexo-card small{font-size:10px;font-weight:950;letter-spacing:.13em;color:#d9ff59}.pm45-nexo-card h2{margin:7px 0 6px;font-size:clamp(28px,3vw,44px);line-height:.98;letter-spacing:-.045em}.pm45-nexo-card p{max-width:650px;margin:0;color:#bdcad1;font-size:14px;line-height:1.5}.pm45-nexo-card a{min-height:52px;padding:0 20px;border-radius:16px;background:#d9ff59;color:#071827;display:flex;align-items:center;justify-content:center;font-size:13px;font-weight:950;text-decoration:none;white-space:nowrap;box-shadow:0 14px 32px rgba(217,255,89,.14)}
.pm45-shortlist{padding:52px 22px;background:#f6f7fb}.pm45-shortlist-grid{width:min(1180px,100%);margin:20px auto 0;display:grid;grid-template-columns:minmax(0,1fr) minmax(340px,.9fr);gap:16px;align-items:stretch}.pm45-short-copy,.pm45-profile{border:1px solid #e3e7eb;border-radius:24px;background:#fff;box-shadow:0 16px 40px rgba(24,37,47,.06)}.pm45-short-copy{padding:25px}.pm45-short-copy h2{margin:7px 0 8px;font-size:clamp(30px,3.2vw,46px);line-height:1;letter-spacing:-.045em}.pm45-short-copy p{max-width:560px;margin:0;color:#66737e;font-size:14px;line-height:1.55}.pm45-short-copy a{display:inline-flex;margin-top:17px;color:#111821;font-size:13px;font-weight:900;text-decoration:none}.pm45-profile{padding:16px;display:grid;grid-template-columns:112px 1fr;gap:16px;align-items:center}.pm45-profile-photo{width:112px;height:112px;border-radius:19px;background:url('https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=400') center/cover}.pm45-profile-copy>small{font-size:9px;font-weight:950;letter-spacing:.1em;color:#6e72ff}.pm45-profile-copy h3{margin:5px 0 3px;font-size:23px;line-height:1}.pm45-profile-copy>p{margin:0;color:#6b7680;font-size:12px}.pm45-signals{display:flex;flex-wrap:wrap;gap:7px;margin-top:12px}.pm45-signals span{padding:7px 9px;border-radius:10px;background:#f2f5f6;color:#33424d;font-size:10px;font-weight:850}.pm45-signals span:first-child{background:#eaffb1;color:#24350a}.pm45-signals .pm45-rating{background:#f0edff;color:#5544ca;border:1px solid #ded8ff}.pm45-disclaimer{width:min(1180px,100%);margin:13px auto 0;color:#7a848d;font-size:10px;line-height:1.45}
body .pm7-employer .pm19-plans-ready{padding-top:64px!important;padding-bottom:64px!important}body .pm7-employer .pm19-plans-ready .pm7-section-head{margin-bottom:22px!important}body .pm7-employer .pm19-plans-ready .pm7-section-head h2{font-size:clamp(36px,4vw,56px)!important}body .pm7-employer .pm19-plans-ready .pm7-section-head>p{font-size:14px!important;line-height:1.5!important}.pm45-plan-item-flex{font-weight:900!important}.pm45-old-price{text-decoration:line-through;color:#8b9299;font-size:15px;font-weight:800;margin-bottom:4px}.pm45-after-price{display:block;margin-top:5px;color:#5f6870;font-size:12px;font-weight:800}
@media(max-width:820px){.pm45-compact,.pm45-shortlist{padding:38px 14px}.pm45-steps{grid-template-columns:1fr;gap:9px}.pm45-step{min-height:0;padding:17px}.pm45-nexo{padding:16px 12px}.pm45-nexo-card{grid-template-columns:1fr;padding:21px;border-radius:22px}.pm45-nexo-card a{width:100%}.pm45-shortlist-grid{grid-template-columns:1fr}.pm45-profile{grid-template-columns:88px 1fr}.pm45-profile-photo{width:88px;height:88px}.pm45-short-copy{padding:20px}.pm45-title{font-size:34px}.pm45-sub{font-size:14px}body .pm7-employer .pm19-plans-ready{padding-top:48px!important;padding-bottom:48px!important}}
@media(max-width:520px){.pm45-compact,.pm45-shortlist{padding-top:31px;padding-bottom:31px}.pm45-step p{font-size:12.5px}.pm45-nexo-card h2{font-size:31px}.pm45-nexo-card p{font-size:13px}.pm45-short-copy h2{font-size:31px}.pm45-profile{grid-template-columns:72px 1fr;padding:13px}.pm45-profile-photo{width:72px;height:72px;border-radius:15px}.pm45-signals span{font-size:9.5px;padding:6px 8px}}
`

export default function EmployerLanding(){return <main className={`${styles.page} pm7-page pm7-employer`}>
 <style>{compactCss}</style>
 <PlatformHeader audience="employer"/>
 <section className="pm7-employer-hero"><div className="pm7-employer-hero-inner"><div className="pm17-hero-copy"><span className="pm7-eyebrow lime">SELECCIÓN SIMPLE · DECISIÓN HUMANA</span><h1>Encontrá gente.<br/><em>Hablá. Decidí.</em></h1><p>Publicás una búsqueda, llegan perfiles ordenados y Nexo te resume lo importante desde la PC o el teléfono. Menos pestañas, más conversación y criterio humano.</p><div className="pm7-employer-actions"><Link className="pm7-btn-black" href="/empresas/publicar">Publicar gratis</Link><Link className="pm7-btn-white" href="/empresas/movil">Nexo en PC + móvil</Link></div><div className="pm17-human-proof"><div className="pm17-proof-faces"><i className="one"/><i className="two"/><i className="three"/></div><div><b>Hecho para personas que contratan mientras trabajan.</b><span>Dueños, encargados y equipos de RRHH pueden revisar, conversar y decidir sin vivir adentro de un sistema.</span></div></div><div className="pm7-employer-proof"><span>Cuenta inicial sin tarjeta</span><span>·</span><span>La decisión final siempre es humana</span><span>·</span><span>Datos sensibles fuera del ranking</span></div></div><div className="pm7-employer-console"><div className="pm17-human-card"><div className="pm17-human-photo"/><div><span>SELECCIÓN EN MOVIMIENTO</span><b>Lucía · Encargada de local</b><small>Revisando candidatos desde el teléfono</small></div></div><div className="pm7-employer-phone pm17-nexo-phone"><div className="pm17-phone-status"><b>9:41</b><span>● ◔ ▰</span></div><div className="pm17-phone-island"/><div className="pm7-employer-phone-head"><span>NX</span><div><b>Nexo</b><small>Búsqueda activa · Vendedor/a Palermo</small></div><i/></div><div className="pm7-employer-phone-chat"><div className="a"><b>Nexo</b>Entraron 12 postulaciones nuevas. Hay 5 que cumplen los requisitos que marcaste.</div><div className="q">Mostrame esas cinco y decime quién puede los sábados.</div><div className="a">Tres tienen disponibilidad confirmada. Te marco qué experiencia tiene cada uno y qué conviene validar.</div><div className="q">Prepará una shortlist para Recursos Humanos.</div><div className="a">Listo. Queda preparada para que la revises antes de compartirla.</div><div className="pm17-phone-compose"><span>Escribile a Nexo…</span><b>●</b></div></div><div className="pm17-homebar"/></div><div className="pm7-employer-float one"><small>EJEMPLO DE INTERFAZ</small><b>Shortlist explicada</b><span>Ordenada por evidencia laboral relevante</span></div><div className="pm7-employer-float two"><small>NEXO · PC + MÓVIL</small><b>Preguntá como hablás.</b><span>En escritorio abre como chat y en el celular te acompaña mientras trabajás.</span></div></div></div></section>

 <section className="pm45-compact"><div className="pm45-inner"><span className="pm45-kicker">CÓMO FUNCIONA</span><h2 className="pm45-title">Publicá. Recibí. Hablá.</h2><p className="pm45-sub">Tres pasos simples. Lo demás queda atrás.</p><div className="pm45-steps"><article className="pm45-step"><span>01 · PUBLICÁ</span><b>Contá qué necesitás.</b><p>Armás el aviso y lo revisás antes de publicarlo.</p></article><article className="pm45-step"><span>02 · RECIBÍ</span><b>Los perfiles llegan ordenados.</b><p>Ves rápido qué conviene revisar.</p></article><article className="pm45-step"><span>03 · HABLÁ</span><b>Preguntale a Nexo.</b><p>Compará candidatos y prepará entrevistas.</p></article></div><Link className="pm45-more" href="/empresas/movil">Ver cómo funciona Nexo <span>→</span></Link></div></section>

 <section className="pm45-nexo"><div className="pm45-nexo-card"><div><small>NEXO · PC + MÓVIL</small><h2>Tu búsqueda, donde estés.</h2><p>Revisá candidatos y hacé preguntas desde la computadora o el teléfono.</p></div><Link href="/empresas/movil">Ver Nexo <span>→</span></Link></div></section>

 <section className="pm45-shortlist"><div className="pm45-inner"><span className="pm45-kicker">SHORTLIST EXPLICADA</span></div><div className="pm45-shortlist-grid"><div className="pm45-short-copy"><h2>Menos CV para leer. Más contexto para decidir.</h2><p>Un ejemplo alcanza: ajuste al aviso, disponibilidad, experiencia e indicador laboral, sin convertir ninguna señal en una decisión automática.</p><Link href="/politica-evaluaciones">Cómo funciona la evaluación <span>→</span></Link></div><article className="pm45-profile"><div className="pm45-profile-photo"/><div className="pm45-profile-copy"><small>EJEMPLO ILUSTRATIVO</small><h3>Perfil A</h3><p>Ventas · caja · retail</p><div className="pm45-signals"><span>94% ajuste</span><span className="pm45-rating">★ 4,7 · Favorable · 8 experiencias</span><span>Full time · sábados</span><span>3 años retail</span></div></div></article></div><p className="pm45-disclaimer">El indicador laboral se activa a partir de 3 experiencias finalizadas. Antes aparece como “Indicador en formación”. Las evaluaciones dentro del plazo de 10 días todavía no se computan.</p></section>

 <section className="pm7-employer-section pm19-plans-ready"><div className="pm7-employer-section-inner"><div className="pm7-section-head"><div><span className="pm7-eyebrow blue">PLANES PARA EMPRESAS</span><h2>Probá 30 días gratis. Después decidís.</h2></div><p>Gratis sigue en $0. Impulso y Selección IA se activan hoy sin pago durante 30 días. Antes de vencer te avisamos; si no continuás, volvés automáticamente al plan Gratis.</p></div><div className="pm7-employer-plans">{plans.map(plan=><article data-plan={plan.id} className={`pm7-employer-plan ${plan.featured?'featured':''}`} key={plan.name}><span>{plan.name.toUpperCase()}</span><h3>{plan.copy}</h3>{plan.oldPrice?<div className="pm45-old-price">{plan.oldPrice}</div>:null}<div className="price">{plan.price}{plan.price==='$0'&&plan.id!=='gratis'?<small> · 30 días</small>:null}</div>{plan.after?<small className="pm45-after-price">{plan.after}</small>:null}<ul>{plan.items.map(i=><li className={i.includes('Servicios Flex')?'pm45-plan-item-flex':''} key={i}>{i}</li>)}</ul><Link href={`/empresas/registro?plan=${plan.id}`}>{plan.id==='gratis'?'Crear cuenta gratis':`Activar ${plan.name} gratis 30 días`}</Link></article>)}</div></div></section>

 <section className="pmv6-faq pm7-faq"><div className="pmv6-faq-inner"><div className="pmv6-faq-head"><div><span className="pm7-eyebrow lime">PREGUNTAS RÁPIDAS</span><h2>Lo importante, sin vueltas.</h2></div><p>La IA ayuda a ordenar y explicar. La decisión sigue siendo humana.</p></div><div className="pmv6-faq-list"><details><summary>¿La IA descarta candidatos automáticamente?</summary><p>No. Ordena información relevante y explica coincidencias o dudas, pero la decisión de avanzar sigue siendo humana.</p></details><details><summary>¿Nexo funciona en PC y teléfono?</summary><p>Sí. Podés revisar candidatos y consultar tu búsqueda desde ambos.</p></details><details><summary>¿Los datos de una empresa se mezclan con otra?</summary><p>No. Cada empresa trabaja dentro de su propio contexto.</p></details></div></div></section>

 <section className="pm7-final"><div><span>POSTULÁ MEJOR EMPRESAS</span><h2>Que contratar se parezca más a hablar con gente.</h2></div><div><Link href="/empresas/publicar" className="pm7-btn-black">Publicar una búsqueda</Link><Link href="/empresas/movil" className="pm7-btn-white">Nexo · PC + móvil</Link></div></section>
 <PlatformFooter/>
 </main>}
