import Link from 'next/link'
import styles from '../postula-preview/platform.module.css'
import {PlatformFooter,PlatformHeader} from '../postula-preview/PlatformChrome'
import EmployerReputationShowcase from './EmployerReputationShowcase'
import '../postula-preview/premium-v4.css'
import '../postula-preview/premium-v5.css'
import '../postula-preview/premium-v6.css'
import '../postula-preview/premium-v7.css'
import '../postula-preview/premium-v7-extra.css'
import './employer-v17.css'
import './employer-reputation-v37.css'

export const metadata={
 title:{absolute:'Postulá Mejor Empresas | Contratá mejor'},
 description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde una experiencia simple, en PC y móvil, asistida por Nexo.',
 robots:{index:true,follow:true},
 alternates:{canonical:'https://postulamejor.com/empresas'},
 openGraph:{title:'Postulá Mejor Empresas | Contratá mejor',description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde PC o móvil con una experiencia simple y asistida.',url:'https://postulamejor.com/empresas'},
 twitter:{card:'summary',title:'Postulá Mejor Empresas | Contratá mejor',description:'Publicá búsquedas, ordená postulaciones y conversá con candidatos desde PC o móvil.'},
}

const plans=[
 {name:'Gratis',price:'$0',copy:'Para probar con una búsqueda real.',items:['2 avisos por mes · 30 días','Primeros 10 postulantes completos','Pipeline básico','Cuenta empresa sin tarjeta']},
 {name:'Impulso',price:'$18.900',copy:'Para comercios y equipos chicos.',items:['5 búsquedas activas','Hasta 250 postulaciones/mes','Aviso asistido + filtros','Exportación de CV']},
 {name:'Selección IA',price:'$34.900',copy:'Cuando leer CV ya se volvió trabajo.',items:['Hasta 2.000 postulaciones/mes','Shortlist explicada','Nexo en PC + móvil + entrevistas','Routing a RRHH'],featured:true},
 {name:'Escala',price:'$74.900',copy:'Para varias áreas y varios usuarios.',items:['Hasta 5.000 postulaciones/mes','Roles y reglas por búsqueda','Auditoría y analítica','5 agentes especializados']},
 {name:'Empresa',price:'A medida',copy:'Volumen alto y gobierno corporativo.',items:['10.000+ postulaciones','Múltiples unidades','MFA/SSO y políticas','Integraciones acordadas']},
]

const profiles=[
 {name:'Perfil A',role:'Ventas · caja · retail',match:'94%',availability:'Full time · sábados',experience:'3 años retail',reputation:'Resumen disponible',repState:'ready',signal:'4 evaluaciones · 2 vínculos verificados',image:'https://images.pexels.com/photos/1181690/pexels-photo-1181690.jpeg?auto=compress&cs=tinysrgb&w=600'},
 {name:'Perfil B',role:'Atención · POS',match:'87%',availability:'Turnos rotativos',experience:'2 años atención',reputation:'En formación',repState:'forming',signal:'1 evaluación · muestra todavía insuficiente',image:'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=600'},
 {name:'Perfil C',role:'Ventas · comercial',match:'84%',availability:'Lun a sábados',experience:'2 años ventas',reputation:'En revisión',repState:'review',signal:'3 evaluaciones · una señal temporalmente revisada',image:'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=600'},
]

const candidateCardCss=`
.pm7-employer-candidates{max-width:1080px!important;margin-inline:auto!important;grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:18px!important;align-items:start!important}
.pm7-employer-candidates>article{height:auto!important;min-height:0!important;align-self:start!important;border-radius:24px!important;overflow:hidden!important}
.pm7-employer-candidate-photo{height:226px!important;min-height:0!important}
.pm7-employer-candidate-photo>span{font-size:10px!important;line-height:1.15!important;padding:8px 11px!important}
.pm7-employer-candidate-body{height:auto!important;min-height:0!important;padding:18px!important;display:block!important}
.pm7-employer-candidate-body h3{font-size:25px!important;line-height:1!important;margin:0 0 7px!important}
.pm7-employer-candidate-body>p{font-size:13px!important;line-height:1.35!important;margin:0 0 13px!important}
.pm38-candidate-quick{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:7px;margin:0 0 11px}
.pm38-candidate-quick>div{min-height:64px;padding:9px 10px;border-radius:13px;background:#f3f6f7;border:1px solid #e4e9eb;display:flex;flex-direction:column;justify-content:space-between;gap:6px}
.pm38-candidate-quick small{font-size:8px!important;line-height:1.2!important;font-weight:950!important;letter-spacing:.045em!important;text-transform:uppercase!important;color:#7a8891!important}
.pm38-candidate-quick b{font-size:11px!important;line-height:1.25!important;color:#17262f!important}
.pm38-candidate-quick>div:first-child{background:#f3ffd8;border-color:#d9eda3}.pm38-candidate-quick>div:first-child b{font-size:19px!important;color:#27380e!important}
.pm7-employer-candidates .pm37-candidate-reputation{min-height:0!important;height:auto!important;align-self:start!important;margin:0 0 12px!important;padding:11px 12px!important}
.pm7-employer-candidates .pm37-candidate-reputation>span{font-size:9px!important}.pm7-employer-candidates .pm37-candidate-reputation>b{font-size:12px!important}.pm7-employer-candidates .pm37-candidate-reputation>small{font-size:9px!important}
.pm7-employer-candidates .pm37-candidate-reputation.review{border-color:#edd9ac!important;background:linear-gradient(135deg,#fffaf0,#fff7e1)!important}.pm7-employer-candidates .pm37-candidate-reputation.review>b{color:#82571b!important}
.pm7-employer-candidate-body>button{width:100%!important;height:auto!important;min-height:46px!important;padding:12px 14px!important;font-size:13px!important;line-height:1.2!important;font-weight:900!important}
@media(max-width:920px){.pm7-employer-candidates{grid-template-columns:repeat(2,minmax(0,1fr))!important}.pm7-employer-candidates>article:last-child{grid-column:1/-1;max-width:520px;justify-self:center;width:100%}}
@media(max-width:620px){.pm7-employer-candidates{grid-template-columns:1fr!important;max-width:430px!important}.pm7-employer-candidates>article:last-child{grid-column:auto;max-width:none}.pm7-employer-candidate-photo{height:240px!important}.pm38-candidate-quick{grid-template-columns:1fr 1fr}.pm38-candidate-quick>div:first-child{grid-column:1/-1;min-height:58px}}
`

export default function EmployerLanding(){return <main className={`${styles.page} pm7-page pm7-employer`}>
 <style>{candidateCardCss}</style>
 <PlatformHeader audience="employer"/>
 <section className="pm7-employer-hero"><div className="pm7-employer-hero-inner"><div className="pm17-hero-copy"><span className="pm7-eyebrow lime">SELECCIÓN SIMPLE · DECISIÓN HUMANA</span><h1>Encontrá gente.<br/><em>Hablá. Decidí.</em></h1><p>Publicás una búsqueda, llegan perfiles ordenados y Nexo te resume lo importante desde la PC o el teléfono. Menos pestañas, más conversación y criterio humano.</p><div className="pm7-employer-actions"><Link className="pm7-btn-black" href="/empresas/publicar">Publicar gratis</Link><Link className="pm7-btn-white" href="/empresas/movil">Nexo en PC + móvil</Link></div><div className="pm17-human-proof"><div className="pm17-proof-faces"><i className="one"/><i className="two"/><i className="three"/></div><div><b>Hecho para personas que contratan mientras trabajan.</b><span>Dueños, encargados y equipos de RRHH pueden revisar, conversar y decidir sin vivir adentro de un sistema.</span></div></div><div className="pm7-employer-proof"><span>Cuenta inicial sin tarjeta</span><span>·</span><span>La decisión final siempre es humana</span><span>·</span><span>Datos sensibles fuera del ranking</span></div></div><div className="pm7-employer-console"><div className="pm17-human-card"><div className="pm17-human-photo"/><div><span>SELECCIÓN EN MOVIMIENTO</span><b>Lucía · Encargada de local</b><small>Revisando candidatos desde el teléfono</small></div></div><div className="pm7-employer-phone pm17-nexo-phone"><div className="pm17-phone-status"><b>9:41</b><span>● ◔ ▰</span></div><div className="pm17-phone-island"/><div className="pm7-employer-phone-head"><span>NX</span><div><b>Nexo</b><small>Búsqueda activa · Vendedor/a Palermo</small></div><i/></div><div className="pm7-employer-phone-chat"><div className="a"><b>Nexo</b>Entraron 12 postulaciones nuevas. Hay 5 que cumplen los requisitos que marcaste.</div><div className="q">Mostrame esas cinco y decime quién puede los sábados.</div><div className="a">Tres tienen disponibilidad confirmada. Te marco qué experiencia tiene cada uno y qué conviene validar.</div><div className="q">Prepará una shortlist para Recursos Humanos.</div><div className="a">Listo. Queda preparada para que la revises antes de compartirla.</div><div className="pm17-phone-compose"><span>Escribile a Nexo…</span><b>●</b></div></div><div className="pm17-homebar"/></div><div className="pm7-employer-float one"><small>EJEMPLO DE INTERFAZ</small><b>Shortlist explicada</b><span>Ordenada por evidencia laboral relevante</span></div><div className="pm7-employer-float two"><small>NEXO · PC + MÓVIL</small><b>Preguntá como hablás.</b><span>En escritorio abre como chat. En el celular ocupa la pantalla y te acompaña mientras trabajás.</span></div></div></div></section>

 <section className="pm7-employer-section"><div className="pm7-employer-section-inner"><div className="pm7-section-head"><div><span className="pm7-eyebrow blue">TRES PASOS Y A HABLAR CON GENTE</span><h2>No hace falta aprender otro sistema.</h2></div><p>La capa técnica queda atrás. Lo visible es publicar, recibir claridad y conversar con personas reales.</p></div><div className="pm7-employer-steps"><article className="pm7-employer-step"><span>PUBLICÁ</span><h3>Contá qué necesitás.</h3><p>Escribís el puesto como lo explicarías en una conversación. El sistema propone título, tareas, requisitos, horario y preguntas filtro.</p><ul><li>Editable antes de publicar</li><li>Plantillas por sucursal o rol</li><li>Sin formularios eternos</li></ul></article><article className="pm7-employer-step"><span>RECIBÍ</span><h3>Los CV llegan ordenados.</h3><p>La IA clasifica evidencia laboral y marca qué conviene validar. No usa foto, edad, género ni información sensible para ordenar.</p><ul><li>Shortlist explicada</li><li>Disponibilidad visible</li><li>Duplicados detectados</li></ul></article><article className="pm7-employer-step"><span>CONVERSÁ</span><h3>Preguntale a Nexo.</h3><p>Desde la PC o el celular podés pedir comparaciones, disponibilidad, preguntas de entrevista o preparar una derivación a RRHH.</p><ul><li>Chat de escritorio + experiencia móvil</li><li>Contexto aislado por empresa</li><li>Acciones auditables</li></ul></article></div></div></section>

 <section className="pm7-employer-section dark"><div className="pm7-employer-section-inner"><div className="pm7-employer-social"><div className="pm7-employer-photo"/><div className="pm7-employer-social-copy"><span className="pm7-eyebrow lime">NEXO · PC + MÓVIL</span><h2>Tu búsqueda, donde estés.</h2><p>En la computadora Nexo se abre como una ventana de chat centrada para trabajar sin abandonar el panel. En el celular se transforma en una experiencia de pantalla completa con candidatos, dudas, respuestas rápidas y órdenes simples.</p><div className="pm7-employer-command-list"><div><span>1</span><b>“Mostrame los perfiles con mejor ajuste y explicame por qué.”</b></div><div><span>2</span><b>“¿Quién puede trabajar sábados y domingos?”</b></div><div><span>3</span><b>“Compará estos dos perfiles en dos líneas.”</b></div><div><span>4</span><b>“Prepará una shortlist para Recursos Humanos.”</b></div><div><span>5</span><b>“Preparame preguntas para entrevistar a estos tres.”</b></div></div><Link href="/empresas/movil" className="pm17-nexo-cta">Abrir Nexo <span>→</span></Link></div></div></div></section>

 <section className="pm7-employer-section"><div className="pm7-employer-section-inner"><div className="pm7-section-head"><div><span className="pm7-eyebrow coral">EJEMPLOS DE INTERFAZ</span><h2>La shortlist también puede sentirse humana.</h2></div><p>Estos perfiles son ilustrativos. El ajuste al puesto y las señales de experiencia se muestran por separado: ninguna señal funciona por sí sola como sentencia, ranking secreto o motivo automático de exclusión.</p></div><div className="pm7-employer-candidates">{profiles.map(p=><article key={p.name}><div className="pm7-employer-candidate-photo" style={{backgroundImage:`url(${p.image})`}}><span>{p.match} coincidencia con el aviso</span></div><div className="pm7-employer-candidate-body"><h3>{p.name}</h3><p>{p.role}</p><div className="pm38-candidate-quick"><div><small>Coincidencia</small><b>{p.match}</b></div><div><small>Disponibilidad</small><b>{p.availability}</b></div><div><small>Experiencia</small><b>{p.experience}</b></div></div><div className={`pm37-candidate-reputation ${p.repState}`}><span>Señales verificadas</span><b>{p.reputation}</b><small>{p.signal}</small></div><button type="button" disabled aria-disabled="true">Perfil ilustrativo</button></div></article>)}</div></div></section>

 <EmployerReputationShowcase/>

 <section className="pm7-employer-section"><div className="pm7-employer-section-inner"><div className="pm7-section-head"><div><span className="pm7-eyebrow blue">PLANES EN EVALUACIÓN</span><h2>Empezá gratis. Escalá cuando el volumen lo justifique.</h2></div><p>Los valores que ves hoy son orientativos de esta etapa y pueden cambiar antes de una oferta comercial definitiva. Siempre vas a ver el precio vigente antes de contratar.</p></div><div className="pm7-employer-plans">{plans.map(plan=><article className={`pm7-employer-plan ${plan.featured?'featured':''}`} key={plan.name}><span>{plan.name.toUpperCase()}</span><h3>{plan.copy}</h3><div className="price">{plan.price}{plan.price.startsWith('$')&&plan.price!=='$0'?<small> / mes · valor orientativo</small>:null}</div><ul>{plan.items.map(i=><li key={i}>{i}</li>)}</ul><Link href={plan.name==='Gratis'?'/empresas/registro':'/empresas/panel'}>{plan.name==='Gratis'?'Crear cuenta':'Ver funcionamiento'}</Link></article>)}</div></div></section>

 <section className="pmv6-faq pm7-faq"><div className="pmv6-faq-inner"><div className="pmv6-faq-head"><div><span className="pm7-eyebrow lime">PREGUNTAS DE EMPRESA</span><h2>Contratar rápido no tiene que ser opaco.</h2></div><p>Qué ordena la IA, qué puede hacer Nexo y qué se mantiene bajo control humano.</p></div><div className="pmv6-faq-list"><details><summary>¿La IA descarta candidatos automáticamente?</summary><p>No. Puede ordenar evidencia relevante y explicar coincidencias o dudas. La decisión de contactar, entrevistar o contratar sigue siendo humana.</p></details><details><summary>¿Nexo puede preparar candidatos para Recursos Humanos?</summary><p>Sí, dentro del equipo de la misma cuenta puede preparar una shortlist o derivación. Las acciones sensibles se muestran para revisión y quedan asociadas a la empresa activa.</p></details><details><summary>¿Puedo usar Nexo desde PC y desde el teléfono?</summary><p>Sí. En PC se abre como chat de escritorio. En móvil usa una interfaz de pantalla completa pensada para revisar candidatos y dar órdenes mientras estás trabajando.</p></details><details><summary>¿Puede mezclar datos de otra empresa?</summary><p>No. El contexto de Nexo se ata a la empresa y búsqueda activas y las acciones se resuelven dentro de ese tenant.</p></details></div></div></section>
 <section className="pm7-final"><div><span>POSTULÁ MEJOR EMPRESAS</span><h2>Que contratar se parezca más a hablar con gente.</h2></div><div><Link href="/empresas/publicar" className="pm7-btn-black">Publicar una búsqueda</Link><Link href="/empresas/movil" className="pm7-btn-white">Nexo · PC + móvil</Link></div></section>
 <PlatformFooter/>
 </main>}