'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'
import styles from '../../postula-preview/platform.module.css'
type Draft={title:string;area:string;location:string;mode:string;schedule:string;description:string;mustHave:string;salary:string}
async function authHeaders(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
export default function EmployerPublishWizard(){
 const [step,setStep]=useState(1),[saved,setSaved]=useState(false),[published,setPublished]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[company,setCompany]=useState<{id:string;name:string;verification_status:string}|null>(null),[auth,setAuth]=useState<boolean|null>(null)
 const [draft,setDraft]=useState<Draft>({title:'',area:'Ventas y Comercial',location:'',mode:'Presencial',schedule:'Full time',description:'',mustHave:'',salary:''});const set=(k:keyof Draft,v:string)=>setDraft(p=>({...p,[k]:v}))
 useEffect(()=>{(async()=>{const {data}=await cvAuthClient().auth.getSession();setAuth(Boolean(data.session));if(!data.session)return;const r=await fetch('/api/postula/company',{headers:{Authorization:`Bearer ${data.session.access_token}`}});const d=await r.json().catch(()=>({}));const row=d?.memberships?.[0];if(row?.pm_companies)setCompany({id:row.company_id,name:row.pm_companies.name,verification_status:row.pm_companies.verification_status})})()},[])
 function generate(){const role=draft.title||'Vendedor/a';const place=draft.location||'CABA';setDraft(p=>({...p,title:role,description:p.description||`Buscamos ${role} para sumarse a nuestro equipo en ${place}. La persona tendrá foco en las tareas del puesto, buena comunicación y trabajo colaborativo. Revisá este texto y agregá condiciones concretas antes de publicar.`,mustHave:p.mustHave||'Disponibilidad para el horario publicado · experiencia o habilidades relacionadas · buena comunicación'}));setStep(2)}
 async function save(publish:boolean){if(!company)return;setBusy(true);setError('');try{const headers={'Content-Type':'application/json',...(await authHeaders())};const r=await fetch('/api/postula/company/jobs',{method:'POST',headers,body:JSON.stringify({company_id:company.id,title:draft.title,area:draft.area,location:draft.location,mode:draft.mode,schedule:draft.schedule,description:draft.description,requirements:draft.mustHave,salary:draft.salary,publish})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos guardar la búsqueda.');setSaved(true);setPublished(publish);setStep(4)}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar la búsqueda.')}finally{setBusy(false)}}
 if(auth===false)return <div className={styles.formCard}><h1>Ingresá como empleador.</h1><p>Necesitamos identificar la cuenta y la empresa antes de publicar.</p><Link href="/postula-acceso-preview?rol=empresa&next=/empresas-preview/publicar" className={styles.buttonDark}>Crear o abrir cuenta</Link></div>
 if(auth&&company===null)return <div className={styles.formCard}><span className={styles.miniLabel}>Antes de publicar</span><h1>Completá tu empresa.</h1><p>La validación básica lleva pocos datos y evita publicaciones anónimas.</p><Link href="/empresas-preview/registro" className={styles.buttonDark}>Crear / validar empresa</Link></div>
 return <div className={styles.wizardGrid}><aside className={styles.steps}><div className={`${styles.step} ${step===1?styles.stepActive:''}`}>1 · Necesidad</div><div className={`${styles.step} ${step===2?styles.stepActive:''}`}>2 · Aviso</div><div className={`${styles.step} ${step===3?styles.stepActive:''}`}>3 · Filtros</div><div className={`${styles.step} ${step===4?styles.stepActive:''}`}>4 · Revisión</div></aside><section className={styles.formCard}><span className={styles.miniLabel}>{company?.name||'Empresa'} · Publicador asistido</span><h1>{step===1?'Contanos a quién necesitás.':step===2?'La base del aviso ya está ordenada.':step===3?'Definí qué vale la pena preguntar.':published?'Búsqueda publicada.':'Borrador guardado.'}</h1>
 {step===1&&<><p>Empezá como se lo explicarías a otra persona. La IA ordena el texto, pero vos confirmás todo.</p><div className={styles.field}><label>Puesto</label><input value={draft.title} onChange={e=>set('title',e.target.value)} placeholder="Ej. vendedor/a de salón"/></div><div className={styles.fieldRow}><div className={styles.field}><label>Área</label><select value={draft.area} onChange={e=>set('area',e.target.value)}><option>Ventas y Comercial</option><option>Atención al cliente</option><option>Administración y Finanzas</option><option>Recursos Humanos</option><option>Gastronomía</option><option>Turismo y Hotelería</option><option>Operaciones y Logística</option><option>Tecnología</option><option>Marketing y Comunicación</option><option>Producción y Oficios</option></select></div><div className={styles.field}><label>Zona</label><input value={draft.location} onChange={e=>set('location',e.target.value)} placeholder="Ej. Belgrano, CABA"/></div></div><div className={styles.field}><label>En tus palabras</label><textarea value={draft.description} onChange={e=>set('description',e.target.value)} placeholder="Necesito alguien que atienda clientes, maneje caja, tenga disponibilidad por la tarde…"/></div><button className={styles.button} type="button" onClick={generate} disabled={!draft.title}>Ordenar aviso</button></>}
 {step===2&&<><p>Revisá el aviso como lo va a leer una persona. Nada se publica sin tu confirmación.</p><div className={styles.field}><label>Título</label><input value={draft.title} onChange={e=>set('title',e.target.value)}/></div><div className={styles.field}><label>Descripción</label><textarea value={draft.description} onChange={e=>set('description',e.target.value)} style={{minHeight:190}}/></div><div className={styles.fieldRow}><div className={styles.field}><label>Modalidad</label><select value={draft.mode} onChange={e=>set('mode',e.target.value)}><option>Presencial</option><option>Híbrido</option><option>Remoto</option></select></div><div className={styles.field}><label>Jornada</label><select value={draft.schedule} onChange={e=>set('schedule',e.target.value)}><option>Full time</option><option>Part time</option><option>Por turnos</option><option>Contrato</option></select></div></div><div className={styles.field}><label>Salario / rango (opcional)</label><input value={draft.salary} onChange={e=>set('salary',e.target.value)} placeholder="Ej. $900.000 a $1.100.000"/></div><div className={styles.heroActions}><button className={styles.buttonLight} type="button" onClick={()=>setStep(1)}>Atrás</button><button className={styles.buttonDark} type="button" onClick={()=>setStep(3)} disabled={draft.description.length<30||!draft.location}>Definir filtros</button></div></>}
 {step===3&&<><p>Usá requisitos relacionados al puesto. Evitá datos personales o sensibles que no correspondan.</p><div className={styles.field}><label>Requisitos importantes</label><textarea value={draft.mustHave} onChange={e=>set('mustHave',e.target.value)} placeholder="Ej. disponibilidad sábados · manejo de caja · experiencia de atención"/></div><div className={styles.questionCard}><div><b>Disponibilidad para el horario publicado</b><div style={{fontSize:11,color:'#748495'}}>Sí / No · requisito objetivo</div></div><span className={styles.status}>RECOMENDADA</span></div><div className={styles.aiNote}><b>Auditor activo.</b> No proponemos preguntas sobre edad, salud, religión, género, estado civil u otros datos sensibles como criterio de contratación.</div><div className={styles.heroActions}><button className={styles.buttonLight} type="button" onClick={()=>setStep(2)}>Editar aviso</button><button className={styles.buttonDark} type="button" onClick={()=>setStep(4)}>Revisar búsqueda</button></div></>}
 {step===4&&<><div className={styles.reviewBox}><span className={styles.miniLabel}>{saved?(published?'PUBLICADA':'BORRADOR'):'REVISIÓN'}</span><h3>{draft.title}</h3><p style={{fontSize:12,color:'#657788'}}>{draft.location} · {draft.mode} · {draft.schedule}{draft.salary?` · ${draft.salary}`:''}</p><p style={{fontSize:13,lineHeight:1.6,color:'#5d6f7e'}}>{draft.description}</p></div>{error&&<div className={styles.securityBadge} style={{color:'#a52b34'}}>{error}</div>}{!saved?<><div className={styles.aiNote}><b>Antes de publicar:</b> la búsqueda aparecerá en Postulá Mejor durante hasta 30 días y las postulaciones quedarán aisladas dentro de {company?.name}.</div><div className={styles.heroActions}><button className={styles.buttonLight} type="button" onClick={()=>setStep(3)}>Volver</button><button className={styles.buttonLight} type="button" onClick={()=>save(false)} disabled={busy}>Guardar borrador</button><button className={styles.button} type="button" onClick={()=>save(true)} disabled={busy}>{busy?'Publicando…':'Publicar ahora'}</button></div></>:<div className={styles.heroActions}><Link className={styles.button} href="/empresas-preview/panel">Abrir panel de empresa</Link><Link className={styles.buttonDark} href="/empleos-preview">Ver portal público</Link></div>}</>}
 </section></div>
}
