'use client'

import {FormEvent,useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import styles from './account.module.css'
import {CV_ACCOUNT_API,SESSION_KEY,cvAuthClient,trackCvEvent} from '../cv-ia/cvAuth'

const SIGNUP_TICKET_API='https://pejkycdttogpmmdntzuq.supabase.co/functions/v1/cv-ai-signup-ticket'
const REGISTER_API='https://pejkycdttogpmmdntzuq.supabase.co/functions/v1/cv-ai-register-verified'
type Account={email:string;role:'member'|'owner';display_name?:string|null}
async function signupTicket(email:string){const response=await fetch(SIGNUP_TICKET_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const data=await response.json().catch(()=>({ok:false,error:'Respuesta inválida'}));if(!response.ok||!data?.ok)throw new Error(data?.error||'No pudimos preparar la creación de tu cuenta.');return String(data.signup_token||'')}
async function registerVerified(email:string,password:string,signup_token:string,role:'candidate'|'employer',next:string){const response=await fetch(REGISTER_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,signup_token,role,next})});const data=await response.json().catch(()=>({ok:false,error:'Respuesta inválida'}));if(!response.ok||!data?.ok)throw new Error(data?.error||'No pudimos crear tu cuenta.');return data}
function strongPassword(value:string){return value.length>=10&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/[0-9]/.test(value)}

export default function AccountClient(){
 const params=useSearchParams();const [mode,setMode]=useState<'login'|'signup'>(params.get('modo')==='crear'?'signup':'login');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [newPassword,setNewPassword]=useState('');const [account,setAccount]=useState<Account|null>(null);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [accepted,setAccepted]=useState(false);const reset=params.get('reset')==='1';const verified=params.get('verified')==='1';const next=params.get('next')||'';const requestedRole=params.get('role')==='employer'?'employer':'candidate'
 async function ensurePostulaProfile(accessToken:string,acceptLegal=false){const response=await fetch('/api/postula/profile',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({role:requestedRole,accept_legal:acceptLegal,terms_version:'2026-08-21',responsibility_ack:acceptLegal,source:'account_signup'})});const data=await response.json().catch(()=>({}));if(!response.ok||!data?.ok)throw new Error(data?.error||'No pudimos preparar tu perfil de Postulá Mejor.')}
 async function sendWelcome(accessToken:string){try{await fetch('/api/postula/welcome',{method:'POST',headers:{Authorization:`Bearer ${accessToken}`}})}catch{/* no bloquea el acceso */}}
 async function finishAccount(accessToken:string,acceptLegal=false){const currentToken=localStorage.getItem(SESSION_KEY)||'';const response=await fetch(CV_ACCOUNT_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({action:'link',session_token:currentToken})});const data=await response.json().catch(()=>({ok:false,error:'Respuesta inválida'}));if(!response.ok||!data?.ok)throw new Error(data?.error||'No pudimos vincular tu cuenta.');if(data.session_token)localStorage.setItem(SESSION_KEY,data.session_token);setAccount(data.account);if(data.account?.role==='owner'){const token=localStorage.getItem(SESSION_KEY)||'';await fetch(CV_ACCOUNT_API,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${accessToken}`},body:JSON.stringify({action:'owner_prepare',session_token:token})})}else await ensurePostulaProfile(accessToken,acceptLegal);if(verified){void sendWelcome(accessToken);setMessage('Email confirmado. Tu cuenta ya está activa.')}if(next)window.setTimeout(()=>location.assign(next),500)}
 useEffect(()=>{const client=cvAuthClient();client.auth.getSession().then(async({data})=>{if(data.session){try{await finishAccount(data.session.access_token,false)}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar tu cuenta.')}}});const {data:listener}=client.auth.onAuthStateChange(async(event,session)=>{if(event==='SIGNED_IN'&&session){try{await finishAccount(session.access_token,false)}catch{}}});return()=>listener.subscription.unsubscribe()
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const client=cvAuthClient(),cleanEmail=email.trim().toLowerCase();if(mode==='login'){const {data,error}=await client.auth.signInWithPassword({email:cleanEmail,password});if(error)throw error;if(!data.session)throw new Error('No pudimos iniciar la sesión.');await finishAccount(data.session.access_token,false);void trackCvEvent('account_signed_in',{source:'account'},'/cuenta');setMessage('Sesión iniciada correctamente.')}else{if(!accepted)throw new Error('Para crear la cuenta necesitás aceptar los Términos, la Política de Privacidad y el marco de responsabilidad de publicación.');if(!strongPassword(password))throw new Error('Usá al menos 10 caracteres, con mayúscula, minúscula y un número.');const ticket=await signupTicket(cleanEmail);if(!ticket)throw new Error('No pudimos preparar el registro seguro.');await registerVerified(cleanEmail,password,ticket,requestedRole,next);void trackCvEvent('account_verification_sent',{source:'account',role:requestedRole},'/cuenta');setMessage('Cuenta preparada. Te enviamos un correo a '+cleanEmail+'. Confirmalo para activar la cuenta y recién después vas a poder ingresar.');setPassword('')}}catch(e){setError(e instanceof Error?e.message:'No pudimos completar el acceso.')}finally{setBusy(false)}}
 async function forgot(){setError('');setMessage('');if(!email.trim()){setError('Escribí tu email primero.');return}try{const {error}=await cvAuthClient().auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:'https://postulamejor.com/cuenta?reset=1'});if(error)throw error;setMessage('Te enviamos un enlace para recuperar el acceso. Revisá también spam.')}catch(e){setError(e instanceof Error?e.message:'No pudimos enviar el recupero.')}}
 async function updatePassword(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!strongPassword(newPassword))throw new Error('Usá al menos 10 caracteres, con mayúscula, minúscula y un número.');const {error}=await cvAuthClient().auth.updateUser({password:newPassword});if(error)throw error;setMessage('Contraseña actualizada. Ya podés usar tu cuenta.');setNewPassword('')}catch(e){setError(e instanceof Error?e.message:'No pudimos cambiar la contraseña.')}finally{setBusy(false)}}
 async function logout(){await cvAuthClient().auth.signOut();setAccount(null);setMessage('Sesión cerrada.')}
 if(account)return <div className={styles.card}><div className={styles.accountBox}><div className={styles.accountHeader}><div><h2>Tu cuenta</h2><p>{account.email}</p></div><span className={`${styles.role} ${account.role==='owner'?styles.owner:''}`}>{account.role==='owner'?'PROPIETARIO':'CUENTA ACTIVA'}</span></div>{account.role==='owner'&&<div className={styles.ownerNote}><b>Modo propietario.</b> Esta cuenta puede probar diagnósticos, CV Pro+ y Búsqueda Activa sin cobro. El permiso se valida en servidor.</div>}<div className={styles.actions}>{requestedRole==='employer'?<a href="/empresas/panel">Abrir panel empresa</a>:<a href="/mi-cuenta">Abrir mi perfil</a>}<a href="/mejorar-cv">Mejorar mi CV</a></div><button className={styles.secondary} onClick={logout}>Cerrar sesión</button>{message&&<div className={styles.message}>{message}</div>}</div></div>
 if(reset)return <form className={`${styles.card} ${styles.form}`} onSubmit={updatePassword}><h2>Nueva contraseña</h2><p className={styles.security}>Elegí una contraseña única de al menos 10 caracteres, con mayúscula, minúscula y un número.</p><label>Nueva contraseña<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" required/></label><button className={styles.primary} disabled={busy}>{busy?'Guardando…':'Guardar nueva contraseña'}</button>{message&&<div className={styles.message}>{message}</div>}{error&&<div className={`${styles.message} ${styles.error}`}>{error}</div>}</form>
 return <div className={styles.card}><div className={styles.tabs}><button data-on={mode==='login'} onClick={()=>{setMode('login');setError('');setMessage('')}}>Iniciar sesión</button><button data-on={mode==='signup'} onClick={()=>{setMode('signup');setError('');setMessage('')}}>Crear cuenta</button></div><form className={styles.form} onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" required placeholder="tu@email.com"/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='login'?'current-password':'new-password'} required placeholder={mode==='signup'?'10+ caracteres, mayúscula y número':'Tu contraseña'}/></label>{mode==='signup'&&<label style={{display:'flex',gridTemplateColumns:'auto 1fr',alignItems:'flex-start',gap:9,fontSize:11,lineHeight:1.45,fontWeight:650}}><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)} style={{width:17,height:17,marginTop:1}}/><span>Acepto los <a href="/terminos" target="_blank">Términos y Condiciones</a>, la <a href="/privacidad" target="_blank">Política de Privacidad</a> y el tratamiento de datos necesario para operar la plataforma. Si publico un empleo, un Trabajo Flex u otro contenido, declaro ser titular o representante autorizado de la cuenta y asumo la responsabilidad por la veracidad, legalidad y cumplimiento de las obligaciones que correspondan a esa publicación.</span></label>}{mode==='login'&&<button type="button" className={styles.forgot} onClick={forgot}>Olvidé mi contraseña</button>}<button className={styles.primary} disabled={busy}>{busy?(mode==='login'?'Ingresando…':'Preparando cuenta…'):(mode==='login'?'Ingresar':'Crear mi cuenta')}</button></form>{message&&<div className={styles.message} style={{marginTop:12}}>{message}</div>}{error&&<div className={`${styles.message} ${styles.error}`} style={{marginTop:12}}>{error}</div>}<div className={styles.security}>La contraseña queda gestionada por el sistema de autenticación y no se almacena en texto legible. Para cuentas nuevas exigimos confirmar el correo electrónico antes del primer ingreso. Tu cuenta no se elimina si vence un plan: simplemente vuelve al nivel gratuito.</div></div>
}
