import {NextRequest,NextResponse} from 'next/server'
import {processSellerMessage} from '../seller/engine'
export const runtime='nodejs'
export const dynamic='force-dynamic'
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
const SERVICE_KEY=process.env.SUPABASE_SERVICE_ROLE_KEY||''
const EVOLUTION_URL=(process.env.EVOLUTION_API_URL||'').replace(/\/+$/,'')
const EVOLUTION_KEY=process.env.EVOLUTION_API_KEY||''
const WEBHOOK_SECRET=process.env.EVOLUTION_WEBHOOK_SECRET||''
function companyIdFromInstance(instance:string){const raw=instance.replace(/^cl-/,'').replace(/[^a-f0-9]/gi,'').toLowerCase();if(raw.length!==32)return'';return`${raw.slice(0,8)}-${raw.slice(8,12)}-${raw.slice(12,16)}-${raw.slice(16,20)}-${raw.slice(20)}`}
function textFrom(data:any){return String(data?.message?.conversation||data?.message?.extendedTextMessage?.text||data?.message?.imageMessage?.caption||data?.message?.videoMessage?.caption||data?.message?.buttonsResponseMessage?.selectedDisplayText||data?.message?.listResponseMessage?.title||'').trim()}
function phoneFromJid(value:unknown){return String(value||'').split('@')[0].replace(/\D/g,'').slice(0,18)}
async function companyName(companyId:string){const r=await fetch(`${SUPABASE_URL}/rest/v1/companies?id=eq.${encodeURIComponent(companyId)}&select=name&limit=1`,{headers:{apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${SERVICE_KEY}`},cache:'no-store'}),rows=await r.json().catch(()=>[]);return String(rows?.[0]?.name||'Mi comercio')}
async function send(instance:string,number:string,text:string){const r=await fetch(`${EVOLUTION_URL}/message/sendText/${encodeURIComponent(instance)}`,{method:'POST',headers:{apikey:EVOLUTION_KEY,'Content-Type':'application/json'},body:JSON.stringify({number,text,delay:600}),cache:'no-store'}),data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data?.message||data?.error||`Evolution ${r.status}`);return data}
export async function POST(req:NextRequest){if(!SERVICE_KEY||!EVOLUTION_URL||!EVOLUTION_KEY||!WEBHOOK_SECRET)return NextResponse.json({ok:false,error:'Webhook real todavía no está habilitado en este entorno.'},{status:503});const received=req.headers.get('x-whatsapp-webhook-secret')||req.headers.get('x-evolution-webhook-secret')||'';if(received!==WEBHOOK_SECRET)return NextResponse.json({ok:false,error:'No autorizado.'},{status:401});const payload=await req.json().catch(()=>({})),event=String(payload?.event||payload?.type||'').toLowerCase();if(event&&event!=='messages.upsert')return NextResponse.json({ok:true,ignored:true,event});const instance=String(payload?.instance||payload?.instanceName||payload?.data?.instance||''),companyId=companyIdFromInstance(instance);if(!companyId)return NextResponse.json({ok:true,ignored:true,reason:'unknown_instance'});const data=Array.isArray(payload?.data)?payload.data[0]:payload?.data||payload;if(data?.key?.fromMe===true)return NextResponse.json({ok:true,ignored:true,reason:'from_me'});const remoteJid=String(data?.key?.remoteJid||data?.remoteJid||'');if(!remoteJid||/@g\.us$|status@broadcast/i.test(remoteJid))return NextResponse.json({ok:true,ignored:true,reason:'not_direct_chat'});const phone=phoneFromJid(remoteJid),text=textFrom(data),externalMessageId=String(data?.key?.id||payload?.id||'');if(phone.length<8||!text)return NextResponse.json({ok:true,ignored:true,reason:'no_text'});try{const result=await processSellerMessage({token:SERVICE_KEY,companyId,companyName:await companyName(companyId),phone,text,externalMessageId,commitSale:true});if(result?.reply)await send(instance,phone,String(result.reply));return NextResponse.json({ok:true,processed:true,duplicate:Boolean(result?.duplicate)})}catch(error){const message=error instanceof Error?error.message:String(error);if(/no está habilitado|todavía no activó|pausada/i.test(message))return NextResponse.json({ok:true,ignored:true,reason:message});return NextResponse.json({ok:false,error:message},{status:500})}}
