import type { CashSummary } from './cash-api'

const money=new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:2})
function lines(summary:CashSummary,company:string){const payments=Object.entries(summary.payments||{});return [`CIERRE DE CAJA · ${company}`,`Apertura: ${new Date(summary.opened_at).toLocaleString('es-AR')}`,`Cierre: ${new Date(summary.closed_at).toLocaleString('es-AR')}`,`Monto inicial: ${money.format(summary.opening_amount||0)}`,`Ventas: ${money.format(summary.sales_total||0)} · ${summary.sales_count||0} operaciones`,'MEDIOS DE PAGO',...payments.map(([k,v])=>`${k}: ${money.format(Number(v||0))}`),`Ingresos de caja: ${money.format(summary.income||0)}`,`Gastos: ${money.format(summary.expenses||0)}`,`Retiros: ${money.format(summary.egress||0)}`,`Efectivo esperado: ${money.format(summary.expected_cash||0)}`,`Efectivo contado: ${money.format(summary.counted_cash??summary.expected_cash??0)}`,`Diferencia: ${money.format(summary.difference||0)}`]}
export function cashCloseText(summary:CashSummary,company:string){return lines(summary,company).join('\n')}
export function cashWhatsAppText(summary:CashSummary,company:string){return `Hola, te estoy enviando el cierre de caja del día de ${company}.\n\n${cashCloseText(summary,company)}`}
function esc(s:string){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]||c))}
export async function printCashClose(summary:CashSummary,company:string,paper:'58'|'80'='58',printerName=''){
  const body=lines(summary,company).map((l,i)=>`<div class="${i===0?'title':''}">${esc(l)}</div>`).join('')
  const html=`<!doctype html><html><head><meta charset="utf-8"><style>@page{size:${paper}mm auto;margin:0}html,body{width:${paper}mm;margin:0;padding:0}body{font-family:Arial,sans-serif;font-size:11px;padding:2mm;line-height:1.35}.title{text-align:center;font-size:15px;font-weight:900;border-bottom:1px dashed #000;padding-bottom:5px;margin-bottom:5px}div{margin:2px 0}</style></head><body>${body}</body></html>`
  if(typeof window!=='undefined'&&window.ComercioLlenoPrintBridge?.printHtml){await window.ComercioLlenoPrintBridge.printHtml({html,printerName,paper,copies:1});return}
  const frame=document.createElement('iframe');frame.style.cssText='position:fixed;width:1px;height:1px;opacity:0;border:0';document.body.appendChild(frame);const doc=frame.contentDocument;if(!doc){frame.remove();return}doc.open();doc.write(html);doc.close();await new Promise(r=>setTimeout(r,140));frame.contentWindow?.print();setTimeout(()=>frame.remove(),900)
}
function pdfEsc(s:string){return s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)').replace(/[^\x20-\x7E]/g,'?')}
function pdfBytes(rows:string[]){let y=805;const commands=['BT','/F1 11 Tf'];rows.forEach((row,i)=>{commands.push(`/${i===0?'F2':'F1'} ${i===0?16:11} Tf`,`1 0 0 1 45 ${y} Tm`,`(${pdfEsc(row)}) Tj`);y-=i===0?25:17});commands.push('ET');const stream=commands.join('\n');const objects=['<< /Type /Catalog /Pages 2 0 R >>','<< /Type /Pages /Kids [3 0 R] /Count 1 >>','<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 4 0 R /F2 5 0 R >> >> /Contents 6 0 R >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>','<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>',`<< /Length ${stream.length} >>\nstream\n${stream}\nendstream`];let pdf='%PDF-1.4\n',offs=[0];objects.forEach((o,i)=>{offs.push(pdf.length);pdf+=`${i+1} 0 obj\n${o}\nendobj\n`});const xref=pdf.length;pdf+=`xref\n0 ${objects.length+1}\n0000000000 65535 f \n`;offs.slice(1).forEach(o=>pdf+=`${String(o).padStart(10,'0')} 00000 n \n`);pdf+=`trailer\n<< /Size ${objects.length+1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF`;return new TextEncoder().encode(pdf)}
export function cashClosePdf(summary:CashSummary,company:string){return new Blob([pdfBytes(lines(summary,company))],{type:'application/pdf'})}
export function downloadCashClosePdf(summary:CashSummary,company:string){const blob=cashClosePdf(summary,company),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`cierre-caja-${new Date(summary.closed_at).toISOString().slice(0,10)}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1200)}
export function openCashWhatsApp(phone:string|undefined|null,summary:CashSummary,company:string){const digits=String(phone||'').replace(/\D/g,'');if(!digits)throw new Error('El propietario todavía no tiene un WhatsApp cargado en Configuración.');window.open(`https://wa.me/${digits}?text=${encodeURIComponent(cashWhatsAppText(summary,company))}`,'_blank','noopener,noreferrer')}
