import type { CartLine,CompanyProfile,DeviceSettings,TenantSession } from './types'

export type QuoteItem={product_id?:string|null;name:string;barcode?:string|null;qty:number;unit_price:number;line_total:number}
export type Quote={id:string;company_id:string;branch_id:string;customer_id?:string|null;quote_number?:number|string|null;status:'open'|'accepted'|'expired'|'cancelled'|string;subtotal:number;discount_amount:number;total:number;valid_until?:string|null;items:QuoteItem[];note?:string|null;created_at:string;updated_at?:string|null}

function headers(session:TenantSession){return{Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'}}
export async function listQuotes(session:TenantSession){const response=await fetch('/api/redesign/quotes',{headers:headers(session),cache:'no-store'});const result=await response.json().catch(()=>({}));if(!response.ok||!result?.ok)throw Object.assign(new Error(result?.error||'No se pudieron cargar los presupuestos.'),{previewSchemaPending:result?.preview_schema_pending===true});return(result.quotes||[]) as Quote[]}
export async function createQuote(session:TenantSession,input:{cart:CartLine[];customer_id?:string|null;discount_amount?:number;valid_until?:string|null;note?:string|null}){const items=input.cart.map(item=>({product_id:item.id,name:item.name,barcode:item.barcode||null,qty:Number(item.qty||0),unit_price:Number(item.price||0)}));const response=await fetch('/api/redesign/quotes',{method:'POST',headers:headers(session),body:JSON.stringify({...input,items}),cache:'no-store'});const result=await response.json().catch(()=>({}));if(!response.ok||!result?.ok)throw Object.assign(new Error(result?.error||'No se pudo guardar el presupuesto.'),{previewSchemaPending:result?.preview_schema_pending===true});return result.quote as Quote}
export async function deleteQuote(session:TenantSession,id:string){const response=await fetch(`/api/redesign/quotes?id=${encodeURIComponent(id)}`,{method:'DELETE',headers:headers(session),cache:'no-store'});const result=await response.json().catch(()=>({}));if(!response.ok||!result?.ok)throw new Error(result?.error||'No se pudo eliminar el presupuesto.')}

function esc(value:unknown){return String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]||char))}
function money(value:number){return new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',minimumFractionDigits:2}).format(Number(value)||0)}
export function quoteLabel(quote:Quote){return `P-${String(quote.quote_number||quote.id.slice(0,8)).padStart(6,'0')}`}
export function buildQuoteHtml(quote:Quote,company:CompanyProfile,paper:'80'|'58'='58',settings?:Partial<DeviceSettings>){
  const width=paper==='58'?'52mm':'72mm';const name=settings?.showBusinessName!==false?company.name:'';const tax=settings?.showTaxId!==false&&company.tax_id?`CUIT ${esc(company.tax_id)}`:'';const address=String(settings?.receiptAddress||company.address||'').trim();const footer=String(settings?.receiptFooter||'').trim();
  const rows=quote.items.map(item=>`<tr><td>${esc(item.name)}${settings?.showBarcode&&item.barcode?`<small>${esc(item.barcode)}</small>`:''}</td><td class="r">${item.qty}</td><td class="r">${money(item.unit_price)}</td><td class="r"><b>${money(item.line_total)}</b></td></tr>`).join('')
  return `<!doctype html><html><head><meta charset="utf-8"><title>Presupuesto ${esc(quoteLabel(quote))}</title><style>@page{size:${paper==='58'?'58mm':'80mm'} auto;margin:3mm}*{box-sizing:border-box}body{font-family:Arial,sans-serif;width:${width};margin:0 auto;color:#111;font-size:${paper==='58'?'10px':'11px'};line-height:1.3}.c{text-align:center}.r{text-align:right}h1{font-size:${paper==='58'?'18px':'20px'};letter-spacing:.08em;margin:4px 0}.business{font-size:14px;font-weight:900}.warning{margin:9px 0;border:2px solid #111;padding:7px;text-align:center;font-weight:900}.meta{border-top:1px dashed #555;border-bottom:1px dashed #555;padding:7px 0;margin:7px 0}.meta div{margin:2px 0}table{width:100%;border-collapse:collapse}th,td{padding:4px 1px;vertical-align:top;border-bottom:1px dotted #aaa}th{font-size:9px;text-align:left}.total{font-size:18px;font-weight:950;text-align:right;margin-top:10px}.discount{text-align:right;margin-top:5px}.foot{text-align:center;margin-top:12px;padding-top:8px;border-top:1px dashed #777}.dev{font-size:9px;margin-top:10px}.dev b{display:block;font-size:13px}small{display:block;font-size:8px;color:#555}</style></head><body><div class="c">${name?`<div class="business">${esc(name)}</div>`:''}${tax?`<div>${tax}</div>`:''}${address?`<div>${esc(address)}</div>`:''}<h1>PRESUPUESTO</h1><b>${esc(quoteLabel(quote))}</b></div><div class="warning">SIN VALIDEZ FISCAL<br>NO ES FACTURA · NO AFECTA STOCK NI CAJA</div><div class="meta"><div><b>Fecha:</b> ${esc(new Date(quote.created_at).toLocaleString('es-AR'))}</div>${quote.valid_until?`<div><b>Válido hasta:</b> ${esc(new Date(`${quote.valid_until}T12:00:00`).toLocaleDateString('es-AR'))}</div>`:''}</div><table><thead><tr><th>Producto</th><th class="r">Cant.</th><th class="r">Precio</th><th class="r">Total</th></tr></thead><tbody>${rows}</tbody></table>${quote.discount_amount>0?`<div class="discount">Subtotal ${money(quote.subtotal)}<br>Descuento − ${money(quote.discount_amount)}</div>`:''}<div class="total">TOTAL ${money(quote.total)}</div>${quote.note?`<div class="meta"><b>Nota:</b> ${esc(quote.note)}</div>`:''}<div class="foot">Este documento es únicamente informativo y no representa una venta ni un comprobante fiscal.${footer?`<br>${esc(footer)}`:''}<div class="dev">Sistema desarrollado por<b>ComercioLleno.com</b></div></div></body></html>`
}
export async function printQuote(quote:Quote,company:CompanyProfile,device:DeviceSettings){if(typeof window==='undefined')return;const popup=window.open('','_blank','width=520,height=760');if(!popup)throw new Error('El navegador bloqueó la ventana de impresión. Habilitá ventanas emergentes e intentá nuevamente.');popup.document.open();popup.document.write(buildQuoteHtml(quote,company,device.paper,device));popup.document.close();popup.focus();await new Promise(resolve=>setTimeout(resolve,180));popup.print()}
