import type { TenantSession,UserPermissions } from './types'
import type { StaffProfile } from './api'

const URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
export type CompanyAdmin={id:string;name:string;legal_name?:string|null;tax_id?:string|null;owner_phone?:string|null;country?:string|null;province?:string|null;address?:string|null;onboarding_complete?:boolean}
export type BranchAdmin={id:string;name:string;address?:string|null;country?:string|null;province?:string|null;is_primary:boolean;active:boolean}
export type StaffRole='seller'|'manager'|'cashier'|'supervisor'

async function req<T>(session:TenantSession,path:string,init:RequestInit={}){const r=await fetch(`${URL}/rest/v1/${path}`,{...init,headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json',...(init.headers||{})},cache:'no-store'});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||d?.error||`Error ${r.status}`);return d as T}
export async function loadTenantAdmin(session:TenantSession){const [companies,branches,staff]=await Promise.all([req<CompanyAdmin[]>(session,`companies?select=id,name,legal_name,tax_id,owner_phone,country,province,address,onboarding_complete&id=eq.${encodeURIComponent(session.companyId)}&limit=1`),req<BranchAdmin[]>(session,`branches?select=id,name,address,country,province,is_primary,active&company_id=eq.${encodeURIComponent(session.companyId)}&active=eq.true&order=is_primary.desc,created_at.asc`),req<StaffProfile[]>(session,`profiles?select=id,full_name,username,role,permissions,active&company_id=eq.${encodeURIComponent(session.companyId)}&order=created_at.asc`)]);return{company:companies[0],branches,staff}}
export async function saveCompanyAdmin(session:TenantSession,company:Partial<CompanyAdmin>){await req(session,`companies?id=eq.${encodeURIComponent(session.companyId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(company)});if(company.name&&typeof window!=='undefined')localStorage.setItem('cl_company_name',company.name)}
export async function saveBranch(session:TenantSession,branch:Partial<BranchAdmin>&Pick<BranchAdmin,'name'>){const body={company_id:session.companyId,name:branch.name.trim(),address:branch.address||null,country:branch.country||null,province:branch.province||null,is_primary:Boolean(branch.is_primary),active:true,updated_at:new Date().toISOString()};if(branch.id)await req(session,`branches?id=eq.${encodeURIComponent(branch.id)}&company_id=eq.${encodeURIComponent(session.companyId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)});else await req(session,'branches',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify(body)})}
export async function deactivateBranch(session:TenantSession,id:string){await req(session,`branches?id=eq.${encodeURIComponent(id)}&company_id=eq.${encodeURIComponent(session.companyId)}&is_primary=eq.false`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({active:false,updated_at:new Date().toISOString()})})}
export async function updateStaffAdmin(session:TenantSession,id:string,role:StaffRole,permissions:UserPermissions,active=true){await req(session,`profiles?id=eq.${encodeURIComponent(id)}&company_id=eq.${encodeURIComponent(session.companyId)}`,{method:'PATCH',headers:{Prefer:'return=minimal'},body:JSON.stringify({role,permissions,active})})}
export async function createStaffAdmin(session:TenantSession,input:{username:string;password:string;full_name:string;role:StaffRole;permissions:UserPermissions}){const r=await fetch(`${URL}/functions/v1/create-staff-user`,{method:'POST',headers:{apikey:KEY,Authorization:`Bearer ${session.token}`,'Content-Type':'application/json'},body:JSON.stringify(input)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||'No se pudo crear el usuario.');return d}
