import type {Metadata} from 'next'
import Link from 'next/link'
import {PlatformFooter,PlatformHeader} from '../postula-preview/PlatformChrome'
import '../postula-preview/premium-v7.css'
import styles from '../legal.module.css'

export const metadata:Metadata={title:{absolute:'Política de evaluaciones y señales verificadas | Postulá Mejor'},description:'Reglas de Postulá Mejor para evaluaciones laborales verificadas, opcionales y bilaterales entre personas y empresas.',robots:{index:true,follow:true},alternates:{canonical:'https://postulamejor.com/politica-evaluaciones'},openGraph:{title:'Política de evaluaciones y señales verificadas | Postulá Mejor',description:'Cómo funcionan las evaluaciones laborales verificadas y qué protecciones existen para ambas partes.',url:'https://postulamejor.com/politica-evaluaciones'}}

export default function EvaluationPolicy(){return <><PlatformHeader/><main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link className={styles.back} href="/">← Volver a Postulá Mejor</Link></div><article className={styles.card}>
 <span className={styles.eyebrow}>POSTULÁ MEJOR · CONFIANZA Y EVALUACIONES</span><h1>Cómo funcionan las calificaciones laborales</h1><div className={styles.updated}>Versión vigente desde el 27 de agosto de 2026.</div>
 <p className={styles.notice}>Las evaluaciones son opcionales y sólo corresponden a experiencias laborales vinculadas dentro de Postulá Mejor. No crean una lista negra, no reemplazan referencias formales y no determinan automáticamente una contratación.</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,margin:'24px 0'}}>
  <div style={{padding:16,borderRadius:16,background:'#f5f6ff',border:'1px solid #e1defe'}}><small style={{fontWeight:900,color:'#6554df'}}>01 · VÍNCULO VERIFICADO</small><b style={{display:'block',marginTop:7}}>Primero debe existir una contratación confirmada.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>Una empresa sólo puede evaluar a una persona que marcó como contratada, y esa persona sólo puede evaluar a esa empresa.</p></div>
  <div style={{padding:16,borderRadius:16,background:'#f7fafb',border:'1px solid #e2e7ea'}}><small style={{fontWeight:900,color:'#53616d'}}>02 · TIEMPO DE EXPERIENCIA</small><b style={{display:'block',marginTop:7}}>No se califica apenas empieza el vínculo.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>La evaluación se habilita después de 30 días de relación o antes si la relación laboral se marca como finalizada.</p></div>
  <div style={{padding:16,borderRadius:16,background:'#efffdf',border:'1px solid #d9efbf'}}><small style={{fontWeight:900,color:'#567b17'}}>03 · 30 DÍAS OPCIONALES</small><b style={{display:'block',marginTop:7}}>Evaluar o responder nunca es obligatorio.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>Desde que se habilita, ambas partes tienen 30 días para evaluar, modificar su evaluación o responder una recibida.</p></div>
 </div>
 <h2>1. Principio general</h2><p>Una evaluación representa la experiencia de una de las partes dentro de un vínculo laboral concreto. No certifica la conducta general de una persona o empresa, no garantiza desempeño futuro y no debe utilizarse como única razón para aceptar, rechazar o excluir a alguien.</p>
 <h2>2. Quién puede evaluar</h2><p>No se permiten calificaciones abiertas a cualquier usuario. La empresa debe haber confirmado en Postulá Mejor que contrató a esa persona. A partir de ese mismo registro queda determinada la pareja de participantes: esa empresa puede evaluar a esa persona y esa persona puede evaluar a esa empresa.</p><p>Cada parte puede emitir una evaluación por vínculo laboral. Postulá Mejor puede aplicar controles contra cuentas relacionadas, fraude, presión, incentivos, evaluaciones coordinadas o manipulación.</p>
 <h2>3. Cuándo se habilita</h2><p>Confirmar una contratación no habilita una calificación inmediata. Como regla general, se espera que transcurran 30 días desde el inicio confirmado para que exista una base mínima de experiencia. Si la relación laboral finaliza antes, una de las partes puede marcarla como finalizada y el período de evaluación puede habilitarse desde ese momento.</p>
 <h2>4. Período de evaluación y respuesta</h2><p>Una vez habilitada la evaluación, se abre un período de 30 días. Durante ese tiempo cada parte puede, si quiere, calificar de 1 a 5, dejar un comentario laboral, modificar su propia evaluación y responder u observar una evaluación recibida. No existe obligación de calificar ni penalización por no hacerlo.</p><p>Al finalizar ese período se cierra la edición y la respuesta ordinaria. Los mecanismos de soporte, integridad o corrección de datos siguen disponibles cuando corresponda.</p>
 <h2>5. Qué criterios corresponden</h2><p>Las señales deben referirse a la experiencia concreta y a aspectos razonablemente vinculados con el trabajo. Para una persona pueden incluir cumplimiento de lo acordado, comunicación, colaboración profesional y organización. Para una empresa pueden incluir claridad de condiciones, cumplimiento de pagos o acuerdos, trato, comunicación y organización.</p><p>No deben utilizarse datos sensibles ni características personales ajenas al desempeño o a las condiciones de la relación.</p>
 <h2>6. Comentarios, respuestas e indicador</h2><p>Los comentarios y respuestas completas forman parte del contexto de la experiencia entre las partes. El indicador público utiliza resultados agregados de experiencias cerradas y no publica automáticamente acusaciones, datos privados ni textos personales como si fueran hechos verificados.</p><p>Con menos de tres experiencias finalizadas puede mostrarse “Indicador en formación”. Desde tres experiencias cerradas, el promedio agregado puede traducirse en una señal simple como Favorable, Mixto o Desfavorable, acompañada por la cantidad de experiencias que la sostienen.</p>
 <h2>7. Contenido no permitido</h2><p>No se permite utilizar una evaluación para insultos, amenazas, hostigamiento, datos privados, datos sensibles, acusaciones delictivas o afirmaciones sobre terceros identificables. Los hechos graves deben comunicarse mediante soporte o a las autoridades competentes según corresponda.</p>
 <h2>8. Revisión, desacuerdo y corrección</h2><p>Durante el período de 30 días la persona evaluada puede dejar una respuesta u observación. Además, cualquiera de las partes puede solicitar revisión por soporte cuando considere que una evaluación no corresponde al vínculo, proviene de una cuenta no autorizada, contiene un dato objetivo incorrecto o infringe estas reglas.</p><p>Postulá Mejor puede marcar, limitar temporalmente o dejar de computar una señal cuando existan razones fundadas de integridad o seguridad, incluso después del cierre.</p>
 <h2>9. Protección de datos personales</h2><p>Las evaluaciones, vínculos asociados y resúmenes que puedan identificar a una persona se tratan conforme a la normativa argentina aplicable y a la <Link href="/privacidad">Política de Privacidad</Link>. Las personas pueden ejercer los derechos de acceso, actualización, rectificación o supresión que correspondan conforme a la Ley 25.326 y normativa complementaria.</p>
 <h2>10. Dignidad y no discriminación</h2><p>No se admiten evaluaciones basadas en motivos discriminatorios ni criterios relacionados con datos sensibles protegidos. Las señales no deben convertirse en una herramienta de persecución, represalia o exclusión automática.</p>
 <h2>11. Moderación e integridad</h2><p>Postulá Mejor puede revisar, limitar, ocultar o eliminar señales cuando existan indicios razonables de fraude, suplantación, conflicto de interés, extorsión, beneficio a cambio de una evaluación, presión, contenido abusivo, datos privados, irrelevancia o incumplimiento de esta política y de los Términos.</p>
 <h2>12. Alcance</h2><p>Postulá Mejor facilita la recolección y presentación contextual de señales dentro del servicio. No garantiza que una evaluación describa por completo una relación ni asume como propia la opinión emitida por un usuario.</p>
 <h2>13. Cambios de esta política</h2><p>Esta política puede actualizarse cuando cambie la función, la normativa, los criterios o los mecanismos de protección. La versión vigente y su fecha se publican en esta página.</p>
 <div className={styles.footer}>Consultá también los <Link href="/terminos">Términos y Condiciones</Link>, la <Link href="/privacidad">Política de Privacidad</Link> y el <Link href="/legales">Centro legal y de seguridad</Link>.</div>
 </article></div></main><PlatformFooter/></>}
