import type {Metadata} from 'next'
import Link from 'next/link'
import {PlatformFooter,PlatformHeader} from '../postula-preview/PlatformChrome'
import '../postula-preview/premium-v7.css'
import styles from '../legal.module.css'

export const metadata:Metadata={title:{absolute:'Política de evaluaciones y señales verificadas | Postulá Mejor'},description:'Reglas de Postulá Mejor para evaluaciones laborales verificadas, opcionales y bilaterales entre personas y empresas.',robots:{index:true,follow:true},alternates:{canonical:'https://postulamejor.com/politica-evaluaciones'}}

export default function EvaluationPolicy(){return <><PlatformHeader/><main className={styles.page}><div className={styles.shell}><div className={styles.top}><Link className={styles.back} href="/">← Volver a Postulá Mejor</Link></div><article className={styles.card}>
 <span className={styles.eyebrow}>POSTULÁ MEJOR · CONFIANZA Y EVALUACIONES</span><h1>Cómo funcionan las calificaciones laborales</h1><div className={styles.updated}>Versión vigente desde el 29 de agosto de 2026.</div>
 <p className={styles.notice}>Las evaluaciones son opcionales y sólo nacen de una contratación confirmada dentro de Postulá Mejor. No son una lista negra, no reemplazan referencias formales y no determinan automáticamente una contratación futura.</p>
 <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(190px,1fr))',gap:10,margin:'24px 0'}}>
  <div style={{padding:16,borderRadius:16,background:'#f5f6ff',border:'1px solid #e1defe'}}><small style={{fontWeight:900,color:'#6554df'}}>01 · VÍNCULO VERIFICADO</small><b style={{display:'block',marginTop:7}}>Primero tiene que existir una contratación real.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>El botón de contratación se habilita cuando el proceso ya tiene una entrevista confirmada o un acuerdo concreto registrado en Mensajes.</p></div>
  <div style={{padding:16,borderRadius:16,background:'#f7fafb',border:'1px solid #e2e7ea'}}><small style={{fontWeight:900,color:'#53616d'}}>02 · 30 DÍAS</small><b style={{display:'block',marginTop:7}}>No se califica al empezar.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>La evaluación se habilita automáticamente 30 días después de confirmar la contratación.</p></div>
  <div style={{padding:16,borderRadius:16,background:'#efffdf',border:'1px solid #d9efbf'}}><small style={{fontWeight:900,color:'#567b17'}}>03 · 5 PREGUNTAS</small><b style={{display:'block',marginTop:7}}>La nota sale de un promedio.</b><p style={{margin:'6px 0 0',fontSize:13,lineHeight:1.45}}>Cada parte responde cinco criterios del 1 al 5. El promedio de esas respuestas forma la calificación de esa experiencia.</p></div>
 </div>
 <h2>1. Quién puede evaluar</h2><p>La empresa sólo puede evaluar a una persona que figure como contratada en ese proceso, y esa persona sólo puede evaluar a la empresa vinculada a esa misma contratación. Cada lado puede dejar una evaluación por vínculo laboral.</p>
 <h2>2. Cuándo se habilita</h2><p>Confirmar una contratación inicia el plazo. Recién 30 días después se habilita la evaluación para ambas partes. La función no se activa por una simple postulación, por entrar a shortlist ni por estar solamente en etapa de entrevista.</p>
 <h2>3. Cómo se calcula la calificación</h2><p>La evaluación tiene cinco preguntas y cada una se responde con una puntuación del 1 al 5. Para una persona se consideran responsabilidad y cumplimiento, desempeño, comunicación y trato profesional, organización y puntualidad, y trabajo en equipo o adaptación. Para una empresa se consideran claridad de condiciones, cumplimiento de pagos y acuerdos, trato y respeto, comunicación y organización del trabajo.</p><p>La calificación de esa experiencia es el promedio matemático de las cinco respuestas. El perfil público muestra el promedio acumulado de las evaluaciones recibidas y la cantidad de evaluaciones que lo forman. Con una evaluación se muestra una; con dos se promedian ambas; y así sucesivamente.</p>
 <h2>4. Comentarios y réplica</h2><p>El comentario escrito es opcional. Cuando una parte envía su evaluación, la otra dispone de 30 días para dejar una observación o réplica si quiere aclarar algo o manifiesta disconformidad. La réplica no modifica automáticamente la puntuación original, pero queda asociada a esa experiencia.</p>
 <h2>5. Evaluar es opcional</h2><p>Ninguna de las partes está obligada a calificar. No evaluar no genera sanciones, pérdida de funciones ni una nota negativa automática.</p>
 <h2>6. Qué no corresponde incluir</h2><p>No se admiten insultos, amenazas, hostigamiento, datos privados o sensibles, acusaciones sobre terceros, ni contenido discriminatorio. La evaluación debe limitarse a aspectos razonablemente vinculados con la experiencia laboral concreta.</p>
 <h2>7. Integridad y moderación</h2><p>Postulá Mejor puede revisar, limitar o dejar de computar evaluaciones cuando existan indicios razonables de fraude, cuentas relacionadas, extorsión, presión, intercambio de beneficios por una nota, suplantación o incumplimiento de estas reglas.</p>
 <h2>8. Corrección y soporte</h2><p>Además de la réplica disponible durante 30 días, cualquiera de las partes puede comunicarse con soporte cuando considere que una evaluación no corresponde al vínculo, contiene un dato objetivo incorrecto o infringe esta política.</p>
 <h2>9. Datos personales</h2><p>Las evaluaciones y los vínculos asociados se tratan conforme a la normativa argentina aplicable y a la <Link href="/privacidad">Política de Privacidad</Link>. Las personas pueden ejercer los derechos de acceso, actualización, rectificación o supresión que correspondan.</p>
 <div className={styles.footer}>Consultá también los <Link href="/terminos">Términos y Condiciones</Link>, la <Link href="/privacidad">Política de Privacidad</Link> y el <Link href="/legales">Centro legal y de seguridad</Link>.</div>
 </article></div></main><PlatformFooter/></>}
