export default function LandingPage(){
  return <main style={{minHeight:'100vh',background:'radial-gradient(circle at 72% 25%,rgba(35,184,103,.18),transparent 28%),linear-gradient(135deg,#071625,#0b1d2e 58%,#071725)',color:'#fff',fontFamily:'Inter,system-ui,-apple-system,Segoe UI,sans-serif'}}>
    <header style={{height:70,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 6vw',borderBottom:'1px solid rgba(255,255,255,.08)'}}>
      <div style={{fontSize:20,fontWeight:950,letterSpacing:-.5}}>COMERCIO <span style={{color:'#29bd69'}}>LLENO</span> 🛒↗</div>
      <div style={{display:'flex',gap:10}}><a href="/login" style={{textDecoration:'none',color:'#fff',padding:'11px 17px',borderRadius:10,border:'1px solid rgba(255,255,255,.13)',background:'rgba(255,255,255,.07)',fontWeight:800}}>Ingresar</a><a href="/login" style={{textDecoration:'none',color:'#fff',padding:'11px 17px',borderRadius:10,background:'#20aa60',fontWeight:800}}>Probar gratis</a></div>
    </header>
    <section style={{minHeight:'calc(100vh - 70px)',display:'grid',gridTemplateColumns:'minmax(0,1.1fr) minmax(330px,.72fr)',gap:'5vw',alignItems:'center',padding:'5vh 7vw 7vh',boxSizing:'border-box'}}>
      <div><span style={{display:'inline-flex',alignItems:'center',border:'1px solid rgba(44,203,116,.28)',background:'rgba(44,203,116,.09)',color:'#56dd91',borderRadius:999,padding:'8px 12px',fontSize:11,fontWeight:900}}>● 14 DÍAS GRATIS · SIN INSTALACIÓN</span><h1 style={{fontSize:'clamp(42px,5.3vw,76px)',lineHeight:.98,letterSpacing:-3,margin:'22px 0 18px',maxWidth:760}}>Tu comercio, <span style={{color:'#32c873'}}>más simple</span> y bajo control.</h1><p style={{fontSize:17,lineHeight:1.65,color:'#c4cfda',maxWidth:650}}>Ventas, stock, caja, clientes y reportes en un solo lugar. Empezá en minutos y administrá tu negocio desde cualquier computadora.</p><div style={{display:'flex',gap:10,alignItems:'center',margin:'27px 0'}}><a href="/login" style={{textDecoration:'none',color:'#fff',padding:'12px 18px',borderRadius:10,background:'#20aa60',fontWeight:850}}>Empezar prueba gratis →</a><span style={{fontSize:12,color:'#9fb0c1'}}>14 días sin cargo</span></div><div style={{display:'flex',gap:22,flexWrap:'wrap',color:'#bac7d3',fontSize:12}}><span>✓ Punto de venta</span><span>✓ Control de stock</span><span>✓ Caja diaria</span><span>✓ Reportes</span></div></div>
      <aside style={{background:'#fff',color:'#17202a',borderRadius:22,padding:28,boxShadow:'0 28px 70px rgba(0,0,0,.32)'}}><h2 style={{margin:0,fontSize:22}}>Todo lo que necesitás</h2><div style={{fontSize:39,fontWeight:950,letterSpacing:-2,margin:'8px 0'}}>$ 9.990 <small style={{fontSize:13,fontWeight:700,color:'#71808d'}}>/ mes</small></div><p style={{color:'#71808d',fontSize:13,lineHeight:1.55}}>Probalo gratis durante 14 días. Después continuás por un precio simple y previsible.</p><div style={{display:'grid',gap:10,margin:'20px 0',fontSize:12}}><span>✓ Ventas y medios de pago</span><span>✓ Productos y stock</span><span>✓ Clientes y reportes</span><span>✓ Usuarios por comercio</span><span>✓ Asistente y centro de ayuda</span></div><a href="/login" style={{display:'flex',justifyContent:'center',textDecoration:'none',color:'#fff',padding:'12px 18px',borderRadius:10,background:'#20aa60',fontWeight:850}}>Crear mi cuenta gratis</a><p style={{fontSize:11,textAlign:'center',color:'#71808d'}}>Primero creás tu usuario y después configurás tu comercio.</p></aside>
    </section>
    <a target="_blank" rel="noopener noreferrer" href="https://wa.me/5491159609135?text=Hola%2C%20quiero%20consultar%20por%20Comercio%20Lleno" style={{position:'fixed',right:20,bottom:20,background:'#20aa60',color:'#fff',textDecoration:'none',borderRadius:999,padding:'12px 16px',fontSize:12,fontWeight:900,boxShadow:'0 12px 30px rgba(0,0,0,.24)'}}>💬 ¿Necesitás ayuda?</a>
  </main>
}
