import {NextRequest,NextResponse} from 'next/server'
import {getSellerFeatureState,normalizePhone,processSellerMessage,resetSellerConversation,sellerState} from './engine'

export const runtime='nodejs'
export const dynamic='force-dynamic'
const SUPABASE_URL=process.env.NEXT_PUBLIC_SUPABASE_URL??'https://wtcntclzcubkbtcsqkzc.supabase.co'
const PUBLISHABLE_KEY=process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY??'sb_publishable_02U2KDLDTR42KxdcFHtfYw_IDM00Deb'
type Auth={token:string;companyId:string;companyName:string}
function decodeSub(token:string){try{const p=token.split('.')[1];if(!p)return'';return String(JSON.parse(Buffer.from(p,'base64url').toString('utf8'))?.sub||'')}catch{return''}}
async function authorize(req:NextRequest):Promise<Auth>{const authorization=req.headers.get('authorization')||'';if(!authorization.toLowerCase().startsWith('bearer '))throw new Error('UNAUTHORIZED');const token=authorization.slice(7).trim(),userId=decodeSub(token);if(!userId)throw new Error('UNAUTHORIZED');const h={apikey:PUBLISHABLE_KEY,Authorization:`Bearer ${token}`};const profileResponse=await fetch(`${SUPABASE_URL}/rest/v1/profiles?id=eq.${encodeURIComponent(userId)}&select=company_id,role,active&limit=1`,{headers:h,cache:'no-store'});const profiles=await profileResponse.json().catch(()=>[]),profile=Array.isArray(profiles)?profiles[0]:null;if(!profileResponse.ok||!profile?.company_id||profile.active===false)throw new Error('UNAUTHORIZED');if(profile.role!=='owner')throw new Error('OWNER_ONLY');const companyResponse=await fetch(`${SUPABASE_URL}/rest/v1/companies?id=eq.${encodeURIComponent(profile.company_id)}&select=id,name&limit=1`,{headers:h,cache:'no-store'});const companies=await companyResponse.json().catch(()=>[]),company=Array.isArray(companies)?companies[0]:null;if(!companyResponse.ok||!company?.id)throw new Error('UNAUTHORIZED');return{token,companyId:String(company.id),companyName:String(company.name||'Mi comercio')}}
export async function POST(req:NextRequest){let auth:Auth;try{auth=await authorize(req)}catch(error){const code=error instanceof Error?error.message:'UNAUTHORIZED';return NextResponse.json({ok:false,error:code==='OWNER_ONLY'?'Sólo el propietario puede configurar y probar Vendedor IA WhatsApp.':'Sesión no disponible.'},{status:code==='OWNER_ONLY'?403:401})}const body=await req.json().catch(()=>({})),action=String(body?.action||'state');try{if(action==='state')return NextResponse.json({ok:true,...await sellerState(auth.token,auth.companyId,String(body?.phone||''))});if(action==='feature_state')return NextResponse.json({ok:true,feature:await getSellerFeatureState(auth.token,auth.companyId)});if(action==='reset'){await resetSellerConversation(auth.token,auth.companyId,String(body?.phone||''));return NextResponse.json({ok:true})}if(action==='message'){const phone=normalizePhone(body?.phone),text=String(body?.text||'').trim().slice(0,1500);if(phone.length<10)return NextResponse.json({ok:false,error:'Ingresá un número de prueba con código de país y área.'},{status:400});if(!text)return NextResponse.json({ok:false,error:'Escribí un mensaje para probar al vendedor.'},{status:400});return NextResponse.json({ok:true,...await processSellerMessage({token:auth.token,companyId:auth.companyId,companyName:auth.companyName,phone,text,externalMessageId:String(body?.externalMessageId||'')||null,commitSale:body?.commitSale===true})})}return NextResponse.json({ok:false,error:'Acción no válida.'},{status:400})}catch(error){const message=error instanceof Error?error.message:String(error);const status=/habilitado para este plan|todavía no activó|pausada/i.test(message)?409:500;return NextResponse.json({ok:false,error:message},{status})}}
