'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import {cvAuthClient} from '../../cv-ia/cvAuth'
import type {PreviewJob} from '../../postula-preview/jobs'
import styles from '../../postula-preview/platform.module.css'

type CandidateProfile={resume_path?:string;resume_name?:string;city?:string;neighborhood?:string;phone?:string;availability?:string;headline?:string;skills?:string[]}
async function authHeaders(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
export default function ApplicationWizard({job}:{job:PreviewJob}){
 const search=useSearchParams(),quickRequested=search.get('rapida')==='1'
 const [logged,setLogged]=useState<boolean|null>(null),[step,setStep]=useState(1),[name,setName]=useState(''),[phone,setPhone]=useState(''),[city,setCity]=useState(''),[cvFile,setCvFile]=useState<File|null>(null),[profileCv,setProfileCv]=useState<CandidateProfile>({}),[useProfileCv,setUseProfileCv]=useState(true),[letter,setLetter]=useState(''),[availability,setAvailability]=useState(''),[experience,setExperience]=useState(''),[expectedSalary,setExpectedSalary]=useState(''),[consent,setConsent]=useState(false),[saved,setSaved]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{(async()=>{const {data}=await cvAuthClient().auth.getSession();setLogged(Boolean(data.session));setName(String(data.session?.user.user_metadata?.full_name||''));if(!data.session)return;const r=await fetch('/api/postula/profile',{headers:{Authorization:`Bearer ${data.session.access_token}`}});const d=await r.json().catch(()=>({}));if(d?.ok){setName(d.profile?.display_name||String(data.session.user.user_metadata?.full_name||''));setProfileCv(d.candidate||{});setPhone(d.candidate?.phone||'');setCity([d.candidate?.neighborhood,d.candidate?.city].filter(Boolean).join(', '));setAvailability(d.candidate?.availability||'');setUseProfileCv(Boolean(d.candidate?.resume_path))}})()},[])
 const quickReady=Boolean(profileCv.resume_path&&name&&phone&&city)
 async function uploadResume(){if(useProfileCv&&profileCv.resume_path)return profileCv.resume_path;if(!cvFile)return'';const {data}=await cvAuthClient().auth.getSession();if(!data.session)throw new Error('Tu sesión venció.');const ext=(cvFile.name.split('.').pop()||'pdf').toLowerCase();const path=`${data.session.user.id}/application-${job.internalJobId||job.slug}-${Date.now()}.${ext}`;const {error}=await cvAuthClient().storage.from('postula-private').upload(path,cvFile,{upsert:false});if(error)throw error;return path}
 async function activateCandidate(){try{const {data}=await cvAuthClient().auth.getSession();if(!data.session)return;await fetch('/api/postula/profile',{method:'POST',headers:{Authorization:`Bearer ${data.session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({role:'candidate',activate_candidate:true,source:'job_application',terms_version:'2026-08-21'})})}catch{}}
 async function sendApplication({quick=false}:{quick?:boolean}={}){
  if(!consent)return;setBusy(true);setError('')
  try{
   await activateCandidate()
   const effectiveAvailability=availability||profileCv.availability||'A coordinar'
   const effectiveExperience=experience||(profileCv.headline?'Perfil laboral cargado':'A validar con el candidato')
   if(job.external){const payload={title:job.title,company:job.company,status:'Preparada',date:'Hoy',job:job.slug,cv:cvFile?.name||profileCv.resume_name||'',letter,availability:effectiveAvailability,experience:effectiveExperience,expected_salary:expectedSalary,quick};try{const raw=localStorage.getItem('pm_preview_applications');const rows=raw?JSON.parse(raw):[];localStorage.setItem('pm_preview_applications',JSON.stringify([payload,...rows.filter((r:any)=>r.job!==job.slug)]))}catch{}setSaved(true);setStep(4);return}
   if(!job.internalJobId)throw new Error('No encontramos el identificador de la búsqueda.')
   const resumePath=await uploadResume();const headers={'Content-Type':'application/json',...(await authHeaders())};const r=await fetch('/api/postula/applications',{method:'POST',headers,body:JSON.stringify({job_id:job.internalJobId,resume_path:resumePath,cover_letter:letter,name,phone,city,availability:effectiveAvailability,experience:effectiveExperience,expected_salary:expectedSalary})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos enviar la postulación.');setSaved(true);setStep(4)
  }catch(e){setError(e instanceof Error?e.message:'No pudimos guardar la postulación.')}finally{setBusy(false)}
 }
 async function save(e:FormEvent){e.preventDefault();await sendApplication()}
 if(logged===null)return <div className={styles.empty}>Validando tu cuenta…</div>
 if(!logged)return <div className={styles.formCard}><span className={styles.miniLabel}>Antes de postularte</span><h1>Creá tu cuenta gratis.</h1><p>La cuenta conserva tu CV, mensajes y estado de cada búsqueda. Postularse no tiene costo.</p><Link href={`/registro?next=${encodeURIComponent(`/postular/${job.slug}${quickRequested?'?rapida=1':''}`)}`} className={styles.button}>Crear cuenta con email</Link><div className={styles.securityBadge}>No te pedimos tarjeta para postularte. Los planes pagos son herramientas opcionales.</div></div>
 if(quickRequested&&quickReady&&step!==4)return <form className={`${styles.formCard} pm-quick-apply-card`} onSubmit={e=>{e.preventDefault();void sendApplication({quick:true})}}><span className={styles.miniLabel}>POSTULACIÓN RÁPIDA · {job.company}</span><h1>Confirmá y enviá.</h1><p>Ya tenemos tus datos básicos y el CV de tu perfil. Revisá lo esencial antes de compartirlo con esta búsqueda.</p><div className="pm-quick-summary"><div><small>CV</small><b>{profileCv.resume_name||'CV de tu perfil'}</b></div><div><small>Contacto</small><b>{phone}</b></div><div><small>Zona</small><b>{city}</b></div></div><div className={styles.field}><label>Sueldo bruto pretendido <small>(opcional)</small></label><div className="pm-salary-input"><span>$</span><input inputMode="numeric" value={expectedSalary} onChange={e=>setExpectedSalary(e.target.value.replace(/[^0-9.,]/g,''))} placeholder="Ej. 1.200.000"/></div><small style={{color:'#748495'}}>Es una referencia para esta postulación. No define por sí sola si avanzás o no.</small></div><div className={styles.questionCard}><label style={{display:'flex',gap:10,alignItems:'flex-start'}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{job.external?'Autorizo a Postulá Mejor a preparar este paquete con mi CV y datos. El envío final se realiza en el canal oficial.':'Autorizo a compartir mi CV y estos datos exclusivamente con la empresa de esta búsqueda para gestionar esta postulación.'}</span></label></div>{error&&<div className={styles.securityBadge} style={{color:'#a52b34'}}>{error}</div>}<button type="submit" className={`${styles.button} pm-quick-submit`} disabled={!consent||busy}>{busy?'Enviando…':job.external?'Preparar postulación rápida':'Postularme ahora'}</button><Link href={`/postular/${job.slug}`} className="pm-quick-normal">Prefiero revisar todos los datos</Link></form>
 return <form className={styles.formCard} onSubmit={save}><span className={styles.miniLabel}>{job.external?'Postulación asistida':'Postulación en Postulá Mejor'} · {job.company}</span><h1>{step===1?'Tus datos':step===2?'Tu presentación':step===3?'Revisá y autorizá':job.external?'Paquete preparado':'Postulación enviada'}</h1><p>{step<4?(job.external?'Completá sólo lo necesario. Si la oferta es externa, el envío final ocurre en el canal oficial.':'Completá sólo lo necesario. Esta empresa recibe la postulación dentro de la plataforma.'):(job.external?'Ya tenés todo ordenado. Revisá también el aviso oficial.':`Tu postulación ya llegó al espacio de selección de ${job.company}.`)}</p>
 {step===1&&<><div className={styles.fieldRow}><div className={styles.field}><label>Nombre y apellido</label><input value={name} onChange={e=>setName(e.target.value)} required/></div><div className={styles.field}><label>Teléfono</label><input value={phone} onChange={e=>setPhone(e.target.value)} required/></div></div><div className={styles.field}><label>Ciudad / zona</label><input value={city} onChange={e=>setCity(e.target.value)} placeholder="Ej. Palermo, CABA" required/></div>{profileCv.resume_path&&<div className={styles.questionCard}><label style={{display:'flex',gap:10,alignItems:'center'}}><input type="checkbox" checked={useProfileCv} onChange={e=>setUseProfileCv(e.target.checked)}/><span>Usar el CV de mi perfil: <b>{profileCv.resume_name||'CV adjunto'}</b></span></label></div>}<div className={styles.field}><label>{profileCv.resume_path?'O adjuntar otro CV':'CV para esta postulación'}</label><input type="file" accept=".pdf,.doc,.docx" onChange={e=>{setCvFile(e.target.files?.[0]||null);if(e.target.files?.[0])setUseProfileCv(false)}}/><small style={{color:'#748495'}}>PDF, DOC o DOCX. Queda privado y sólo se comparte con la empresa de esta búsqueda cuando autorizás la postulación.</small></div><div className={styles.heroActions}><button type="button" className={styles.buttonDark} onClick={()=>setStep(2)} disabled={!name||!phone||(!job.external&&!useProfileCv&&!cvFile)}>Continuar</button><Link className={styles.buttonLight} href={`/mejorar-cv?puesto=${encodeURIComponent(job.title)}&empresa=${encodeURIComponent(job.company)}`}>Mejorar mi CV primero</Link></div></>}
 {step===2&&<><div className={styles.field}><label>Presentación breve (opcional)</label><textarea value={letter} onChange={e=>setLetter(e.target.value)} placeholder={`Contale a ${job.company} por qué te interesa este rol y qué experiencia aporta valor.`}/></div><div className={styles.fieldRow}><div className={styles.field}><label>Disponibilidad</label><select value={availability} onChange={e=>setAvailability(e.target.value)} required><option value="">Elegir</option><option>Inmediata</option><option>15 días</option><option>30 días</option><option>A coordinar</option></select></div><div className={styles.field}><label>Experiencia relacionada</label><select value={experience} onChange={e=>setExperience(e.target.value)} required><option value="">Elegir</option><option>Sin experiencia específica</option><option>Menos de 1 año</option><option>1 a 3 años</option><option>3 a 5 años</option><option>Más de 5 años</option></select></div></div><div className={styles.field}><label>Sueldo bruto pretendido <small>(opcional)</small></label><div className="pm-salary-input"><span>$</span><input inputMode="numeric" value={expectedSalary} onChange={e=>setExpectedSalary(e.target.value.replace(/[^0-9.,]/g,''))} placeholder="Ej. 1.200.000"/></div><small style={{color:'#748495'}}>Se comparte sólo con la empresa de esta búsqueda como referencia de expectativa salarial.</small></div><div className={styles.aiNote}><b>Calidad antes que volumen.</b> Búsqueda Activa ayuda a priorizar y seguir postulaciones, pero no convierte tu cuenta en un bot que envía solicitudes sin control.</div><div className={styles.heroActions}><button type="button" className={styles.buttonLight} onClick={()=>setStep(1)}>Atrás</button><button type="button" className={styles.buttonDark} onClick={()=>setStep(3)} disabled={!availability||!experience}>Revisar</button></div></>}
 {step===3&&<><div className={styles.reviewBox}><h3>{job.title}</h3><p style={{fontSize:12,color:'#647587'}}>{name} · {city} · {(useProfileCv?profileCv.resume_name:cvFile?.name)||'Sin CV'}</p><p style={{fontSize:12,lineHeight:1.55,color:'#647587'}}>{letter||'Sin carta de presentación.'}</p>{expectedSalary&&<p style={{fontSize:12,lineHeight:1.55,color:'#647587'}}><b>Sueldo bruto pretendido:</b> ${expectedSalary}</p>}</div><div className={styles.questionCard}><label style={{display:'flex',gap:10,alignItems:'flex-start'}}><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/><span>{job.external?'Autorizo a Postulá Mejor a conservar este paquete para mi búsqueda. Si continúo al canal oficial, el envío final lo hago yo.':'Autorizo a Postulá Mejor a compartir este CV y estos datos exclusivamente con la empresa de esta búsqueda para gestionar mi postulación, mensajes y proceso de selección.'}</span></label></div><div className={styles.sourceNotice}>{job.external?`Esta búsqueda es externa. Postulá Mejor no representa a ${job.company} ni envía datos sin un canal válido.`:`Esta búsqueda fue publicada dentro de Postulá Mejor. El acceso del empleador está limitado por empresa y rol.`}</div>{error&&<div className={styles.securityBadge} style={{color:'#a52b34'}}>{error}</div>}<div className={styles.heroActions}><button type="button" className={styles.buttonLight} onClick={()=>setStep(2)}>Editar</button><button type="submit" className={styles.button} disabled={!consent||busy}>{busy?'Enviando…':job.external?'Guardar y continuar':'Enviar postulación'}</button></div></>}
 {step===4&&<><div className={styles.aiNote}><b>{saved?'Listo.':'Preparado.'}</b> {job.external?'Tu paquete quedó guardado. El siguiente paso abre la fuente oficial.':'La empresa ya puede ver esta postulación. Si inicia una conversación, te va a aparecer en Mensajes tanto desde PC como desde el celular.'}</div>{job.external?<a href={job.sourceUrl} target="_blank" rel="noopener noreferrer" className={styles.button}>Continuar en {job.company}</a>:<Link href="/mensajes" className={styles.button}>Ver mis mensajes</Link>}<Link href="/mi-cuenta" className={styles.buttonDark} style={{marginLeft:8}}>Ver mi tablero</Link></>}
 </form>
}
