import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
import {getVercelOidcToken} from '@vercel/oidc'

const SUPABASE_URL='https://pejkycdttogpmmdntzuq.supabase.co'
const SUPABASE_KEY='sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I'
const GATEWAY='https://ai-gateway.vercel.sh/v1/chat/completions'
const MODELS=['openai/gpt-5.4-nano','google/gemini-3.5-flash-lite','openai/gpt-5.4']
const ELIGIBLE_NEXO=new Set(['seleccion'])

type Candidate={application_id:string;user_id:string;name:string;score:number|null;role:string;status:string;availability:string;experience:string;city:string;cover_letter:string;reasons:string[];missing:string[];resume_path:string|null}
type JobDraft={title?:string;area?:string;location?:string;mode?:string;schedule?:string;salary?:string;tasks?:string[];requirements?:string[];tasks_confirmed?:boolean;requirements_confirmed?:boolean;description?:string;source_notes?:string[]}

function db(req:NextRequest){const auth=req.headers.get('authorization')||'';return createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
function clean(s:string){return s.replace(/\*\*/g,'').replace(/\*/g,'').replace(/#{1,6}\s*/g,'').trim()}
function normalizeText(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function requestedCount(q:string){const digit=q.match(/\b(\d{1,3})\b/);if(digit)return Math.max(1,Math.min(50,Number(digit[1])));const words:Record<string,number>={uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12,trece:13,catorce:14,quince:15,dieciseis:16,diecisiete:17,dieciocho:18,diecinueve:19,veinte:20,treinta:30,cuarenta:40,cincuenta:50};for(const [w,n] of Object.entries(words))if(new RegExp(`\\b${w}\\b`,'i').test(q))return n;return null}
function rank(list:Candidate[]){const stage:Record<string,number>={shortlist:4,interview:3,viewed:2,submitted:1};return [...list].sort((a,b)=>{const as=a.score==null?-1:a.score,bs=b.score==null?-1:b.score;if(bs!==as)return bs-as;return (stage[b.status]||0)-(stage[a.status]||0)})}
function candidateLabel(c:Candidate){return `${c.name} · ${c.role||'Perfil'}${c.score!=null?` · ${c.score}% de ajuste`:''}`}
function contextIds(body:any){return Array.isArray(body?.context_candidate_ids)?body.context_candidate_ids.map(String).slice(0,50):[]}
function usable(list:Candidate[]){return list.filter(x=>!['rejected','withdrawn','hired'].includes(x.status))}
const STAGES:Record<string,string>={submitted:'Recibidos',viewed:'Revisados',shortlist:'Preseleccionados',interview:'En entrevista',hired:'Contratados',rejected:'No seleccionados',withdrawn:'Retirados'}
const JOB_STATES:Record<string,string>={published:'Publicada',draft:'Borrador',paused:'Pausada',closed:'Cerrada',archived:'Archivada'}
const ROLES:Record<string,string>={owner:'Propietario',admin:'Administrador',recruiter:'RR. HH.',hiring_manager:'Responsable de contratación',viewer:'Consulta'}
function stageLabel(v:string){return STAGES[v]||'En proceso'}
function jobStateLabel(v:string){return JOB_STATES[v]||'En proceso'}
function roleLabel(v:string){return ROLES[v]||'Equipo'}
function verificationLabel(v:string){return v==='verified'?'Verificada':v==='basic'?'Validación básica':'Pendiente de validación'}
function publicAnswer(value:string){return clean(value).replace(/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi,'').replace(/\s*[—–-]?\s*(?:id|uuid)\s*[:#-]?\s*(?=[,.;)\n]|$)/gi,'').replace(/\s*\((?:estado|status)\s*:[^)]+\)/gi,'').replace(/\b(submitted|viewed|shortlist|interview|hired|rejected|withdrawn)\b/gi,m=>stageLabel(m.toLowerCase())).replace(/\bmatch orientativo\b/gi,'ajuste').replace(/\bmatch\b/gi,'ajuste').replace(/Puesto:\s*/gi,'').replace(/[ \t]{2,}/g,' ').replace(/\s+([,.;])/g,'$1').trim()}
function list(v:unknown){return Array.isArray(v)?v.map(x=>String(x||'').trim().slice(0,220)).filter(Boolean).slice(0,20):[]}
function text(v:unknown,n=500){return String(v??'').trim().slice(0,n)}
function wantsCreateJob(q:string){return /(?:publica|publicar|publicame|crear|crea|armar|arma|hacer|hace|cargar|carga).*(?:aviso|oferta|busqueda|vacante|empleo|puesto)|(?:aviso|oferta|busqueda|vacante).*(?:publica|publicar|crear|armar|hacer|cargar)/.test(q)}
function cancelJob(q:string){return /^(?:cancelar|cancela|olvidalo|dejalo|salir|no quiero seguir)(?:\s+.*)?$/.test(q)}
function confirmsPublish(q:string){return /^(?:si|sí|dale|ok|okay|confirmo|publicalo|publicálo|publicar|publica|publicá|mandalo|subilo)(?:[.!\s]*)$/.test(q)||/(?:si|sí|dale).*(?:publica|subi)|(?:publica|subi).*(?:si|sí|dale)/.test(q)}
function deterministicDescription(d:JobDraft){const parts=[`Buscamos ${d.title} para incorporarse al equipo.`,d.location?`La posición es para ${d.location}${d.mode?` y modalidad ${d.mode}`:''}.`:'',d.schedule?`Jornada: ${d.schedule}.`:'',d.tasks?.length?`Principales tareas: ${d.tasks.join('; ')}.`:'',d.requirements_confirmed?(d.requirements?.length?`Requisitos: ${d.requirements.join('; ')}.`:'No se indicaron requisitos excluyentes.'):''];return parts.filter(Boolean).join(' ')}
function nextJobQuestion(d:JobDraft){if(!d.title)return{step:'title',question:'¿Qué puesto necesitás cubrir?'};if(!d.location)return{step:'location',question:'¿En qué zona o localidad es el trabajo?'};if(!d.mode)return{step:'mode',question:'¿Es presencial, híbrido o remoto? Si todavía no está definido, decime “a coordinar”.'};if(!d.schedule)return{step:'schedule',question:'¿Qué jornada u horario querés ofrecer? Por ejemplo full time, part time o el horario concreto.'};if(!d.tasks_confirmed)return{step:'tasks',question:'¿Cuáles son las tareas principales? Decímelas como te salgan; yo después las redacto bien sin agregar nada.'};if(!d.requirements_confirmed)return{step:'requirements',question:'¿Qué requisitos querés pedir? Experiencia, conocimientos, disponibilidad, etc. Si no hay requisitos excluyentes, decime “ninguno”.'};return{step:'preview',question:''}}
function jobPreview(d:JobDraft){const req=d.requirements?.length?d.requirements.join(' · '):'Sin requisitos excluyentes indicados';return `Te lo armé así:\n${d.title} · ${d.location} · ${d.mode} · ${d.schedule}\n${d.description||deterministicDescription(d)}\nRequisitos: ${req}${d.salary?`\nRemuneración: ${d.salary}`:''}\nSi está correcto y cumple las reglas de publicación, decime “publicalo”. Si querés cambiar algo, decime qué.`}

async function gatewayKey(){let key=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;try{if(!key)key=await getVercelOidcToken()}catch{}return key||''}
async function askGatewayJson(system:string,user:string,maxTokens=700){const key=await gatewayKey();if(!key)return null;for(const model of MODELS){try{const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'user',content:user}],temperature:0,max_tokens:maxTokens}),cache:'no-store'});const data=await r.json().catch(()=>({}));if(!r.ok)continue;const raw=String(data?.choices?.[0]?.message?.content||'').trim();const match=raw.match(/\{[\s\S]*\}/);if(match)return JSON.parse(match[0])}catch{}}return null}
async function enrichJobDraft(c:any,companyId:string,current:JobDraft,message:string,step:string){const {data:quota,error}=await c.rpc('pm_consume_nexo_quota',{p_company_id:companyId});const canAI=!error&&Number(quota)>=0;let merged:JobDraft={...current,source_notes:[...(current.source_notes||[]),message].slice(-20)};if(canAI){const system=`Sos el asistente que arma avisos de empleo para Postulá Mejor. Tu única tarea es extraer y ordenar datos que el empleador YA DIJO. Nunca inventes, completes, supongas ni mejores requisitos con información nueva. Conservá los datos previos salvo que el usuario los corrija. Respondé SOLO JSON válido con esta forma: {"title":string|null,"area":string|null,"location":string|null,"mode":string|null,"schedule":string|null,"salary":string|null,"tasks":string[],"requirements":string[],"tasks_confirmed":boolean,"requirements_confirmed":boolean,"description":string|null}. Si el usuario dice que no hay requisitos, requirements=[] y requirements_confirmed=true. Si todavía no dio tareas, tasks_confirmed=false. Si después de combinar los datos ya están definidos puesto, ubicación, modalidad, jornada, tareas y requisitos, redactá description en español natural y profesional usando EXCLUSIVAMENTE esos datos. No agregues beneficios, años de experiencia, estudios, género, edad, salario, horarios ni condiciones que no hayan sido informados.`;const parsed=await askGatewayJson(system,`Datos ya confirmados: ${JSON.stringify(current)}\nPaso actual: ${step}\nMensaje nuevo del empleador: ${message}`);if(parsed){const scalar=['title','area','location','mode','schedule','salary','description'] as const;for(const k of scalar){if(parsed[k]!=null&&text(parsed[k],k==='description'?6000:500))merged[k]=text(parsed[k],k==='description'?6000:500)}if(Array.isArray(parsed.tasks)){merged.tasks=list(parsed.tasks);merged.tasks_confirmed=Boolean(parsed.tasks_confirmed)||merged.tasks.length>0}else if(parsed.tasks_confirmed===true){merged.tasks_confirmed=true}if(Array.isArray(parsed.requirements)){merged.requirements=list(parsed.requirements);merged.requirements_confirmed=Boolean(parsed.requirements_confirmed)||merged.requirements.length>0}else if(parsed.requirements_confirmed===true){merged.requirements_confirmed=true}}}
 if(!canAI||!merged.title&&step==='title'){
  const raw=message.trim();if(step==='title'&&raw.length>=2)merged.title=raw.slice(0,180);else if(step==='location'&&raw.length>=2)merged.location=raw.slice(0,180);else if(step==='mode'&&raw.length>=2)merged.mode=raw.slice(0,30);else if(step==='schedule'&&raw.length>=2)merged.schedule=raw.slice(0,60);else if(step==='tasks'&&raw.length>=2){merged.tasks=raw.split(/[;,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,20);merged.tasks_confirmed=true}else if(step==='requirements'&&raw.length>=2){if(/^(ninguno|ninguna|no hay|sin requisitos)/i.test(raw)){merged.requirements=[];merged.requirements_confirmed=true}else{merged.requirements=raw.split(/[;,\n]/).map(x=>x.trim()).filter(Boolean).slice(0,20);merged.requirements_confirmed=true}}
 }
 if(merged.tasks?.length)merged.tasks_confirmed=true;if(merged.requirements?.length)merged.requirements_confirmed=true
 return merged
}
async function saveMessage(c:any,companyId:string,userId:string,role:'user'|'ai',body:string,ids:string[]=[]){try{await c.from('pm_nexo_messages').insert({company_id:companyId,user_id:userId,role,body:text(body,8000),context_candidate_ids:ids.slice(0,50)})}catch{}}
async function saveState(c:any,companyId:string,userId:string,patch:Record<string,any>){try{await c.from('pm_nexo_state').upsert({company_id:companyId,user_id:userId,...patch,updated_at:new Date().toISOString()},{onConflict:'company_id,user_id'})}catch{}}
async function clearJobState(c:any,companyId:string,userId:string){await saveState(c,companyId,userId,{job_step:null,job_draft:{}})}

export async function GET(req:NextRequest){
 const c=db(req);const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({ok:false,error:'Iniciá sesión.'},{status:401})
 const requested=req.nextUrl.searchParams.get('company_id')||'';let mq=c.from('pm_company_members').select('company_id,pm_companies(name)').eq('user_id',user.id).eq('status','active');if(requested)mq=mq.eq('company_id',requested);const {data:m}=await mq.limit(1).maybeSingle();if(!m)return NextResponse.json({ok:false,error:'No encontramos una empresa autorizada.'},{status:403});const companyId=String(m.company_id)
 const [{data:rows},{data:state}]=await Promise.all([c.from('pm_nexo_messages').select('role,body,context_candidate_ids,created_at').eq('company_id',companyId).eq('user_id',user.id).order('created_at',{ascending:false}).limit(200),c.from('pm_nexo_state').select('context_candidate_ids,job_step,job_draft,updated_at').eq('company_id',companyId).eq('user_id',user.id).maybeSingle()])
 return NextResponse.json({ok:true,company_id:companyId,company_name:String((m as any).pm_companies?.name||''),messages:(rows||[]).reverse(),state:state||null})
}

export async function POST(req:NextRequest){
 if(!(req.headers.get('content-type')||'').includes('application/json'))return NextResponse.json({ok:false,error:'Formato inválido.'},{status:415})
 const c=db(req);const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user)return NextResponse.json({ok:false,error:'Iniciá sesión como integrante de una empresa.'},{status:401})
 const body=await req.json().catch(()=>({}));const rawMessage=String(body?.message||'').trim().slice(0,2000);const message=rawMessage.split(/\n\nRespondé de forma breve/i)[0].trim();if(!message)return NextResponse.json({ok:false,error:'Escribí o dictá una consulta.'},{status:400})
 const requestedCompany=String(body?.company_id||'').trim();let membershipQuery=c.from('pm_company_members').select('company_id,role,pm_companies(id,name,verification_status)').eq('user_id',user.id).eq('status','active');if(requestedCompany)membershipQuery=membershipQuery.eq('company_id',requestedCompany)
 const {data:membership,error:mErr}=await membershipQuery.limit(1).maybeSingle();if(mErr||!membership)return NextResponse.json({ok:false,error:'No encontramos una empresa autorizada para esta cuenta.'},{status:403})
 const companyId=String(membership.company_id),companyName=String((membership as any).pm_companies?.name||'Tu empresa'),companyVerification=String((membership as any).pm_companies?.verification_status||'pending'),memberRole=String(membership.role||'viewer')
 const {data:subscription,error:subscriptionError}=await c.from('pm_company_subscriptions').select('plan,status,provider,current_period_end').eq('company_id',companyId).maybeSingle();if(subscriptionError)return NextResponse.json({ok:false,error:'No pudimos verificar el acceso a Nexo.'},{status:503})
 const activePlan=subscription?.status==='authorized'?String(subscription.plan||'gratis'):'gratis';const trialExpired=subscription?.provider==='trial'&&subscription?.current_period_end&&new Date(subscription.current_period_end).getTime()<=Date.now();if(trialExpired||subscription?.status!=='authorized'||!ELIGIBLE_NEXO.has(activePlan))return NextResponse.json({ok:false,code:'nexo_plan_required',error:'Nexo se habilita con el plan Selección IA.',plan:activePlan},{status:402})
 const {data:nexoState}=await c.from('pm_nexo_state').select('context_candidate_ids,job_step,job_draft').eq('company_id',companyId).eq('user_id',user.id).maybeSingle();await saveMessage(c,companyId,user.id,'user',message,Array.isArray(nexoState?.context_candidate_ids)?nexoState.context_candidate_ids:[])
 const reply=async(payload:Record<string,any>,init?:ResponseInit)=>{const answer=payload.answer?publicAnswer(String(payload.answer)):'';const ids=Array.isArray(payload.selected_candidate_ids)?payload.selected_candidate_ids.map(String).slice(0,50):undefined;if(ids)await saveState(c,companyId,user.id,{context_candidate_ids:ids});if(answer)await saveMessage(c,companyId,user.id,'ai',answer,ids||[]);return NextResponse.json(answer?{...payload,answer}:payload,init)}

 const [{data:companyJobs,error:jobsError},{data:teamRows,error:teamError}]=await Promise.all([c.from('pm_jobs').select('id,title,status,location_text').eq('company_id',companyId).order('created_at',{ascending:false}).limit(100),c.from('pm_company_members').select('user_id,role,status').eq('company_id',companyId).eq('status','active').limit(100)])
 if(jobsError)return NextResponse.json({ok:false,error:'No pudimos leer las búsquedas de esta empresa.'},{status:400});if(teamError)return NextResponse.json({ok:false,error:'No pudimos leer el equipo de esta empresa.'},{status:400})
 const requestedJob=String(body?.job_id||'').trim();let appQuery=c.from('pm_applications').select('id,candidate_user_id,resume_path,cover_letter,status,candidate_snapshot,created_at,pm_jobs!inner(id,title,company_id),pm_candidate_matches(score,reasons,missing_evidence,model_version)').eq('pm_jobs.company_id',companyId).order('created_at',{ascending:false}).limit(500);if(requestedJob)appQuery=appQuery.eq('job_id',requestedJob)
 const {data:apps,error:aErr}=await appQuery;if(aErr)return NextResponse.json({ok:false,error:'No pudimos leer las postulaciones de esta empresa.'},{status:400})
 const candidates:Candidate[]=(apps||[]).map((a:any)=>{const match=Array.isArray(a.pm_candidate_matches)?a.pm_candidate_matches[0]:a.pm_candidate_matches,snap=a.candidate_snapshot||{};return {application_id:String(a.id),user_id:String(a.candidate_user_id),name:String(snap.display_name||'Candidato/a'),score:match?.score==null?null:Number(match.score),role:String(a.pm_jobs?.title||''),status:String(a.status||'submitted'),availability:String(snap.availability||'No informada'),experience:String(snap.experience||'No informada'),city:String(snap.city||'No informada'),cover_letter:String(a.cover_letter||''),reasons:Array.isArray(match?.reasons)?match.reasons.map(String):[],missing:Array.isArray(match?.missing_evidence)?match.missing_evidence.map(String):[],resume_path:a.resume_path?String(a.resume_path):null}})
 const q=normalizeText(message),stateIds=Array.isArray(nexoState?.context_candidate_ids)?nexoState.context_candidate_ids.map(String):[],bodyIds=contextIds(body),selectedIds=bodyIds.length?bodyIds:stateIds,selected=selectedIds.map(id=>candidates.find(x=>x.application_id===id)).filter(Boolean) as Candidate[],sorted=rank(candidates),jobs=companyJobs||[],activeJobs=jobs.filter((x:any)=>String(x.status)==='published'),team=teamRows||[]

 let jobStep=String(nexoState?.job_step||''),jobDraft=(nexoState?.job_draft&&typeof nexoState.job_draft==='object'?nexoState.job_draft:{}) as JobDraft
 if(jobStep||wantsCreateJob(q)){
  if(!['owner','admin','recruiter'].includes(memberRole))return reply({ok:true,answer:'Tu rol puede consultar Nexo, pero no puede crear ni publicar avisos. Necesitás un acceso de propietario, administrador o RR. HH.',intent:'job_permission'})
  if(cancelJob(q)){await clearJobState(c,companyId,user.id);return reply({ok:true,answer:'Listo, descarté el aviso que estábamos armando.',intent:'job_cancelled'})}
  if(jobStep==='preview'&&confirmsPublish(q)){
   if(!['basic','verified'].includes(companyVerification))return reply({ok:true,answer:'Antes de publicarlo falta completar la validación básica de la empresa.',intent:'job_validation_required'})
   const description=text(jobDraft.description||deterministicDescription(jobDraft),10000);if(!jobDraft.title||!jobDraft.location||description.length<30)return reply({ok:true,answer:'Me falta información del aviso antes de poder publicarlo. Decime qué querés corregir y lo terminamos.',intent:'job_incomplete'})
   const version='2026-08-21';const consentRows=['terms','privacy','employer_publish_rules'].map(consent_type=>({user_id:user.id,consent_type,version,accepted:true,source:'nexo_job_publish'}));const {error:consentErr}=await c.from('pm_consents').upsert(consentRows,{onConflict:'user_id,consent_type,version',ignoreDuplicates:true});if(consentErr)return reply({ok:true,answer:'No pude registrar la confirmación de las reglas. Probá nuevamente.',intent:'job_publish_error'})
   const {data:draft,error:draftErr}=await c.from('pm_jobs').insert({company_id:companyId,title:text(jobDraft.title,180),area:text(jobDraft.area,100)||null,location_text:text(jobDraft.location,180)||null,public_location_text:null,employer_visibility:'public',work_mode:text(jobDraft.mode,30)||null,schedule:text(jobDraft.schedule,60)||null,compensation_text:text(jobDraft.salary,120)||null,description,requirements:list(jobDraft.requirements),status:'draft',created_by:user.id,published_at:null,closes_at:null}).select('*').single();if(draftErr||!draft)return reply({ok:true,answer:'No pude guardar el aviso. No publiqué nada. Probá otra vez en unos segundos.',intent:'job_publish_error'})
   const {error:activateError}=await c.rpc('pm_activate_job_with_credit',{p_job_id:draft.id,p_event_type:'publish'});await clearJobState(c,companyId,user.id);if(activateError){if(/publication_credit_exhausted/i.test(activateError.message))return reply({ok:true,answer:`El aviso de ${jobDraft.title} quedó guardado como borrador, pero no te quedan créditos de publicación este mes.`,intent:'job_saved_draft'});return reply({ok:true,answer:`Guardé el aviso de ${jobDraft.title} como borrador, pero no pude activarlo. Podés retomarlo desde Publicaciones.`,intent:'job_saved_draft'})}
   return reply({ok:true,answer:`Listo. Publiqué el aviso de ${jobDraft.title} para ${jobDraft.location}. Ya quedó activo y puede empezar a recibir postulaciones.`,intent:'job_published',job_id:draft.id})
  }
  if(jobStep==='preview'&&/^(?:no|todavia no|todavía no)$/i.test(message.trim()))return reply({ok:true,answer:'Perfecto. Decime qué querés cambiar del aviso y lo ajusto antes de publicar.',intent:'job_edit_waiting'})
  if(!jobStep){jobStep='title';jobDraft={source_notes:[]}}
  jobDraft=await enrichJobDraft(c,companyId,jobDraft,message,jobStep)
  const next=nextJobQuestion(jobDraft);jobStep=next.step;if(jobStep==='preview'&&!jobDraft.description)jobDraft.description=deterministicDescription(jobDraft)
  await saveState(c,companyId,user.id,{job_step:jobStep,job_draft:jobDraft})
  if(jobStep==='preview')return reply({ok:true,answer:jobPreview(jobDraft),intent:'job_preview'})
  return reply({ok:true,answer:`Sí, lo puedo armar y publicar desde Nexo. ${next.question}`,intent:'job_collect',job_step:jobStep})
 }

 const wantsRoute=/(envia|enviar|manda|mandar|reenvia|reenviar|deriva|derivar|pasa|pasar).*(rrhh|recursos humanos|recruiter)/.test(q)
 if(wantsRoute){if(!['owner','admin','recruiter','hiring_manager'].includes(memberRole))return NextResponse.json({ok:false,error:'Tu rol no puede derivar candidatos.'},{status:403});const count=requestedCount(q);const base=selected.length?selected:usable(sorted);const chosen=base.slice(0,count||base.length||5);if(!chosen.length)return reply({ok:true,answer:'Todavía no hay candidatos disponibles para derivar.',selected_candidate_ids:[],intent:'route_empty'});const priorities=['recruiter','hiring_manager','admin'];let recipient:any=null;for(const role of priorities){recipient=team.find((x:any)=>String(x.user_id)!==user.id&&String(x.role)===role);if(recipient)break}if(!recipient)return reply({ok:true,tenant:companyId,company:companyName,answer:'Todavía no hay una persona asignada a RR. HH. o contratación. Podés agregarla desde Equipo y permisos.',selected_candidate_ids:chosen.map(x=>x.application_id),intent:'route_missing_recipient'});const rows=chosen.map(x=>({company_id:companyId,application_id:x.application_id,sender_user_id:user.id,recipient_user_id:recipient.user_id,recipient_role:recipient.role,note:'Derivado desde Nexo',status:'pending'}));const {error}=await c.from('pm_candidate_handoffs').upsert(rows,{onConflict:'application_id,recipient_user_id,status',ignoreDuplicates:true});if(error)return NextResponse.json({ok:false,error:'No pudimos crear la derivación interna.'},{status:400});const recipientName=roleLabel(String(recipient.role));return reply({ok:true,tenant:companyId,company:companyName,answer:`Listo. Envié ${chosen.length} postulaciones a ${recipientName}: ${chosen.map(x=>x.name).join(', ')}.`,selected_candidate_ids:chosen.map(x=>x.application_id),intent:'route',delivery:{destination:'Equipo interno',recipient:recipientName,count:chosen.length,status:'created'}})}
 if(!candidates.length)return reply({ok:true,tenant:companyId,company:companyName,answer:`Todavía no hay postulaciones para revisar.${activeJobs.length?` Tenés ${activeJobs.length} búsquedas publicadas.`:''}`,selected_candidate_ids:[]})
 const wantsBest=/(cual|quien).*(mejor)|\bmejor\b|\bconviene\b/.test(q)
 if(wantsBest&&selected.length){const chosen=rank(selected),best=chosen[0];const reason=best.reasons[0]?` ${best.reasons[0]}.`:'';const missing=best.missing[0]?` Falta validar ${best.missing[0].toLowerCase()}.`:'';return reply({ok:true,tenant:companyId,company:companyName,answer:`Hoy me quedo con ${candidateLabel(best)}.${reason}${missing}`,selected_candidate_ids:chosen.map(x=>x.application_id),intent:'best'})}
 if(/(mejor(?:es)?|top|ranking|conviene|recomenda).*(curr|cv|candidat|postul|perfil)|(?:curr|cv|candidat|postul|perfil).*(mejor(?:es)?|top|ranking|conviene|recomenda)/.test(q)){const n=requestedCount(q)||5,chosen=usable(sorted).slice(0,n);return reply({ok:true,tenant:companyId,company:companyName,answer:`Los que mejor encajan hoy son:\n${chosen.map((x,i)=>`${i+1}. ${candidateLabel(x)}`).join('\n')}\nDecime cuál querés revisar.`,selected_candidate_ids:chosen.map(x=>x.application_id),intent:'shortlist'})}
 if(/(cuantos|cantidad|total).*(candidat|cv|postul)|(?:candidat|cv|postul).*(cuantos|cantidad|total)/.test(q)&&!/embudo|pipeline|etapas?/.test(q))return reply({ok:true,tenant:companyId,company:companyName,answer:`Tenés ${candidates.length} postulaciones en total.`,selected_candidate_ids:[]})
 if(/embudo|pipeline|etapas?/.test(q)){const counts=candidates.reduce((acc:Record<string,number>,x)=>{acc[x.status]=(acc[x.status]||0)+1;return acc},{});return reply({ok:true,tenant:companyId,company:companyName,answer:`Tenés ${candidates.length} postulaciones. ${Object.entries(counts).map(([k,v])=>`${stageLabel(k)}: ${v}`).join(' · ')}.`,selected_candidate_ids:[]})}
 if(/(mi empresa|perfil de empresa|empresa actual|verificacion|verificada|mi cuenta)/.test(q))return reply({ok:true,tenant:companyId,company:companyName,answer:`Estás trabajando sobre ${companyName}. ${verificationLabel(companyVerification)}. Tenés ${activeJobs.length} búsquedas publicadas y ${candidates.length} postulaciones.`,selected_candidate_ids:[]})
 if(/(busquedas|ofertas|avisos|puestos|publicaciones)/.test(q)&&!/(candidat|cv|postul)/.test(q)){const chosen=jobs.slice(0,8);return reply({ok:true,tenant:companyId,company:companyName,answer:chosen.length?`${activeJobs.length} búsquedas publicadas. ${chosen.map((x:any)=>`${x.title}${x.location_text?` · ${x.location_text}`:''}${/estado|status|borrador|pausad|cerrad/.test(q)?` · ${jobStateLabel(String(x.status))}`:''}`).join(' · ')}`:'Todavía no hay búsquedas creadas.',selected_candidate_ids:[]})}
 if(/(equipo|usuarios|miembros|permisos|rrhh)/.test(q)){const byRole=team.reduce((acc:Record<string,number>,x:any)=>{const role=roleLabel(String(x.role||'viewer'));acc[role]=(acc[role]||0)+1;return acc},{});return reply({ok:true,tenant:companyId,company:companyName,answer:`El equipo tiene ${team.length} integrantes. ${Object.entries(byRole).map(([role,count])=>`${role}: ${count}`).join(' · ')}`,selected_candidate_ids:[]})}
 const named=candidates.filter(x=>q.includes(normalizeText(x.name.split(' ')[0]))).slice(0,8)
 if(/compara|comparame|diferencia/.test(q)&&named.length>=2)return reply({ok:true,tenant:companyId,company:companyName,answer:named.map(x=>`${candidateLabel(x)}.${x.reasons[0]?` A favor: ${x.reasons[0]}.`:''}${x.missing[0]?` Falta validar: ${x.missing[0]}.`:''}`).join('\n'),selected_candidate_ids:named.map(x=>x.application_id),intent:'compare'})
 if(/disponibil|horario|turno|sabado|domingo/.test(q)){const chosen=named.length?named:(selected.length?selected:usable(sorted).slice(0,8));return reply({ok:true,tenant:companyId,company:companyName,answer:chosen.map(x=>`${x.name}: ${x.availability}${x.city&&x.city!=='No informada'?` · ${x.city}`:''}`).join('\n'),selected_candidate_ids:chosen.map(x=>x.application_id),intent:'availability'})}
 if(/preguntas?.*(entrevista)|entrevista.*preguntas?/.test(q)){const chosen=selected.length?selected.slice(0,6):(named.length?named:usable(sorted).slice(0,4));return reply({ok:true,tenant:companyId,company:companyName,answer:`Para ${chosen.map(x=>x.name).join(', ')} preguntaría por experiencia similar, disponibilidad real, fortalezas para el puesto y los datos que todavía falten validar.`,selected_candidate_ids:chosen.map(x=>x.application_id),intent:'interview'})}
 if(/(plan|suscripcion|nexo|pago)/.test(q)&&!/(candidat|cv|postul)/.test(q))return reply({ok:true,tenant:companyId,company:companyName,answer:'Tenés Selección IA activa y Nexo habilitado.',selected_candidate_ids:[]})

 const safeCandidates=sorted.slice(0,50).map(x=>({nombre:x.name,ajuste:x.score,puesto:x.role,disponibilidad:x.availability,experiencia:x.experience,zona:x.city,carta:x.cover_letter.slice(0,500),razones:x.reasons,falta_validar:x.missing})),safeAccount={empresa:{nombre:companyName,verificacion:verificationLabel(companyVerification),plan:'Selección IA'},busquedas:jobs.slice(0,30).map((x:any)=>({titulo:x.title,ubicacion:x.location_text||''})),equipo:team.map((x:any)=>({rol:roleLabel(String(x.role||'viewer'))})),postulaciones:safeCandidates,seleccion_actual:selected.map(x=>({nombre:x.name,puesto:x.role,ajuste:x.score}))}
 const {data:quota,error:quotaError}=await c.rpc('pm_consume_nexo_quota',{p_company_id:companyId});if(quotaError||Number(quota)<0)return reply({ok:true,tenant:companyId,company:companyName,answer:'Llegaste al límite de consultas abiertas con IA por esta hora. Los conteos, rankings, comparaciones, publicaciones y derivaciones siguen funcionando.',intent:'ai_quota'})
 const key=await gatewayKey();if(!key)return reply({ok:true,tenant:companyId,company:companyName,answer:'Puedo revisar postulantes, comparar perfiles, preparar rankings, entrevistas, publicaciones y derivaciones.',selected_candidate_ids:selectedIds})
 const {data:recentRows}=await c.from('pm_nexo_messages').select('role,body').eq('company_id',companyId).eq('user_id',user.id).order('created_at',{ascending:false}).limit(14);const history=(recentRows||[]).reverse();if(history.length&&history[history.length-1]?.role==='user'&&history[history.length-1]?.body===message)history.pop()
 const system=`Sos Nexo, asistente de selección de Postulá Mejor para ${companyName}. Respondé en español rioplatense, natural, claro y muy breve: por defecto 2 a 5 líneas y menos de 90 palabras. Priorizá nombre, puesto y el dato útil para decidir. No muestres jamás IDs, UUIDs, códigos, nombres de tablas, campos internos, estados técnicos, roles técnicos ni etiquetas del backend. No digas submitted, viewed, shortlist, interview, hired, rejected o withdrawn salvo que el usuario pida explícitamente las etapas, y aun así traducilas a español natural. No uses rótulos como 'Puesto:', 'Estado:' o 'Match orientativo:'. No repitas datos ni expliques el criterio salvo que te lo pidan. Sólo usá el contexto autorizado de esta empresa. Nunca inventes CV, experiencia, referencias, identidad ni puntajes. Nunca uses edad, género, foto, salud, religión, origen u otros datos sensibles para evaluar. Si falta un dato importante, decí brevemente que falta validar. Para acciones que modifican datos, no simules haber ejecutado una acción si no fue ejecutada por el backend. Si el usuario quiere crear o publicar un aviso, indicá que Nexo puede hacerlo y pedile iniciar el flujo; no digas que no tenés esa capacidad.`
 let last='';for(const model of MODELS){try{const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'system',content:`Contexto autorizado: ${JSON.stringify(safeAccount)}`},...history.map((h:any)=>({role:h.role==='ai'?'assistant':'user',content:String(h.body)})),{role:'user',content:message}],temperature:.1,max_tokens:240}),cache:'no-store'});const data=await r.json().catch(()=>({}));if(r.ok){const answer=publicAnswer(String(data?.choices?.[0]?.message?.content||''));if(answer)return reply({ok:true,tenant:companyId,company:companyName,answer,model,selected_candidate_ids:selectedIds})}last=String(data?.error?.message||data?.error||`AI ${r.status}`)}catch(e){last=e instanceof Error?e.message:String(e)}}
 return reply({ok:true,tenant:companyId,company:companyName,answer:'No pude completar esa consulta con IA ahora. Igual podés pedirme conteos, rankings, comparaciones, publicaciones o derivaciones.',selected_candidate_ids:selectedIds,note:last||undefined})
}
