import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
import {getVercelOidcToken} from '@vercel/oidc'

const SUPABASE_URL='https://pejkycdttogpmmdntzuq.supabase.co'
const SUPABASE_KEY='sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I'
const GATEWAY='https://ai-gateway.vercel.sh/v1/chat/completions'
const MODELS=['openai/gpt-5.4-nano','google/gemini-3.5-flash-lite','openai/gpt-5.4']
const ELIGIBLE_NEXO=new Set(['seleccion'])
type Candidate={application_id:string;user_id:string;name:string;score:number|null;role:string;status:string;availability:string;experience:string;city:string;cover_letter:string;reasons:string[];missing:string[];resume_path:string|null}
function db(req:NextRequest){const auth=req.headers.get('authorization')||'';return createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
function clean(s:string){return s.replace(/\*\*/g,'').replace(/\*/g,'').replace(/#{1,6}\s*/g,'').trim()}
function normalizeText(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function requestedCount(q:string){const digit=q.match(/\b(\d{1,3})\b/);if(digit)return Math.max(1,Math.min(50,Number(digit[1])));const words:Record<string,number>={uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12,trece:13,catorce:14,quince:15,dieciseis:16,diecisiete:17,dieciocho:18,diecinueve:19,veinte:20,treinta:30,cuarenta:40,cincuenta:50};for(const [w,n] of Object.entries(words))if(new RegExp(`\\b${w}\\b`,'i').test(q))return n;return null}
function rank(list:Candidate[]){const stage:Record<string,number>={shortlist:4,interview:3,viewed:2,submitted:1};return [...list].sort((a,b)=>{const as=a.score==null?-1:a.score,bs=b.score==null?-1:b.score;if(bs!==as)return bs-as;return (stage[b.status]||0)-(stage[a.status]||0)})}
function candidateLabel(c:Candidate){return `${c.name}${c.score!=null?` · match ${c.score}%`:''} · ${c.role||'perfil sin puesto'} · ${c.status}`}
function contextIds(body:any){return Array.isArray(body?.context_candidate_ids)?body.context_candidate_ids.map(String).slice(0,50):[]}
function usable(list:Candidate[]){return list.filter(x=>!['rejected','withdrawn','hired'].includes(x.status))}

export async function POST(req:NextRequest){
 if(!(req.headers.get('content-type')||'').includes('application/json'))return NextResponse.json({ok:false,error:'Formato inválido.'},{status:415})
 const c=db(req);const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user)return NextResponse.json({ok:false,error:'Iniciá sesión como integrante de una empresa.'},{status:401})
 const body=await req.json().catch(()=>({})),message=String(body?.message||'').trim().slice(0,1600);if(!message)return NextResponse.json({ok:false,error:'Escribí o dictá una consulta.'},{status:400})
 const requestedCompany=String(body?.company_id||'').trim();let membershipQuery=c.from('pm_company_members').select('company_id,role,pm_companies(id,name,verification_status)').eq('user_id',user.id).eq('status','active');if(requestedCompany)membershipQuery=membershipQuery.eq('company_id',requestedCompany)
 const {data:membership,error:mErr}=await membershipQuery.limit(1).maybeSingle();if(mErr||!membership)return NextResponse.json({ok:false,error:'No encontramos una empresa autorizada para esta cuenta.'},{status:403})
 const companyId=String(membership.company_id),companyName=String((membership as any).pm_companies?.name||'Tu empresa'),companyVerification=String((membership as any).pm_companies?.verification_status||'pending'),memberRole=String(membership.role||'viewer')
 const {data:subscription,error:subscriptionError}=await c.from('pm_company_subscriptions').select('plan,status,provider,current_period_end').eq('company_id',companyId).maybeSingle();if(subscriptionError)return NextResponse.json({ok:false,error:'No pudimos verificar el acceso a Nexo.'},{status:503})
 const activePlan=subscription?.status==='authorized'?String(subscription.plan||'gratis'):'gratis';const trialExpired=subscription?.provider==='trial'&&subscription?.current_period_end&&new Date(subscription.current_period_end).getTime()<=Date.now()
 if(trialExpired||subscription?.status!=='authorized'||!ELIGIBLE_NEXO.has(activePlan))return NextResponse.json({ok:false,code:'nexo_plan_required',error:'Nexo se habilita con el plan Selección IA.',plan:activePlan},{status:402})
 const [{data:companyJobs,error:jobsError},{data:teamRows,error:teamError}]=await Promise.all([c.from('pm_jobs').select('id,title,status,location_text').eq('company_id',companyId).order('created_at',{ascending:false}).limit(100),c.from('pm_company_members').select('user_id,role,status').eq('company_id',companyId).eq('status','active').limit(100)])
 if(jobsError)return NextResponse.json({ok:false,error:'No pudimos leer las búsquedas de esta empresa.'},{status:400});if(teamError)return NextResponse.json({ok:false,error:'No pudimos leer el equipo de esta empresa.'},{status:400})
 const requestedJob=String(body?.job_id||'').trim();let appQuery=c.from('pm_applications').select('id,candidate_user_id,resume_path,cover_letter,status,candidate_snapshot,created_at,pm_jobs!inner(id,title,company_id),pm_candidate_matches(score,reasons,missing_evidence,model_version)').eq('pm_jobs.company_id',companyId).order('created_at',{ascending:false}).limit(500);if(requestedJob)appQuery=appQuery.eq('job_id',requestedJob)
 const {data:apps,error:aErr}=await appQuery;if(aErr)return NextResponse.json({ok:false,error:'No pudimos leer las postulaciones de esta empresa.'},{status:400})
 const candidates:Candidate[]=(apps||[]).map((a:any)=>{const match=Array.isArray(a.pm_candidate_matches)?a.pm_candidate_matches[0]:a.pm_candidate_matches,snap=a.candidate_snapshot||{};return {application_id:String(a.id),user_id:String(a.candidate_user_id),name:String(snap.display_name||'Candidato/a'),score:match?.score==null?null:Number(match.score),role:String(a.pm_jobs?.title||''),status:String(a.status||'submitted'),availability:String(snap.availability||'No informada'),experience:String(snap.experience||'No informada'),city:String(snap.city||'No informada'),cover_letter:String(a.cover_letter||''),reasons:Array.isArray(match?.reasons)?match.reasons.map(String):[],missing:Array.isArray(match?.missing_evidence)?match.missing_evidence.map(String):[],resume_path:a.resume_path?String(a.resume_path):null}})
 const q=normalizeText(message),selectedIds=contextIds(body),selected=selectedIds.map(id=>candidates.find(x=>x.application_id===id)).filter(Boolean) as Candidate[],sorted=rank(candidates),jobs=companyJobs||[],activeJobs=jobs.filter((x:any)=>String(x.status)==='published'),team=teamRows||[]
 const wantsRoute=/(envia|enviar|manda|mandar|reenvia|reenviar|deriva|derivar|pasa|pasar).*(rrhh|recursos humanos|recruiter)/.test(q)
 if(wantsRoute){
  if(!['owner','admin','recruiter','hiring_manager'].includes(memberRole))return NextResponse.json({ok:false,error:'Tu rol no puede derivar candidatos.'},{status:403})
  const count=requestedCount(q);const base=selected.length?selected:usable(sorted);const list=base.slice(0,count||base.length||5)
  if(!list.length)return NextResponse.json({ok:true,answer:'Todavía no hay candidatos disponibles para derivar.',selected_candidate_ids:[],intent:'route_empty'})
  const priorities=['recruiter','hiring_manager','admin'];let recipient:any=null;for(const role of priorities){recipient=team.find((x:any)=>String(x.user_id)!==user.id&&String(x.role)===role);if(recipient)break}
  if(!recipient)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:'Todavía no creaste o asignaste ningún rol de Recursos Humanos o responsable de contratación. Agregá a esa persona desde Equipo y permisos y después decime de nuevo que le envíe la selección.',selected_candidate_ids:list.map(x=>x.application_id),intent:'route_missing_recipient'})
  const rows=list.map(x=>({company_id:companyId,application_id:x.application_id,sender_user_id:user.id,recipient_user_id:recipient.user_id,recipient_role:recipient.role,note:'Derivado desde Nexo',status:'pending'}));const {error}=await c.from('pm_candidate_handoffs').upsert(rows,{onConflict:'application_id,recipient_user_id,status',ignoreDuplicates:true});if(error)return NextResponse.json({ok:false,error:'No pudimos crear la derivación interna.'},{status:400})
  return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`Listo. Envié ${list.length} postulaciones al responsable de ${recipient.role}: ${list.map(x=>x.name).join(', ')}. Quedaron derivadas dentro de la empresa y con trazabilidad.`,selected_candidate_ids:list.map(x=>x.application_id),intent:'route',delivery:{destination:'Equipo interno',recipient:String(recipient.role),count:list.length,status:'created'}})
 }
 if(!candidates.length)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`Todavía no hay postulaciones para revisar. ${activeJobs.length?`Tenés ${activeJobs.length} búsquedas publicadas.`:'Tampoco hay búsquedas publicadas ahora.'}`,selected_candidate_ids:[]})
 if(/(mejor(?:es)?|top|ranking|conviene|recomenda).*(curr|cv|candidat|postul|perfil)|(?:curr|cv|candidat|postul|perfil).*(mejor(?:es)?|top|ranking|conviene|recomenda)/.test(q)){const n=requestedCount(q)||5,list=usable(sorted).slice(0,n),withScores=list.some(x=>x.score!=null);return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`${withScores?'Los ordené priorizando el match explicable con la búsqueda y usando la etapa sólo como desempate.':'Todavía faltan scores de match para algunos perfiles; los ordené con la evidencia disponible sin inventar datos.'}\n${list.map((x,i)=>`${i+1}. ${candidateLabel(x)}. Disponibilidad: ${x.availability}. Experiencia: ${x.experience}.`).join('\n')}`,selected_candidate_ids:list.map(x=>x.application_id),intent:'shortlist'})}
 if(/(cuantos|cantidad|total).*(candidat|cv|postul)|(?:candidat|cv|postul).*(cuantos|cantidad|total)|embudo|pipeline/.test(q)){const counts=candidates.reduce((acc:Record<string,number>,x)=>{acc[x.status]=(acc[x.status]||0)+1;return acc},{});return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`Recibiste ${candidates.length} postulaciones en el contexto actual. ${Object.entries(counts).map(([k,v])=>`${k}: ${v}`).join(' · ')}.`,selected_candidate_ids:[]})}
 if(/(mi empresa|perfil de empresa|empresa actual|verificacion|verificada|mi cuenta)/.test(q))return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`Estás trabajando sobre ${companyName}. Verificación: ${companyVerification}. Plan activo: Selección IA. Hay ${activeJobs.length} búsquedas publicadas, ${candidates.length} postulaciones y ${team.length} integrantes activos.`,selected_candidate_ids:[]})
 if(/(busquedas|ofertas|avisos|puestos|publicaciones)/.test(q)&&!/(candidat|cv|postul)/.test(q)){const list=jobs.slice(0,12);return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:list.length?`${companyName} tiene ${activeJobs.length} búsquedas publicadas y ${jobs.length} en total. ${list.map((x:any)=>`${x.title} (${x.status}${x.location_text?` · ${x.location_text}`:''})`).join(' · ')}`:'Todavía no hay búsquedas creadas.',selected_candidate_ids:[]})}
 if(/(equipo|usuarios|miembros|permisos|rrhh)/.test(q)){const byRole=team.reduce((acc:Record<string,number>,x:any)=>{const role=String(x.role||'viewer');acc[role]=(acc[role]||0)+1;return acc},{});return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`El equipo tiene ${team.length} integrantes activos. ${Object.entries(byRole).map(([role,count])=>`${role}: ${count}`).join(' · ')||'No hay roles activos.'}`,selected_candidate_ids:[]})}
 const named=candidates.filter(x=>q.includes(normalizeText(x.name.split(' ')[0]))).slice(0,8)
 if(/compara|comparame|diferencia/.test(q)&&named.length>=2)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:named.map(x=>`${candidateLabel(x)}. Disponibilidad: ${x.availability}. Experiencia: ${x.experience}. ${x.reasons.length?`A favor: ${x.reasons.slice(0,3).join(', ')}.`:''} ${x.missing.length?`Falta validar: ${x.missing.slice(0,3).join(', ')}.`:''}`).join('\n'),selected_candidate_ids:named.map(x=>x.application_id),intent:'compare'})
 if(/disponibil|horario|turno|sabado|domingo/.test(q)){const list=named.length?named:(selected.length?selected:usable(sorted).slice(0,12));return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:list.map(x=>`${x.name}: ${x.availability}. Zona: ${x.city}.`).join('\n'),selected_candidate_ids:list.map(x=>x.application_id),intent:'availability'})}
 if(/preguntas?.*(entrevista)|entrevista.*preguntas?/.test(q)){const list=selected.length?selected.slice(0,10):(named.length?named:usable(sorted).slice(0,5));return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`Para ${list.map(x=>x.name).join(', ')} usaría: 1) una situación similar al trabajo que resolvió; 2) disponibilidad real para el horario; 3) qué parte del puesto domina y cuál debería aprender; 4) una pregunta específica por cada dato que falte validar.`,selected_candidate_ids:list.map(x=>x.application_id),intent:'interview'})}
 if(/(plan|suscripcion|nexo|pago)/.test(q)&&!/(candidat|cv|postul)/.test(q))return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:`El plan activo de ${companyName} es Selección IA y Nexo está habilitado.`,selected_candidate_ids:[]})
 const safeCandidates=sorted.slice(0,50).map(x=>({id:x.application_id,name:x.name,match:x.score,puesto:x.role,estado:x.status,disponibilidad:x.availability,experiencia:x.experience,zona:x.city,carta:x.cover_letter.slice(0,500),razones:x.reasons,falta_validar:x.missing})),safeAccount={empresa:{nombre:companyName,verificacion:companyVerification,plan:'Selección IA'},busquedas:jobs.slice(0,30).map((x:any)=>({titulo:x.title,estado:x.status,ubicacion:x.location_text||''})),equipo:team.map((x:any)=>({rol:String(x.role||'viewer')})),postulaciones:safeCandidates,contexto_seleccionado:selected.map(x=>x.application_id)}
 const {data:quota,error:quotaError}=await c.rpc('pm_consume_nexo_quota',{p_company_id:companyId});if(quotaError||Number(quota)<0)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:'Llegaste al límite de consultas abiertas con IA por esta hora. Los conteos, rankings, comparaciones, disponibilidad, entrevistas y derivaciones siguen funcionando.',intent:'ai_quota'})
 let key=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;try{if(!key)key=await getVercelOidcToken()}catch{};if(!key)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:'Puedo responder sobre búsquedas, postulaciones, equipo y plan; también puedo ordenar candidatos, comparar perfiles, preparar entrevistas y derivar una selección a RR. HH.',selected_candidate_ids:selectedIds})
 const system=`Sos Nexo, guía agéntica de selección de Postulá Mejor para ${companyName}. Respondé en español rioplatense, claro y breve. Sólo usá el contexto autorizado de esta empresa. Nunca inventes CV, experiencia, referencias, identidad ni scores. Nunca uses edad, género, foto, salud, religión, origen u otros datos sensibles para evaluar. El match es orientativo y explicable y la decisión final es humana. Si falta un dato, decí que falta validar. Conservá como referencia los ids en contexto_seleccionado cuando el usuario diga esos, esos últimos o los anteriores. Para acciones que modifican datos, indicá que debe usar una orden soportada por Nexo; no simules haber ejecutado una acción si no fue ejecutada por el backend. Máximo 220 palabras salvo que pidan detalle.`
 let last='';for(const model of MODELS){try{const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'system',content:`Contexto autorizado: ${JSON.stringify(safeAccount)}`},{role:'user',content:message}],temperature:.1,max_tokens:520}),cache:'no-store'});const data=await r.json().catch(()=>({}));if(r.ok){const answer=clean(String(data?.choices?.[0]?.message?.content||''));if(answer)return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer,model,selected_candidate_ids:selectedIds})}last=String(data?.error?.message||data?.error||`AI ${r.status}`)}catch(e){last=e instanceof Error?e.message:String(e)}}
 return NextResponse.json({ok:true,tenant:companyId,company:companyName,answer:'No pude completar esa consulta con IA ahora. Igual siguen disponibles conteos, ranking, comparación, disponibilidad, entrevistas y derivación interna.',selected_candidate_ids:selectedIds,note:last||undefined})
}
