import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
import {getVercelOidcToken} from '@vercel/oidc'

const SUPABASE_URL='https://pejkycdttogpmmdntzuq.supabase.co'
const SUPABASE_KEY='sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I'
const GATEWAY='https://ai-gateway.vercel.sh/v1/chat/completions'
const MODELS=['openai/gpt-5.4-nano','google/gemini-3.5-flash-lite','openai/gpt-5.4']
const ELIGIBLE_NEXO=new Set(['seleccion'])
type Candidate={application_id:string;user_id:string;name:string;score:number|null;role:string;status:string;availability:string;experience:string;city:string;cover_letter:string;reasons:string[];missing:string[];resume_path:string|null}
function db(req:NextRequest){const auth=req.headers.get('authorization')||'';return createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
function clean(s:string){return s.replace(/\*\*/g,'').replace(/\*/g,'').replace(/#{1,6}\s*/g,'').trim()}
function normalizeText(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function requestedCount(q:string){const digit=q.match(/\b(\d{1,3})\b/);if(digit)return Math.max(1,Math.min(50,Number(digit[1])));const words:Record<string,number>={uno:1,una:1,dos:2,tres:3,cuatro:4,cinco:5,seis:6,siete:7,ocho:8,nueve:9,diez:10,once:11,doce:12,trece:13,catorce:14,quince:15,dieciseis:16,diecisiete:17,dieciocho:18,diecinueve:19,veinte:20,treinta:30,cuarenta:40,cincuenta:50};for(const [w,n] of Object.entries(words))if(new RegExp(`\\b${w}\\b`,'i').test(q))return n;return null}
function rank(list:Candidate[]){const stage:Record<string,number>={shortlist:4,interview:3,viewed:2,submitted:1};return [...list].sort((a,b)=>{const as=a.score==null?-1:a.score,bs=b.score==null?-1:b.score;if(bs!==as)return bs-as;return (stage[b.status]||0)-(stage[a.status]||0)})}
function candidateLabel(c:Candidate){return `${c.name} · ${c.role||'Perfil'}${c.score!=null?` · ${c.score}% de ajuste`:''}`}
function contextIds(body:any){return Array.isArray(body?.context_candidate_ids)?body.context_candidate_ids.map(String).slice(0,50):[]}
function usable(list:Candidate[]){return list.filter(x=>!['rejected','withdrawn','hired'].includes(x.status))}
const STAGES:Record<string,string>={submitted:'Recibidos',viewed:'Revisados',shortlist:'Preseleccionados',interview:'En entrevista',hired:'Contratados',rejected:'No seleccionados',withdrawn:'Retirados'}
const JOB_STATES:Record<string,string>={published:'Publicada',draft:'Borrador',paused:'Pausada',closed:'Cerrada',archived:'Archivada'}
const ROLES:Record<string,string>={owner:'Propietario',admin:'Administrador',recruiter:'RR. HH.',hiring_manager:'Responsable de contratación',viewer:'Consulta'}
function stageLabel(v:string){return STAGES[v]||'En proceso'}
function jobStateLabel(v:string){return JOB_STATES[v]||'En proceso'}
function roleLabel(v:string){return ROLES[v]||'Equipo'}
function verificationLabel(v:string){return v==='verified'?'Verificada':v==='basic'?'Validación básica':'Pendiente de validación'}
function publicAnswer(value:string){
 return clean(value)
  .replace(/\b[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}\b/gi,'')
  .replace(/\s*[—–-]?\s*(?:id|uuid)\s*[:#-]?\s*(?=[,.;)\n]|$)/gi,'')
  .replace(/\s*\((?:estado|status)\s*:[^)]+\)/gi,'')
  .replace(/\b(submitted|viewed|shortlist|interview|hired|rejected|withdrawn)\b/gi,m=>stageLabel(m.toLowerCase()))
  .replace(/\bmatch orientativo\b/gi,'ajuste')
  .replace(/\bmatch\b/gi,'ajuste')
  .replace(/Puesto:\s*/gi,'')
  .replace(/[ \t]{2,}/g,' ')
  .replace(/\s+([,.;])/g,'$1')
  .trim()
}
function answerJson(payload:Record<string,any>,init?:ResponseInit){return NextResponse.json(payload.answer?{...payload,answer:publicAnswer(String(payload.answer))}:payload,init)}

export async function POST(req:NextRequest){
 if(!(req.headers.get('content-type')||'').includes('application/json'))return NextResponse.json({ok:false,error:'Formato inválido.'},{status:415})
 const c=db(req);const {data:{user},error:authError}=await c.auth.getUser();if(authError||!user)return NextResponse.json({ok:false,error:'Iniciá sesión como integrante de una empresa.'},{status:401})
 const body=await req.json().catch(()=>({})),message=String(body?.message||'').trim().slice(0,1600);if(!message)return NextResponse.json({ok:false,error:'Escribí o dictá una consulta.'},{status:400})
 const requestedCompany=String(body?.company_id||'').trim();let membershipQuery=c.from('pm_company_members').select('company_id,role,pm_companies(id,name,verification_status)').eq('user_id',user.id).eq('status','active');if(requestedCompany)membershipQuery=membershipQuery.eq('company_id',requestedCompany)
 const {data:membership,error:mErr}=await membershipQuery.limit(1).maybeSingle();if(mErr||!membership)return NextResponse.json({ok:false,error:'No encontramos una empresa autorizada para esta cuenta.'},{status:403})
 const companyId=String(membership.company_id),companyName=String((membership as any).pm_companies?.name||'Tu empresa'),companyVerification=String((membership as any).pm_companies?.verification_status||'pending'),memberRole=String(membership.role||'viewer')
 const {data:subscription,error:subscriptionError}=await c.from('pm_company_subscriptions').select('plan,status,provider,current_period_end').eq('company_id',companyId).maybeSingle();if(subscriptionError)return NextResponse.json({ok:false,error:'No pudimos verificar el acceso a Nexo.'},{status:503})
 const activePlan=subscription?.status==='authorized'?String(subscription.plan||'gratis'):'gratis';const trialExpired=subscription?.provider==='trial'&&subscription?.current_period_end&&new Date(subscription.current_period_end).getTime()<=Date.now()
 if(trialExpired||subscription?.status!=='authorized'||!ELIGIBLE_NEXO.has(activePlan))return NextResponse.json({ok:false,code:'nexo_plan_required',error:'Nexo se habilita con el plan Selección IA.',plan:activePlan},{status:402})
 const [{data:companyJobs,error:jobsError},{data:teamRows,error:teamError}]=await Promise.all([c.from('pm_jobs').select('id,title,status,location_text').eq('company_id',companyId).order('created_at',{ascending:false}).limit(100),c.from('pm_company_members').select('user_id,role,status').eq('company_id',companyId).eq('status','active').limit(100)])
 if(jobsError)return NextResponse.json({ok:false,error:'No pudimos leer las búsquedas de esta empresa.'},{status:400});if(teamError)return NextResponse.json({ok:false,error:'No pudimos leer el equipo de esta empresa.'},{status:400})
 const requestedJob=String(body?.job_id||'').trim();let appQuery=c.from('pm_applications').select('id,candidate_user_id,resume_path,cover_letter,status,candidate_snapshot,created_at,pm_jobs!inner(id,title,company_id),pm_candidate_matches(score,reasons,missing_evidence,model_version)').eq('pm_jobs.company_id',companyId).order('created_at',{ascending:false}).limit(500);if(requestedJob)appQuery=appQuery.eq('job_id',requestedJob)
 const {data:apps,error:aErr}=await appQuery;if(aErr)return NextResponse.json({ok:false,error:'No pudimos leer las postulaciones de esta empresa.'},{status:400})
 const candidates:Candidate[]=(apps||[]).map((a:any)=>{const match=Array.isArray(a.pm_candidate_matches)?a.pm_candidate_matches[0]:a.pm_candidate_matches,snap=a.candidate_snapshot||{};return {application_id:String(a.id),user_id:String(a.candidate_user_id),name:String(snap.display_name||'Candidato/a'),score:match?.score==null?null:Number(match.score),role:String(a.pm_jobs?.title||''),status:String(a.status||'submitted'),availability:String(snap.availability||'No informada'),experience:String(snap.experience||'No informada'),city:String(snap.city||'No informada'),cover_letter:String(a.cover_letter||''),reasons:Array.isArray(match?.reasons)?match.reasons.map(String):[],missing:Array.isArray(match?.missing_evidence)?match.missing_evidence.map(String):[],resume_path:a.resume_path?String(a.resume_path):null}})
 const q=normalizeText(message),selectedIds=contextIds(body),selected=selectedIds.map(id=>candidates.find(x=>x.application_id===id)).filter(Boolean) as Candidate[],sorted=rank(candidates),jobs=companyJobs||[],activeJobs=jobs.filter((x:any)=>String(x.status)==='published'),team=teamRows||[]
 const wantsRoute=/(envia|enviar|manda|mandar|reenvia|reenviar|deriva|derivar|pasa|pasar).*(rrhh|recursos humanos|recruiter)/.test(q)
 if(wantsRoute){
  if(!['owner','admin','recruiter','hiring_manager'].includes(memberRole))return NextResponse.json({ok:false,error:'Tu rol no puede derivar candidatos.'},{status:403})
  const count=requestedCount(q);const base=selected.length?selected:usable(sorted);const list=base.slice(0,count||base.length||5)
  if(!list.length)return answerJson({ok:true,answer:'Todavía no hay candidatos disponibles para derivar.',selected_candidate_ids:[],intent:'route_empty'})
  const priorities=['recruiter','hiring_manager','admin'];let recipient:any=null;for(const role of priorities){recipient=team.find((x:any)=>String(x.user_id)!==user.id&&String(x.role)===role);if(recipient)break}
  if(!recipient)return answerJson({ok:true,tenant:companyId,company:companyName,answer:'Todavía no hay una persona asignada a RR. HH. o contratación. Podés agregarla desde Equipo y permisos.',selected_candidate_ids:list.map(x=>x.application_id),intent:'route_missing_recipient'})
  const rows=list.map(x=>({company_id:companyId,application_id:x.application_id,sender_user_id:user.id,recipient_user_id:recipient.user_id,recipient_role:recipient.role,note:'Derivado desde Nexo',status:'pending'}));const {error}=await c.from('pm_candidate_handoffs').upsert(rows,{onConflict:'application_id,recipient_user_id,status',ignoreDuplicates:true});if(error)return NextResponse.json({ok:false,error:'No pudimos crear la derivación interna.'},{status:400})
  const recipientName=roleLabel(String(recipient.role));return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Listo. Envié ${list.length} postulaciones a ${recipientName}: ${list.map(x=>x.name).join(', ')}.`,selected_candidate_ids:list.map(x=>x.application_id),intent:'route',delivery:{destination:'Equipo interno',recipient:recipientName,count:list.length,status:'created'}})
 }
 if(!candidates.length)return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Todavía no hay postulaciones para revisar.${activeJobs.length?` Tenés ${activeJobs.length} búsquedas publicadas.`:''}`,selected_candidate_ids:[]})
 const wantsBest=/(cual|quien).*(mejor)|\bmejor\b|\bconviene\b/.test(q)
 if(wantsBest&&selected.length){const list=rank(selected),best=list[0];const reason=best.reasons[0]?` ${best.reasons[0]}.`:'';const missing=best.missing[0]?` Falta validar ${best.missing[0].toLowerCase()}.`:'';return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Hoy me quedo con ${candidateLabel(best)}.${reason}${missing}`,selected_candidate_ids:list.map(x=>x.application_id),intent:'best'})}
 if(/(mejor(?:es)?|top|ranking|conviene|recomenda).*(curr|cv|candidat|postul|perfil)|(?:curr|cv|candidat|postul|perfil).*(mejor(?:es)?|top|ranking|conviene|recomenda)/.test(q)){const n=requestedCount(q)||5,list=usable(sorted).slice(0,n);return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Los que mejor encajan hoy son:\n${list.map((x,i)=>`${i+1}. ${candidateLabel(x)}`).join('\n')}\nDecime cuál querés revisar.`,selected_candidate_ids:list.map(x=>x.application_id),intent:'shortlist'})}
 if(/(cuantos|cantidad|total).*(candidat|cv|postul)|(?:candidat|cv|postul).*(cuantos|cantidad|total)/.test(q)&&!/embudo|pipeline|etapas?/.test(q))return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Tenés ${candidates.length} postulaciones en total.`,selected_candidate_ids:[]})
 if(/embudo|pipeline|etapas?/.test(q)){const counts=candidates.reduce((acc:Record<string,number>,x)=>{acc[x.status]=(acc[x.status]||0)+1;return acc},{});return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Tenés ${candidates.length} postulaciones. ${Object.entries(counts).map(([k,v])=>`${stageLabel(k)}: ${v}`).join(' · ')}.`,selected_candidate_ids:[]})}
 if(/(mi empresa|perfil de empresa|empresa actual|verificacion|verificada|mi cuenta)/.test(q))return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Estás trabajando sobre ${companyName}. ${verificationLabel(companyVerification)}. Tenés ${activeJobs.length} búsquedas publicadas y ${candidates.length} postulaciones.`,selected_candidate_ids:[]})
 if(/(busquedas|ofertas|avisos|puestos|publicaciones)/.test(q)&&!/(candidat|cv|postul)/.test(q)){const list=jobs.slice(0,8);return answerJson({ok:true,tenant:companyId,company:companyName,answer:list.length?`${activeJobs.length} búsquedas publicadas. ${list.map((x:any)=>`${x.title}${x.location_text?` · ${x.location_text}`:''}${/estado|status|borrador|pausad|cerrad/.test(q)?` · ${jobStateLabel(String(x.status))}`:''}`).join(' · ')}`:'Todavía no hay búsquedas creadas.',selected_candidate_ids:[]})}
 if(/(equipo|usuarios|miembros|permisos|rrhh)/.test(q)){const byRole=team.reduce((acc:Record<string,number>,x:any)=>{const role=roleLabel(String(x.role||'viewer'));acc[role]=(acc[role]||0)+1;return acc},{});return answerJson({ok:true,tenant:companyId,company:companyName,answer:`El equipo tiene ${team.length} integrantes. ${Object.entries(byRole).map(([role,count])=>`${role}: ${count}`).join(' · ')}`,selected_candidate_ids:[]})}
 const named=candidates.filter(x=>q.includes(normalizeText(x.name.split(' ')[0]))).slice(0,8)
 if(/compara|comparame|diferencia/.test(q)&&named.length>=2)return answerJson({ok:true,tenant:companyId,company:companyName,answer:named.map(x=>`${candidateLabel(x)}.${x.reasons[0]?` A favor: ${x.reasons[0]}.`:''}${x.missing[0]?` Falta validar: ${x.missing[0]}.`:''}`).join('\n'),selected_candidate_ids:named.map(x=>x.application_id),intent:'compare'})
 if(/disponibil|horario|turno|sabado|domingo/.test(q)){const list=named.length?named:(selected.length?selected:usable(sorted).slice(0,8));return answerJson({ok:true,tenant:companyId,company:companyName,answer:list.map(x=>`${x.name}: ${x.availability}${x.city&&x.city!=='No informada'?` · ${x.city}`:''}`).join('\n'),selected_candidate_ids:list.map(x=>x.application_id),intent:'availability'})}
 if(/preguntas?.*(entrevista)|entrevista.*preguntas?/.test(q)){const list=selected.length?selected.slice(0,6):(named.length?named:usable(sorted).slice(0,4));return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Para ${list.map(x=>x.name).join(', ')} preguntaría por experiencia similar, disponibilidad real, fortalezas para el puesto y los datos que todavía falten validar.`,selected_candidate_ids:list.map(x=>x.application_id),intent:'interview'})}
 if(/(plan|suscripcion|nexo|pago)/.test(q)&&!/(candidat|cv|postul)/.test(q))return answerJson({ok:true,tenant:companyId,company:companyName,answer:`Tenés Selección IA activa y Nexo habilitado.`,selected_candidate_ids:[]})
 const safeCandidates=sorted.slice(0,50).map(x=>({nombre:x.name,ajuste:x.score,puesto:x.role,disponibilidad:x.availability,experiencia:x.experience,zona:x.city,carta:x.cover_letter.slice(0,500),razones:x.reasons,falta_validar:x.missing})),safeAccount={empresa:{nombre:companyName,verificacion:verificationLabel(companyVerification),plan:'Selección IA'},busquedas:jobs.slice(0,30).map((x:any)=>({titulo:x.title,ubicacion:x.location_text||''})),equipo:team.map((x:any)=>({rol:roleLabel(String(x.role||'viewer'))})),postulaciones:safeCandidates,seleccion_actual:selected.map(x=>({nombre:x.name,puesto:x.role,ajuste:x.score}))}
 const {data:quota,error:quotaError}=await c.rpc('pm_consume_nexo_quota',{p_company_id:companyId});if(quotaError||Number(quota)<0)return answerJson({ok:true,tenant:companyId,company:companyName,answer:'Llegaste al límite de consultas abiertas con IA por esta hora. Los conteos, rankings, comparaciones y derivaciones siguen funcionando.',intent:'ai_quota'})
 let key=process.env.AI_GATEWAY_API_KEY||process.env.VERCEL_OIDC_TOKEN;try{if(!key)key=await getVercelOidcToken()}catch{};if(!key)return answerJson({ok:true,tenant:companyId,company:companyName,answer:'Puedo revisar postulantes, comparar perfiles, preparar rankings, entrevistas y derivaciones.',selected_candidate_ids:selectedIds})
 const system=`Sos Nexo, asistente de selección de Postulá Mejor para ${companyName}. Respondé en español rioplatense, natural, claro y muy breve: por defecto 2 a 5 líneas y menos de 90 palabras. Priorizá nombre, puesto y el dato útil para decidir. No muestres jamás IDs, UUIDs, códigos, nombres de tablas, campos internos, estados técnicos, roles técnicos ni etiquetas del backend. No digas submitted, viewed, shortlist, interview, hired, rejected o withdrawn salvo que el usuario pida explícitamente las etapas, y aun así traducilas a español natural. No uses rótulos como 'Puesto:', 'Estado:' o 'Match orientativo:'; escribí por ejemplo 'Vanina · Reservas · 30% de ajuste'. No repitas datos ni expliques el criterio salvo que te lo pidan. Sólo usá el contexto autorizado de esta empresa. Nunca inventes CV, experiencia, referencias, identidad ni puntajes. Nunca uses edad, género, foto, salud, religión, origen u otros datos sensibles para evaluar. Si falta un dato importante, decí brevemente que falta validar. La decisión final es humana, pero no hace falta repetir esa aclaración en cada respuesta. Para acciones que modifican datos, no simules haber ejecutado una acción si no fue ejecutada por el backend.`
 let last='';for(const model of MODELS){try{const r=await fetch(GATEWAY,{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({model,messages:[{role:'system',content:system},{role:'system',content:`Contexto autorizado: ${JSON.stringify(safeAccount)}`},{role:'user',content:message}],temperature:.1,max_tokens:240}),cache:'no-store'});const data=await r.json().catch(()=>({}));if(r.ok){const answer=publicAnswer(String(data?.choices?.[0]?.message?.content||''));if(answer)return answerJson({ok:true,tenant:companyId,company:companyName,answer,model,selected_candidate_ids:selectedIds})}last=String(data?.error?.message||data?.error||`AI ${r.status}`)}catch(e){last=e instanceof Error?e.message:String(e)}}
 return answerJson({ok:true,tenant:companyId,company:companyName,answer:'No pude completar esa consulta con IA ahora. Igual podés pedirme conteos, rankings, comparaciones o derivaciones.',selected_candidate_ids:selectedIds,note:last||undefined})
}
