'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {cvAuthClient} from '../../cv-ia/cvAuth'

type Plan='impulso'|'seleccion'
const INFO={impulso:{label:'Impulso',price:'$18.900'},seleccion:{label:'Selección IA',price:'$34.900'}} as const
export default function Page(){
 const [plan,setPlan]=useState<Plan>('seleccion'),[auth,setAuth]=useState<boolean|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
 useEffect(()=>{const p=new URLSearchParams(location.search).get('plan');if(p==='impulso'||p==='seleccion')setPlan(p);void cvAuthClient().auth.getSession().then(({data})=>setAuth(Boolean(data.session)))},[])
 async function pay(){setBusy(true);setError('');try{const {data}=await cvAuthClient().auth.getSession();const session=data.session;if(!session){location.assign(`/acceso?rol=empresa&next=${encodeURIComponent(`/empresas/continuar?plan=${plan}`)}`);return}const r=await fetch('/api/postula/billing/checkout',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,'Content-Type':'application/json'},body:JSON.stringify({plan,mode:'payment'})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok||!d?.init_point)throw new Error(d?.error||'No pudimos abrir Mercado Pago.');location.assign(String(d.init_point))}catch(e){setError(e instanceof Error?e.message:'No pudimos abrir Mercado Pago.')}finally{setBusy(false)}}
 const info=INFO[plan]
 return <main style={{minHeight:'100vh',display:'grid',placeItems:'center',padding:24,background:'#f5f7f6',color:'#111821'}}><section style={{width:'min(560px,100%)',background:'#fff',border:'1px solid #dde3e2',borderRadius:24,padding:28,boxShadow:'0 20px 60px rgba(17,24,33,.08)'}}><span style={{fontSize:11,fontWeight:900,letterSpacing:'.12em'}}>POSTULÁ MEJOR EMPRESAS</span><h1 style={{fontSize:34,margin:'12px 0 8px'}}>Continuar con {info.label}</h1><p style={{lineHeight:1.55,color:'#5f6d76'}}>Tu prueba de 30 días no genera ningún cobro automático. Sólo si elegís continuar desde acá abrimos Mercado Pago.</p><div style={{margin:'22px 0',padding:18,borderRadius:18,background:'#f4f7f4'}}><small>VALOR DESPUÉS DE LA PRUEBA</small><strong style={{display:'block',fontSize:28,marginTop:6}}>{info.price} / mes</strong></div>{auth===false?<Link href={`/acceso?rol=empresa&next=${encodeURIComponent(`/empresas/continuar?plan=${plan}`)}`} style={{display:'block',padding:15,borderRadius:14,textAlign:'center',background:'#111821',color:'#fff',fontWeight:900,textDecoration:'none'}}>Ingresar para continuar</Link>:<button type="button" disabled={busy||auth===null} onClick={()=>void pay()} style={{width:'100%',padding:15,border:0,borderRadius:14,background:'#111821',color:'#fff',fontWeight:900,cursor:'pointer'}}>{busy?'Abriendo Mercado Pago…':'Continuar y pagar con Mercado Pago'}</button>}{error&&<p role="alert" style={{color:'#a12d35',fontWeight:700}}>{error}</p>}<Link href="/empresas/panel" style={{display:'block',marginTop:16,textAlign:'center',color:'#43515a'}}>Volver al panel</Link></section></main>
}
