'use client'

import { useMemo, useState } from 'react'
import styles from './vocational.module.css'
import { trackCvEvent } from '../cv-ia/cvAuth'

type Area='R'|'I'|'A'|'S'|'E'|'C'
type Question={area:Area,text:string}
const questions:Question[]=[
 {area:'R',text:'Disfrutaría armar, reparar o mejorar algo con mis manos.'},{area:'I',text:'Me entusiasma investigar por qué ocurre un problema y encontrar una explicación.'},{area:'A',text:'Me gustaría crear piezas visuales, textos, música, videos o ideas originales.'},{area:'S',text:'Me hace bien acompañar a alguien para que aprenda, mejore o resuelva una dificultad.'},{area:'E',text:'Me atrae presentar una idea y lograr que otras personas se sumen.'},{area:'C',text:'Me siento cómodo ordenando información, registros, fechas o tareas.'},
 {area:'R',text:'Preferiría un trabajo donde pueda moverme, usar herramientas o trabajar sobre cosas concretas.'},{area:'I',text:'Me gusta comparar datos, detectar patrones y llegar a una conclusión.'},{area:'A',text:'Me importa que mi trabajo tenga espacio para expresar una mirada personal.'},{area:'S',text:'Podría disfrutar un trabajo con mucha escucha, atención o trato humano.'},{area:'E',text:'Me motiva negociar, vender, coordinar o impulsar un proyecto.'},{area:'C',text:'Me resulta satisfactorio que un proceso quede prolijo, completo y sin errores.'},
 {area:'R',text:'Me interesaría aprender a operar equipos, máquinas, sistemas técnicos o instalaciones.'},{area:'I',text:'Podría pasar bastante tiempo aprendiendo un tema complejo que me genera curiosidad.'},{area:'A',text:'Me divierte imaginar distintas formas de comunicar la misma idea.'},{area:'S',text:'Me gustaría que una parte importante de mi trabajo ayude directamente a otras personas.'},{area:'E',text:'Me siento cómodo tomando iniciativa y haciendo que las cosas avancen.'},{area:'C',text:'Prefiero tener criterios, pasos o información clara para organizar el trabajo.'},
 {area:'R',text:'Me atraen tareas donde al final del día puedo ver un resultado físico o concreto.'},{area:'I',text:'Ante un problema, primero quiero entender bien la causa antes de actuar.'},{area:'A',text:'Me interesan el diseño, la estética, la escritura, el contenido o la creatividad aplicada.'},{area:'S',text:'Tengo paciencia para explicar algo más de una vez si la otra persona lo necesita.'},{area:'E',text:'Me entusiasma asumir objetivos, competir sanamente o buscar oportunidades.'},{area:'C',text:'Me gusta trabajar con listas, planillas, sistemas, documentación o seguimiento.'},
 {area:'R',text:'No me molestaría un trabajo que combine oficina con actividad práctica o terreno.'},{area:'I',text:'Me interesa aprender herramientas para analizar información o resolver problemas difíciles.'},{area:'A',text:'Me gustaría trabajar en proyectos donde no exista una sola respuesta correcta.'},{area:'S',text:'Valoro mucho los trabajos donde se construyen vínculos y confianza.'},{area:'E',text:'Podría verme liderando una tarea, un equipo pequeño o una iniciativa.'},{area:'C',text:'Soy de notar cuando falta un dato, algo no cierra o un proceso quedó incompleto.'},
]
const labels=[{v:1,t:'Nada conmigo'},{v:2,t:'Poco'},{v:3,t:'No estoy seguro/a'},{v:4,t:'Bastante'},{v:5,t:'Mucho conmigo'}]
const info:Record<Area,{name:string,short:string,description:string,areas:string[],roles:string[]}>={
 R:{name:'Realista',short:'Hacer y resolver',description:'Te atraen las tareas prácticas, concretas y técnicas, donde podés intervenir sobre objetos, equipos, espacios o procesos reales.',areas:['Técnica y mantenimiento','Logística y operaciones','Producción','Oficios y campo'],roles:['Auxiliar de logística','Operador/a','Técnico/a junior','Mantenimiento','Depósito y expedición']},
 I:{name:'Investigador',short:'Entender y analizar',description:'Te moviliza comprender cómo funcionan las cosas, investigar, comparar información y resolver problemas con lógica.',areas:['Datos y análisis','Tecnología','Ciencias','Calidad e investigación'],roles:['Analista junior','Soporte técnico','Control de calidad','Asistente de investigación','Data entry analítico']},
 A:{name:'Artístico',short:'Crear y comunicar',description:'Buscás espacio para crear, comunicar, diseñar o encontrar soluciones originales sin seguir siempre una fórmula fija.',areas:['Diseño y contenido','Comunicación','Marketing creativo','Producción audiovisual'],roles:['Asistente de contenido','Diseño junior','Community manager junior','Redacción','Producción audiovisual']},
 S:{name:'Social',short:'Ayudar y conectar',description:'Te energiza trabajar con personas, escuchar, enseñar, orientar, cuidar o resolver necesidades de otros.',areas:['Atención y servicio','Educación','Salud y bienestar','Recursos humanos'],roles:['Atención al cliente','Recepción','Asistente educativo','Soporte al usuario','Asistente de RR.HH.']},
 E:{name:'Emprendedor',short:'Impulsar y convencer',description:'Te atrae tomar iniciativa, persuadir, negociar, vender, coordinar y convertir una idea u objetivo en movimiento.',areas:['Ventas','Comercial','Emprendimientos','Gestión y liderazgo'],roles:['Asesor/a comercial','Ventas','Ejecutivo/a junior','Promotor/a','Coordinación junior']},
 C:{name:'Convencional',short:'Ordenar y sostener',description:'Te sentís cómodo organizando información, siguiendo procesos, controlando detalles y dando estructura al trabajo.',areas:['Administración','Finanzas operativas','Back office','Control y documentación'],roles:['Administrativo/a','Back office','Asistente contable','Facturación','Carga y control de datos']},
}

export default function VocationalTestClient(){
 const [started,setStarted]=useState(false),[index,setIndex]=useState(0),[answers,setAnswers]=useState<number[]>(Array(questions.length).fill(0)),[done,setDone]=useState(false)
 const progress=Math.round(((done?questions.length:index)/questions.length)*100)
 const result=useMemo(()=>{const totals:Record<Area,number>={R:0,I:0,A:0,S:0,E:0,C:0};answers.forEach((v,i)=>{if(v)totals[questions[i].area]+=v});return (Object.keys(totals) as Area[]).map(area=>({area,score:totals[area]})).sort((a,b)=>b.score-a.score)},[answers])
 function beginTest(){setStarted(true);void trackCvEvent('vocational_test_started',{source:'direct'},'/test-vocacional')}
 function answer(value:number){const next=[...answers];next[index]=value;setAnswers(next);if(index===questions.length-1){setDone(true);const top=resultFrom(next);localStorage.setItem('postula_vocational_result_v1',JSON.stringify(top));void trackCvEvent('vocational_test_completed',{source:'test',result_count:3,mode:top.slice(0,3).map(x=>x.area).join('')},'/test-vocacional')}else setIndex(index+1)}
 function resultFrom(values:number[]){const totals:Record<Area,number>={R:0,I:0,A:0,S:0,E:0,C:0};values.forEach((v,i)=>totals[questions[i].area]+=v);return (Object.keys(totals) as Area[]).map(area=>({area,score:totals[area],...info[area]})).sort((a,b)=>b.score-a.score)}
 function restart(){setAnswers(Array(questions.length).fill(0));setIndex(0);setDone(false);setStarted(true)}
 const final=resultFrom(answers),top=final.slice(0,3),roles=Array.from(new Set(top.flatMap(x=>x.roles))).slice(0,10)
 function buildCv(){localStorage.setItem('postula_vocational_result_v1',JSON.stringify(final));localStorage.setItem('postula_first_cv_target_v1',roles[0]||'');void trackCvEvent('first_cv_started',{source:'vocational'},'/test-vocacional');location.href='/primer-cv'}
 return <main className={styles.page}>
  <header className={styles.top}><a href="/" className={styles.brand}><span>postula</span><strong>mejor</strong><span>.com</span></a><a href="/" className={styles.back}>Volver</a></header>
  {!started?<section className={styles.start}>
   <div className={styles.startCopy}><span>TEST VOCACIONAL · GRATIS</span><h1>No hace falta tener todo claro para empezar.</h1><p>Te voy a mostrar 30 situaciones cortas. Elegí cuánto te representan y al final vas a ver qué tipos de trabajo, áreas y primeros puestos pueden tener más sentido para vos.</p><div className={styles.startMeta}><div><b>30</b><span>situaciones</span></div><div><b>5 min</b><span>aprox.</span></div><div><b>3</b><span>señales principales</span></div></div><button onClick={beginTest}>Empezar el test <i>→</i></button><small>Sin respuestas correctas. Sin decidir una carrera por vos.</small></div>
   <div className={styles.startVisual} aria-hidden="true"><div className={styles.orbit}><span>CREAR</span><span>AYUDAR</span><span>ANALIZAR</span><span>HACER</span><span>IMPULSAR</span><span>ORDENAR</span></div><div className={styles.startCard}><small>UNA PISTA A LA VEZ</small><strong>¿Qué tipo de trabajo te daría ganas de probar?</strong><div><span>Curiosidad</span><span>Intereses</span><span>Experiencias</span></div></div></div>
  </section>:!done?<section className={styles.test}>
   <div className={styles.testHead}><span>TEST GRATUITO · INTERESES VOCACIONALES Y LABORALES</span><h1>Busquemos pistas sobre el trabajo que podría hacerte bien.</h1><p>No hay respuestas correctas. Contestá pensando en lo que realmente te atrae, no en lo que creés que “deberías” elegir.</p></div>
   <div className={styles.progress}><div style={{width:`${progress}%`}}/><span>{index+1} de {questions.length}</span></div>
   <article className={styles.question}><small>IMAGINATE EN ESTA SITUACIÓN</small><h2>{questions[index].text}</h2><div className={styles.answers}>{labels.map(x=><button key={x.v} onClick={()=>answer(x.v)}><b>{x.v}</b><span>{x.t}</span></button>)}</div>{index>0&&<button className={styles.previous} onClick={()=>setIndex(index-1)}>← Volver a la anterior</button>}</article>
   <div className={styles.method}><b>¿En qué se basa?</b><p>Usamos una adaptación orientativa propia del modelo RIASEC de Holland: seis grandes tipos de intereses laborales. Es el mismo marco teórico utilizado por O*NET Interest Profiler. Este test explora intereses; no mide inteligencia, capacidad ni determina una carrera obligatoria.</p></div>
  </section>:<section className={styles.results}>
   <div className={styles.resultHead}><span>TU MAPA DE INTERESES</span><h1>No sos “una sola cosa”. Estas son tus tres señales más fuertes hoy.</h1><p>Usalas como punto de partida para explorar trabajos, cursos y experiencias. Tus intereses pueden cambiar con el tiempo y con lo que vayas probando.</p></div>
   <div className={styles.code}>{top.map((x,i)=><div key={x.area} className={styles.codeItem}><strong>{x.area}</strong><span>{x.name}</span><i style={{height:`${Math.max(28,x.score/25*100)}%`}}/></div>)}</div>
   <div className={styles.topGrid}>{top.map((x,i)=><article key={x.area}><div><span>#{i+1}</span><b>{x.name}</b></div><h2>{x.short}</h2><p>{x.description}</p><small>ÁREAS PARA EXPLORAR</small><ul>{x.areas.map(a=><li key={a}>{a}</li>)}</ul></article>)}</div>
   <section className={styles.roles}><div><span>PARA BAJARLO A TIERRA</span><h2>Puestos iniciales que podrías explorar</h2><p>No significa que “tengas que” trabajar de esto. Son búsquedas concretas relacionadas con tus intereses principales para empezar a mirar qué te despierta curiosidad.</p></div><div className={styles.roleCloud}>{roles.map(r=><span key={r}>{r}</span>)}</div></section>
   <section className={styles.next}><div><span>SIGUIENTE PASO GRATIS</span><h2>Ahora transformemos esto en tu primer CV.</h2><p>Vamos a usar estos intereses como guía, pero el CV sólo va a incluir cosas reales que vos nos cuentes: estudios, habilidades, proyectos, trabajos informales o experiencia formal si la tenés.</p></div><button onClick={buildCv}>Armar mi primer CV con este resultado →</button></section>
   <div className={styles.actions}><button onClick={restart}>Rehacer el test</button><a href="/">Ir al analizador principal</a></div>
   <p className={styles.disclaimer}>Herramienta de orientación, no evaluación psicológica ni diagnóstico vocacional. Está basada en el marco RIASEC/Holland y desarrollada como experiencia propia de Postulá Mejor; no es el instrumento oficial O*NET Interest Profiler.</p>
  </section>}
 </main>
}
