'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useMemo,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type Audience='candidate'|'employer'
type CalendarEvent={id:string;source:'interview'|'custom';task_id?:string;interview_id?:string;conversation_id?:string;title:string;counterpart?:string;starts_at:string;ends_at?:string|null;duration_minutes?:number;mode?:string;location_text?:string|null;notes?:string|null;status:string;locked?:boolean}
type FormState={title:string;starts_at:string;duration_minutes:number;location_text:string;notes:string}
const weekdays=['Lun','Mar','Mié','Jue','Vie','Sáb','Dom']
const months=['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre']

function pad(v:number){return String(v).padStart(2,'0')}
function dayKey(d:Date){return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`}
function sameDay(iso:string,key:string){return dayKey(new Date(iso))===key}
function startMonth(d:Date){return new Date(d.getFullYear(),d.getMonth(),1)}
function addMonths(d:Date,amount:number){return new Date(d.getFullYear(),d.getMonth()+amount,1)}
function formatTime(v:string){return new Date(v).toLocaleTimeString('es-AR',{hour:'2-digit',minute:'2-digit'})}
function formatLong(v:string){return new Date(v).toLocaleString('es-AR',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}
function modeLabel(v?:string){return v==='virtual'?'Virtual':v==='telefonica'?'Telefónica':v==='presencial'?'Presencial':v==='a_coordinar'?'A coordinar':''}
function statusLabel(v:string){return v==='accepted'?'Confirmada':v==='proposed'?'Pendiente de respuesta':v==='declined'?'No aceptada':v==='cancelled'?'Cancelada':v==='completed'?'Completada':'Programada'}
function defaultForm(date=new Date()):FormState{const next=new Date(Math.max(Date.now()+3600000,date.getTime()));next.setMinutes(next.getMinutes()<30?30:0,0,0);if(next.getMinutes()===0&&date.getTime()<=Date.now())next.setHours(next.getHours()+1);return{title:'',starts_at:`${next.getFullYear()}-${pad(next.getMonth()+1)}-${pad(next.getDate())}T${pad(next.getHours())}:${pad(next.getMinutes())}`,duration_minutes:60,location_text:'',notes:''}}
async function token(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token||''}

export default function CalendarHub({audience}:{audience:Audience}){
 const today=new Date(),[month,setMonth]=useState(startMonth(today)),[selected,setSelected]=useState(dayKey(today)),[events,setEvents]=useState<CalendarEvent[]>([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState(''),[formOpen,setFormOpen]=useState(false),[form,setForm]=useState<FormState>(defaultForm()),[busy,setBusy]=useState(false),[companyName,setCompanyName]=useState('')
 const monthStart=new Date(month.getFullYear(),month.getMonth(),1),monthEnd=new Date(month.getFullYear(),month.getMonth()+1,1)
 async function load(){setLoading(true);setNotice('');try{const access=await token();if(!access)throw new Error('Iniciá sesión para usar el calendario.');const from=new Date(monthStart);from.setDate(from.getDate()-8);const to=new Date(monthEnd);to.setDate(to.getDate()+8);const r=await fetch(`/api/postula/calendar?audience=${audience}&from=${encodeURIComponent(from.toISOString())}&to=${encodeURIComponent(to.toISOString())}`,{headers:{Authorization:`Bearer ${access}`},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos cargar el calendario.');setEvents(d.events||[]);setCompanyName(d.company?.name||'')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos cargar el calendario.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[month.getFullYear(),month.getMonth(),audience])
 const cells=useMemo(()=>{const first=new Date(monthStart),weekday=(first.getDay()+6)%7,gridStart=new Date(first);gridStart.setDate(first.getDate()-weekday);return Array.from({length:42},(_,i)=>{const d=new Date(gridStart);d.setDate(gridStart.getDate()+i);return d})},[month.getFullYear(),month.getMonth()])
 const selectedEvents=events.filter(event=>sameDay(event.starts_at,selected)).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime())
 const future=events.filter(event=>new Date(event.starts_at).getTime()>=Date.now()&&!['cancelled','declined'].includes(event.status)).sort((a,b)=>new Date(a.starts_at).getTime()-new Date(b.starts_at).getTime())
 const confirmed=future.filter(event=>event.source==='interview'&&event.status==='accepted')
 const next=future[0]
 function selectDay(d:Date){const key=dayKey(d);setSelected(key);if(d.getMonth()!==month.getMonth()||d.getFullYear()!==month.getFullYear())setMonth(startMonth(d))}
 function openNew(){const parts=selected.split('-').map(Number),d=new Date(parts[0],parts[1]-1,parts[2],10,0);setForm(defaultForm(d));setFormOpen(true);setNotice('')}
 async function createTask(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setNotice('');try{const access=await token();if(!access)throw new Error('Iniciá sesión.');const date=new Date(form.starts_at);if(Number.isNaN(date.getTime()))throw new Error('Elegí una fecha y hora.');const r=await fetch('/api/postula/calendar',{method:'POST',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({audience,title:form.title,starts_at:date.toISOString(),duration_minutes:form.duration_minutes,location_text:form.location_text,notes:form.notes})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos guardar la tarea.');setFormOpen(false);setNotice('Agendado.');await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos guardar la tarea.')}finally{setBusy(false)}}
 async function changeTask(event:CalendarEvent,status:'completed'|'scheduled'){if(!event.task_id||busy)return;setBusy(true);try{const access=await token();const r=await fetch('/api/postula/calendar',{method:'PATCH',headers:{Authorization:`Bearer ${access}`,'Content-Type':'application/json'},body:JSON.stringify({id:event.task_id,status})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos actualizar la tarea.');await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos actualizar la tarea.')}finally{setBusy(false)}}
 async function removeTask(event:CalendarEvent){if(!event.task_id||busy||!window.confirm('¿Eliminar esta tarea del calendario?'))return;setBusy(true);try{const access=await token();const r=await fetch(`/api/postula/calendar?id=${encodeURIComponent(event.task_id)}`,{method:'DELETE',headers:{Authorization:`Bearer ${access}`}});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos eliminar la tarea.');await load()}catch(e){setNotice(e instanceof Error?e.message:'No pudimos eliminar la tarea.')}finally{setBusy(false)}}
 return <section className="pmcal-shell" data-audience={audience}>
  <header className="pmcal-hero"><div><span>CALENDARIO</span><h1>{audience==='employer'?'Entrevistas y tareas, en orden.':'Tus entrevistas y pendientes, en un lugar.'}</h1><p>{audience==='employer'?(companyName?`${companyName} · Entrevistas confirmadas y tareas del equipo.`:'Entrevistas confirmadas y tareas del equipo.'):'Cuando aceptás una entrevista se agrega automáticamente. También podés sumar recordatorios propios.'}</p></div><button type="button" onClick={openNew}>＋ Agregar tarea</button></header>
  <div className="pmcal-kpis"><article><small>PRÓXIMOS</small><b>{future.length}</b><span>eventos por delante</span></article><article><small>ENTREVISTAS</small><b>{confirmed.length}</b><span>confirmadas</span></article><article className="wide"><small>LO SIGUIENTE</small>{next?<><b>{formatLong(next.starts_at)}</b><span>{next.title}{next.counterpart?` · ${next.counterpart}`:''}</span></>:<><b>Agenda libre</b><span>No hay pendientes próximos.</span></>}</article></div>
  {notice&&<div className="pmcal-notice">{notice}<button type="button" onClick={()=>setNotice('')}>×</button></div>}
  <div className="pmcal-layout">
   <div className="pmcal-calendar"><div className="pmcal-month-head"><button type="button" onClick={()=>setMonth(addMonths(month,-1))}>←</button><div><small>{month.getFullYear()}</small><h2>{months[month.getMonth()]}</h2></div><div><button type="button" onClick={()=>{setMonth(startMonth(today));setSelected(dayKey(today))}}>Hoy</button><button type="button" onClick={()=>setMonth(addMonths(month,1))}>→</button></div></div><div className="pmcal-weekdays">{weekdays.map(x=><span key={x}>{x}</span>)}</div><div className="pmcal-grid">{cells.map(d=>{const key=dayKey(d),dayEvents=events.filter(event=>sameDay(event.starts_at,key)),outside=d.getMonth()!==month.getMonth(),isToday=key===dayKey(today);return <button type="button" key={key} data-selected={key===selected} data-outside={outside} data-today={isToday} onClick={()=>selectDay(d)}><strong>{d.getDate()}</strong><div>{dayEvents.slice(0,3).map(event=><i key={event.id} data-kind={event.source} data-status={event.status} title={event.title}/>)}{dayEvents.length>3&&<em>+{dayEvents.length-3}</em>}</div></button>})}</div></div>
   <aside className="pmcal-day"><div className="pmcal-day-head"><div><small>{new Date(`${selected}T12:00:00`).toLocaleDateString('es-AR',{weekday:'long'})}</small><h2>{new Date(`${selected}T12:00:00`).toLocaleDateString('es-AR',{day:'numeric',month:'long'})}</h2></div><button type="button" onClick={openNew}>＋</button></div>{loading?<div className="pmcal-empty">Cargando agenda…</div>:selectedEvents.length?selectedEvents.map(event=><article className="pmcal-event" key={event.id} data-kind={event.source} data-status={event.status}><time>{formatTime(event.starts_at)}</time><div><span>{event.source==='interview'?'ENTREVISTA':'TAREA'}</span><h3>{event.title}</h3>{event.counterpart&&<b>{event.counterpart}</b>}<p>{[modeLabel(event.mode),event.location_text].filter(Boolean).join(' · ')}</p>{event.notes&&<small>{event.notes}</small>}<em>{statusLabel(event.status)}</em></div>{event.source==='interview'?<Link href={`${audience==='employer'?'/empresas/panel?tab=mensajes':'/mensajes'}${audience==='candidate'&&event.conversation_id?`?conversation=${encodeURIComponent(event.conversation_id)}`:''}`}>Abrir chat</Link>:<div className="pmcal-event-actions"><button type="button" onClick={()=>void changeTask(event,event.status==='completed'?'scheduled':'completed')}>{event.status==='completed'?'Reabrir':'✓'}</button><button type="button" className="delete" onClick={()=>void removeTask(event)}>×</button></div>}</article>):<div className="pmcal-empty"><b>Ese día está libre.</b><p>Podés sumar una tarea propia o esperar a que una entrevista confirmada se agregue automáticamente.</p><button type="button" onClick={openNew}>Agregar algo</button></div>}</aside>
  </div>
  {formOpen&&<div className="pmcal-modal-backdrop" onMouseDown={e=>{if(e.currentTarget===e.target)setFormOpen(false)}}><form className="pmcal-modal" onSubmit={createTask}><header><div><small>NUEVO PENDIENTE</small><h2>Agregar al calendario</h2></div><button type="button" onClick={()=>setFormOpen(false)}>×</button></header><label>Título<input autoFocus value={form.title} onChange={e=>setForm(v=>({...v,title:e.target.value}))} maxLength={160} placeholder={audience==='employer'?'Ej. Llamar a candidato finalista':'Ej. Preparar portfolio'}/></label><div className="pmcal-form-grid"><label>Fecha y hora<input type="datetime-local" value={form.starts_at} onChange={e=>setForm(v=>({...v,starts_at:e.target.value}))}/></label><label>Duración<select value={form.duration_minutes} onChange={e=>setForm(v=>({...v,duration_minutes:Number(e.target.value)}))}><option value={30}>30 min</option><option value={60}>1 hora</option><option value={90}>1 h 30</option><option value={120}>2 horas</option><option value={240}>4 horas</option></select></label></div><label>Lugar o enlace <span>opcional</span><input value={form.location_text} onChange={e=>setForm(v=>({...v,location_text:e.target.value}))} maxLength={240} placeholder="Palermo · Meet · oficina"/></label><label>Nota <span>opcional</span><textarea value={form.notes} onChange={e=>setForm(v=>({...v,notes:e.target.value}))} maxLength={1200} rows={4} placeholder="Algo que quieras recordar…"/></label><button className="pmcal-save" disabled={busy||!form.title.trim()}>{busy?'Guardando…':'Guardar en calendario'}</button></form></div>}
 </section>
}
