'use client'

import Link from 'next/link'
import {useEffect,useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import css from './EmploymentReviewPanel.module.css'

type Review={id:string;direction:string;rating:number;comment?:string|null;reply_body?:string|null;editable_until:string;submitted_at?:string;updated_at:string}
type ReviewData={ok:boolean;status:string;hired_at?:string|null;employment_ended_at?:string|null;review_available_at?:string|null;editable_until?:string|null;can_review:boolean;can_end_relationship?:boolean;viewer_role:'candidate'|'employer';job_title:string;company_name:string;mine:Review|null;other:Review|null;error?:string}

function dateLabel(value?:string|null){if(!value)return'';return new Date(value).toLocaleDateString('es-AR',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'America/Argentina/Buenos_Aires'})}
function starsText(value:number){return`${'★'.repeat(Math.max(0,Math.min(5,value)))}${'☆'.repeat(Math.max(0,5-Math.min(5,value)))}`}

export default function EmploymentReviewPanel({applicationId}:{applicationId:string}){
 const [data,setData]=useState<ReviewData|null>(null),[rating,setRating]=useState(0),[comment,setComment]=useState(''),[reply,setReply]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[error,setError]=useState('')
 async function request(body?:Record<string,unknown>){
  const {data:auth}=await cvAuthClient().auth.getSession();const token=auth.session?.access_token
  if(!token)throw new Error('Iniciá sesión para ver esta experiencia.')
  const r=await fetch(body?'/api/postula/reviews':`/api/postula/reviews?application_id=${encodeURIComponent(applicationId)}`,body?{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({application_id:applicationId,...body})}:{headers:{Authorization:`Bearer ${token}`},cache:'no-store'})
  const payload=await r.json().catch(()=>({}));if(!r.ok)throw new Error(payload?.error||'No pudimos actualizar la evaluación.');return payload as ReviewData
 }
 async function load(){try{const next=await request();setData(next);setRating(Number(next.mine?.rating||0));setComment(String(next.mine?.comment||''));setReply(String(next.other?.reply_body||''))}catch(e){setError(e instanceof Error?e.message:'No pudimos cargar la evaluación.')}}
 useEffect(()=>{void load()},[applicationId])
 async function saveReview(){if(!rating||busy)return;setBusy(true);setError('');setNotice('');try{const next=await request({action:'review',rating,comment});setData(next);setRating(Number(next.mine?.rating||rating));setComment(String(next.mine?.comment||comment));setNotice('Calificación guardada. Es opcional y podés modificarla mientras el período siga abierto.')}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar la calificación.')}finally{setBusy(false)}}
 async function saveReply(){if(!data?.other?.id||!reply.trim()||busy)return;setBusy(true);setError('');setNotice('');try{const next=await request({action:'reply',review_id:data.other.id,reply});setData(next);setReply(String(next.other?.reply_body||reply));setNotice('Observación guardada.')}catch(e){setError(e instanceof Error?e.message:'No pudimos guardar la observación.')}finally{setBusy(false)}}
 async function endRelationship(){if(!data?.can_end_relationship||busy)return;if(!window.confirm('¿Confirmás que esta relación laboral ya finalizó? Esto habilita el período opcional de evaluación para ambas partes.'))return;setBusy(true);setError('');setNotice('');try{const next=await request({action:'end_relationship'});setData(next);setNotice('Relación marcada como finalizada. La evaluación opcional quedó habilitada durante 30 días.')}catch(e){setError(e instanceof Error?e.message:'No pudimos actualizar la relación laboral.')}finally{setBusy(false)}}
 if(error&&!data)return <div className={css.panel}><div className={css.error}>{error}</div></div>
 if(!data||data.status!=='hired')return null
 const employer=data.viewer_role==='employer',otherName=employer?'postulante':'empresa',mineName=employer?'al postulante':'a la empresa'
 if(!data.can_review&&!data.mine&&!data.other&&data.review_available_at&&new Date(data.review_available_at).getTime()>Date.now())return <section className={css.panel} aria-label="Calificación de experiencia laboral"><div className={css.head}><div><span>EXPERIENCIA LABORAL VERIFICADA</span><h3>La evaluación se habilita con tiempo real de experiencia.</h3><p>La contratación ya fue confirmada, pero calificar es totalmente opcional. Para que haya criterio, la evaluación se habilita a los 30 días de relación o antes si la relación laboral finaliza.</p></div><div className={css.deadline}>Desde {dateLabel(data.review_available_at)}</div></div><div className={css.waiting}><div><b>No hace falta hacer nada ahora.</b><p>Cuando se habilite, sólo esta persona y la empresa vinculada a esta contratación podrán evaluarse entre sí.</p></div>{data.can_end_relationship&&<button type="button" disabled={busy} onClick={()=>void endRelationship()}>{busy?'Actualizando…':'Marcar relación como finalizada'}</button>}</div><div className={css.notice}>Las calificaciones no son obligatorias. Nadie puede evaluar una empresa o postulante con quien no exista una contratación confirmada. <Link href="/politica-evaluaciones">Ver reglas simples</Link>.</div>{notice&&<div className={css.saved}>{notice}</div>}{error&&<div className={css.error}>{error}</div>}</section>
 return <section className={css.panel} aria-label="Calificación de experiencia laboral">
  <div className={css.head}><div><span>EXPERIENCIA LABORAL VERIFICADA</span><h3>Calificación bilateral y opcional</h3><p>Sólo pueden participar la empresa y la persona vinculadas a esta contratación. Tenés 30 días para evaluar o responder; hacerlo no es obligatorio.</p></div><div className={css.deadline} data-open={data.can_review}>{data.can_review?`Hasta ${dateLabel(data.editable_until)}`:'Período cerrado'}</div></div>
  <div className={css.grid}>
   <div className={css.card}><small>TU EVALUACIÓN</small><h4>Calificá {mineName}</h4>{data.can_review?<><div className={css.stars} aria-label="Calificación de 1 a 5">{[1,2,3,4,5].map(n=><button type="button" key={n} className={css.star} data-on={rating>=n} onClick={()=>setRating(n)} aria-label={`${n} estrella${n===1?'':'s'}`}>★</button>)}</div><textarea className={css.textarea} maxLength={1200} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Contá brevemente cómo fue la experiencia laboral. Evitá datos sensibles o personales que no correspondan."/><button type="button" className={css.action} disabled={busy||!rating} onClick={()=>void saveReview()}>{busy?'Guardando…':data.mine?'Actualizar calificación':'Guardar calificación'}</button><div className={css.mini}>Opcional: podés cerrar esta pantalla sin calificar.</div></>:data.mine?<div className={css.review}><strong>{starsText(data.mine.rating)} · {data.mine.rating}/5</strong>{data.mine.comment&&<p>{data.mine.comment}</p>}</div>:<div className={css.closed}>No dejaste una calificación durante el período opcional.</div>}{data.mine?.reply_body&&<div className={css.reply}><b>Respuesta recibida</b><p>{data.mine.reply_body}</p></div>}</div>
   <div className={css.card}><small>EVALUACIÓN RECIBIDA</small><h4>Lo que indicó {otherName}</h4>{data.other?<><div className={css.review}><strong>{starsText(data.other.rating)} · {data.other.rating}/5</strong>{data.other.comment&&<p>{data.other.comment}</p>}</div>{data.can_review?<><textarea className={css.textarea} maxLength={1200} value={reply} onChange={e=>setReply(e.target.value)} placeholder="Si querés aclarar algo o no estás de acuerdo, podés dejar una observación."/><button type="button" className={`${css.action} ${css.secondary}`} disabled={busy||!reply.trim()} onClick={()=>void saveReply()}>{data.other.reply_body?'Actualizar observación':'Responder / dejar observación'}</button></>:data.other.reply_body&&<div className={css.reply}><b>Tu observación</b><p>{data.other.reply_body}</p></div>}</>:<div className={css.closed}>{data.can_review?`La otra parte todavía no evaluó. También es opcional y puede hacerlo hasta ${dateLabel(data.editable_until)}.`:'La otra parte no dejó una evaluación durante el período.'}</div>}</div>
  </div>
  {notice&&<div className={css.saved}>{notice}</div>}{error&&<div className={css.error}>{error}</div>}
  <div className={css.notice}>La evaluación se habilita después de 30 días de relación o cuando se marca finalizada. El período para evaluar, modificar o responder dura 30 días. <Link href="/politica-evaluaciones">Cómo funciona</Link>.</div>
 </section>
}
