export type PreviewGig={
 id:string;title:string;category:string;location:string;when:string;pay:string;duration:string;poster:string;posterRole:string;rating:string;verified:boolean;image:string;summary:string;requirements:string[];tags:string[]
}

export const previewGigs:PreviewGig[]=[
 {id:'armar-mueble-palermo',title:'Armar un placard y una biblioteca',category:'Casa y arreglos',location:'Palermo · CABA',when:'Hoy · desde las 17:30',pay:'$38.000',duration:'3–4 h',poster:'Sofía M.',posterRole:'Vecina',rating:'4,9',verified:true,image:'https://images.pexels.com/photos/5691622/pexels-photo-5691622.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Necesito una mano para armar dos muebles nuevos. Tengo herramientas básicas y manuales.',requirements:['Experiencia armando muebles','Cuidado del espacio','Confirmar horario antes de ir'],tags:['Hoy','Herramientas','Interior']},
 {id:'fotos-emprendimiento-caballito',title:'Fotos y reels para emprendimiento',category:'Contenido y foto',location:'Caballito · CABA',when:'Sábado · 11:00',pay:'$52.000',duration:'2 h',poster:'Lola Estudio',posterRole:'Emprendimiento',rating:'5,0',verified:true,image:'https://images.pexels.com/photos/3379943/pexels-photo-3379943.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Buscamos alguien con buen ojo para sacar fotos de producto y 4 reels cortos para redes.',requirements:['Celular o cámara propia','Portfolio simple','Entrega digital en 72 h'],tags:['Creativo','Sábado','Redes']},
 {id:'paseo-perro-belgrano',title:'Pasear a Milo durante la semana',category:'Mascotas',location:'Belgrano · CABA',when:'Lun a vie · 13:00',pay:'$9.000 / paseo',duration:'45 min',poster:'Tomás R.',posterRole:'Dueño de Milo',rating:'4,8',verified:true,image:'https://images.pexels.com/photos/7210748/pexels-photo-7210748.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Busco una persona responsable para paseo al mediodía. Milo es mediano, sociable y tiene correa.',requirements:['Buen trato con animales','Puntualidad','Zona Belgrano / Núñez'],tags:['Recurrente','Mascotas','Mediodía']},
 {id:'ayuda-evento-san-telmo',title:'Ayuda en evento de marca',category:'Eventos',location:'San Telmo · CABA',when:'Viernes · 18:00 a 00:00',pay:'$46.000',duration:'6 h',poster:'Modo Sur',posterRole:'Productora',rating:'4,7',verified:true,image:'https://images.pexels.com/photos/1190297/pexels-photo-1190297.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Recepción de invitados, entrega de acreditaciones y apoyo general durante un lanzamiento.',requirements:['Buena presencia y trato','Llegar 30 min antes','Vestimenta negra lisa'],tags:['Evento','Viernes','Noche']},
 {id:'mudanza-almagro',title:'Dos personas para una mini mudanza',category:'Mudanzas',location:'Almagro → Villa Crespo',when:'Mañana · 9:30',pay:'$32.000 c/u',duration:'3 h',poster:'Agus P.',posterRole:'Particular',rating:'4,9',verified:true,image:'https://images.pexels.com/photos/4246120/pexels-photo-4246120.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Cajas, una mesa, sillas y un sillón chico. Ya tenemos flete; necesitamos ayuda para subir y bajar.',requirements:['Poder cargar peso moderado','Ropa cómoda','Confirmar disponibilidad'],tags:['Mañana','Físico','3 horas']},
 {id:'excel-negocio-vicente-lopez',title:'Ordenar una planilla de ventas',category:'Digital',location:'Vicente López · remoto posible',when:'Esta semana',pay:'$44.000',duration:'2–3 h',poster:'Ferretería Norte',posterRole:'Comercio',rating:'4,8',verified:true,image:'https://images.pexels.com/photos/590041/pexels-photo-590041.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Tenemos un Excel con ventas y productos desordenados. Queremos filtros, totales y una vista simple.',requirements:['Excel intermedio','Explicar lo que hiciste','No compartir información del negocio'],tags:['Remoto','Excel','Negocio']},
 {id:'cocina-cumple-boedo',title:'Ayudante de cocina para cumpleaños',category:'Gastronomía',location:'Boedo · CABA',when:'Domingo · 16:00 a 22:00',pay:'$48.000',duration:'6 h',poster:'Mariana C.',posterRole:'Particular',rating:'4,9',verified:true,image:'https://images.pexels.com/photos/4252139/pexels-photo-4252139.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Apoyo para preparar, ordenar y servir comida en un cumpleaños familiar de 35 personas.',requirements:['Experiencia básica de cocina','Orden e higiene','Llegar puntual'],tags:['Domingo','Cocina','Evento']},
 {id:'clases-compu-adulto-mayor',title:'Enseñar WhatsApp y trámites digitales',category:'Clases y ayuda',location:'Flores · CABA',when:'A coordinar',pay:'$18.000 / clase',duration:'1 h',poster:'Laura A.',posterRole:'Familiar',rating:'5,0',verified:true,image:'https://images.pexels.com/photos/7551617/pexels-photo-7551617.jpeg?auto=compress&cs=tinysrgb&w=900',summary:'Buscamos alguien paciente para enseñar uso básico del celular, WhatsApp, turnos y pagos simples.',requirements:['Paciencia','Explicar sin apuro','Preferencia por encuentros presenciales'],tags:['Flexible','Ayuda','1 hora']},
]

export const gigCategories=['Para hoy','Casa y arreglos','Eventos','Mascotas','Mudanzas','Contenido y foto','Digital','Gastronomía','Clases y ayuda']
