import {createClient} from '@supabase/supabase-js'
import {currentJobBoost} from './publicJobBoost'
import {publicJobExtras} from './publicJobExtras'
import {commonPublicJobs} from './publicJobCommon'

export type PreviewJob={
  slug:string;title:string;company:string;location:string;mode:'Presencial'|'Híbrido'|'Remoto';schedule:string;area:string;source:string;sourceUrl:string;checkedAt:string;summary:string;requirements:string[];tags:string[];external:boolean;internalJobId?:string;compensation?:string;confidential?:boolean;logoUrl?:string
}

const officialCheck=['Revisar los requisitos completos en la publicación oficial','Confirmar modalidad, horario y vigencia antes de postularte','Postularse únicamente por el canal oficial de la empresa']

export const previewJobs:PreviewJob[]=[
  {slug:'despegar-agente-ventas-pilar',title:'Agente de viajes (Ventas) - Tienda Pilar',company:'Despegar',location:'Buenos Aires · Pilar',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Despegar Careers / Lever',sourceUrl:'https://jobs.lever.co/despegar/?location=Buenos+Aires',checkedAt:'2026-08-24',summary:'Búsqueda vigente para atención comercial y venta de experiencias de viaje en la tienda de Pilar.',requirements:officialCheck,tags:['Ventas','Turismo','Pilar'],external:true},
  {slug:'pedidosya-strategy-performance-market',title:'Strategy & Performance Specialist - PedidosYa Market',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Híbrido',schedule:'Full time',area:'Administración y Finanzas',source:'PedidosYa · Empleos',sourceUrl:'https://empleos.pedidosya.com/job/strategy-and-performance-specialist-pedidosya-market-in-buenos-aires-argentina-jid-2134',checkedAt:'2026-08-24',summary:'Rol regional para acompañar la estrategia de PedidosYa Market, bajar planes a los equipos locales y seguir performance, crecimiento y rentabilidad.',requirements:officialCheck,tags:['Estrategia','Performance','Híbrido'],external:true},
  {slug:'emi-customer-support',title:'Customer Support Representative',company:'Emi Labs',location:'Provincia de Buenos Aires',mode:'Híbrido',schedule:'6 horas',area:'Atención al cliente',source:'Emi Labs Careers / Lever',sourceUrl:'https://jobs.lever.co/emilabs/260adebe-02da-4a7d-927c-ada8c36c1899',checkedAt:'2026-08-24',summary:'Posición vigente de soporte para resolver consultas, investigar incidentes y trabajar junto a equipos de producto y tecnología.',requirements:['Disponibilidad para jornada de 6 horas','Comunicación y resolución de problemas','Revisar requisitos completos en la publicación oficial'],tags:['Soporte','Part time','Tecnología'],external:true},
  {slug:'ey-junior-consultoria-base-talentos',title:'Junior para Consultoría - Base de Talentos',company:'EY',location:'Buenos Aires · CABA',mode:'Híbrido',schedule:'Full time',area:'Administración y Finanzas',source:'EY Careers',sourceUrl:'https://careers.ey.com/ey/job/Buenos-Aires-EY-Junior-para-Consultor%C3%ADa-CABA-1437/1290386901/',checkedAt:'2026-08-24',summary:'Base de talentos junior para incorporarse a equipos de consultoría de EY en Buenos Aires, con modalidad híbrida y capacitación continua.',requirements:['Perfil orientado a resultados y aprendizaje','Planificación, organización y trabajo en equipo','Revisar requisitos académicos completos en EY Careers'],tags:['Junior','Consultoría','Primer empleo'],external:true},
  {slug:'emi-backend-engineer',title:'Back-end Engineer',company:'Emi Labs',location:'Provincia de Buenos Aires',mode:'Híbrido',schedule:'Full time',area:'Tecnología',source:'Emi Labs Careers / Lever',sourceUrl:'https://jobs.lever.co/emilabs/d0ff8121-5a9f-4c4d-b306-045e81ae54d3',checkedAt:'2026-08-24',summary:'Búsqueda vigente para desarrollo back-end del producto de recruiting de Emi Labs, dentro del equipo de ingeniería.',requirements:officialCheck,tags:['Back-end','Software','Híbrido'],external:true},
  {slug:'despegar-pasaporte-trainee-2026',title:'Pasaporte Trainee 2026 | Argentina',company:'Despegar',location:'Buenos Aires · Argentina',mode:'Híbrido',schedule:'Part time · 20 h semanales',area:'Administración y Finanzas',source:'Despegar Careers / Lever',sourceUrl:'https://jobs.lever.co/despegar/57d7de89-ac21-44f9-bbde-0f5bb81a6082',checkedAt:'2026-08-24',summary:'Programa trainee de seis meses para estudiantes avanzados, con posibilidades en Comercial, Finanzas, Operaciones, Customer Service, RRHH y Legal.',requirements:['Ser estudiante regular con al menos 50% de la carrera aprobada','Cursar los últimos semestres de carreras afines','Disponibilidad part time en esquema híbrido'],tags:['Trainee','Estudiantes','Primer empleo'],external:true},
  {slug:'despegar-agente-ventas-tortuguitas',title:'Agente de viajes (Ventas) - Tienda TOM',company:'Despegar',location:'Buenos Aires · Tortuguitas',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Despegar Careers / Lever',sourceUrl:'https://jobs.lever.co/despegar/77bf31a4-721a-4e86-8ba4-3036e2036b78',checkedAt:'2026-08-24',summary:'Rol comercial para asesorar clientes por canales presenciales y remotos, preparar cotizaciones y vender experiencias de viaje.',requirements:['Experiencia comercial o de atención al cliente','Disponibilidad para turnos rotativos','Orientación a resultados y buena comunicación'],tags:['Ventas','Turismo','Atención al cliente'],external:true},
  {slug:'emi-technical-project-manager',title:'Technical Project Manager',company:'Emi Labs',location:'Argentina · Buenos Aires',mode:'Remoto',schedule:'Full time',area:'Tecnología',source:'Emi Labs Careers / Lever',sourceUrl:'https://jobs.lever.co/emilabs/5bb2d94a-3ac5-46cd-84bc-5a1795f38264',checkedAt:'2026-08-24',summary:'Gestión end-to-end de implementaciones técnicas, coordinación de equipos y relación con clientes durante discovery, configuración, QA y go-live.',requirements:['3 a 5+ años en project management o implementación','Capacidad para traducir negocio a soluciones técnicas','Inglés upper-intermediate'],tags:['Project Management','SaaS','Remoto'],external:true},
  {slug:'emi-product-manager',title:'Product Manager',company:'Emi Labs',location:'Provincia de Buenos Aires',mode:'Híbrido',schedule:'Full time',area:'Producto y Diseño',source:'Emi Labs Careers / Lever',sourceUrl:'https://jobs.lever.co/emilabs/63ee35db-2cda-45fd-959f-a95b3d9d6403',checkedAt:'2026-08-24',summary:'Rol de producto para definir estrategia, requisitos y ejecución de iniciativas de software junto a ingeniería, data y equipos de cara al cliente.',requirements:['5+ años de Product Management','Experiencia con productos técnicos de software','Comunicación en español e inglés'],tags:['Producto','B2B SaaS','Tecnología'],external:true},
  {slug:'ey-junior-auditoria',title:'Junior para Auditoría Externa - Base de Talentos',company:'EY',location:'Buenos Aires · CABA',mode:'Híbrido',schedule:'Full time',area:'Administración y Finanzas',source:'EY Careers',sourceUrl:'https://careers.ey.com/ey/job/Buenos-Aires-EY-Junior-para-Auditor%C3%ADa-Externa-Base-de-Talentos-CABA-1002/1399547833/',checkedAt:'2026-08-24',summary:'Convocatoria junior para incorporarse a equipos de auditoría externa y desarrollarse dentro de una firma global de servicios profesionales.',requirements:['Interés en Auditoría y servicios profesionales','Perfil analítico y colaborativo','Disponibilidad para trabajar en Buenos Aires'],tags:['Junior','Auditoría','Primeros empleos'],external:true},
]

const brandingBucket='https://pejkycdttogpmmdntzuq.supabase.co/storage/v1/object/public/postula-branding/'
const brandDomains:Record<string,string>={
 'despegar':'https://www.despegar.com/favicon.ico','ey':'https://www.ey.com/favicon.ico','marriott international':'https://www.marriott.com/favicon.ico','minor hotels europe & americas':'https://www.minorhotels.com/favicon.ico','wyndham hotels & resorts':'https://www.wyndhamhotels.com/favicon.ico','coca-cola femsa':'https://coca-colafemsa.com/favicon.ico','cencosud':'https://www.cencosud.com/favicon.ico','givaudan':'https://www.givaudan.com/favicon.ico','emi labs':'https://www.emilabs.ai/favicon.ico','pedidosya':'https://www.pedidosya.com/favicon.ico','dlocal':'https://www.dlocal.com/favicon.ico','aleph':'https://www.alephholding.com/favicon.ico','binance':'https://www.binance.com/favicon.ico','monks':'https://www.monks.com/favicon.ico','hogarth worldwide':'https://www.hogarth.com/favicon.ico','appsflyer':'https://www.appsflyer.com/favicon.ico','grido':'https://www.gridohelado.com/favicon.ico','carrefour':'https://www.carrefour.com.ar/favicon.ico','coto':'https://www.coto.com/favicon.ico','supermercados dia':'https://diaonline.supermercadosdia.com.ar/favicon.ico','changomás':'https://www.masonline.com.ar/favicon.ico','farmacity':'https://www.farmacity.com/favicon.ico','frávega':'https://www.fravega.com/favicon.ico','mercado libre':'https://www.mercadolibre.com.ar/favicon.ico'
}
function brandLogo(company:string){return brandDomains[company.trim().toLowerCase()]||''}
function normalizeMode(v:string):'Presencial'|'Híbrido'|'Remoto'{const s=v.toLowerCase();if(s.includes('remot'))return'Remoto';if(s.includes('híbr')||s.includes('hibr'))return'Híbrido';return'Presencial'}
function semanticKey(job:PreviewJob){if(job.internalJobId)return`internal:${job.internalJobId}`;const url=job.sourceUrl.toLowerCase();if(/jobs\.lever\.co|greenhouse\.io|boards\.greenhouse|\/viewjob\?|\/job\//.test(url))return`url:${url}`;return`semantic:${job.company}|${job.title}|${job.location}`.toLowerCase()}
function normalized(value:string){return value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\s+/g,' ').trim()}
const foreignLocation=/\b(sudafrica|south africa|brasil|brazil|colombia|peru|chile|uruguay|montevideo|paraguay|bolivia|ecuador|venezuela|mexico|latinoamerica|latin america|latam|global|worldwide|spain|espana|portugal|united states|estados unidos|usa|miami|new york|sao paulo|bogota|medellin|lima)\b/
function argentinaOnly(job:PreviewJob){const where=normalized(job.location||'');return Boolean(where)&&!foreignLocation.test(where)}
function recency(job:PreviewJob){const value=Date.parse(String(job.checkedAt||''));if(!Number.isFinite(value))return 0;return Math.min(value,Date.now())}
async function nativeJobs():Promise<PreviewJob[]>{try{const db=createClient('https://pejkycdttogpmmdntzuq.supabase.co','sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I',{auth:{persistSession:false,autoRefreshToken:false}});const {data,error}=await db.rpc('pm_public_job_catalog');if(error||!Array.isArray(data))return[];return data.map((r:any)=>({slug:`pm-${r.id}`,title:String(r.title),company:String(r.company_name),location:String(r.location_text||'Argentina'),mode:normalizeMode(String(r.work_mode||'')),schedule:String(r.schedule||'A confirmar'),area:String(r.area||'Otros rubros'),source:`Publicada en Postulá Mejor · ${r.employer_visibility==='confidential'?'identidad del empleador reservada':r.company_verification==='verified'?'empresa verificada':'validación básica'}`,sourceUrl:`/postular/pm-${r.id}`,checkedAt:String(r.published_at||new Date().toISOString()),summary:String(r.description||'').slice(0,1000),requirements:Array.isArray(r.requirements)?r.requirements.map(String):[],tags:[String(r.area||'Trabajo'),String(r.work_mode||''),r.employer_visibility==='confidential'?'Empleador reservado':''].filter(Boolean),external:false,internalJobId:String(r.id),compensation:String(r.compensation_text||''),confidential:r.employer_visibility==='confidential',logoUrl:r.company_logo_path?`${brandingBucket}${String(r.company_logo_path)}`:''}))}catch{return[]}}

export async function getJobCatalog(){
  const [{discoverPublicJobs},{discoverOverflowJobs},native]=await Promise.all([import('./publicJobSources'),import('./publicJobOverflow'),nativeJobs()])
  const [live,overflow]=await Promise.all([discoverPublicJobs(),discoverOverflowJobs()])
  const seen=new Set<string>()
  return [...commonPublicJobs,...previewJobs,...native,...publicJobExtras,...currentJobBoost,...live,...overflow]
   .filter(job=>{if(!argentinaOnly(job))return false;const key=semanticKey(job);if(seen.has(key))return false;seen.add(key);return true})
   .map(job=>({...job,logoUrl:job.confidential?'':job.logoUrl||brandLogo(job.company)}))
   .sort((a,b)=>recency(b)-recency(a)||Number(Boolean(b.internalJobId))-Number(Boolean(a.internalJobId))||a.title.localeCompare(b.title,'es'))
}

export function getPreviewJob(slug:string){const job=[...commonPublicJobs,...previewJobs,...publicJobExtras,...currentJobBoost].find(job=>job.slug===slug);return job?{...job,logoUrl:job.logoUrl||brandLogo(job.company)}:undefined}
