import Link from 'next/link'
import styles from './platform.module.css'
import {PlatformFooter,PlatformHeader,MobileNav} from './PlatformChrome'
import {getJobCatalog} from './jobs'
import {previewGigs} from './gigs'
import './premium-v4.css'
import './premium-v5.css'
import './premium-v6.css'
import './premium-v7.css'

export const metadata={title:'Postulá Mejor | Tu red para encontrar trabajo',description:'Empleos, changas, CV y conversaciones en una experiencia laboral más humana.',robots:{index:false,follow:false}}
export const revalidate=21600

const people=[
 {name:'Mica',role:'Diseño',image:'https://images.pexels.com/photos/3769021/pexels-photo-3769021.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Nico',role:'Ventas',image:'https://images.pexels.com/photos/614810/pexels-photo-614810.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Cami',role:'Gastro',image:'https://images.pexels.com/photos/733872/pexels-photo-733872.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Facu',role:'Logística',image:'https://images.pexels.com/photos/2379005/pexels-photo-2379005.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Lola',role:'Social',image:'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=500'},
 {name:'Agus',role:'Admin',image:'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=500'},
]

const categoryCards=[
 {title:'Gastronomía',copy:'Bar, cocina, salón, café',image:'https://images.pexels.com/photos/3771118/pexels-photo-3771118.jpeg?auto=compress&cs=tinysrgb&w=900'},
 {title:'Ventas',copy:'Retail, comercial, atención',image:'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=900'},
 {title:'Logística',copy:'Depósito, reparto, operaciones',image:'https://images.pexels.com/photos/6169668/pexels-photo-6169668.jpeg?auto=compress&cs=tinysrgb&w=900'},
 {title:'Administración',copy:'Oficina, soporte, finanzas',image:'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=900'},
]

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}
function jobVisual(area:string,index:number){const a=area.toLowerCase();if(/venta|comercial|atenci/.test(a))return 'https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=1200';if(/tecn|producto|dise/.test(a))return 'https://images.pexels.com/photos/3861969/pexels-photo-3861969.jpeg?auto=compress&cs=tinysrgb&w=1200';if(/admin|finan|audit/.test(a))return 'https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=1200';return ['https://images.pexels.com/photos/3768126/pexels-photo-3768126.jpeg?auto=compress&cs=tinysrgb&w=1200','https://images.pexels.com/photos/3184418/pexels-photo-3184418.jpeg?auto=compress&cs=tinysrgb&w=1200'][index%2]}

export default async function PostulaPreview(){
 const jobs=await getJobCatalog()
 const featured=jobs.slice(0,5)
 return <main className={`${styles.page} pm7-page pm7-candidate`}>
  <PlatformHeader/>

  <section className="pm7-hero"><div className="pm7-hero-bg one"/><div className="pm7-hero-bg two"/><div className="pm7-hero-inner">
   <div className="pm7-hero-copy"><span className="pm7-eyebrow coral">TRABAJO SIN CARA DE TRÁMITE</span><h1>Encontrá algo<br/>que te dé <em>ganas.</em></h1><p>Empleos, changas, gente, empresas y herramientas para moverte. Más conversación, menos formulario eterno.</p><div className="pm7-search"><div><small>¿Qué querés hacer?</small><b>ventas, café, diseño, logística…</b></div><div><small>¿Dónde?</small><b>CABA y Buenos Aires</b></div><Link href="/empleos-preview">Buscar</Link></div><div className="pm7-hero-actions"><Link href="/empleos-preview" className="pm7-btn-black">Explorar empleos</Link><Link href="/changas-preview" className="pm7-btn-glass">Ver changas para hoy</Link></div><div className="pm7-hero-proof"><span><i/>Postularte es gratis</span><span><i/>Tu perfil es tuyo</span><span><i/>La IA explica, no decide</span></div></div>
   <div className="pm7-hero-visual"><div className="pm7-main-photo"><div className="pm7-main-photo-image"/><div className="pm7-photo-caption"><span>HOY · PALERMO</span><b>Barista · Café de especialidad</b><small>Presencial · Turno mañana</small></div></div><div className="pm7-float-job"><span className="pm7-float-logo">SP</span><div><small>NUEVA OPORTUNIDAD</small><b>Vendedor/a · Shopping</b><span>Hace 8 min · 2,4 km</span></div><strong>→</strong></div><div className="pm7-float-msg"><div className="pm7-chat-avatar">M</div><p><b>Marina · RRHH</b><span>Hola, vimos tu perfil. ¿Podés hablar hoy?</span></p><small>ahora</small></div><div className="pm7-float-match"><b>92%</b><span>Tu perfil coincide</span><small>te explicamos por qué</small></div></div>
  </div></section>

  <section className="pm7-stories"><div className="pm7-stories-inner"><div className="pm7-stories-label"><span>GENTE EN MOVIMIENTO</span><b>Perfiles, rubros y oportunidades</b></div><div className="pm7-story-row">{people.map((p,i)=><Link href="/empleos-preview" key={p.name} className="pm7-story"><span className={`pm7-story-ring r${i%4}`}><i style={{backgroundImage:`url(${p.image})`}}/></span><b>{p.name}</b><small>{p.role}</small></Link>)}</div><Link className="pm7-story-more" href="/empleos-preview">Ver todo →</Link></div></section>

  <section className="pm7-discover"><div className="pm7-section-head"><div><span className="pm7-eyebrow blue">DESCUBRÍ TU LUGAR</span><h2>No todos buscan lo mismo.<br/>Por suerte.</h2></div><p>Entrá por rubro, por cercanía o por lo que te gustaría probar. La experiencia se parece más a descubrir contenido que a navegar una planilla.</p></div><div className="pm7-category-grid">{categoryCards.map((c,i)=><Link href="/empleos-preview" key={c.title} className={`pm7-category-card c${i}`} style={{backgroundImage:`url(${c.image})`}}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{c.title}</h3><p>{c.copy}</p></div><b>→</b></Link>)}</div></section>

  <section className="pm7-feed"><div className="pm7-feed-layout"><div className="pm7-feed-main"><div className="pm7-feed-title"><div><span className="pm7-eyebrow coral">PARA VOS</span><h2>Oportunidades que se sienten cerca.</h2></div><Link href="/empleos-preview">Ver todas</Link></div><div className="pm7-social-job-list">{featured.map((job,i)=><article className="pm7-social-job" key={job.slug}><div className="pm7-social-job-cover" style={{backgroundImage:`url(${jobVisual(job.area,i)})`}}><span>{job.mode}</span><button aria-label="Guardar">♡</button></div><div className="pm7-social-job-body"><div className="pm7-social-company"><span>{initials(job.company)}</span><div><b>{job.company}</b><small>{job.location}</small></div><em>hace poco</em></div><h3>{job.title}</h3><p>{job.summary}</p><div className="pm7-social-tags"><span>{job.area}</span><span>{job.schedule}</span>{job.tags.slice(0,1).map(x=><span key={x}>{x}</span>)}</div><div className="pm7-social-job-foot"><span><i/>Fuente verificada</span><Link href={`/empleos-preview/${job.slug}`}>Ver trabajo →</Link></div></div></article>)}</div></div>
   <aside className="pm7-feed-side"><div className="pm7-profile-card"><div className="pm7-profile-top"><span className="pm7-profile-avatar">GG</span><div><small>TU PERFIL</small><b>Listo para moverse</b></div></div><div className="pm7-profile-progress"><i/><span>72%</span></div><p>Sumá preferencias y disponibilidad para que el feed tenga más sentido.</p><Link href="/mi-postula-preview">Completar mi perfil</Link></div><div className="pm7-side-card"><span>CV</span><h3>Tres plantillas lindas siguen siendo gratis.</h3><p>Elegí color, editá y llevátelas en PDF o archivo editable.</p><Link href="/plantillas-preview">Ver plantillas →</Link></div><div className="pm7-side-card dark"><span>AHORA</span><h3>{jobs.length}+ oportunidades en el catálogo.</h3><p>Fuentes trazables, Buenos Aires primero y renovación periódica.</p><Link href="/empleos-preview">Abrir explorador →</Link></div></aside></div></section>

  <section className="pm7-changas-band"><div className="pm7-changas-head"><div><span className="pm7-eyebrow black">CHANGAS · NUEVO</span><h2>Una tarde libre también puede ser una oportunidad.</h2></div><p>Tareas cortas, trabajos por hora y pedidos concretos. Chat primero, pago claro y contexto antes de aceptar.</p></div><div className="pm7-changa-row">{previewGigs.slice(0,4).map((g,i)=><Link href="/changas-preview" key={g.id} className={`pm7-changa-mini g${i}`}><div className="pm7-changa-mini-img" style={{backgroundImage:`url(${g.image})`}}><span>{g.when}</span></div><div><small>{g.category}</small><h3>{g.title}</h3><div><b>{g.pay}</b><span>{g.duration}</span></div><p>{g.location}</p></div></Link>)}</div><div className="pm7-changas-cta"><Link href="/changas-preview" className="pm7-btn-black">Explorar changas</Link><span>Para tareas puntuales. No reemplaza relaciones laborales cuando corresponden.</span></div></section>

  <section className="pm7-motion"><div className="pm7-motion-media"><video autoPlay muted loop playsInline preload="metadata" poster="https://images.pexels.com/photos/466685/pexels-photo-466685.jpeg?auto=compress&cs=tinysrgb&w=1400"><source src="https://commons.wikimedia.org/wiki/Special:Redirect/file/Buenos_Aires_-_Argentina.webm" type="video/webm"/></video><div className="pm7-motion-badge"><i/>BUENOS AIRES EN MOVIMIENTO</div></div><div className="pm7-motion-copy"><span className="pm7-eyebrow lime">NO TODO EMPIEZA IGUAL</span><h2>Primer trabajo.<br/>Cambio de rubro.<br/>Una changa.<br/><em>Todo suma.</em></h2><p>La marca no debería hablarle sólo a gente con un CV perfecto. Queremos acompañar a quien necesita empezar, volver, probar algo nuevo o simplemente generar un ingreso esta semana.</p><div className="pm7-motion-quotes"><blockquote>“Busco algo cerca para poder estudiar y trabajar.”<span>— perfil joven · CABA</span></blockquote><blockquote>“Quiero cambiar de rubro sin sentir que arranco de cero.”<span>— perfil comercial · GBA</span></blockquote></div></div></section>

  <section className="pm7-social-proof"><div className="pm7-social-proof-head"><span className="pm7-eyebrow blue">SE SIENTE COMO UNA RED</span><h2>La conversación es parte del trabajo.</h2><p>Mensajes claros, perfiles humanos y acciones rápidas. El empleador también tiene un modo móvil para preguntar por candidatos sin abrir veinte pantallas.</p></div><div className="pm7-conversation-stage"><div className="pm7-phone-chat"><header><span>←</span><div className="pm7-chat-face">PM</div><p><b>Postulá Mejor</b><small>tu búsqueda</small></p><i/></header><div className="pm7-bubble incoming">Encontré 7 trabajos nuevos cerca de tu zona que coinciden con lo que marcaste.</div><div className="pm7-bubble outgoing">Mostrame los de ventas y atención.</div><div className="pm7-bubble incoming">Listo. Te dejé primero los que tienen horario compatible y fuente verificada.</div><div className="pm7-chat-compose"><span>＋</span><div>Escribí un mensaje…</div><b>↑</b></div></div><div className="pm7-floating-community"><article><span className="pm7-community-face a"/><div><b>Camila consiguió entrevista</b><small>Ventas · Belgrano · hace 12 min</small></div></article><article><span className="pm7-community-face b"/><div><b>Facu completó una changa</b><small>Mudanza · Almagro · hoy</small></div></article><article><span className="pm7-community-face c"/><div><b>Nuevo puesto cerca tuyo</b><small>Barista · Palermo · 1,8 km</small></div></article></div></div></section>

  <section className="pmv6-faq pm7-faq"><div className="pmv6-faq-inner"><div className="pmv6-faq-head"><div><span className="pm7-eyebrow lime">PREGUNTAS FRECUENTES</span><h2>Simple también significa claro.</h2></div><p>Qué es gratis, qué hace la IA, cómo funcionan las changas y qué pasa con tus datos.</p></div><div className="pmv6-faq-list"><details><summary>¿Postularme sigue siendo gratis?</summary><p>Sí. Buscar, guardar y postularte con las funciones básicas no requiere un plan pago. CV Pro+ y Búsqueda Activa agregan herramientas opcionales.</p></details><details><summary>¿Qué diferencia hay entre un empleo y una changa?</summary><p>Las changas están pensadas para tareas puntuales o trabajos breves. Cuando una relación por su realidad corresponde a empleo formal, la plataforma no debería disfrazarla como tarea independiente.</p></details><details><summary>¿La IA decide por mí?</summary><p>No. Puede ordenar, resumir, explicar coincidencias y ayudarte a preparar una postulación. No toma la decisión final de contratar o aceptar un trabajo.</p></details><details><summary>¿Puedo ver las plantillas Pro antes de pagar?</summary><p>Sí. Se muestran completas. El editor y la exportación premium se habilitan sólo cuando el servidor valida un plan vigente.</p></details><details><summary>¿Qué pasa con una recomendación laboral?</summary><p>Se trata como una señal general y verificable. No funciona como lista negra ni como descarte automático, y la persona debe poder verla y pedir revisión.</p></details></div></div></section>

  <section className="pm7-final"><div><span>POSTULÁ MEJOR</span><h2>Encontrar trabajo puede sentirse un poco más humano.</h2></div><div><Link href="/empleos-preview" className="pm7-btn-black">Empezar ahora</Link><Link href="/empresas-preview" className="pm7-btn-white">Soy empleador</Link></div></section>
  <PlatformFooter/><MobileNav active="inicio"/>
 </main>
}
