import Link from 'next/link'
import styles from './platform.module.css'
import {PlatformFooter,PlatformHeader,MobileNav} from './PlatformChrome'
import {getJobCatalog} from './jobs'
import './premium-v4.css'
import './premium-v5.css'

export const metadata={title:'Postulá Mejor | Empleo y selección con tecnología',description:'Buscá trabajo, mejorá tu perfil o contratá con una plataforma simple y asistida por IA.',robots:{index:false,follow:false}}
export const revalidate=21600

function initials(name:string){return name.split(/\s+/).filter(Boolean).slice(0,2).map(x=>x[0]).join('').toUpperCase()}

export default async function PostulaPreview(){
  const jobs=await getJobCatalog()
  const featured=jobs.slice(0,6)
  return <main className={`${styles.page} pmv4 pmv5-candidate`}>
    <PlatformHeader/>
    <section className="pmv4-hero"><div className="pmv4-hero-inner"><div><span className="pmv4-kicker">EMPLEO + TECNOLOGÍA QUE EXPLICA</span><h1>Que buscar trabajo<br/>vuelva a sentirse <em>posible.</em></h1><p className="pmv4-lead">Un lugar para encontrar oportunidades, presentarte mejor y saber qué conviene hacer después. Sin convertir la búsqueda en otra jornada de formularios.</p><div className="pmv4-actions"><Link href="/empleos-preview" className="pmv4-btn">Buscar empleo</Link><Link href="/empresas-preview" className="pmv4-btn-ghost">Necesito contratar</Link></div><div className="pmv4-hero-micro"><span><i/>Postularse es gratis</span><span><i/>Cuenta gratis para siempre</span><span><i/>Los planes vencen; tu historial queda</span></div></div><div className="pmv4-console" aria-label="Vista de producto"><div className="pmv4-console-head"><span>POSTULÁ MEJOR · SIGNAL DESK</span><span className="pmv4-live"><i/>ACTIVO</span></div><div className="pmv4-float one"><div className="pmv4-float-top"><span className="pmv4-bubble">CV</span><div><strong>Tu perfil está listo para comparar</strong><small>Experiencia, disponibilidad y preferencias</small></div><b>01</b></div><p>No te reducimos a una palabra clave. El sistema organiza lo que vos decidís compartir.</p></div><div className="pmv4-float two"><div className="pmv4-float-top"><span className="pmv4-bubble">IA</span><div><strong>Encontramos coincidencias explicables</strong><small>Sin descarte automático por datos sensibles</small></div><b>02</b></div><p>Te mostramos por qué una oportunidad puede servirte y qué requisito conviene revisar.</p></div><div className="pmv4-float three"><div className="pmv4-float-top"><span className="pmv4-bubble">GO</span><div><strong>Vos elegís cuándo avanzar</strong><small>Postulación simple o asistida</small></div><b>03</b></div><p>La tecnología prepara. La decisión sigue siendo tuya.</p></div></div></div></section>

    <section className="pmv4-section"><div className="pmv4-inner"><div className="pmv4-head"><div><span className="pmv4-label">DOS EXPERIENCIAS, UNA MISMA MARCA</span><h2>Entrá por lo que necesitás hoy.</h2></div><p>Candidato y empleador comparten identidad, pero no panel. Cada uno recibe una experiencia pensada alrededor de sus tareas reales.</p></div><div className="pmv4-dual"><Link href="/empleos-preview" className="pmv4-path candidate"><div className="pmv4-path-number">01</div><h3>Quiero encontrar trabajo.</h3><p>Ofertas por área y zona, CV reutilizable, guardados, seguimiento, plantillas y herramientas pagas sólo cuando realmente te aportan valor.</p><div className="pmv4-path-foot"><span>Cuenta gratuita · empezar ahora</span><span className="pmv4-arrow">→</span></div></Link><Link href="/empresas-preview" className="pmv4-path employer"><div className="pmv4-path-number">02</div><h3>Quiero contratar mejor.</h3><p>Publicación simple, filtros relevantes, shortlist explicada, roles para RRHH y agentes que absorben tareas repetitivas sin quitarte el control.</p><div className="pmv4-path-foot"><span>Publicar gratis · ver plataforma</span><span className="pmv4-arrow">→</span></div></Link></div></div></section>

    <section className="pmv4-section pmv4-jobs"><div className="pmv4-inner"><div className="pmv4-head"><div><span className="pmv4-label">CATÁLOGO VIVO</span><h2>{jobs.length}+ oportunidades para explorar ahora.</h2></div><p>La preview consulta fuentes públicas oficiales y prioriza Buenos Aires y Argentina. Renovamos el catálogo cada seis horas y siempre mostramos la fuente original.</p></div><div className="pmv4-job-grid">{featured.map(job=><Link href={`/empleos-preview/${job.slug}`} className="pmv4-job" key={job.slug}><div className="pmv4-job-top"><span className="pmv4-logo">{initials(job.company)}</span><div><b>{job.company}</b><small>{job.area}</small></div></div><h3>{job.title}</h3><div className="pmv4-job-tags"><span>{job.location}</span><span>{job.mode}</span><span>{job.schedule}</span></div><div className="pmv4-job-foot"><span><i/>Fuente oficial</span><strong>Ver oportunidad</strong></div></Link>)}</div><div className="pmv4-actions" style={{marginTop:22}}><Link href="/empleos-preview" className="pmv4-btn-dark">Ver todas las ofertas</Link><Link href="/mi-postula-preview" className="pmv4-btn-dark">Abrir mi tablero</Link></div></div></section>

    <section className="pmv4-section pmv4-value"><div className="pmv4-inner"><div className="pmv4-head"><div><span className="pmv4-label">CRECER SIN BLOQUEAR LO BÁSICO</span><h2>Gratis para buscar. Pago para hacer más y mejor.</h2></div><p>La cuenta no se elimina cuando vence un plan. Simplemente vuelve al nivel gratuito y conserva historial, datos y postulaciones.</p></div><div className="pmv4-flow"><article className="pmv4-step"><span>01</span><h3>Gratis</h3><p>Buscar, guardar, postularte, cargar tu CV, ver tu tablero y hacer seguimiento básico.</p></article><article className="pmv4-step"><span>02</span><h3>CV Pro+</h3><p>30 días con CV mejorado, plantillas premium, versiones y más herramientas de presentación.</p></article><article className="pmv4-step"><span>03</span><h3>Postulación inteligente</h3><p>Más volumen asistido, cartas personalizadas y explicación de compatibilidad sin enviar a ciegas.</p></article><article className="pmv4-step"><span>04</span><h3>Búsqueda Activa</h3><p>30 días con radar, seguimiento avanzado, preparación y automatizaciones bajo confirmación.</p></article></div></div></section>

    <section className="pmv4-final"><div className="pmv4-final-inner"><div><span className="pmv4-label" style={{color:'#eef1ff'}}>POSTULÁ MEJOR</span><h2>Tu próxima oportunidad no debería perderse entre pestañas.</h2></div><Link href="/empleos-preview" className="pmv4-btn">Empezar gratis</Link></div></section>
    <PlatformFooter/><MobileNav active="inicio"/>
  </main>
}
