'use client'

import Link from 'next/link'
import {FormEvent,useEffect,useState} from 'react'
import {useSearchParams} from 'next/navigation'
import {cvAuthClient} from '../cv-ia/cvAuth'
import styles from './platform.module.css'

const SIGNUP_TICKET_API='https://pejkycdttogpmmdntzuq.supabase.co/functions/v1/cv-ai-signup-ticket'
const REGISTER_API='https://pejkycdttogpmmdntzuq.supabase.co/functions/v1/cv-ai-register-verified'
function strongPassword(value:string){return value.length>=10&&/[a-z]/.test(value)&&/[A-Z]/.test(value)&&/[0-9]/.test(value)}
async function signupTicket(email:string){const r=await fetch(SIGNUP_TICKET_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos preparar el registro.');return String(d.signup_token||'')}
async function registerVerified(email:string,password:string,signup_token:string){const r=await fetch(REGISTER_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password,signup_token,role:'candidate',next:'/registro'})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos crear tu cuenta.');return d}
async function ensureProfile(token:string){await fetch('/api/postula/profile',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify({role:'candidate',source:'personal_access'})})}
async function welcome(token:string){try{await fetch('/api/postula/welcome',{method:'POST',headers:{Authorization:`Bearer ${token}`}})}catch{}}

export default function PersonalAccessForm({mode}:{mode:'signup'|'login'}){
 const params=useSearchParams();const reset=params.get('reset')==='1';const verified=params.get('verified')==='1'
 const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[newPassword,setNewPassword]=useState(''),[accepted,setAccepted]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('')
 useEffect(()=>{cvAuthClient().auth.getSession().then(async({data})=>{if(data.session&&verified){await ensureProfile(data.session.access_token);void welcome(data.session.access_token);location.replace('/mi-cuenta')}})},[verified])
 async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{const clean=email.trim().toLowerCase();if(mode==='signup'){if(!accepted)throw new Error('Para crear la cuenta necesitás aceptar los Términos y la Política de Privacidad.');if(!strongPassword(password))throw new Error('Usá al menos 10 caracteres, con mayúscula, minúscula y un número.');const ticket=await signupTicket(clean);await registerVerified(clean,password,ticket);setPassword('');setMessage(`Te enviamos un correo a ${clean}. Confirmalo para activar tu cuenta.`)}else{const {data,error}=await cvAuthClient().auth.signInWithPassword({email:clean,password});if(error)throw error;if(!data.session)throw new Error('No pudimos iniciar la sesión.');await ensureProfile(data.session.access_token);location.assign('/mi-cuenta')}}catch(e){setError(e instanceof Error?e.message:'No pudimos completar el acceso.')}finally{setBusy(false)}}
 async function forgot(){setError('');setMessage('');if(!email.trim()){setError('Escribí tu email primero.');return}try{const {error}=await cvAuthClient().auth.resetPasswordForEmail(email.trim().toLowerCase(),{redirectTo:'https://postulamejor.com/login?reset=1'});if(error)throw error;setMessage('Te enviamos un enlace para recuperar tu contraseña.')}catch(e){setError(e instanceof Error?e.message:'No pudimos enviar el recupero.')}}
 async function updatePassword(e:FormEvent){e.preventDefault();setBusy(true);setError('');try{if(!strongPassword(newPassword))throw new Error('Usá al menos 10 caracteres, con mayúscula, minúscula y un número.');const {error}=await cvAuthClient().auth.updateUser({password:newPassword});if(error)throw error;setMessage('Contraseña actualizada. Ya podés entrar a tu cuenta.');setNewPassword('')}catch(e){setError(e instanceof Error?e.message:'No pudimos cambiar la contraseña.')}finally{setBusy(false)}}
 if(reset)return <div className={`${styles.authCard} pm-employer-auth-card`}><span className="pm-employer-auth-kicker">POSTULÁ MEJOR</span><h2>Nueva contraseña</h2><p>Elegí una contraseña nueva para recuperar tu cuenta.</p><form className="pm-employer-auth-form" onSubmit={updatePassword}><label>Nueva contraseña<input type="password" value={newPassword} onChange={e=>setNewPassword(e.target.value)} autoComplete="new-password" required/></label><button className={styles.buttonDark} disabled={busy}>{busy?'Guardando…':'Guardar nueva contraseña'}</button></form>{message&&<div className="pm-employer-auth-message">{message}</div>}{error&&<div className="pm-employer-auth-error">{error}</div>}</div>
 return <div className={`${styles.authCard} pm-employer-auth-card`}><span className="pm-employer-auth-kicker">POSTULÁ MEJOR · PERSONAS</span><h2>{mode==='signup'?'Creá tu cuenta gratis':'Volvé a tu cuenta'}</h2><p>{mode==='signup'?'Una sola cuenta para buscar empleo, postularte, usar tu CV, conversar y participar en Trabajo Flex.':'Ingresá con tu email para volver a tus postulaciones, mensajes, CV y Trabajo Flex.'}</p><form className="pm-employer-auth-form" onSubmit={submit}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email" placeholder="tu@email.com" required/></label><label>Contraseña<input type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={mode==='signup'?'new-password':'current-password'} placeholder={mode==='signup'?'10+ caracteres, mayúscula y número':'Tu contraseña'} required/></label>{mode==='signup'&&<label className="pm-employer-auth-consent"><input type="checkbox" checked={accepted} onChange={e=>setAccepted(e.target.checked)}/><span>Acepto los <Link href="/terminos" target="_blank">Términos y Condiciones</Link> y la <Link href="/privacidad" target="_blank">Política de Privacidad</Link>.</span></label>}{mode==='login'&&<button type="button" onClick={forgot} style={{border:0,background:'transparent',padding:0,textAlign:'left',fontSize:12,fontWeight:850,cursor:'pointer'}}>Olvidé mi contraseña</button>}<button className={styles.buttonDark} disabled={busy}>{busy?(mode==='signup'?'Preparando cuenta…':'Ingresando…'):(mode==='signup'?'Crear mi cuenta':'Ingresar')}</button></form>{message&&<div className="pm-employer-auth-message">{message}</div>}{error&&<div className="pm-employer-auth-error">{error}</div>}<div className="pm-employer-auth-switch">{mode==='signup'?<>¿Ya tenés cuenta? <Link href="/login">Iniciar sesión</Link></>:<>¿Todavía no tenés cuenta? <Link href="/registro">Crear cuenta gratis</Link></>}</div></div>
}
