import type {PreviewJob} from './jobs'
const checkedAt='2026-08-22'
const req=['Revisar requisitos completos y vigencia en la fuente original','Confirmar horario, modalidad y ubicación antes de postularte','Postularse únicamente por el canal oficial de la empresa']
const make=(x:Omit<PreviewJob,'checkedAt'|'requirements'|'external'>):PreviewJob=>({...x,checkedAt,requirements:req,external:true})
const cencosud='https://cencosudarg.hiringroom.com/jobs'
const peya='https://empleos.pedidosya.com/jobs'
export const publicJobExtras:PreviewJob[]=[
 make({slug:'cencosud-senior-cajas-quilmes',title:'Senior de Cajas - Quilmes',company:'Cencosud',location:'Quilmes · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Oportunidad publicada por Cencosud para operación de cajas en Quilmes.',tags:['Cajas','Retail','Quilmes']}),
 make({slug:'cencosud-auxiliar-frutas-verduras-pilar',title:'Auxiliar de Frutas & Verduras - Tienda Makro',company:'Cencosud',location:'Pilar · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto operativo de tienda para el sector de frutas y verduras en Pilar.',tags:['Auxiliar','Supermercado','Pilar']}),
 make({slug:'cencosud-auxiliar-depostador-pilar',title:'Auxiliar Depostador',company:'Cencosud',location:'Pilar · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Búsqueda junior para tareas operativas de tienda en Pilar.',tags:['Auxiliar','Operaciones','Junior']}),
 make({slug:'cencosud-cajero-part-time-san-justo',title:'Cajero Part-Time - Tienda Makro',company:'Cencosud',location:'San Justo · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto de caja part time para tienda Makro en San Justo.',tags:['Cajero','Part time','San Justo']}),
 make({slug:'cencosud-depostador-carnicero-quilmes',title:'Auxiliar Depostador / Carnicero - Tienda Makro',company:'Cencosud',location:'Quilmes · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Oportunidad operativa para sector de tienda y carnicería en Quilmes.',tags:['Carnicería','Auxiliar','Retail']}),
 make({slug:'cencosud-auxiliar-almacen-benavidez',title:'Auxiliar de Almacén - Tienda Makro',company:'Cencosud',location:'Benavídez · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Tareas de almacén, depósito y expedición en tienda Makro de Benavídez.',tags:['Almacén','Depósito','Logística']}),
 make({slug:'cencosud-depostador-carnicero-benavidez',title:'Auxiliar Depostador / Carnicero - Tienda Makro',company:'Cencosud',location:'Benavídez · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto junior operativo de tienda en Benavídez.',tags:['Carnicería','Auxiliar','Benavídez']}),
 make({slug:'cencosud-frios-fiambres-benavidez',title:'Auxiliar Fríos y Fiambres - Tienda Makro',company:'Cencosud',location:'Benavídez · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto part time para el sector de fríos y fiambres de tienda.',tags:['Fiambres','Part time','Retail']}),
 make({slug:'cencosud-mantenimiento-olivos',title:'Auxiliar de Mantenimiento - Makro Olivos',company:'Cencosud',location:'Olivos · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Salud y Servicios',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Oportunidad junior de mantenimiento general para tienda en Olivos.',tags:['Mantenimiento','Junior','Olivos']}),
 make({slug:'cencosud-auxiliar-perdidas-haedo',title:'Auxiliar de Pérdidas - Makro',company:'Cencosud',location:'Haedo · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Salud y Servicios',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Posición operativa vinculada a prevención y control de pérdidas en tienda.',tags:['Seguridad','Retail','Haedo']}),
 make({slug:'cencosud-cajero-part-time-haedo',title:'Cajero Part Time - Tienda Makro',company:'Cencosud',location:'Haedo · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto de caja part time para tienda Makro en Haedo.',tags:['Cajero','Part time','Haedo']}),
 make({slug:'cencosud-mantenimiento-shopping-martinez',title:'Jefe de Mantenimiento Shopping',company:'Cencosud',location:'Martínez · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Búsqueda de mantenimiento para centro comercial en Martínez.',tags:['Mantenimiento','Shopping','Martínez']}),
 make({slug:'cencosud-desarrollo-clientes-cordoba',title:'Responsable de Desarrollo de Clientes - Makro',company:'Cencosud',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'A confirmar',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Oportunidad comercial para desarrollo de clientes en Córdoba.',tags:['Clientes','Comercial','Córdoba']}),
 make({slug:'cencosud-depostador-carnicero-cordoba',title:'Auxiliar Depostador / Carnicero - Makro',company:'Cencosud',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'A confirmar',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Puesto junior operativo en tienda Makro de Córdoba.',tags:['Carnicería','Junior','Córdoba']}),
 make({slug:'cencosud-prevencion-perdidas-cordoba',title:'Coordinador de Prevención de Pérdidas - Makro',company:'Cencosud',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'A confirmar',area:'Salud y Servicios',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Rol de coordinación para prevención de pérdidas y seguridad operativa.',tags:['Seguridad','Operaciones','Córdoba']}),
 make({slug:'cencosud-gerente-tienda-salta',title:'Gerente General de Tienda - Makro',company:'Cencosud',location:'Salta · Salta',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Gerencia general de tienda mayorista en Salta.',tags:['Retail','Gerencia','Salta']}),
 make({slug:'cencosud-coordinador-perecederos-salta',title:'Coordinador de Perecederos - Makro',company:'Cencosud',location:'Salta · Salta',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Cencosud · Hiring Room',sourceUrl:cencosud,summary:'Coordinación del sector de perecederos para tienda Makro.',tags:['Perecederos','Supermercado','Salta']}),
 make({slug:'pedidosya-sales-executive-buenos-aires',title:'Sales Executive',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Híbrido',schedule:'Full time',area:'Ventas y Comercial',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Oportunidad comercial para identificar y desarrollar nuevos partners.',tags:['Ventas','Partners','Híbrido']}),
 make({slug:'pedidosya-shift-supervisor-munro',title:'Shift Supervisor - Munro',company:'PedidosYa',location:'Munro · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'PedidosYa · Empleos',sourceUrl:'https://empleos.pedidosya.com/job/shift-supervisor-munro-in-munro-buenos-aires-province-argentina-jid-2373',summary:'Supervisión de turno para la operación de tienda, picking, recepción, inventario y coordinación del equipo.',tags:['Operaciones','Tienda','Munro']}),
 make({slug:'pedidosya-store-manager-buenos-aires',title:'Store Manager',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Gestión integral de tienda y coordinación de procesos administrativos y operativos.',tags:['Tienda','Operaciones','Management']}),
 make({slug:'pedidosya-quality-control-analyst',title:'Quality Control Analyst',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Control de recepción, cadena de frío y calidad de productos en la operación de mercados.',tags:['Calidad','Operaciones','Alimentos']}),
 make({slug:'pedidosya-field-operations-zona-sur',title:'Field Operations Supervisor - Zona Sur',company:'PedidosYa',location:'Zona Sur · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Supervisión de operaciones de quick commerce en Zona Sur.',tags:['Operaciones','Zona Sur','Supervisión']}),
 make({slug:'pedidosya-food-safety-analyst',title:'Food Safety Sr Analyst',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Híbrido',schedule:'Full time',area:'Salud y Servicios',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Gestión de calidad y seguridad alimentaria para la operación de mercados.',tags:['Alimentos','Calidad','Híbrido']}),
 make({slug:'pedidosya-performance-operations',title:'Performance Operations Sr. Analyst',company:'PedidosYa',location:'Buenos Aires · Argentina',mode:'Híbrido',schedule:'Full time',area:'Operaciones y Logística',source:'PedidosYa · Empleos',sourceUrl:peya,summary:'Seguimiento de indicadores operativos, productividad, inventarios y calidad de entrega.',tags:['Operaciones','Analista','Híbrido']}),
]
