import type {PreviewJob} from './jobs'

const checkedAt='2026-08-28'
const requirements=['Revisar requisitos completos y vigencia en la fuente original','Confirmar horario, modalidad y ubicación antes de postularte','Postularse únicamente por el canal indicado en la publicación']
const job=(data:Omit<PreviewJob,'checkedAt'|'requirements'|'external'>):PreviewJob=>({...data,checkedAt,requirements,external:true})

export const everydayPublicJobs:PreviewJob[]=[
  job({slug:'cotidiano-rex-repositor-cordoba',title:'Repositor',company:'Rex',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=0a803efc2ce364e7',summary:'Recepción y reposición de mercadería, control de stock, entrega de pedidos y atención al cliente en sucursal de Córdoba.',tags:['Reposición','Retail','Córdoba']}),
  job({slug:'cotidiano-rex-cajero-cordoba',title:'Cajero',company:'Rex',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'Full time · lunes a sábados',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=aeef561bc450e58c',summary:'Manejo de valores, arqueos, apertura y cierre de caja y cobros con distintos medios de pago en sucursal de Córdoba.',tags:['Caja','Retail','Córdoba']}),
  job({slug:'cotidiano-rex-vendedor-calle-cordoba',title:'Vendedor de calle',company:'Rex',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Rex · portal oficial',sourceUrl:'https://rex.hiringroom.com/jobs/get_vacancy/6a611f083f9a7a4c80494ee1?source=talent',summary:'Desarrollo de cartera, visitas comerciales, generación de oportunidades y seguimiento de ventas para la zona de Córdoba.',tags:['Ventas','Ferretería','Córdoba']}),
  job({slug:'cotidiano-minor-ayudante-cocina-cordoba',title:'Ayudante de Cocina',company:'Minor Hotels Europe & Americas',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'Temporario',area:'Gastronomía',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=ec99100de6cfeb87',summary:'Preparación de ingredientes, mise en place, apoyo a cocina y tareas de limpieza para operación hotelera en Córdoba.',tags:['Cocina','Hotelería','Córdoba']}),
  job({slug:'cotidiano-roga-mozo-cordoba',title:'Mozo/a de servicio de bar',company:'ROGA CHEF S.A',location:'Córdoba · Córdoba',mode:'Presencial',schedule:'Full time',area:'Gastronomía',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=8926d65d703ba6e8',summary:'Atención de mesas y mostrador, cobro, cafetería y apoyo general en servicios de bar de hospitales y universidades.',tags:['Mozo','Bar','Córdoba']}),
  job({slug:'cotidiano-rex-repositor-rosario',title:'Repositor',company:'Rex',location:'Rosario · Santa Fe',mode:'Presencial',schedule:'Full time · lunes a sábados',area:'Ventas y Comercial',source:'Rex · portal oficial',sourceUrl:'https://rex.hiringroom.com/jobs/get_vacancy/6a7097bd75540e6df34ae18f?source=linkedinjobs',summary:'Recepción y reposición de mercadería, control de pedidos, stock y atención al cliente en Rosario.',tags:['Reposición','Retail','Rosario']}),
  job({slug:'cotidiano-western-union-cajero-rosario',title:'Cajero/a',company:'Western Union',location:'Rosario · Santa Fe',mode:'Presencial',schedule:'Full time',area:'Atención al cliente',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=ef48c3e837a3e7aa',summary:'Atención al cliente, manejo y control de caja y comercialización de servicios financieros en Rosario.',tags:['Caja','Atención al cliente','Rosario']}),
  job({slug:'cotidiano-motos-vendedor-mostrador-rosario',title:'Vendedor técnico de mostrador',company:'Albertengo & Asociados S.R.L.',location:'Rosario · Santa Fe',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=13d069bf025aebb8',summary:'Venta y asesoramiento de repuestos y accesorios de motos, recepción de mercadería y atención al público en zona sur de Rosario.',tags:['Mostrador','Repuestos','Rosario']}),
  job({slug:'cotidiano-rex-repositor-santa-fe',title:'Repositor',company:'Rex',location:'Santa Fe · Santa Fe',mode:'Presencial',schedule:'Full time · lunes a sábados',area:'Ventas y Comercial',source:'Rex · portal oficial',sourceUrl:'https://rex.hiringroom.com/jobs/get_vacancy/6a75fa4280f3b72106da044a',summary:'Reposición, recepción de mercadería, control de stock y atención al cliente en sucursal de Santa Fe.',tags:['Reposición','Retail','Santa Fe']}),
  job({slug:'cotidiano-mirgor-vendedor-mendoza',title:'Vendedor',company:'Mirgor',location:'Mendoza · Mendoza',mode:'Presencial',schedule:'Full time / part time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=b82aaf38abd12bfd',summary:'Atención personalizada, ventas presenciales, facturación y control de stock para tiendas retail de Mendoza.',tags:['Ventas','Retail','Mendoza']}),
  job({slug:'cotidiano-minor-camarero-mendoza',title:'Camarero/a',company:'Minor Hotels Europe & Americas',location:'Mendoza · Mendoza',mode:'Presencial',schedule:'Temporario',area:'Gastronomía',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=f17bd021c42d2f6b',summary:'Servicio de alimentos y bebidas y atención de huéspedes para NH Mendoza Cordillera.',tags:['Camarero','Hotel','Mendoza']}),
  job({slug:'cotidiano-macowens-vendedor-salta',title:'Vendedor',company:'Macowens y Devré',location:'Salta · Salta',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=900af8f030c0b72c',summary:'Atención al público, venta de indumentaria, orden del local, salón, depósito y control de stock en Salta Capital.',tags:['Indumentaria','Local','Salta']}),
  job({slug:'cotidiano-grupo-jalil-planes-salta',title:'Asesor Comercial de Planes de Ahorro',company:'Grupo Jalil',location:'Salta · Salta',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=a544c4eaba615caf',summary:'Venta consultiva de planes de ahorro para vehículos, seguimiento comercial y cierre de operaciones en Salta.',tags:['Planes de ahorro','Automotriz','Salta']}),
  job({slug:'cotidiano-rex-repositor-neuquen',title:'Repositor',company:'Rex',location:'Neuquén · Neuquén',mode:'Presencial',schedule:'Full time · lunes a sábados',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=34e89eb3ccbc5bdf',summary:'Recepción y reposición de mercadería, control de pedidos y stock y atención al cliente en Neuquén.',tags:['Reposición','Retail','Neuquén']}),
  job({slug:'cotidiano-mirgor-vendedor-neuquen',title:'Vendedor',company:'Mirgor',location:'Neuquén · Neuquén',mode:'Presencial',schedule:'Full time / part time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=248cc00343e09410',summary:'Ventas presenciales, atención personalizada, facturación y control de stock en tiendas retail de Neuquén.',tags:['Ventas','Retail','Neuquén']}),
  job({slug:'cotidiano-rapsodia-vendedora-neuquen',title:'Vendedora - Alto Comahue',company:'Rapsodia',location:'Neuquén · Neuquén',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=1809148f411a592a',summary:'Asesoramiento personalizado y venta de indumentaria en la tienda Rapsodia de Alto Comahue.',tags:['Indumentaria','Shopping','Neuquén']}),
  job({slug:'cotidiano-rex-chofer-neuquen',title:'Chofer',company:'Rex',location:'Neuquén · Neuquén',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'Rex · portal oficial',sourceUrl:'https://rex.hiringroom.com/jobs/get_vacancy/6a7f6e3d19e1a3aacab20286',summary:'Transporte y entrega de mercadería, control de carga y apoyo operativo en sucursal de Neuquén.',tags:['Chofer','Logística','Neuquén']}),
  job({slug:'cotidiano-glex-recepcionista-hotel-caba',title:'Recepcionista de Hotel',company:'GLEX',location:'CABA · Buenos Aires',mode:'Presencial',schedule:'Turnos rotativos',area:'Turismo y Hotelería',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=e317e585a57e5ff6',summary:'Check-in y check-out, caja, facturación, atención telefónica y coordinación con housekeeping y mantenimiento en hotel boutique.',tags:['Recepción','Hotel','CABA']}),
  job({slug:'cotidiano-marriott-mucama-caba',title:'Mucama/o',company:'Marriott International',location:'CABA · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Turismo y Hotelería',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=5409c1ed15043cfb',summary:'Limpieza y mantenimiento de habitaciones y áreas comunes, reposición de carros y atención de pedidos de huéspedes.',tags:['Mucama','Housekeeping','CABA']}),
  job({slug:'cotidiano-arte-gourmet-ayudante-cocina-caba',title:'Sandwichero / Ayudante de Cocina',company:'ARTE GOURMET SRL',location:'Capital Federal · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Gastronomía',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=bcb5c3c4a2442955',summary:'Preparación de sándwiches, rellenos, mise en place, control de stock y apoyo general de cocina en panadería.',tags:['Ayudante de cocina','Panadería','CABA']}),
  job({slug:'cotidiano-la-pista-vendedor-ferreteria-benavidez',title:'Vendedor de salón',company:'La Pista Express',location:'Benavídez · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso público',sourceUrl:'https://ar.indeed.com/viewjob?jk=219f9a7c93df4ae6',summary:'Venta de mostrador y atención al público para sucursal vinculada a pinturería, ferretería y construcción en Benavídez.',tags:['Ferretería','Mostrador','Benavídez']}),
  job({slug:'cotidiano-adecco-playero-moreno',title:'Empleado de Estación de Servicio - Playero',company:'Adecco Argentina',location:'Moreno · Buenos Aires',mode:'Presencial',schedule:'Full time · contrato eventual',area:'Atención al cliente',source:'Adecco · aviso público',sourceUrl:'https://adeccoargentina.pandape.computrabajo.com/Detail/12113786',summary:'Atención en playa, carga de combustible, manejo de cobros, orden del sector y control de inventario en estación de servicio de Moreno.',tags:['Estación de servicio','Playero','Moreno']}),
  job({slug:'cotidiano-securion-guardia-mardel',title:'Guardia de Seguridad',company:'Securion',location:'Mar del Plata · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Otros rubros',source:'Securion · portal oficial',sourceUrl:'https://secarsecuritygroup.hiringroom.com/jobs/get_vacancy/6a8de4cb4aa1514c5c046812?source=linkedinjobs',summary:'Recepción, control de ingreso y egreso y rondines para servicios de seguridad en Mar del Plata.',tags:['Seguridad','Mar del Plata','Vigilancia']}),
  job({slug:'cotidiano-securion-guardia-comodoro',title:'Guardia de Seguridad',company:'Securion',location:'Comodoro Rivadavia · Chubut',mode:'Presencial',schedule:'Full time',area:'Otros rubros',source:'Securion · portal oficial',sourceUrl:'https://secarsecuritygroup.hiringroom.com/jobs/get_vacancy/6a8d90950e9102a5bbad0296?source=linkedinjobs',summary:'Control de accesos, rondines y tareas de vigilancia para servicios de seguridad en Comodoro Rivadavia.',tags:['Seguridad','Chubut','Comodoro Rivadavia']}),
  job({slug:'cotidiano-securion-guardia-caba',title:'Guardia de Seguridad - Zona CABA',company:'Securion',location:'Capital Federal · Argentina',mode:'Presencial',schedule:'Full time',area:'Otros rubros',source:'Securion · portal oficial',sourceUrl:'https://secarsecuritygroup.hiringroom.com/jobs/get_vacancy/6a8c4e7eaecd57940f6b779e?source=linkedinjobs',summary:'Recepción, control de ingresos y egresos, rondines y monitoreo de cámaras en servicios de seguridad de CABA.',tags:['Seguridad','CABA','Vigilancia']}),
  job({slug:'cotidiano-manpower-playero-leones',title:'Playero/a Vendedor/a Dual Eventual',company:'ManpowerGroup',location:'Leones · Córdoba',mode:'Presencial',schedule:'Turnos rotativos · eventual',area:'Atención al cliente',source:'Computrabajo · aviso público',sourceUrl:'https://ar.computrabajo.com/ofertas-de-trabajo/oferta-de-trabajo-de-playeroa-vendedora-dual-eventual-en-leones-cordoba-en-leones-67b5074dda6bd38961373e686dcf3405',summary:'Atención de clientes, carga y control de combustible, caja, stock y apoyo de tienda en estación de servicio de Leones.',tags:['Estación de servicio','Playero','Córdoba']}),
]
