import type {PreviewJob} from './jobs'

const checkedAt='2026-08-25'
const req=['Revisar requisitos completos y vigencia en el aviso original','Confirmar horario, modalidad y ubicación antes de postularte','Postularse únicamente por el canal indicado en la fuente original']
const job=(data:Omit<PreviewJob,'checkedAt'|'requirements'|'external'>):PreviewJob=>({...data,checkedAt,requirements:req,external:true})

export const commonPublicJobs:PreviewJob[]=[
 job({slug:'concreto-cocacola-repositor-fin-semana',title:'Repositor/a de Hiper & Super - Sábado y Domingo',company:'Coca-Cola FEMSA',location:'Buenos Aires · Buenos Aires',mode:'Presencial',schedule:'Part time · fin de semana',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=6916b247bf8b693e',summary:'Reposición y exhibición de productos en hipermercados y supermercados. La posición trabaja sábados y domingos y combina merchandising, rotación y atención en puntos de venta.',tags:['Reposición','Fin de semana','Retail']}),
 job({slug:'concreto-cencosud-cajero-san-justo',title:'Cajero Part-Time - San Justo (Makro)',company:'Cencosud',location:'San Justo · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=9b62741d12f4aa1d',summary:'Vacante de caja part time para tienda Makro en San Justo, con atención al cliente y operación habitual del sector de cajas.',tags:['Caja','Makro','Part time']}),
 job({slug:'concreto-cencosud-cajero-haedo',title:'Cajero Part Time - Tienda Makro (Haedo)',company:'Cencosud',location:'Haedo · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=cf4565d8f2ce1591',summary:'Vacante concreta para caja en tienda Makro de Haedo. El puesto es presencial y está orientado a atención y operación de cajas.',tags:['Caja','Makro','Haedo']}),
 job({slug:'concreto-itsm-operario-deposito-castelar',title:'Operario de Depósito - Zona Oeste',company:'ITSM Consulting',location:'Castelar · Buenos Aires',mode:'Presencial',schedule:'Full time · lunes a viernes',area:'Operaciones y Logística',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=fc5f604b345c0b61',summary:'Carga y descarga, recepción de mercadería, preparación de pedidos, control de stock y mantenimiento del depósito para una operación ubicada en Castelar.',tags:['Depósito','Zona Oeste','Logística']}),
 job({slug:'concreto-clarks-cajero-gastronomico',title:'Cajero Gastronómico',company:'Clarks',location:'Recoleta · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Gastronomía',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=daad329c2f059876',summary:'Puesto de cajero para operación gastronómica en Recoleta, orientado a manejo de caja y atención al público.',tags:['Caja','Gastronomía','Recoleta']}),
 job({slug:'concreto-el-mayorista-cajero-bella-vista',title:'Cajero/a de Sucursal - Bella Vista',company:'El Precio Mayorista',location:'Bella Vista · Buenos Aires',mode:'Presencial',schedule:'Part time',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=147282e1fe0e477e',summary:'Caja, atención al cliente, reposición y apoyo en salón para sucursal mayorista de Bella Vista.',tags:['Caja','Mayorista','Atención']}),
 job({slug:'concreto-prodental-recepcionista-berazategui',title:'Recepcionista Administrativa - Berazategui',company:'Prodental',location:'Berazategui · Buenos Aires',mode:'Presencial',schedule:'Full time · lunes a viernes',area:'Atención al cliente',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=4ef89de9af6f504c',summary:'Recepción de pacientes, agenda de turnos, llamadas, carga de datos, documentación y cobros para la sucursal de Berazategui.',tags:['Recepción','Administración','Berazategui']}),
 job({slug:'concreto-fleni-recepcionista-belgrano',title:'Recepcionista',company:'Fleni',location:'Belgrano · CABA',mode:'Presencial',schedule:'Full time · turno tarde',area:'Atención al cliente',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=9dfd9945fae23868',summary:'Atención de pacientes, gestión de turnos y consultas, carga de datos, prefacturación y manejo de agendas médicas en la sede Belgrano.',tags:['Recepción','Salud','Belgrano']}),
 job({slug:'concreto-taranto-operario-logistica-avellaneda',title:'Operario de Logística - Avellaneda',company:'Taranto',location:'Avellaneda · Buenos Aires',mode:'Presencial',schedule:'Full time · turnos rotativos',area:'Operaciones y Logística',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=b293d47511901b07',summary:'Operación logística en planta de Avellaneda. Se valora experiencia en depósito o almacenamiento y disponibilidad para tres turnos rotativos.',tags:['Logística','Operario','Avellaneda']}),
 job({slug:'concreto-rex-repositor-vicente-lopez',title:'Repositor',company:'Rex',location:'Vicente López · Buenos Aires',mode:'Presencial',schedule:'Full time · lunes a sábados',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=18cd33b25f226d60',summary:'Recepción y reposición de mercadería, control y entrega de pedidos, control de stock y atención al cliente en sucursal.',tags:['Reposición','Retail','Vicente López']}),
 job({slug:'concreto-rex-repositor-tortuguitas',title:'Repositor - Tortuguitas',company:'Rex',location:'Tortuguitas · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=d2b17abf0bf73344',summary:'Reposición, recepción de mercadería, control de pedidos y stock, más atención al cliente en la sucursal de Tortuguitas.',tags:['Reposición','Retail','Tortuguitas']}),
 job({slug:'concreto-popstore-cajero-vendedor-palermo',title:'Cajero-Vendedor',company:'Pop Store',location:'Palermo Hollywood · CABA',mode:'Presencial',schedule:'Full time / part time',area:'Ventas y Comercial',source:'Indeed · aviso individual',sourceUrl:'https://ar.indeed.com/viewjob?jk=9423e864a3d2406c',summary:'Atención en local, manejo de caja, reposición y orden del salón para un comercio de Palermo Hollywood.',tags:['Ventas','Caja','Palermo']}),
]