import type {PreviewJob} from './jobs'

const checkedAt='2026-08-21'
const commonRequirements=['Revisar los requisitos completos en la fuente antes de postularte','Confirmar horario, modalidad y vigencia del aviso','Postularse únicamente por los canales indicados por la fuente']
const indeed=(query:string,location='Buenos Aires')=>`https://ar.indeed.com/jobs?q=${encodeURIComponent(query)}&l=${encodeURIComponent(location)}`
const job=(data:Omit<PreviewJob,'checkedAt'|'requirements'|'external'>):PreviewJob=>({...data,checkedAt,requirements:commonRequirements,external:true})

export const currentJobBoost:PreviewJob[]=[
 job({slug:'actual-la-payada-auxiliar-cocina',title:'Auxiliar de Cocina (sin experiencia)',company:'La Payada',location:'Caballito · CABA',mode:'Presencial',schedule:'Turno tarde/noche',area:'Gastronomía',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Auxiliar de Cocina La Payada','Caballito, Buenos Aires'),summary:'Búsqueda para incorporarse a un local gastronómico de Caballito. El aviso actual prioriza puntualidad, compromiso y disponibilidad horaria.',tags:['Cocina','Sin experiencia','CABA']}),
 job({slug:'actual-amia-ayudante-cocina',title:'Ayudante de cocina',company:'AMIA',location:'Palermo · CABA',mode:'Presencial',schedule:'A confirmar',area:'Gastronomía',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Ayudante de cocina AMIA','Palermo, Buenos Aires'),summary:'Oportunidad de ayudante de cocina con tareas de mise en place, orden del sector y asistencia al equipo de cocina.',tags:['Cocina','Ayudante','Palermo']}),
 job({slug:'actual-innova-cocinero-produccion',title:'Cocinero de producción',company:'Innova Recursos Humanos',location:'Capital Federal · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Gastronomía',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Cocinero de producción Innova Recursos Humanos','Capital Federal, Buenos Aires'),summary:'Búsqueda orientada a cocina de producción para personas con experiencia previa en restaurantes u hoteles.',tags:['Cocinero','Producción','Gastronomía']}),
 job({slug:'actual-emplear-rh-cocina-salon',title:'Cocinero/a, Ayudante de cocina y Camareros',company:'Emplear RH',location:'Palermo · CABA',mode:'Presencial',schedule:'Full time',area:'Gastronomía',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-cocina-trabajo-l-capital-federal%2C-buenos-aires-empleos.html',summary:'Asador de Palermo con búsquedas activas para cocina y salón. Se valora experiencia gastronómica, organización y orientación al servicio.',tags:['Cocina','Camareros','Palermo']}),
 job({slug:'actual-minor-ayudante-cocina',title:'Ayudante de Cocina - Pool de talento',company:'Minor Hotels Europe & Americas',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Ayudante de Cocina Minor Hotels','Buenos Aires, Buenos Aires'),summary:'Convocatoria hotelera para perfiles que puedan asistir a supervisores y cocineros en tareas de preparación y operación de cocina.',tags:['Hotelería','Cocina','Hotel']}),
 job({slug:'actual-minor-vajillero',title:'Lavador/a de Vajilla - Pool de talento',company:'Minor Hotels Europe & Americas',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Lavador de Vajilla Minor Hotels','Buenos Aires, Buenos Aires'),summary:'Búsqueda hotelera para limpieza y mantenimiento de vajilla, equipos y sector de trabajo.',tags:['Hotelería','Vajilla','Cocina']}),
 job({slug:'actual-glex-recepcionista-hotel',title:'Recepcionista de Hotel',company:'GLEX',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'Turnos rotativos',area:'Turismo y Hotelería',source:'Indeed · aviso vigente',sourceUrl:'https://ar.indeed.com/viewjob?jk=e317e585a57e5ff6',summary:'Recepción hotelera con atención de huéspedes, check-in/check-out, caja, facturación y coordinación con housekeeping y mantenimiento.',tags:['Recepción','Hotelería','Atención al cliente']}),
 job({slug:'actual-minor-recepcionista',title:'Recepcionista - Pool de talento',company:'Minor Hotels Europe & Americas',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Recepcionista Minor Hotels','Buenos Aires, Buenos Aires'),summary:'Convocatoria para recepción hotelera y atención profesional de huéspedes durante ingreso, estadía y salida.',tags:['Recepción','Hotel','Turismo']}),
 job({slug:'actual-marriott-mucama',title:'Mucama/o',company:'Marriott International',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'Full time',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-mucama-l-puerto-madero%2C-buenos-aires-empleos.html',summary:'Posición de housekeeping para limpieza y preparación de habitaciones y espacios del hotel.',tags:['Housekeeping','Mucama','Hotelería']}),
 job({slug:'actual-minor-limpieza-hotel',title:'Personal de Limpieza - Pool de talento',company:'Minor Hotels Europe & Americas',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Personal de Limpieza Minor Hotels','Buenos Aires, Buenos Aires'),summary:'Búsqueda de personal para tareas de limpieza y mantenimiento de espacios hoteleros con cumplimiento de tiempos y estándares operativos.',tags:['Limpieza','Hotelería','Servicios']}),
 job({slug:'actual-minor-auditor-nocturno',title:'Auditor/a Nocturno/a - Pool de talento',company:'Minor Hotels Europe & Americas',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'Turno noche',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Auditor Nocturno Minor Hotels','Buenos Aires, Buenos Aires'),summary:'Convocatoria hotelera para tareas de recepción y control operativo durante el turno nocturno.',tags:['Hotelería','Turno noche','Recepción']}),
 job({slug:'actual-wyndham-reservas',title:'Ejecutivo/a de Reservas',company:'Wyndham Hotels & Resorts',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Turismo y Hotelería',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Ejecutivo de Reservas Wyndham','Buenos Aires, Buenos Aires'),summary:'Oportunidad en reservas hoteleras para gestionar consultas, disponibilidad y características de habitaciones y servicios.',tags:['Reservas','Hotelería','Atención al cliente']}),
 job({slug:'actual-cocacola-repositor',title:'Repositor/a de Hiper & Super - Sábado y Domingo',company:'Coca-Cola FEMSA',location:'Buenos Aires · GBA',mode:'Presencial',schedule:'Fin de semana',area:'Ventas y Comercial',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-Repositor-l-Buenos-Aires%2C-Buenos-Aires-empleos.html',summary:'Búsqueda de reposición y merchandising en hipermercados y supermercados, con foco en exhibición y disponibilidad de producto.',tags:['Repositor','Supermercado','Fin de semana']}),
 job({slug:'actual-cencosud-repositor-makro',title:'Repositor Full Time - Tienda Makro',company:'Cencosud',location:'Quilmes · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Repositor Full Time Tienda Makro Cencosud','Quilmes, Buenos Aires'),summary:'Posición de reposición full time para tienda mayorista, orientada a operación de salón y abastecimiento de mercadería.',tags:['Repositor','Retail','Quilmes']}),
 job({slug:'actual-caro-cuore-vendedora',title:'Vendedor/a de salón',company:'Caro Cuore',location:'CABA · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Ventas y Comercial',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Caro Cuore Vendedora CABA','Buenos Aires, Buenos Aires'),summary:'Búsqueda comercial para atención y venta en salón, con disponibilidad full time y francos rotativos.',tags:['Ventas','Salón','Retail']}),
 job({slug:'actual-popstore-cajero-vendedor',title:'Cajero/a - Vendedor/a',company:'Pop Store',location:'Palermo · CABA',mode:'Presencial',schedule:'Full time / part time',area:'Ventas y Comercial',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-vendedor-de-sal%C3%B3n-l-buenos-aires%2C-buenos-aires-empleos.html',summary:'Atención de local con tareas de ventas, caja, reposición y orden del salón.',tags:['Ventas','Caja','Atención al cliente']}),
 job({slug:'actual-itsm-operario-deposito',title:'Operario de Depósito - Zona Oeste',company:'ITSM Consulting',location:'Castelar · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Operaciones y Logística',source:'Indeed · aviso vigente',sourceUrl:'https://ar.indeed.com/viewjob?jk=fc5f604b345c0b61',summary:'Tareas de carga y descarga, recepción de mercadería, preparación de pedidos, control de stock y mantenimiento del depósito.',tags:['Depósito','Logística','Zona Oeste']}),
 job({slug:'actual-taranto-operario-logistica',title:'Operario de Logística',company:'Taranto',location:'Avellaneda · Buenos Aires',mode:'Presencial',schedule:'Turnos rotativos',area:'Operaciones y Logística',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Operario de Logística Taranto','Avellaneda, Buenos Aires'),summary:'Posición operativa de logística para planta, con disponibilidad para turnos rotativos.',tags:['Logística','Operario','Avellaneda']}),
 job({slug:'actual-pampa-empleado-deposito',title:'Empleado/a de Depósito',company:'PAMPA MAYORISTA',location:'San Fernando · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Empleado de deposito PAMPA MAYORISTA','San Fernando, Buenos Aires'),summary:'Búsqueda para organización y mantenimiento de depósito; se valora experiencia en logística, reposición o atención al público.',tags:['Depósito','Mayorista','Logística']}),
 job({slug:'actual-talent-operarios-planta',title:'Operarios Generales de Planta y Depósito',company:'Talent Solutions RRHH',location:'Tortuguitas · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Operarios Generales de Planta y Depósito Talent Solutions RRHH','Tortuguitas, Buenos Aires'),summary:'Oportunidad para tareas generales de planta, movimientos de stock y operación de depósito.',tags:['Operario','Planta','Depósito']}),
 job({slug:'actual-givaudan-abastecimiento',title:'Operaria/o - Abastecimiento',company:'Givaudan',location:'Buenos Aires · GBA',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-operaria-o-producci%C3%B3n-l-capital-federal%2C-buenos-aires-empleos.html?vjk=5b09b56f3c7702ce',summary:'Posición operativa de abastecimiento con tareas de estibado, etiquetado y preparación de producto terminado para despacho.',tags:['Producción','Abastecimiento','Operario']}),
 job({slug:'actual-umicore-operario-produccion',title:'Operario de Producción',company:'Umicore',location:'Pilar · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Operaciones y Logística',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Operario de Producción Umicore','Pilar, Buenos Aires'),summary:'Búsqueda de operario para procesos productivos bajo procedimientos de manufactura y buenas prácticas.',tags:['Producción','Operario','Pilar']}),
 job({slug:'actual-bfpb-administrativo',title:'Administrativo/a',company:'BFPB S.R.L.',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Administración y Asistencia',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-administrativo-jr-l-buenos-aires%2C-buenos-aires-empleos.html',summary:'Búsqueda administrativa para perfiles dinámicos con manejo de herramientas de oficina y planillas.',tags:['Administración','Office','Asistencia']}),
 job({slug:'actual-ciclosrh-asistente-administrativo',title:'Asistente Administrativo/a',company:'CiclosRH',location:'Capital Federal · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Administración y Asistencia',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Asistente Administrativo CiclosRH','Capital Federal, Buenos Aires'),summary:'Asistencia administrativa general, tareas de secretaría, recepción y soporte operativo de oficina.',tags:['Administración','Recepción','Asistente']}),
 job({slug:'actual-rrhhinsights-gestor-administrativo',title:'Gestor Administrativo',company:'RRHH INSIGHTS',location:'Buenos Aires · CABA',mode:'Presencial',schedule:'A confirmar',area:'Administración y Asistencia',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-gestor-administrativo-l-buenos-aires%2C-buenos-aires-empleos.html',summary:'Oportunidad de gestión administrativa y soporte de procesos para una empresa de soluciones de software.',tags:['Administración','Gestión','Oficina']}),
 job({slug:'actual-prodental-recepcionista-admin',title:'Recepcionista Administrativa',company:'Prodental',location:'Berazategui · Buenos Aires',mode:'Presencial',schedule:'Franquero/a',area:'Atención al cliente',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-recepci%C3%B3nista-l-capital-federal%2C-buenos-aires-empleos.html',summary:'Recepción y administración con atención al público para sucursal de Berazategui.',tags:['Recepción','Administración','Berazategui']}),
 job({slug:'actual-loncon-operario-limpieza',title:'Operario/a de Limpieza - Media Jornada',company:'LONCON SA',location:'Ramos Mejía · Buenos Aires',mode:'Presencial',schedule:'Media jornada',area:'Salud y Servicios',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-maestranza-limpieza-l-san-justo%2C-buenos-aires-empleos.html',summary:'Tareas de limpieza en oficinas, baños, salas de reuniones y espacios comunes en Zona Oeste.',tags:['Limpieza','Media jornada','Zona Oeste']}),
 job({slug:'actual-sitesa-supervisor-limpieza',title:'Supervisor/a operativo de Maestranza y Limpieza',company:'Sitesa S.R.L.',location:'Capital Federal · Buenos Aires',mode:'Presencial',schedule:'Full time',area:'Salud y Servicios',source:'Indeed · búsqueda vigente',sourceUrl:'https://ar.indeed.com/q-limpieza-maestranza-empleos.html',summary:'Supervisión y coordinación de servicios de limpieza, personal operativo y estándares de calidad.',tags:['Limpieza','Supervisor','Maestranza']}),
 job({slug:'actual-limpiolux-coordinador-limpieza',title:'Coordinador/a de Limpieza',company:'Limpiolux S.A.',location:'Tortuguitas · Buenos Aires',mode:'Presencial',schedule:'A confirmar',area:'Salud y Servicios',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Coordinador de limpieza Limpiolux','Tortuguitas, Buenos Aires'),summary:'Coordinación de personal y seguimiento diario de servicios de limpieza.',tags:['Limpieza','Coordinación','Tortuguitas']}),
 job({slug:'actual-santacatalina-confiteria',title:'Asistente de Confitería - Turno Tarde',company:'Santa Catalina Neurorehabilitación Clínica',location:'Balvanera · CABA',mode:'Presencial',schedule:'Turno tarde',area:'Gastronomía',source:'Indeed · búsqueda vigente',sourceUrl:indeed('Asistente de Confitería Santa Catalina','Balvanera, Buenos Aires'),summary:'Asistencia en preparación, despacho y reposición de productos de confitería, con atención cordial al público.',tags:['Confitería','Atención al cliente','Turno tarde']}),
]
