'use client'

import {FormEvent,useEffect,useRef,useState,type PointerEvent as ReactPointerEvent} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'

type Audience='candidate'|'employer'
type Ticket={id:string;category:string;priority:number;subject:string;status:string;last_message_at:string}
type Message={id:string;sender_kind:string;body:string;created_at:string}
const categories=[
 {id:'security_fraud',title:'Seguridad o posible estafa',copy:'Algo te resulta sospechoso, te pidieron dinero, claves o documentación.',tone:'urgent'},
 {id:'user_problem',title:'Problema con otro usuario',copy:'Conducta inapropiada, acoso, engaño o conflicto en un chat.',tone:'urgent'},
 {id:'payment',title:'Pago, plan o créditos',copy:'Cobros, planes, Mercado Pago o créditos de Servicios Flex.',tone:'high'},
 {id:'publishing',title:'Postulación o publicación',copy:'No podés postularte, publicar o gestionar una búsqueda.',tone:'high'},
 {id:'technical',title:'Problema técnico',copy:'Algo de la plataforma no carga, falla o se ve mal.',tone:'normal'},
 {id:'how_to',title:'Cómo usar Postulá Mejor',copy:'Necesitás orientación con alguna función.',tone:'normal'},
]
function statusLabel(status:string){if(status==='waiting_support')return'Esperando a soporte';if(status==='waiting_user')return'Esperando tu respuesta';if(status==='resolved')return'Resuelto';if(status==='closed')return'Cerrado';if(status==='open')return'Abierto';return status.replace(/_/g,' ')}
async function sessionHeader(){const {data}=await cvAuthClient().auth.getSession();return data.session?.access_token?{Authorization:`Bearer ${data.session.access_token}`}:{}}
export default function SupportHelp({audience}:{audience:Audience}){
 const [open,setOpen]=useState(false),[category,setCategory]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState(''),[tickets,setTickets]=useState<Ticket[]>([]),[active,setActive]=useState<Ticket|null>(null),[messages,setMessages]=useState<Message[]>([]),[companyId,setCompanyId]=useState<string|null>(null),[fabPos,setFabPos]=useState<{x:number;y:number}|null>(null)
 const fabRef=useRef<HTMLButtonElement|null>(null),dragRef=useRef<{pointerId:number;startX:number;startY:number;left:number;top:number;moved:boolean}|null>(null),blockClickRef=useRef(false)
 const storageKey=`pm-help-fab-pos-${audience}`
 function clampPos(x:number,y:number){const el=fabRef.current,w=el?.offsetWidth||64,h=el?.offsetHeight||64,pad=10;return{x:Math.max(pad,Math.min(window.innerWidth-w-pad,x)),y:Math.max(pad,Math.min(window.innerHeight-h-pad,y))}}
 useEffect(()=>{if(typeof window==='undefined'||!window.matchMedia('(max-width:720px)').matches)return;try{const raw=localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw);if(Number.isFinite(parsed?.x)&&Number.isFinite(parsed?.y))setFabPos(clampPos(Number(parsed.x),Number(parsed.y)))}}catch{}const onResize=()=>setFabPos(p=>p?clampPos(p.x,p.y):p);window.addEventListener('resize',onResize);window.visualViewport?.addEventListener('resize',onResize);return()=>{window.removeEventListener('resize',onResize);window.visualViewport?.removeEventListener('resize',onResize)}},[storageKey])
 useEffect(()=>{if(audience!=='employer')return;(async()=>{const h=await sessionHeader();if(!('Authorization' in h))return;const r=await fetch('/api/postula/company',{headers:h});const d=await r.json().catch(()=>({}));setCompanyId(d?.memberships?.[0]?.company_id||null)})()},[audience])
 async function loadTickets(){const h=await sessionHeader();if(!('Authorization' in h))return;const r=await fetch('/api/postula/support',{headers:h});const d=await r.json().catch(()=>({}));if(r.ok&&d?.ok)setTickets(d.tickets||[])}
 async function loadTicket(ticket:Ticket){const h=await sessionHeader();if(!('Authorization' in h))return;const r=await fetch(`/api/postula/support?ticket=${encodeURIComponent(ticket.id)}`,{headers:h});const d=await r.json().catch(()=>({}));if(r.ok&&d?.ok){setActive(d.ticket);setMessages(d.messages||[])}}
 useEffect(()=>{if(open)void loadTickets()},[open])
 function dragStart(e:ReactPointerEvent<HTMLButtonElement>){if(typeof window==='undefined'||!window.matchMedia('(max-width:720px)').matches)return;const rect=e.currentTarget.getBoundingClientRect();dragRef.current={pointerId:e.pointerId,startX:e.clientX,startY:e.clientY,left:rect.left,top:rect.top,moved:false};try{e.currentTarget.setPointerCapture(e.pointerId)}catch{}}
 function dragMove(e:ReactPointerEvent<HTMLButtonElement>){const d=dragRef.current;if(!d||d.pointerId!==e.pointerId)return;const dx=e.clientX-d.startX,dy=e.clientY-d.startY;if(Math.hypot(dx,dy)>5)d.moved=true;if(!d.moved)return;e.preventDefault();setFabPos(clampPos(d.left+dx,d.top+dy))}
 function dragEnd(e:ReactPointerEvent<HTMLButtonElement>){const d=dragRef.current;if(!d||d.pointerId!==e.pointerId)return;try{e.currentTarget.releasePointerCapture(e.pointerId)}catch{}if(d.moved){blockClickRef.current=true;setFabPos(p=>{if(p)try{localStorage.setItem(storageKey,JSON.stringify(p))}catch{}return p});window.setTimeout(()=>{blockClickRef.current=false},80)}dragRef.current=null}
 async function create(e:FormEvent){e.preventDefault();if(!category||message.trim().length<5||busy)return;setBusy(true);setNotice('');try{const h=await sessionHeader();if(!('Authorization' in h)){location.assign(`/acceso?next=${encodeURIComponent(location.pathname)}`);return}const r=await fetch('/api/postula/support',{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify({action:'create',audience,category,message:message.trim(),company_id:companyId,page_path:location.pathname+location.search})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos abrir el caso.');setMessage('');setCategory('');setNotice(d.ticket.priority<=1?'Consulta prioritaria enviada. Soporte la recibió y la revisará con prioridad.':'Consulta enviada. Soporte la recibió y responderá a la brevedad.');await loadTickets();await loadTicket(d.ticket)}catch(e){setNotice(e instanceof Error?e.message:'No pudimos abrir el caso.')}finally{setBusy(false)}}
 async function reply(e:FormEvent){e.preventDefault();if(!active||message.trim().length<2||busy)return;setBusy(true);try{const h=await sessionHeader();const r=await fetch('/api/postula/support',{method:'POST',headers:{'Content-Type':'application/json',...h},body:JSON.stringify({action:'message',ticket_id:active.id,message:message.trim()})});const d=await r.json().catch(()=>({}));if(!r.ok||!d?.ok)throw new Error(d?.error||'No pudimos enviar el mensaje.');setMessages(v=>[...v,d.message]);setActive(v=>v?{...v,status:'waiting_support'}:v);setMessage('');setNotice('Mensaje enviado. Soporte responderá a la brevedad.')}catch(e){setNotice(e instanceof Error?e.message:'No pudimos enviar el mensaje.')}finally{setBusy(false)}}
 return <>
  <button ref={fabRef} type="button" className="pm21-help-fab" data-pm-support-open data-pm-draggable-fab onPointerDown={dragStart} onPointerMove={dragMove} onPointerUp={dragEnd} onPointerCancel={dragEnd} onClick={()=>{if(!blockClickRef.current)setOpen(true)}} style={fabPos?{left:fabPos.x,top:fabPos.y,right:'auto',bottom:'auto',touchAction:'none'}:{touchAction:'none'}} aria-label="Abrir ayuda"><span>?</span><b>Ayuda</b></button>
  {open&&<div className="pm21-help-backdrop" role="dialog" aria-modal="true"><section className="pm21-help-panel"><header><div><span>SOPORTE POSTULÁ MEJOR</span><h2>{active?'Tu caso':'¿En qué te ayudamos?'}</h2><p>{active?'Podés continuar la conversación desde acá.':'Elegí la opción que mejor describa el problema. Los casos de seguridad se priorizan automáticamente.'}</p></div><button type="button" onClick={()=>{setOpen(false);setActive(null);setMessages([])}}>×</button></header>
   {!active?<><div className="pm21-help-cats">{categories.map(c=><button type="button" key={c.id} data-on={category===c.id} data-tone={c.tone} onClick={()=>setCategory(c.id)}><b>{c.title}</b><span>{c.copy}</span></button>)}</div><form onSubmit={create} className="pm21-help-compose"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Contanos brevemente qué pasó…" maxLength={3000}/><button disabled={busy||!category||message.trim().length<5}>{busy?'Enviando…':'Abrir caso con soporte'}</button></form>{tickets.length>0&&<div className="pm21-help-history"><b>Casos anteriores</b>{tickets.slice(0,4).map(t=><button type="button" key={t.id} onClick={()=>void loadTicket(t)}><span>{t.subject}</span><small>{statusLabel(t.status)}</small></button>)}</div>}</>:<><div className="pm21-help-ticket-meta"><span data-priority={active.priority}>{active.priority<=1?'Prioridad alta':'Caso de soporte'}</span><b>{active.subject}</b><small>{statusLabel(active.status)}</small></div><div className="pm21-help-thread">{messages.map(m=><article key={m.id} data-support={m.sender_kind!=='user'}><div><p>{m.body}</p><small>{new Date(m.created_at).toLocaleString('es-AR',{dateStyle:'short',timeStyle:'short'})}</small></div></article>)}</div><form onSubmit={reply} className="pm21-help-compose"><textarea value={message} onChange={e=>setMessage(e.target.value)} placeholder="Escribí una respuesta…" maxLength={3000}/><div><button type="button" className="secondary" onClick={()=>{setActive(null);setMessages([]);setMessage('')}}>Volver</button><button disabled={busy||message.trim().length<2}>{busy?'Enviando…':'Enviar'}</button></div></form></>}
   {notice&&<div className="pm21-help-notice">{notice}</div>}
  </section></div>}
 </>
}
