import type { Metadata } from 'next'
const icon='/postula-mejor-favicon.svg'
export const metadata:Metadata={metadataBase:new URL('https://postulamejor.com'),title:{absolute:'Términos | Postulá Mejor'},description:'Condiciones de uso de cuentas, empleos, Trabajos Flex, diagnósticos y herramientas de Postulá Mejor.',applicationName:'Postulá Mejor',robots:{index:false,follow:true},icons:{icon:[{url:icon,type:'image/svg+xml',sizes:'any'}],shortcut:icon,apple:icon}}
const box:React.CSSProperties={maxWidth:860,margin:'0 auto',padding:'40px 18px 80px',fontFamily:'Inter,system-ui,sans-serif',color:'#15171a',lineHeight:1.62};const h2:React.CSSProperties={fontSize:22,letterSpacing:'-.03em',marginTop:34};const p:React.CSSProperties={fontSize:14,color:'#555c66'};const note:React.CSSProperties={...p,background:'#f5f4ff',border:'1px solid #e4e0ff',borderRadius:14,padding:'14px 16px'}
export default function TermsPage(){return <main style={{background:'#fff',minHeight:'100vh'}}><article style={box}><a href="/" style={{color:'#5b49df',fontWeight:800,textDecoration:'none'}}>← Postulá Mejor</a><h1 style={{fontSize:42,lineHeight:1,letterSpacing:'-.055em',margin:'26px 0 12px'}}>Términos de uso</h1><p style={p}>Versión vigente: 21 de agosto de 2026.</p><p style={p}>Postulá Mejor es un producto digital de Llena Group, operado por Gabriel Alejandro Granvillano, CUIT 20-38422407-6. Al crear una cuenta, procesar un CV, postularte, publicar un empleo o utilizar Trabajos Flex aceptás estos Términos y la Política de Privacidad vigente.</p><p style={note}><b>Finalidad de la plataforma.</b> Postulá Mejor facilita búsqueda, publicación, selección, mensajería, herramientas de CV y coordinación entre usuarios. No es parte de los contratos laborales o acuerdos privados que los usuarios celebren entre sí.</p>
<h2 style={h2}>Cuentas, autoridad y credenciales</h2><p style={p}>El titular de una cuenta debe utilizar un email válido, custodiar sus credenciales y mantener sus datos actualizados. Las cuentas nuevas requieren confirmación del correo electrónico. Quien actúa en nombre de una empresa, comercio u organización declara contar con autorización suficiente y con una relación legítima con esa organización para administrar búsquedas y datos de candidatos.</p>
<h2 style={h2}>Responsabilidad de quien publica</h2><p style={p}>Quien publica un empleo, Trabajo Flex, perfil de empresa u otro contenido declara que la información es verdadera, que tiene derecho a publicarla y que cumple la normativa aplicable. La cuenta publicadora es responsable por condiciones ofrecidas, remuneración, obligaciones laborales, fiscales, contractuales, de seguridad e higiene, habilitaciones y cualquier otra obligación que corresponda.</p><p style={p}>Postulá Mejor puede revisar, limitar, pausar o retirar contenidos y suspender cuentas ante fraude, abuso, incumplimientos, denuncias fundadas o riesgos para terceros. La moderación no reemplaza las obligaciones de los usuarios ni convierte a la plataforma en empleador, contratante o parte del acuerdo.</p>
<h2 style={h2}>Empleos y procesos de selección</h2><p style={p}>Las ofertas deben corresponder a oportunidades reales, describir un único puesto de forma clara y utilizar criterios vinculados al trabajo. No se permiten requisitos discriminatorios, cobros previos injustificados, esquemas piramidales, captación engañosa, actividades ilícitas, ofertas que requieran una inversión del candidato ni pedidos de información sensible sin necesidad legítima.</p><p style={p}>Cuando una publicación se configura como confidencial, Postulá Mejor conserva internamente la identidad validada del empleador, mientras el público sólo ve la información reducida definida para ese aviso. La identidad puede revelarse cuando la empresa decide avanzar con el candidato según el flujo previsto.</p>
<h2 style={h2}>Uso de CV y datos de candidatos por empleadores</h2><p style={p}>Los CV, mensajes, datos de contacto y demás información de candidatos a la que acceda una empresa deben utilizarse exclusivamente para procesos de selección legítimos relacionados con la finalidad de la plataforma. Deben tratarse con reserva, limitarse a las personas del equipo que necesiten conocerlos y protegerse contra accesos no autorizados.</p><p style={p}>No está permitido revender, ceder o transferir datos de candidatos para finalidades ajenas a la selección; utilizarlos para publicidad, marketing o comunicaciones no solicitadas; recolectarlos de forma masiva; crear bases privadas paralelas de CV para usos futuros no relacionados con la postulación; ni utilizar automatizaciones para extraer información de la plataforma. Si detectamos un uso incompatible podremos limitar el acceso a datos, bloquear funcionalidades o suspender la cuenta.</p>
<h2 style={h2}>Trabajos Flex</h2><p style={p}>Trabajos Flex está destinado a tareas puntuales. No debe utilizarse para encubrir una relación laboral cuando por continuidad, dependencia u otras circunstancias corresponda otra figura jurídica. Quien publica debe indicar con claridad tarea, zona, horario cuando aplique, duración estimada, pago o forma de cálculo y requisitos de seguridad. Las partes deben acordar alcance y condiciones antes de comenzar.</p>
<h2 style={h2}>Mensajes, seguridad y reportes</h2><p style={p}>Los mensajes sirven para coordinar procesos de selección o tareas. No compartas contraseñas, códigos de autenticación, claves bancarias ni documentación sensible sin una razón legítima y un canal adecuado. Los usuarios pueden reportar estafas, conductas inapropiadas o contenido dudoso. Postulá Mejor puede conservar el reporte, la conversación relacionada y datos técnicos necesarios para investigar y aplicar medidas.</p>
<h2 style={h2}>Inteligencia artificial</h2><p style={p}>Las herramientas de IA ayudan a ordenar información, redactar, comparar evidencias y resumir. Sus resultados pueden contener errores y deben revisarse. No sustituyen deliberaciones humanas, no garantizan contratación y no deben utilizarse para discriminar sobre la base de características protegidas. Los porcentajes de compatibilidad son estimaciones explicables vinculadas a una búsqueda concreta, no una puntuación de valor personal.</p>
<h2 style={h2}>CV Pro y Búsqueda Activa</h2><p style={p}>CV Pro es un pago único según el precio publicado al contratar e incluye diagnóstico y materiales de mejora. Búsqueda Activa tiene vigencia limitada según la oferta vigente e incorpora adaptaciones y seguimiento. Los beneficios exactos, incluyendo créditos de Trabajo Flex, son los que se muestran al momento de la contratación.</p>
<h2 style={h2}>Planes de empresa, Nexo y créditos Flex</h2><p style={p}>Los planes de empresa habilitan diferentes límites y funciones. Nexo Móvil requiere como mínimo el plan Selección IA o uno superior, salvo funciones expresamente gratuitas de Trabajo Flex. Los créditos de Trabajo Flex pueden provenir de la cuenta, planes o packs independientes; al publicar se descuenta el crédito correspondiente. Los créditos incluidos en un plan pueden depender de la vigencia de ese plan.</p>
<h2 style={h2}>Pagos</h2><p style={p}>Los pagos se procesan mediante Mercado Pago. Un servicio pago se habilita cuando el servidor puede verificar la operación como aprobada por el importe y moneda esperados. Pagos pendientes, rechazados, cancelados o revertidos pueden no habilitar o pueden suspender el beneficio asociado.</p>
<h2 style={h2}>Privacidad, consentimientos y comunicaciones</h2><p style={p}>Al crear una cuenta y en determinados flujos de publicación solicitamos aceptación expresa de estos Términos y de la Política de Privacidad. Guardamos la versión, fecha y referencias necesarias para acreditar esa aceptación. Podemos enviar correos estrictamente operativos de confirmación, recupero, seguridad, soporte y cambios relevantes de la cuenta. Las comunicaciones promocionales y notificaciones opcionales se administran separadamente.</p>
<h2 style={h2}>Disponibilidad y limitación razonable</h2><p style={p}>El servicio se presta según disponibilidad y puede requerir mantenimiento. Postulá Mejor no garantiza entrevistas, contratación, ingresos, cantidad mínima de candidatos ni resultados específicos. Nada de estos Términos limita derechos que no puedan limitarse legalmente.</p>
<h2 style={h2}>Contacto</h2><p style={p}>Para soporte, seguridad, privacidad, publicaciones o pagos utilizá el botón Ayuda dentro de tu cuenta o escribí a hola@postulamejor.com.</p></article></main>}
