-- PREVIEW ONLY. Apply after approval together with the Comercio Lleno 2026-08-22 release.

alter table public.companies
  add column if not exists business_modules jsonb not null default jsonb_build_object(
    'fractional', jsonb_build_object('enabled',false,'units',jsonb_build_array('kg','g','litro','ml'),'decimals',3),
    'scale', jsonb_build_object('enabled',false,'mode','webserial','protocol','generic','baudRate',9600,'autoRead',true),
    'apparel', jsonb_build_object('enabled',false,'sizes',jsonb_build_array('XS','S','M','L','XL'),'colors',jsonb_build_array('Negro','Blanco'),'exchangeTicketDays',30,'trackLocation',true)
  );

alter table public.products add column if not exists sell_by_fraction boolean not null default false;
alter table public.products add column if not exists fraction_unit text;
alter table public.products add column if not exists scale_plu text;
alter table public.products add column if not exists parent_product_id uuid references public.products(id) on delete cascade;
alter table public.products add column if not exists apparel_size text;
alter table public.products add column if not exists apparel_color text;
alter table public.products add column if not exists inventory_location text;

alter table public.products drop constraint if exists products_fraction_unit_check;
alter table public.products add constraint products_fraction_unit_check check (fraction_unit is null or fraction_unit in ('kg','g','litro','ml'));
create index if not exists products_parent_variant_idx on public.products(company_id,branch_id,parent_product_id) where parent_product_id is not null;

create table if not exists public.quotes (
  id uuid primary key default gen_random_uuid(),
  company_id uuid not null references public.companies(id) on delete cascade,
  branch_id uuid not null,
  customer_id uuid references public.customers(id) on delete set null,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  quote_number bigint generated by default as identity,
  status text not null default 'open' check (status in ('open','accepted','expired','cancelled')),
  subtotal numeric(14,2) not null check (subtotal >= 0),
  discount_amount numeric(14,2) not null default 0 check (discount_amount >= 0),
  total numeric(14,2) not null check (total >= 0),
  valid_until date,
  items jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint quotes_branch_fkey foreign key(company_id,branch_id) references public.branches(company_id,id)
);

create index if not exists quotes_company_branch_created_idx on public.quotes(company_id,branch_id,created_at desc);
create index if not exists quotes_customer_idx on public.quotes(company_id,customer_id) where customer_id is not null;

alter table public.quotes enable row level security;
drop policy if exists quotes_branch_select on public.quotes;
drop policy if exists quotes_branch_insert on public.quotes;
drop policy if exists quotes_branch_update on public.quotes;
drop policy if exists quotes_branch_delete on public.quotes;
create policy quotes_branch_select on public.quotes for select to authenticated
  using (company_id=public.current_user_company_id() and public.can_access_branch(branch_id));
create policy quotes_branch_insert on public.quotes for insert to authenticated
  with check (company_id=public.current_user_company_id() and public.branch_has_permission(branch_id,'can_sell',array['cashier','seller','manager','supervisor']));
create policy quotes_branch_update on public.quotes for update to authenticated
  using (company_id=public.current_user_company_id() and public.branch_has_permission(branch_id,'can_sell',array['cashier','seller','manager','supervisor']))
  with check (company_id=public.current_user_company_id() and public.can_access_branch(branch_id));
create policy quotes_branch_delete on public.quotes for delete to authenticated
  using (company_id=public.current_user_company_id() and public.branch_has_permission(branch_id,'can_delete_sales','{}'::text[]));

grant select,insert,update,delete on public.quotes to authenticated;
grant usage,select on all sequences in schema public to authenticated;

-- Guardrail: quotes are intentionally stored outside public.sales. No stock, cash,
-- sales metrics or ARCA functions read this table, so creating a quote is non-fiscal
-- and has no operational accounting effect by construction.
