drop policy if exists companies_isolation on public.companies;
drop policy if exists companies_owner_update on public.companies;
create policy companies_owner_update on public.companies for update to authenticated using(id=public.current_user_company_id() and public.current_user_role()='owner') with check(id=public.current_user_company_id() and public.current_user_role()='owner');
revoke insert,delete,truncate,references,trigger on public.companies from authenticated;revoke all on public.companies from anon;grant select,update on public.companies to authenticated;

create or replace function public.protect_profile_sensitive_fields() returns trigger language plpgsql security definer set search_path=public,pg_temp as $$
declare v_uid uuid:=auth.uid();v_role text;v_company uuid;v_jwt_role text:=coalesce(current_setting('request.jwt.claim.role',true),(current_setting('request.jwt.claims',true)::jsonb->>'role'));
begin if v_jwt_role='service_role' then return new;end if;if v_uid is null then raise exception 'Usuario no autenticado';end if;select role,company_id into v_role,v_company from public.profiles where id=v_uid;if v_role='owner' and old.company_id=v_company then return new;end if;if new.company_id is distinct from old.company_id or new.role is distinct from old.role or new.permissions is distinct from old.permissions or new.active is distinct from old.active then raise exception 'No podés modificar tu rol, permisos, comercio o estado';end if;if new.id is distinct from old.id then raise exception 'No podés modificar el identificador del perfil';end if;return new;end;$$;
drop trigger if exists profiles_protect_sensitive_fields on public.profiles;create trigger profiles_protect_sensitive_fields before update on public.profiles for each row execute function public.protect_profile_sensitive_fields();revoke all on function public.protect_profile_sensitive_fields() from public,anon,authenticated;
revoke insert,delete,truncate,references,trigger on public.profiles from authenticated;revoke all on public.profiles from anon;grant select,update on public.profiles to authenticated;

drop policy if exists "authenticated users can manage company cash registers" on public.cash_registers;drop policy if exists cash_registers_company_isolation on public.cash_registers;drop policy if exists cash_registers_tenant_select on public.cash_registers;create policy cash_registers_tenant_select on public.cash_registers for select to authenticated using(company_id=public.current_user_company_id());revoke insert,update,delete,truncate,references,trigger on public.cash_registers from authenticated;revoke all on public.cash_registers from anon;grant select on public.cash_registers to authenticated;

drop policy if exists cash_movements_company_isolation on public.cash_movements;drop policy if exists cash_movements_authorized_select on public.cash_movements;drop policy if exists cash_movements_authorized_insert on public.cash_movements;create policy cash_movements_authorized_select on public.cash_movements for select to authenticated using(company_id=public.current_user_company_id() and(public.current_user_role()='owner' or public.comercio_has_permission('can_open_close_cash',false)));create policy cash_movements_authorized_insert on public.cash_movements for insert to authenticated with check(company_id=public.current_user_company_id() and(public.current_user_role()='owner' or public.comercio_has_permission('can_open_close_cash',false)));revoke update,delete,truncate,references,trigger on public.cash_movements from authenticated;revoke all on public.cash_movements from anon;grant select,insert on public.cash_movements to authenticated;
