'use client'

import Link from 'next/link'
import {useSearchParams} from 'next/navigation'
import styles from '../postula-preview/platform.module.css'

export default function AuthPreviewClient(){
 const params=useSearchParams();const role=params.get('rol')==='empresa'?'empresa':'candidato';const next=params.get('next')||(role==='empresa'?'/empresas-preview/panel':'/mi-postula-preview');const roleParam=role==='empresa'?'employer':'candidate'
 return <div className={styles.authGrid}><section className={styles.authVisual}><span className={styles.eyebrow}>{role==='empresa'?'Cuenta de empresa':'Cuenta de candidato'}</span><h1>{role==='empresa'?'Contratá con una cuenta que identifica a tu empresa.':'Tu búsqueda, guardada en un solo lugar.'}</h1><p>{role==='empresa'?'Empezá con email y contraseña. Después completás datos básicos de la empresa y podés invitar a RRHH con un rol separado.':'La cuenta es gratis y tarda segundos. Guardás perfil, CV, mensajes, búsquedas y postulaciones sin perderlas cuando vence un plan pago.'}</p><div className={styles.heroMicro}><span><i/>Acceso protegido</span><span><i/>Datos bajo tu control</span><span><i/>Sin tarjeta para registrarte</span></div></section><section className={styles.authCardWrap}><div className={styles.authCard}><span className={styles.miniLabel}>Postulá Mejor</span><h2>{role==='empresa'?'Crear cuenta de empleador':'Crear mi cuenta gratis'}</h2><p>Email + contraseña. Nada más para entrar; el resto del perfil lo completás después.</p><Link className={styles.buttonDark} style={{width:'100%'}} href={`/cuenta?modo=crear&role=${roleParam}&next=${encodeURIComponent(next)}`}>Continuar con email y contraseña</Link><div className={styles.divider}>o</div><button className={styles.google} disabled title="Se habilita en la etapa de conexión de Google">Continuar con Google · próxima conexión</button>{role==='empresa'&&<div className={styles.securityBadge}><b>Publicar requiere una validación básica de empresa.</b><br/>Pedimos datos de contacto, ciudad, actividad y señales simples de identidad. No exigimos constancia fiscal para empezar.</div>}<p style={{fontSize:11,marginTop:18}}>Al crear la cuenta te pedimos aceptar expresamente los Términos, la Política de Privacidad y el tratamiento de datos necesario para operar la plataforma. <Link href="/legales">Ver legales</Link>.</p><Link href="/postula-preview" style={{fontSize:11,fontWeight:850}}>← Volver</Link></div></section></div>
}
