'use client'

import Link from 'next/link'
import {useSearchParams} from 'next/navigation'
import {useState} from 'react'
import {cvAuthClient} from '../cv-ia/cvAuth'
import styles from '../postula-preview/platform.module.css'

export default function AuthPreviewClient(){const params=useSearchParams();const role=params.get('rol')==='empresa'?'empresa':'candidato';const next=params.get('next')||(role==='empresa'?'/empresas-preview/panel':'/mi-postula-preview');const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function google(){setBusy(true);setError('');try{const redirect=`${window.location.origin}${next}`;const {error}=await cvAuthClient().auth.signInWithOAuth({provider:'google',options:{redirectTo:redirect}});if(error)throw error}catch(e){setError(e instanceof Error?e.message:'No pudimos iniciar con Google.');setBusy(false)}}return <div className={styles.authGrid}><section className={styles.authVisual}><span className={styles.eyebrow}>{role==='empresa'?'Cuenta de empresa':'Cuenta de candidato'}</span><h1>{role==='empresa'?'Contratá con una cuenta verificada.':'Tu búsqueda, guardada en un solo lugar.'}</h1><p>{role==='empresa'?'El acceso puede comenzar con Google o email. Antes de publicar búsquedas nativas, la empresa pasa por una capa de verificación para reducir fraude y suplantaciones.':'Guardá empleos, reutilizá tu CV, seguí postulaciones y activá herramientas según tu plan. Crear la cuenta es gratis.'}</p><div className={styles.heroMicro}><span><i/>Acceso protegido</span><span><i/>Datos bajo tu control</span><span><i/>Sin tarjeta para registrarte</span></div></section><section className={styles.authCardWrap}><div className={styles.authCard}><span className={styles.miniLabel}>Postulá Mejor</span><h2>{role==='empresa'?'Ingresar como empleador':'Entrar a mi cuenta'}</h2><p>Usá el acceso más cómodo. El perfil queda separado según el rol que elegís.</p><button className={styles.google} onClick={google} disabled={busy}>{busy?'Abriendo Google…':'Continuar con Google'}</button><div className={styles.divider}>o</div><Link className={styles.buttonDark} style={{width:'100%'}} href={`/cuenta?next=${encodeURIComponent(next)}`}>Continuar con email y contraseña</Link>{role==='empresa'&&<div className={styles.securityBadge}><b>Verificación adicional para empleadores.</b><br/>El panel incorpora estado de empresa, roles internos, auditoría y una etapa de validación antes de publicar de forma nativa.</div>}{error&&<div className={styles.securityBadge} style={{color:'#9b2d32'}}>{error}</div>}<p style={{fontSize:11,marginTop:18}}>Al continuar aceptás las condiciones y la política de privacidad aplicables al rol. <Link href="/postula-preview">Volver</Link></p></div></section></div>}
