import {NextRequest,NextResponse} from 'next/server'
import {createClient} from '@supabase/supabase-js'
const URL='https://pejkycdttogpmmdntzuq.supabase.co',KEY='sb_publishable_JmqxkVG1qNuCwWfqMeVgBg_-Nn32N2I'
function db(req:NextRequest){const auth=req.headers.get('authorization')||'';return createClient(URL,KEY,{auth:{persistSession:false,autoRefreshToken:false},global:{headers:{Authorization:auth}}})}
const txt=(v:unknown,n=180)=>String(v??'').trim().slice(0,n)
async function hash(v:string){const raw=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(v));return Array.from(new Uint8Array(raw),x=>x.toString(16).padStart(2,'0')).join('')}
function token(){const a=new Uint8Array(24);crypto.getRandomValues(a);return Array.from(a,x=>x.toString(16).padStart(2,'0')).join('')}
export async function GET(req:NextRequest){const c=db(req);const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({ok:false,error:'Iniciá sesión.'},{status:401});const company=req.nextUrl.searchParams.get('company')||'';const [{data:members,error:mErr},{data:invites,error:iErr}]=await Promise.all([c.from('pm_company_members').select('company_id,user_id,role,status,created_at').eq('company_id',company),c.from('pm_company_invites').select('id,email,role,status,expires_at,created_at').eq('company_id',company).order('created_at',{ascending:false})]);if(mErr||iErr)return NextResponse.json({ok:false,error:mErr?.message||iErr?.message},{status:403});return NextResponse.json({ok:true,members:members||[],invites:invites||[]})}
export async function POST(req:NextRequest){const c=db(req);const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({ok:false,error:'Iniciá sesión.'},{status:401});const b=await req.json().catch(()=>({})),company=txt(b?.company_id,80),email=txt(b?.email,180).toLowerCase(),role=txt(b?.role,40);if(!/^\S+@\S+\.\S+$/.test(email)||!['admin','recruiter','hiring_manager','viewer'].includes(role))return NextResponse.json({ok:false,error:'Email o rol inválido.'},{status:400});const raw=token(),tokenHash=await hash(raw);const {data,error}=await c.from('pm_company_invites').insert({company_id:company,email,role,token_hash:tokenHash,invited_by:user.id}).select('id,email,role,status,expires_at').single();if(error)return NextResponse.json({ok:false,error:error.message},{status:403});return NextResponse.json({ok:true,invite:data,invite_url:`/empresas-preview/invitacion?token=${raw}`})}
export async function PATCH(req:NextRequest){const c=db(req);const {data:{user}}=await c.auth.getUser();if(!user)return NextResponse.json({ok:false,error:'Iniciá sesión.'},{status:401});const b=await req.json().catch(()=>({})),company=txt(b?.company_id,80),member=txt(b?.user_id,80),role=txt(b?.role,40),status=txt(b?.status,20);if(!['owner','admin','recruiter','hiring_manager','viewer'].includes(role)||!['active','disabled'].includes(status))return NextResponse.json({ok:false,error:'Rol o estado inválido.'},{status:400});const {data,error}=await c.from('pm_company_members').update({role,status}).eq('company_id',company).eq('user_id',member).select('*').single();if(error)return NextResponse.json({ok:false,error:error.message},{status:403});return NextResponse.json({ok:true,member:data})}
