import type {Metadata} from 'next'

export const metadata:Metadata={metadataBase:new URL('https://postulamejor.com'),title:{absolute:'Términos de Servicios Flex | Postulá Mejor'},description:'Reglas específicas para publicar y acordar tareas puntuales mediante Servicios Flex.',robots:{index:true,follow:true},alternates:{canonical:'https://postulamejor.com/terminos/servicios-flex'}}
const box:React.CSSProperties={maxWidth:900,margin:'0 auto',padding:'42px 18px 90px',fontFamily:'Inter,system-ui,sans-serif',color:'#15171a',lineHeight:1.62};const h2:React.CSSProperties={fontSize:23,letterSpacing:'-.03em',marginTop:34};const p:React.CSSProperties={fontSize:14,color:'#535b66'};const note:React.CSSProperties={...p,background:'#f3ffcf',border:'1px solid #d8ee91',borderRadius:16,padding:'15px 17px'};const warn:React.CSSProperties={...p,background:'#fff2ee',border:'1px solid #ffd0c7',borderRadius:16,padding:'15px 17px'}

export default function ServicesFlexTerms(){return <main style={{background:'#fff',minHeight:'100vh'}}><article style={box}>
 <a href="/servicios-flex" style={{color:'#5b49df',fontWeight:850,textDecoration:'none'}}>← Servicios Flex</a>
 <h1 style={{fontSize:43,lineHeight:1,letterSpacing:'-.055em',margin:'26px 0 12px'}}>Términos específicos de Servicios Flex</h1>
 <p style={p}>Versión vigente: 25 de agosto de 2026. Estos términos complementan los Términos generales y la Política de Privacidad de Postulá Mejor.</p>
 <p style={note}><b>Qué es Servicios Flex.</b> Es una herramienta de contacto para tareas concretas y servicios independientes con principio y fin definidos. “Servicios Flex” es un nombre comercial de una funcionalidad de la plataforma y no crea una categoría jurídica propia ni modifica la naturaleza real de una relación.</p>
 <h2 style={h2}>1. Rol de Postulá Mejor</h2><p style={p}>Postulá Mejor facilita la publicación, visualización y mensajería entre usuarios. No es empleador del prestador, no contrata el servicio en nombre de quien publica, no representa a ninguna de las partes y no se convierte en parte del acuerdo privado por el solo uso de la plataforma. La persona que solicita el servicio y quien decide prestarlo deben definir entre sí el alcance, fecha, lugar, materiales, importe y demás condiciones.</p>
 <h2 style={h2}>2. Cuándo corresponde usar Servicios Flex</h2><p style={p}>La sección está pensada para una tarea u obra puntual, autónoma y delimitada. Antes de publicar se realiza una clasificación preventiva. Si las respuestas indican continuidad habitual, cobertura de un puesto, horario permanente, órdenes o supervisión propias de una organización, u otras señales incompatibles con un servicio independiente, la plataforma puede impedir la publicación como Servicio Flex y derivar al módulo de Empleos.</p><p style={warn}><b>Importante.</b> La denominación elegida por los usuarios no prevalece sobre la realidad de la prestación. Si por sus características corresponde una relación laboral, deben cumplirse las obligaciones laborales y de registración aplicables.</p>
 <h2 style={h2}>3. Casas particulares, cuidado y tareas domésticas</h2><p style={p}>Las tareas de limpieza, mantenimiento, asistencia personal, acompañamiento o cuidado realizadas dentro de una casa particular o del ámbito familiar pueden estar alcanzadas por el Régimen Especial de Contrato de Trabajo para el Personal de Casas Particulares, incluso cuando la prestación sea por pocas horas. Cuando el clasificador indique ese supuesto, Servicios Flex no habilita la publicación como servicio independiente.</p><p style={p}><a href="https://www.argentina.gob.ar/servicio/registrar-al-personal-de-casas-particulares" target="_blank" rel="noreferrer">Información oficial sobre registración de personal de casas particulares →</a></p>
 <h2 style={h2}>4. Reparto y movilidad</h2><p style={p}>Los servicios de reparto de bienes y movilidad de personas coordinados mediante plataformas tecnológicas tienen un régimen específico en Argentina. Por el momento Postulá Mejor no habilita esas actividades dentro de Servicios Flex. La exclusión puede revisarse si la plataforma implementa específicamente los requisitos correspondientes.</p>
 <h2 style={h2}>5. Mayoría de edad</h2><p style={p}>Para publicar, ofrecerse o acordar un Servicio Flex dentro de esta sección se requiere ser mayor de 18 años. Las reglas especiales sobre trabajo adolescente no se gestionan mediante Servicios Flex.</p>
 <h2 style={h2}>6. Importe y pagos entre las partes</h2><p style={p}>El importe del servicio se acuerda directamente entre quien solicita y quien presta. Postulá Mejor no recibe, retiene, custodia, administra ni libera el dinero pactado por el servicio y no actúa como escrow o garantía de pago. Los pagos que Postulá Mejor pueda procesar mediante Mercado Pago corresponden exclusivamente a planes, herramientas o créditos de publicación de la plataforma.</p><p style={p}>Las partes son responsables de acordar la forma y momento de pago, conservar los comprobantes que correspondan y resolver entre sí cualquier diferencia vinculada con la ejecución del servicio, sin perjuicio de los mecanismos de reporte o asistencia que ofrezca la plataforma.</p>
 <h2 style={h2}>7. Obligaciones fiscales y comprobantes</h2><p style={p}>Cada usuario es responsable de determinar sus obligaciones fiscales, de facturación, registración, aportes, seguros o habilitaciones según su actividad y situación concreta. Cuando una prestación sea independiente y corresponda emitir recibo o factura, hacerlo puede ser relevante para documentar correctamente la relación. Postulá Mejor no determina la condición tributaria de los usuarios ni brinda asesoramiento contable individual.</p>
 <h2 style={h2}>8. Actividades profesionales, permisos y seguridad</h2><p style={p}>No se puede utilizar Servicios Flex para ofrecer actividades ilegales, peligrosas, fraudulentas o que exijan matrícula, habilitación, licencia, seguro o autorización que el prestador no posea. Quien publica debe informar riesgos relevantes, condiciones del lugar y materiales necesarios. Quien presta debe evaluar si cuenta con capacidad, elementos y cobertura adecuados antes de aceptar.</p>
 <h2 style={h2}>9. Conductas prohibidas</h2><p style={p}>No se permiten fraude, estafas, esquemas piramidales, suplantación de identidad, explotación, acoso, discriminación, servicios sexuales, armas, drogas, actividades ilícitas, pedidos injustificados de claves o documentación sensible, cobros engañosos, ni publicaciones destinadas a encubrir empleo no registrado. Postulá Mejor puede pausar, retirar o revisar publicaciones y suspender cuentas ante señales razonables de riesgo.</p>
 <h2 style={h2}>10. Identidad, verificaciones y reportes</h2><p style={p}>Las señales de identidad, verificación o historial reducen incertidumbre pero no constituyen una garantía absoluta sobre una persona, empresa, capacidad profesional o resultado. Ante una conducta sospechosa, fraude, riesgo o contenido que parezca incumplir estas reglas, utilizá Ayuda dentro de la plataforma o escribí a hola@postulamejor.com.</p>
 <h2 style={h2}>11. Créditos de publicación</h2><p style={p}>Los créditos de Servicios Flex habilitan publicaciones dentro de la plataforma y son independientes del importe del servicio. Los créditos gratuitos incluidos en la cuenta pueden renovarse y vencer según las reglas informadas en pantalla. Los créditos adquiridos mediante pago se rigen por las condiciones mostradas al comprarlos.</p>
 <h2 style={h2}>12. Responsabilidad y derechos de los usuarios</h2><p style={p}>Postulá Mejor no garantiza que una publicación reciba respuestas, que las partes lleguen a un acuerdo ni un resultado determinado del servicio. Estas reglas no excluyen ni limitan derechos que legalmente no puedan ser excluidos o limitados. La plataforma procurará brindar información clara sobre su rol y sobre los riesgos relevantes del uso de Servicios Flex.</p>
 <h2 style={h2}>13. Revisión del encuadre</h2><p style={p}>La clasificación previa es una medida preventiva basada en las respuestas del usuario y no sustituye un análisis jurídico, laboral, fiscal o profesional del caso concreto. Si tenés dudas sobre el encuadre de una actividad, corresponde consultar a un profesional competente antes de acordarla.</p>
 <p style={{...note,marginTop:36}}><b>Resumen operativo:</b> tarea puntual e independiente → Servicios Flex. Puesto habitual, continuidad o dependencia → Empleos. Tareas comprendidas en casas particulares → régimen específico. Reparto o movilidad mediante plataforma → no habilitados por ahora. Pago del servicio → directamente entre las partes.</p>
 </article></main>}
