import Link from 'next/link'
import {notFound} from 'next/navigation'
import styles from '../../postula-preview/platform.module.css'
import {PlatformHeader,PlatformFooter,MobileNav} from '../../postula-preview/PlatformChrome'
import {getPreviewJob,previewJobs} from '../../postula-preview/jobs'

export function generateStaticParams(){return previewJobs.map(job=>({slug:job.slug}))}
export const dynamicParams=false

export default async function JobDetail({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const job=getPreviewJob(slug);if(!job)notFound();return <main className={styles.page}><PlatformHeader/><section className={styles.detailHero}><div className={styles.detailHeroInner}><div className={styles.breadcrumbs}><Link href="/empleos-preview">Empleos</Link><span>/</span><span>{job.company}</span></div><span className={styles.eyebrow}>{job.company} · oferta externa verificada</span><h1>{job.title}</h1><div className={styles.detailMeta}><span>{job.location}</span><span>{job.mode}</span><span>{job.schedule}</span><span>{job.area}</span></div></div></section><div className={styles.detailLayout}><div className={styles.contentCard}><h2>Sobre la oportunidad</h2><p>{job.summary}</p><h2 style={{marginTop:28}}>Lo que conviene revisar antes de postularte</h2><ul>{job.requirements.map(r=><li key={r}>{r}</li>)}</ul><h2 style={{marginTop:28}}>Cómo te ayuda Postulá Mejor</h2><p>Podés preparar un paquete con tu CV, una presentación breve y respuestas clave. Para esta oferta externa, el envío final se hace en la página oficial de {job.company}. Cuando la búsqueda sea publicada por una empresa dentro de Postulá Mejor, vas a poder completar todo el proceso sin salir.</p><div className={styles.aiNote}><b>Match transparente.</b> El porcentaje que ves en esta previa es una señal orientativa de producto. La versión funcional utilizará información que vos autorices de tu perfil y requisitos explícitos del puesto, mostrando por qué existe cada coincidencia.</div></div><aside className={styles.sideCard}><span className={styles.miniLabel}>Canal de postulación</span><h2 style={{margin:'7px 0 4px'}}>Prepará todo antes de salir.</h2><p style={{fontSize:13,lineHeight:1.55,color:'#657788'}}>Guardá tu CV elegido, carta breve y respuestas. Después continuás en la fuente oficial.</p><Link href={`/postulacion-preview/${job.slug}`} className={styles.button}>Preparar mi postulación</Link><a href={job.sourceUrl} target="_blank" rel="noopener noreferrer" className={styles.buttonDark}>Ir directo a {job.company}</a><div className={styles.sourceNotice}><b>Fuente:</b> {job.source}<br/><b>Revisada:</b> {job.checkedAt}<br/>No existe afiliación implícita con la empresa. La oferta puede cambiar o cerrar en origen.</div></aside></div><PlatformFooter/><MobileNav active="empleos"/></main>}
